client/src/main/java/com/alibaba/nacos/client/naming/net/NamingProxy.java
There is a try catch block in`getServerListFromEndpoint` method,  it'll return null if any exception happens , which will raise a unexpected NPE
Using `CollectionUtils.isEmpty` to check if server list is null or empty
=> Fix potential NPE

naming/src/main/java/com/alibaba/nacos/naming/controllers/InstanceController.java
Fix #219
PUT /instance should use param key "useIPPort4Check" instead of "userIPPort4Check"
Fix the bug when call PUT /instance ， it will not become effective if chage the value of “userIPPort4Check“ in the Cluster
=> PUT /instance should use param key "useIPPort4Check" instead of "userIPPort4Check"

distribution/bin/startup.cmd
There is a Bug in Nacos Server Folder ，Bin directory ，startup.cmd File,
if not ""%2"" == "cluster" (
)
if you run startup.cmd -m cluster can’t startup with cluster mode，
if not "%2" == "cluster" (
)
run startup.cmd -m cluster Ok，you can running in cluster mode
=> Hotfix 672

client/src/main/java/com/alibaba/nacos/client/naming/beat/BeatReactor.java
Fix https://github.com/alibaba/nacos/issues/768.
* Use `schedule(...)` to start `BeatProcessor` task instead of `scheduleAtFixedRate(...)`
* Schedule `BeatProcessor` itself with a delay of `clientBeatInterval` at the end of task.
Client beat interval change to the value that returned by server.
=> [ISSUE #768] Fix: client beat interval is not controlled by server.

console/src/main/resources/META-INF/nacos-default.properties, distribution/conf/application.properties, naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/DistroConsistencyServiceImpl.java, naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/TaskDispatcher.java, naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/raft/RaftConsistencyServiceImpl.java, naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/raft/RaftCore.java, naming/src/main/java/com/alibaba/nacos/naming/controllers/InstanceController.java, naming/src/main/java/com/alibaba/nacos/naming/core/Instances.java, naming/src/main/java/com/alibaba/nacos/naming/core/ServiceManager.java, naming/src/main/java/com/alibaba/nacos/naming/healthcheck/HealthCheckTask.java, naming/src/main/java/com/alibaba/nacos/naming/misc/HttpClient.java, naming/src/main/java/com/alibaba/nacos/naming/misc/NamingProxy.java, naming/src/main/java/com/alibaba/nacos/naming/web/DistroFilter.java, naming/src/main/resources/application.properties, test/src/test/resources/application.properties
=> Feature dns

config/src/main/java/com/alibaba/nacos/config/server/service/dump/DumpService.java
历史配置文件保留时间改成可配置
DumpService 增加 retentionDays 字段，对应配置项为 retention.days
=> [ISSUE #1118] 历史配置文件保留天数，可配置

distribution/bin/startup.cmd
windows 脚本支持指定 function_mode：
startup.cmd -m cluster -f config
=> Windows script cannot specify FUNCTION_MODE #1148

naming/src/main/java/com/alibaba/nacos/naming/controllers/ServiceController.java, naming/src/main/java/com/alibaba/nacos/naming/core/SubscribeManager.java, naming/src/main/java/com/alibaba/nacos/naming/pojo/Subscriber.java, naming/src/main/java/com/alibaba/nacos/naming/pojo/Subscribers.java, naming/src/main/java/com/alibaba/nacos/naming/push/PushService.java, naming/src/test/java/com/alibaba/nacos/naming/core/SubscribeManagerTest.java, naming/src/test/java/com/alibaba/nacos/naming/pojo/SubscriberTest.java
get the subscriber info by namespaceId、serviceName and aggregation
Add an interface call in Pushservice to get subscription information from pushClient
Add aggregation judgment to control whether data is single-machine acquisition or cluster acquisition
=> Feature get subscribers

console/src/main/resources/application.properties
Issue  #1753 
In the Spring Boot 2.x, remove `server.contextPath`
nacos-console remove `server.contextPath`
nacos-console remove `server.contextPath`
=> [ISSUE #1753] Remove [nacos-console] server.contextPath

client/src/main/java/com/alibaba/nacos/client/naming/beat/BeatReactor.java
fix #1733
stop the existing beatInfo when add a new one for the same instance with same serviceName, ip and port.
XXXX
* [√ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [√ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ √] Write a pull request description that is detailed enough to …
=> ISSUE #1733

api/src/main/java/com/alibaba/nacos/api/config/listener/AbstractSharedListener.java, client/src/main/java/com/alibaba/nacos/client/config/common/GroupKey.java, config/src/main/java/com/alibaba/nacos/config/server/model/app/ApplicationInfo.java, config/src/main/java/com/alibaba/nacos/config/server/service/AggrWhitelist.java, config/src/main/java/com/alibaba/nacos/config/server/service/LocalDataSourceServiceImpl.java, config/src/main/java/com/alibaba/nacos/config/server/utils/GroupKey.java, config/src/main/java/com/alibaba/nacos/config/server/utils/MD5.java, config/src/main/java/com/alibaba/nacos/config/server/utils/RegexParser.java, config/src/main/java/com/alibaba/nacos/config/server/utils/TimeUtils.java, config/src/main/java/com/alibaba/nacos/config/server/utils/TimeoutUtils.java, config/src/main/java/com/alibaba/nacos/config/server/utils/UrlAnalysisUtils.java, core/src/main/java/com/alibaba/nacos/core/utils/SystemUtils.java, test/src/test/java/com/alibaba/nacos/test/naming/RandomUtils.java
Modifiers should be declared in the correct order;
Map init 设置大小
XX
=> style: Modifiers should be declared in the correct order;Map init 设置大小

naming/src/main/java/com/alibaba/nacos/naming/controllers/OperatorController.java, naming/src/main/java/com/alibaba/nacos/naming/core/ServiceManager.java, naming/src/main/java/com/alibaba/nacos/naming/misc/NamingProxy.java
Fixed cluster page show not consistency bug
change implementation for fixed bug
Ok
=> [ISSUE#1602] Fixed cluster page show bug

config/src/test/java/com/alibaba/nacos/config/server/utils/GroupKeyTest.java
I've analysed your codebase and noticed that `com.alibaba.nacos.config.server.utils.GroupKey` is not fully tested.
I've written some tests for the methods in this class with the help of [Diffblue Cover](https://www.diffblue.com/opensource).
Hopefully, these tests will help you detect any regressions caused by future code changes. If you would find it useful to have additional tests written for this repository, I would be more than happy to look at other classes that you consider important in a subsequent PR
=> Add unit tests for com.alibaba.nacos.config.server.utils.GroupKey

console/src/main/resources/static/console-fe/src/pages/ConfigurationManagement/NewConfig/NewConfig.js
fix bug #1775
When I read the source code, I found that this problem caused by these two inconsistencies:[NewConfig.js](https://github.com/alibaba/nacos/blob/0808d0cc397c0fc6a48240639aa943365a91dec7/console/src/main/resources/static/console-fe/src/pages/ConfigurationManagement/NewConfig/NewConfig.js#L417) and [NewConfigEditor.js](https://github.com/alibaba/nacos/blob/0808d0cc397c0fc6a48240639aa943365a91dec7/console/src/main/resources/static/console-fe/src/pages/ConfigurationManagement/ConfigEditor/NewConfigEditor.js#L49).
so I commit this pull request~
=> fix bug #1775

distribution/bin/startup.cmd
当我更新到nacos 1.1.3之后，在windows平台中运行startup.cmd时，nacos并未正常启动，它抛出了一个Error：Unable access jarfile的异常，我查看了startup.cmd脚本，发现在29行处 set SERVER时带上双引号，而在JAVA_OPT赋值时最终赋值成%BASE_DIR%\target"nacos-server".jar。
我修改了/distribution/bin/startup.cmd脚本
=> 运行startup.cmd发生的Error：Unable access jarfile

naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/raft/RaftCore.java
fix #1994 
make RequestVote RPC handler in nacos(com.alibaba.nacos.naming.consistency.persistent.raft.RaftCore#receivedVote) thread-safe.
XXXXX
add "synchronized" to com.alibaba.nacos.naming.consistency.persistent.raft.RaftCore#receivedVote.
=> make RequestVote RPC handler thread-safe

api/src/main/java/com/alibaba/nacos/api/naming/utils/NamingUtils.java
Modify the string splicing method of com.alibaba.nacos.api.naming.utils.NamingUtils.getGroupedName(String serviceName, String groupName).
Because com.alibaba.nacos.client.utils.stringutils has been marked @ deprecated, otherwise public splicing methods can be proposed
=> Modify the string splicing method of getgroupedname()

client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java
fix issue #1723 ，#2056
In order to prevent the server from handling the delay of the client's long task, increase the client's read timeout to avoid this problem.
(为了防止服务器端处理客户端长的任务出现延迟情况，调大客户端的读取超时时间，避免出现此问题的出现)
XXXX
=> refactor(client/config): increase the client's read timeout

naming/src/main/java/com/alibaba/nacos/naming/misc/GlobalConfig.java
将 taskDispatchPeriod 的注解上的默认值与代码设置的默认值统一
Fixs [#2370](https://github.com/alibaba/nacos/issues/2370)
taskDispatchPeriod 的默认值设置为 200
=> 统一 taskDispatchPeriod 的默认值

naming/src/main/java/com/alibaba/nacos/naming/push/PushService.java
delete duplicate code and fix log error
delete duplicate code and fix log error
delete duplicate code and fix log error
=> delete duplicate code and fix log error

client/src/main/java/com/alibaba/nacos/client/naming/net/NamingProxy.java
ref: https://github.com/alibaba/nacos/issues/2527
encoding the body of beat to avoid the server incorrect parse；
such as this beat：
beat={"cluster":"DEFAULT","ip":"30.5.125.57","metadata":{"dubbo.metadata-service.urls":"[ \"dubbo://30.128.116.47:20880/com.alibaba.cloud.dubbo.service.DubboMetadataService?anyhost=true&application=spring-cloud-alibaba-dubbo-server&bind.ip=30.128.116.47&bind.port=20880&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&group=spring-cloud-alibaba-dubbo-server&interface=com.alibaba.cloud.dubbo.service.DubboMetadataService&methods=getAllServiceKeys,getServiceRestMetadata,getExportedURLs,getAllExportedURLs&pid=2362&qos.enable=false&release=2.7.4.1&revision=1.0.0&side=provider&timestamp=1585139980414&version=1.0.0\" …
=> fix: https://github.com/alibaba/nacos/issues/2527

client/src/main/java/com/alibaba/nacos/client/naming/net/HttpClient.java
fix issues #2577 
rename the variable name from `TIME_OUT_MILLIS` to `READ_TIME_OUT_MILLIS`, and set the key to `com.alibaba.nacos.client.naming.rtimeout`
=> [ISSUE#2577] Fix naming client http read timeout and connect timeout properties

core/src/main/java/com/alibaba/nacos/core/code/ControllerMethodsCache.java
#2755
ControllerMethodsCache中    
public Method getMethod(String httpMethod, String path) {
String key = httpMethod + "-->" + path.replace(“/nacos”, "");
return methods.get(key);
}
这里用于过滤出api，但是replace的target是写死的“/nacos”，当修改了配置文件的contextPath后，使用自定义的根路径时，此处会无法正常过滤出api，造成后续DistroFilter无法获取到指定Method，抛出NoSuchMethodException。
此处将replace的target修改为动态获取到的contextPath,即可解决该问题。
=> [ISSUE #2755]解决修改contextPath后出现no such api异常

naming/src/main/java/com/alibaba/nacos/naming/misc/ServiceStatusSynchronizer.java
fix issues #2690 
Considering that the map has only one parameter，so:
choose more appropriate initialCapacity：Change from 10 to 1
=> hashMap constructor : choose more appropriate initialCapacity

api/src/main/java/com/alibaba/nacos/api/exception/NacosDeserializationException.java, api/src/main/java/com/alibaba/nacos/api/exception/NacosSerializationException.java, api/src/main/java/com/alibaba/nacos/api/exception/runtime/NacosDeserializationException.java, api/src/main/java/com/alibaba/nacos/api/exception/runtime/NacosRuntimeException.java, api/src/main/java/com/alibaba/nacos/api/exception/runtime/NacosSerializationException.java, api/src/main/java/com/alibaba/nacos/api/naming/pojo/Instance.java, api/src/main/java/com/alibaba/nacos/api/naming/pojo/ListView.java, api/src/main/java/com/alibaba/nacos/api/naming/pojo/ServiceInfo.java, api/src/test/java/com/alibaba/nacos/api/annotation/NacosPropertiesTest.java, api/src/test/java/com/alibaba/nacos/api/naming/pojo/ServiceInfoTest.java, client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingService.java, client/src/main/java/com/alibaba/nacos/client/naming/backups/FailoverReactor.java, client/src/main/java/com/alibaba/nacos/client/naming/beat/BeatInfo.java, client/src/main/java/com/alibaba/nacos/client/naming/beat/BeatReactor.java, client/src/main/java/com/alibaba/nacos/client/naming/cache/DiskCache.java, client/src/main/java/com/alibaba/nacos/client/naming/core/HostReactor.java, client/src/main/java/com/alibaba/nacos/client/naming/core/PushReceiver.java, client/src/main/java/com/alibaba/nacos/client/naming/net/NamingProxy.java, client/src/main/java/com/alibaba/nacos/client/security/SecurityProxy.java, client/src/test/java/com/alibaba/nacos/client/naming/cache/DiskCacheTest.java, client/src/test/java/com/alibaba/nacos/client/naming/core/HostReactorTest.java, client/src/test/java/com/alibaba/nacos/client/security/SecurityProxyTest.java, common/src/main/java/com/alibaba/nacos/common/utils/JacksonUtils.java, naming/src/main/java/com/alibaba/nacos/naming/core/Instance.java
For #2842 .
Replace Fastjson with Jackson.
- Handle serialization exception in JacksonUtils
- Replace all fastjson with jackson in nacos-api
- Replace fastjson with jackson for nacos-client
=> [ISSUE #2842]Replace Fastjson with Jackson for nacos-api and nacos-client

naming/src/main/java/com/alibaba/nacos/naming/controllers/RaftController.java, naming/src/main/java/com/alibaba/nacos/naming/controllers/ServiceController.java, naming/src/main/java/com/alibaba/nacos/naming/core/Cluster.java, naming/src/test/java/com/alibaba/nacos/naming/core/ClusterTest.java
For #2842 .
Fix serverStatus api 500 error after replaced fastjson with jackson.
XXXX
=> [ISSUE #2842] Fix serverStatus api jackson error

naming/src/main/java/com/alibaba/nacos/naming/controllers/DistroController.java, naming/src/main/java/com/alibaba/nacos/naming/misc/HttpClient.java, naming/src/main/java/com/alibaba/nacos/naming/web/FilterBase.java, test/src/test/java/com/alibaba/nacos/test/naming/NamingProxy_ITCase.java
HttpCLient uses ByteArrayEntity when sync data
=> HttpCLient uses ByteArrayEntity when sync data

common/src/main/java/com/alibaba/nacos/common/utils/CollectionUtils.java, config/src/main/java/com/alibaba/nacos/config/server/service/datasource/ExternalDataSourceProperties.java, config/src/main/java/com/alibaba/nacos/config/server/service/datasource/ExternalDataSourceServiceImpl.java, config/src/test/java/com/alibaba/nacos/config/server/service/datasource/ExternalDataSourcePropertiesTest.java, distribution/bin/startup.cmd, distribution/bin/startup.sh, pom.xml
Upgrade the database driver version of Mysql to 8
1. Upgrade the database driver version of Mysql to 8
2. Optimize data source configuration code
#3036 
#2993
#2676  
#1868 
1. Upgrade the database driver version of Mysql to 8
2. Optimize data source configuration code
=> Upgrade the database driver version of Mysql to 8 # 3036 #2993 #1868

client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingMaintainService.java, client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingService.java, client/src/main/java/com/alibaba/nacos/client/utils/ValidatorUtils.java, client/src/test/java/com/alibaba/nacos/client/utils/ValidatorUtilsTest.java, common/src/main/java/com/alibaba/nacos/common/utils/StringUtils.java
=> [#3063] fixed parameter validation boundary problem

naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/raft/RaftCore.java
=> [ISSUE #2810] don't send beat when standalone model

naming/src/main/java/com/alibaba/nacos/naming/consistency/ConsistencyService.java, naming/src/main/java/com/alibaba/nacos/naming/consistency/DelegateConsistencyServiceImpl.java, naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/DistroConsistencyServiceImpl.java, naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/raft/RaftConsistencyServiceImpl.java, naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/raft/RaftCore.java, naming/src/main/java/com/alibaba/nacos/naming/controllers/InstanceController.java, naming/src/main/java/com/alibaba/nacos/naming/core/Cluster.java, naming/src/main/java/com/alibaba/nacos/naming/core/ServiceManager.java
=> Method name optimization

common/src/main/java/com/alibaba/nacos/common/NotThreadSafe.java, common/src/main/java/com/alibaba/nacos/common/notify/DefaultPublisher.java, common/src/main/java/com/alibaba/nacos/common/notify/Event.java, common/src/main/java/com/alibaba/nacos/common/notify/EventPublisher.java, common/src/main/java/com/alibaba/nacos/common/notify/NotifyCenter.java, common/src/main/java/com/alibaba/nacos/common/notify/SlowEvent.java, common/src/main/java/com/alibaba/nacos/common/notify/listener/SmartSubscriber.java, common/src/main/java/com/alibaba/nacos/common/notify/listener/Subscriber.java, common/src/main/java/com/alibaba/nacos/common/utils/BiFunction.java, common/src/main/java/com/alibaba/nacos/common/utils/ClassUtils.java, common/src/main/java/com/alibaba/nacos/common/utils/MapUtils.java
Sink the Notify implementation into common module and optimize some parts
Sink the Notify implementation into common module and optimize some parts.
And this pr is one part of another bigger pr.The link is #2859.
XXXX
=> [#3117]Just Sink the Notify implementation into common module and optimize some parts

client/src/main/java/com/alibaba/nacos/client/naming/net/HttpClient.java, client/src/main/java/com/alibaba/nacos/client/naming/net/NamingHttpClientManager.java, client/src/main/java/com/alibaba/nacos/client/naming/net/NamingProxy.java, client/src/main/java/com/alibaba/nacos/client/security/SecurityProxy.java, common/src/main/java/com/alibaba/nacos/common/http/BaseHttpMethod.java, common/src/main/java/com/alibaba/nacos/common/http/HttpClientBeanHolder.java, common/src/main/java/com/alibaba/nacos/common/http/client/HttpClientResponse.java, common/src/main/java/com/alibaba/nacos/common/http/client/NacosAsyncRestTemplate.java, common/src/main/java/com/alibaba/nacos/common/http/client/NacosRestTemplate.java, common/src/main/java/com/alibaba/nacos/common/http/handler/ResponseHandler.java, test/src/test/java/com/alibaba/nacos/test/common/NacosAsyncRestTemplate_ITCase.java, test/src/test/java/com/alibaba/nacos/test/common/NacosRestTemplate_ITCase.java, test/src/test/java/com/alibaba/nacos/test/naming/AutoDeregisterInstance_ITCase.java, test/src/test/java/com/alibaba/nacos/test/naming/NamingBase.java
nacos-client module replace http client
fix: #3140 refer: #2858
- Unified use of httpclient
- use `nacosRestTemplate` replace `nacos-client` module `httpClient` 
XXXX
=> [ISSUE #3140]nacos-client module replace http client

api/src/main/java/com/alibaba/nacos/api/exception/NacosException.java, api/src/main/java/com/alibaba/nacos/api/naming/pojo/Instance.java, api/src/main/java/com/alibaba/nacos/api/naming/pojo/healthcheck/impl/Http.java, api/src/main/java/com/alibaba/nacos/api/naming/pojo/healthcheck/impl/Mysql.java, api/src/main/java/com/alibaba/nacos/api/naming/utils/NamingUtils.java, api/src/main/java/com/alibaba/nacos/api/utils/StringUtils.java, api/src/test/java/com/alibaba/nacos/api/naming/pojo/ServiceInfoTest.java, api/src/test/java/com/alibaba/nacos/api/naming/pojo/healthcheck/AbstractHealthCheckerTest.java, api/src/test/java/com/alibaba/nacos/api/naming/pojo/healthcheck/HealthCheckerFactoryTest.java, api/src/test/java/com/alibaba/nacos/api/naming/pojo/healthcheck/impl/MysqlTest.java
=> replace lang3 in api

naming/src/main/java/com/alibaba/nacos/naming/consistency/KeyBuilder.java, naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/raft/RaftStore.java, naming/src/main/java/com/alibaba/nacos/naming/misc/SwitchManager.java, naming/src/main/java/com/alibaba/nacos/naming/misc/UtilsAndCommons.java
=> [ISSUE #3160]fix compatibility issue when reading cache files with suffix ".datum"

core/src/main/java/com/alibaba/nacos/core/cluster/MemberMetaDataConstants.java, core/src/main/java/com/alibaba/nacos/core/cluster/MemberUtils.java, core/src/main/java/com/alibaba/nacos/core/cluster/ServerMemberManager.java, naming/src/main/java/com/alibaba/nacos/naming/controllers/CatalogController.java, naming/src/main/java/com/alibaba/nacos/naming/core/DistroMapper.java, pom.xml
After #3168 merged, much health member list changed log. This PR fix this problem.
=> Hotfix frequent member change logs after #3168

console/src/main/java/com/alibaba/nacos/console/security/nacos/NacosAuthConfig.java
NacosAuthConfig类上的@EnableGlobalMethodSecurity注解已经包含了@Configuration，冗余又写了一次@Configuration
=> 移除nacos/console包下NacosAuthConfig类上冗余注解@Configuration

istio/src/main/java/com/alibaba/nacos/istio/mcp/NacosMcpService.java, naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/DistroConsistencyServiceImpl.java, naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/raft/RaftCore.java, naming/src/main/java/com/alibaba/nacos/naming/core/ServiceManager.java, naming/src/main/java/com/alibaba/nacos/naming/healthcheck/HealthCheckCommon.java, naming/src/main/java/com/alibaba/nacos/naming/healthcheck/HealthCheckReactor.java, naming/src/main/java/com/alibaba/nacos/naming/healthcheck/MysqlHealthCheckProcessor.java, naming/src/main/java/com/alibaba/nacos/naming/healthcheck/TcpSuperSenseProcessor.java, naming/src/main/java/com/alibaba/nacos/naming/misc/GlobalExecutor.java, naming/src/main/java/com/alibaba/nacos/naming/misc/UtilsAndCommons.java, naming/src/main/java/com/alibaba/nacos/naming/monitor/PerformanceLoggerThread.java, naming/src/main/java/com/alibaba/nacos/naming/push/PushService.java
#2856 
1. Unified naming module thread pool usage
XXXX
=> [ISSUE #2856]Adjust the use of thread pools (naming module)

console/pom.xml, console/src/main/java/com/alibaba/nacos/Nacos.java, console/src/main/java/com/alibaba/nacos/console/config/ConsoleConfig.java, console/src/main/java/com/alibaba/nacos/console/controller/HealthController.java, console/src/main/java/com/alibaba/nacos/console/controller/NamespaceController.java, console/src/main/java/com/alibaba/nacos/console/controller/PermissionController.java, console/src/main/java/com/alibaba/nacos/console/controller/RoleController.java, console/src/main/java/com/alibaba/nacos/console/controller/ServerStateController.java, console/src/main/java/com/alibaba/nacos/console/controller/UserController.java, console/src/main/java/com/alibaba/nacos/console/exception/ConsoleExceptionHandler.java, console/src/main/java/com/alibaba/nacos/console/filter/JwtAuthenticationTokenFilter.java, console/src/main/java/com/alibaba/nacos/console/model/Namespace.java, console/src/main/java/com/alibaba/nacos/console/model/NamespaceAllInfo.java, console/src/main/java/com/alibaba/nacos/console/security/nacos/CustomAuthenticationProvider.java, console/src/main/java/com/alibaba/nacos/console/security/nacos/JwtAuthenticationEntryPoint.java, console/src/main/java/com/alibaba/nacos/console/security/nacos/JwtTokenManager.java, console/src/main/java/com/alibaba/nacos/console/security/nacos/NacosAuthConfig.java, console/src/main/java/com/alibaba/nacos/console/security/nacos/NacosAuthManager.java, console/src/main/java/com/alibaba/nacos/console/security/nacos/roles/NacosRoleServiceImpl.java, console/src/main/java/com/alibaba/nacos/console/security/nacos/users/NacosUser.java, console/src/main/java/com/alibaba/nacos/console/security/nacos/users/NacosUserDetails.java, console/src/main/java/com/alibaba/nacos/console/security/nacos/users/NacosUserDetailsServiceImpl.java, console/src/main/java/com/alibaba/nacos/console/utils/JwtTokenUtils.java, console/src/main/java/com/alibaba/nacos/console/utils/PasswordEncoderUtil.java, console/src/test/java/com/alibaba/nacos/console/controller/HealthControllerTest.java, console/src/test/java/com/alibaba/nacos/console/controller/UserControllerTest.java
For #2992 .
Reformat nacos-console module with new code style and fix checkstyle.
=> [ISSUE #2992] Use new code style for nacos-console module.

client/pom.xml, pom.xml
Resolved [#3223](https://github.com/alibaba/nacos/issues/3223)
Upgrade log4j to security version
XXXX
=> [ISSUE #3223] Upgrade log4j to security version

address/pom.xml, address/src/main/java/com/alibaba/nacos/address/AddressServer.java, address/src/main/java/com/alibaba/nacos/address/component/AddressServerGeneratorManager.java, address/src/main/java/com/alibaba/nacos/address/component/AddressServerManager.java, address/src/main/java/com/alibaba/nacos/address/constant/AddressServerConstants.java, address/src/main/java/com/alibaba/nacos/address/controller/AddressServerClusterController.java, address/src/main/java/com/alibaba/nacos/address/controller/ServerListController.java, address/src/main/java/com/alibaba/nacos/address/misc/Loggers.java, address/src/main/java/com/alibaba/nacos/address/util/AddressServerParamCheckUtil.java, address/src/main/resources/META-INF/logback/nacos-included.xml, address/src/main/resources/application.properties, address/src/test/java/com/alibaba/nacos/address/AddressServerControllerTests.java, address/src/test/java/com/alibaba/nacos/address/ParamCheckUtilTests.java, address/src/test/java/com/alibaba/nacos/address/SimpleHttpTestUtils.java
For #2992 
Use new code style for nacos-address module.
XXXX
=> [ISSUE #2992]  Use new code style for nacos-address module.

config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedStoragePersistServiceImpl.java, config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java
fix #3235 
`String.format("select 1 from %s order by id limit 1", tableName);`
or
`String.format("select 1 from %s where id = 1", tableName);`
Both of these SQL statements are very fast, and can be viewed through `explain`
=> optimize isExistTable function 

client/pom.xml, client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingService.java, client/src/main/java/com/alibaba/nacos/client/naming/beat/BeatReactor.java, client/src/main/java/com/alibaba/nacos/client/naming/net/NamingProxy.java, client/src/main/java/com/alibaba/nacos/client/security/SecurityProxy.java, client/src/test/java/com/alibaba/nacos/client/ConfigTest.java, client/src/test/java/com/alibaba/nacos/client/NamingTest.java
When 1.3.1-BETA SDK register instance, there will be double register a `null` service.
Reason is from #3037.
The PR change the logic of create beatinfo, which get service name from instance, if users input instance without service name. It will double register a null name service.
=> Hotfix double register null service and beat info invalid problem

config/src/main/java/com/alibaba/nacos/config/server/monitor/MemoryMonitor.java, config/src/main/java/com/alibaba/nacos/config/server/monitor/MetricsMonitor.java, config/src/main/java/com/alibaba/nacos/config/server/monitor/NotifyTaskQueueMonitorTask.java, config/src/main/java/com/alibaba/nacos/config/server/monitor/PrintGetConfigResponeTask.java, config/src/main/java/com/alibaba/nacos/config/server/monitor/PrintMemoryTask.java, config/src/main/java/com/alibaba/nacos/config/server/monitor/ResponseMonitor.java, config/src/main/java/com/alibaba/nacos/config/server/result/ResultBuilder.java, config/src/main/java/com/alibaba/nacos/config/server/result/code/ResultCodeEnum.java, config/src/main/java/com/alibaba/nacos/config/server/result/core/IResultCode.java, config/src/main/java/com/alibaba/nacos/config/server/service/AggrWhitelist.java, config/src/main/java/com/alibaba/nacos/config/server/service/ClientIpWhiteList.java, config/src/main/java/com/alibaba/nacos/config/server/service/ClientRecord.java, config/src/main/java/com/alibaba/nacos/config/server/service/ClientTrackService.java, config/src/main/java/com/alibaba/nacos/config/server/service/ConfigCacheService.java, config/src/main/java/com/alibaba/nacos/config/server/service/ConfigChangePublisher.java, config/src/main/java/com/alibaba/nacos/config/server/service/ConfigSubService.java, config/src/main/java/com/alibaba/nacos/config/server/service/LongPollingService.java, config/src/main/java/com/alibaba/nacos/config/server/service/SwitchService.java
Resolve the issues of codestyle of nacos-config module for some package parts below.
Package:
(1)com.alibaba.nacos.config.server.monitor;
(2)com.alibaba.nacos.config.server.result;
(3)com.alibaba.nacos.config.server.result.code;
(4)com.alibaba.nacos.config.server.result.core;
(5)com.alibaba.nacos.config.server.service;
XX
XXXX
=> Resolve the issues of codestyle of nacos-config module for phase5.

api/src/main/java/com/alibaba/nacos/api/naming/pojo/healthcheck/HealthCheckerFactory.java
1. Replace RuntimeException caused by HealthCheckerFactory with Nacos serialization exception
Because we will use nacos as the first choice for the registration center in the future development plan, I am starting to learn nacos and try to learn its source code design. When I saw two TODOs, I changed it smoothly. Nacos is very good. Want to contribute to it
nacos-api:
- com.alibaba.nacos.api.naming.pojo.healthcheck.HealthCheckerFactory#deserialize
- com.alibaba.nacos.api.naming.pojo.healthcheck.HealthCheckerFactory#serialize
=> [Resolve TODO] Replace RuntimeException caused by HealthCheckerFactory with Nacos serialization exception

config/src/main/java/com/alibaba/nacos/config/server/service/datasource/ExternalDataSourceProperties.java, config/src/test/java/com/alibaba/nacos/config/server/service/datasource/ExternalDataSourcePropertiesTest.java
[ISSUE#3300](https://github.com/alibaba/nacos/issues/3300)
Optimize the default "minIdle"" of HikariPool set by naocs.
优化nacos默认设置的HiKariPool连接池的最小空闲数。
=> [ISSUE#3300] Optimize the default "minIdle"" of HikariPool set by naocs

cmdb/src/main/java/com/alibaba/nacos/cmdb/memory/CmdbProvider.java, cmdb/src/main/java/com/alibaba/nacos/cmdb/utils/CmdbExecutor.java, cmdb/src/main/java/com/alibaba/nacos/cmdb/utils/UtilsAndCommons.java, common/src/main/java/com/alibaba/nacos/common/executor/ExecutorFactory.java, config/src/main/java/com/alibaba/nacos/config/server/monitor/MemoryMonitor.java, config/src/main/java/com/alibaba/nacos/config/server/monitor/NotifyTaskQueueMonitorTask.java, config/src/main/java/com/alibaba/nacos/config/server/service/ConfigSubService.java, config/src/main/java/com/alibaba/nacos/config/server/service/LongPollingService.java, config/src/main/java/com/alibaba/nacos/config/server/service/capacity/CapacityService.java, config/src/main/java/com/alibaba/nacos/config/server/service/datasource/ExternalDataSourceServiceImpl.java, config/src/main/java/com/alibaba/nacos/config/server/service/dump/DumpService.java, config/src/main/java/com/alibaba/nacos/config/server/service/notify/AsyncNotifyService.java, config/src/main/java/com/alibaba/nacos/config/server/service/notify/NotifySingleService.java, config/src/main/java/com/alibaba/nacos/config/server/utils/ConfigExecutor.java, config/src/main/java/com/alibaba/nacos/config/server/utils/SimpleFlowData.java, config/src/main/java/com/alibaba/nacos/config/server/utils/SimpleIpFlowData.java
#2856
1. Unified config module thread pool usage
2. Unified cmdb module thread pool usage
> Consider that SimpleIPFlowData and SimpleIPFlowData are not spring beans and are not used. Not moved to ConfigExecutor class management
XXXX
=> [ISSUE #2856]Adjust the use of thread pools (config module)

client/src/main/java/com/alibaba/nacos/client/naming/net/NamingHttpClientManager.java, common/src/main/java/com/alibaba/nacos/common/http/AbstractHttpClientFactory.java, common/src/main/java/com/alibaba/nacos/common/http/DefaultHttpClientFactory.java, common/src/main/java/com/alibaba/nacos/common/http/HttpClientBeanHolder.java, common/src/main/java/com/alibaba/nacos/common/http/client/AbstractNacosRestTemplate.java, common/src/main/java/com/alibaba/nacos/common/http/client/DefaultHttpClientRequest.java, common/src/main/java/com/alibaba/nacos/common/http/client/NacosAsyncRestTemplate.java, common/src/main/java/com/alibaba/nacos/common/http/client/NacosRestTemplate.java, test/src/test/java/com/alibaba/nacos/test/common/NacosAsyncRestTemplate_ITCase.java, test/src/test/java/com/alibaba/nacos/test/common/NacosRestTemplate_ITCase.java, test/src/test/java/com/alibaba/nacos/test/common/NacosRestTemplate_Interceptors_ITCase.java
XXXXX
Provide abstract assignLogger method in AbstractHttpClientFactory, and specify Logger by implementing this method
XXXX
=> [ISSUE#3311] Add specified Logger when constructing nacos resttemplate

common/src/main/java/com/alibaba/nacos/common/http/AbstractHttpClientFactory.java, common/src/main/java/com/alibaba/nacos/common/http/HttpClientBeanHolder.java, common/src/main/java/com/alibaba/nacos/common/http/client/HttpClientResponse.java, common/src/main/java/com/alibaba/nacos/common/http/client/JdkHttpClientRequest.java, common/src/main/java/com/alibaba/nacos/common/http/client/JdkHttpClientResponse.java
fix: #3317 
implement `JdkHttpClientRequest` and `JdkHttpClientResponse` replace `DefaultHttpClientRequest` and `DefaultClientHttpResponse`
XXXX
=> [ISSUE##3317]Change the http client implementation that nacos resttemplate depends on from apache to JDk

address/pom.xml, api/pom.xml, api/src/main/java/com/alibaba/nacos/api/naming/pojo/ServiceInfo.java, api/src/main/java/com/alibaba/nacos/api/naming/remote/NamingRemoteConstants.java, api/src/main/java/com/alibaba/nacos/api/naming/remote/request/InstanceRequest.java, api/src/main/java/com/alibaba/nacos/api/naming/remote/request/ServiceQueryRequest.java, api/src/main/java/com/alibaba/nacos/api/naming/remote/response/ServiceQueryResponse.java, api/src/main/java/com/alibaba/nacos/api/remote/ResponseRegistry.java, client/pom.xml, client/src/main/java/com/alibaba/nacos/client/naming/net/NamingGrpcClientProxy.java, cmdb/pom.xml, common/pom.xml, config/pom.xml, consistency/pom.xml, console/pom.xml, core/pom.xml, distribution/pom.xml, example/pom.xml, istio/pom.xml, naming/pom.xml, naming/src/main/java/com/alibaba/nacos/naming/remote/handler/InstanceRequestHandler.java, naming/src/main/java/com/alibaba/nacos/naming/remote/handler/ServiceQueryRequestHandler.java, pom.xml, test/pom.xml
Add naming support gRPC for query instance list and service info
=> Add naming support gRPC for query instance list and service info

api/src/main/java/com/alibaba/nacos/api/config/remote/request/ConfigChangeListenRequest.java, api/src/main/java/com/alibaba/nacos/api/config/remote/response/ConfigChangeListenResponse.java, api/src/main/java/com/alibaba/nacos/api/config/remote/response/ConfigChangeNotifyResponse.java, api/src/main/java/com/alibaba/nacos/api/config/remote/response/ConfigPubishResponse.java, api/src/main/java/com/alibaba/nacos/api/config/remote/response/ConfigQueryResponse.java, api/src/main/java/com/alibaba/nacos/api/config/remote/response/ConfigRemoveResponse.java, api/src/main/java/com/alibaba/nacos/api/naming/remote/response/InstanceResponse.java, api/src/main/java/com/alibaba/nacos/api/naming/remote/response/ServiceQueryResponse.java, api/src/main/java/com/alibaba/nacos/api/remote/ResponseRegistry.java, api/src/main/java/com/alibaba/nacos/api/remote/response/ConnectResetResponse.java, api/src/main/java/com/alibaba/nacos/api/remote/response/HeartBeatResponse.java, api/src/main/java/com/alibaba/nacos/api/remote/response/PlainBodyResponse.java, api/src/main/java/com/alibaba/nacos/api/remote/response/Response.java, api/src/main/java/com/alibaba/nacos/api/remote/response/UnKnowResponse.java, client/src/test/java/com/alibaba/nacos/client/ConfigTest.java, config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigChangeListenRequestHandler.java, core/src/main/java/com/alibaba/nacos/core/remote/HeartBeatRequestHandler.java, core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcUtils.java, distribution/conf/nacos-logback.xml, naming/src/main/java/com/alibaba/nacos/naming/remote/handler/InstanceRequestHandler.java
=> response model optimize

common/src/main/java/com/alibaba/nacos/common/notify/NotifyCenter.java, common/src/test/java/com/alibaba/nacos/common/notify/NotifyCenterTest.java
Fix no throw exception when publish event but no subsciber.
XX
XXXX
=> [ISSUE#3356]Fix no throw exception when publish event but no subsciber.

client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingMaintainService.java, client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingService.java, client/src/main/java/com/alibaba/nacos/client/naming/core/ServerListManager.java, client/src/main/java/com/alibaba/nacos/client/naming/remote/http/NamingHttpClientProxy.java, client/src/main/java/com/alibaba/nacos/client/naming/utils/NamingHttpUtil.java
For #3386
Extract server list maintain logic to ServerListManager
XXXX
=> [ISSUE #3386] Extract server list maintain logic to ServerListManager

api/src/main/java/com/alibaba/nacos/api/naming/pojo/Instance.java, naming/src/main/java/com/alibaba/nacos/naming/controllers/InstanceController.java
#3353
Adjust the value logic of clientBeatInterval
XXXX
=> [#3353]Adjust the value logic of clientBeatInterval

api/src/main/java/com/alibaba/nacos/api/config/remote/request/ConfigPublishRequest.java, client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java, client/src/main/java/com/alibaba/nacos/client/remote/RpcClient.java, client/src/main/java/com/alibaba/nacos/client/remote/grpc/GrpcClient.java, client/src/test/java/com/alibaba/nacos/client/ConfigTest.java, config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigPublishRequestHandler.java, core/src/main/java/com/alibaba/nacos/core/remote/ClientConnectionEventListenerRegistry.java, core/src/main/java/com/alibaba/nacos/core/remote/ConnectCoordinator.java, core/src/main/java/com/alibaba/nacos/core/remote/ConnectionManager.java, core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcServer.java
=> notify connect listeners on start up

common/src/main/java/com/alibaba/nacos/common/http/BaseHttpClient.java, common/src/main/java/com/alibaba/nacos/common/http/BaseHttpMethod.java, common/src/main/java/com/alibaba/nacos/common/http/HttpUtils.java, common/src/main/java/com/alibaba/nacos/common/http/client/request/DefaultHttpClientRequest.java
Since `HttpRequestBase` is an enum member attribute of `BaseHttpMethod`, when multiple threads call the init method at the same time, there will be thread safety issues.
Thereby affecting the http client request.
fix: #3366, #3314 
Remove the `HttpRequestBase` member attribute from the `BaseHttpMethod` enum, and return the instance directly through the init method
XXXX
=> Fix the thread safety problem of obtaining HttpRequestBase through BaseHttpMethod enumeration

console/src/main/resources/application.properties, core/src/main/java/com/alibaba/nacos/core/cluster/lookup/AddressServerMemberLookup.java, distribution/conf/application.properties, distribution/conf/application.properties.example
see #3509 
1. Use ApplicationUtils.getProperty () get variable
2. Synchronize the parameters in properties
3. After the change, get the priority system environment variable of the variable, then start the JVM (- D) - > properties property
=> [#3509] Fix address server mode cannot be obtained application.properties

client/src/test/java/com/alibaba/nacos/client/ConfigTest.java, common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClient.java, core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcConnection.java, core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcRequestHandlerReactor.java, core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcServer.java
=> connection event notification  of grpc server

api/src/main/java/com/alibaba/nacos/api/naming/pojo/ServiceInfo.java, client/src/main/java/com/alibaba/nacos/client/naming/core/HostReactor.java, naming/src/main/java/com/alibaba/nacos/naming/controllers/InstanceController.java
=> [ISSUE #3628] set naming client updateTask interval more flexible

naming/src/main/java/com/alibaba/nacos/naming/misc/HttpClient.java
Fix #3651 , 
Try to fix nacos server CLOSE_WAIT
=> [ISSUE #3651] Try to fix nacos server CLOSE_WAIT

common/src/main/java/com/alibaba/nacos/common/http/AbstractApacheHttpClientFactory.java, common/src/main/java/com/alibaba/nacos/common/http/AbstractHttpClientFactory.java, common/src/main/java/com/alibaba/nacos/common/http/BaseHttpMethod.java, common/src/main/java/com/alibaba/nacos/common/http/HttpComponentsHttpClientFactory.java, common/src/main/java/com/alibaba/nacos/common/http/client/NacosRestTemplate.java
for: #3712 
Add `AbstractApacheHttpClientFactory` class to support the use of apache http client.
XXXX
=> [ISSUE#3712] add apache http client factory

common/src/main/java/com/alibaba/nacos/common/notify/DefaultSharePublisher.java, common/src/test/java/com/alibaba/nacos/common/notify/NotifyCenterTest.java
Fix #3833 .
- Fix NullPointerException when no subscriber for slow event
=> [ISSUE#3833] Fix NullPointerException when no subscriber for slow event

naming/src/main/java/com/alibaba/nacos/naming/core/InstanceService.java, naming/src/main/java/com/alibaba/nacos/naming/core/SubscribeManager.java, naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/ConnectionBasedClientManager.java, naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/IpPortBasedClientManager.java, naming/src/main/java/com/alibaba/nacos/naming/misc/GlobalExecutor.java, naming/src/main/java/com/alibaba/nacos/naming/push/ClientPushService.java, naming/src/main/java/com/alibaba/nacos/naming/push/PushService.java, naming/src/main/java/com/alibaba/nacos/naming/push/v2/PushExecuteService.java, naming/src/main/java/com/alibaba/nacos/naming/push/v2/PushExecuteServiceDelegate.java, naming/src/main/java/com/alibaba/nacos/naming/push/v2/RpcPushExecuteServiceImpl.java, naming/src/main/java/com/alibaba/nacos/naming/push/v2/UdpPushExecuteServiceImpl.java
Add upd push for ip port client
- Add upd push for ip port client
- auto clean expire ip port client
XXXX
=> Add upd push for ip port client

common/src/main/java/com/alibaba/nacos/common/http/HttpUtils.java, common/src/main/java/com/alibaba/nacos/common/http/param/MediaType.java, common/src/test/java/com/alibaba/nacos/common/http/param/MediaTypeTest.java
Because MediaType has supplemented the character set at present, this causes apache http to be abnormal when initRequestEntity.
Error message : `java.lang.IllegalArgumentException: MIME type may not contain reserved characters`
Reason: When using the `org.apache.http.entity.ContentType#create(java.lang.String, java.lang.String) `method to pass in mimeType and charset, mimeType is not allowed to have a character set.
XXXX
=> Fix apache http exception due to the character set of Content-Type

naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/v2/DistroClientDataProcessor.java, naming/src/main/java/com/alibaba/nacos/naming/core/DistroMapper.java, naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperatorClientImpl.java, naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/ClientSyncDatumSnapshot.java, naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/ClientManager.java, naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/ClientManagerDelegate.java, naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/ConnectionBasedClientManager.java, naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/IpPortBasedClientManager.java, naming/src/main/java/com/alibaba/nacos/naming/web/DistroFilter.java, naming/src/main/java/com/alibaba/nacos/naming/web/DistroIpPortTagGenerator.java, naming/src/main/java/com/alibaba/nacos/naming/web/DistroServiceNameTagGenerator.java, naming/src/main/java/com/alibaba/nacos/naming/web/DistroTagGenerator.java, naming/src/main/java/com/alibaba/nacos/naming/web/DistroTagGeneratorImpl.java
=> Refactor distro filter to support route by ip port

client/src/main/java/com/alibaba/nacos/client/naming/core/PushReceiver.java
=> [ISSUE #3850] ignore socket exception when client destroy already

config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigController.java, config/src/main/java/com/alibaba/nacos/config/server/controller/HealthController.java, config/src/main/java/com/alibaba/nacos/config/server/model/app/ApplicationInfo.java, config/src/main/java/com/alibaba/nacos/config/server/service/dump/DumpService.java, config/src/main/java/com/alibaba/nacos/config/server/service/merge/MergeDatumService.java, config/src/main/java/com/alibaba/nacos/config/server/service/merge/MergeTaskProcessor.java, config/src/main/java/com/alibaba/nacos/config/server/service/notify/AsyncNotifyService.java, config/src/main/java/com/alibaba/nacos/config/server/service/notify/NotifyTaskProcessor.java, config/src/main/java/com/alibaba/nacos/config/server/service/trace/ConfigTraceService.java, core/src/main/java/com/alibaba/nacos/core/cluster/ServerMemberManager.java, core/src/main/java/com/alibaba/nacos/core/cluster/lookup/StandaloneMemberLookup.java, core/src/main/java/com/alibaba/nacos/core/code/StartingSpringApplicationRunListener.java, naming/src/main/java/com/alibaba/nacos/naming/misc/NetUtils.java, sys/src/main/java/com/alibaba/nacos/sys/utils/ApplicationUtils.java, sys/src/main/java/com/alibaba/nacos/sys/utils/InetUtils.java, test/src/test/java/com/alibaba/nacos/test/config/ConfigDerbyRaft_DITCase.java, test/src/test/java/com/alibaba/nacos/test/core/BaseClusterTest.java, test/src/test/java/com/alibaba/nacos/test/core/InetUtils_ITCase.java, test/src/test/java/com/alibaba/nacos/test/core/cluster/MemberLookup_ITCase.java
=> [ISSUE #3909] add domain's judgement

api/src/main/java/com/alibaba/nacos/api/naming/NamingMaintainService.java, client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingMaintainService.java, test/src/test/java/com/alibaba/nacos/test/naming/NamingMaintainService_ITCase.java
…mingMaintainService
fix #3576 
Added the 'shutdown()' method in interface 'NamingMaintainService' and the implementation 'NacosNamingMaintainService', and use the method in the unit tests.
XXXX
=> [ISSUE #3576] [Enhancement] Adding the destroy lifecycle method on NamingMaintainService

core/src/main/java/com/alibaba/nacos/core/utils/WebUtils.java
**purpose of the change**
For #3710
**Brief changelog**
Fix special characters cannot be used in Metadata
**Verifying this change**
- nacos-client uses special characters to register nacos verified
- openAPI uses special characters to register nacos verified
> RaftController
> OperationController
> ApiController
> CatalogController
> ClusterController
> InstanceController
> ServiceController
> HealthController
- Verified in the official environment
=> For #3710#, Fix special characters cannot be used in Metadata

config/src/main/java/com/alibaba/nacos/config/server/service/dump/DumpService.java, config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/DerbySnapshotOperation.java, core/src/main/java/com/alibaba/nacos/core/utils/TimerContext.java, naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/impl/NamingKvStorage.java, naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/impl/NamingSnapshotOperation.java, naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/raft/RaftCore.java
During upgrade to 1.4.0-SNAPSHOT,  old raft may get null datum from old leader.
The PR will hotfix this problem.
fix raft may get null datum from old leader during upgrade to 1.4.0
=> Develop fix jraft null datum

console/src/main/java/com/alibaba/nacos/console/config/ConsoleConfig.java
修正config相关接口返回时间时区-8的问题。例如获取配置历史列表查询以及历史配置详情等，接口中返回的(lastModifiedTime)最后修改时间字段比真正操作时间少8小时。
原因：spring转json的默认实现jackson中会根据时区去转换时间，而jackson的默认时区跟国内应该是相差8小时，所以在时间换算上自动减去了8小时。
相关链接：https://my.oschina.net/u/4391021/blog/3580942
添加spring.jackson.time-zone=Asia/Shanghai 配置
=> updates the default time zone for interface results

common/src/main/java/com/alibaba/nacos/common/utils/ArrayUtil.java, common/src/main/java/com/alibaba/nacos/common/utils/BooleanUtil.java, common/src/main/java/com/alibaba/nacos/common/utils/ConvertUtils.java, common/src/main/java/com/alibaba/nacos/common/utils/NumberUtil.java, common/src/main/java/com/alibaba/nacos/common/utils/RandomUtil.java, common/src/main/java/com/alibaba/nacos/common/utils/StringUtils.java
#3102 phase 1.
Create utils class to nacos-common, prepare to remove apache commons-lang dependency step by step.
XX
XXXX
=> [ISSUE #3102] Create utils class to nacos-common

core/pom.xml, sys/pom.xml
##What is the purpose of the change
add commons-lang3 dependency into core and sys.
XX
XXXX
=> [ISSUE #3102] add commons-lang3 dependency into core and sys

common/src/main/java/com/alibaba/nacos/common/http/AbstractApacheHttpClientFactory.java, common/src/main/java/com/alibaba/nacos/common/http/AbstractHttpClientFactory.java
fix: #4236 
Modify the `RequestContent` attribute `overwrite` to `true` to override the manually added `content-length` and `transfer-Encoding`.
XXXX
=> [ISSUE #4236] Add RequestContent and set attribute Overwrite to true to resolve the Apache Header Already Present problem

naming/src/main/java/com/alibaba/nacos/naming/controllers/InstanceController.java, naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperator.java, naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperatorClientImpl.java, naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperatorServiceImpl.java, naming/src/main/java/com/alibaba/nacos/naming/core/v2/index/ServiceStorage.java, naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/InstanceMetadataProcessor.java, naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/MetadataOperation.java, naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/NamingMetadataOperateService.java, naming/src/main/java/com/alibaba/nacos/naming/healthcheck/heartbeat/ClientBeatCheckTaskV2.java, naming/src/main/java/com/alibaba/nacos/naming/push/v2/task/PushExecuteTask.java, naming/src/main/java/com/alibaba/nacos/naming/utils/Constants.java, naming/src/main/java/com/alibaba/nacos/naming/utils/ServiceUtil.java
=> Support update instance metadata and sync by raft

naming/src/main/java/com/alibaba/nacos/naming/core/CatalogServiceV2Impl.java, naming/src/main/java/com/alibaba/nacos/naming/core/v2/ServiceManager.java, naming/src/main/java/com/alibaba/nacos/naming/core/v2/index/ServiceStorage.java, naming/src/main/java/com/alibaba/nacos/naming/remote/handler/ServiceListRequestHandler.java
=> Move namespace cache to ServiceManager

client/src/main/java/com/alibaba/nacos/client/config/http/ServerHttpAgent.java, client/src/main/java/com/alibaba/nacos/client/config/impl/ServerListManager.java, client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingMaintainService.java, client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingService.java, client/src/main/java/com/alibaba/nacos/client/naming/utils/InitUtils.java, client/src/main/java/com/alibaba/nacos/client/security/SecurityProxy.java, client/src/main/java/com/alibaba/nacos/client/utils/ContextPathUtil.java, client/src/test/java/com/alibaba/nacos/client/utils/ContextPathUtilTest.java, test/src/test/java/com/alibaba/nacos/test/config/ConfigAPI_CITCase.java, test/src/test/java/com/alibaba/nacos/test/config/ConfigAPI_With_RootContextPath_CITCase.java, test/src/test/java/com/alibaba/nacos/test/naming/DeregisterInstance_ITCase.java, test/src/test/java/com/alibaba/nacos/test/naming/DeregisterInstance_With_RootContextPath_ITCase.java, test/src/test/java/com/alibaba/nacos/test/naming/NamingBase.java, test/src/test/java/com/alibaba/nacos/test/naming/RegisterInstance_ITCase.java, test/src/test/java/com/alibaba/nacos/test/naming/RegisterInstance_With_RootContextPath_ITCase.java
#4181
Just use ContextPathUtil normalize ContextPath value on nacos-client
> Maybe we can unified handle the acquisition of client-side attribute values in later versions
=> [ISSUE-#4181]  Normalize ContextPath value in client-side

console-ui/src/pages/NameSpace/NameSpace.js
The old marginTop of this button is zero, so we need to fix it.
**Before fixing, it looks like:**
**After fixing, it looks beautiful than before:**
Update `mariginRight: 0` to `mariginRight: 20`
Open your browser and visit it.
=> The button '新建命名空间' misses marginRight on the page '命名空间'

api/src/test/java/com/alibaba/nacos/api/naming/pojo/healthcheck/HealthCheckerFactoryTest.java
Fix an order-dependent flaky test (trivial, just one line)
[Problem]
`testSerializeExtend` add an item to a static mapper,
and `testDeserializeExtend` read that item from that static mapper.
So if `testDeserializeExtend` runs before `testSerializeExtend`,
`testDeserializeExtend` will fail.
@Ignore `testSerializeExtend` can stably reproduce this issue.
[Solution]
Add that item to the static mapper at the beginning of the
`testDeserializeExtend` to make this test independent of
`testSerializeExtend`.
(Even though using static variables in unit tests is a bad practice)
N/A
`mvn test` passes
=> Fix an order-dependent flaky test

naming/src/main/java/com/alibaba/nacos/naming/controllers/InstanceController.java, naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperator.java, naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperatorClientImpl.java, naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperatorServiceImpl.java, naming/src/main/java/com/alibaba/nacos/naming/core/InstancePatchObject.java
=> Adapt all openAPI in for InstanceController.

api/src/main/java/com/alibaba/nacos/api/remote/response/ResponseCode.java
the param is `decs `, and `this.desc = desc;`
so response desc always null
=> Fix response desc always null

client/src/main/java/com/alibaba/nacos/client/naming/event/InstancesChangeNotifier.java, common/src/main/java/com/alibaba/nacos/common/notify/DefaultPublisher.java, core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcRequestAcceptor.java, naming/src/main/java/com/alibaba/nacos/naming/controllers/OperatorController.java, naming/src/main/java/com/alibaba/nacos/naming/core/SubscribeManager.java, naming/src/main/java/com/alibaba/nacos/naming/core/v2/event/service/ServiceEvent.java, naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/InstanceMetadataProcessor.java, naming/src/main/java/com/alibaba/nacos/naming/core/v2/pojo/Service.java, naming/src/main/java/com/alibaba/nacos/naming/misc/GlobalExecutor.java, naming/src/main/java/com/alibaba/nacos/naming/monitor/MetricsMonitor.java, naming/src/main/java/com/alibaba/nacos/naming/monitor/PerformanceLoggerThread.java, naming/src/main/java/com/alibaba/nacos/naming/push/NamingSubscriberServiceAggregationImpl.java, naming/src/main/java/com/alibaba/nacos/naming/push/PushService.java, naming/src/main/java/com/alibaba/nacos/naming/push/v2/NamingSubscriberServiceV2Impl.java, naming/src/main/java/com/alibaba/nacos/naming/push/v2/NoRequiredRetryException.java, naming/src/main/java/com/alibaba/nacos/naming/push/v2/executor/PushExecutor.java, naming/src/main/java/com/alibaba/nacos/naming/push/v2/executor/PushExecutorDelegate.java, naming/src/main/java/com/alibaba/nacos/naming/push/v2/executor/PushExecutorRpcImpl.java, naming/src/main/java/com/alibaba/nacos/naming/push/v2/executor/PushExecutorUdpImpl.java, naming/src/main/java/com/alibaba/nacos/naming/push/v2/task/PushDelayTaskExecuteEngine.java, naming/src/main/java/com/alibaba/nacos/naming/push/v2/task/PushExecuteTask.java, naming/src/main/java/com/alibaba/nacos/naming/remote/udp/AckEntry.java, naming/src/main/java/com/alibaba/nacos/naming/remote/udp/AckPacket.java, naming/src/main/java/com/alibaba/nacos/naming/remote/udp/UdpConnector.java, naming/src/main/java/com/alibaba/nacos/naming/utils/Constants.java, naming/src/test/java/com/alibaba/nacos/naming/core/SubscribeManagerTest.java, naming/src/test/java/com/alibaba/nacos/naming/monitor/MetricsMonitorTest.java
=> Add callback, simple retry and metric for naming push

client/src/main/java/com/alibaba/nacos/client/logging/NacosLogging.java, client/src/main/java/com/alibaba/nacos/client/logging/NacosLoggingUtils.java, client/src/main/java/com/alibaba/nacos/client/utils/LogUtils.java
=> [ISSUE-#4567] Refactor nacos-client Load Logging Configuration code.

console/src/main/java/com/alibaba/nacos/console/controller/UserController.java, console/src/main/java/com/alibaba/nacos/console/security/nacos/NacosAuthConfig.java, console/src/main/java/com/alibaba/nacos/console/security/nacos/roles/NacosRoleServiceImpl.java, test/src/test/java/com/alibaba/nacos/test/core/auth/User_ITCase.java
#3406
Use a special resource to update the password.  any user can access,authentication is implemented inside the method
XX
XXXX
=> [ISSUE #3406] fix change self's password fail

core/src/main/java/com/alibaba/nacos/core/remote/RequestHandlerRegistry.java
Pre init registryHandlers before grpc request call. Needn't wait the grpc request then to init registryHandlers, We can guarantee the request be handle after application started.
```
if (!ApplicationUtils.isStarted()) {
responseObserver.onNext(GrpcUtils.convert(new PlainBodyResponse("server is starting.")));
responseObserver.onCompleted();
return;
}
```
=> Pre init registryHandlers before grpc request call.

naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/DistroHttpRegistry.java, naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/component/DistroHttpAgent.java
For #4355 .
Do not retry distro sync again if member has removed.
=> [ISSUE#4355] Do not retry distro sync again if member has removed.

client/src/main/java/com/alibaba/nacos/client/config/impl/ConfigHttpClientManager.java, client/src/main/java/com/alibaba/nacos/client/config/utils/ConcurrentDiskUtil.java, client/src/main/java/com/alibaba/nacos/client/naming/cache/ConcurrentDiskUtil.java, common/src/main/java/com/alibaba/nacos/common/http/client/request/JdkHttpClientRequest.java, common/src/main/java/com/alibaba/nacos/common/http/client/response/HttpClientResponse.java, common/src/main/java/com/alibaba/nacos/common/utils/IoUtils.java, common/src/main/java/com/alibaba/nacos/common/utils/ResourceUtils.java, config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigServletInner.java, config/src/main/java/com/alibaba/nacos/config/server/service/datasource/LocalDataSourceServiceImpl.java, naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/raft/RaftStore.java, test/src/test/java/com/alibaba/nacos/test/common/NacosRestTemplate_Interceptors_ITCase.java
=> [ISSUE-#4594,#4596] Fix IO close problem

config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigServletInner.java, config/src/main/java/com/alibaba/nacos/config/server/enums/FileTypeEnum.java, config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedStoragePersistServiceImpl.java, config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java, test/src/test/java/com/alibaba/nacos/test/common/FileTypeEnum_ITCase.java
=> 优化 FileTypeEnum 取值逻辑, 避免使用异常当作逻辑分支

client/src/main/java/com/alibaba/nacos/client/naming/core/ServerListManager.java, naming/src/main/java/com/alibaba/nacos/naming/core/v2/ServiceManager.java, naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/AbstractClient.java, naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/ServiceMetadataProcessor.java, naming/src/main/java/com/alibaba/nacos/naming/misc/NamingExecuteTaskDispatcher.java, naming/src/main/java/com/alibaba/nacos/naming/monitor/MetricsMonitor.java, naming/src/main/java/com/alibaba/nacos/naming/monitor/PerformanceLoggerThread.java
=> Add some metrics and logs

client/src/main/java/com/alibaba/nacos/client/identify/CredentialWatcher.java
=> [ISSUE-#4631] Remove timer,Use ScheduledThreadPoolExecutor replaced.

api/src/main/java/com/alibaba/nacos/api/PropertyKeyConst.java, api/src/main/java/com/alibaba/nacos/api/naming/pojo/ServiceInfo.java, client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingService.java, client/src/main/java/com/alibaba/nacos/client/naming/core/HostReactor.java
=> [ISSUE-#3880] NamingService Client support pushEmptyProtection.

auth/src/main/java/com/alibaba/nacos/auth/common/AuthConfigs.java, auth/src/main/java/com/alibaba/nacos/auth/util/AuthHeaderUtil.java, config/src/main/java/com/alibaba/nacos/config/server/service/notify/AsyncNotifyService.java, core/src/main/java/com/alibaba/nacos/core/auth/AuthFilter.java, core/src/main/java/com/alibaba/nacos/core/distributed/raft/utils/JRaftUtils.java, distribution/conf/application.properties, naming/src/main/java/com/alibaba/nacos/naming/misc/HttpClient.java, naming/src/main/java/com/alibaba/nacos/naming/misc/NamingProxy.java
For #4593 , Add server identity to replace user-agent white list.
Templately Fix security problem. User can shutdown user-agent white list and defined their own identity key and value for request between servers.
- Add server identity to replace user-agent white list.
XXXX
=> [ISSUE #4593] Add server identity to replace user-agent white list.

api/src/main/java/com/alibaba/nacos/api/common/Constants.java, config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigQueryRequestHandler.java
=> [ISSUE #4681] Fix miss line break for query config.

console/src/main/java/com/alibaba/nacos/console/config/ConsoleConfig.java, console/src/main/resources/application.properties, core/src/main/java/com/alibaba/nacos/core/auth/AuthFilter.java, core/src/main/java/com/alibaba/nacos/core/code/ControllerMethodsCache.java
Fix #4701 
- Add support for uri end with '/'
- Directly reject if can't find api path in nacos implementations.
XX
XXXX
=> [ISSUE #4701] Fix bypass authentication(identity) problem.

core/src/main/java/com/alibaba/nacos/core/auth/AuthFilter.java
For #4701.
Found if interceptor all un register api, ui will be interceptor too.
so only add '/' support in methodCache first.
XX
XXXX
=> Revert interceptor all ui problem

naming/src/main/java/com/alibaba/nacos/naming/core/ServiceManager.java
method createServiceIfAbsent in ServiceManager require sync #3922
change method createServiceIfAbsent sync
Double-Check
=> [ISSUE #3922] method createServiceIfAbsent in ServiceManager require sync

.gitignore, client/src/main/java/com/alibaba/nacos/client/config/impl/YmlChangeParser.java, client/src/test/java/com/alibaba/nacos/client/config/listener/impl/YmlChangeParserTest.java
When users' use AbstractConfigChangeListener to listen config change key, nacos-client will parse yaml. But there are no use SafeConstructor.
This PR is to use SafeConstructor to parse the yaml and find out the changed key. Then callback users listener.
Now, spring cloud, dubbo, and springboot all not use `AbstractConfigChangeListener` to listen config changes. So It **will not** affect users for spring cloud, dubbo, and springboot.
Only affect those users using nacos-client directly and use `AbstractConfigChangeListener` to listener change keys in yaml configurations.
XXXXX
XX
XXXX
=> Use SafeConstructor to parse yaml configuration 

client/src/main/java/com/alibaba/nacos/client/naming/net/NamingProxy.java, client/src/main/java/com/alibaba/nacos/client/security/SecurityProxy.java
- add volatile keywork, make SecurityProxy.accessToken  threadsafe in single writer multi reader.
- adjust initRefreshTask, make SecurityProxy.login not running concurrently
XX
XXXX
=> make SecurityProxy.accessToken threadsafe in single writer  multi reader

api/src/main/java/com/alibaba/nacos/api/remote/RpcScheduledExecutor.java, config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java, core/src/main/java/com/alibaba/nacos/core/controller/ServerLoaderController.java, core/src/main/java/com/alibaba/nacos/core/utils/Commons.java
=> move server loader controller from console to core; modify common server scheduler count to solve large cpu usage

config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigQueryRequestHandler.java
=> optimize config file read

common/src/main/java/com/alibaba/nacos/common/http/client/response/JdkHttpClientResponse.java, common/src/main/java/com/alibaba/nacos/common/http/param/Header.java, common/src/test/java/com/alibaba/nacos/common/http/param/HeaderTest.java
=> [ISSUE-#4854] Modify Header to support Keys Ignore Case

naming/src/main/java/com/alibaba/nacos/naming/healthcheck/HealthCheckReactor.java
The same service call init twice concurrently,
It's just like 
```
public static void main(String[] args) throws IOException, InterruptedException, ClassNotFoundException, IllegalAccessException, InvocationTargetException, InstantiationException {
ScheduledExecutorService scheduledExecutor = Executors.newSingleThreadScheduledExecutor();
Map<String, ScheduledFuture> x = new ConcurrentHashMap<>();
x.putIfAbsent("11", scheduledExecutor.scheduleWithFixedDelay(new Runnable() {
@Override
public void run() {
System.out.println("3333");
}
}, 1000, 1000, TimeUnit.MILLISECONDS));
x.putIfAbsent("11", scheduledExecutor.scheduleWithFixedDelay(new Runnable() {
@Override
public void run() {
System.out.println("3333");
}
}, 1000, 1000, TimeUnit.MILLISECONDS));
Thread.sleep(5000); …
```
=> Fix one service init twice problem.

client/src/main/java/com/alibaba/nacos/client/utils/ParamUtil.java, client/src/main/java/com/alibaba/nacos/client/utils/TemplateUtils.java
- fix source.trim() if source is null
- call TenantUtil.getUserTenantForAcm() directly when  namespaceTmp is null
XX
XXXX
=> fix TemplateUtils usage

client/src/main/java/com/alibaba/nacos/client/config/http/MetricsHttpAgent.java
=> [ISSUE #5026]fix MetricsHttpAgent metrics twice

client/src/test/java/com/alibaba/nacos/client/config/filter/impl/ConfigContextTest.java, client/src/test/java/com/alibaba/nacos/client/config/filter/impl/ConfigFilterChainManagerTest.java, client/src/test/java/com/alibaba/nacos/client/config/filter/impl/ConfigRequestTest.java, client/src/test/java/com/alibaba/nacos/client/config/filter/impl/ConfigResponseTest.java
FIX [ISSUE #5032] add ut for package com.alibaba.nacos.client.config.filter, test coverage is 97%
XX
XXXX
=> [ISSUE #5032] add ut for package com.alibaba.nacos.client.config.filter

client/src/test/java/com/alibaba/nacos/client/config/utils/ConcurrentDiskUtilTest.java, client/src/test/java/com/alibaba/nacos/client/config/utils/ContentUtilsTest.java, client/src/test/java/com/alibaba/nacos/client/config/utils/JvmUtilTest.java, client/src/test/java/com/alibaba/nacos/client/config/utils/ParamUtilsTest.java, client/src/test/java/com/alibaba/nacos/client/config/utils/SnapShotSwitchTest.java
fix [ISSUE #5037]add ut for package com.alibaba.nacos.client.config.utils
line coverage 82%
XX
XXXX
=> [ISSUE #5037]add ut for package com.alibaba.nacos.client.config.utils

client/src/test/java/com/alibaba/nacos/client/config/http/MetricsHttpAgentTest.java, client/src/test/java/com/alibaba/nacos/client/config/http/ServerHttpAgentTest.java
fix [ISSUE #5034] add ut for package com.alibaba.nacos.client.config.http
line coverage 59%   
XX
XXXX
=> [ISSUE #5034] add ut for package com.alibaba.nacos.client.config.http

naming/src/test/java/com/alibaba/nacos/naming/core/v2/service/ClientOperationServiceProxyTest.java, naming/src/test/java/com/alibaba/nacos/naming/core/v2/service/impl/EphemeralClientOperationServiceImplTest.java, naming/src/test/java/com/alibaba/nacos/naming/core/v2/service/impl/PersistentClientOperationServiceImplTest.java
….v2.service in nacos 2.0
a part of fixing ISSUE #4983 
XXXXX
XX
XXXX
=> [ISSUE #4983] Add unit tests to package com.alibaba.nacos.naming.core.v2.service in nacos 2.0

core/src/main/java/com/alibaba/nacos/core/cluster/ServerMemberManager.java
It seem a mistake when merging from develop branch(#5135)。
https://github.com/alibaba/nacos/pull/5135/files#diff-df650e04d1ac3fca2d6a980d5f05ab28d926d1e6ecf0c7d2f866034b7e8bc879R364
which may cause members to lose state, such as `supportRemoteConnection`.
When the node list is changed, `ClusterRpcClientProxy#refresh` is judged as a member leave.
=> Fix merge mistake

naming/src/main/java/com/alibaba/nacos/naming/healthcheck/heartbeat/InstanceBeatCheckResponsibleInterceptor.java, naming/src/main/java/com/alibaba/nacos/naming/healthcheck/heartbeat/InstanceBeatCheckTask.java, naming/src/main/java/com/alibaba/nacos/naming/web/DistroIpPortTagGenerator.java, naming/src/main/resources/META-INF/services/com.alibaba.nacos.naming.healthcheck.heartbeat.AbstractBeatCheckInterceptor
FIX #5169 
- DISTRO filter support `beat` parameter.
- Only responsible server need to check instance heartbeats.
=> [ISSUE #5169] Fix instance beat run only by responsible server.

core/src/main/java/com/alibaba/nacos/core/cluster/ServerMemberManager.java
=> [ISSUE#5253] Fix missing identity header error

common/src/main/java/com/alibaba/nacos/common/utils/Observable.java, common/src/main/java/com/alibaba/nacos/common/utils/Observer.java, config/src/main/java/com/alibaba/nacos/config/server/filter/CurcuitFilter.java, config/src/main/java/com/alibaba/nacos/config/server/service/dump/EmbeddedDumpService.java, consistency/src/main/java/com/alibaba/nacos/consistency/ProtocolMetaData.java, consistency/src/test/java/com/alibaba/nacos/consistency/ProtocolMetaDataTest.java, naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/impl/PersistentServiceProcessor.java, test/src/test/java/com/alibaba/nacos/test/config/ConfigDerbyRaft_DITCase.java, test/src/test/java/com/alibaba/nacos/test/core/BaseClusterTest.java
After depending Jraft, protocol metadata can be subscribe for each key. One key and value will build an ValueItem to save data and observer. But the old implementation only four notify thread and ValueItem will block notify thread if no observer, which will cause some observer may not be called if there are more than four ValueItems without observer.
So I change the logic. Remove the notify thread and notify observer by main thread.
For non-block thread, removing the wait logic for observer. And when observer added, call `update` immediately to let observer can be notify at first.
After this PR, the observer of naming persistent server will be called, and change the `Down` to `Up` as expected.
- Fix #5351 
- Remove …
=> [ISSUE #5351] Remove blocked thread for Protocol metadata

config/src/main/java/com/alibaba/nacos/config/server/service/dump/DumpService.java
=> [ISSUE #5437]: change dump-task taskKey

api/src/main/java/com/alibaba/nacos/api/PropertyKeyConst.java, client/src/main/java/com/alibaba/nacos/client/naming/core/PushReceiver.java
nacos+dubbo 以consumer端部署的时候如果部署在容器内(docker内).就会发现provider list 的更新频率变成自动跑的任务的更新频率,而且永远收不到udp的push信息,这是因为docker内部安装的应用需要提前通知他们使用什么端口,不然其实是隔离的(比如桥接模式).
简单描述就是:查询list列表的时候会上报udp端口,但nacos server 获取到变更后并不能通知到容器中 dubbo 的 consumer端
=> Support specified naming UDP push port for client

api/src/main/java/com/alibaba/nacos/api/config/ConfigType.java
Optimize the ConfigType.isValidType method
see #5432 
XX
XXXX
=> Optimize the ConfigType.isValidType method

naming/src/main/java/com/alibaba/nacos/naming/controllers/ServiceController.java, naming/src/main/java/com/alibaba/nacos/naming/core/SubscribeManager.java, naming/src/test/java/com/alibaba/nacos/naming/core/SubscribeManagerTest.java
Fixes #5078 
由于每台机器的subscribers的数量都可能超过pageSize，所以暂时没有使用查本地再去查远程服务的方式。因为在做翻页的时候，必须要告诉后端已经查询了哪些机器，这样才能确认这一次查询需要查询那些机器，这样复杂度会很高，改动范围会比较大。所以暂时考虑用这种方式修复此问题。
XX
XXXX
=> [ISSUE #5078] set default pageSize to 10000 for getting all the  subscribers in other server node.

client/src/main/java/com/alibaba/nacos/client/utils/ParamUtil.java
Optimize ParamUtil code and extract constants
see more detail from #5527 
XX
XXXX
=> Optimize ParamUtil code and extract constants

core/src/main/java/com/alibaba/nacos/core/cluster/ServerMemberManager.java
FIX #5574 
Remove member version info when target member has no `cluster/report` api.
The downgraded member from 2.x to 1.1.x can recover to state `UP` via old `server/status` api.
=> [ISSUE #5574] Remove downgraded member version info.

naming/src/main/java/com/alibaba/nacos/naming/core/Service.java, naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/ServiceMetadataProcessor.java, naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/doublewrite/delay/DoubleWriteAction.java, naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/doublewrite/delay/DoubleWriteEventListener.java, naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/doublewrite/delay/ServiceChangeV1Task.java, naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/doublewrite/delay/ServiceChangeV2Task.java, naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/doublewrite/execute/AsyncServicesCheckTask.java, naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/doublewrite/execute/DoubleWriteMetadataChangeToV2Task.java, naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/doublewrite/execute/DoubleWriteServiceRemovalToV1Task.java, naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/doublewrite/execute/DoubleWriteServiceRemovalToV2Task.java
FIX #5692 
Make service removal sensed by double write task on both `v2 to v1` and `v1 to v2` sides.
XXXX
=> [ISSUE #5692] Make service removal sensed by double write.

config/src/main/java/com/alibaba/nacos/config/server/service/capacity/CapacityService.java, config/src/main/java/com/alibaba/nacos/config/server/service/datasource/ExternalDataSourceServiceImpl.java, config/src/main/java/com/alibaba/nacos/config/server/service/datasource/LocalDataSourceServiceImpl.java, config/src/main/java/com/alibaba/nacos/config/server/service/dump/DumpService.java, config/src/main/java/com/alibaba/nacos/config/server/service/dump/processor/DumpAllProcessor.java, config/src/main/java/com/alibaba/nacos/config/server/service/dump/processor/DumpChangeProcessor.java, config/src/main/java/com/alibaba/nacos/config/server/service/dump/processor/DumpProcessor.java, config/src/main/java/com/alibaba/nacos/config/server/service/merge/MergeDatumService.java, config/src/main/java/com/alibaba/nacos/config/server/service/merge/MergeTaskProcessor.java, config/src/main/java/com/alibaba/nacos/config/server/service/notify/AsyncNotifyService.java, config/src/main/java/com/alibaba/nacos/config/server/service/notify/NotifySingleService.java, config/src/main/java/com/alibaba/nacos/config/server/service/notify/NotifyTaskProcessor.java
improve the code quality of `nacos-config`, directory `service` part 1
Fixes #5727 
- change the position of variable to match common code habits 
- return first, reduce the if/for nest
- change the Chinese javadoc to English.
=> [ISSUE #5727 service-1] improve the code quality of nacos-config 

naming/src/main/java/com/alibaba/nacos/naming/consistency/KeyBuilder.java, naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/component/DistroDataStorageImpl.java, naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/component/DistroHttpAgent.java, naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/impl/NamingKvStorage.java
=>  [ISSUE #5774] improve the code quality for consistency

address/src/main/java/com/alibaba/nacos/address/component/AddressServerGeneratorManager.java, address/src/main/java/com/alibaba/nacos/address/controller/AddressServerClusterController.java, client/src/main/java/com/alibaba/nacos/client/config/impl/ServerListManager.java, client/src/main/java/com/alibaba/nacos/client/config/utils/ParamUtils.java, client/src/main/java/com/alibaba/nacos/client/naming/remote/http/NamingHttpClientProxy.java, common/src/main/java/com/alibaba/nacos/common/tls/SelfHostnameVerifier.java, common/src/main/java/com/alibaba/nacos/common/utils/InternetAddressUtil.java, common/src/test/java/com/alibaba/nacos/common/utils/InternetAddressUtilTest.java, config/src/main/java/com/alibaba/nacos/config/server/service/datasource/ExternalDataSourceServiceImpl.java, config/src/main/java/com/alibaba/nacos/config/server/utils/SystemConfig.java, core/src/main/java/com/alibaba/nacos/core/cluster/MemberUtil.java, core/src/main/java/com/alibaba/nacos/core/distributed/raft/JRaftServer.java, naming/src/main/java/com/alibaba/nacos/naming/cluster/ServerListManager.java, naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/raft/RaftCore.java, naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/raft/RaftProxy.java, naming/src/main/java/com/alibaba/nacos/naming/controllers/OperatorController.java, naming/src/main/java/com/alibaba/nacos/naming/core/HealthOperatorV2Impl.java, naming/src/main/java/com/alibaba/nacos/naming/core/Instance.java, naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperatorClientImpl.java, naming/src/main/java/com/alibaba/nacos/naming/core/ServiceManager.java, naming/src/main/java/com/alibaba/nacos/naming/core/v2/pojo/InstancePublishInfo.java, naming/src/main/java/com/alibaba/nacos/naming/healthcheck/ClientBeatCheckTask.java, naming/src/main/java/com/alibaba/nacos/naming/misc/NamingProxy.java, naming/src/main/java/com/alibaba/nacos/naming/misc/NetUtils.java, naming/src/main/java/com/alibaba/nacos/naming/misc/ServerStatusSynchronizer.java, naming/src/main/java/com/alibaba/nacos/naming/misc/ServiceStatusSynchronizer.java, naming/src/main/java/com/alibaba/nacos/naming/web/DistroIpPortTagGenerator.java, naming/src/test/java/com/alibaba/nacos/naming/healthcheck/heartbeat/ClientBeatCheckTaskV2Test.java, sys/src/main/java/com/alibaba/nacos/sys/utils/InetUtils.java, sys/src/test/java/com/alibaba/nacos/sys/utils/InetUtilsTest.java
For #5765 
fix ```localhost``` in cluster.conf not available
- rename IPUitl to InternetAddressUtil
- move isDomain to InternetAddressUtil
- fix localhost not match ip
[unit test case](https://github.com/alibaba/nacos/commit/ad541f664c99c8dde3ec76e7b0dc4a9e87132a68#diff-e3feb653a6109bcc8e7bbc7974c2d6fa93b17cc25783e9a26f31d86f36f2d471R103) pass
=> [ISSUE #5765] fix localhost not match ip

client/src/main/java/com/alibaba/nacos/client/identify/CredentialService.java, client/src/main/java/com/alibaba/nacos/client/identify/CredentialWatcher.java, client/src/main/java/com/alibaba/nacos/client/identify/IdentifyConstants.java, client/src/main/java/com/alibaba/nacos/client/identify/StsConfig.java
improve the code quality of `nacos-client`, directory `identify` 
For #5771
=> [FOR 5771 identify] improve the code quality of nacos-client.

core/src/main/java/com/alibaba/nacos/core/cluster/lookup/AddressServerMemberLookup.java, core/src/test/java/com/alibaba/nacos/core/cluster/lookup/AddressServerMemberLookupTest.java
AddressServerMemberLookup.syncFromAddressUrl方法需要服务端返回JSON数据，而nacos endpoint现在定义的返回是简单字符串。
修改AddressServerMemberLookup.syncFromAddressUrl方法使用字符串返回值，避免重复建设同类接口
将genericType定义从GenericType<RestResult<String>>为GenericType<String>
XXXX
=> [ISSUE #5999] AddressServerMemberLookup.syncFromAddressUrl适配nacos endpoint

naming/src/main/java/com/alibaba/nacos/naming/core/ServiceManager.java
=> [code quality][nacos-address]improve the code of ServiceManager.java

config/src/test/java/com/alibaba/nacos/config/server/auth/MockAuthManager.java, config/src/test/java/com/alibaba/nacos/config/server/controller/HealthControllerUnitTest.java, config/src/test/java/com/alibaba/nacos/config/server/service/ConfigChangePublisherTest.java, config/src/test/java/com/alibaba/nacos/config/server/service/dump/DumpServiceTest.java, config/src/test/resources/application.properties
=> [#5983] Fix unit tests in nacos-config

core/src/test/java/com/alibaba/nacos/core/remote/TpsMonitorManagerTest.java, naming/src/main/java/com/alibaba/nacos/naming/constants/ClientConstants.java, naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperatorClientImpl.java, naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/ClientAttributes.java, naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/ClientSyncData.java, naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/factory/ClientFactory.java, naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/factory/impl/ConnectionBasedClientFactory.java, naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/factory/impl/EphemeralIpPortClientFactory.java, naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/factory/impl/PersistentIpPortClientFactory.java, naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/impl/IpPortBasedClient.java, naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/ClientManager.java, naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/ClientManagerDelegate.java, naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/ConnectionBasedClientManager.java, naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/EphemeralIpPortClientManager.java, naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/PersistentIpPortClientManager.java, naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/impl/PersistentClientOperationServiceImpl.java, naming/src/test/java/com/alibaba/nacos/naming/core/v2/client/impl/IpPortBasedClientTest.java, naming/src/test/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/ConnectionBasedClientManagerTest.java, naming/src/test/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/EphemeralIpPortClientManagerTest.java, naming/src/test/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/PersistentIpPortClientManagerTest.java, naming/src/test/java/com/alibaba/nacos/naming/core/v2/event/publisher/NamingEventPublisherTest.java, naming/src/test/java/com/alibaba/nacos/naming/core/v2/service/impl/EphemeralClientOperationServiceImplTest.java, naming/src/test/java/com/alibaba/nacos/naming/healthcheck/v2/processor/HttpHealthCheckProcessorTest.java
Fixes #6116 .
- Refactor ClientManager and make register client and schedule checkTask is atomic.
=> [ISSUE#6116] Refactor ClientManager and make register client and schedule checkTask is atomic.

console-ui/src/pages/ConfigurationManagement/ConfigDetail/ConfigDetail.js, console-ui/src/pages/ConfigurationManagement/ConfigDetail/index.scss, console-ui/src/pages/ConfigurationManagement/ConfigEditor/NewConfigEditor.js, console-ui/src/pages/ConfigurationManagement/NewConfig/NewConfig.js
Unified configuration page style
For #6178
=> [#6178] Unified configuration page style

common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClient.java, naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/impl/EphemeralClientOperationServiceImpl.java
The client may be null after disconnect, fix it.
=> If the client already disconnect, ignore this request to avoid NPE.

naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/DefaultSelfUpgradeChecker.java, naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/SelfUpgradeChecker.java, naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/SelfUpgradeCheckerSpiHolder.java, naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/UpgradeJudgement.java, naming/src/test/java/com/alibaba/nacos/naming/core/v2/upgrade/MockSelfUpgradeChecker.java, naming/src/test/java/com/alibaba/nacos/naming/core/v2/upgrade/UpgradeJudgementTest.java, naming/src/test/resources/META-INF/services/com.alibaba.nacos.naming.core.v2.upgrade.SelfUpgradeChecker
=> Add SPI for upgrade checker.

common/src/test/java/com/alibaba/nacos/common/utils/InternetAddressUtilTest.java
For #5095
- add unit test to InternetAddressUtil
- inline variable
- simplify assert
[before coverage](http://htmlpreview.github.io/?https://github.com/SunJiFengPlus/nacos/blob/common-coverage/doc/before/InternetAddressUtil.html)
[after coverage](http://htmlpreview.github.io/?https://github.com/SunJiFengPlus/nacos/blob/common-coverage/doc/after/InternetAddressUtil.html)
=> [ISSUE #5095] Add unit test for InternetAddressUtil

config/src/main/java/com/alibaba/nacos/config/server/auth/EmbeddedPermissionPersistServiceImpl.java, config/src/main/java/com/alibaba/nacos/config/server/auth/EmbeddedRolePersistServiceImpl.java, config/src/main/java/com/alibaba/nacos/config/server/auth/EmbeddedUserPersistServiceImpl.java, config/src/main/java/com/alibaba/nacos/config/server/auth/ExternalPermissionPersistServiceImpl.java, config/src/main/java/com/alibaba/nacos/config/server/auth/ExternalRolePersistServiceImpl.java, config/src/main/java/com/alibaba/nacos/config/server/auth/ExternalUserPersistServiceImpl.java, config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigOpsController.java, config/src/main/java/com/alibaba/nacos/config/server/service/capacity/GroupCapacityPersistService.java, config/src/main/java/com/alibaba/nacos/config/server/service/capacity/TenantCapacityPersistService.java, config/src/main/java/com/alibaba/nacos/config/server/service/repository/PersistService.java, config/src/main/java/com/alibaba/nacos/config/server/service/repository/RowMapperManager.java, config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedPaginationHelperImpl.java, config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedStoragePersistServiceImpl.java, config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePaginationHelperImpl.java, config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java, config/src/test/java/com/alibaba/nacos/config/server/auth/ExternalPermissionPersistServiceImplTest.java, config/src/test/java/com/alibaba/nacos/config/server/auth/ExternalRolePersistServiceImplTest.java, config/src/test/java/com/alibaba/nacos/config/server/auth/ExternalUserPersistServiceImplTest.java
For [#6216]
Unify SQL naming style.
**SQL keyword : uppercase(eg.INSERT INTO, SELECT, UPDATE, DELETE, FROM, WHERE, LEFT JOIN, AND, LIKE... )**
**SQL function name : lowercase(eg. count, max...)**
**SQL field name: lowercase**
**Table name : lowercase**
`SELECT  a,b,c FROM table;`
`SELECT count(*) FROM table;`
=> [ISSUE #6216] Unify SQL naming style.

common/src/main/java/com/alibaba/nacos/common/utils/ConvertUtils.java, common/src/test/java/com/alibaba/nacos/common/utils/ConvertUtilsTest.java
For #5095
- 100% cover ConvertUtils, because there were so many branches of code, I import [ApprovalTests](https://github.com/approvals/ApprovalTests.Java) for test
- delete dead code
- simplify code
[before coverage](https://htmlpreview.github.io/?https://raw.githubusercontent.com/SunJiFengPlus/nacos/common-coverage/docs/com.alibaba.nacos.common.utils/.classes/ConvertUtils.html)
[after coverage](https://htmlpreview.github.io/?https://raw.githubusercontent.com/SunJiFengPlus/nacos/common-coverage/common-coverage/common-current/com.alibaba.nacos.common.utils/.classes/CollectionUtils.html)
=> [ISSUE #5095] Add unit test for ConvertUtils

common/src/test/java/com/alibaba/nacos/common/utils/JacksonUtilsTest.java
For #5095
[before coverage](https://htmlpreview.github.io/?https://raw.githubusercontent.com/SunJiFengPlus/nacos/common-coverage/docs/com.alibaba.nacos.common.utils/.classes/JacksonUtils.html)
[after coverage](https://htmlpreview.github.io/?https://raw.githubusercontent.com/SunJiFengPlus/nacos/common-coverage/common-coverage/common-current/com.alibaba.nacos.common.utils/.classes/ClassUtils.html)
=> [ISSUE #5095] Add unit test for JacksonUtils

common/src/main/java/com/alibaba/nacos/common/tls/SelfHostnameVerifier.java, common/src/test/java/com/alibaba/nacos/common/tls/SelfHostnameVerifierTest.java
For #5095
- replace the variable with  constant
[before coverage](https://htmlpreview.github.io/?https://raw.githubusercontent.com/SunJiFengPlus/nacos/common-coverage/docs/com.alibaba.nacos.common.tls/.classes/SelfHostnameVerifier.html)
[after coverage](https://htmlpreview.github.io/?https://raw.githubusercontent.com/SunJiFengPlus/nacos/common-coverage/common-coverage/common-current/com.alibaba.nacos.common.tls/.classes/SelfHostnameVerifier.html)
=>  [ISSUE #5095] Add unit test for SelfHostnameVerifier

distribution/bin/startup.sh
#6335 Fix the problem of startup error when the `JAVA_HOME` path contains spaces under Linux/Unix/Mac system, but this leads to another problem, #6382 -- You will get the following error when logging in to the console:
```
caused: Unable to obtain JCA MAC algorithm 'HmacSHA256': Algorithm HmacSHA256 not available;caused: Algorithm HmacSHA256 not available;
```
This is due to the failure to load the lib package specified by `-Djava.ext.dirs`. Therefore, the security algorithm of JDK is not available.
Modify the `distribution/bin/startup.sh` file, change 
```
JAVA_OPT_EXT_FIX="-Djava.ext.dirs=\"${JAVA_HOME}/jre/lib/ext:${JAVA_HOME}/lib/ext\""
``` 
to 
```
JAVA_OPT_EXT_FIX="-Djava.ext.dirs=${JAVA_HOME}/jre/lib/ext:${JAVA_HOME}/lib/ext"
```
Just remove the `\"` around `java.ext.dirs` value. …
=> [ISSUE #6382] Fix the Algorithm HmacSHA256 not available error when login

common/src/main/java/com/alibaba/nacos/common/tls/TlsFileWatcher.java, common/src/test/java/com/alibaba/nacos/common/tls/TlsFileWatcherTest.java
For #5095
- replace explicit type argument with <>
- replace anonymous Runnable with lambda
- rename parameter because of catch parameter named 'ignored' is used
- adjust log style
[before coverage](https://htmlpreview.github.io/?https://raw.githubusercontent.com/SunJiFengPlus/nacos/common-coverage/docs/com.alibaba.nacos.common.tls/.classes/TlsFileWatcher.html)
[after coverage](https://htmlpreview.github.io/?https://raw.githubusercontent.com/SunJiFengPlus/nacos/common-coverage/common-coverage/common-current/com.alibaba.nacos.common.tls/.classes/TlsFileWatcher.html)
=> [ISSUE #5095] Add unit test for TlsFileWatcher

common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClientFactory.java, common/src/test/java/com/alibaba/nacos/common/remote/client/RpcClientFactoryTest.java
For #5095
- fix typo
[before coverage](https://htmlpreview.github.io/?https://raw.githubusercontent.com/SunJiFengPlus/nacos/common-coverage/docs/com.alibaba.nacos.common.remote.client/.classes/RpcClientFactory.html)
[after coverage](https://htmlpreview.github.io/?https://raw.githubusercontent.com/SunJiFengPlus/nacos/common-coverage/common-coverage/common-current/com.alibaba.nacos.common.remote.client/.classes/RpcClientFactory.html)
=> [ISSUE #5095] Add unit test for RpcClientFactory

core/src/main/java/com/alibaba/nacos/core/utils/GenericType.java, core/src/test/java/com/alibaba/nacos/core/utils/ClassUtilsTest.java
Replace "com.google.common.reflect.TypeToken" API with jdk API. for #6523
=> Replace "google.common.reflect.* TypeToken" API with jdk API

client/src/main/java/com/alibaba/nacos/client/naming/beat/BeatReactor.java
fix #1733 again for nacos 1.x to avoid creating beat task more than once by doing ConcurrentHashMap.put concurrently.
i met the issue again by using nacos sync:
1. restart N instances of one sync task at the same time, it trigged sync event more than once,
2. for each sync event, nacos sync called registerInstance concurrently,
3. ConcurrentHashMap.put was called concurrently for the same instance.
=> fix #1733 again for nacos 1.x

common/src/test/java/com/alibaba/nacos/common/remote/client/RpcClientTest.java
For #5095
- add unit test to RpcClient
[before coverage](https://htmlpreview.github.io/?https://raw.githubusercontent.com/SunJiFengPlus/nacos/common-coverage/docs/com.alibaba.nacos.common.remote.client/.classes/RpcClient.html)
[after coverage](https://htmlpreview.github.io/?https://raw.githubusercontent.com/SunJiFengPlus/nacos/common-coverage/common-coverage/common-current/ns-10/sources/source-2.html)
=> [ISSUE #5095] Add unit test for RpcClient

core/src/main/java/com/alibaba/nacos/core/distributed/raft/JRaftServer.java
detail #6583 
When use raft read-index, the follower will wait self apply index reach leader's commitIndex. If follower fall behind leader much, the read-index read will timeout(default timeout is 2000ms).
If read-index read timeout, request to leader directly.
=> When read-index read timeout, go to leader to read.

naming/src/main/java/com/alibaba/nacos/naming/constants/ClientConstants.java, naming/src/main/java/com/alibaba/nacos/naming/controllers/OperatorController.java, naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/impl/IpPortBasedClient.java, naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/ClientManagerDelegate.java, naming/src/test/java/com/alibaba/nacos/naming/controllers/OperatorControllerTest.java
=> [ISSUE #6572] add client info for OperatorController metrics interface

common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClient.java
```
Caused by: java.lang.NullPointerException
at com.alibaba.nacos.common.remote.client.RpcClient.shutdown(RpcClient.java:466)
at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.shutdown(GrpcClient.java:81)
at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.shutdown(NamingGrpcClientProxy.java:234)
at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.shutdown(NamingClientProxyDelegate.java:180)
at com.alibaba.nacos.client.naming.NacosNamingService.shutDown(NacosNamingService.java:456)
at org.apache.dubbo.registry.nacos.NacosNamingServiceWrapper.shutdown(NacosNamingServiceWrapper.java:78)
at org.apache.dubbo.registry.nacos.NacosServiceDiscovery.doDestroy(NacosServiceDiscovery.java:70)
at org.apache.dubbo.registry.client.AbstractServiceDiscovery.destroy …
```
=> Fix npe when connection is not established.

common/src/test/java/com/alibaba/nacos/common/http/HttpUtilsTest.java
For #5095
- add unit test to HttpUtils
[before coverage](https://htmlpreview.github.io/?https://raw.githubusercontent.com/SunJiFengPlus/nacos/common-coverage/docs/com.alibaba.nacos.common.http/.classes/HttpUtils.html)
[after coverage](https://htmlpreview.github.io/?https://raw.githubusercontent.com/SunJiFengPlus/nacos/common-coverage/common-coverage/common-current/ns-8/sources/source-8.html)
=> [ISSUE #5095] Add unit test to HttpUtils

client/src/main/java/com/alibaba/nacos/client/naming/remote/http/NamingHttpClientProxy.java
optimize the HashMap’s initialCapacity
HashMap will automatically expand, when it‘s size greater than initialCapacity * 0.75. And the initialCapacity’s value should be 2^n.
The following code will expand：
（1）NamingHttpClientProxy#registerService method：
The size of "params" will be 13 or 16. Because the reqApi method will put 2 or 5 value into the it. So the initialCapacity should be 32.
(2)NamingHttpClientProxy#deregisterService method:
The size of "params" will be 8 or 11. So the initialCapacity should be 16.
(3)NamingHttpClientProxy#updateInstance method:
The size of "params" will be 12 or 15. So the initialCapacity should be 32.
(4)NamingHttpClientProxy#queryInstancesOfService method:
The size of "params" will be 8 or 11. So the initialCapacity should be 16. …
=> optimize the HashMap’s initialCapacity

client/src/main/java/com/alibaba/nacos/client/config/AesCrypto.java, client/src/main/java/com/alibaba/nacos/client/config/filter/impl/ConfigCryptoFilter.java
=> [ISSUE#5695] Summer2021  Inheritance AbstractConfigFilter

common/src/main/java/com/alibaba/nacos/common/executor/ExecutorFactory.java, common/src/main/java/com/alibaba/nacos/common/executor/ThreadPoolManager.java, common/src/test/java/com/alibaba/nacos/common/event/ServerConfigChangeEventTest.java, common/src/test/java/com/alibaba/nacos/common/executor/ExecutorFactoryTest.java, common/src/test/java/com/alibaba/nacos/common/executor/NameThreadFactoryTest.java, common/src/test/java/com/alibaba/nacos/common/executor/ThreadPoolManagerTest.java
=> [ISSUE #5095] Add some testcases for common executor

config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigController.java, config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigPublishRequestHandler.java, config/src/main/java/com/alibaba/nacos/config/server/service/repository/PersistService.java, config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedStoragePersistServiceImpl.java, config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java
=> [ISSUE#5695] Summer2021 Import/export compatible with configuration encryption and decryption

core/src/main/java/com/alibaba/nacos/core/distributed/raft/JRaftServer.java, core/src/main/java/com/alibaba/nacos/core/distributed/raft/utils/FailoverClosureImpl.java
Now the response `success` is false, the logic is not right.
If remote processor response `success` is false, we should judge the value before future.complete.
Now the judgement is in whenComplete, it's unuseful.
=> Fix response success

api/src/main/java/com/alibaba/nacos/api/exception/NacosException.java, api/src/main/java/com/alibaba/nacos/api/remote/response/ErrorResponse.java, common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClient.java, core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcRequestAcceptor.java
At now, when client handle request from server error, it will send PushAckRequest to server, but server side didn't hold corresponding requestHandler, it should use bidiStream to send response directly.
=> Fix PushAckRequest mismatch problem.

common/src/main/java/com/alibaba/nacos/common/Beta.java, consistency/src/main/java/com/alibaba/nacos/consistency/IdGenerator.java, core/src/main/java/com/alibaba/nacos/core/cluster/ServerMemberManager.java, core/src/main/java/com/alibaba/nacos/core/controller/v2/CoreOpsV2Controller.java, core/src/main/java/com/alibaba/nacos/core/controller/v2/NacosClusterV2Controller.java, core/src/main/java/com/alibaba/nacos/core/distributed/id/SnowFlowerIdGenerator.java, core/src/main/java/com/alibaba/nacos/core/model/request/LogUpdateRequest.java, core/src/main/java/com/alibaba/nacos/core/model/request/LookupUpdateRequest.java, core/src/main/java/com/alibaba/nacos/core/model/vo/IdGeneratorVO.java, core/src/test/java/com/alibaba/nacos/core/controller/v2/CoreOpsV2ControllerTest.java, core/src/test/java/com/alibaba/nacos/core/controller/v2/NacosClusterV2ControllerTest.java, core/src/test/java/com/alibaba/nacos/core/model/request/LogUpdateRequestTest.java, core/src/test/java/com/alibaba/nacos/core/model/request/LookupUpdateRequestTest.java, core/src/test/java/com/alibaba/nacos/core/model/vo/IdGeneratorVOTest.java, style/NacosCheckStyle.xml
=> [ISSUE #6970] Add rest api v2 in core module

core/src/main/java/com/alibaba/nacos/core/cluster/ServerMemberManager.java, core/src/test/java/com/alibaba/nacos/core/cluster/ServerMemberManagerTest.java
Ignore the WebServerInitializedEvent if the name space of the spring context is management
Close#7230
#7230
- ServerMemberManager#onApplicationEvent add namespace conditon code block 
XXXX
=> [ISSUE #7225] Ignore the WebServerInitializedEvent if the name space of the spring context is management

client/src/main/java/com/alibaba/nacos/client/config/impl/CacheData.java, client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java
fix #7039
不是好的实现方式，临时修复至配置解密可用。期待社区统一考虑配置获取和解密 Filter 等，同时也兼并考虑 2.x 版本里的这部分。
提 PR 仅是希望知道真的有这个 bug，谢谢。
---
It is not a good implementation method. It is temporarily repaired until the configuration decryption is available. The community is expected to uniformly consider the configuration, acquisition and decryption of filter, and also consider this part in version 2.x.
I just want to know that there is really a bug. Thank you.
=> fix 1.4.2 EncryptedData Long-Polling listerning bug in client(LongPollingRunnable). 

client/src/main/java/com/alibaba/nacos/client/naming/beat/BeatReactor.java, client/src/main/java/com/alibaba/nacos/client/naming/net/NamingProxy.java
Users often complain about the annoying nacos client beat error log when they look over application logs.
And also they always get a 500(HttpStatus) instead of other HttpStatus.
So this change will improve the experience of looking over application logs when the application goes wrong.
Following exceptions logs has bean optimized
- 403、404 exceptions come from nacos server and so on
- java.net.ConnectException
- java.net.SocketTimeoutException
=> Optimizing client beat log output

core/src/main/java/com/alibaba/nacos/core/distributed/raft/JRaftServer.java
catch exception when register self to cluster.
=> catch exception when register self to cluster.

api/src/main/java/com/alibaba/nacos/api/exception/runtime/NacosLoadException.java, client/src/main/java/com/alibaba/nacos/client/naming/core/ServerListManager.java, client/src/test/java/com/alibaba/nacos/client/naming/NacosNamingMaintainServiceTest.java, client/src/test/java/com/alibaba/nacos/client/naming/NacosNamingServiceTest.java, client/src/test/java/com/alibaba/nacos/client/naming/remote/NamingClientProxyDelegateTest.java
当未配置nacos服务端地址时，启动会报错
修改之后在启动时如果发现获取不到服务端地址直接给出提示
XX
XXXX
=> fix by zero error

core/src/main/java/com/alibaba/nacos/core/distributed/raft/JRaftServer.java, core/src/main/java/com/alibaba/nacos/core/distributed/raft/utils/FailoverClosureImpl.java
1. apply PR #7564 from develop to catch exception when register self to cluster.
2. apply PR #6987 from develop to fix response success.
3. apply PR #6575 from develop to read from leader when readIndex timeout.
=> [1.x] Patch v1.x JRaftServer.java

config/src/test/java/com/alibaba/nacos/config/server/remote/RpcConfigChangeNotifierTest.java
for #5092
add junit test for RpcConfigChangeNotifier
XXXX
=> add junit test for RpcConfigChangeNotifier

console/src/main/java/com/alibaba/nacos/console/exception/ConsoleExceptionHandler.java
1. don't set response entity when ClientAbortException occurred (avoid infinite exception handler loop).
2. log request uri and address at exception handlers.
=> [1.x] Patch v1.x console exception handler

common/src/main/java/com/alibaba/nacos/common/http/AbstractApacheHttpClientFactory.java, common/src/main/java/com/alibaba/nacos/common/http/AbstractHttpClientFactory.java, common/src/main/java/com/alibaba/nacos/common/http/HttpClientConfig.java, common/src/main/java/com/alibaba/nacos/common/http/client/request/DefaultAsyncHttpClientRequest.java, common/src/main/java/com/alibaba/nacos/common/http/client/request/DefaultHttpClientRequest.java, naming/src/main/java/com/alibaba/nacos/naming/misc/HttpClient.java
Fixes #7375
1. set default connection lease request timeout to avoid OOM under continuously huge beat requestions. 
2. merge default connection configurations to each http client request.
3. add IOReactorExceptionHandler and log ioreactor shutdown reason.
=> [1.x] Patch v1.x set default connection lease request timeout

consistency/src/main/java/com/alibaba/nacos/consistency/ProtoMessageUtil.java, consistency/src/test/java/com/alibaba/nacos/consistency/ProtoMessageUtilTest.java, core/src/main/java/com/alibaba/nacos/core/distributed/raft/JRaftServer.java
=> [develop] add request type field at the head of task data, exchange parse order between Log and GetRequest 

naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/ClusterVersionJudgement.java
fix bug #7971 
ClusterVersionJudgement在执行runVersionListener的时候增加判断，如果所有成员已经是新版本，且通知成功，则不再执行后续的runVersionListener
已经通知过后，就不会再次提交runVersionListener任务
=> [ISSUE #7971] fix ClusterVersionJudgement#ClusterVersionJudge Task never stop

common/src/main/java/com/alibaba/nacos/common/utils/JacksonUtils.java, common/src/test/java/com/alibaba/nacos/common/utils/JacksonUtilsTest.java
Change implementation of JacksonUtils methods about byte operation to reduce memory cost, especially when DistroProtocol fetching full data from peer node in the initialization phase. (#8072)
详见：https://github.com/alibaba/nacos/issues/8072
Reduce memory cost in DistroProtocol initialization to avoid OOM
Unit tests for changes have been added.
=> [ISSUE #8072] Reduce memory cost in DistroProtocol initialization to avoid OutOfMemoryError

core/src/main/java/com/alibaba/nacos/core/controller/NacosClusterController.java, core/src/test/java/com/alibaba/nacos/core/controller/NacosClusterControllerTest.java
V2.x fix(#6273): server/leave, add end conditions for cluster notifications.
relate #8099
=> V2.x fix(#6273): server/leave, add end conditions for cluster notifications.

console-ui/src/utils/request.js
- use IdentityContextHolder instead of get user information from session
Problem:
问题:
Users restart nacos server and do not login again then users update password will get an error `authorization failed`
用户重启了 nacos server 端,并未重新登录. 在做修改用户密码时提示`authorization failed`
Cause:
原因:
The session information was lost by restart.
重启客户端session信息丢失
Fix:
修复:
Use `IdentityContextHolder` instead of sessions, When requests are cross the `AuthFilter`, the `AuthFilter` will set a `IdentityContext` object into `IdentityContextHolder` and clean it in the end
使用 `IdentityContextHolder` 替代从 session 中获取用户信息. 每次请求经过 `AuthFilter`  把 `IdentityContext` 对象放入到 `IdentityContextHolder` 中并在请求结束时清空 `IdentityContextHolder`
Close #8107
Follow this …
=> [ISSUE #8107] 403 go to home page when modify user's password 

naming/src/main/java/com/alibaba/nacos/naming/controllers/ServiceController.java
[ISSUE #8196] Return count number of subscribers correctly when throw an exception
Close #8196
XXXXX
XX
XXXX
=> [ISSUE #8196] Return count number of subscribers correctly when throw an exception

core/src/main/java/com/alibaba/nacos/core/distributed/raft/utils/JRaftConstants.java, core/src/main/java/com/alibaba/nacos/core/distributed/raft/utils/JRaftOps.java
feat(#5346): reset raft cluster ops for no leader, use JRaft Api resetPeers.
Use only in very urgent situations where availability is more important!
https://www.sofastack.tech/projects/sofa-jraft/jraft-user-guide/#7.3 多数节点故障
只有在非常紧急并且可用性更为重要的情况下使用。
> 面对 k8s 云环境这种上下线/重启等成员 ip 变动大的情况，常常遇到 issue 里描述的问题；
而 Nacos 还是 AP 用法，所以 CP 不应该作为影响集群整体可用性的拦路虎；
而且 nacos-client 也会不断 beat 补全注册的数据，从而我这边增加了一个重置整个集群选举的入口 resetPeers （用于真的无法选主时的极限运维，总好过集群整体挂掉）
=> feat(#5346): reset raft cluster ops for no leader, use JRaft Api resetPeers.

api/src/main/java/com/alibaba/nacos/api/PropertyKeyConst.java, client/src/main/java/com/alibaba/nacos/client/config/impl/CacheData.java, client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java, client/src/main/java/com/alibaba/nacos/client/config/impl/ServerListManager.java, client/src/main/resources/nacos-logback.xml, client/src/test/java/com/alibaba/nacos/client/config/http/ServerHttpAgentTest.java, client/src/test/java/com/alibaba/nacos/client/config/impl/ClientWorkerTest.java, client/src/test/java/com/alibaba/nacos/client/config/impl/ServerListManagerTest.java, common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClientFactory.java
fix bug isuue 8163
add nacos.cache.data.init.snapshot properties ,to determine if load snapshot content on  startup  which will result in a default notification on initialing  ,default is true
=> issue#8163 fix multi instance share the same local snapshot

config/src/main/java/com/alibaba/nacos/config/server/service/ConfigCacheService.java
Fix the problem mentioned in [issue #7780] (https://github.com/alibaba/nacos/issues/7780): Data inconsistency (a-b-a) caused by concurrent execution of DumpAllProcessor and DumpProcessor
修复 [ISSUE#7780](https://github.com/alibaba/nacos/issues/7780) 中提到的问题：DumpAllProcessor和DumpProcessor 并发执行导致的数据不一致
When dump is executed, add the comparison logic of the last modification time. If the target data is older than the data in the cache, directly `reture true` and no modification logic will be executed
dump执行到修改逻辑前，加上最后修改时间的对比逻辑，如果目标数据比缓存中数据老的时候，直接 `reture true`，不再执行修改
Use [ISSUE#7780](https://github.com/alibaba/nacos/issues/7780) The reproduction method in has been verified and can solve this problem
使用 [ISSUE#7780](https://github.com/alibaba/nacos/issues/7780) 中的复现方法已经验证通过，可以解决此问题
Follow this …
=> [ISSUE#7780] Fix a-b-a problem.

client/src/main/java/com/alibaba/nacos/client/config/impl/Limiter.java, common/src/main/java/com/alibaba/nacos/common/cache/builder/CacheBuilder.java, core/src/main/java/com/alibaba/nacos/core/utils/StringPool.java
Close #7487 
Add generics for the CacheBuilder:
- CacheBuilder#builder
- CacheBuilder#expireNanos
=> [ISSUE #7487] Add generics for the CacheBuilder.

client/src/main/java/com/alibaba/nacos/client/config/http/ServerHttpAgent.java
由于目前调用GET: /nacos/v1/cs/configs，当配置不存在时，会返回状态码为404。此处无法识别错误，导致日志看不出来
增加对404状态码的判断
=> 增加对状态码为404的判断

.github/workflows/ci.yml, naming/pom.xml, naming/src/test/java/com/alibaba/nacos/naming/BaseTest.java, naming/src/test/java/com/alibaba/nacos/naming/consistency/persistent/PersistentConsistencyServiceDelegateImplTest.java, naming/src/test/java/com/alibaba/nacos/naming/controllers/CatalogControllerTest.java, naming/src/test/java/com/alibaba/nacos/naming/controllers/InstanceControllerV2Test.java, naming/src/test/java/com/alibaba/nacos/naming/core/DistroMapperTest.java, naming/src/test/java/com/alibaba/nacos/naming/core/DomainTest.java, naming/src/test/java/com/alibaba/nacos/naming/core/InstanceOperatorClientImplTest.java, naming/src/test/java/com/alibaba/nacos/naming/core/ServiceManagerTest.java, naming/src/test/java/com/alibaba/nacos/naming/core/ServiceOperatorV2ImplTest.java, naming/src/test/java/com/alibaba/nacos/naming/core/ServiceTest.java, naming/src/test/java/com/alibaba/nacos/naming/core/v2/event/publisher/NamingEventPublisherFactoryTest.java, naming/src/test/java/com/alibaba/nacos/naming/core/v2/upgrade/doublewrite/delay/DoubleWriteEventListenerTest.java, naming/src/test/java/com/alibaba/nacos/naming/monitor/MetricsMonitorTest.java, naming/src/test/java/com/alibaba/nacos/naming/pojo/instance/BeatInfoInstanceBuilderTest.java, naming/src/test/java/com/alibaba/nacos/naming/pojo/instance/HttpRequestInstanceBuilderTest.java, naming/src/test/java/com/alibaba/nacos/naming/push/v2/executor/PushExecutorRpcImplTest.java, naming/src/test/java/com/alibaba/nacos/naming/push/v2/executor/PushExecutorUdpImplTest.java, naming/src/test/java/com/alibaba/nacos/naming/raft/RaftStoreTest.java, naming/src/test/java/com/alibaba/nacos/naming/remote/udp/UdpConnectorTest.java, pom.xml
=> [ISSUE#4982] Fix naming module unit test and generate jacoco coverage report

.github/workflows/ci.yml, codecov.yml, pom.xml
=> Add codeCov report after CI finish

client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java, client/src/main/java/com/alibaba/nacos/client/utils/EnvUtil.java, client/src/test/java/com/alibaba/nacos/client/utils/EnvUtilTest.java
fix the #8350 
In the process of reading the source code, it is found that the word is misspelled in the 'envutil' tool class:
在阅读源码的过程中， 发现在 `EnvUtil` 工具类中， 发现一处单词拼写错误：
源代码：
```java
// 变量名：amorayTagTmp  
// 这里的 amoray, 从上下文分析。 此时应为 amory
// 可能是大佬手速太快了 [手动狗头]
List<String> amorayTagTmp = headers.get(Constants.AMORY_TAG);
if (amorayTagTmp == null) {
if (selfAmorayTag != null) {
selfAmorayTag = null;
LOGGER.warn("selfAmoryTag:null");
}
```
=> Hotfix issue 8350

config/src/test/java/com/alibaba/nacos/config/server/configuration/ConditionDistributedEmbedStorageTest.java, config/src/test/java/com/alibaba/nacos/config/server/configuration/ConditionOnEmbeddedStorageTest.java, config/src/test/java/com/alibaba/nacos/config/server/configuration/ConditionOnExternalStorageTest.java, config/src/test/java/com/alibaba/nacos/config/server/configuration/ConditionStandaloneEmbedStorageTest.java, config/src/test/java/com/alibaba/nacos/config/server/controller/ConfigControllerTest.java, config/src/test/java/com/alibaba/nacos/config/server/controller/ConfigOpsControllerTest.java, config/src/test/java/com/alibaba/nacos/config/server/controller/ConfigServletInnerTest.java, config/src/test/java/com/alibaba/nacos/config/server/controller/HealthControllerTest.java, config/src/test/java/com/alibaba/nacos/config/server/controller/HistoryControllerTest.java, config/src/test/java/com/alibaba/nacos/config/server/remote/ConfigChangeBatchListenRequestHandlerTest.java, config/src/test/java/com/alibaba/nacos/config/server/remote/ConfigQueryRequestHandlerTest.java, config/src/test/java/com/alibaba/nacos/config/server/service/capacity/GroupCapacityPersistServiceTest.java, config/src/test/java/com/alibaba/nacos/config/server/service/capacity/TenantCapacityPersistServiceTest.java, config/src/test/java/com/alibaba/nacos/config/server/service/datasource/DynamicDataSourceTest.java, config/src/test/java/com/alibaba/nacos/config/server/service/dump/DumpServiceTest.java, config/src/test/java/com/alibaba/nacos/config/server/utils/DiskUtilsTest.java, config/src/test/java/com/alibaba/nacos/config/server/utils/MD5UtilTest.java, config/src/test/java/com/alibaba/nacos/config/server/utils/ParamUtilsTest.java, config/src/test/java/com/alibaba/nacos/config/server/utils/PropertyUtilTest.java, config/src/test/java/com/alibaba/nacos/config/server/utils/ResponseUtilTest.java
=> Fix some failing unit tests in nacos config module 

naming/pom.xml, pom.xml
https://github.com/alibaba/nacos/pull/8324
XX
XXXX
=> Remove mina dependency.

common/src/main/java/com/alibaba/nacos/common/utils/IoUtils.java, common/src/test/java/com/alibaba/nacos/common/utils/IoUtilsTest.java
=> optimize IoUtils and Add some unit test

client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingService.java, client/src/main/java/com/alibaba/nacos/client/naming/cache/ServiceInfoHolder.java, client/src/main/java/com/alibaba/nacos/client/naming/event/InstancesChangeEvent.java, client/src/main/java/com/alibaba/nacos/client/naming/event/InstancesChangeNotifier.java, client/src/test/java/com/alibaba/nacos/client/naming/cache/ServiceInfoHolderTest.java, client/src/test/java/com/alibaba/nacos/client/naming/event/InstancesChangeEventTest.java, client/src/test/java/com/alibaba/nacos/client/naming/event/InstancesChangeNotifierTest.java, common/src/main/java/com/alibaba/nacos/common/notify/DefaultPublisher.java, common/src/main/java/com/alibaba/nacos/common/notify/Event.java, common/src/main/java/com/alibaba/nacos/common/notify/listener/Subscriber.java, test/naming-test/src/test/java/com/alibaba/nacos/test/naming/Subscribe_ITCase.java
=> [ISSUE #8428] fix naming subscribe bug when multiple NamingService (2.x)

client/src/main/java/com/alibaba/nacos/client/naming/core/HostReactor.java, client/src/main/java/com/alibaba/nacos/client/naming/event/InstancesChangeEvent.java, client/src/main/java/com/alibaba/nacos/client/naming/event/InstancesChangeNotifier.java, common/src/main/java/com/alibaba/nacos/common/notify/DefaultPublisher.java, common/src/main/java/com/alibaba/nacos/common/notify/Event.java, common/src/main/java/com/alibaba/nacos/common/notify/listener/Subscriber.java, test/src/test/java/com/alibaba/nacos/test/naming/Subscribe_ITCase.java
=> [ISSUE #8428] fix naming subscribe bug when multiple NamingService (1.x)

api/src/main/java/com/alibaba/nacos/api/naming/remote/NamingRemoteConstants.java, api/src/main/java/com/alibaba/nacos/api/naming/remote/request/BatchInstanceRequest.java, api/src/main/java/com/alibaba/nacos/api/naming/remote/response/BatchInstanceResponse.java, naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/ClientOperationService.java, naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/ClientOperationServiceProxy.java, naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/impl/EphemeralClientOperationServiceImpl.java, naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/impl/PersistentClientOperationServiceImpl.java, naming/src/main/java/com/alibaba/nacos/naming/remote/rpc/handler/BatchInstanceRequestHandler.java
For #5863. support nacos2.x batch register instance，define InstanceRequest InstanceResponse and Handler
XX
XXXX
=> [ISSUE#5863] Define InstanceRequest InstanceResponse and Handler

core/src/main/java/com/alibaba/nacos/core/code/SpringApplicationRunListener.java, pom.xml
Issue: #8169
参考 https://github.com/advisories/GHSA-36p3-wjmg-h94x ，升级到 Spring Boot 2.6.6 修复此问题
=> [ISSUE #8169] Upgrade spring-boot version to 2.6.6(2.x)

console/src/main/resources/META-INF/nacos-default.properties, console/src/main/resources/application.properties, distribution/conf/application.properties, distribution/conf/application.properties.example, naming/src/main/resources/application.properties, test/config-test/src/test/resources/application.properties, test/core-test/src/test/resources/application.properties, test/naming-test/src/test/resources/application.properties
=> [ISSUE #8528] update server.tomcat.basedir default value

client/pom.xml, config/pom.xml, console/pom.xml, core/pom.xml, pom.xml, test/pom.xml
issue #8472
Dependency Governance, Remove useless dependencies.
XX
`mvn clean install -Dmaven.test.skip=true -P release-nacos`
Make sure there are no compile errors.
务必已保障没有编译错误。
=> [ISSUE #8472]: Dependency Governance, Remove useless dependencies. (#8472)

common/src/main/java/com/alibaba/nacos/common/trace/DeregisterInstanceReason.java, common/src/main/java/com/alibaba/nacos/common/trace/HealthStateChangeReason.java, common/src/main/java/com/alibaba/nacos/common/trace/event/NamingTraceEvent.java, common/src/main/java/com/alibaba/nacos/common/trace/event/TraceEvent.java, common/src/main/java/com/alibaba/nacos/common/trace/publisher/TraceEventPublisher.java, common/src/main/java/com/alibaba/nacos/common/trace/publisher/TraceEventPublisherFactory.java, common/src/test/java/com/alibaba/nacos/common/trace/publisher/TraceEventPublisherFactoryTest.java, common/src/test/java/com/alibaba/nacos/common/trace/publisher/TraceEventPublisherTest.java, common/src/test/java/com/alibaba/nacos/common/trace/publisher/TraceTestEvent.java, naming/src/main/java/com/alibaba/nacos/naming/controllers/InstanceController.java, naming/src/main/java/com/alibaba/nacos/naming/controllers/InstanceControllerV2.java, naming/src/main/java/com/alibaba/nacos/naming/controllers/ServiceController.java, naming/src/main/java/com/alibaba/nacos/naming/controllers/ServiceControllerV2.java, naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/ConnectionBasedClientManager.java, naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/EphemeralIpPortClientManager.java, naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/PersistentIpPortClientManager.java, naming/src/main/java/com/alibaba/nacos/naming/core/v2/event/client/ClientEvent.java, naming/src/main/java/com/alibaba/nacos/naming/core/v2/index/ClientServiceIndexesManager.java, naming/src/main/java/com/alibaba/nacos/naming/healthcheck/ClientBeatProcessor.java, naming/src/main/java/com/alibaba/nacos/naming/healthcheck/HealthCheckCommon.java, naming/src/main/java/com/alibaba/nacos/naming/healthcheck/heartbeat/ClientBeatProcessorV2.java, naming/src/main/java/com/alibaba/nacos/naming/healthcheck/heartbeat/ExpiredInstanceChecker.java, naming/src/main/java/com/alibaba/nacos/naming/healthcheck/heartbeat/UnhealthyInstanceChecker.java, naming/src/main/java/com/alibaba/nacos/naming/healthcheck/v2/processor/HealthCheckCommonV2.java, naming/src/main/java/com/alibaba/nacos/naming/push/v2/task/PushExecuteTask.java, naming/src/main/java/com/alibaba/nacos/naming/remote/rpc/handler/InstanceRequestHandler.java, naming/src/main/java/com/alibaba/nacos/naming/remote/rpc/handler/SubscribeServiceRequestHandler.java, naming/src/test/java/com/alibaba/nacos/naming/healthcheck/v2/HealthCheckTaskV2Test.java
[ISSUE #8481 ]
Nacos目前尚无统一的trace统计功能模块，只在config配置中心有部分的trace日志，注册中心尚无trace功能。随着眼前推送轨迹功能需求以及后期诊断系统的设计需要，需要对nacos设计统一的trace模块，实现对Nacos服务注册，服务注销，服务推送，配置发布，配置推送等诸多事件的trace收集统计。
基于Nacos的事件机制设计统一的trace事件收集模块；
完成Nacos 注册中心主要主动操作事件traceEvent设计并埋点：
- 实例注册rpc
- 实例注册http
- 实例注销rpc
- 实例注销http
- 服务注册
- 服务注销
- 注册监听
- 注销监听
- 服务推送
对Nacos 注册中心主要被动操作事件traceEvent设计并埋点：
- 客户端断连
- 被动心跳检测：超时健康状态异常
- 被动心跳检测：健康状态异常超时实例移除
- 主动健康检查状态异常
=> [ISSUE#8481]Unified TRACE capacity building

naming/src/main/java/com/alibaba/nacos/naming/push/v2/executor/PushExecutor.java, naming/src/main/java/com/alibaba/nacos/naming/push/v2/executor/PushExecutorDelegate.java, naming/src/main/java/com/alibaba/nacos/naming/push/v2/executor/PushExecutorRpcImpl.java, naming/src/main/java/com/alibaba/nacos/naming/push/v2/executor/PushExecutorUdpImpl.java, naming/src/main/java/com/alibaba/nacos/naming/push/v2/task/NamingPushCallback.java, naming/src/main/java/com/alibaba/nacos/naming/push/v2/task/PushExecuteTask.java, naming/src/test/java/com/alibaba/nacos/naming/healthcheck/heartbeat/ClientBeatCheckTaskV2Test.java, naming/src/test/java/com/alibaba/nacos/naming/push/v1/NamingSubscriberServiceV1ImplTest.java, naming/src/test/java/com/alibaba/nacos/naming/push/v2/executor/PushExecutorDelegateTest.java, naming/src/test/java/com/alibaba/nacos/naming/push/v2/executor/PushExecutorRpcImplTest.java, naming/src/test/java/com/alibaba/nacos/naming/push/v2/executor/PushExecutorUdpImplTest.java, naming/src/test/java/com/alibaba/nacos/naming/push/v2/task/FixturePushExecutor.java, naming/src/test/java/com/alibaba/nacos/naming/push/v2/task/PushDelayTaskExecuteEngineTest.java
Naming push call back will filter hosts of service info. but the PushExecutor has do this operation once. So once push will do twice filter, which will cost double time and cpu.
What's more, after push success or failed, the service matadata may be changed, so the filter in callback may be different with the actual push serviceInfo.
- Abstract `NamingPushCallback`
- set `actualServiceInfo` to `NamingPushCallback` in `PushExecutor`
=> Enhance to remove double filter service info for push callback.

naming/src/test/java/com/alibaba/nacos/naming/healthcheck/v2/processor/HttpHealthCheckProcessorTest.java, sys/src/main/java/com/alibaba/nacos/sys/env/Constants.java, sys/src/main/java/com/alibaba/nacos/sys/utils/InetUtils.java, sys/src/test/java/com/alibaba/nacos/sys/utils/InetUtilsTest.java
- remove nacos.core.inet.auto-refresh property
- unregistered IPChangeEvent
- add some unit tests for InetUtils
Close #8515
XXXXX
XX
XXXX
=> [ISSUE #8515] Optimize some code in InetUtils

pom.xml
Explicitly specify ```spring-boot-maven-plugin``` version same as spring-boot by pluginManagement.
=> Explicitly specify spring-boot-maven-plugin version same as spring-boot

pom.xml
=> Bump mysql-connector-java from 8.0.21 to 8.0.28

distribution/conf/nacos-mysql.sql
The `id` column of the `his_config_info` table with length of 64 makes no sense.
Nothing
Unnecessary
=> Change the length of the id column of the his_config_info table to 20

naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/raft/RaftCore.java
=> [ISSUES #8635] fix a NPE when call the shutdown method

core/src/main/java/com/alibaba/nacos/core/cluster/remote/ClusterRpcClientProxy.java, core/src/test/java/com/alibaba/nacos/core/cluster/remote/ClusterRpcClientProxyTest.java, naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/v2/DistroClientTransportAgent.java, naming/src/test/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/v2/DistroClientTransportAgentTest.java
Fix #8099 .
- Fast failure for distro sync task and verify task if cluster disconnect.
=> [ISSUE#8099] Fast failure for distro sync task and verify task if cluster disconnect.

api/src/main/java/com/alibaba/nacos/api/naming/NamingService.java, api/src/main/java/com/alibaba/nacos/api/naming/utils/NamingUtils.java, client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingService.java, client/src/main/java/com/alibaba/nacos/client/naming/remote/NamingClientProxy.java, client/src/main/java/com/alibaba/nacos/client/naming/remote/NamingClientProxyDelegate.java, client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc/NamingGrpcClientProxy.java, client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc/redo/NamingGrpcRedoService.java, client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc/redo/RedoScheduledTask.java, client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc/redo/data/BatchInstanceRedoData.java, client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc/redo/data/InstanceRedoData.java, client/src/main/java/com/alibaba/nacos/client/naming/remote/http/NamingHttpClientProxy.java, client/src/test/java/com/alibaba/nacos/client/naming/remote/AbstractNamingClientProxyTest.java, client/src/test/java/com/alibaba/nacos/client/naming/remote/gprc/NamingGrpcClientProxyTest.java, naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/impl/EphemeralClientOperationServiceImpl.java
for #5863 nacos client support batchRegister request
XX
XXXX
=> [ISSUE#5863]add nacos client batchRegitserInstance request

address/src/main/java/com/alibaba/nacos/address/config/AddressServerSecurityConfiguration.java, address/src/main/java/com/alibaba/nacos/address/config/NacosSecurityConfiguration.java, address/src/test/java/com/alibaba/nacos/address/AddressServerControllerTests.java
=> [ISSUE #8701] ignore getServerList url

config/src/main/java/com/alibaba/nacos/config/server/service/datasource/DynamicDataSource.java, naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/impl/PersistentClientOperationServiceImpl.java, naming/src/main/java/com/alibaba/nacos/naming/healthcheck/v2/PersistentHealthStatusSynchronizer.java, naming/src/test/java/com/alibaba/nacos/naming/core/ClusterTest.java, naming/src/test/java/com/alibaba/nacos/naming/core/v2/service/impl/PersistentClientOperationServiceImplTest.java, naming/src/test/java/com/alibaba/nacos/naming/healthcheck/v2/PersistentHealthStatusSynchronizerTest.java
for #8653
1.持久化实例新增change操作
2.在jraft apply操作中校验client是否还存在，如果存在才更新实例
XXXX
=> [ISSUE#8653]Fix health check bug

common/src/main/java/com/alibaba/nacos/common/utils/IoUtils.java
[ISSUE#8906] An IOException has been catch，so throws IOException Is invalid
=> [ISSUE#8906] An IOException has been catch，so throws IOException Is invalid

common/src/main/java/com/alibaba/nacos/common/utils/IoUtils.java
Close IO by [try with resource] for model [nacos-common]
=> [ISSUE #8993]Close input stream and output stream by try with resource[nacos-common]

client/src/test/java/com/alibaba/nacos/client/naming/core/ServiceInfoUpdateServiceTest.java, naming/src/main/java/com/alibaba/nacos/naming/utils/ServiceUtil.java
Fix grpc push data not filter by cluster.
Fix grpc push data not filter by cluster.
=> Fix grpc push data not filter by cluster.

client/src/test/java/com/alibaba/nacos/client/config/impl/LimiterTest.java, core/src/main/java/com/alibaba/nacos/core/remote/control/TpsMonitorPoint.java, core/src/test/java/com/alibaba/nacos/core/cluster/lookup/LookupFactoryTest.java, core/src/test/java/com/alibaba/nacos/core/remote/control/TpsMonitorPointTest.java
performance optimization for #9014 
Refact `TpsMonitorPoint` methods: 
- `getTrimMillsOfSecond`,
- `getTrimMillsOfMinute`,
- `getTrimMillsOfHour`,
- `getTimeFormatOfSecond`.
pass test unit and jmh test
OS: macOS Monterey 12.5.1
CPU: M1 Pro
Memory: 16GB
```java
@BenchmarkMode({Mode.Throughput, Mode.AverageTime})
@OutputTimeUnit(TimeUnit.NANOSECONDS)
@State(Scope.Benchmark)
@Warmup(iterations = 5, time = 100, timeUnit = TimeUnit.MICROSECONDS)
@Measurement(iterations = 5, time = 10, timeUnit = TimeUnit.SECONDS)
@Fork(1)
public class JmhTpsMonitorPoint {
@Benchmark
public void measureGetTrimMillsOfSecond() {
TpsMonitorPoint.getTrimMillsOfSecond(1661235833111L);
}
@Benchmark
public void measureGetTrimMillsOfMinute() { …
```
=> [ISSUE #9014] performance optimization--refacte TpsMonitorPoint

common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClient.java, common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClient.java, common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcConsts.java, common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcSdkClient.java, common/src/test/java/com/alibaba/nacos/common/remote/client/RpcClientTest.java, common/src/test/java/com/alibaba/nacos/common/remote/client/grpc/GrpcConstsTest.java
Fix the issue #9013 
添加GrpcClient健康检查可重试机制
e.g.  nacos.remote.client.grpc.health.retry  
nacos.remote.client.grpc.health.timeout
XXXXX
XX
XXXX
=> Add configurable for GrpcClient health check retry times

plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/derby/ConfigInfoAggrMapperByDerby.java, plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/derby/ConfigInfoBetaMapperByDerby.java, plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/derby/ConfigInfoMapperByDerby.java, plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/mysql/ConfigInfoMapperByMySql.java, plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/ConfigInfoMapper.java, plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/ConfigTagsRelationMapper.java
For issue#8312
Update the mappers.
XXXX
=> [ISSUE #8312]Update the mappers.

.github/workflows/ci.yml, .github/workflows/it.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
=> GitHub Workflows security hardening

config/src/main/java/com/alibaba/nacos/config/server/service/datasource/ExternalDataSourceServiceImpl.java
=> For #8611, Close old datasource connection.

common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/DefaultGrpcClientConfig.java, core/src/main/java/com/alibaba/nacos/core/cluster/MemberUtil.java, core/src/main/java/com/alibaba/nacos/core/cluster/ServerMemberManager.java, core/src/main/java/com/alibaba/nacos/core/controller/NacosClusterController.java, core/src/test/java/com/alibaba/nacos/core/cluster/MemberUtilTest.java, core/src/test/java/com/alibaba/nacos/core/cluster/ServerMemberManagerTest.java, core/src/test/java/com/alibaba/nacos/core/controller/NacosClusterControllerTest.java
Fixes #8650 .
- cluster/report api return self information.
- Update metadata when received report response.
- Add UT.
=> [ISSUE#8650] Make cluster/report both receive and send metadata.

common/src/main/java/com/alibaba/nacos/common/notify/listener/Subscriber.java
see #9227
修复旧版本nacos-client升级到2.1.1导致自定义订阅事件失效问题
#8433 中在 com.alibaba.nacos.common.notify.listener.Subscriber 增加了 scopeMatches方法，用于区分事件的作用域 , 区分作用域的逻辑在子类中已经进行了重写 , 所以父类默认返回true即可
=> [ISSUE #9227] fix subscriber scopeMatches

console/pom.xml, console/src/main/resources/application.properties, distribution/conf/application.properties, distribution/conf/application.properties.example, distribution/conf/nacos-logback.xml, k8s-sync/pom.xml, k8s-sync/src/main/java/com/alibaba/nacos/k8s/sync/K8sSyncConfig.java, k8s-sync/src/main/java/com/alibaba/nacos/k8s/sync/K8sSyncServer.java, k8s-sync/src/main/java/com/alibaba/nacos/k8s/sync/Loggers.java, pom.xml
For issue #8309
Sync services and endpoints from k8s.
=> [ISSUE #8309] Sync services and endpoints from k8s

naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/v2/DistroClientDataProcessor.java, naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/AbstractClient.java, naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/impl/ConnectionBasedClient.java, naming/src/main/java/com/alibaba/nacos/naming/core/v2/pojo/BatchInstancePublishInfo.java, naming/src/test/java/com/alibaba/nacos/naming/core/v2/client/AbstractClientTest.java, naming/src/test/java/com/alibaba/nacos/naming/core/v2/client/MockAbstractClient.java, naming/src/test/java/com/alibaba/nacos/naming/core/v2/client/impl/ConnectionBasedClientTest.java
Fixes #9210.
ConnectionBasedClient support add revision
=> [ISSUE#9210] ConnectionBasedClient support add revision

client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java
[issue](https://github.com/alibaba/nacos/issues/9282)
=> [ISSUE #9282]remove redundant judgment

client/src/main/java/com/alibaba/nacos/client/config/impl/CacheData.java, client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java
fix cache removed when listener add delay
=> fix cache removed when listeneradd delay

api/src/main/java/com/alibaba/nacos/api/PropertyKeyConst.java, client/src/main/java/com/alibaba/nacos/client/naming/core/ServiceInfoUpdateService.java
The naming async query is for protect the UDP push failed. And in 2.0, we keep this featrue in early version for protecting some unknown problem for gRPC push.
In 2.0.X, we foung the conflicts in `reflections` package will cause the push data can't be deserializated. 
After 2.1.0, nacos-client remove the dependency of `reflections` , and not fount any problem for handle push data from server.
So we plan add an swithes to close the async query feature in 2.1.2, and set the default value as close in 2.2.X. If no problem, will remove this feature in 2.3.X or 3.X.
Add switch for naming async query.
XXXX
=> Add switch for naming async query.

naming/src/main/java/com/alibaba/nacos/naming/web/ServiceNameFilter.java
=> [ISSUE#9323]1.x http接口服务名校验问题

config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedStoragePersistServiceImpl.java, config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java, plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/derby/ConfigInfoAggrMapperByDerby.java, plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/derby/ConfigInfoBetaMapperByDerby.java, plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/derby/ConfigInfoMapperByDerby.java, plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/derby/ConfigInfoTagMapperByDerby.java, plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/derby/ConfigInfoTagsRelationMapperByDerby.java, plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/derby/HistoryConfigInfoMapperByDerby.java, plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/mysql/ConfigInfoAggrMapperByMySql.java, plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/mysql/ConfigInfoBetaMapperByMySql.java, plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/mysql/ConfigInfoMapperByMySql.java, plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/mysql/ConfigInfoTagMapperByMySql.java, plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/mysql/ConfigTagsRelationMapperByMySql.java, plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/mysql/HistoryConfigInfoMapperByMySql.java, plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/AbstractMapper.java, plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/ConfigInfoAggrMapper.java, plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/ConfigInfoBetaMapper.java, plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/ConfigInfoMapper.java, plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/ConfigInfoTagMapper.java, plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/HistoryConfigInfoMapper.java, plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/Mapper.java
=> [ISSUE #8312]Merge sql.

plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/persistence/ExternalRolePersistServiceImpl.java, plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/persistence/ExternalUserPersistServiceImpl.java
优化模糊查询，使SQL就可以通用性地适配其他可能接入的数据库，减少未来插件开发者的扩展插件的时候，还需要触碰主分支。
=> [ISSUE #9414] Optimize fuzzy queries to make SQL more general

console-ui/src/components/NameSpaceList/NameSpaceList.js
修复样式，存在多行 namespace后，显示不全。
修复样式
修复样式，存在多行 namespace后，显示不全。
=> [ISSUE #9437] [ISSUE #9408] fix style NameSpaceList.js

core/src/main/java/com/alibaba/nacos/core/listener/LoggingApplicationListener.java, core/src/main/java/com/alibaba/nacos/core/listener/NacosApplicationListener.java, core/src/main/java/com/alibaba/nacos/core/listener/StartingApplicationListener.java, naming/src/main/java/com/alibaba/nacos/naming/misc/GracefulShutdownListener.java
=> [ISSUE #9459] Modify the method modifier of NacosApplicationListener to default

client/src/main/java/com/alibaba/nacos/client/logging/AbstractNacosLogging.java, client/src/main/java/com/alibaba/nacos/client/logging/log4j2/Log4J2NacosLogging.java, client/src/main/java/com/alibaba/nacos/client/logging/log4j2/NacosClientPropertiesLookup.java, client/src/main/java/com/alibaba/nacos/client/logging/logback/NacosClientPropertyAction.java, client/src/main/java/com/alibaba/nacos/client/logging/logback/NacosJoranConfigurator.java, client/src/main/resources/nacos-log4j2.xml, client/src/main/resources/nacos-logback.xml, client/src/test/java/com/alibaba/nacos/client/logging/log4j2/NacosClientPropertiesLookupTest.java, client/src/test/java/com/alibaba/nacos/client/logging/logback/NacosClientPropertyActionTest.java
- Replace system.getProperties and system.getEnv with  NacosClientProperties
- log4j and logback support reading properties from NacosClientProperties
relate #9356
XXXXX
XX
XXXX
=> [ISSUE #8622] sub pr of 9356 - logging module

console/src/main/resources/application.properties, distribution/conf/application.properties, distribution/conf/application.properties.example, plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/LdapAuthConfig.java, plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/LdapAuthenticationProvider.java, plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/constant/AuthConstants.java, plugin-default-impl/src/test/java/com/alibaba/nacos/plugin/auth/impl/LdapAuthenticationProviderTest.java
解决nacos提供的默认ldap鉴权实现更好的适配ldap服务（如微软AD域控）用户名不区分大小写的情况。
XX
默认情况下是改实现是大小写敏感的，也可以通过设置nacos.core.auth.ldap.case.sensitive=false调整默认ldap鉴权插件的用户名为大小写不敏感。
=> resolve issue #9318 add ldap filter config:caseSensitive

config/src/main/java/com/alibaba/nacos/config/server/service/capacity/GroupCapacityPersistService.java, config/src/main/java/com/alibaba/nacos/config/server/service/capacity/TenantCapacityPersistService.java, config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java, plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/AbstractMapper.java, plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/Mapper.java
#9497 
针对ISSUE9497进行处理，替换了Statement.RETURN_GENERATED_KEYS为通用的new String[]{"id"}，避免开发者开发数据库适配插件时，需要更改主分支的问题：
修改内容涉及到：
config_info发布配置接口
tenant_capacity
group_capacity
目前核心影响数据库适配插件开发者的相关改动点，就剩下这几个了。其他的未来有待发现
1、项目启动后，测试新增配置
2、可以测试其他适配的数据库插件
=> [ISSUE #9497]Update some class method from RETURN_GENERATED_KEYS replace to new String[]{"id"},Avoid database compatibility issues

console-ui/src/components/NameSpaceList/NameSpaceList.js, console-ui/src/pages/ConfigurationManagement/ConfigurationManagement/ConfigurationManagement.js
fix #9584 
change overflow hidden to visible in configuration query div
=> [ISSUE #9584]: change overflow hidden to visible in configuration query div

distribution/bin/startup.cmd, distribution/bin/startup.sh
fix #9020
prefix CUSTOM_SEARCH_LOCATIONS with 'optional:' in startup.sh/startup.cmd
XXXX
=> fix #9020, prefix CUSTOM_SEARCH_LOCATIONS with 'optional:'

client/src/main/java/com/alibaba/nacos/client/naming/remote/http/NamingHttpClientProxy.java
fix issue #9615 
fixed the issue of client get same server
After modification, the client will get a random server.
修改后客户端将获得随机的server地址。
=> [ISSUE #9615] fixed the issue of client get same server

config/src/main/java/com/alibaba/nacos/config/server/exception/GlobalExceptionHandler.java, console/src/main/java/com/alibaba/nacos/console/exception/ConsoleExceptionHandler.java
fix #9655
修复一个bug，该bug会让AccessException被提前捕获从而导致HttpResponse取得错误的返回
=> [ISSUE #9655] fix ExceptionHandler order bug

istio/src/main/java/com/alibaba/nacos/istio/mcp/McpConnection.java, istio/src/main/java/com/alibaba/nacos/istio/xds/XdsConnection.java
The onNext operation of grpc stream oberver is not thread-safe. So we must synchronize calls on push.
=> Fix data race in xds.

plugin-default-impl/pom.xml, plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/JwtTokenManager.java, plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/NacosAuthManager.java, plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/filter/JwtAuthenticationTokenFilter.java, plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/jwt/NacosJwtParser.java, plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/jwt/NacosJwtPayload.java, plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/jwt/NacosSignatureAlgorithm.java, plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/roles/NacosRoleServiceImpl.java, plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/users/NacosUser.java, plugin-default-impl/src/test/java/com/alibaba/nacos/plugin/auth/impl/JwtTokenManagerTest.java, plugin-default-impl/src/test/java/com/alibaba/nacos/plugin/auth/impl/controller/UserControllerTest.java, plugin-default-impl/src/test/java/com/alibaba/nacos/plugin/auth/impl/jwt/NacosJwtParserTest.java
优化jwt相关的方法性能.优化结果如下(详细测试结果参考[此处](https://github.com/YunWZ/nacos/blob/5461b254e176a4104702b2b850b6e9b69dd1d914/microbench/src/main/resources/result/optimize/perf-jwt-finally.txt)):
```text
Benchmark                                                           Mode  Cnt     Score    Error   Units
JwtTokenManagerBenchmark.measureCreateNewTokenForNacosJwtParser32  thrpt   20    ≈ 10⁻⁴           ops/ns
JwtTokenManagerBenchmark.measureCreateNewTokenForNacosJwtParser48  thrpt   20    ≈ 10⁻⁴           ops/ns
JwtTokenManagerBenchmark.measureCreateNewTokenForNacosJwtParser64  thrpt   20    ≈ 10⁻⁴           ops/ns
JwtTokenManagerBenchmark.measureCreateTokenForManager              thrpt   20    ≈ 10⁻⁴           ops/ns
JwtTokenManagerBenchmark.measureValidForManager                    thrpt   20    ≈ …
```
=> [ISSUE #9859]使用自定义的JWT生成/验证方法,而不依赖于`jjwt`.

plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/CustomAuthenticationProvider.java, plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/JwtAuthenticationEntryPoint.java, plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/JwtTokenManager.java, plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/LdapAuthConfig.java, plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/LdapAuthPluginService.java, plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/LdapAuthenticationProvider.java, plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/NacosAuthConfig.java, plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/NacosAuthManager.java, plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/NacosAuthPluginService.java, plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/authenticate/AbstractAuthenticationManager.java, plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/authenticate/AuthenticationNamagerDelegator.java, plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/authenticate/DefaultAuthenticationManager.java, plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/authenticate/IAuthenticationManager.java, plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/authenticate/LdapAuthenticationManager.java, plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/constant/AuthConstants.java, plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/controller/UserController.java, plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/roles/NacosRoleServiceImpl.java, plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/users/NacosUser.java, plugin-default-impl/src/test/java/com/alibaba/nacos/plugin/auth/impl/controller/UserControllerTest.java, plugin-default-impl/src/test/java/com/alibaba/nacos/plugin/auth/impl/jwt/NacosJwtParserTest.java
重构默认插件的登陆/鉴权逻辑, 提高性能.
不使用`Spring-Security`中的登陆鉴权逻辑,由鉴权插件自己实现:
1. 优化登陆接口的逻辑,避免重复验证jwt(登陆时由插件自己生成令牌,无需重复验证);
2. 优化AcessToken的验证逻辑;
XXXX
=> [ISSUE #9859] 重构默认插件的登陆/鉴权逻辑

api/src/test/java/com/alibaba/nacos/api/ability/ClientAbilitiesTest.java, api/src/test/java/com/alibaba/nacos/api/ability/ServerAbilitiesTest.java, api/src/test/java/com/alibaba/nacos/api/config/ability/ClientRemoteAbilityTest.java, api/src/test/java/com/alibaba/nacos/api/config/ability/ServerRemoteAbilityTest.java, api/src/test/java/com/alibaba/nacos/api/remote/ability/ClientRemoteAbilityTest.java, api/src/test/java/com/alibaba/nacos/api/remote/ability/ServerRemoteAbilityTest.java, naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/InstanceMetadataProcessor.java, naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/NamingMetadataManager.java, naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/ServiceMetadataProcessor.java
Enhance the metadata operation stability. Handling the problem of when metadata operation throw an exception without message, the exception will be replaced by NPE and the statu machine will stop.
=> Judge the message whether null for metadata processor.

console/src/main/resources/application.properties, distribution/conf/application.properties, plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/token/impl/JwtTokenManager.java
=> Remove the default token.secret.key

client/pom.xml, client/src/main/java/com/alibaba/nacos/client/logging/logback/LogbackNacosLogging.java, client/src/main/java/com/alibaba/nacos/client/logging/logback/NacosClientLogbackProperties.java, client/src/main/java/com/alibaba/nacos/client/logging/logback/NacosLogbackConfiguratorAdapterV1.java, client/src/main/resources/META-INF/services/com.alibaba.nacos.common.log.NacosLogbackConfigurator, client/src/main/resources/META-INF/services/com.alibaba.nacos.common.log.NacosLogbackProperties, common/src/main/java/com/alibaba/nacos/common/log/NacosLogbackConfigurator.java, common/src/main/java/com/alibaba/nacos/common/log/NacosLogbackProperties.java
**issue**:#9860
**修改方案**：
1.通过判断高版本的类是否存在选择不同版本的api
2.通过spi的方式+新增logback-adapter的依赖解决不同版本api存在同一个项目中编译报错的问题，依赖项目https://github.com/nacos-group/logback-adpater
**测试场景**：
1.2.9 版本的logback的demo服务使用该依赖启动可正常加载logback配置
1.4.5 版本的logback的demo服务使用该依赖启动可正常加载logback配置
=> [ISSUE #9860] abstract the nacos logback configurator to solve the problem between different version

core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcServerConstants.java
Unified use of millisecond time units
XX
XXXX
=> [ISSUE #9954] Unified use of millisecond time units

client/src/main/java/com/alibaba/nacos/client/env/SearchableProperties.java, client/src/main/java/com/alibaba/nacos/client/logging/AbstractNacosLogging.java, client/src/main/resources/nacos-log4j2.xml, client/src/main/resources/nacos-logback.xml
=> [ISSUES #10029] optimize SearchableProperties building code

client/src/main/java/com/alibaba/nacos/client/config/impl/LocalConfigInfoProcessor.java, client/src/main/java/com/alibaba/nacos/client/env/NacosClientProperties.java, client/src/main/java/com/alibaba/nacos/client/env/SearchableProperties.java, client/src/main/java/com/alibaba/nacos/client/env/SourceType.java, client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingService.java, client/src/main/java/com/alibaba/nacos/client/naming/utils/InitUtils.java, client/src/main/java/com/alibaba/nacos/client/utils/ParamUtil.java, client/src/test/java/com/alibaba/nacos/client/env/NacosClientPropertiesTest.java
=> [ISSUES #10014] clear confused logic about namespace properties

plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/MapperManager.java, plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/proxy/MapperProxy.java
=> [ISSUE #10159]修改mapperProxy单例

pom.xml
remove httpasyncclient version dependency management, avoid version conflicts
I find spring boot parent had httpasyncclient version dependency management,  conflicting with own version
Avoid this issue  https://github.com/alibaba/nacos/issues/7698 from happening again
=> [ISSUE #7698] refactor: remove httpasyncclient version dependency management,  avoid version conflicts

distribution/conf/application.properties
1. expose prometheus endpoint for metrics.
2. expose health endpoint for SLB healthcheck.
3. switch on mbean for tomcat, so we can collect tomcat metrics.
4. use one file per hour for tomcat access log
=> [ISSUE #10206] Optimize nacos default application.properties configuration

client/src/main/java/com/alibaba/nacos/client/naming/backups/FailoverReactor.java
Failover file path should be like `{user.home}/naming/{group}/failover/00-00---000-VIPSRV_FAILOVER_SWITCH-000---00-00`.
XXXXX
XX
XXXX
=> [ISSUE #10271] Fix failover file path.

api/src/main/java/com/alibaba/nacos/api/config/ConfigService.java, client/src/main/java/com/alibaba/nacos/client/config/NacosConfigService.java, client/src/main/java/com/alibaba/nacos/client/config/filter/impl/ConfigFilterChainManager.java
=> Expose way to add config filter

common/src/main/java/com/alibaba/nacos/common/remote/TlsConfig.java, common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/DefaultGrpcClientConfig.java, common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClient.java, common/src/test/java/com/alibaba/nacos/common/remote/client/RpcClientFactoryTest.java
取消默认使用openssl作为provider，系统会自动选择
XX
XXXX
=> 取消默认openssl

config/src/main/java/com/alibaba/nacos/config/server/remote/RpcConfigChangeNotifier.java
Update log output in RpcConfigChangeNotifier.java when push fail
fix #10310 
XX
XXXX
=> [ISSUE #10310] Update log output in RpcConfigChangeNotifier.java when push fail

pom.xml
[bot pr#10648] Optimize Guava Dependency
Remove guava dependencyManagement, and imported by grpc.
According to the result of `mvn dependency:tree`, the actually version of guava is `31.1-android`,which imported by `grpc-netty-shaded`.
=> [bot pr#10648] Optimize Guava Dependency

console/src/main/java/com/alibaba/nacos/console/exception/ConsoleExceptionHandler.java
relation #10640
在 ExceptionHandler 中，返回的数据如果存在 html 标签，则可能导致前端出现一些特殊情况，所以对于未知的 Exception 返回 body 部分增加 html 转义
XX
XXXX
=> ExceptionHandler 中 Exception 部分返回 body 参数增加 html 转义

console-ui/src/pages/AuthorityControl/PermissionsManagement/NewPermissions.js, console-ui/src/pages/ConfigurationManagement/ConfigurationManagement/ConfigurationManagement.js
- fix the warnings: `Each child in a list should have a unique "key" prop` in the nacos  admin UI console
=> FIX: Warning: Each child in a list should have a unique "key" prop

console-ui/src/index.scss
- Healthy instance displays green and unhealthy instance displays red, which  is a good UI function for users, However the new UI has overridden it, resume it.
- Tested by `Chrome  114.0.5735.198 (x86_64)` and `Safari 15.2 (17612.3.6.1.6)`
=> Service instance should display related color when healthy or unhealthy

config/src/main/java/com/alibaba/nacos/config/server/aspect/ConfigOpFailureAspect.java
feat(#10539): When the operation configuration fails, log.
=> feat(#10539): When the operation configuration fails, log.

prometheus/src/main/java/com/alibaba/nacos/prometheus/controller/PrometheusController.java, prometheus/src/test/java/com/alibaba/nacos/prometheus/controller/PrometheusControllerTest.java
Refactor Prometheus Module
1. Extract common method to get service array node.
2. Complete prometheus controller test case.
=> Refactor Prometheus Module

common/src/main/java/com/alibaba/nacos/common/paramcheck/ParamCheckRules.java
fix the param check rule
change the param check rule 
XXXX
* [Y] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [Y] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [Y] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [Y] Write …
=> For #10734,fix the param check rule

plugin/control/src/main/java/com/alibaba/nacos/plugin/control/ruleactivator/DiskUtils.java, plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/mysql/ConfigInfoAggrMapperByMySql.java, plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/AbstractMapper.java, plugin/datasource/src/test/java/com/alibaba/nacos/plugin/datasource/mapper/AbstractMapperTest.java
Reactor code in datasource-plugin
1. Extract common method to append where clause in `AbstractMapper`, in order to reduce duplicated code.
2. Remove unnecessary boxing in `ConfigInfoAggrMapperByMySql`.
3. Fix word spelling in `DiskUtils`.
4. Complete AbstractMapper Test Case.
=> Reactor code in datasource-plugin

naming/src/main/java/com/alibaba/nacos/naming/remote/rpc/handler/BatchInstanceRequestHandler.java, naming/src/main/java/com/alibaba/nacos/naming/remote/rpc/handler/InstanceRequestHandler.java, naming/src/main/java/com/alibaba/nacos/naming/utils/InstanceUtil.java, naming/src/test/java/com/alibaba/nacos/naming/remote/rpc/handler/BatchInstanceRequestHandlerTest.java, naming/src/test/java/com/alibaba/nacos/naming/remote/rpc/handler/InstanceRequestHandlerTest.java, naming/src/test/java/com/alibaba/nacos/naming/utils/InstanceUtilTest.java
feat(#5608 && #10223): When the custom instance id is empty, the id will be automatically generated.
=> feat(#5608 && #10223): When the custom instance id is empty, the id will be automatically generated.

client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingService.java, client/src/main/java/com/alibaba/nacos/client/naming/core/ServiceInfoUpdateService.java, client/src/main/java/com/alibaba/nacos/client/naming/remote/NamingClientProxy.java, client/src/main/java/com/alibaba/nacos/client/naming/remote/NamingClientProxyDelegate.java, client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc/NamingGrpcClientProxy.java, client/src/main/java/com/alibaba/nacos/client/naming/remote/http/NamingHttpClientProxy.java, client/src/test/java/com/alibaba/nacos/client/naming/NacosNamingServiceTest.java, client/src/test/java/com/alibaba/nacos/client/naming/core/ServiceInfoUpdateServiceTest.java, client/src/test/java/com/alibaba/nacos/client/naming/remote/AbstractNamingClientProxyTest.java, client/src/test/java/com/alibaba/nacos/client/naming/remote/NamingClientProxyDelegateTest.java, client/src/test/java/com/alibaba/nacos/client/naming/remote/gprc/NamingGrpcClientProxyTest.java, client/src/test/java/com/alibaba/nacos/client/naming/remote/http/NamingHttpClientProxyTest.java
Remove udp port param for v1-client
#10824
=> [ISSUE #10824] Remove udp port param for v1-client

client/src/main/java/com/alibaba/nacos/client/naming/cache/ServiceInfoHolder.java, client/src/main/java/com/alibaba/nacos/client/naming/event/InstancesChangeEvent.java, client/src/main/java/com/alibaba/nacos/client/naming/event/InstancesChangeNotifier.java, client/src/main/java/com/alibaba/nacos/client/naming/event/InstancesDiff.java, client/src/main/java/com/alibaba/nacos/client/naming/listener/AbstractNamingChangeListener.java, client/src/main/java/com/alibaba/nacos/client/naming/listener/NamingChangeEvent.java, client/src/test/java/com/alibaba/nacos/client/naming/event/InstancesChangeEventTest.java, client/src/test/java/com/alibaba/nacos/client/naming/event/InstancesChangeNotifierTest.java, client/src/test/java/com/alibaba/nacos/client/naming/event/InstancesDiffTest.java, client/src/test/java/com/alibaba/nacos/client/naming/listener/NamingChaneEventTest.java, client/src/test/java/com/alibaba/nacos/client/naming/listener/NamingChangeEventTest.java
For [#10374](https://github.com/alibaba/nacos/issues/10374), support listener to get changed instances.
* Add `InstancesDiff` and `NamingChangeEvent` to get the changed instances.
* Add `AbstractNamingChangeListener` for `NamingChangeEvent`.
* Update `InstancesChangeEvent`, `InstancesChangeNotifier`, `ServiceInfoHolder`.
=> [ISSUE #10374] Support listener to get changed instances

plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/token/impl/JwtTokenManager.java
=> [ISSUE#10921] Fix login failed when close auth.

common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClient.java, common/src/test/java/com/alibaba/nacos/common/remote/client/RpcClientTest.java
=> Fix RpcClient retries.(#10952)

console-ui/src/pages/AuthorityControl/PermissionsManagement/PermissionsManagement.js, console-ui/src/pages/AuthorityControl/RolesManagement/RolesManagement.js, console-ui/src/pages/AuthorityControl/UserManagement/UserManagement.js
- How to reproduce this bug:
> Suppose that I have 10 pages users data, when I jump to page 4, then I search username like "bob"
>     then I search for nothing, in fact the data in the page 2, the parameter pageNo should 
>     be reset to 1, not 4.
- The paging backend api seems not to work, I'll create another PR to fix it.
=> Permission related pages should reset pageNum when searching

core/src/main/java/com/alibaba/nacos/core/remote/ConnectionManager.java
Fix word spelling in `ConnectionManager`
=> Fix word spelling in `ConnectionManager`

api/src/main/java/com/alibaba/nacos/api/naming/selector/NamingContext.java, api/src/main/java/com/alibaba/nacos/api/naming/selector/NamingResult.java, api/src/main/java/com/alibaba/nacos/api/naming/selector/NamingSelector.java, api/src/main/java/com/alibaba/nacos/api/selector/client/SelectResult.java, api/src/main/java/com/alibaba/nacos/api/selector/client/Selector.java, client/src/main/java/com/alibaba/nacos/client/naming/event/InstancesDiff.java, client/src/main/java/com/alibaba/nacos/client/naming/listener/NamingChangeEvent.java, client/src/main/java/com/alibaba/nacos/client/naming/selector/DefaultNamingSelector.java, client/src/main/java/com/alibaba/nacos/client/naming/selector/NamingListenerInvoker.java, client/src/main/java/com/alibaba/nacos/client/naming/selector/NamingSelectorWrapper.java, client/src/main/java/com/alibaba/nacos/client/selector/AbstractSelectorWrapper.java, client/src/main/java/com/alibaba/nacos/client/selector/ListenerInvoker.java, client/src/main/java/com/alibaba/nacos/client/selector/SelectorFactory.java, client/src/main/java/com/alibaba/nacos/client/selector/SelectorManager.java, client/src/main/java/com/alibaba/nacos/client/selector/SelectorWrapper.java, client/src/test/java/com/alibaba/nacos/client/naming/event/InstancesDiffTest.java, client/src/test/java/com/alibaba/nacos/client/naming/selector/DefaultNamingSelectorTest.java, client/src/test/java/com/alibaba/nacos/client/naming/selector/NamingListenerInvokerTest.java, client/src/test/java/com/alibaba/nacos/client/naming/selector/NamingSelectorWrapperTest.java, client/src/test/java/com/alibaba/nacos/client/selector/SelectorFactoryTest.java, client/src/test/java/com/alibaba/nacos/client/selector/SelectorManagerTest.java
For [#10374](https://github.com/alibaba/nacos/issues/10374), Define selectors and related components.
* **nacos-api :** Add `Selector`、`NamingSelector` and `NamingContext`.
* **nacos-client:** Add `DefaultNamingSelector`、 `ListenerInvoker`、`NamingListenerInvoker`、`AbstractSelectorWrapper`、`NamingSelectorWrapper`、`SelectorManager` and `SelectorFactory`。
* Add unit tests.
* Update `InstancesDiff`.
=> [ISSUE #10374] Define selectors and related components

naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/v2/DistroClientDataProcessor.java
Fix [ISSUE #10975]
The grpc disconnect will add clean expire InstanceMetadataEvent job , and will clean the expired job after it reconnected in 60 seconds .
But clean expired job is only in the register instance nacos server ,the other ones not perform this , and will remove the InstanceMetadata when the job time occur, and this will make the service offline next time it reconnect
Add the clean expire InstanceMetadataEvent after the distro process got the instance register event !
XXXX
=> [ISSUE #10975] Fix gRpc reconnect will cause service offline after next register connection come in

client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java
#11020 The taskId is always less than 0
=> [ISSUE #11020] The taskId is always less than 0 (#11020)

config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigChangeListenContext.java
fix(#10980 ): After connectionIds.remove(connectionId) is executed, if connectionsIds is empty, clear the k-v corresponding to groupKeyContext.
fix(#10980 ): After connectionIds.remove(connectionId) is executed, if connectionsIds is empty, clear the k-v corresponding to groupKeyContext.
fix(#10980 ): After connectionIds.remove(connectionId) is executed, if connectionsIds is empty, clear the k-v corresponding to groupKeyContext.
=> fix(#10980 ): After connectionIds.remove(connectionId) is executed, if connectionsIds is empty, clear the k-v corresponding to groupKeyContext.

config/src/main/java/com/alibaba/nacos/config/server/model/CacheItem.java, config/src/main/java/com/alibaba/nacos/config/server/service/ConfigCacheService.java
(Fix #10963 ) In CacheItem, it's better to use the private and final keywords to modify the member variable rwLock.
(Fix #10963 ) In CacheItem, it's better to use the private and final keywords to modify the member variable rwLock.
=> In CacheItem, it's better to use the private and final keywords to modify the member variable rwLock.

client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java, client/src/main/java/com/alibaba/nacos/client/config/impl/ServerListChangeEvent.java, client/src/main/java/com/alibaba/nacos/client/config/impl/ServerListManager.java
fix(#11083 ): Standardize the naming of the ServerlistChangeEvent class.
=> fix(#11083): Standardize the naming of the ServerlistChangeEvent class.

common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClient.java
Remove unnecessary judgment
update GrpcClient
XXXX
=> [Refactor]Remove unnecessary judgment

api/src/main/java/com/alibaba/nacos/api/naming/NamingService.java, client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingService.java, client/src/main/java/com/alibaba/nacos/client/naming/core/ServiceInfoUpdateService.java, client/src/main/java/com/alibaba/nacos/client/naming/event/InstancesChangeNotifier.java, client/src/main/java/com/alibaba/nacos/client/naming/selector/NamingSelectorWrapper.java, client/src/main/java/com/alibaba/nacos/client/selector/SelectorFactory.java, client/src/main/java/com/alibaba/nacos/client/selector/SelectorManager.java, client/src/test/java/com/alibaba/nacos/client/naming/NacosNamingServiceTest.java, client/src/test/java/com/alibaba/nacos/client/naming/event/InstancesChangeNotifierTest.java, client/src/test/java/com/alibaba/nacos/client/naming/selector/NamingSelectorWrapperTest.java, client/src/test/java/com/alibaba/nacos/client/selector/SelectorManagerTest.java
For [#10374](https://github.com/alibaba/nacos/issues/10374), Select clusters using the selector
* **nacos-api :** Update `NamingService`.
* **nacos-client :** Update `NacosNamingService`, `InstancesChangeNotifier`, `ServiceInfoUpdateService` and `SelectorManager`.
=> [ISSUE #10374] Select clusters using the selector

config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigController.java
=> [ISSUE #11100] Update ConfigController.java, add srcUser when delete config by ids

persistence/src/main/java/com/alibaba/nacos/persistence/constants/PersistenceConstant.java, persistence/src/main/java/com/alibaba/nacos/persistence/repository/embedded/EmbeddedPaginationHelperImpl.java, persistence/src/main/java/com/alibaba/nacos/persistence/repository/extrnal/ExternalStoragePaginationHelperImpl.java
Fix issues https://github.com/alibaba/nacos/issues/10973
支持后台分页查询用户
在PaginationHelper插件的fetchPage 分页方法中，追加拼接sql的分页条件的逻辑。
多造点用户数据，在对应的页面操作即可验证
=> Fix issues #10973 支持后台分页查询用户

config/src/main/java/com/alibaba/nacos/config/server/service/LongPollingService.java, config/src/main/java/com/alibaba/nacos/config/server/service/capacity/GroupCapacityPersistService.java, config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedConfigInfoAggrPersistServiceImpl.java, config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedConfigInfoBetaPersistServiceImpl.java, config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedConfigInfoPersistServiceImpl.java, config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedConfigInfoTagPersistServiceImpl.java, config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedHistoryConfigInfoPersistServiceImpl.java, config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedStoragePersistServiceImpl.java, config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalConfigInfoBetaPersistServiceImpl.java, config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalConfigInfoPersistServiceImpl.java, config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalConfigInfoTagPersistServiceImpl.java, config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalHistoryConfigInfoPersistServiceImpl.java, config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java
1、alternate string method.
2、alternate 'Arrays.as(SingleString)' method.
3、a repeat intercept exception
remark: public class EmptyResultDataAccessException extends IncorrectResultSizeDataAccessException
=> [#11035] (PR-4/4) config module, alternate string method.

client/src/main/resources/nacos-log4j2.xml
=> [ISSUE #11132]feat: Add a rolling deletion strategy to solve the hidden danger of unlimited number of log files

common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClient.java
In the RecAbilityContext class, the await method now returns a value indicating whether a response from the server has been received. Upon receiving a server response, it is considered successful; otherwise, it is regarded as a registration failure.
For #10797
XXXX
=> [ISSUE #10797]Enhance the registration logic.

auth/src/main/java/com/alibaba/nacos/auth/config/AuthConfigs.java, config/src/main/java/com/alibaba/nacos/config/server/configuration/ConfigChangeConfigs.java, core/src/main/java/com/alibaba/nacos/core/remote/tls/RpcServerTlsConfig.java, sys/src/main/java/com/alibaba/nacos/sys/utils/PropertiesUtil.java, sys/src/test/java/com/alibaba/nacos/sys/utils/PropertiesUtilTest.java
The Nacos source code startup results in an error as follows:
```
2023-10-09 21:26:50.729  WARN 4688 --- [           main] c.a.n.c.s.c.ConfigChangeConfigs          : [ConfigChangeConfigs]Refresh config plugin properties failed 
java.lang.reflect.InvocationTargetException: null
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.alibaba.nacos.sys.utils.PropertiesUtil.handleSpringBinder(PropertiesUtil.java:62)
at com.alibaba.nacos.sys.utils.PropertiesUtil.getPropertiesWithPrefix(PropertiesUtil.java:35)
at …
```
=> [ISSUE #11231]Optimize the handleSpringBinder method in PropertiesUtil.

common/src/test/java/com/alibaba/nacos/common/pathencoder/PathEncoderManagerTest.java
=> [ISSUE #11255]Update PathEncoderManagerTest#testEncodeWithNonExistOs.

core/src/test/java/com/alibaba/nacos/core/remote/grpc/negotiator/tls/DefaultTlsContextBuilderTest.java, core/src/test/java/com/alibaba/nacos/core/remote/grpc/negotiator/tls/DefaultTlsProtocolNegotiatorBuilderTest.java
https://github.com/alibaba/nacos/issues/11304
XXXXX
=> add startup conditions

client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingService.java, client/src/test/java/com/alibaba/nacos/client/naming/NacosNamingServiceTest.java
see #11298
* check and strip group name prefix of instance service name at register and deregister functions of NacosNamingService.java
=> strip groupNamePrefix of instance serviceName at register or deregister

config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigQueryRequestHandler.java
=> feat: code clean.

client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc/NamingGrpcClientProxy.java, client/src/test/java/com/alibaba/nacos/client/naming/remote/gprc/NamingGrpcClientProxyTest.java
fix #11298
* only check  ip and port of deregister instances at getRetainInstance function of NamingGrpcClientProxy.java
=> get retained instances only based on ip and port checking

api/src/main/java/com/alibaba/nacos/api/ability/constant/AbilityKey.java, api/src/main/java/com/alibaba/nacos/api/ability/register/impl/ServerAbilities.java, api/src/main/java/com/alibaba/nacos/api/naming/remote/request/PersistentInstanceRequest.java, api/src/main/java/com/alibaba/nacos/api/naming/utils/NamingUtils.java, api/src/main/resources/META-INF/services/com.alibaba.nacos.api.remote.Payload, api/src/test/java/com/alibaba/nacos/api/ability/register/impl/ServerAbilitiesTest.java, api/src/test/java/com/alibaba/nacos/api/naming/remote/request/PersistentInstanceRequestTest.java, api/src/test/java/com/alibaba/nacos/api/naming/utils/NamingUtilsTest.java, api/src/test/java/com/alibaba/nacos/api/utils/AbilityKeyTest.java, client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingService.java, client/src/main/java/com/alibaba/nacos/client/naming/remote/NamingClientProxyDelegate.java, client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc/NamingGrpcClientProxy.java, client/src/main/java/com/alibaba/nacos/client/naming/remote/http/NamingHttpClientProxy.java, client/src/test/java/com/alibaba/nacos/client/naming/remote/NamingClientProxyDelegateTest.java, client/src/test/java/com/alibaba/nacos/client/naming/remote/gprc/NamingGrpcClientProxyTest.java, core/src/main/java/com/alibaba/nacos/core/paramcheck/impl/PersistentInstanceRequestParamExtractor.java, core/src/main/resources/META-INF/services/com.alibaba.nacos.core.paramcheck.AbstractRpcParamExtractor, naming/src/main/java/com/alibaba/nacos/naming/remote/rpc/handler/PersistentInstanceRequestHandler.java, naming/src/test/java/com/alibaba/nacos/naming/remote/rpc/handler/PersistentInstanceRequestHandlerTest.java
Support register or deregister persistent instance by grpc.
1. Add PersistentInstanceRequest in 2.3.0 server and client.
2. Add ability tag like supportPersistentInstanceByGrpc in AbilityTables of 2.3.0 server and client.
3. when using 2.3.0 client and later version, it can judge whether use grpc request to register persistent instance, if server supported, use grpc request, otherwise use old way to adapt it.
=> feat(#11393): support register or deregister persistent instance by grpc

distribution/conf/mysql-schema.sql
fix(#11306 ): change the length of the field named resource from 255 to 128.
fix(#11306 ): change the length of the field named resource from 255 to 128.
fix(#11306 ): change the length of the field named resource from 255 to 128.
=> fix(#11306): change the length of the field named resource from 255 to 128.

client/src/main/java/com/alibaba/nacos/client/auth/impl/NacosClientAuthServiceImpl.java
=> [ISSUE#11494] Client don't judge token content invalid.

plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/proxy/MapperProxy.java
description: when set nacos.plugin.datasource.log.enabled=true, will create Proxy Object, but it was mistakenly changed to a different type
relate #11497 #11461
=> [ISSUE #11502] fix proxy mapper bug

config/src/main/java/com/alibaba/nacos/config/server/controller/HealthController.java, config/src/test/java/com/alibaba/nacos/config/server/controller/HealthControllerTest.java
Close #11499
return UP  status when the nacos server doesn't use address-server
optimize HealthController#isAddressServerHealthy logic
1. start nacos server using the standalone model
2. curl `http://localhost:8848/nacos/v1/cs/health` 
3. check api result 
=> [ISSUES #11499] fix address server health check error

client/src/test/java/com/alibaba/nacos/client/config/filter/impl/ConfigEncryptionFilterTest1.java, plugin/encryption/src/test/java/com/alibaba/nacos/plugin/encryption/handler/EncryptionAesHandlerTest.java, test/config-test/src/test/java/com/alibaba/nacos/test/config/AbstractConfigAPI_CITCase.java
当dataId开头为字母cipher时，这种情况的单测覆盖不够全面，我这边想补充一下。
=> [ISSUE #11544] Supplementary single test, when the prefix of dataId is cipher.

plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/controller/UserController.java
fix https://github.com/alibaba/nacos/issues/11595
XX
XXXX
=> [ISSUE #11595]fix user update permission

core/src/main/java/com/alibaba/nacos/core/distributed/raft/RaftConfig.java
fix https://github.com/alibaba/nacos/issues/11647
XX
XXXX
=> fix RaftConfig is always {}

client/src/main/java/com/alibaba/nacos/client/config/impl/CacheData.java, client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java, client/src/main/java/com/alibaba/nacos/client/config/impl/ServerListManager.java, client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingMaintainService.java, client/src/main/java/com/alibaba/nacos/client/naming/backups/FailoverReactor.java, client/src/main/java/com/alibaba/nacos/client/naming/remote/NamingClientProxyDelegate.java, common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClient.java, config/src/main/java/com/alibaba/nacos/config/server/service/ConfigDetailService.java
Fix #11612
Unified use of `NameThreadFactory` to create thread pools.
XXXX
=> [ISSUE #11612] Unified use of `NameThreadFactory` to create thread pools

plugin-default-impl/nacos-default-control-plugin/src/main/java/com/alibaba/nacos/plugin/control/impl/NacosConnectionControlManager.java
Fixed an issue [#11624](https://github.com/alibaba/nacos/issues/11624) where the maximum number of anti-fragile plug-ins implemented by default in Nacos is one more than the actual number of connections.
=> [ISSUES #11624] 修改Nacos 2.3.0 反脆弱插件NacosConnectionControlManager类判断条件

config/src/main/java/com/alibaba/nacos/config/server/model/ConfigInfoStateWrapper.java, config/src/main/java/com/alibaba/nacos/config/server/service/ConfigCacheService.java, config/src/main/java/com/alibaba/nacos/config/server/service/dump/DumpChangeConfigWorker.java, config/src/main/java/com/alibaba/nacos/config/server/service/dump/DumpService.java, config/src/main/java/com/alibaba/nacos/config/server/service/dump/processor/DumpAllProcessor.java, config/src/main/java/com/alibaba/nacos/config/server/service/dump/task/DumpAllTask.java, config/src/main/java/com/alibaba/nacos/config/server/service/repository/ConfigInfoPersistService.java, config/src/main/java/com/alibaba/nacos/config/server/service/repository/ConfigRowMapperInjector.java, config/src/main/java/com/alibaba/nacos/config/server/service/repository/HistoryConfigInfoPersistService.java, config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedConfigInfoPersistServiceImpl.java, config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedHistoryConfigInfoPersistServiceImpl.java, config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalConfigInfoPersistServiceImpl.java, config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalHistoryConfigInfoPersistServiceImpl.java, config/src/main/java/com/alibaba/nacos/config/server/utils/PropertyUtil.java, config/src/test/java/com/alibaba/nacos/config/server/service/dump/DumpChangeConfigWorkerTest.java, config/src/test/java/com/alibaba/nacos/config/server/service/dump/DumpServiceTest.java, config/src/test/java/com/alibaba/nacos/config/server/service/dump/processor/DumpAllProcessorTest.java, config/src/test/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedConfigInfoPersistServiceImplTest.java, config/src/test/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedHistoryConfigInfoPersistServiceImplTest.java, config/src/test/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalConfigInfoPersistServiceImplTest.java, config/src/test/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalHistoryConfigInfoPersistServiceImplTest.java, config/src/test/java/com/alibaba/nacos/config/server/utils/PropertyUtilTest.java, plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/constants/ContextConstant.java, plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/derby/ConfigInfoMapperByDerby.java, plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/mysql/ConfigInfoMapperByMySql.java, plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/ConfigInfoMapper.java, plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/model/MapperContext.java, plugin/datasource/src/test/java/com/alibaba/nacos/plugin/datasource/impl/derby/ConfigInfoMapperByDerbyTest.java, plugin/datasource/src/test/java/com/alibaba/nacos/plugin/datasource/impl/mysql/ConfigInfoMapperByMySqlTest.java
1.optimize config dump all,do not select content in page query,single query config on md5 and ts updated.
2. remove convertDeleteConfig and convertConfigConfig ，use standard RowMapper instead.
=> optimize dump all logic and optimize dump change interface

config/src/main/java/com/alibaba/nacos/config/server/aspect/ConfigChangeAspect.java, config/src/test/java/com/alibaba/nacos/config/server/aspect/ConfigChangeAspectTest.java, config/src/test/java/com/alibaba/nacos/config/server/configuration/ConfigChangeConfigsTest.java, plugin/config/src/main/java/com/alibaba/nacos/plugin/config/ConfigChangePluginManager.java, plugin/config/src/test/java/com/alibaba/nacos/plugin/config/ConfigChangePluginManagerTests.java
Fixed an issue  #11655 fix invalid usage of ProporityQueue in ConfigChangePluginMaanger
XX
XXXX
=> [ISSUE #11655]fix invalid usage of ProporityQueue in ConfigChangePluginManger

client/src/main/java/com/alibaba/nacos/client/config/http/ServerHttpAgent.java, client/src/main/java/com/alibaba/nacos/client/config/impl/CacheData.java, client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java, client/src/main/java/com/alibaba/nacos/client/config/impl/ConfigTransportClient.java, client/src/test/java/com/alibaba/nacos/client/config/NacosConfigServiceTest.java, client/src/test/java/com/alibaba/nacos/client/config/http/ServerHttpAgentTest.java, client/src/test/java/com/alibaba/nacos/client/config/impl/CacheDataTest.java, client/src/test/java/com/alibaba/nacos/client/config/impl/ClientWorkerTest.java, config/src/test/java/com/alibaba/nacos/config/server/configuration/ConfigCommonConfigTest.java, core/src/main/java/com/alibaba/nacos/core/control/http/NacosHttpTpsFilter.java, core/src/main/java/com/alibaba/nacos/core/control/remote/TpsControlRequestFilter.java, core/src/main/java/com/alibaba/nacos/core/remote/AbstractRequestFilter.java, core/src/test/java/com/alibaba/nacos/core/control/http/NacosHttpTpsFilterTest.java, core/src/test/java/com/alibaba/nacos/core/control/remote/TpsControlRequestFilterTest.java
1.ServerHttpAgent covers http get&post&delete  successful and failed scene.
2.ClientWorker covers config publish&get&remove scene, config change notify handler,config metrics handler , config listen execution include failover config,discarded configs and normal config changed configs.
3.NacosConfigService covers getconfig for normal ,403,failover,snapshot scenes.
4.CacheData covers notify timeouts init, notify listener blocking,shared listener,config change listener
5. ConfigCommonConfigTest test cases fixed.
6.NacosHttpTpsFilter TpsControlRequestFilter coverage.
=> config module coverage

plugin/control/src/main/java/com/alibaba/nacos/plugin/control/connection/ConnectionControlManager.java, plugin/control/src/main/java/com/alibaba/nacos/plugin/control/connection/DefaultConnectionControlManager.java, plugin/control/src/main/java/com/alibaba/nacos/plugin/control/rule/ControlRuleChangeActivator.java, plugin/control/src/main/java/com/alibaba/nacos/plugin/control/rule/storage/LocalDiskRuleStorage.java, plugin/control/src/main/java/com/alibaba/nacos/plugin/control/tps/TpsControlManager.java
=> log improvement

api/src/main/java/com/alibaba/nacos/api/PropertyKeyConst.java, client/src/main/java/com/alibaba/nacos/client/config/impl/ServerListManager.java, client/src/main/java/com/alibaba/nacos/client/naming/core/ServerListManager.java, client/src/test/java/com/alibaba/nacos/client/config/impl/ServerListManagerTest.java, client/src/test/java/com/alibaba/nacos/client/naming/core/ServerListManagerTest.java
feat(#11752 ): The contentPath of AddressServerUrl is not flexible.
feat(#11752 ): The contentPath of AddressServerUrl is not flexible.
feat(#11752 ): The contentPath of AddressServerUrl is not flexible.
=> feat(#11752): The contentPath of AddressServerUrl is not flexible.

common/src/main/java/com/alibaba/nacos/common/utils/StringUtils.java, console/src/main/java/com/alibaba/nacos/console/controller/ServerStateController.java
https://github.com/alibaba/nacos/issues/11821
ensure that the filename has no path separators or parent directory references
确保文件名没有路径分隔符或父目录引用
Uncontrolled data used in path expression
XXXX
=> :bug: Uncontrolled data used in path expression

naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/NamingMetadataManager.java
fix #11835
update service's lastUpdatedTime when snapshot loaded.
=> fix #11835

api/src/main/java/com/alibaba/nacos/api/common/Constants.java, client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java, client/src/test/java/com/alibaba/nacos/client/config/impl/ClientWorkerTest.java, common/src/main/java/com/alibaba/nacos/common/labels/LabelsCollector.java, common/src/main/java/com/alibaba/nacos/common/labels/LabelsCollectorManager.java, common/src/main/java/com/alibaba/nacos/common/labels/impl/AbstractLabelsCollector.java, common/src/main/java/com/alibaba/nacos/common/labels/impl/DefaultLabelsCollector.java, common/src/main/java/com/alibaba/nacos/common/labels/impl/DefaultLabelsCollectorManager.java, common/src/main/java/com/alibaba/nacos/common/labels/impl/utils/AbstractConfigGetter.java, common/src/main/java/com/alibaba/nacos/common/labels/impl/utils/ConfigGetterManager.java, common/src/main/java/com/alibaba/nacos/common/labels/impl/utils/EnvConfigGetter.java, common/src/main/java/com/alibaba/nacos/common/labels/impl/utils/JvmConfigGetter.java, common/src/main/java/com/alibaba/nacos/common/labels/impl/utils/OrderedConfigGetter.java, common/src/main/java/com/alibaba/nacos/common/labels/impl/utils/PropertiesConfigGetter.java, common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClientFactory.java, common/src/main/java/com/alibaba/nacos/common/utils/ConnLabelsUtils.java, common/src/main/resources/META-INF/services/com.alibaba.nacos.common.labels.LabelsCollector, common/src/test/java/com/alibaba/nacos/common/labels/impl/ConfigGetterManagerTest.java, common/src/test/java/com/alibaba/nacos/common/labels/impl/DefaultLabelsCollectorManagerTest.java, common/src/test/java/com/alibaba/nacos/common/labels/impl/Test1LabelsCollector.java, common/src/test/java/com/alibaba/nacos/common/labels/impl/Test2LabelsCollector.java, common/src/test/java/com/alibaba/nacos/common/utils/ConnLabelsUtilsTest.java, common/src/test/resources/META-INF/services/com.alibaba.nacos.common.labels.LabelsCollector, core/src/main/java/com/alibaba/nacos/core/remote/Connection.java, core/src/main/java/com/alibaba/nacos/core/remote/ConnectionMeta.java
nacos-client can collect labels in the form of SPI plug-in and attach them to the labels attribute of long connection.
---
支持nacos-client可以通过SPI插件的形式采集labels标签，并附加labels属性到长连接中。
XX
XXXX
=> feature: add client labels collect and attach labels to conn

common/src/main/java/com/alibaba/nacos/common/labels/impl/DefaultLabelsCollector.java, common/src/main/java/com/alibaba/nacos/common/labels/impl/DefaultLabelsCollectorManager.java, common/src/main/java/com/alibaba/nacos/common/utils/ConnLabelsUtils.java, common/src/test/java/com/alibaba/nacos/common/utils/ConnLabelsUtilsTest.java
=> format check on client labels

pom.xml
=> fix: CVE-2024-22243 & CVE-2024-22259 Upgrade Spring Web to 5.3.33

plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/mysql/ConfigInfoMapperByMySql.java, plugin/datasource/src/test/java/com/alibaba/nacos/plugin/datasource/impl/mysql/ConfigInfoMapperByMySqlTest.java
link https://github.com/alibaba/nacos/issues/11859
XX
XXXX
=> fix：add param for ConfigInfoMapperByMySql#findAllConfigInfoBaseFetchRows

pom.xml
- CVE-2024-22257 Upgrade Spring Security to 5.7.12.
- Use spring-framework-bom as dependencyManagement.
Closes #11904
XXXXX
XX
XXXX
=> fix: vulnerability

config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigController.java
fix #11943 
ConfigController.parseImportDataV2、ConfigController.parseImportData记录导入用户
导入后，查看数据库，存在导入用户
=> [ISSUE #11943] 记录导入配置用户

naming/src/main/java/com/alibaba/nacos/naming/pojo/instance/SnowFlakeInstanceIdGenerator.java, naming/src/test/java/com/alibaba/nacos/naming/pojo/instance/HttpRequestInstanceBuilderTest.java
1. fix unit test bug.
2. 解决SnowFlakeInstanceIdGenerator类加载时强依赖workerId的初始化过程。
@BeforeClass增加EnvUtil.setEnvironment(new StandardEnvironment());
改变WorkerId的加载方式。通过SnowFlakeInstanceIdGenerator静态代码块加载->在generateInstanceId通过双检锁保证加载一次
XXXX
=> [ISSUE #11994]修复HttpRequestInstanceBuilderTest出现的空指针问题，优化SnowFlakeInstanceIdGenerator初始化流程

pom.xml
update spring boot version and fix CVE-2023-34034 in nacos 1.x version
=> update spring-boot-dependencies version to 2.7.18

address/src/test/java/com/alibaba/nacos/address/component/AddressServerGeneratorManagerTest.java, address/src/test/java/com/alibaba/nacos/address/component/AddressServerManagerTests.java, address/src/test/java/com/alibaba/nacos/address/controller/AddressServerClusterControllerTest.java, address/src/test/java/com/alibaba/nacos/address/controller/ServerListControllerTest.java
=> [ISSUE #12083] module address upgrade junit4 to junit5

config/src/main/java/com/alibaba/nacos/config/server/service/dump/disk/ConfigRawDiskService.java, config/src/test/java/com/alibaba/nacos/config/server/service/dump/disk/ConfigRawDiskServiceTest.java
BUG：https://github.com/alibaba/nacos/issues/11967%EF%BC%8C details refer： https://github.com/alibaba/nacos/issues/10119 & https://github.com/alibaba/nacos/pull/10101
=> [ISSUE #11967] Can not aquire the specific config

plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/token/impl/JwtTokenManager.java, plugin-default-impl/nacos-default-auth-plugin/src/test/java/com/alibaba/nacos/plugin/auth/impl/token/impl/JwtTokenManagerTest.java
fix issue #12060
> 1. fix too large ttl when auth disabled
> 2. generate a valid token when nacos.core.auth.plugin.nacos.token.secret.key is valid even if auth disabled
XXXX
=> [ISSUE #12060]  fix too large ttl when auth disabled

console/src/test/java/com/alibaba/nacos/console/controller/HealthControllerTest.java, console/src/test/java/com/alibaba/nacos/console/controller/NamespaceControllerTest.java, console/src/test/java/com/alibaba/nacos/console/controller/ServerStateControllerTest.java, console/src/test/java/com/alibaba/nacos/console/controller/v2/HealthControllerV2Test.java, console/src/test/java/com/alibaba/nacos/console/controller/v2/NamespaceControllerV2Test.java, console/src/test/java/com/alibaba/nacos/console/exception/ConsoleExceptionHandlerTest.java, console/src/test/java/com/alibaba/nacos/console/exception/NacosApiExceptionHandlerTest.java, console/src/test/java/com/alibaba/nacos/console/filter/XssFilterTest.java, console/src/test/java/com/alibaba/nacos/console/paramcheck/ParamExtractorTest.java
=> [ISSUE #12135] upgrade module naocs-console from junit4 to junit5

api/src/main/java/com/alibaba/nacos/api/PropertyKeyConst.java, client/src/main/java/com/alibaba/nacos/client/auth/ram/RamClientAuthServiceImpl.java, client/src/main/java/com/alibaba/nacos/client/auth/ram/RamConstants.java, client/src/main/java/com/alibaba/nacos/client/auth/ram/RamContext.java, client/src/main/java/com/alibaba/nacos/client/auth/ram/injector/AbstractResourceInjector.java, client/src/main/java/com/alibaba/nacos/client/auth/ram/injector/ConfigResourceInjector.java, client/src/main/java/com/alibaba/nacos/client/auth/ram/injector/NamingResourceInjector.java, client/src/main/java/com/alibaba/nacos/client/auth/ram/utils/CalculateV4SigningKeyUtil.java, client/src/test/java/com/alibaba/nacos/client/auth/ram/RamClientAuthServiceImplTest.java, client/src/test/java/com/alibaba/nacos/client/auth/ram/identify/CredentialServiceTest.java, client/src/test/java/com/alibaba/nacos/client/auth/ram/injector/ConfigResourceInjectorTest.java, client/src/test/java/com/alibaba/nacos/client/auth/ram/injector/NamingResourceInjectorTest.java, client/src/test/java/com/alibaba/nacos/client/auth/ram/utils/CalculateV4SigningKeyUtilTest.java
=> Support aliyun ram v4 signature method.

prometheus/src/main/java/com/alibaba/nacos/prometheus/utils/PrometheusUtils.java, prometheus/src/test/java/com/alibaba/nacos/prometheus/controller/PrometheusControllerTest.java
add feature for #12130 
XX
XXXX
=> [ISSUE #12130] add metadata as labels in prometheus http sd

api/src/main/java/com/alibaba/nacos/api/PropertyKeyConst.java, client/src/main/java/com/alibaba/nacos/client/config/NacosConfigService.java, client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingService.java, client/src/main/java/com/alibaba/nacos/client/utils/ParamUtil.java, client/src/test/java/com/alibaba/nacos/client/utils/ParamUtilTest.java
=> Enhance nacos client init properties logger.

client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingService.java, client/src/main/java/com/alibaba/nacos/client/naming/backups/FailoverReactor.java, client/src/main/java/com/alibaba/nacos/client/naming/cache/InstancesDiffer.java, client/src/main/java/com/alibaba/nacos/client/naming/cache/ServiceInfoHolder.java, client/src/main/java/com/alibaba/nacos/client/naming/event/InstancesChangeEvent.java, client/src/main/java/com/alibaba/nacos/client/naming/selector/NamingListenerInvoker.java, client/src/test/java/com/alibaba/nacos/client/naming/backups/FailoverReactorTest.java
=> Do some refactor for naming notify event.

client/src/main/java/com/alibaba/nacos/client/naming/utils/CacheDirUtil.java, client/src/test/java/com/alibaba/nacos/client/naming/utils/CacheDirUtilTest.java
=> [ISSUE #12185]fix: use nacos properties in CacheDirUtil

api/src/main/java/com/alibaba/nacos/api/PropertyKeyConst.java, client/src/main/java/com/alibaba/nacos/client/config/impl/ServerListManager.java, client/src/main/java/com/alibaba/nacos/client/naming/core/ServerListManager.java, client/src/test/java/com/alibaba/nacos/client/config/impl/ServerListManagerTest.java, client/src/test/java/com/alibaba/nacos/client/naming/core/ServerListManagerTest.java
1.add endpoint cluster name to split the cluster name params used for naming endpoint and spring cloud instance registry.
2.add endpoint cluster name to instead cluster name param , using cluster name for compatibility.
=> add endpoint cluster name for config & naming server list manager

address/pom.xml, api/pom.xml, api/src/test/java/com/alibaba/nacos/api/naming/pojo/builder/InstanceBuilderTest.java, auth/pom.xml, client/src/test/java/com/alibaba/nacos/client/naming/event/InstancesDiffTest.java, client/src/test/java/com/alibaba/nacos/client/naming/listener/NamingChangeEventTest.java, client/src/test/java/com/alibaba/nacos/client/naming/selector/DefaultNamingSelectorTest.java, client/src/test/java/com/alibaba/nacos/client/naming/selector/NamingListenerInvokerTest.java, client/src/test/java/com/alibaba/nacos/client/naming/selector/NamingSelectorFactoryTest.java, client/src/test/java/com/alibaba/nacos/client/naming/selector/NamingSelectorWrapperTest.java, client/src/test/java/com/alibaba/nacos/client/selector/SelectorManagerTest.java, cmdb/pom.xml, common/src/test/java/com/alibaba/nacos/common/trace/publisher/TraceEventPublisherTest.java, config/pom.xml, config/src/test/java/com/alibaba/nacos/config/server/exception/GlobalExceptionHandlerTest.java, console/pom.xml, console/src/test/java/com/alibaba/nacos/console/exception/NacosApiExceptionHandlerTest.java, core/pom.xml, persistence/pom.xml, plugin-default-impl/nacos-default-auth-plugin/pom.xml, pom.xml, prometheus/pom.xml, prometheus/src/test/java/com/alibaba/nacos/prometheus/controller/PrometheusControllerTest.java, prometheus/src/test/java/com/alibaba/nacos/prometheus/controller/exception/PrometheusApiExceptionHandlerTest.java, sys/pom.xml, sys/src/test/java/com/alibaba/nacos/sys/env/EnvUtilWithConfigTest.java, sys/src/test/java/com/alibaba/nacos/sys/env/EnvUtilWithoutConfigTest.java, sys/src/test/java/com/alibaba/nacos/sys/utils/PropertiesUtilTest.java
fix #12016 
At last, all unit test case have  been upgrade to junit5 style.
XX
=> [ISSUE #12016] upgrade to junit5 and remove junit4

prometheus/src/main/java/com/alibaba/nacos/prometheus/utils/PrometheusUtils.java
fix  https://github.com/alibaba/nacos/issues/12196
prometheus http sd contains label names with "." and "-", which can not parsed by prometheus, this commit auto connvert invalid words to "_" to make  prometheus happy.
label "preserved.register.source":"SPRING_CLOUD" is auto added by nacos sdk,
and another example is label "management.endpoints.web.base-path":"/xxxx"  , which auto exported by nacos sdk, label name contains two invalid words .  and - .
above 2 label name are not controlled or registered by enduser, and prometheus can't parse these label names, then this scrape job failed, this job results show nothing.
this commit convert label name from .  and - words to_ in …
=> [ISSUE #12196] FIX prometheus http sd invalid label names

client/src/main/java/com/alibaba/nacos/client/config/impl/ServerListManager.java, client/src/test/java/com/alibaba/nacos/client/config/impl/ServerListManagerTest.java
=> [ISSUE #12219] 修复nacos-client中config的ServerListManager解析endpoint失败问题

test/core-test/src/test/java/com/alibaba/nacos/test/core/auth/AuthBase.java, test/core-test/src/test/java/com/alibaba/nacos/test/core/auth/ConfigAuthCoreITCase.java, test/core-test/src/test/java/com/alibaba/nacos/test/core/auth/LdapAuthCoreITCase.java, test/core-test/src/test/java/com/alibaba/nacos/test/core/auth/NamingAuthCoreITCase.java, test/core-test/src/test/java/com/alibaba/nacos/test/core/auth/PermissionCoreITCase.java, test/core-test/src/test/java/com/alibaba/nacos/test/core/auth/RoleCoreITCase.java, test/core-test/src/test/java/com/alibaba/nacos/test/core/auth/UserCoreITCase.java
=> Adjust core module auth integration tests to meet checkstyle requirements.

config/src/main/java/com/alibaba/nacos/config/server/monitor/MetricsMonitor.java, config/src/main/java/com/alibaba/nacos/config/server/service/trace/ConfigTraceService.java
feat(#12355): Record the cost of ConfigDump in Prometheus.
feat(#12355): Record the cost of ConfigDump in Prometheus.
feat(#12355): Record the cost of ConfigDump in Prometheus.
=> feat(#12355): Record the cost of ConfigDump in Prometheus.

logger-adapter-impl/logback-adapter-12/src/main/java/com/alibaba/nacos/logger/adapter/logback12/LogbackNacosLoggingAdapter.java
fix issue #12323 , using project's logback packagingData configuration instead of logback-nacos.xml's packagingData configuration
Before `LogbackNacosLoggingAdapter`  loading ` logback-nocas.xml ` ，get the `isPackagingDataEnabled` property , when ` logback-nocas.xml ` is loaded , revert the `isPackagingDataEnabled` property of LoggerContext .
=> fix [ISSUE #12323]  , using the  project's logback packagingData configuration instead of logback-nacos.xml's packagingData  configuration

api/src/main/java/com/alibaba/nacos/api/common/Constants.java, auth/src/main/java/com/alibaba/nacos/auth/parser/grpc/ConfigGrpcResourceParser.java, auth/src/main/java/com/alibaba/nacos/auth/parser/http/ConfigHttpResourceParser.java, auth/src/test/java/com/alibaba/nacos/auth/HttpProtocolAuthServiceTest.java, auth/src/test/java/com/alibaba/nacos/auth/parser/http/ConfigHttpResourceParserTest.java
fix(#12333 ): fixed auth Plugin resource parser can't parser v2 config openAPI namespaceId.
fix(#12333 ): fixed auth Plugin resource parser can't parser v2 config openAPI namespaceId.
fix(#12333 ): fixed auth Plugin resource parser can't parser v2 config openAPI namespaceId.
=> fix(#12333): fixed auth Plugin resource parser can't parser v2 config openAPI namespaceId.

.gitignore, api/src/main/java/com/alibaba/nacos/api/PropertyKeyConst.java, api/src/main/java/com/alibaba/nacos/api/SystemPropertyKeyConst.java, api/src/main/java/com/alibaba/nacos/api/common/Constants.java, client/src/main/java/com/alibaba/nacos/client/auth/ram/RamClientAuthServiceImpl.java, client/src/main/java/com/alibaba/nacos/client/auth/ram/utils/RamUtil.java, client/src/test/java/com/alibaba/nacos/client/auth/ram/utils/RamUtilTest.java, pom.xml
=> Develop support ram info switch

config/src/main/java/com/alibaba/nacos/config/server/service/dump/DefaultHistoryConfigCleaner.java, config/src/main/java/com/alibaba/nacos/config/server/service/dump/DumpService.java, config/src/main/java/com/alibaba/nacos/config/server/service/dump/HistoryConfigCleaner.java, config/src/main/java/com/alibaba/nacos/config/server/service/dump/HistoryConfigCleanerConfig.java, config/src/main/java/com/alibaba/nacos/config/server/service/dump/HistoryConfigCleanerManager.java, config/src/test/java/com/alibaba/nacos/config/server/service/dump/DefaultHistoryConfigCleanerTest.java, config/src/test/java/com/alibaba/nacos/config/server/service/dump/DumpServiceTest.java, config/src/test/java/com/alibaba/nacos/config/server/service/dump/HistoryConfigCleanerConfigTest.java, config/src/test/java/com/alibaba/nacos/config/server/service/dump/HistoryConfigCleanerManagerTest.java
fix issue#12359
Refactoring the historical configuration cleanup strategy with SPI (Service Provider Interface), and add unit test for
DefaultHistoryConfigCleaner ,HistoryConfigCleanerManager and HistoryConfigCleanerConfig
XXXX
=> [ISSUE#12359]Refactoring the historical configuration cleanup strategy with SPI 

plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/LdapAuthenticationProvider.java, plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/constant/AuthConstants.java, plugin-default-impl/nacos-default-auth-plugin/src/test/java/com/alibaba/nacos/plugin/auth/impl/LdapAuthenticationProviderTest.java
feat(#12405 ) The LDAP default password can be customized by setting a JVM system property.
-Dldap.default.password=yourLdapDeafultPassword
feat(#12405 ) The LDAP default password can be customized by setting a JVM system property.
-Dldap.default.password=yourLdapDeafultPassword
feat(#12405 ) The LDAP default password can be customized by setting a JVM system property.
-Dldap.default.password=yourLdapDeafultPassword
=> feat(#12405): The LDAP default password is a fixed value 'nacos' and cannot be customized.

test/naming-test/src/test/java/com/alibaba/nacos/test/base/Params.java
=> [IT]Adjust naming module base ITs for Checkstyle compliance.

plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/ConfigInfoMapper.java
按文档指示，该修改是小型修改，无需创建对应issue
修改mapper接口当中过时的注释内容，以使得注释中的sql内容和默认mysql实现类中的一致。
否则自己扩展datasource插件的时候，很容易被过时的注释混淆，导致连接其他数据库时的行为和期望行为不一致。
增加注释中缺少的LIMIT字段，删除多余的字段等。
修改注释后，注释中的sql内容和默认mysql当中实现的一致。
=> Fix default sql in the comment to be consistent with the implementation

plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/jwt/NacosJwtParser.java
add some tips when the user upgrades Nacos
XX
XXXX
=> [ISSUE #11887] add some tips for upgrade

naming/src/main/java/com/alibaba/nacos/naming/core/v2/pojo/Service.java, naming/src/main/java/com/alibaba/nacos/naming/healthcheck/v2/processor/TcpHealthCheckProcessor.java
for #12301
fix #12301
Beat 对象toString()增加 nameSpace区分
tryStartCheck日志打印增加nameSpace区分
XX
XXXX
=> [ISSUE #12301] 相同永久实例在不同nameSpace下面健康检测问题

console-ui/src/globalLib.js
关闭nacos控制台的登录，使用nginx的auth_basic限制控制台访问的时候，部分接口的请求Authorization会被置为null，导致auth_basic无法正常使用
token不存在时Authorization置为undefined
能正常用nginx的auth_basic了
=> fix: 关闭控制台登录时请求的Authorization为null

consistency/pom.xml, pom.xml
fixes #12342 
Resolve the Hessian package conflict issue.
Replaced the jraft-core Hessian dependency version `3.3.6` and the original Nacos project dependency on `com.caucho:hessian:4.0.63` with `com.alipay.sofa:hessian:4.0.4`.
We have been using this solution in our production environment since version 2.2.x, and it has been validated across versions 2.3.3 and 2.4.0.1. Throughout the use of this solution for service startup, as a configuration center, and as a registration center, no issues have been encountered.
=> [ISSUE #12342] Resolve the Hessian package conflict issue.

common/src/main/java/com/alibaba/nacos/common/paramcheck/DefaultParamChecker.java, common/src/test/java/com/alibaba/nacos/common/paramcheck/DefaultParamCheckerTest.java, sys/src/main/java/com/alibaba/nacos/sys/env/EnvUtil.java, sys/src/test/java/com/alibaba/nacos/sys/env/EnvUtilTest.java
resolves #12466
增加serviceMetadata的环境变量配置： NACOS_NAMING_SERVICE_METADATA_LENGTH
XX
XXXX
=> [ISSUE #12466]  serviceMetadata environment variables config

core/src/main/java/com/alibaba/nacos/core/persistence/DistributedDatabaseOperateImpl.java, persistence/src/main/java/com/alibaba/nacos/persistence/repository/embedded/operate/StandaloneDatabaseOperateImpl.java, persistence/src/main/java/com/alibaba/nacos/persistence/repository/embedded/sql/limiter/SqlLimiter.java, persistence/src/main/java/com/alibaba/nacos/persistence/repository/embedded/sql/limiter/SqlTypeLimiter.java, persistence/src/test/java/com/alibaba/nacos/persistence/repository/embedded/operate/StandaloneDatabaseOperateImplTest.java, persistence/src/test/java/com/alibaba/nacos/persistence/repository/embedded/sql/limiter/SqlTypeLimiterTest.java
=> [Enhancement] Enhance derby sql to support limit sql.

config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/DistributedDatabaseOperateImpl.java, config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/StandaloneDatabaseOperateImpl.java, config/src/main/java/com/alibaba/nacos/config/server/service/sql/limit/SqlLimiter.java, config/src/main/java/com/alibaba/nacos/config/server/service/sql/limit/SqlTypeLimiter.java, naming/src/main/java/com/alibaba/nacos/naming/consistency/KeyBuilder.java, naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/impl/BasePersistentServiceProcessor.java
=> V1.x develop limit storage

config/src/test/java/com/alibaba/nacos/config/server/paramcheck/ParamExtractorTest.java, config/src/test/resources/log4j.properties, plugin/datasource/src/test/java/com/alibaba/nacos/plugin/datasource/impl/derby/ConfigInfoMapperByDerbyTest.java, plugin/datasource/src/test/java/com/alibaba/nacos/plugin/datasource/impl/derby/ConfigInfoTagsRelationMapperByDerbyTest.java, plugin/datasource/src/test/java/com/alibaba/nacos/plugin/datasource/impl/mysql/ConfigInfoMapperByMySqlTest.java, plugin/datasource/src/test/java/com/alibaba/nacos/plugin/datasource/impl/mysql/ConfigTagsRelationMapperByMySqlTest.java
=> Fix unit test error.

consistency/src/main/java/com/alibaba/nacos/consistency/ConsistencyProtocol.java, core/src/main/java/com/alibaba/nacos/core/distributed/ProtocolManager.java, core/src/main/java/com/alibaba/nacos/core/distributed/raft/JRaftProtocol.java, core/src/main/java/com/alibaba/nacos/core/distributed/raft/JRaftServer.java, core/src/main/java/com/alibaba/nacos/core/distributed/raft/RaftConfig.java, core/src/test/java/com/alibaba/nacos/core/distributed/raft/JRaftProtocolTest.java, core/src/test/java/com/alibaba/nacos/core/distributed/raft/JRaftServerTest.java, naming/src/main/java/com/alibaba/nacos/naming/cluster/ServerStatusManager.java, naming/src/main/java/com/alibaba/nacos/naming/web/TrafficReviseFilter.java, naming/src/test/java/com/alibaba/nacos/naming/cluster/ServerStatusManagerTest.java
Fixes #12526, check whether cp protocol has init before getting to avoid async get dead lock.
For #12504,#12541,#12558 Enhance naming server stauts check logic, which can downgrade the check to avoid affect core features.
But if no leader for raft group, the relative features still can't be used.
XX
XXXX
=> [Refactor&Enhancement] Enhance naming server status check.

config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigChangeBatchListenRequestHandler.java, config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigChangeClusterSyncRequestHandler.java, config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigQueryRequestHandler.java, config/src/main/java/com/alibaba/nacos/config/server/service/dump/disk/ConfigRawDiskService.java, config/src/main/java/com/alibaba/nacos/config/server/utils/ParamUtils.java, config/src/test/java/com/alibaba/nacos/config/server/service/dump/disk/ConfigRawDiskServiceTest.java, config/src/test/java/com/alibaba/nacos/config/server/utils/ParamUtilsTest.java
Addition for #12563, Add parameter check for tag.
XX
XXXX
=> Addition for #12563, Add parameter check for tag.

naming/src/main/java/com/alibaba/nacos/naming/misc/SwitchEntry.java, naming/src/main/java/com/alibaba/nacos/naming/misc/SwitchManager.java, naming/src/main/java/com/alibaba/nacos/naming/model/form/UpdateSwitchForm.java
=> [ISSUE #12555] SwitchManager support http、tcp、mysql HealthParams and pushCSharpVersion update

client/src/main/java/com/alibaba/nacos/client/auth/impl/process/HttpLoginProcessor.java, client/src/main/java/com/alibaba/nacos/client/utils/ParamUtil.java, client/src/test/java/com/alibaba/nacos/client/auth/impl/process/HttpLoginProcessorTest.java, client/src/test/java/com/alibaba/nacos/client/utils/ParamUtilTest.java
Fixes #12547, nacos client supports desensitise in logging.
XX
XXXX
=> [ISSUE#12547] nacos client supports desensitise in logging.

core/src/main/java/com/alibaba/nacos/core/namespace/repository/EmbeddedNamespacePersistServiceImpl.java, core/src/main/java/com/alibaba/nacos/core/namespace/repository/ExternalNamespacePersistServiceImpl.java, core/src/test/java/com/alibaba/nacos/core/namespace/repository/EmbeddedNamespacePersistServiceTest.java, core/src/test/java/com/alibaba/nacos/core/namespace/repository/ExternalNamespacePersistServiceTest.java
Fixes https://github.com/alibaba/nacos/issues/12569
=> [Issue#12569] Enhance is exist table logic to support more database.

core/src/main/java/com/alibaba/nacos/core/distributed/ProtocolManager.java, sys/src/main/java/com/alibaba/nacos/sys/utils/ApplicationUtils.java
fix #12583 ProtocolManager可能导致的并发问题
- getCpProtocol()和getApProtocol()的内部实现不再锁住当前对象
- volatile修饰apInit和cpInit
- 修改ApplicationUtils.getBeanIfExist，保证异常正常抛出
XXXX
=> [ISSUE#12583] ProtocolManager代码优化

pom.xml
=> Upgrade spring to 5.3.39 and tomcat to 9.0.93

common/src/main/java/com/alibaba/nacos/common/labels/impl/DefaultLabelsCollector.java
=> fix labels from env 

api/src/main/java/com/alibaba/nacos/api/PropertyKeyConst.java, client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java, client/src/test/java/com/alibaba/nacos/client/config/impl/ClientWorkerTest.java
=> [ISSUE #12103] Enhance ClientWorker support grpc request timeout param.

config/src/main/java/com/alibaba/nacos/config/server/service/NamespaceConfigInfoService.java, config/src/test/java/com/alibaba/nacos/config/server/service/NamespaceConfigInfoServiceTest.java
=> fix derby usage filed

config/src/main/java/com/alibaba/nacos/config/server/controller/ClientMetricsController.java, config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigChangeClusterSyncRequestHandler.java, core/src/main/java/com/alibaba/nacos/core/cluster/remote/MemberReportHandler.java, core/src/main/java/com/alibaba/nacos/core/remote/RequestHandlerRegistry.java, core/src/main/java/com/alibaba/nacos/core/remote/core/ServerLoaderInfoRequestHandler.java, core/src/main/java/com/alibaba/nacos/core/remote/core/ServerReloaderRequestHandler.java, core/src/main/java/com/alibaba/nacos/core/remote/grpc/BaseGrpcServer.java, core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcClusterServer.java, core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcSdkServer.java, core/src/main/java/com/alibaba/nacos/core/remote/grpc/InvokeSource.java, core/src/test/java/com/alibaba/nacos/core/remote/RequestHandlerRegistryTest.java, core/src/test/java/com/alibaba/nacos/core/remote/grpc/GrpcServerTest.java, naming/src/main/java/com/alibaba/nacos/naming/remote/rpc/handler/DistroDataRequestHandler.java
=> grpc invoke source refactor

.github/workflows/pr-comment.yml
=> Develop add pr comment

auth/src/main/java/com/alibaba/nacos/auth/AbstractProtocolAuthService.java, auth/src/test/java/com/alibaba/nacos/auth/GrpcProtocolAuthServiceTest.java, auth/src/test/java/com/alibaba/nacos/auth/HttpProtocolAuthServiceTest.java, auth/src/test/java/com/alibaba/nacos/auth/mock/MockResourceParser.java, auth/src/test/java/com/alibaba/nacos/auth/parser/grpc/ConfigGrpcResourceParserTest.java, plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/NacosAuthPluginService.java, plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/controller/UserController.java, plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/roles/NacosRoleServiceImpl.java, plugin-default-impl/nacos-default-auth-plugin/src/test/java/com/alibaba/nacos/plugin/auth/impl/roles/NacosRoleServiceImplTest.java
=> Refactor update password api auth check and add unit test.

client/src/main/java/com/alibaba/nacos/client/config/impl/ConfigHttpClientManager.java, client/src/main/java/com/alibaba/nacos/client/utils/ParamUtil.java, client/src/test/java/com/alibaba/nacos/client/utils/ParamUtilTest.java
=> [ISSUE#12748] Support custom client configuration timeout.

console-ui/src/components/EditorNameSpace/EditorNameSpace.js, console-ui/src/pages/ConfigurationManagement/ConfigDetail/ConfigDetail.js, console-ui/src/pages/ConfigurationManagement/ConfigEditor/NewConfigEditor.js, console-ui/src/pages/ConfigurationManagement/ConfigurationManagement/ConfigurationManagement.js, console-ui/src/pages/ConfigurationManagement/ListeningToQuery/ListeningToQuery.js, console-ui/src/pages/ServiceManagement/ServiceDetail/EditClusterDialog.js, console-ui/src/pages/ServiceManagement/ServiceDetail/EditInstanceDialog.js, console-ui/src/pages/ServiceManagement/ServiceDetail/EditServiceDialog.js, console-ui/src/pages/ServiceManagement/ServiceDetail/InstanceTable.js, console-ui/src/pages/ServiceManagement/ServiceDetail/ServiceDetail.js, console-ui/src/pages/ServiceManagement/ServiceList/ServiceList.js, console/src/main/java/com/alibaba/nacos/console/controller/v3/config/ConsoleConfigController.java, console/src/main/java/com/alibaba/nacos/console/controller/v3/core/ConsoleNamespaceController.java, console/src/main/java/com/alibaba/nacos/console/controller/v3/naming/ConsoleServiceController.java, console/src/main/java/com/alibaba/nacos/console/handler/config/ConfigHandler.java, console/src/main/java/com/alibaba/nacos/console/handler/inner/config/ConfigInnerHandler.java, console/src/main/java/com/alibaba/nacos/console/proxy/config/ConfigProxy.java, console/src/test/java/com/alibaba/nacos/console/controller/v3/config/ConsoleConfigControllerTest.java, console/src/test/java/com/alibaba/nacos/console/controller/v3/core/ConsoleNamespaceControllerTest.java
For #12017
Fix backend bugs
Fix frontend bugs
* Merged the develop branch
* Fixed bugs in configuration, service, and namespace
* Modified the namespace update method
* Added two beta-related API in the config section
* Modified relevant unit tests
=> [ISSUE #12017] Fix console backend and frontend bugs

plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/controller/v3/PermissionControllerV3.java, plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/controller/v3/RoleControllerV3.java, plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/controller/v3/UserControllerV3.java, plugin-default-impl/nacos-default-auth-plugin/src/test/java/com/alibaba/nacos/plugin/auth/impl/controller/v3/UserControllerV3Test.java
=> Specified result for v3 auth console API.

core/src/main/java/com/alibaba/nacos/core/cluster/remote/ClusterRpcClientProxy.java, core/src/test/java/com/alibaba/nacos/core/cluster/remote/ClusterRpcClientProxyTest.java
=> Cluster grpc request add server identity info.

console-ui/README.md
Update the Taobao NPM mirror address in the README.md document to the latest one.
=> The Taobao NPM mirror address is outdated.  (#12869)

distribution/conf/mysql-schema.sql
Fixed nacos/distribution/conf  /mysql-schema.sql execution error
From the image above, you can see that the database will report an error when executing the sql file.
I took a closer look at the sql file and found that a **missing semicolon on line 64 and an extra comma on line 159** caused both errors.
①Line 64:
`) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='config_info_gray'`
-----》
`) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='config_info_tag';`
②Line 159:
`publish_type varchar(50) DEFAULT 'formal' COMMENT 'publish type gray or formal',,`
-----》
`publish_type varchar(50) DEFAULT 'formal' COMMENT 'publish type gray or formal',`
After executing the modified sql file, there is no …
=> [ISSUE##12864] Fixed nacos/distribution/conf/mysql-schema.sql execution error

auth/src/main/java/com/alibaba/nacos/auth/AbstractProtocolAuthService.java, auth/src/main/java/com/alibaba/nacos/auth/GrpcProtocolAuthService.java, auth/src/main/java/com/alibaba/nacos/auth/HttpProtocolAuthService.java, auth/src/main/java/com/alibaba/nacos/auth/ProtocolAuthService.java, auth/src/main/java/com/alibaba/nacos/auth/serveridentity/DefaultChecker.java, auth/src/main/java/com/alibaba/nacos/auth/serveridentity/ServerIdentity.java, auth/src/main/java/com/alibaba/nacos/auth/serveridentity/ServerIdentityChecker.java, auth/src/main/java/com/alibaba/nacos/auth/serveridentity/ServerIdentityCheckerHolder.java, auth/src/main/java/com/alibaba/nacos/auth/serveridentity/ServerIdentityResult.java, auth/src/test/java/com/alibaba/nacos/auth/GrpcProtocolAuthServiceTest.java, auth/src/test/java/com/alibaba/nacos/auth/HttpProtocolAuthServiceTest.java, auth/src/test/java/com/alibaba/nacos/auth/serveridentity/ServerIdentityCheckerHolderTest.java, common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClient.java, common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClusterClient.java, config/src/test/java/com/alibaba/nacos/config/server/controller/v2/ConfigControllerV2Test.java, console/src/main/resources/application.properties, core/src/main/java/com/alibaba/nacos/core/auth/AuthFilter.java, core/src/test/java/com/alibaba/nacos/core/auth/AuthFilterTest.java
=> Refactor Auth server identity check.

auth/src/main/java/com/alibaba/nacos/auth/GrpcProtocolAuthService.java, auth/src/test/java/com/alibaba/nacos/auth/GrpcProtocolAuthServiceTest.java, config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigChangeClusterSyncRequestHandler.java, core/src/main/java/com/alibaba/nacos/core/auth/RemoteRequestAuthFilter.java, core/src/main/java/com/alibaba/nacos/core/cluster/remote/MemberReportHandler.java, core/src/main/java/com/alibaba/nacos/core/remote/core/ServerLoaderInfoRequestHandler.java, core/src/main/java/com/alibaba/nacos/core/remote/core/ServerReloaderRequestHandler.java, core/src/test/java/com/alibaba/nacos/core/auth/RemoteRequestAuthFilterTest.java, naming/src/main/java/com/alibaba/nacos/naming/remote/rpc/handler/DistroDataRequestHandler.java
=> Support grpc inner api force check server identity info.

client/src/test/java/com/alibaba/nacos/client/naming/selector/NamingSelectorFactoryTest.java
In response to [ISSUE #12884](https://github.com/alibaba/nacos/issues/12884)
The purpose is to fix a flakiness issue in the `com.alibaba.nacos.client.naming.selector.NamingSelectorFactoryTest.testNewMetadataSelector`and `testNewMetadataSelector2` tests, caused by the non-deterministic iteration order of HashMap, which led to inconsistent test outcomes when metadata key-value pairs were accessed.
You can see this issue because `testNewMetadataSelector` and `testNewMetadataSelector2` passed when I ran them normally using the command: `mvn -pl client test -Dtest=com.alibaba.nacos.client.naming.selector.NamingSelectorFactoryTest#testNewMetadataSelector` but were failing when ran under [NonDex](https://github.com/TestingResearchIllinois/NonDex), a testing tool that identifies flaky tests …
=> [ISSUE #12884] Fix Flaky Behavior in NewMetadataSelector Tests 

client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingService.java, client/src/main/java/com/alibaba/nacos/client/naming/selector/ServiceInfoContext.java, client/src/test/java/com/alibaba/nacos/client/naming/NacosNamingServiceTest.java, client/src/test/java/com/alibaba/nacos/client/naming/selector/ServiceInfoContextTest.java
Fixes #12644 .
1. Return cached instances when getAllInstance with subscribe exception.
2. Throw subscribe exception if no cached instances .
3. getAllInstance and selectInstance with clusters new local selector but not subscribe again.
XXXX
=> [ISSUE#12644] Return cached instances when getAllInstance with subscribe exception

plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/AbstractMapper.java, plugin/datasource/src/test/java/com/alibaba/nacos/plugin/datasource/mapper/AbstractMapperTest.java
=> 【ISSUE #12911】将for循环拼接的SQL语句改为Lambda表达式拼接，使得代码简洁清晰，并添加相关测试用例

core/src/main/java/com/alibaba/nacos/core/controller/CoreOpsController.java, core/src/main/java/com/alibaba/nacos/core/controller/NacosClusterController.java, core/src/main/java/com/alibaba/nacos/core/controller/v3/CoreOpsControllerV3.java, core/src/main/java/com/alibaba/nacos/core/controller/v3/NacosClusterControllerV3.java, core/src/main/java/com/alibaba/nacos/core/controller/v3/ServerLoaderControllerV3.java, core/src/main/java/com/alibaba/nacos/core/model/form/v3/RaftCommandForm.java, core/src/main/java/com/alibaba/nacos/core/model/response/ServerLoaderMetric.java, core/src/main/java/com/alibaba/nacos/core/model/response/ServerLoaderMetrics.java, core/src/main/java/com/alibaba/nacos/core/utils/Commons.java, core/src/test/java/com/alibaba/nacos/core/controller/v3/CoreOpsControllerV3Test.java, core/src/test/java/com/alibaba/nacos/core/controller/v3/NacosClusterControllerV3Test.java, core/src/test/java/com/alibaba/nacos/core/controller/v3/ServerLoaderControllerV3Test.java
Add new admin API for core module
New Admin Api list: https://www.yuque.com/yuntiankong-ssuco/qngi85/fd87o46forpxb70n
XXXX
=> [ISSUE #12983] Add new admin API for core module

client/src/main/java/com/alibaba/nacos/client/config/impl/ConfigHttpClientManager.java, client/src/main/java/com/alibaba/nacos/client/naming/remote/http/NamingHttpClientManager.java, common/src/main/java/com/alibaba/nacos/common/executor/ThreadPoolManager.java, common/src/main/java/com/alibaba/nacos/common/http/HttpClientBeanHolder.java, common/src/main/java/com/alibaba/nacos/common/notify/NotifyCenter.java, config/src/main/java/com/alibaba/nacos/config/server/service/notify/HttpClientManager.java, naming/src/main/java/com/alibaba/nacos/naming/misc/HttpClientManager.java
This change improves the clarity and professionalism of logging messages across various components. Specifically, it updates log messages related to resource destruction processes to ensure consistent grammar, clarity, and message intent.
Updated log messages in ConfigHttpClientManager to clarify resource destruction stages.
Updated log messages in NamingHttpClientManager for better grammar and meaning.
Refined log messages in ThreadPoolManager to ensure clarity about the shutdown process.
Improved log messages in HttpClientBeanHolder to clearly describe the start and completion of HTTP client destruction.
Enhanced logging in NotifyCenter to make resource cleanup messages more professional and meaningful.
Updated …
=> [ISSUE #12946] Improve Clarity and Log Level of Shutdown Message in HttpClientBeanHolder 

naming/src/main/java/com/alibaba/nacos/naming/controllers/v2/ClientInfoControllerV2.java, naming/src/test/java/com/alibaba/nacos/naming/controllers/v2/ClientInfoControllerV2Test.java
Add a new param to support return all subscriber when ip or port is null.
=>  Return all subscriber when ip or port is null.

config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigServletInner.java, config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigQueryRequestHandler.java, config/src/main/java/com/alibaba/nacos/config/server/service/query/DefaultConfigQueryHandlerChainBuilder.java, config/src/main/java/com/alibaba/nacos/config/server/service/query/handler/AbstractConfigQueryHandler.java, config/src/main/java/com/alibaba/nacos/config/server/service/query/handler/ConfigContentTypeHandler.java, config/src/main/java/com/alibaba/nacos/config/server/service/query/handler/FormalHandler.java, config/src/main/java/com/alibaba/nacos/config/server/service/query/handler/GrayRuleMatchHandler.java, config/src/main/java/com/alibaba/nacos/config/server/service/query/handler/SpecialTagNotFoundHandler.java, config/src/main/java/com/alibaba/nacos/config/server/service/query/model/ConfigQueryChainResponse.java, config/src/test/java/com/alibaba/nacos/config/server/remote/ConfigQueryRequestHandlerTest.java, config/src/test/java/com/alibaba/nacos/config/server/service/query/DefaultChainRequestExtractorTest.java, config/src/test/java/com/alibaba/nacos/config/server/service/query/handler/ConfigChainEntryHandlerTest.java, config/src/test/java/com/alibaba/nacos/config/server/service/query/handler/ConfigContentTypeHandlerTest.java, config/src/test/java/com/alibaba/nacos/config/server/service/query/handler/FormalHandlerTest.java, config/src/test/java/com/alibaba/nacos/config/server/service/query/handler/GrayRuleMatchHandlerTest.java, config/src/test/java/com/alibaba/nacos/config/server/service/query/handler/SpecialTagNotFoundHandlerTest.java
fix #13023, Add Unit Test for ConfigQueryHandlerChain and handlers, fix the logic of SpecialTagNotFoundHandler, add ConfigContentTypeHandler
XX
XXXX
* [*] Write a pull request description …
=> [ISSUE #13023]Add Unit Test for ConfigQueryHandlerChainn and optimize the logic

api/src/main/java/com/alibaba/nacos/api/model/v2/ErrorCode.java, config/src/main/java/com/alibaba/nacos/config/server/constant/Constants.java, config/src/main/java/com/alibaba/nacos/config/server/controller/CapacityController.java, config/src/main/java/com/alibaba/nacos/config/server/controller/ClientMetricsController.java, config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigController.java, config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigOpsController.java, config/src/main/java/com/alibaba/nacos/config/server/controller/HealthController.java, config/src/main/java/com/alibaba/nacos/config/server/controller/HistoryController.java, config/src/main/java/com/alibaba/nacos/config/server/controller/v2/ConfigControllerV2.java, config/src/main/java/com/alibaba/nacos/config/server/controller/v2/HistoryControllerV2.java, config/src/main/java/com/alibaba/nacos/config/server/controller/v3/CapacityControllerV3.java, config/src/main/java/com/alibaba/nacos/config/server/controller/v3/ConfigControllerV3.java, config/src/main/java/com/alibaba/nacos/config/server/controller/v3/ConfigOpsControllerV3.java, config/src/main/java/com/alibaba/nacos/config/server/controller/v3/HistoryControllerV3.java, config/src/main/java/com/alibaba/nacos/config/server/controller/v3/ListenerControllerV3.java, config/src/main/java/com/alibaba/nacos/config/server/controller/v3/MetricsControllerV3.java, config/src/main/java/com/alibaba/nacos/config/server/model/form/UpdateCapacityForm.java, config/src/test/java/com/alibaba/nacos/config/server/controller/v3/CapacityControllerV3Test.java, config/src/test/java/com/alibaba/nacos/config/server/controller/v3/ConfigControllerV3Test.java, config/src/test/java/com/alibaba/nacos/config/server/controller/v3/ConfigOpsControllerV3Test.java, config/src/test/java/com/alibaba/nacos/config/server/controller/v3/HistoryControllerV3Test.java, config/src/test/java/com/alibaba/nacos/config/server/controller/v3/ListenerControllerV3Test.java, config/src/test/java/com/alibaba/nacos/config/server/controller/v3/MetricControllerV3Test.java
=> [ISSUE#12968] Develop config admin api.

common/src/main/java/com/alibaba/nacos/common/Beta.java, config/src/main/java/com/alibaba/nacos/config/server/controller/v3/ConfigControllerV3.java, config/src/main/java/com/alibaba/nacos/config/server/controller/v3/HistoryControllerV3.java, config/src/main/java/com/alibaba/nacos/config/server/controller/v3/ListenerControllerV3.java, config/src/main/java/com/alibaba/nacos/config/server/model/form/ConfigForm.java, config/src/test/java/com/alibaba/nacos/config/server/controller/v3/HistoryControllerV3Test.java, core/src/main/java/com/alibaba/nacos/core/controller/v3/CoreOpsControllerV3.java, core/src/main/java/com/alibaba/nacos/core/controller/v3/NacosClusterControllerV3.java, core/src/main/java/com/alibaba/nacos/core/controller/v3/ServerLoaderControllerV3.java, core/src/main/java/com/alibaba/nacos/core/model/response/ServerLoaderMetrics.java, naming/src/main/java/com/alibaba/nacos/naming/controllers/v3/ClientControllerV3.java, naming/src/main/java/com/alibaba/nacos/naming/controllers/v3/InstanceControllerV3.java, naming/src/main/java/com/alibaba/nacos/naming/controllers/v3/ServiceControllerV3.java, naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperator.java, naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperatorClientImpl.java, naming/src/main/java/com/alibaba/nacos/naming/core/Operator.java, naming/src/main/java/com/alibaba/nacos/naming/model/form/ClientServiceForm.java, naming/src/test/java/com/alibaba/nacos/naming/controllers/v3/InstanceControllerV3Test.java, naming/src/test/java/com/alibaba/nacos/naming/controllers/v3/ServiceControllerV3Test.java
=> V3.0 develop admin adi enhance and refactor.

auth/src/main/java/com/alibaba/nacos/auth/AbstractProtocolAuthService.java, auth/src/main/java/com/alibaba/nacos/auth/serveridentity/ServerIdentityCheckerHolder.java, auth/src/test/java/com/alibaba/nacos/auth/serveridentity/ServerIdentityCheckerHolderTest.java, bootstrap/src/main/resources/application.properties, core/src/main/java/com/alibaba/nacos/core/auth/AbstractWebAuthFilter.java, core/src/main/java/com/alibaba/nacos/core/auth/AuthAdminFilter.java, core/src/main/java/com/alibaba/nacos/core/auth/AuthConfig.java, core/src/main/java/com/alibaba/nacos/core/auth/NacosServerAdminAuthConfig.java, core/src/main/java/com/alibaba/nacos/core/controller/ServerLoaderController.java, core/src/main/java/com/alibaba/nacos/core/controller/compatibility/ApiCompatibilityConfig.java, distribution/conf/application.properties, naming/src/main/java/com/alibaba/nacos/naming/controllers/v3/InstanceControllerV3.java, naming/src/main/java/com/alibaba/nacos/naming/model/form/InstanceListForm.java, naming/src/test/java/com/alibaba/nacos/naming/controllers/v3/InstanceControllerV3Test.java, plugin/auth/src/main/java/com/alibaba/nacos/plugin/auth/constant/Constants.java
For https://github.com/alibaba/nacos/issues/12953.
XX
XXXX
=> Fix some 3.0 admin api problem.

client/src/main/java/com/alibaba/nacos/client/auth/impl/NacosClientAuthServiceImpl.java, client/src/test/java/com/alibaba/nacos/client/auth/impl/NacosClientAuthServiceImplTest.java
For [issue#12823](https://github.com/alibaba/nacos/issues/12823#issuecomment-2586872688)
XX
XXXX
=> [ISSUE #12823] Randomly generate TokenRefreshWindow

naming/src/main/java/com/alibaba/nacos/naming/controllers/v3/InstanceControllerV3.java, naming/src/main/java/com/alibaba/nacos/naming/controllers/v3/OperatorControllerV3.java
=> Fix resource annotation in V3.0 controller

logger-adapter-impl/log4j2-adapter/src/main/resources/nacos-log4j2.xml
I don't think the default value should be true，As a configuration for the production, it is best to have automatic archiving
=> Update log4j config testMode default value

.github/workflows/pr-ci.yml, .github/workflows/pr-e2e-test.yml, .github/workflows/push-ci.yaml
-  Request will be automatically failed cased by a deprecated version of `actions/upload-artifact: v3`;
- "actions/upload-artifact: v3" and "actions/github-script@v3.1.0"  do not match which will result in pipeline failure;
- The repository will not be found result of "https://ghproxy.com".
- change `actions/upload-artifact` version from v3 to v4;
- change `actions/github-script` version from v3 to v6;
- delete "https://ghproxy.com".
XXXX
=> Fix version bug

naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/impl/PersistentClientOperationServiceImpl.java
=> [ISSUE#13027] Fix persistent service instance metadata will not be expired after instance deregister.

plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/NacosAuthConfig.java, plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/SafeBcryptPasswordEncoder.java, plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/constant/AuthConstants.java, plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/utils/PasswordEncoderUtil.java, plugin-default-impl/nacos-default-auth-plugin/src/test/java/com/alibaba/nacos/plugin/auth/impl/SafeBcryptPasswordEncoderTest.java, plugin-default-impl/nacos-default-auth-plugin/src/test/java/com/alibaba/nacos/plugin/auth/impl/utils/PasswordEncoderUtilTest.java
Fix #13205
BCryptPasswordEncoder.matches(CharSequence,String) will incorrectly return true for passwords larger than 72 characters as long as the first 72 characters are the same.
Implement `SafeBcryptPasswordEncoder` to address password length vulnerability
`com.alibaba.nacos.plugin.auth.impl.SafeBcryptPasswordEncoderTest`
=> [ISSUE #13205] Implement `SafeBcryptPasswordEncoder` to address password length vulnerability

distribution/bin/startup.sh
refactoring startup script
1. use a variable to store the log file path, instead of hard-coded multiple times.
2. the log file contains stdout & stderr, startup.log file is preferred. start.out may mean output only.
3. the echo command is not needed to run in background. And also no need to redirect stderr to stdout.
4. variable/string concatenation style. pure variable in quotes, no curly braces needed, as "$var" . String and variable in quotes, braces needed, as "some string ${var}continue".
=> [noissue] bin/startup.sh, refactoring, extract variable

pom.xml
Add build-helper-maven-plugin in root pom.xml to help IDEA automatically recognize generated source files under target/generated-sources directory, avoiding red squiggles in IDEA after source code import.
- Add build-helper-maven-plugin configuration in root pom.xml to add generated sources directory
1. Import project into IDEA
2. Verify that generated source files under target/generated-sources are properly recognized by IDEA
3. Verify no red squiggles appear for the generated source files
This change:
=> [ISSUE #13297] Add build-helper-maven-plugin to support IDEA auto-recognize generated sources

pom.xml
https://github.com/alibaba/nacos/issues/13358
XXXXX
XX
XXXX
=> :wrench: use Maven Central Portal

config/src/main/java/com/alibaba/nacos/config/server/aspect/ConfigChangeAspect.java, config/src/test/java/com/alibaba/nacos/config/server/aspect/ConfigChangeAspectTest.java, plugin/config/src/main/java/com/alibaba/nacos/plugin/config/ConfigChangePluginManager.java
=> [ISSUE#13249] Fix configuration change plugin return incompatibility.

common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClientFactory.java, common/src/test/java/com/alibaba/nacos/common/remote/client/RpcClientFactoryTest.java, core/src/main/java/com/alibaba/nacos/core/cluster/remote/ClusterRpcClientProxy.java
https://github.com/alibaba/nacos/issues/13273
RpcClientFactory新增方法支持GrpcClientConfig构建GrpcClusterClient，ClusterRpcClientProxy构建GrpcClient时通过properties构建GrpcClientConfig，然后再t通过RpcClientFactory的构建方法构建。这样就可以通过nacos.remote.server.grpc.xxx相关配置设置集群间GrpcClient属性。
Verifying this change
通过测试验证配置nacos.remote.server.grpc.max-inboud-message-size可设置集群间grpc传输最值大，集群间grpc也支持nacos.remote.server.grpc.xxx相关配置，
=> [ISSUE #13273]: 2.x support create cluseter client use nacos.remote.client.grpc config

common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClientFactory.java, common/src/test/java/com/alibaba/nacos/common/remote/client/RpcClientFactoryTest.java, core/src/main/java/com/alibaba/nacos/core/cluster/remote/ClusterRpcClientProxy.java
https://github.com/alibaba/nacos/issues/13273
RpcClientFactory新增方法支持GrpcClientConfig构建GrpcClusterClient，ClusterRpcClientProxy构建GrpcClient时通过properties构建GrpcClientConfig，然后再t通过RpcClientFactory的构建方法构建。这样就可以通过nacos.remote.server.grpc.xxx相关配置设置集群间GrpcClient属性。
通过测试验证配置nacos.remote.server.grpc.max-inboud-message-size可设置集群间grpc传输最值大，集群间grpc也支持nacos.remote.server.grpc.xxx相关配置，
=> [ISSUE #13273]: support create cluseter client use nacos.remote.client.grpc config

core/src/main/java/com/alibaba/nacos/core/utils/RemoteUtils.java
Fix the comment about "remote executors thread times of processors" 
Fix the comment about "remote executors thread times of processors" - the default is 16
=> [ISSUE #13485]  Fix the comment about "remote executors thread times of processors" - the default is 16

ai/src/main/java/com/alibaba/nacos/ai/service/McpServerOperationService.java
Purpose of the Change
Improve clarity and diagnostic value of error logs when MCP server version information is not found. The original error message was ambiguous and contained formatting issues, making debugging difficult.
=> fox#13565 Optimize error logs for MCP server not found scenario

client/src/main/java/com/alibaba/nacos/client/config/impl/CacheData.java, client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java, client/src/main/java/com/alibaba/nacos/client/config/impl/ConfigFuzzyWatchGroupKeyHolder.java, client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingService.java, client/src/main/java/com/alibaba/nacos/client/naming/cache/NamingFuzzyWatchServiceListHolder.java, common/src/main/java/com/alibaba/nacos/common/notify/DefaultPublisher.java, common/src/main/java/com/alibaba/nacos/common/notify/NotifyCenter.java
在本地启动 NacosConfigService 和 NacosNamingService 后分析内存快照发现的确有资源未被及时回收，我觉得可以分为两种情况讨论：
- ClientWorker.ConfigRpcTransportClient#multiTaskExecutor: 线程池未关闭
- CacheData#scheduledExecutor: 线程池未关闭，并发现了双重检测锁创建线程池时未将变量使用 voliatile 修饰的问题
如题，也是这个 ISSUE 中主要的问题。
NotifyCenter 的静态代码块中注册了钩子方法 ThreadUtils.addShutdownHook(NotifyCenter::shutdown);，在 System.exit 等条件下会被触发到，而从 ISSUE 中的描述来看，他主动手动去卸载了这些能够在钩子方法中卸载的资源，说明在 war 部署并关闭应用时，这个钩子方法没有被执行到，所以导致了一系列的 DefaultPublisher 和 DefaultSharePublisher 线程没有被关闭。
同样地，还有 ThreadPoolManager#resourcesManager 中被统一管理的线程池资源也是采用了在静态代码块中注册钩子方法来完成卸载的，如果 war 包应用关闭时无法触发这个钩子方法，这里面的线程池也不会被回收。
我在代码里添加了主动调用 NotifyCenter#shutdown 的逻辑以达成释放 DefaultPublisher 等线程资源的目的，但是这样改我觉得不优雅，麻烦有时间帮忙 Review。并且我在 DefaultPublisher#shutdown 方法中添加了 this.interrupt(); 逻辑帮助线程关闭。
此外，ThreadPoolManager 中的资源我不清楚在哪里主动调用 …
=> [ISSUE #13546] help gc

api/src/main/java/com/alibaba/nacos/api/common/Constants.java, auth/src/main/java/com/alibaba/nacos/auth/parser/AbstractResourceParser.java, auth/src/main/java/com/alibaba/nacos/auth/parser/http/ConfigHttpResourceParser.java, auth/src/test/java/com/alibaba/nacos/auth/parser/http/ConfigHttpResourceParserTest.java, config/src/main/java/com/alibaba/nacos/config/server/controller/v3/ConfigControllerV3.java, console/src/main/java/com/alibaba/nacos/console/controller/v3/config/ConsoleConfigController.java, plugin/auth/src/main/java/com/alibaba/nacos/plugin/auth/constant/Constants.java
fix: #13600  
This change is to address the problem in ISSUE #13600 where regular users with read and write permissions fail to clone configurations.
Fixed the cloning exception caused by the mismatch between the `namespaceId` that requires authentication in the ordinary user's configuration cloning interface and the currently used authentication `namespaceId`. Actually, the `targetNamespaceId` should be obtained for authentication. However, in line 105 of the doFilter method in `AbstractWebAuthFilter.java`, the `resource` fails to obtain the `targetNamespaceId`, and the default `public` namespace is used, resulting in authentication errors and configuration cloning failures. This commit fixes the way the namespace …
=> 【Fix issue #13600】 auth error when non-admin users clone config
