README.md

**What is the purpose of the change**
modify "Nacos provides four major funcations“ to  "Nacos provides four major functions“,here the funcations is wrong spell
**Brief changelog**
modify "Nacos provides four major funcations“ to  "Nacos provides four major functions“,here the funcations is wrong spell

Fix README.md modify funcation to function

---

naming/pom.xml

delete the duplicate maven config
#82

fix duplicate Maven dependencies(#82)

---

README.md

I fixed a typo in README.md
I only fixed a typo.

fixed designed

---

naming/src/main/java/com/alibaba/nacos/naming/misc/Loggers.java
naming/src/main/java/com/alibaba/nacos/naming/misc/ServerStatusSynchronizer.java

remove useless import
- remove `import java.io.File` from `Loggers.java`
- remove `import java.util.Arrays` and `import java.util.List` from `ServerStatusSynchronizer.java`

[ISSUE #116]remove useless import

---

naming/src/main/java/com/alibaba/nacos/naming/raft/PeerSet.java

[ISSUE #89] Change deprecated apache ObjectUtils equals to java.util Objects equals in PeerSet

---

client/src/main/java/com/alibaba/nacos/client/config/utils/MD5.java
config/src/main/java/com/alibaba/nacos/config/server/constant/Constants.java
config/src/main/java/com/alibaba/nacos/config/server/utils/TimeUtils.java

1：the name of the variable is consistent with the method explanation
2：delete the unused code

improving code quality

---

test/src/test/java/com/alibaba/nacos/test/config/ConfigAPI_ITCase.java

1. add open api testcases
1. add open api testcases
add testcase

add open api testcases

---

config/src/main/resources/META-INF/logback/nacos-included.xml
core/src/main/resources/META-INF/logback/nacos.xml
core/src/test/java/com/alibaba/nacos/core/env/NacosDefaultPropertySourceEnvironmentPostProcessorTest.java
naming/src/main/resources/META-INF/logback/nacos-included.xml
test/src/test/java/com/alibaba/nacos/test/naming/ServiceListTest.java
test/src/test/resources/application.properties

Fixed test cases

---

README.md

This is to fix [ISSUE #157], Add more information in README.md to reflect the echosystem

Add more information in README.md to reflect the echosystem, fix [ISSUE #157],

---

console/src/main/resources/static/src/pages/ServiceManagement/ServiceList/ServiceList.js

Fix a bug in PR #211，Delete refresh table

Fix a bug in PR #211

---

console/src/main/resources/static/src/pages/ServiceManagement/ServiceList/ServiceList.js

FE rollback, service list, remove new and delete buttons

fix: fe rollback, service list

---

console/src/main/resources/static/src/pages/ServiceManagement/ServiceList/ServiceList.js

FE rollback, service list, remove new and delete buttons

FE rollback, service list

---

REPORTING-BUGS.md

fix issue #239 
我们非常认真地对待错误和错误 -> 我们非常认真地对待错误和缺陷

fix issue #239

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md
pom.xml

#166 
Enrich the content of CONTRIBUTING
README.MD
CONTRIBUTING.MD
CODE_OF_CONDUCT.md

Enrich the content of CONTRIBUTING

---

console/src/main/resources/static/src/pages/ConfigurationManagement/ConfigurationManagement/ConfigurationManagement.js

Remove the Balloon of DataId/Group.
[ISSUE #258]
Remove the Balloon of DataId/Group

[ISSUE #258] Remove the Balloon of DataId/Group.

---

console/src/main/resources/static/src/pages/ServiceManagement/ServiceDetail/InstanceTable.js

fix: closes #256

---

client/pom.xml

Hide mvn repository config

---

distribution/bin/startup.sh

issue ##314
GC log does not take effect
GC log does not take effect
#314

fix : GC log does not take effect

---

client/src/main/java/com/alibaba/nacos/client/naming/core/HostReactor.java
client/src/main/java/com/alibaba/nacos/client/naming/net/HttpClient.java
client/src/main/java/com/alibaba/nacos/client/naming/net/NamingProxy.java
client/src/main/java/com/alibaba/nacos/client/naming/utils/NetUtils.java
naming/src/main/java/com/alibaba/nacos/naming/healthcheck/AbstractHealthCheckProcessor.java
naming/src/main/java/com/alibaba/nacos/naming/web/ApiCommands.java

Optimize code
1. [ISSUE #377 ] Clean up messy code in Naming module.

#377 Clean up code

---

README.md
naming/src/main/java/com/alibaba/nacos/naming/web/ApiCommands.java
test/src/test/java/com/alibaba/nacos/test/naming/SelectInstances_ITCase.java

Fix bug
1. [ISSUE #388 ] Fix cluster name lost bug.

Hotfix cluster lost in instance

---

client/src/main/java/com/alibaba/nacos/client/logger/slf4j/Slf4jLogger.java
console/pom.xml
console/src/main/java/com/alibaba/nacos/console/controller/HealthController.java
console/src/test/java/com/alibaba/nacos/console/controller/HealthControllerTest.java

Fixes #391 Fixes #229

---

console/src/main/resources/static/console-fe/src/pages/ServiceManagement/ServiceDetail/InstanceTable.js

#362 bugfix, Add parameter metadata

Fixes #362

---

test/pom.xml
test/src/test/java/com/alibaba/nacos/test/config/ConfigAPI_ITCase.java
test/src/test/java/com/alibaba/nacos/test/naming/AutoDeregisterInstance_ITCase.java
test/src/test/java/com/alibaba/nacos/test/naming/DeregisterInstance_ITCase.java
test/src/test/java/com/alibaba/nacos/test/naming/RegisterInstance_ITCase.java
test/src/test/java/com/alibaba/nacos/test/naming/SelectInstances_ITCase.java
test/src/test/java/com/alibaba/nacos/test/naming/SelectOneHealthyInstance_ITCase.java
test/src/test/java/com/alibaba/nacos/test/naming/ServiceListTest.java
test/src/test/java/com/alibaba/nacos/test/naming/SubscribeCluster_ITCase.java
test/src/test/java/com/alibaba/nacos/test/naming/Subscribe_ITCase.java
test/src/test/java/com/alibaba/nacos/test/naming/Unsubscribe_ITCase.java

[ISSUE #243]fix Integration testing too long
modify naming and config testcases 

[ISSUE #243]fix Integration testing too long

---

console/src/main/resources/static/console-fe/src/pages/ConfigurationManagement/NewConfig/NewConfig.js
console/src/main/resources/static/console-fe/src/pages/ServiceManagement/ServiceDetail/InstanceTable.js

Fixes #353

---

.editorconfig

added editorconfig to maintain consistent coding styles. more infos https://editorconfig.org/
added `.editorconfig` file to nacos project root dir.
e.g. idea ide ,locked:
1. 4 space,
2. charset is utf-8
3. end of line style is LF

[ISSUE #417] maintain consistent coding styles

---

core/pom.xml
core/src/main/resources/banner.txt

Fixes #432
Fixes #432
Fixes #432

[ISSUE #123] When packing nacos-core, ${user.home} is replaced in the logback configuration file (nacos.xml)

---

config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigServletInner.java
config/src/main/java/com/alibaba/nacos/config/server/service/BasicDataSourceServiceImpl.java
config/src/main/java/com/alibaba/nacos/config/server/service/ConfigService.java
config/src/main/java/com/alibaba/nacos/config/server/service/DynamicDataSource.java
config/src/main/java/com/alibaba/nacos/config/server/service/LocalDataSourceServiceImpl.java
config/src/main/java/com/alibaba/nacos/config/server/service/capacity/GroupCapacityPersistService.java
config/src/main/java/com/alibaba/nacos/config/server/service/capacity/TenantCapacityPersistService.java
config/src/main/java/com/alibaba/nacos/config/server/utils/PaginationHelper.java
config/src/main/java/com/alibaba/nacos/config/server/utils/PropertyUtil.java
config/src/main/java/com/alibaba/nacos/config/server/utils/RunningConfigUtils.java
distribution/conf/application.properties

nacos support mysql in the case of stand-alone mode
[ISSUE #395 ] Fix nacos not support mysql in the case of stand-alone mode

Fixes #395

---

CHANGELOG.md
api/src/main/java/com/alibaba/nacos/api/cmdb/spi/CmdbService.java
client/src/test/java/com/alibaba/nacos/client/NamingTest.java
cmdb/src/main/java/com/alibaba/nacos/cmdb/controllers/OperationController.java
cmdb/src/main/java/com/alibaba/nacos/cmdb/core/SwitchAndOptions.java
cmdb/src/main/java/com/alibaba/nacos/cmdb/memory/CmdbProvider.java
console/src/main/resources/META-INF/nacos-default.properties
distribution/conf/application.properties

Code optimization
1. Add label dump task.
2. Add debug log

Feature cmdb

---

naming/src/main/java/com/alibaba/nacos/naming/raft/GlobalExecutor.java
naming/src/main/java/com/alibaba/nacos/naming/raft/RaftPeer.java

Rename the property RAMDOM_MS in class GlobalExecutor to RANDOM_MS
fix a spelling mistake

fix a spelling mistake

---

naming/src/main/java/com/alibaba/nacos/naming/raft/GlobalExecutor.java
naming/src/main/java/com/alibaba/nacos/naming/raft/RaftCore.java
naming/src/main/java/com/alibaba/nacos/naming/raft/RaftPeer.java

Rename the property HEARTBEAT_INTVERAL_MS in class GlobalExecutor to HEARTBEAT_INTERVAL_MS;
Rename the property ADDRESS_SERVER_UPDATE_INTVERAL_MS in class GlobalExecutor to ADDRESS_SERVER_UPDATE_INTERVAL_MS.
fix some spelling mistakes

 fix some spelling mistakes

---

client/src/main/java/com/alibaba/nacos/client/config/impl/LocalConfigInfoProcessor.java

Fixes #336 #439 
Fixes #336 #439 
Fixes #336 #439 

[ISSUE #439] save snapshot error

---

console/src/main/resources/static/console-fe/src/components/BatchHandle/BatchHandle.js
console/src/main/resources/static/console-fe/src/components/CloneDialog/CloneDialog.js
console/src/main/resources/static/console-fe/src/components/DeleteDialog/DeleteDialog.js
console/src/main/resources/static/console-fe/src/locales/en-US.js
console/src/main/resources/static/console-fe/src/locales/zh-CN.js

Fixes #474 CloneDialog

---

console/src/main/resources/static/console-fe/src/components/ExportDialog/ExportDialog.js
console/src/main/resources/static/console-fe/src/locales/en-US.js
console/src/main/resources/static/console-fe/src/locales/zh-CN.js
console/src/main/resources/static/console-fe/src/pages/ConfigurationManagement/ConfigurationManagement/ConfigurationManagement.js

Fixes #474 ExportDialog

---

.gitignore

add .vscode and .factorypath to .gitignore

[ISSUE #490] fix gitignore

---

client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingService.java
client/src/main/java/com/alibaba/nacos/client/naming/beat/BeatInfo.java
client/src/main/java/com/alibaba/nacos/client/naming/beat/BeatReactor.java
distribution/conf/nacos-logback.xml
naming/src/main/java/com/alibaba/nacos/naming/controllers/ServiceController.java
naming/src/main/java/com/alibaba/nacos/naming/core/DomainsManager.java
naming/src/main/java/com/alibaba/nacos/naming/core/VirtualClusterDomain.java
naming/src/main/java/com/alibaba/nacos/naming/misc/HttpClient.java
naming/src/main/java/com/alibaba/nacos/naming/misc/Switch.java
naming/src/main/java/com/alibaba/nacos/naming/misc/UtilsAndCommons.java
naming/src/main/java/com/alibaba/nacos/naming/push/PushService.java
naming/src/main/java/com/alibaba/nacos/naming/raft/RaftCore.java
naming/src/main/java/com/alibaba/nacos/naming/web/ApiCommands.java
naming/src/main/java/com/alibaba/nacos/naming/web/RaftCommands.java
naming/src/test/java/com/alibaba/nacos/naming/core/DomainsManagerTest.java
test/src/test/java/com/alibaba/nacos/test/naming/AutoDeregisterInstance_ITCase.java
test/src/test/java/com/alibaba/nacos/test/naming/SelectInstances_ITCase.java

Fix bug
1. [#526] Possible data inconsistency in server side health check mode. 

Hotfix server side check lose data

---

distribution/conf/application.properties

Add access log setting
1. #558 Add access log setting

#558 Add access log setting

---

console/src/main/resources/static/console-fe/src/components/SuccessDialog/SuccessDialog.js
console/src/main/resources/static/console-fe/src/locales/en-US.js
console/src/main/resources/static/console-fe/src/locales/zh-CN.js
console/src/main/resources/static/console-fe/src/pages/ConfigurationManagement/ConfigEditor/ConfigEditor.js
console/src/main/resources/static/console-fe/src/pages/ConfigurationManagement/ConfigSync/ConfigSync.js
console/src/main/resources/static/console-fe/src/pages/ConfigurationManagement/NewConfig/NewConfig.js

- SuccessDialog
* ConfigEditor
* ConfigSync
* NewConfig
- 
- 

refactor: SuccessDialog i18n #474

---

CONTRIBUTING.md
api/src/main/java/com/alibaba/nacos/api/config/ConfigFactory.java
api/src/main/java/com/alibaba/nacos/api/config/filter/IConfigContext.java
api/src/main/java/com/alibaba/nacos/api/config/filter/IConfigFilter.java
api/src/main/java/com/alibaba/nacos/api/config/filter/IConfigFilterChain.java
api/src/main/java/com/alibaba/nacos/api/config/filter/IConfigRequest.java
api/src/main/java/com/alibaba/nacos/api/config/filter/IConfigResponse.java
api/src/main/java/com/alibaba/nacos/api/config/filter/IFilterConfig.java
api/src/main/java/com/alibaba/nacos/api/config/listener/AbstractListener.java
api/src/main/java/com/alibaba/nacos/api/config/listener/Listener.java
distribution/bin/startup.cmd
example/src/main/java/com/alibaba/nacos/example/ConfigExample.java

changes:
+ correct spelling error, eg: Listner
+ refactor repeat code

Correct typos and Remove unnecessary method modifier in Interface

---

client/src/main/java/com/alibaba/nacos/client/config/listener/impl/PropertiesListener.java
config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigController.java
config/src/main/java/com/alibaba/nacos/config/server/controller/HealthController.java
config/src/main/java/com/alibaba/nacos/config/server/controller/ListenerController.java
config/src/main/java/com/alibaba/nacos/config/server/controller/OpsController.java
config/src/main/java/com/alibaba/nacos/config/server/manager/TaskManagerMBean.java
config/src/main/java/com/alibaba/nacos/config/server/service/BasicDataSourceServiceImpl.java

read the ```config``` code and do some cleanup:
+ add @Override annotation for the Interface implement, eg: PropertiesListener,BasicDataSourceServiceImpl
+ translate the msg from chinese to english, eg: HealthController
+ format some comment blocks,eg: OpsController

Clean the code in config module 

---

config/src/main/java/com/alibaba/nacos/config/server/utils/RequestUtil.java
config/src/test/java/com/alibaba/nacos/config/server/utils/RequestUtilTest.java
test/src/test/java/com/alibaba/nacos/test/naming/NamingBase.java
test/src/test/java/com/alibaba/nacos/test/naming/RestAPI_ITCase.java
test/src/test/java/com/alibaba/nacos/test/naming/ServiceListTest.java

config 获取客服端 ip 时添加 X-Forwarded-For 的支持

---

api/src/main/java/com/alibaba/nacos/api/common/Constants.java
client/src/main/java/com/alibaba/nacos/client/config/NacosConfigService.java
client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java
client/src/main/java/com/alibaba/nacos/client/naming/core/HostReactor.java
client/src/main/java/com/alibaba/nacos/client/naming/core/PushReceiver.java
config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigServletInner.java
config/src/main/java/com/alibaba/nacos/config/server/controller/ListenerController.java
config/src/main/java/com/alibaba/nacos/config/server/service/LongPollingService.java

Fix #442 and reopen to merge into the branch "develop".

[ISSUE #442] Fix typos in class names and variables.

---

naming/src/main/java/com/alibaba/nacos/naming/controllers/HealthController.java

issue #579 update health in none health check mode through api

---

client/src/main/java/com/alibaba/nacos/client/config/http/MetricsHttpAgent.java
naming/src/main/java/com/alibaba/nacos/naming/monitor/PerformanceLoggerThread.java

surpport metrics

---

api/src/main/java/com/alibaba/nacos/api/exception/NacosException.java
config/src/main/java/com/alibaba/nacos/config/server/model/ConfigKey.java

remove useless semicolon 删除无用的分号
NacosException.java，ConfigKey.java remove useless semicolon 删除无用的分号

remove useless semicolon

---

console/src/main/java/com/alibaba/nacos/console/filter/JwtAuthenticationTokenFilter.java

JwtAuthenticationTokenFilter.java  50 row 
if String jwt =null
jwt.trim() Will have a NPE
fix JwtAuthenticationTokenFilter.java  50 row NPE

fix JwtAuthenticationTokenFilter NPE bug

---

distribution/bin/startup.sh

Fix CMDB JVM option error

---

console/src/main/resources/static/console-fe/src/pages/Login/index.scss

fix the style

---

naming/src/main/java/com/alibaba/nacos/naming/web/ApiCommands.java

Compatible for old DNS-F client
#678 

Close #678

---

README.md

Update README.MD for update fenghuang LOGO
Update README.MD for update fenghuang LOGO
Update README.MD for update fenghuang LOGO
close #723
close #723

Update README.MD for update fenghuang LOGO

---

naming/src/main/java/com/alibaba/nacos/naming/push/PushService.java

#720 Memory leak in PushService

---

client/pom.xml
client/src/main/java/com/alibaba/nacos/client/config/http/MetricsHttpAgent.java
client/src/main/java/com/alibaba/nacos/client/monitor/MetricsMonitor.java
client/src/main/java/com/alibaba/nacos/client/naming/net/NamingProxy.java

fix not support java 1.7

---

api/pom.xml
api/src/main/java/com/alibaba/nacos/api/PropertyKeyConst.java
api/src/main/java/com/alibaba/nacos/api/SystemPropertyKeyConst.java
client/pom.xml
client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingService.java
client/src/main/java/com/alibaba/nacos/client/naming/net/NamingProxy.java
cmdb/pom.xml
common/pom.xml
config/pom.xml
console/pom.xml
core/pom.xml
distribution/pom.xml
example/pom.xml
naming/pom.xml
pom.xml
test/pom.xml

Support higher priority system properties for NamingService

---

naming/src/main/java/com/alibaba/nacos/naming/core/Cluster.java
naming/src/main/java/com/alibaba/nacos/naming/web/ApiCommands.java

Registering instance should update valid (health)

Registering instance should update valid (health)

---

naming/src/main/java/com/alibaba/nacos/naming/raft/RaftCore.java

signalPublish with !STANDALONE_MODE on publish data to other servers.
`if (!STANDALONE_MODE && !latch.await(UtilsAndCommons.RAFT_PUBLISH_TIMEOUT, TimeUnit.MILLISECONDS))`
XXXX

signalPublish with not STANDALONE_MODE

---

naming/src/main/java/com/alibaba/nacos/naming/pojo/IpAddressInfo.java

Obsessive-compulsive disorder: simply align all
XX
XXXX

Align attribute name

---

client/src/main/java/com/alibaba/nacos/client/logging/logback/LogbackNacosLogging.java
client/src/main/java/com/alibaba/nacos/client/naming/backups/FailoverReactor.java
client/src/main/java/com/alibaba/nacos/client/naming/beat/BeatReactor.java
client/src/main/java/com/alibaba/nacos/client/naming/cache/DiskCache.java
client/src/main/java/com/alibaba/nacos/client/naming/core/EventDispatcher.java
client/src/main/java/com/alibaba/nacos/client/naming/core/HostReactor.java
client/src/main/java/com/alibaba/nacos/client/naming/core/PushReceiver.java
client/src/main/java/com/alibaba/nacos/client/naming/net/HttpClient.java
client/src/main/java/com/alibaba/nacos/client/naming/net/NamingProxy.java

Fixes #826 
Fixes #826
Fixes #826 

Refactoring the log of naming

---

client/src/main/java/com/alibaba/nacos/client/config/NacosConfigService.java
client/src/main/java/com/alibaba/nacos/client/config/impl/ServerListManager.java
client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingService.java

Code robustness to enhance the null value of properties

---

client/src/main/java/com/alibaba/nacos/client/logging/log4j2/Log4J2NacosLogging.java

Fixes #868
Fixes #868
Fixes #868

Fixes #868

---

client/src/main/java/com/alibaba/nacos/client/logging/AbstractNacosLogging.java
client/src/main/resources/nacos-log4j2.xml
client/src/main/resources/nacos-logback.xml

Support for custom the log file path of Nacos client
Support for custom the log file path of Nacos client
Support for custom the log file path of Nacos client

Fixes #880

---

client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingService.java

change the isNotBlank to isBlank

---

core/src/main/java/com/alibaba/nacos/core/utils/InetUtils.java

surport hostname

---

CHANGELOG.md
console/src/main/resources/META-INF/nacos-default.properties
distribution/conf/application.properties
naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/DistroConsistencyServiceImpl.java
naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/raft/RaftCore.java
naming/src/main/java/com/alibaba/nacos/naming/core/Service.java
naming/src/main/java/com/alibaba/nacos/naming/healthcheck/ClientBeatCheckTask.java
naming/src/main/java/com/alibaba/nacos/naming/misc/GlobalConfig.java
naming/src/main/java/com/alibaba/nacos/naming/misc/HttpClient.java
naming/src/main/java/com/alibaba/nacos/naming/misc/SwitchDomain.java
naming/src/main/java/com/alibaba/nacos/naming/misc/UtilsAndCommons.java
naming/src/main/resources/application.properties
test/src/test/resources/application.properties

Feature naming group

---

client/src/main/resources/nacos-logback.xml

Fixes #925
Fixes #925
Fixes #925

Fixes #925

---

naming/src/main/java/com/alibaba/nacos/naming/misc/SwitchDomain.java

#745 Moidfy default server mode

#745 Modify default server mode

---

naming/src/main/java/com/alibaba/nacos/naming/controllers/ApiController.java
naming/src/main/java/com/alibaba/nacos/naming/core/Service.java
naming/src/main/java/com/alibaba/nacos/naming/core/ServiceManager.java
naming/src/main/java/com/alibaba/nacos/naming/web/FilterBase.java

Fix bug
#923 Add old client beat method

Hotfix client beat

---

config/src/main/java/com/alibaba/nacos/config/server/service/DiskUtil.java

Fixes #984
Fixes #984
Fixes #984

Fixes #984

---

client/pom.xml
client/src/main/java/com/alibaba/nacos/client/config/http/ServerHttpAgent.java
client/src/main/java/com/alibaba/nacos/client/utils/JSONUtils.java
config/pom.xml
config/src/main/java/com/alibaba/nacos/config/server/service/ConfigSubService.java
config/src/main/java/com/alibaba/nacos/config/server/utils/JSONUtils.java
pom.xml

remove lgpl dependency

---

client/pom.xml
client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java
client/src/main/java/com/alibaba/nacos/client/config/impl/ServerListManager.java
client/src/main/java/com/alibaba/nacos/client/naming/core/HostReactor.java
client/src/main/java/com/alibaba/nacos/client/naming/utils/IoUtils.java
config/pom.xml
config/src/main/java/com/alibaba/nacos/config/server/service/PersistService.java
config/src/main/java/com/alibaba/nacos/config/server/service/capacity/GroupCapacityPersistService.java
config/src/main/java/com/alibaba/nacos/config/server/service/capacity/TenantCapacityPersistService.java
naming/pom.xml
naming/src/main/java/com/alibaba/nacos/naming/boot/RunningConfig.java
naming/src/main/java/com/alibaba/nacos/naming/web/DistroFilter.java
pom.xml

Remove spotbugs-annotations dependency & Delete Findbugs SuppressFBWarnings
#981

Remove spotbugs-annotations dependency

---

core/src/main/java/com/alibaba/nacos/core/utils/PropertyUtil.java

Fixes #986
Fixes #986
Fixes #986

Fixes #986

---

naming/src/main/java/com/alibaba/nacos/naming/core/Cluster.java
naming/src/main/java/com/alibaba/nacos/naming/core/Service.java

#961 init cluster after instantiate cluster

---

README.md
naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/raft/RaftStore.java
naming/src/main/java/com/alibaba/nacos/naming/controllers/InstanceController.java
pom.xml

Hotfix recognize 080 data

---

client/src/main/java/com/alibaba/nacos/client/config/NacosConfigService.java
naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/TaskDispatcher.java

Fix test case error

---

README.md
console/src/main/java/com/alibaba/nacos/console/controller/NamespaceController.java

console 里的public首字母是大写的和命名空间里那个保留控件不一致

---

distribution/bin/startup.sh

#1069 Increase the URL length limit for temporary solution

---

api/src/main/java/com/alibaba/nacos/api/naming/listener/NamingEvent.java
client/src/main/java/com/alibaba/nacos/client/naming/core/EventDispatcher.java

New feature for NamingEvent to support  getGroupName and getClusters method

[#1075]  NamingEvent add getGroupName and getClusters method

---

naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/DataSyncer.java
naming/src/main/java/com/alibaba/nacos/naming/healthcheck/ClientBeatCheckTask.java
naming/src/main/java/com/alibaba/nacos/naming/misc/ServerStatusSynchronizer.java
naming/src/main/java/com/alibaba/nacos/naming/web/DistroFilter.java

Hotfix server list inconsistent

---

pom.xml
test/src/test/java/com/alibaba/nacos/test/naming/AutoDeregisterInstance_ITCase.java
test/src/test/java/com/alibaba/nacos/test/naming/RegisterInstance_ITCase.java
test/src/test/java/com/alibaba/nacos/test/naming/RestAPI_ITCase.java
test/src/test/java/com/alibaba/nacos/test/naming/SelectInstances_ITCase.java

collation and analysis of the ignore test cases
梳理nacos集测ignore用例

collation and analysis of the ignore test cases

---

naming/src/main/java/com/alibaba/nacos/naming/controllers/CatalogController.java
naming/src/main/java/com/alibaba/nacos/naming/controllers/ClusterController.java
naming/src/main/java/com/alibaba/nacos/naming/core/Cluster.java
naming/src/main/java/com/alibaba/nacos/naming/core/Service.java
naming/src/main/java/com/alibaba/nacos/naming/core/ServiceManager.java
naming/src/main/java/com/alibaba/nacos/naming/misc/UtilsAndCommons.java
naming/src/test/java/com/alibaba/nacos/naming/BaseTest.java
naming/src/test/java/com/alibaba/nacos/naming/controllers/CatalogControllerTest.java
naming/src/test/java/com/alibaba/nacos/naming/controllers/ClusterControllerTest.java
naming/src/test/java/com/alibaba/nacos/naming/controllers/InstanceControllerTest.java
naming/src/test/java/com/alibaba/nacos/naming/core/ClusterTest.java
naming/src/test/java/com/alibaba/nacos/naming/core/DomainTest.java
naming/src/test/java/com/alibaba/nacos/naming/core/ServiceManagerTest.java
naming/src/test/java/com/alibaba/nacos/naming/core/ServiceTest.java
naming/src/test/java/com/alibaba/nacos/naming/misc/UtilsAndCommonsTest.java

Support #1150 
1. 修正服务和集群之间的关系(Correct the relationship between the service and cluster)
2. 创建集群时必须提供名字和所属服务(The name and the service are required to create a cluster)
3. 修正UtilsAndCommons.shakeUp的注释(Correct the comments for UtilsAndCommons.shakeUp)

[ISSUE #1150] Correct the Relationship between Services and Clusters

---

client/src/test/java/com/alibaba/nacos/client/StringUtilsTest.java

I've analysed your codebase and noticed that com.alibaba.nacos.client.utils.StringUtils is not fully tested.
I've written some tests for the methods in this class with the help of [Diffblue Cover](https://www.diffblue.com/opensource).
Hopefully, these tests will help you detect any regressions caused by future code changes. If you would find it useful to have additional tests written for this repository, I would be more than happy to look at other classes that you consider important.

Add unit tests for com.alibaba.nacos.client.utils.StringUtils

---

naming/src/main/java/com/alibaba/nacos/naming/core/Cluster.java
naming/src/test/java/com/alibaba/nacos/naming/core/ClusterTest.java

Support #1107 
Quick fixing for the cluster deserialization issue

[ISSUE #1107] Quick fixing for the cluster deserialization issue

---

naming/src/test/java/com/alibaba/nacos/naming/core/DomainsManagerTest.java
naming/src/test/java/com/alibaba/nacos/naming/raft/RaftStoreTest.java

[ISSUE #1227] DomainsManagerTest and RaftStoreTest Don't Work

---

console/src/main/resources/static/console-fe/src/utils/validateContent.js

modify the regular expression of properties validation

modify the regular expression of properties validation

---

naming/src/main/java/com/alibaba/nacos/naming/controllers/CatalogController.java

Close #1319

---

naming/src/main/java/com/alibaba/nacos/naming/push/PushService.java

 close stream safety & format code

---

api/src/main/java/com/alibaba/nacos/api/config/annotation/NacosConfigurationProperties.java

modify @NacosConfigurationProperties to support yaml style config

feat(client): @NacosConfigurationProperties support yaml style config

---

core/src/main/java/com/alibaba/nacos/core/utils/SystemUtils.java

fix: #1260

---

pom.xml

Fix config error

---

config/src/main/java/com/alibaba/nacos/config/server/service/DynamicDataSource.java
config/src/main/java/com/alibaba/nacos/config/server/service/LocalDataSourceServiceImpl.java

Avoid accessing static variables or static methods of this class through object references of a class. It increases the cost of compiler parsing and can be accessed directly by class name.
XXXXX
XX
XXXX

Use static methods maybe better

---

api/src/main/java/com/alibaba/nacos/api/naming/pojo/AbstractHealthChecker.java
client/src/main/java/com/alibaba/nacos/client/config/http/ServerHttpAgent.java
client/src/main/java/com/alibaba/nacos/client/config/impl/CacheData.java
client/src/main/java/com/alibaba/nacos/client/config/impl/TimerService.java
client/src/main/java/com/alibaba/nacos/client/identify/CredentialService.java
client/src/main/java/com/alibaba/nacos/client/identify/Credentials.java
client/src/main/java/com/alibaba/nacos/client/naming/backups/FailoverReactor.java
client/src/main/java/com/alibaba/nacos/client/naming/utils/GenericPoller.java
client/src/main/java/com/alibaba/nacos/client/naming/utils/JvmRandom.java
client/src/main/java/com/alibaba/nacos/client/naming/utils/ThreadLocalRandom.java
config/src/main/java/com/alibaba/nacos/config/server/manager/TaskManager.java
config/src/main/java/com/alibaba/nacos/config/server/model/ConfigInfoBase.java
config/src/main/java/com/alibaba/nacos/config/server/model/app/GroupKey.java
config/src/main/java/com/alibaba/nacos/config/server/service/DynamicDataSource.java
config/src/main/java/com/alibaba/nacos/config/server/service/LongPollingService.java
config/src/main/java/com/alibaba/nacos/config/server/service/PersistService.java
config/src/main/java/com/alibaba/nacos/config/server/service/notify/AsyncNotifyService.java
config/src/main/java/com/alibaba/nacos/config/server/utils/SimpleFlowData.java
config/src/main/java/com/alibaba/nacos/config/server/utils/SimpleIPFlowData.java
naming/src/main/java/com/alibaba/nacos/naming/core/Service.java
naming/src/main/java/com/alibaba/nacos/naming/healthcheck/RsInfo.java
naming/src/main/java/com/alibaba/nacos/naming/web/OverrideParameterRequestWrapper.java

All overriding methods must be preceded by @Override annotations.
XX
XXXX

All overriding methods must be preceded by @Override annotations.

---

.travis.yml
api/src/main/java/com/alibaba/nacos/api/PropertyKeyConst.java
api/src/main/java/com/alibaba/nacos/api/annotation/NacosProperties.java
api/src/main/java/com/alibaba/nacos/api/config/ConfigType.java
api/src/main/java/com/alibaba/nacos/api/config/annotation/NacosConfigListener.java
api/src/main/java/com/alibaba/nacos/api/config/annotation/NacosConfigurationProperties.java
client/src/main/java/com/alibaba/nacos/client/config/http/ServerHttpAgent.java
client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java
test/src/test/java/com/alibaba/nacos/test/config/ConfigLongPoll_ITCase.java

support more config type setting and fix travis-ci yaml bug
Fixed some problems with configuration parameter Settings in PR #1341 
XXXX

Support more config type setting and fix travis-ci yaml bug

---

naming/src/main/java/com/alibaba/nacos/naming/controllers/ServiceController.java

Add paging for subscription service queries
add page info

add page info to subscriber service

---

client/src/main/java/com/alibaba/nacos/client/identify/CredentialListener.java
client/src/main/java/com/alibaba/nacos/client/identify/SpasCredential.java
client/src/main/java/com/alibaba/nacos/client/naming/utils/CollectionUtils.java
client/src/main/java/com/alibaba/nacos/client/naming/utils/InitUtils.java
client/src/main/java/com/alibaba/nacos/client/utils/TemplateUtils.java
config/src/main/java/com/alibaba/nacos/config/server/service/PersistService.java
config/src/main/java/com/alibaba/nacos/config/server/utils/event/EventDispatcher.java
console/src/main/java/com/alibaba/nacos/console/model/NamespaceAllInfo.java
naming/src/main/java/com/alibaba/nacos/naming/push/ClientInfo.java
test/src/test/java/com/alibaba/nacos/test/naming/RandomUtils.java

Signed-off-by: slievrly <slievrly@163.com>
optimize modifier access 
optimize modifier access 
ci

optimize modifier access

---

config/src/test/java/com/alibaba/nacos/config/server/service/AggrWhitelistTest.java
config/src/test/java/com/alibaba/nacos/config/server/utils/SimpleReadWriteLockTest.java
test/src/test/java/com/alibaba/nacos/test/config/ConfigAPI_ITCase.java
test/src/test/java/com/alibaba/nacos/test/naming/SelectOneHealthyInstance_ITCase.java
test/src/test/java/com/alibaba/nacos/test/naming/SubscribeCluster_ITCase.java
test/src/test/java/com/alibaba/nacos/test/naming/Unsubscribe_ITCase.java

Signed-off-by: slievrly <slievrly@163.com>
optimize junit
optimize junit
ci

optimize junit

---

api/src/main/java/com/alibaba/nacos/api/annotation/NacosProperties.java

add enableRemoteSyncConfig properties setting

feat(nacos-api): add enableRemoteSyncConfig properties setting

---

api/src/main/java/com/alibaba/nacos/api/config/ConfigFactory.java
api/src/main/java/com/alibaba/nacos/api/exception/NacosException.java
api/src/main/java/com/alibaba/nacos/api/naming/NamingFactory.java
api/src/main/java/com/alibaba/nacos/api/naming/NamingMaintainFactory.java
client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java
naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/raft/RaftConsistencyServiceImpl.java

【issue】#1278

---

client/src/main/java/com/alibaba/nacos/client/config/http/ServerHttpAgent.java
client/src/main/java/com/alibaba/nacos/client/config/impl/ServerListManager.java
client/src/main/java/com/alibaba/nacos/client/identify/Constants.java
client/src/main/java/com/alibaba/nacos/client/naming/net/NamingProxy.java
client/src/main/java/com/alibaba/nacos/client/naming/utils/UtilAndComs.java

config 和 discovery 的 server-addr 只支持 ip:port 形式，如果要使用 https 需要额外指定属性。现在改为直接支持 http(s)://ip:port，也兼容原有的 ip:port 格式
com.alibaba.nacos.client.config.impl.ServerListManager
com.alibaba.nacos.client.naming.net.NamingProxy#callServer
spring cloud alibaba discovery 在解析 server-addr 时，会去判断是否含有 "/"，对应的逻辑也需要修改

HTTPS支持 #1344

---

api/src/main/java/com/alibaba/nacos/api/naming/NamingService.java
client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingService.java

【issue】 #1425

---

naming/src/main/java/com/alibaba/nacos/naming/pojo/Subscriber.java

subscriber's collective data de-duplication
Collective data de-duplication

Collective data de-duplication

---

client/src/main/java/com/alibaba/nacos/client/config/http/ServerHttpAgent.java
client/src/main/java/com/alibaba/nacos/client/utils/JSONUtils.java
config/src/main/java/com/alibaba/nacos/config/server/service/ConfigSubService.java
config/src/main/java/com/alibaba/nacos/config/server/utils/JSONUtils.java

#1442 
Simplify the code
updating `deserializeObject` and caller.

[ISSUE #1442] Fix JSONUtils#deserializeObject method.

---

api/src/main/java/com/alibaba/nacos/api/config/annotation/NacosConfigurationProperties.java

@NacosConfigurationProperties support prefix setting

[FEATURE] @NacosConfigurationProperties support prefix setting

---

client/src/main/java/com/alibaba/nacos/client/naming/net/NamingProxy.java

useless import

---

client/src/main/java/com/alibaba/nacos/client/config/utils/MD5.java

new HashMap<Character, Integer>(16); 负载因子是0.75,digits实际大小是16会扩容一次。
XXXXX
XX
new HashMap<Character, Integer>(16); 负载因子是0.75,digits实际大小是16会扩容一次。

构建rDigits改成google的guava

---

.travis.yml
client/src/main/java/com/alibaba/nacos/client/naming/net/NamingProxy.java
test/src/test/java/com/alibaba/nacos/test/naming/NamingMaintainService_ITCase.java

Fix issue 1455

---

style/codeStyle.md

update code style java guideline link
*
*

update codestyle java guideline link

---

client/src/main/java/com/alibaba/nacos/client/config/impl/ServerListManager.java
test/src/test/java/com/alibaba/nacos/test/naming/Subscribe_ITCase.java

https://github.com/alibaba/nacos/issues/1490
XXXXX
XX
XXXX

fix unuseless import

---

api/src/main/java/com/alibaba/nacos/api/config/annotation/NacosConfigurationProperties.java

Restore the NacosConfigurationProperties yaml() method to be compatible with older clients

Fix @NacosConfigurationProperties to support old version

---

naming/src/main/java/com/alibaba/nacos/naming/controllers/HealthController.java
naming/src/main/java/com/alibaba/nacos/naming/core/Service.java
naming/src/main/java/com/alibaba/nacos/naming/core/ServiceManager.java
naming/src/main/java/com/alibaba/nacos/naming/healthcheck/ClientBeatCheckTask.java
naming/src/main/java/com/alibaba/nacos/naming/healthcheck/ClientBeatProcessor.java
naming/src/main/java/com/alibaba/nacos/naming/healthcheck/HealthCheckCommon.java
naming/src/main/java/com/alibaba/nacos/naming/push/PushService.java
naming/src/main/java/com/alibaba/nacos/naming/push/ServiceChangeEvent.java

support ServiceChangeEvent with naming module

---

console/src/main/resources/static/console-fe/src/pages/ConfigurationManagement/ConfigEditor/NewConfigEditor.js

Fix closes #1521

---

api/src/main/java/com/alibaba/nacos/api/annotation/NacosProperties.java

fix(api): fix issue #1500

---

config/src/main/java/com/alibaba/nacos/config/server/service/BasicDataSourceServiceImpl.java

fix issue #1492 
if user want to use different database setup password，just follow like this
```properties
db.url.0=jdbc:mysql://11.162.196.16:3306/nacos_devtest?
db.user.0=user_0
db.password.0=password_0
db.url.1=jdbc:mysql://11.162.196.16:3306/nacos_devtest?
db.user.1=user_1
db.password.1=password_1
```
But if it is multiple db account password is the same，follow before setting
```properties
db.url.0=jdbc:mysql://11.162.196.16:3306/nacos_devtest?
db.url.1=jdbc:mysql://11.162.196.16:3306/nacos_devtest?
db.user=user_1
db.password=password_1
```

feat(config): support different db name and password

---

naming/src/main/java/com/alibaba/nacos/naming/cluster/ServerListManager.java

1. distro 使用本地时间记录心跳
2. 修正 cleanInvalidServers 逻辑

distro use local time to record heartbeat

---

naming/src/main/java/com/alibaba/nacos/naming/web/AuthFilter.java
naming/src/main/java/com/alibaba/nacos/naming/web/NamingConfig.java
test/src/test/java/com/alibaba/nacos/test/naming/RestAPI_ITCase.java

Fix namespace vulnerability

---

client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingService.java
client/src/test/java/com/alibaba/nacos/client/AppTest.java
cmdb/src/main/java/com/alibaba/nacos/cmdb/controllers/OperationController.java
common/src/main/java/com/alibaba/nacos/common/util/VersionUtils.java
common/src/test/java/com/alibaba/nacos/common/AppTest.java
config/src/main/java/com/alibaba/nacos/config/server/aspect/RequestLogAspect.java
config/src/main/java/com/alibaba/nacos/config/server/controller/CapacityController.java
config/src/main/java/com/alibaba/nacos/config/server/controller/HealthController.java
config/src/main/java/com/alibaba/nacos/config/server/controller/ListenerController.java
config/src/main/java/com/alibaba/nacos/config/server/enums/FileTypeEnum.java
config/src/main/java/com/alibaba/nacos/config/server/model/SubscriberStatus.java
config/src/main/java/com/alibaba/nacos/config/server/result/code/ResultCodeEnum.java
config/src/main/java/com/alibaba/nacos/config/server/service/PersistService.java
config/src/main/java/com/alibaba/nacos/config/server/service/ServerListService.java
config/src/main/java/com/alibaba/nacos/config/server/utils/JSONUtils.java
config/src/test/java/com/alibaba/nacos/config/server/service/AggrWhitelistTest.java
config/src/test/java/com/alibaba/nacos/config/server/utils/SimpleReadWriteLockTest.java
config/src/test/java/com/alibaba/nacos/config/server/utils/event/EventDispatcherTest.java
core/src/main/java/com/alibaba/nacos/core/utils/InetUtils.java
example/src/test/java/com/alibaba/nacos/example/AppTest.java
naming/src/main/java/com/alibaba/nacos/naming/acl/AuthInfo.java
naming/src/main/java/com/alibaba/nacos/naming/cluster/transport/FastJsonSerializer.java
naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/raft/RaftStore.java
naming/src/main/java/com/alibaba/nacos/naming/healthcheck/ClientBeatCheckTask.java
naming/src/test/java/com/alibaba/nacos/naming/healthcheck/ClientBeatCheckTaskTest.java
test/src/test/java/com/alibaba/nacos/test/AppTest.java
test/src/test/java/com/alibaba/nacos/test/config/ConfigBeta_ITCase.java

Delete useless import
Format change is obviously formatted incorrectly
XX
XXXX

format code

---

naming/src/main/java/com/alibaba/nacos/naming/cluster/ServerListManager.java

FIX CI UN Build

---

naming/src/main/java/com/alibaba/nacos/naming/controllers/ServiceController.java

issue https://github.com/alibaba/nacos/issues/1652#issue-477144565
set default value for protectThreshold to 0,  as same as Open API Guide: [https://nacos.io/en-us/docs/open-api.html#Update ](url)
set default value for protectThreshold to 0
XXXX

[ISSUE #1652] Update service description error in Open API Guide

---

naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/DataSyncer.java

fix #1665  
remove syncTask if server is no longer healthy 
XXXX
* [ √] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ √] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ √] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* …

ISSUE #1665

---

console/src/main/resources/application.properties

bug fix https://github.com/alibaba/nacos/issues/1841

bug fix 1841

---

naming/src/main/java/com/alibaba/nacos/naming/core/ServiceManager.java

Fix issue #1916 
Make sure an empty service is already created and inited before ServiceManager#createServiceIfAbsent return.
Run bash command below:
```bash
for i in `seq 1 100`; do curl -X POST "http://xxx:8848/nacos/v1/ns/instance?port=8848&healthy=true&ip=11.11.11.123$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 7)&weight=1.0&serviceName=nacos.test.888$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 7)&encoding=GBK&ephemeral=false"&; done
```
All requests return without error message.
***

[ISSUE #1916] Fix returning ErrCode:400 when register instances concurrently to non-existent services

---

naming/src/main/java/com/alibaba/nacos/naming/core/SubscribeManager.java

fix the return error when the synchronization loop got the subscriber.
fix the return error when the synchronization loop got the subscriber.

fix the getting subscribers error

---

api/src/main/java/com/alibaba/nacos/api/common/Constants.java
api/src/main/java/com/alibaba/nacos/api/naming/PreservedMetadataKeys.java
api/src/main/java/com/alibaba/nacos/api/naming/pojo/Instance.java
naming/src/main/java/com/alibaba/nacos/naming/controllers/InstanceController.java
naming/src/main/java/com/alibaba/nacos/naming/core/Instance.java
naming/src/main/java/com/alibaba/nacos/naming/core/ServiceManager.java
naming/src/test/java/com/alibaba/nacos/naming/controllers/InstanceControllerTest.java
naming/src/test/java/com/alibaba/nacos/naming/core/ServiceManagerTest.java

Signed-off-by: vettal-wu <vettal_wu@163.com>
Generate a unique instance index when instance register. The instance index can be used for the generation of snowflake algorithm, or other scenario.
See issue: #1864
* Generate a unique instance index when register

[ISSUE #1864] Support generate instance id for both simple and snowflake mode 

---

naming/src/main/java/com/alibaba/nacos/naming/controllers/InstanceController.java
naming/src/main/java/com/alibaba/nacos/naming/push/PushService.java
naming/src/test/java/com/alibaba/nacos/naming/push/PushClientTest.java

Hotfix inet addr null

---

client/src/main/java/com/alibaba/nacos/client/naming/net/NamingProxy.java

Change to throw NacosException to make client handle the right Exception case
Change the Exception type 
XXXX

[#2006] Change to throw NacosException 

---

console/src/main/java/com/alibaba/nacos/Nacos.java
naming/src/main/java/com/alibaba/nacos/naming/controllers/InstanceController.java
test/src/test/java/com/alibaba/nacos/test/naming/MultiTenant_InstanceAPI_ITCase.java

https://github.com/alibaba/nacos/issues/1957
应当支持可以更新单个属性的API
add a patch api for update instance property

issues:调用修改实例接口,未传的参数值会被清空

---

common/src/main/java/com/alibaba/nacos/common/utils/IoUtils.java
config/src/main/java/com/alibaba/nacos/config/server/service/AggrWhitelist.java
config/src/main/java/com/alibaba/nacos/config/server/service/DiskUtil.java
config/src/main/java/com/alibaba/nacos/config/server/service/ServerListService.java
config/src/main/java/com/alibaba/nacos/config/server/service/SwitchService.java
config/src/main/java/com/alibaba/nacos/config/server/service/dump/DumpService.java
config/src/main/java/com/alibaba/nacos/config/server/service/notify/NotifyService.java
core/src/main/java/com/alibaba/nacos/core/utils/PropertyUtil.java
naming/src/main/java/com/alibaba/nacos/naming/controllers/RaftController.java
naming/src/main/java/com/alibaba/nacos/naming/controllers/ServiceController.java
naming/src/main/java/com/alibaba/nacos/naming/misc/HttpClient.java

[Issues 2025] Common classes in Nacos should be unified

---

client/src/main/java/com/alibaba/nacos/client/config/NacosConfigService.java
client/src/main/java/com/alibaba/nacos/client/config/impl/ServerListManager.java
client/src/main/java/com/alibaba/nacos/client/identify/STSConfig.java
client/src/main/java/com/alibaba/nacos/client/naming/utils/InitUtils.java
config/src/main/java/com/alibaba/nacos/config/server/service/SwitchService.java
config/src/main/java/com/alibaba/nacos/config/server/utils/PropertyUtil.java
core/src/main/java/com/alibaba/nacos/core/utils/InetUtils.java
naming/src/main/java/com/alibaba/nacos/naming/controllers/ServiceController.java

optimize: the Boolean.parseBoolean(String s) method should be used when converting a String to a Boolean type .  fixes #2084 
1.client/src/main/java/com/alibaba/nacos/client/config/NacosConfigService.java
2.client/src/main/java/com/alibaba/nacos/client/config/impl/ServerListManager.java
3.client/src/main/java/com/alibaba/nacos/client/identify/STSConfig.java
4.client/src/main/java/com/alibaba/nacos/client/naming/utils/InitUtils.java
5.config/src/main/java/com/alibaba/nacos/config/server/service/SwitchService.java
6.config/src/main/java/com/alibaba/nacos/config/server/utils/PropertyUtil.java
7.core/src/main/java/com/alibaba/nacos/core/utils/InetUtils.java
8.naming/src/main/java/com/alibaba/nacos/naming/controllers/ServiceCo …

optimize: the Boolean.parseBoolean(String s) method should be used when converting a String to a Boolean type

---

client/src/main/java/com/alibaba/nacos/client/utils/ParamUtil.java

due to server context path change, client need to change context path too.
add client context path config

add client context path config

---

console/src/main/java/com/alibaba/nacos/console/config/CorsConfig.java
console/src/main/java/com/alibaba/nacos/console/config/WebSecurityConfig.java

add cors support
issue #1983
add file    com.alibaba.nacos.console.config.CorsConfig.java
modify file     com.alibaba.nacos.console.config.WebSecurityConfig.java

add nacos console cors

---

console/src/main/java/com/alibaba/nacos/console/utils/JwtTokenUtils.java

issue fix #2093

---

naming/src/main/java/com/alibaba/nacos/naming/core/SubscribeManager.java
naming/src/main/java/com/alibaba/nacos/naming/push/PushService.java
naming/src/test/java/com/alibaba/nacos/naming/core/PushServiceTest.java
naming/src/test/java/com/alibaba/nacos/naming/core/SubscribeManagerTest.java

optimize subscribers list page ,support fuzzy query
naming/src/main/java/com/alibaba/nacos/naming/core/SubscribeManager.java
naming/src/main/java/com/alibaba/nacos/naming/push/PushService.java
naming/src/test/java/com/alibaba/nacos/naming/core/SubscribeManagerTest.java

[ISSUE #2148] subscribers list page support fuzzy query

---

console/src/main/resources/static/console-fe/src/pages/ConfigurationManagement/ConfigurationManagement/index.scss

fix #2092 pageSize change

---

config/src/main/java/com/alibaba/nacos/config/server/service/PersistService.java
console/src/main/java/com/alibaba/nacos/console/controller/NamespaceController.java

Remove duplicate methods

---

config/src/main/java/com/alibaba/nacos/config/server/service/DiskUtil.java

Fix issue #1781
use `File.separator` instead of `/`
N/A

[ISSUE  #1781]  Fix hard-coded file separator

---

config/src/main/java/com/alibaba/nacos/config/server/utils/PaginationHelper.java

fix ISSUE [#2158](https://github.com/alibaba/nacos/issues/2158) replace null return value

replace null return value

---

naming/src/main/java/com/alibaba/nacos/naming/web/DistroFilter.java

Hotfix 2285

---

console/src/main/resources/static/console-fe/src/pages/ConfigurationManagement/ConfigurationManagement/ConfigurationManagement.js

- configuration management
-
-

fix: closes #2457

---

console/src/main/resources/static/console-fe/src/globalLib.js
console/src/main/resources/static/console-fe/src/utils/request.js

fix: closes #2443

---

client/src/main/java/com/alibaba/nacos/client/naming/core/HostReactor.java

fix #1674 task abort because of exception
`executor.schedule(this, delay, TimeUnit.MILLISECONDS)`  move to finally execute
XXXX

[ISSUE #1674] fix task abort because of exception

---

naming/src/main/java/com/alibaba/nacos/naming/misc/HttpClient.java
naming/src/main/java/com/alibaba/nacos/naming/web/DistroFilter.java

Hotfix client beat lost in redirect

---

client/src/main/java/com/alibaba/nacos/client/naming/net/NamingProxy.java

Change NamingProxy#reqAPI method throw exception log describe

---

console/src/main/resources/static/console-fe/.gitignore
console/src/main/resources/static/console-fe/src/utils/validateContent.js

Nacos config properties type should allow empty line.
Fix the properties format check logic to allow empty line.
Just one line...

Fix #2627 nacos 控制台发布配置BUG

---

core/src/main/java/com/alibaba/nacos/core/distributed/ProtocolManager.java

ProtocolManager class's getCpProtocol()/getApProtocol() method ' codes can be optimized.
XX
XXXX

[#2761]ProtocolManager class's getCpProtocol()/getApProtocol() method ' codes can be optimized.

---

core/src/main/java/com/alibaba/nacos/core/cluster/MemberUtils.java

#2765
Optimize MemberUtils class's kRandom method
XXXX
*  [x] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.

[ISSUE #2765]Optimize MemberUtils class's kRandom method

---

config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigController.java
config/src/main/java/com/alibaba/nacos/config/server/service/PersistService.java
config/src/main/java/com/alibaba/nacos/config/server/utils/ParamUtils.java

add tenant part legality verification.
XX
XXXX

[#2738]add tenant legality verification.

---

config/src/main/java/com/alibaba/nacos/config/server/service/dump/DumpService.java
core/src/main/java/com/alibaba/nacos/core/distributed/raft/utils/JRaftOps.java

refactor: jraft node removal logic optimization

---

client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java

`ClientWorker` `LongPollingRunnable` task 
When the acquired changedGroupKeys is empty will always output the log, I feel that the output will be better when it is not empty.
XX
XXXX

Modify log output

---

client/src/main/java/com/alibaba/nacos/client/config/NacosConfigService.java
client/src/main/java/com/alibaba/nacos/client/config/http/MetricsHttpAgent.java
client/src/main/java/com/alibaba/nacos/client/config/impl/AbstractConfigChangeParser.java

remove useless code in NacosConfigService.java、MetricsHttpAgent.java、AbstractConfigChangeParser.java

remove useless code

---

config/src/main/java/com/alibaba/nacos/config/server/service/repository/EmbeddedStoragePersistServiceImpl.java
config/src/main/java/com/alibaba/nacos/config/server/service/repository/ExternalStoragePersistServiceImpl.java

fix #2657
add `type` in sql using ConfigInfoWrapper

[ISSUE #2657]SQLException when config server quickstart

---

common/src/main/java/com/alibaba/nacos/common/utils/LoggerUtils.java
config/src/main/java/com/alibaba/nacos/config/server/model/event/RaftDBErrorEvent.java
config/src/main/java/com/alibaba/nacos/config/server/service/repository/DistributedDatabaseOperateImpl.java
core/src/main/java/com/alibaba/nacos/core/cluster/ServerMemberManager.java
core/src/main/java/com/alibaba/nacos/core/notify/DefaultPublisher.java
core/src/main/java/com/alibaba/nacos/core/notify/NotifyCenter.java
test/src/test/java/com/alibaba/nacos/test/core/notify/NotifyCenter_ITCase.java

fix: fix the class cast problem

---

core/src/main/java/com/alibaba/nacos/core/notify/DefaultPublisher.java
core/src/main/java/com/alibaba/nacos/core/notify/NotifyCenter.java
test/src/test/java/com/alibaba/nacos/test/core/notify/NotifyCenter_ITCase.java

fix notify-center publish event may cause class-cast-exception
XX
XXXX

Hotfix notify

---

naming/src/main/java/com/alibaba/nacos/naming/core/ServiceManager.java

code optimize. Reduce circulation
Reduce circulation
XXXX

code optimize

---

core/src/main/java/com/alibaba/nacos/core/cluster/MemberUtils.java
core/src/main/java/com/alibaba/nacos/core/cluster/ServerMemberManager.java
naming/src/main/java/com/alibaba/nacos/naming/core/DistroMapper.java

[#2933] adjust where version information is inserted

---

distribution/LICENSE-BIN
pom.xml
test/pom.xml
test/src/test/java/com/alibaba/nacos/test/BaseTest.java
test/src/test/java/com/alibaba/nacos/test/common/HttpUtils_ITCase.java
test/src/test/java/com/alibaba/nacos/test/config/ConfigAPI_ITCase.java
test/src/test/java/com/alibaba/nacos/test/config/ConfigBeta_ITCase.java
test/src/test/java/com/alibaba/nacos/test/config/ConfigExportAndImportAPI_ITCase.java
test/src/test/java/com/alibaba/nacos/test/core/auth/AuthBase.java
test/src/test/java/com/alibaba/nacos/test/core/auth/Permission_ITCase.java
test/src/test/java/com/alibaba/nacos/test/core/auth/Role_ITCase.java
test/src/test/java/com/alibaba/nacos/test/core/auth/User_ITCase.java
test/src/test/java/com/alibaba/nacos/test/naming/CPInstancesAPI_ITCase.java
test/src/test/java/com/alibaba/nacos/test/naming/Cmdb_ITCase.java
test/src/test/java/com/alibaba/nacos/test/naming/MultiTenant_InstanceAPI_ITCase.java
test/src/test/java/com/alibaba/nacos/test/naming/RestAPI_ITCase.java
test/src/test/java/com/alibaba/nacos/test/naming/Subscribe_ITCase.java

For #2842 .
Replace all fastjson dependency with jackson.
- Replace fastjson with jackson for nacos-test
- Remove dependency and LICENSE of fastjson

[ISSUE #2842] Replace all fastjson with jackson

---

config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigController.java
config/src/main/java/com/alibaba/nacos/config/server/model/ConfigHistoryInfo.java
config/src/main/java/com/alibaba/nacos/config/server/model/ConfigInfoAggr.java
config/src/main/java/com/alibaba/nacos/config/server/model/ConfigInfoBase.java
config/src/main/java/com/alibaba/nacos/config/server/model/GroupInfo.java
config/src/main/java/com/alibaba/nacos/config/server/model/capacity/Capacity.java
config/src/main/java/com/alibaba/nacos/config/server/service/notify/AsyncNotifyService.java
config/src/main/java/com/alibaba/nacos/config/server/service/repository/DistributedDatabaseOperateImpl.java
config/src/main/java/com/alibaba/nacos/config/server/service/repository/EmbeddedStoragePersistServiceImpl.java
config/src/test/java/com/alibaba/nacos/config/server/model/ConfigInfoTest.java
core/src/main/java/com/alibaba/nacos/core/distributed/id/IdGeneratorManager.java
core/src/main/java/com/alibaba/nacos/core/distributed/id/SnowFlowerIdGenerator.java
test/src/test/java/com/alibaba/nacos/test/core/SnowFlowerIdGenerator_ITCase.java

Fix front-end Long precision loss problem
XX
XXXX

Hotfix config clone

---

naming/src/main/java/com/alibaba/nacos/naming/cluster/ServerListManager.java

Fix 1.3 version don't report server status to lower version.
XX

Fix 1.3 version don't report server status to lower version.

---

client/src/test/java/com/alibaba/nacos/client/ConfigTest.java
common/src/main/java/com/alibaba/nacos/common/utils/MapUtils.java
config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigController.java
config/src/main/java/com/alibaba/nacos/config/server/model/event/ConfigDataChangeEvent.java
config/src/main/java/com/alibaba/nacos/config/server/model/event/ConfigDumpEvent.java
config/src/main/java/com/alibaba/nacos/config/server/model/event/LocalDataChangeEvent.java
config/src/main/java/com/alibaba/nacos/config/server/service/datasource/DataSourceService.java
config/src/main/java/com/alibaba/nacos/config/server/service/datasource/DynamicDataSource.java
config/src/main/java/com/alibaba/nacos/config/server/service/datasource/ExternalDataSourceServiceImpl.java
config/src/main/java/com/alibaba/nacos/config/server/service/datasource/LocalDataSourceServiceImpl.java
config/src/main/java/com/alibaba/nacos/config/server/service/dump/DumpConfigHandler.java
config/src/main/java/com/alibaba/nacos/config/server/service/repository/RowMapperManager.java
config/src/main/java/com/alibaba/nacos/config/server/utils/DiskUtil.java
core/src/main/java/com/alibaba/nacos/core/distributed/raft/processor/AbstractProcessor.java
core/src/main/java/com/alibaba/nacos/core/distributed/raft/processor/NacosGetRequestProcessor.java
core/src/main/java/com/alibaba/nacos/core/distributed/raft/utils/JRaftOps.java

Configure publish log print recovery
XX
XXXX

HOTFIX： add config publish log

---

config/src/main/java/com/alibaba/nacos/config/server/service/dump/EmbeddedDumpService.java
config/src/main/java/com/alibaba/nacos/config/server/service/merge/MergeDatumService.java

[#2985] fix task executable judgment logic problems

---

console/src/main/java/com/alibaba/nacos/console/security/nacos/JwtTokenManager.java
console/src/main/java/com/alibaba/nacos/console/utils/JwtTokenUtils.java

Resolved [#2956 ](https://github.com/alibaba/nacos/issues/2956)
XX
XXXX

[ISSUE #2956] simplify code

---

.travis.yml
common/src/main/java/com/alibaba/nacos/common/utils/CollectionUtils.java
config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigController.java
config/src/main/java/com/alibaba/nacos/config/server/service/ConfigChangePublisher.java
config/src/main/java/com/alibaba/nacos/config/server/service/LongPollingService.java
config/src/main/java/com/alibaba/nacos/config/server/service/repository/EmbeddedStoragePersistServiceImpl.java
config/src/main/java/com/alibaba/nacos/config/server/service/repository/ExternalStoragePersistServiceImpl.java
config/src/test/java/com/alibaba/nacos/config/server/service/ConfigChangePublisherTest.java
pom.xml
test/src/test/java/com/alibaba/nacos/test/config/ConfigAPI_CITCase.java
test/src/test/java/com/alibaba/nacos/test/config/ConfigBeta_CITCase.java
test/src/test/java/com/alibaba/nacos/test/config/ConfigExportAndImportAPI_CITCase.java
test/src/test/java/com/alibaba/nacos/test/config/ConfigLongPollReturnChanges_CITCase.java
test/src/test/java/com/alibaba/nacos/test/config/ConfigLongPoll_CITCase.java
test/src/test/java/com/alibaba/nacos/test/config/EmbeddedStorageContextUtils_CITCase.java

[#ISSUE 2994] Perf config notify

---

address/src/main/resources/META-INF/logback/nacos-included.xml
config/src/main/resources/META-INF/logback/config-included.xml
core/src/main/resources/META-INF/logback/nacos.xml
distribution/conf/nacos-logback.xml
naming/src/main/resources/META-INF/logback/naming-included.xml

"MaxHistory" naming rule is not nacos default style
MaxHistory字段名称和Nacos默认的命名风格不统一
address/src/main/resources/META-INF/logback/nacos-included.xml
config/src/main/resources/META-INF/logback/config-included.xml
core/src/main/resources/META-INF/logback/nacos.xml
distribution/conf/nacos-logback.xml
naming/src/main/resources/META-INF/logback/naming-included.xml

FIX ISSUE #3007 : MaxHistory字段名称和Nacos默认的命名风格不统一

---

naming/src/main/java/com/alibaba/nacos/naming/healthcheck/MysqlHealthCheckProcessor.java

Use DriverManager instead of MysqlDataSource to get the connection
XX
XXXX

Fix #1865 use DriverManager instead of MysqlDataSource to get the connection

---

client/src/main/java/com/alibaba/nacos/client/naming/net/NamingProxy.java

fix https://github.com/alibaba/nacos/issues/3019
XX
XXXX

a power of two size for hashmap

---

distribution/conf/nacos-mysql.sql

Modify the initial script of MySQL. Modify the length of resource field in permissions table to 255
bug fix #3016
XXXXX
XX
XXXX

修针对mysql5.6版本使用innodb存储引擎，permissions表resouce字段长度过长，无法创建索引，建表出错，修改bug #3016

---

client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingService.java
client/src/main/java/com/alibaba/nacos/client/naming/beat/BeatReactor.java
client/src/main/java/com/alibaba/nacos/client/naming/core/HostReactor.java
client/src/test/java/com/alibaba/nacos/client/naming/core/HostReactorTest.java

[ISSUE #2800] update beatinfo when received instance modify info

---

.github/stale.yml

Add a robot to clean expired issue and PR automatically.

Add issue robot

---

.github/stale.yml

Do not close issue which lable is kind/notice 

Ignore kind/notice label for issue robot

---

.github/stale.yml

Ignore lable `kind/feature` for issue robot

Ignore kind/feature label for issue robot

---

naming/src/main/java/com/alibaba/nacos/naming/controllers/ServiceController.java
naming/src/main/java/com/alibaba/nacos/naming/core/ServiceManager.java

Method name optimization

---

address/pom.xml

```text
address 
- naming
- api
- commons-lang3
```
address does not need to be directly dependent commons-lang3
XX
XXXX

Optimization dependency

---

style/NacoStyleForIdea.xml
style/NacosCheckStyle.xml
style/codeStyle.md

For #2992.
Add code style file version 1 for idea IDE.
- Add code style file for Idea
- Add checkstyle file for option
- Update codestyle.md description

[ISSUE #2992] Add code style file for Idea and checkstyle file for option

---

common/src/main/java/com/alibaba/nacos/common/executor/ExecutorFactory.java
consistency/src/main/java/com/alibaba/nacos/consistency/ProtocolMetaData.java
core/src/main/java/com/alibaba/nacos/core/code/StartingSpringApplicationRunListener.java
core/src/main/java/com/alibaba/nacos/core/distributed/ProtocolExecutor.java
core/src/main/java/com/alibaba/nacos/core/distributed/raft/utils/RaftExecutor.java
core/src/main/java/com/alibaba/nacos/core/file/WatchFileCenter.java
core/src/main/java/com/alibaba/nacos/core/utils/GlobalExecutor.java

#2856
-  Unifiedly adjust the current existing way of creating thread pools in Nacos to the way of ExecutorFactory.xx in core and consistency module
-  ThreadUtils add some `shutdownThreadPool(xxx,xxx)` function to deregister executorService from ThreadPoolManager

[ISSUE #2856]Adjust the use of thread pools

---

naming/src/main/java/com/alibaba/nacos/naming/core/Cluster.java

Instance eliminate module naming optimization

---

common/src/main/java/com/alibaba/nacos/common/executor/ThreadPoolManager.java
common/src/main/java/com/alibaba/nacos/common/http/handler/ResponseHandler.java
common/src/main/java/com/alibaba/nacos/common/http/param/Query.java
common/src/main/java/com/alibaba/nacos/common/model/RestResult.java
common/src/main/java/com/alibaba/nacos/common/model/RestResultUtils.java
common/src/main/java/com/alibaba/nacos/common/utils/IoUtils.java
common/src/main/java/com/alibaba/nacos/common/utils/StringUtils.java
common/src/main/java/com/alibaba/nacos/common/utils/ThreadUtils.java
common/src/main/java/com/alibaba/nacos/common/utils/UuidUtils.java

For #2992 .
Add missing java doc for nacos-common for checkstyle
- Add missing java doc for nacos-common for checkstyle

[ISSUE #2992] Add missing java doc for nacos-common for checkstyle

---

config/src/main/java/com/alibaba/nacos/config/server/utils/JSONUtils.java
pom.xml
test/src/test/java/com/alibaba/nacos/test/core/JacksonUtils.java

For #3115 
- upgrade guava to 24.1.1-jre
- upgrade jackson to 2.10.4

[ISSUE #3115] Upgrade version of Jackson and Guava

---

style/codeStyle.md

Add CodeStyle plugin description

---

core/src/main/java/com/alibaba/nacos/core/cluster/Member.java
core/src/main/java/com/alibaba/nacos/core/cluster/MemberChangeEvent.java
core/src/main/java/com/alibaba/nacos/core/cluster/MemberChangeListener.java
core/src/main/java/com/alibaba/nacos/core/cluster/MemberUtils.java
core/src/main/java/com/alibaba/nacos/core/cluster/MembersChangeEvent.java
core/src/main/java/com/alibaba/nacos/core/cluster/ServerMemberManager.java
core/src/main/java/com/alibaba/nacos/core/controller/NacosClusterController.java
core/src/main/java/com/alibaba/nacos/core/distributed/ProtocolManager.java
core/src/main/java/com/alibaba/nacos/core/file/WatchFileCenter.java
naming/src/main/java/com/alibaba/nacos/naming/cluster/ServerListManager.java
naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/raft/RaftPeerSet.java
naming/src/main/java/com/alibaba/nacos/naming/core/DistroMapper.java
test/src/test/java/com/alibaba/nacos/test/core/cluster/ServerMemberManager_ITCase.java

[ISSUE #3110] Hotfix member health

---

naming/src/main/java/com/alibaba/nacos/naming/controllers/ServiceController.java

fix issues : #3175 
adjust order for start and end ，avoid end value is negative number
init `end` value after `start` value is determined

Update ServiceController.java: adjust order for start and end, avoid end value is negative number

---

config/src/test/java/com/alibaba/nacos/config/server/utils/GroupKeyTest.java
config/src/test/java/com/alibaba/nacos/config/server/utils/SimpleReadWriteLockTest.java

(1)I found there were some chinese unit test method name in the config test module, such as GroupKeyTest and SimpleReadWriteLockTest.
(2)So, I want fix it and translate into correct method name.
XX
XXXX

[#3185]Fix chinese unit method name in config test module.

---

address/pom.xml
api/pom.xml
client/pom.xml
cmdb/pom.xml
common/pom.xml
config/pom.xml
consistency/pom.xml
console/pom.xml
core/pom.xml
distribution/pom.xml
example/pom.xml
istio/pom.xml
naming/pom.xml
pom.xml
test/pom.xml

Update to 1.3.1-BETA

---

config/src/main/java/com/alibaba/nacos/config/server/Config.java
config/src/main/java/com/alibaba/nacos/config/server/aspect/CapacityManagementAspect.java
config/src/main/java/com/alibaba/nacos/config/server/aspect/RequestLogAspect.java
config/src/main/java/com/alibaba/nacos/config/server/auth/ConfigResourceParser.java
config/src/main/java/com/alibaba/nacos/config/server/auth/EmbeddedPermissionPersistServiceImpl.java
config/src/main/java/com/alibaba/nacos/config/server/auth/EmbeddedRolePersistServiceImpl.java
config/src/main/java/com/alibaba/nacos/config/server/auth/EmbeddedUserPersistServiceImpl.java
config/src/main/java/com/alibaba/nacos/config/server/auth/ExternalPermissionPersistServiceImpl.java
config/src/main/java/com/alibaba/nacos/config/server/auth/ExternalRolePersistServiceImpl.java
config/src/main/java/com/alibaba/nacos/config/server/auth/ExternalUserPersistServiceImpl.java
config/src/main/java/com/alibaba/nacos/config/server/auth/PermissionInfo.java
config/src/main/java/com/alibaba/nacos/config/server/auth/PermissionPersistService.java
config/src/main/java/com/alibaba/nacos/config/server/auth/RoleInfo.java
config/src/main/java/com/alibaba/nacos/config/server/auth/RolePersistService.java
config/src/main/java/com/alibaba/nacos/config/server/auth/UserPersistService.java
config/src/main/java/com/alibaba/nacos/config/server/configuration/ConditionOnEmbeddedStorage.java
config/src/main/java/com/alibaba/nacos/config/server/configuration/ConditionOnExternalStorage.java
config/src/main/java/com/alibaba/nacos/config/server/configuration/ConditionStandaloneEmbedStorage.java
config/src/main/java/com/alibaba/nacos/config/server/constant/Constants.java
config/src/main/java/com/alibaba/nacos/config/server/constant/CounterMode.java
config/src/main/java/com/alibaba/nacos/config/server/controller/CapacityController.java
config/src/main/java/com/alibaba/nacos/config/server/controller/CommunicationController.java
config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigController.java
config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigOpsController.java
config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigServletInner.java
config/src/main/java/com/alibaba/nacos/config/server/controller/HealthController.java
config/src/main/java/com/alibaba/nacos/config/server/controller/HistoryController.java
config/src/main/java/com/alibaba/nacos/config/server/controller/ListenerController.java

Resolve the issues of codestyle of nacos-config module for some package parts below.
Package:
(1)com.alibaba.nacos.config.server.
(2)com.alibaba.nacos.config.server.aspect.
(3)com.alibaba.nacos.config.server.auth.
(4)com.alibaba.nacos.config.server.configuration.
(5)com.alibaba.nacos.config.server.constant.
(6)com.alibaba.nacos.config.server.controller.
XX
XXXX

Resolve the issues of codestyle of nacos-config module for phase1

---

config/src/main/java/com/alibaba/nacos/config/server/service/repository/PaginationHelper.java
config/src/main/java/com/alibaba/nacos/config/server/service/repository/PersistService.java
config/src/main/java/com/alibaba/nacos/config/server/service/repository/RowMapperManager.java
config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/DatabaseOperate.java
config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/DerbySnapshotOperation.java
config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/DistributedDatabaseOperateImpl.java
config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedPaginationHelperImpl.java
config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedStoragePersistServiceImpl.java
config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePaginationHelperImpl.java
config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java

Resolve the issues of codestyle of nacos-config module for some package parts below.
Package:
(1)com.alibaba.nacos.config.server.service.repository
1. Remove `@SuppressWarnings("all")` on `PersistService` and fix PMD check 
2. Resolve  other ssues of codestyle of nacos-config module for `repository` part
PersistService is so big ，it contains 109  function, maybe we should split this classes and  remove unused function
XXXX

Resolve the issues of codestyle of nacos-config module for phase4

---

common/src/main/java/com/alibaba/nacos/common/constant/HttpHeaderConsts.java
common/src/main/java/com/alibaba/nacos/common/http/param/Query.java
common/src/main/java/com/alibaba/nacos/common/utils/ThreadUtils.java
common/src/test/java/com/alibaba/nacos/common/http/param/QueryTest.java

When users register instances by inputing instance object without clusterName directly. It will register a `null` cluster.
The reason is that some refactor will put the null parameter as 'null' string, and request to server.

Hotfix register null cluster name instance problem

---

distribution/bin/startup.cmd

Optimize  startup.cmd， fix #3269 

---

config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigServletInner.java
config/src/main/java/com/alibaba/nacos/config/server/service/notify/AsyncNotifyService.java
config/src/main/java/com/alibaba/nacos/config/server/service/notify/NotifyService.java
config/src/main/java/com/alibaba/nacos/config/server/service/notify/NotifySingleService.java
config/src/main/java/com/alibaba/nacos/config/server/service/notify/NotifyTask.java
config/src/main/java/com/alibaba/nacos/config/server/service/notify/NotifyTaskProcessor.java
config/src/main/java/com/alibaba/nacos/config/server/service/sql/EmbeddedStorageContextUtils.java
config/src/main/java/com/alibaba/nacos/config/server/service/sql/ModifyRequest.java
config/src/main/java/com/alibaba/nacos/config/server/service/sql/QueryType.java
config/src/main/java/com/alibaba/nacos/config/server/service/sql/SelectRequest.java
config/src/main/java/com/alibaba/nacos/config/server/service/trace/ConfigTraceService.java

Resolve the issues of codestyle of nacos-config module for some package parts below.
Package:
(1)com.alibaba.nacos.config.server.service.notify
(2)com.alibaba.nacos.config.server.service.sql
(3)com.alibaba.nacos.config.server.service.trace
XX
XXXX

[#3249]Resolve the issues of codestyle of nacos-config module for phase6

---

client/src/main/java/com/alibaba/nacos/client/naming/core/EventDispatcher.java
client/src/main/java/com/alibaba/nacos/client/naming/core/HostReactor.java
client/src/main/java/com/alibaba/nacos/client/naming/core/PushReceiver.java

(1)Add a variable closed in the PushReceiver.java /EventDispatcher.java to control the code's logical;
(2)Do close in the shutdown method, including udpSocket.close();
XX
XXXX

[ISSUE#3275]Fix the problem that 1.3.1-BETA SDK LifeCycle can't be shutdown for some thread executors. 

---

console/src/main/resources/META-INF/nacos-default.properties

From the nacos init commit, there are a default test mysql config, which is invalid. If users use extra storage and do not config their own mysql db. Users will get error information about the IP can't connect.

Hotfix default mysql config

---

config/src/main/java/com/alibaba/nacos/config/server/service/capacity/CapacityService.java
config/src/main/java/com/alibaba/nacos/config/server/service/capacity/GroupCapacityPersistService.java
config/src/main/java/com/alibaba/nacos/config/server/service/capacity/TenantCapacityPersistService.java
config/src/main/java/com/alibaba/nacos/config/server/service/datasource/DataSourceService.java
config/src/main/java/com/alibaba/nacos/config/server/service/datasource/DynamicDataSource.java
config/src/main/java/com/alibaba/nacos/config/server/service/datasource/ExternalDataSourceProperties.java
config/src/main/java/com/alibaba/nacos/config/server/service/datasource/ExternalDataSourceServiceImpl.java
config/src/main/java/com/alibaba/nacos/config/server/service/datasource/LocalDataSourceServiceImpl.java

(1).com.alibaba.nacos.config.server.service.capacity.
(2).com.alibaba.nacos.config.server.service.datasource.
XX
XXXX

[ISSUE#3249]Resolve the issues of codestyle of nacos-config module for phase8.

---

client/src/main/java/com/alibaba/nacos/client/naming/net/NamingProxy.java

use 1.3.1-BETA register ephemeral instance, client will send beat info for first beat. Old client use Servlet as http client, so it need to URLEncode body.
But in 1.3.1-BETA, we upgrade to use apache.httpclient, so we don't need to encode body. 
Otherwise will throw exception `can't parse json` in server because of the encoded body.

Hotfix send beat info error

---

common/src/main/java/com/alibaba/nacos/common/http/client/NacosRestTemplate.java
common/src/main/java/com/alibaba/nacos/common/http/handler/ResponseHandler.java
common/src/test/java/com/alibaba/nacos/common/notify/NotifyCenterTest.java
core/src/main/java/com/alibaba/nacos/core/cluster/ServerMemberManager.java
core/src/main/java/com/alibaba/nacos/core/notify/DefaultPublisher.java
core/src/main/java/com/alibaba/nacos/core/utils/DiskUtils.java
istio/pom.xml
istio/src/main/java/com/alibaba/nacos/istio/IstioApp.java
istio/src/main/java/com/alibaba/nacos/istio/mcp/CollectionTypes.java
istio/src/main/java/com/alibaba/nacos/istio/mcp/McpServerIntercepter.java
istio/src/main/java/com/alibaba/nacos/istio/mcp/NacosMcpServer.java
istio/src/main/java/com/alibaba/nacos/istio/mcp/NacosMcpService.java
istio/src/main/java/com/alibaba/nacos/istio/misc/IstioConfig.java
istio/src/main/java/com/alibaba/nacos/istio/misc/Loggers.java
naming/src/main/java/com/alibaba/nacos/naming/consistency/KeyBuilder.java
naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/raft/RaftStore.java
pom.xml

For #2992.
Use new code style for nacos-cmdb module.

[ISSUE #2992] Use new code style for nacos-cmdb module.

---

address/pom.xml
api/pom.xml
client/pom.xml
cmdb/pom.xml
common/pom.xml
config/pom.xml
consistency/pom.xml
console/pom.xml
core/pom.xml
distribution/pom.xml
example/pom.xml
istio/pom.xml
naming/pom.xml
pom.xml
test/pom.xml

Upgrade 1.3.1

---

api/src/main/java/com/alibaba/nacos/api/naming/remote/NamingRemoteConstants.java
api/src/main/java/com/alibaba/nacos/api/naming/remote/request/InstanceRequest.java
api/src/main/java/com/alibaba/nacos/api/naming/remote/request/NamingCommonRequest.java
api/src/main/java/com/alibaba/nacos/api/naming/remote/response/InstanceResponse.java
api/src/main/java/com/alibaba/nacos/api/remote/ResponseRegistry.java
api/src/main/java/com/alibaba/nacos/api/remote/request/Request.java
client/src/main/java/com/alibaba/nacos/client/config/remote/ConfigGrpcClientProxy.java
client/src/main/java/com/alibaba/nacos/client/naming/net/NamingGrpcClientProxy.java
config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigChangeListenRequestHandler.java
config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigQueryRequestHandler.java
core/src/main/java/com/alibaba/nacos/core/remote/RequestHandler.java
naming/src/main/java/com/alibaba/nacos/naming/remote/InstanceRequestHandler.java
naming/src/main/java/com/alibaba/nacos/naming/remote/SubscribeServiceRequestHandler.java

Add naming support gRPC for register and deregister instance
XXXX

Add naming support gRPC for register and deregister instance

---

api/pom.xml
api/src/main/java/com/alibaba/nacos/api/config/remote/request/ConfigChangeListenRequest.java
api/src/main/java/com/alibaba/nacos/api/config/remote/request/ConfigQueryRequest.java
api/src/main/java/com/alibaba/nacos/api/config/remote/response/ConfigQueryResponse.java
api/src/main/java/com/alibaba/nacos/api/remote/request/RequestMeta.java
api/src/main/java/com/alibaba/nacos/api/remote/response/Response.java
api/src/main/java/com/alibaba/nacos/api/remote/response/ResponseCode.java
client/src/main/java/com/alibaba/nacos/client/config/NacosConfigService.java
client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java
client/src/main/java/com/alibaba/nacos/client/config/remote/ConfigGrpcClientProxy.java
client/src/main/java/com/alibaba/nacos/client/config/utils/ParamUtils.java
client/src/main/java/com/alibaba/nacos/client/remote/RpcClient.java
client/src/main/java/com/alibaba/nacos/client/remote/RpcClientFactory.java
client/src/main/java/com/alibaba/nacos/client/remote/ServerListFactory.java
client/src/main/java/com/alibaba/nacos/client/remote/grpc/GrpcClient.java
config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigQueryRequestHandler.java
config/src/main/java/com/alibaba/nacos/config/server/utils/ParamUtils.java
core/src/main/java/com/alibaba/nacos/core/remote/ConnectCoordinator.java
core/src/main/java/com/alibaba/nacos/core/remote/ConnectionManager.java
core/src/main/java/com/alibaba/nacos/core/remote/RpcServer.java
core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcRequestHandlerReactor.java
core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcStreamRequestHanderImpl.java
core/src/main/java/com/alibaba/nacos/core/utils/Loggers.java
core/src/main/resources/META-INF/logback/nacos.xml

support config query in rpc channel ,add switch http/rpc at client side

---

api/src/main/java/com/alibaba/nacos/api/remote/response/Response.java
client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java
client/src/main/java/com/alibaba/nacos/client/config/remote/ConfigGrpcClientProxy.java
client/src/main/java/com/alibaba/nacos/client/remote/RpcClient.java
client/src/main/java/com/alibaba/nacos/client/remote/RpcClientStatus.java
client/src/main/java/com/alibaba/nacos/client/remote/grpc/GrpcClient.java
client/src/test/java/com/alibaba/nacos/client/ConfigTest.java

client reconnection optimize

---

client/src/main/java/com/alibaba/nacos/client/remote/RpcClient.java
client/src/main/java/com/alibaba/nacos/client/remote/grpc/GrpcClient.java
client/src/test/java/com/alibaba/nacos/client/ConfigTest.java

[ISSUE #1097] client reconnect optimize,  combine first time start and reconnect code 

---

api/src/main/java/com/alibaba/nacos/api/naming/remote/NamingRemoteConstants.java
api/src/main/java/com/alibaba/nacos/api/naming/remote/request/InstanceRequest.java
api/src/main/java/com/alibaba/nacos/api/naming/remote/request/SubscribeServiceRequest.java
api/src/main/java/com/alibaba/nacos/api/naming/remote/response/NotifySubscriberResponse.java
api/src/main/java/com/alibaba/nacos/api/naming/remote/response/QueryServiceResponse.java
api/src/main/java/com/alibaba/nacos/api/naming/remote/response/SubscribeServiceResponse.java
api/src/main/java/com/alibaba/nacos/api/remote/ResponseRegistry.java
client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingService.java
client/src/main/java/com/alibaba/nacos/client/naming/core/HostReactor.java
client/src/main/java/com/alibaba/nacos/client/naming/net/NamingGrpcClientProxy.java
client/src/main/java/com/alibaba/nacos/client/naming/net/gprc/NamingGrpcClientProxy.java
client/src/main/java/com/alibaba/nacos/client/naming/net/gprc/NamingPushResponseHandler.java
client/src/main/java/com/alibaba/nacos/client/remote/ServerPushResponseHandler.java
common/src/main/java/com/alibaba/nacos/common/utils/ConcurrentHashSet.java
core/src/main/java/com/alibaba/nacos/core/remote/AsyncListenContext.java
core/src/main/java/com/alibaba/nacos/core/remote/DataChangeListenerNotifier.java
naming/src/main/java/com/alibaba/nacos/naming/core/ServiceInfoGenerator.java
naming/src/main/java/com/alibaba/nacos/naming/core/SubscribeManager.java
naming/src/main/java/com/alibaba/nacos/naming/push/PushService.java
naming/src/main/java/com/alibaba/nacos/naming/push/RemotePushService.java
naming/src/main/java/com/alibaba/nacos/naming/remote/handler/InstanceRequestHandler.java
naming/src/main/java/com/alibaba/nacos/naming/remote/handler/ServiceQueryRequestHandler.java
naming/src/main/java/com/alibaba/nacos/naming/remote/handler/SubscribeServiceRequestHandler.java

For #1097 .
Naming support un/subscribe service by grpc.
XX
XXXX

[ISSUE #1097] Naming support un/subscribe service by grpc.

---

client/src/main/java/com/alibaba/nacos/client/naming/core/PushReceiver.java

Hotfix client sdk depend jdk7 charset.
XXXX

Hotfix client sdk depend jdk7 charset.

---

client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingService.java
client/src/main/java/com/alibaba/nacos/client/naming/beat/BeatReactor.java
client/src/main/java/com/alibaba/nacos/client/naming/core/HostReactor.java
client/src/main/java/com/alibaba/nacos/client/naming/core/PushReceiver.java
client/src/main/java/com/alibaba/nacos/client/naming/remote/NamingClientProxy.java
client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc/NamingGrpcClientProxy.java
client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc/NamingPushResponseHandler.java
client/src/main/java/com/alibaba/nacos/client/naming/remote/http/NamingHttpClientProxy.java
client/src/test/java/com/alibaba/nacos/client/naming/core/HostReactorTest.java

For #3386 
Move BeatReactor into HttpClientProxy
XXXX

[ISSUE #3386] Move BeatReactor into HttpClientProxy

---

api/src/main/java/com/alibaba/nacos/api/remote/response/ServerPushResponse.java
client/src/main/java/com/alibaba/nacos/client/remote/grpc/GrpcClient.java
client/src/test/java/com/alibaba/nacos/client/ConfigTest.java
core/src/main/java/com/alibaba/nacos/core/remote/RpcPushService.java
core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcConnection.java
core/src/main/java/com/alibaba/nacos/core/remote/grpc/PushAckIdGenerator.java

strengthen exception handle both on server and client ; status transfer bug fix on client 

---

config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedStoragePersistServiceImpl.java
config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java

resolved [#3382](https://github.com/alibaba/nacos/issues/3382)
XX
XXXX

[ISSUE #3382] Use PreparedStatement to replace string concatenation

---

distribution/bin/startup.cmd

Nacos cannot start by startup.cmd script in windows enviroments.
So I modified the startup.cmd scripts and fix the issues.
XX
XXXX

[ISSUE#3409]fix Nacos can't start by the startup.cmd script in windows enviroment.

---

api/src/main/java/com/alibaba/nacos/api/remote/ResponseRegistry.java
api/src/main/java/com/alibaba/nacos/api/remote/connection/Connection.java
api/src/main/java/com/alibaba/nacos/api/remote/exception/ConnectionAlreadyClosedException.java
api/src/main/java/com/alibaba/nacos/api/remote/exception/RemoteException.java
api/src/main/java/com/alibaba/nacos/api/remote/request/HeartBeatRequest.java
api/src/main/java/com/alibaba/nacos/api/remote/request/InternalRequest.java
api/src/main/java/com/alibaba/nacos/api/remote/request/Request.java
api/src/main/java/com/alibaba/nacos/api/remote/request/ServerCheckRequest.java
api/src/main/java/com/alibaba/nacos/api/remote/response/ConnectionUnregisterResponse.java
api/src/main/java/com/alibaba/nacos/api/remote/response/ResponseTypeConstants.java
api/src/main/java/com/alibaba/nacos/api/remote/response/ServerCheckResponse.java
client/src/main/java/com/alibaba/nacos/client/remote/RpcClientStatus.java
client/src/main/java/com/alibaba/nacos/client/remote/grpc/GrpcClient.java
client/src/test/java/com/alibaba/nacos/client/ConfigTest.java
console/src/main/java/com/alibaba/nacos/console/controller/ServerLoaderController.java
core/src/main/java/com/alibaba/nacos/core/remote/ConnectCoordinator.java
core/src/main/java/com/alibaba/nacos/core/remote/ConnectionManager.java
core/src/main/java/com/alibaba/nacos/core/remote/RpcPushService.java
core/src/main/java/com/alibaba/nacos/core/remote/RpcServer.java
core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcConnection.java
core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcRequestHandlerReactor.java
core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcServer.java

switch server optimize and loader balance base on max client count

---

api/src/main/java/com/alibaba/nacos/api/naming/remote/NamingRemoteConstants.java
api/src/main/java/com/alibaba/nacos/api/naming/remote/request/ServiceListRequest.java
api/src/main/java/com/alibaba/nacos/api/naming/remote/response/ServiceListResponse.java
api/src/main/java/com/alibaba/nacos/api/remote/ResponseRegistry.java
client/src/main/java/com/alibaba/nacos/client/naming/remote/NamingClientProxyDelegate.java
client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc/NamingGrpcClientProxy.java
naming/src/main/java/com/alibaba/nacos/naming/controllers/ServiceController.java
naming/src/main/java/com/alibaba/nacos/naming/remote/handler/ServiceListRequestHandler.java
naming/src/main/java/com/alibaba/nacos/naming/utils/ServiceUtil.java
naming/src/test/java/com/alibaba/nacos/naming/utils/ServiceUtilTest.java

For #1097 
grpc support all namingService api
XXXX

[ISSUE #1097]grpc support all namingService api

---

config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedStoragePersistServiceImpl.java

#3434 
Fix DataAccessException when running in embedded mode.
SQL syntax exception occurs when the isExistTable method is executed when running in embedded mode.
Fix DataAccessException when running in embedded mode.
Runserver in embeded mode  and check `logs/config-fatal.log`.

[ISSUE#3434] Fix DataAccessException when running in embedded mode.

---

console/src/main/resources/static/console-fe/src/globalLib.js
console/src/main/resources/static/console-fe/src/utils/request.js

For #3428, Fix token valid go login bug
console/src/main/resources/static/console-fe/src/globalLib.js:531
console/src/main/resources/static/console-fe/src/utils/request.js:88
test completion! token valid go login success!

[ISSUE #3428] Fix token valid go login bug

---

console/src/main/java/com/alibaba/nacos/console/security/nacos/roles/NacosRoleServiceImpl.java

#3388
We should rest nacos roles, permissions when reloading role info from database. For some scenarios, some roles and permission may be removed by administrator.
XXXX

[#3388]Reset nacos roles, permissions during reloading role info from database

---

client/src/main/java/com/alibaba/nacos/client/config/impl/ServerListManager.java
style/NacosCheckStyle.xml

fix checkstyle error

---

address/src/main/java/com/alibaba/nacos/address/auth/AddressServerAuthManager.java
address/src/main/java/com/alibaba/nacos/address/configuration/AddressServerSpringConfiguration.java

[ISSUE#3091] Fix address server can't start up by implement an empty auth manager.

---

common/src/main/java/com/alibaba/nacos/common/http/param/MediaType.java
config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigServletInner.java
config/src/main/java/com/alibaba/nacos/config/server/enums/FileTypeEnum.java

[#1839]add ContentType return while getConfig

---

core/src/main/java/com/alibaba/nacos/core/distributed/id/SnowFlowerIdGenerator.java

#3485 
Fix the UnknownHostException is swallowed
Fix the UnknownHostException is swallowed

[ISSUE #3485] Fix the UnknownHostException is swallowed

---

address/pom.xml
api/pom.xml
client/pom.xml
cmdb/pom.xml
common/pom.xml
config/pom.xml
consistency/pom.xml
console/pom.xml
core/pom.xml
distribution/pom.xml
example/pom.xml
istio/pom.xml
naming/pom.xml
pom.xml
test/pom.xml

Upgrade version to 1.3.2
XX
XXXX

Upgrade version to 1.3.2

---

distribution/bin/shutdown.sh
distribution/bin/startup.sh

#3397 
Fix shell syntax error when running in ubuntu
Fix shell syntax error when running in ubuntu
1. build project
2. run `./startup.sh` in ubuntu

[ISSUE #3397]Fix shell syntax error when running in ubuntu

---

core/src/main/java/com/alibaba/nacos/core/auth/AuthFilter.java
core/src/main/java/com/alibaba/nacos/core/auth/RequestMappingInfo.java
core/src/main/java/com/alibaba/nacos/core/auth/condition/ParamRequestCondition.java
core/src/main/java/com/alibaba/nacos/core/auth/condition/PathRequestCondition.java
core/src/main/java/com/alibaba/nacos/core/code/ControllerMethodsCache.java
core/src/main/java/com/alibaba/nacos/core/utils/Constants.java
naming/src/main/java/com/alibaba/nacos/naming/web/DistroFilter.java
test/src/test/java/com/alibaba/nacos/test/core/code/ControllerMethodsCacheTest.java

[ISSUE #3486] Fix com.alibaba.nacos.core.code.ControllerMethodsCache will mismatch sometimes

---

config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigController.java
config/src/main/java/com/alibaba/nacos/config/server/service/repository/RowMapperManager.java
config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedStoragePersistServiceImpl.java
config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java
config/src/main/java/com/alibaba/nacos/config/server/utils/RequestUtil.java
console/src/main/java/com/alibaba/nacos/console/security/nacos/NacosAuthManager.java
core/src/main/java/com/alibaba/nacos/core/auth/AuthFilter.java

NacosAuthManager request.setAttribute(user) and ConfigController getSrcUserName(req)
XX
XXXX

Fix #3269 When nacos.core.auth.enabled = true, user information is saved to the request in login

---

console/pom.xml
console/src/main/java/com/alibaba/nacos/console/utils/JwtTokenUtils.java
pom.xml

Jjwt API is updated to 0.11.2 and the deprected method is optimized
Jjwt API is updated to 0.11.2 and the deprected method is optimized

[ISSUE #3536] upgrade Jjwt to 0.11.2

---

naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/raft/RaftStore.java

[ISSUE #3550]. fix instance cache file can't create in server side

---

address/pom.xml
api/pom.xml
client/pom.xml
cmdb/pom.xml
common/pom.xml
config/pom.xml
consistency/pom.xml
console/pom.xml
core/pom.xml
distribution/pom.xml
example/pom.xml
istio/pom.xml
naming/pom.xml
pom.xml
test/pom.xml

Upgrade version to 1.4.0-SNAPSHOT

Upgrade version to 1.4.0-SNAPSHOT

---

auth/pom.xml
core/pom.xml
pom.xml

refer #3566 
create a `nacos-auth` module, And add `nacos-auth` dependency for `nacos-core` module
XXXX

[ISSUE #3566] create a nacos-auth module

---

core/src/main/java/com/alibaba/nacos/core/utils/InetUtils.java

[ISSUE #3595] delete the unnecessary code if com.alibaba.nacos.core.utils.InetUtils static code

---

auth/src/main/java/com/alibaba/nacos/auth/common/AuthConfigs.java
console/src/main/java/com/alibaba/nacos/console/security/nacos/JwtTokenManager.java

[ISSUE #3600] Replace the deprecated api of jwt

---

client/src/test/java/com/alibaba/nacos/client/ConfigTest.java

Fix issue #3613 
1. remove `static` in method of `before`, `test`.
2.  update new  method of `test`.

[ISSUE #3613]  Fix `unit test method not be static` & update publish config listener  in `ConfigTest.java`

---

auth/pom.xml
auth/src/main/java/com/alibaba/nacos/auth/common/AuthConfigs.java
console/pom.xml
core/pom.xml

[ISSUE #3622] Move jwt dependency from console,core to auth.

---

client/src/main/java/com/alibaba/nacos/client/config/http/ServerHttpAgent.java
client/src/main/java/com/alibaba/nacos/client/naming/net/NamingProxy.java
client/src/main/java/com/alibaba/nacos/client/security/SecurityProxy.java
common/src/main/java/com/alibaba/nacos/common/http/HttpUtils.java
common/src/main/java/com/alibaba/nacos/common/http/client/NacosAsyncRestTemplate.java
common/src/main/java/com/alibaba/nacos/common/http/client/NacosRestTemplate.java
common/src/main/java/com/alibaba/nacos/common/model/RequestHttpEntity.java
test/src/test/java/com/alibaba/nacos/test/common/NacosAsyncRestTemplate_ITCase.java
test/src/test/java/com/alibaba/nacos/test/common/NacosRestTemplate_ITCase.java
test/src/test/java/com/alibaba/nacos/test/common/NacosRestTemplate_Interceptors_ITCase.java
test/src/test/java/com/alibaba/nacos/test/naming/NamingBase.java

refer #3638  
- Unified use of Query objects as  URL template variables params.
- Add put and post methods without  URL template variables params.
XXXX

[ISSUE #3638]  unified implementation of http client api adjustment.

---

README.md

1. It’s a little weird to use Chinese comma in English
2. Fix typo:   change 'reposity' to  'repository', 'instance' to 'instances'
3. Format other details of the doc
XXXXX
XX
XXXX

fix typo and  format  doc of README file

---

common/src/main/java/com/alibaba/nacos/common/http/param/Header.java

Fix Logging in with the wrong username or password will cause jackson serialization results to fail

---

naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/DistroConsistencyServiceImpl.java
naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/DistroHttpData.java
naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/component/DistroDataStorageImpl.java
naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/component/DistroHttpAgent.java
naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/newimpl/DistroProtocol.java
naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/newimpl/component/DistroComponentHolder.java
naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/newimpl/component/DistroDataProcessor.java
naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/newimpl/task/verify/DistroVerifyTask.java
naming/src/main/java/com/alibaba/nacos/naming/controllers/DistroController.java

For #3692 .
- Use new distro implmentation to handle sync datum request
- Use new distro implmentation to handle checksum request
- Use new distro implmentation to handle get datum request.

[Issue #3692] Use new distro implmentation to handle sync datum and checksum request

---

naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/DistroConsistencyServiceImpl.java
naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/component/DistroDataStorageImpl.java
naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/component/DistroHttpAgent.java
naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/newimpl/DistroProtocol.java
naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/newimpl/component/DistroComponentHolder.java
naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/newimpl/component/DistroDataProcessor.java
naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/newimpl/component/DistroDataStorage.java
naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/newimpl/component/DistroTransportAgent.java
naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/newimpl/exception/DistroException.java
naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/newimpl/task/load/DistroLoadDataTask.java
naming/src/main/java/com/alibaba/nacos/naming/controllers/DistroController.java
naming/src/test/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/DistroConsistencyServiceImplTest.java

For #3692 .
- Use new distro implmentation to handle init all datum request.

[ISSUE#3692] Use new distro implmentation to handle init all datum request.

---

api/src/main/java/com/alibaba/nacos/api/remote/request/ServerLoaderInfoRequest.java
api/src/main/java/com/alibaba/nacos/api/remote/response/ServerLoaderInfoResponse.java
client/src/test/java/com/alibaba/nacos/client/ConfigTest.java
common/src/main/java/com/alibaba/nacos/common/remote/client/Connection.java
common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClient.java
common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClient.java
common/src/main/java/com/alibaba/nacos/common/remote/client/rsocket/RsocketRpcClient.java
console/src/main/java/com/alibaba/nacos/console/controller/ServerLoaderController.java
core/src/main/java/com/alibaba/nacos/core/cluster/MemberUtils.java
core/src/main/java/com/alibaba/nacos/core/remote/ConnectionManager.java
core/src/main/java/com/alibaba/nacos/core/remote/core/HeartBeatRequestHandler.java
core/src/main/java/com/alibaba/nacos/core/remote/core/RemoteConnectionEventListener.java
core/src/main/java/com/alibaba/nacos/core/remote/core/ServerLoaderInfoRequestHandler.java
core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcConnection.java
core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcServer.java

…oader balance  with specific server ip
XXXXX
XX
XXXX

client switch server bugfix ; cluster server connection manage ； loader balance with specific server ip

---

client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java
client/src/test/java/com/alibaba/nacos/client/ConfigTest.java
console/src/main/java/com/alibaba/nacos/console/controller/ServerLoaderController.java
core/src/main/java/com/alibaba/nacos/core/remote/ConnectionManager.java
core/src/main/java/com/alibaba/nacos/core/remote/rsocket/RsocketRpcServer.java
pom.xml

…; switch single
XXXXX
XX
XXXX

loader balance basic support: adjust loader count once  and up limit ；switch single client

---

naming/src/main/java/com/alibaba/nacos/naming/controllers/ApiController.java
naming/src/main/java/com/alibaba/nacos/naming/controllers/InstanceController.java

[ISSUE #3770] replace the deprecated api com.fasterxml.jackson.databind.node.ObjectNode#put(java.lang.String, com.fasterxml.jackson.databind.JsonNode)

---

api/src/main/java/com/alibaba/nacos/api/config/remote/request/ConfigChangeNotifyRequest.java
api/src/main/java/com/alibaba/nacos/api/config/remote/response/ConfigChangeBatchListenResponse.java
api/src/main/java/com/alibaba/nacos/api/remote/AbstractRequestCallBack.java
api/src/main/java/com/alibaba/nacos/api/remote/DefaultRequestFuture.java
api/src/main/java/com/alibaba/nacos/api/remote/RpcScheduledExecutor.java
client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc/NamingGrpcClientProxy.java
client/src/test/java/com/alibaba/nacos/client/ConfigTest.java
client/src/test/java/com/alibaba/nacos/client/config/listener/impl/ClientWorkerTest.java
common/pom.xml
common/src/main/java/com/alibaba/nacos/common/remote/client/Connection.java
common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClient.java
common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClientFactory.java
common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClient.java
common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClusterClient.java
common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcConnection.java
common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcOpsClient.java
common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcSdkClient.java
common/src/main/java/com/alibaba/nacos/common/remote/client/rsocket/RsocketConnection.java
config/src/main/java/com/alibaba/nacos/config/server/remote/RpcConfigChangeNotifier.java
core/src/main/java/com/alibaba/nacos/core/cluster/remote/ClusterRpcClientProxy.java
core/src/main/java/com/alibaba/nacos/core/remote/RpcAckCallbackSynchronizer.java
core/src/main/java/com/alibaba/nacos/core/remote/RpcPushService.java
core/src/main/java/com/alibaba/nacos/core/remote/RpcServer.java
core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcClusterServer.java
core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcConnection.java
core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcSdkServer.java
core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcServer.java
core/src/main/java/com/alibaba/nacos/core/remote/rsocket/RsocketConnection.java
naming/src/main/java/com/alibaba/nacos/naming/cluster/remote/grpc/GrpcClusterClient.java

and cluster grpc server port.
XXXXX
XX
XXXX

request callback timeout support both at client and server; split sdk cluster grpc server port.

---

naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/DistroConsistencyServiceImpl.java
naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/DistroHttpData.java
naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/DistroHttpRegistry.java
naming/src/main/java/com/alibaba/nacos/naming/controllers/DistroController.java
naming/src/test/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/DistroConsistencyServiceImplTest.java

For #3658 .
Some enhance refactor for naming distro

[ISSUE #3658] Some enhance refactor for naming distro

---

api/src/main/java/com/alibaba/nacos/api/naming/utils/NamingUtils.java
naming/src/main/java/com/alibaba/nacos/naming/controllers/InstanceController.java

[ISSUE #3687] check serviceName's format(groupName@@serviceName) in server and client

---

naming/src/main/java/com/alibaba/nacos/naming/core/v2/index/ServiceStorage.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/pojo/Service.java
naming/src/main/java/com/alibaba/nacos/naming/push/RemotePushService.java
naming/src/main/java/com/alibaba/nacos/naming/remote/handler/ServiceListRequestHandler.java
naming/src/main/java/com/alibaba/nacos/naming/utils/ServiceUtil.java

Adapt query service list request with new model
XX
XXXX

Adapt query service list request with new model

---

client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java
client/src/test/java/com/alibaba/nacos/client/ConfigTest.java
common/src/main/java/com/alibaba/nacos/common/remote/client/Connection.java
common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClient.java
common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClientFactory.java
common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClientStatus.java
common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClient.java
common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcConnection.java
common/src/main/java/com/alibaba/nacos/common/remote/client/rsocket/RsocketRpcClient.java
config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigConnectionEventListener.java
console/src/main/resources/application.properties
core/src/main/java/com/alibaba/nacos/core/cluster/ServerMemberManager.java
core/src/main/java/com/alibaba/nacos/core/cluster/remote/ClusterRpcClientProxy.java
core/src/main/java/com/alibaba/nacos/core/remote/BaseRpcServer.java
core/src/main/java/com/alibaba/nacos/core/remote/core/ServerLoaderInfoRequestHandler.java
core/src/main/java/com/alibaba/nacos/core/remote/grpc/BaseGrpcServer.java
core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcClusterServer.java
core/src/main/java/com/alibaba/nacos/core/remote/rsocket/RsocketRpcServer.java

optmize rpc client lifecycle ；request timeout to rpc client； some bugfix

---

api/src/main/java/com/alibaba/nacos/api/remote/RemoteConstants.java
api/src/main/java/com/alibaba/nacos/api/remote/Requester.java
client/src/test/java/com/alibaba/nacos/client/ConfigTest.java
common/src/main/java/com/alibaba/nacos/common/constant/HttpHeaderConsts.java
common/src/main/java/com/alibaba/nacos/common/remote/client/Connection.java
common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClient.java
config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigPublishRequestHandler.java
config/src/main/java/com/alibaba/nacos/config/server/remote/RpcConfigChangeNotifier.java
config/src/main/java/com/alibaba/nacos/config/server/service/dump/ExternalDumpService.java
core/src/main/java/com/alibaba/nacos/core/cluster/remote/ClusterRpcClientProxy.java
core/src/main/java/com/alibaba/nacos/core/remote/Connection.java
core/src/main/java/com/alibaba/nacos/core/remote/ConnectionManager.java
core/src/main/java/com/alibaba/nacos/core/remote/RpcPushService.java
core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcBiStreamRequestAcceptor.java
core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcConnection.java
core/src/main/java/com/alibaba/nacos/core/remote/rsocket/RsocketConnection.java
core/src/main/java/com/alibaba/nacos/core/remote/rsocket/RsocketRpcServer.java
naming/src/main/java/com/alibaba/nacos/naming/cluster/remote/ClusterConnection.java
pom.xml

optimize dumpService warning on starting up ； async request suppport in cluster rpc client proxy.

---

common/src/main/java/com/alibaba/nacos/common/http/param/MediaType.java

Set mediaType charset as utf8 to hotfix the garbled config when publish Chinese context
XXXX

Set mediaType charset as utf8

---

core/src/main/java/com/alibaba/nacos/core/utils/DiskUtils.java
style/nacos-code-style-for-idea.xml

Fix code style problem in DiskUtils

---

core/src/main/java/com/alibaba/nacos/core/auth/RemoteRequestAuthFilter.java
core/src/main/java/com/alibaba/nacos/core/remote/AbstractRequestFilter.java
core/src/main/java/com/alibaba/nacos/core/remote/RequestFilters.java
core/src/main/java/com/alibaba/nacos/core/remote/RequestHandler.java
naming/src/main/java/com/alibaba/nacos/naming/controllers/InstanceController.java
naming/src/main/java/com/alibaba/nacos/naming/core/InstanceService.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/AbstractClient.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/impl/IpPortBasedClient.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/IpPortBasedClientManager.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/MetadataConstants.java
naming/src/main/java/com/alibaba/nacos/naming/healthcheck/BeatCheckTask.java
naming/src/main/java/com/alibaba/nacos/naming/healthcheck/BeatProcessor.java
naming/src/main/java/com/alibaba/nacos/naming/healthcheck/ClientBeatCheckTask.java
naming/src/main/java/com/alibaba/nacos/naming/healthcheck/ClientBeatCheckTaskV2.java
naming/src/main/java/com/alibaba/nacos/naming/healthcheck/ClientBeatProcessor.java
naming/src/main/java/com/alibaba/nacos/naming/healthcheck/ClientBeatProcessorV2.java
naming/src/main/java/com/alibaba/nacos/naming/healthcheck/HealthCheckReactor.java
naming/src/main/java/com/alibaba/nacos/naming/push/v2/PushExecuteServiceDelegate.java
naming/src/main/java/com/alibaba/nacos/naming/remote/handler/ServiceQueryRequestHandler.java

Add heart check for instance registered by http client and openAPI

---

naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/v2/DistroClientDataProcessor.java
naming/src/main/java/com/alibaba/nacos/naming/controllers/InstanceController.java
naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperator.java
naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperatorClientImpl.java
naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperatorServiceImpl.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/ClientManager.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/ClientManagerDelegate.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/ConnectionBasedClientManager.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/IpPortBasedClientManager.java
naming/src/main/java/com/alibaba/nacos/naming/pojo/Subscriber.java
naming/src/main/java/com/alibaba/nacos/naming/push/PushService.java
naming/src/main/java/com/alibaba/nacos/naming/remote/handler/SubscribeServiceRequestHandler.java
naming/src/test/java/com/alibaba/nacos/naming/core/SubscribeManagerTest.java
naming/src/test/java/com/alibaba/nacos/naming/pojo/SubscriberTest.java

Refactor Instance Controller

---

naming/src/main/java/com/alibaba/nacos/naming/core/SubscribeManager.java

The http status code judgment error in the` SubscribeManager#getSubscribers()` method.

Fix the wrong judgment of HTTP status code in SubscribeManager#getSubscribers() method

---

naming/src/main/java/com/alibaba/nacos/naming/misc/NamingProxy.java

#3871 
fix description don't match the error

[ISSUE #3871] fix description don't match the error

---

client/src/main/java/com/alibaba/nacos/client/naming/cache/ConcurrentDiskUtil.java
client/src/test/java/com/alibaba/nacos/client/naming/cache/DiskCacheTest.java

#3815
Fix chinese string are truncated in ConcunrrentDiskUtil.
Fix chinese string are truncated in ConcunrrentDiskUtil.
look at unit test

[ISSUE #3815]Fix chinese string are truncated in ConcunrrentDiskUtil

---

core/src/main/java/com/alibaba/nacos/core/cluster/lookup/AddressServerMemberLookup.java

[ISSUE-3951] isAddressServerHealth set as true when request success

---

client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingService.java

fix #3533 
use config mode to unify the naming system variables.
XXXX

[ISSUE#3533] change cache dir with namespace -- part 1

---

client/src/main/java/com/alibaba/nacos/client/logging/AbstractNacosLogging.java
client/src/main/resources/nacos-log4j2.xml
client/src/main/resources/nacos-logback.xml

Fix #3533 
The main framework is:
(1) If the environment variable 'JM.LOG.PATH' is set, use ${sys:JM.LOG.PATH}/nacos as the parent dir of log files for naming and config module.
(2) Else, use ${sys:user.home}/logs/nacos as the parent dir of log files.
In detail, "nacos.logging.path" -> "JM.LOG.PATH" is made in 
client/src/main/java/com/alibaba/nacos/client/logging/AbstractNacosLogging.java
and 
the log4j configuration files: client/src/main/resources/nacos-log4j2.xml and nacos-logback.xml
XXXX

[ISSUE#3533] change cache dir with namespace -- part 2

---

config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java

[ISSUE-#3953] Fix typo in com.alibaba.nacos.config.server.service.repository.extrnal.ExternalStoragePersistServiceImpl#detailConfigHistory

---

naming/src/test/java/com/alibaba/nacos/naming/controllers/ClusterControllerTest.java

[ISSUE-#3955] Fix com.alibaba.nacos.naming.controllers.ClusterControllerTest can't pass

---

core/src/main/java/com/alibaba/nacos/core/cluster/MemberMetaDataConstants.java
core/src/main/java/com/alibaba/nacos/core/cluster/MemberUtils.java
core/src/main/java/com/alibaba/nacos/core/cluster/ServerMemberManager.java
core/src/test/java/com/alibaba/nacos/core/cluster/MemberUtilsTest.java
core/src/test/java/com/alibaba/nacos/core/cluster/ServerMemberManagerTest.java

Fix #3384 .
Fix member extend info do not update error.

[ISSUE#3384] Fix member extend info do not update error.

---

client/src/main/java/com/alibaba/nacos/client/security/SecurityProxy.java

This reverts commit 29ba11eb to fix #3992
Fix #3992 .
Revert "for #3621 (#3668)" to fix issue 3992.

[ISSUE#3992] Revert "for #3621 (#3668)" to fix issue 3992.

---

core/src/main/java/com/alibaba/nacos/core/distributed/distro/DistroProtocol.java
core/src/main/java/com/alibaba/nacos/core/distributed/distro/task/load/DistroLoadDataTask.java
naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/DistroConsistencyServiceImpl.java

[ISSUE-#4056] Ignore load data from remote when standalone mode

---

.github/workflows/maven.yml

Initial GitHub Action workflow to test nacos on JDK 8 and 11.
Added a workflow file.
Run the action.

Initial GitHub Action workflow to test nacos on JDK 8 and 11

---

naming/src/test/java/com/alibaba/nacos/naming/core/ServiceManagerTest.java

[ISSUE-#4068] Fix ServiceManagerTest#testUpdateIpAddressesNoInstance can't pass

---

naming/src/main/java/com/alibaba/nacos/naming/push/ClientInfo.java

Modify the Go Client display in the service subscription list,keep it consistent with other client styles.
ClientTypeDescription.GO_CLIENT="Nacos-Go-Client"

Refine GoClient  value

---

naming/src/main/java/com/alibaba/nacos/naming/core/ServiceManager.java

fix: typo fix in `ServiceManager`

---

address/pom.xml
api/pom.xml
auth/pom.xml
client/pom.xml
cmdb/pom.xml
common/pom.xml
config/pom.xml
consistency/pom.xml
console/pom.xml
core/pom.xml
distribution/pom.xml
example/pom.xml
istio/pom.xml
naming/pom.xml
pom.xml
sys/pom.xml
test/pom.xml

Upgrade to 1.4.0

---

core/src/main/java/com/alibaba/nacos/core/distributed/id/SnowFlowerIdGenerator.java

#4093 
`IdGeneratorManager.register()` calls the `InetAddress.getLocalHost()` method multiple times, and this is time-consuming. Using `InetUtils.getSelfIP()` replacement has speeded up the startup
XXXX

Reduce unnecessary InetAddress.getLocalHost() calls

---

common/src/main/java/com/alibaba/nacos/common/notify/DefaultSharePublisher.java
common/src/main/java/com/alibaba/nacos/common/utils/MapUtils.java

[ISSUE-#4125] Fix param check in com.alibaba.nacos.common.utils.MapUtils#computeIfAbsent

---

api/src/main/java/com/alibaba/nacos/api/common/Constants.java
naming/src/main/java/com/alibaba/nacos/naming/controllers/ServiceController.java

[ISSUE-#4132] com.alibaba.nacos.naming.controllers.ServiceController.list param groupName support '*' to get all group serviceName

---

address/pom.xml
api/pom.xml
auth/pom.xml
client/pom.xml
cmdb/pom.xml
common/pom.xml
config/pom.xml
consistency/pom.xml
console/pom.xml
core/pom.xml
distribution/pom.xml
example/pom.xml
istio/pom.xml
naming/pom.xml
pom.xml
sys/pom.xml
test/pom.xml

Upgrade to 1.4.1-SNAPSHOT

---

naming/src/main/java/com/alibaba/nacos/naming/core/ServiceManager.java
naming/src/test/java/com/alibaba/nacos/naming/core/ServiceManagerTest.java

[ISSUE-#4066] Make serviceNameList followed string order

---

common/src/main/java/com/alibaba/nacos/common/http/HttpClientBeanHolder.java

[ISSUE#3832] add common http client shutdown method

---

client/src/main/java/com/alibaba/nacos/client/config/impl/ConfigChangeHandler.java
cmdb/src/main/java/com/alibaba/nacos/cmdb/memory/CmdbProvider.java
common/src/main/java/com/alibaba/nacos/common/notify/NotifyCenter.java
common/src/main/java/com/alibaba/nacos/common/spi/NacosServiceLoader.java
common/src/main/java/com/alibaba/nacos/common/spi/ServiceLoaderException.java
common/src/test/java/com/alibaba/nacos/common/spi/NacosServiceLoaderTest.java
common/src/test/java/com/alibaba/nacos/common/spi/SpiTestImpl.java
common/src/test/java/com/alibaba/nacos/common/spi/SpiTestInterface.java
common/src/test/resources/META-INF/services/com.alibaba.nacos.common.spi.SpiTestInterface
consistency/src/main/java/com/alibaba/nacos/consistency/SerializeFactory.java
core/src/main/java/com/alibaba/nacos/core/distributed/ConsistencyConfiguration.java
core/src/main/java/com/alibaba/nacos/core/distributed/id/IdGeneratorManager.java
naming/src/main/java/com/alibaba/nacos/naming/healthcheck/extend/HealthCheckExtendProvider.java

Add NacosServiceLoader and replace ServiceLoader usage directly

---

common/src/main/java/com/alibaba/nacos/common/notify/NotifyCenter.java

[ISSUE-#4166] Optimize notifyCenter code

---

api/src/main/java/com/alibaba/nacos/api/config/ConfigService.java
api/src/main/java/com/alibaba/nacos/api/config/ConfigType.java
client/src/main/java/com/alibaba/nacos/client/config/NacosConfigService.java
config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigController.java

[ISSUE #3907] when publishConfig, if type is absent, set default value 'text'

---

console/src/main/resources/application.properties
distribution/conf/application.properties
distribution/conf/application.properties.example

For-#4179, add index for db.user and db.password, to avoid some situation that it contains symbol `,`.

[ISSUE-#4179] Add index for db.user and db.password

---

api/src/main/java/com/alibaba/nacos/api/naming/utils/NamingUtils.java
naming/src/main/java/com/alibaba/nacos/naming/web/DistroFilter.java

[ISSUE-#4192] Move relation doc info to naming module.

---

config/pom.xml
config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedStoragePersistServiceImpl.java
pom.xml

[ISSUE #3102]Remove lang dependency. Keep lang3.
XX
XXXX

[ISSUE #3102] remove lang dependency.

---

core/src/main/java/com/alibaba/nacos/core/code/ControllerMethodsCache.java
sys/src/main/java/com/alibaba/nacos/sys/utils/ApplicationUtils.java
test/src/test/java/com/alibaba/nacos/test/core/code/ControllerMethodsCacheTest.java

#4181 
I think if  `server.servlet.contextPath=/`  then `ApplicationUtils.getContextPath()` should return ""
1.  adjust url replace logic in `ControllerMethodsCache.getMethod()`
2. adjust the `ApplicationUtils.getContextPath()` logic 
TODO 
Adjust the usage logic related to contextPath
XXXX

[ISSUE-#4181] Fix errors related to custom contextPath

---

naming/src/main/java/com/alibaba/nacos/naming/misc/HttpClient.java

fix #4199 
Replace the http client used by the `HttpClient#request` method with apache http client
XXXX

[ISSUE #4199] Replace the http client implementation used by DistroFilter

---

client/src/main/java/com/alibaba/nacos/client/config/impl/ConfigTransportClient.java
common/src/main/java/com/alibaba/nacos/common/remote/client/rsocket/RsocketUtils.java
config/src/main/java/com/alibaba/nacos/config/server/model/event/LocalDataChangeEvent.java
config/src/main/java/com/alibaba/nacos/config/server/remote/RpcConfigChangeNotifier.java
config/src/main/java/com/alibaba/nacos/config/server/service/trace/ConfigTraceService.java
console/src/main/java/com/alibaba/nacos/console/controller/ServerLoaderController.java
core/src/main/java/com/alibaba/nacos/core/remote/core/ServerReloaderRequestHandler.java
core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcBiStreamRequestAcceptor.java
core/src/main/java/com/alibaba/nacos/core/utils/RemoteUtils.java
core/src/main/java/com/alibaba/nacos/core/utils/StringPool.java

For pmd ,checkstyle

---

console/src/main/resources/application.properties
naming/src/main/java/com/alibaba/nacos/naming/controllers/ServiceController.java
naming/src/main/java/com/alibaba/nacos/naming/core/ServiceOperator.java
naming/src/main/java/com/alibaba/nacos/naming/core/ServiceOperatorV1Impl.java
naming/src/main/java/com/alibaba/nacos/naming/core/ServiceOperatorV2Impl.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/NamingMetadataOperateService.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/ServiceMetadataProcessor.java

 Adapt update service metadata api.

---

sys/src/main/java/com/alibaba/nacos/sys/env/EnvUtil.java

[ISSUE-#4264] Fix always load property when the contextPath is '/'

---

api/src/main/java/com/alibaba/nacos/api/naming/pojo/ServiceInfo.java
api/src/test/java/com/alibaba/nacos/api/naming/pojo/ServiceInfoTest.java
client/src/test/java/com/alibaba/nacos/client/naming/cache/DiskCacheTest.java

#4136 
conversation about :
#4183 
#4249 
I cann't use rebase to fix the PR of #4249 ,then i open a new PR

[ISSUE #4136] Fix the bug that cann't correctlly instantiate ServiceInfo from cache file

---

sys/src/main/java/com/alibaba/nacos/sys/env/EnvUtil.java

Fix twice invoke and the value is not same.

---

api/src/main/java/com/alibaba/nacos/api/naming/remote/request/SubscribeServiceRequest.java
api/src/main/java/com/alibaba/nacos/api/selector/SelectorType.java
client/src/main/java/com/alibaba/nacos/client/naming/remote/NamingClientProxyDelegate.java
client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc/NamingGrpcClientProxy.java
naming/src/main/java/com/alibaba/nacos/naming/core/CatalogServiceV2Impl.java
naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperatorClientImpl.java
naming/src/main/java/com/alibaba/nacos/naming/push/v2/UdpPushExecuteServiceImpl.java
naming/src/main/java/com/alibaba/nacos/naming/push/v2/task/PushExecuteTask.java
naming/src/main/java/com/alibaba/nacos/naming/remote/handler/ServiceQueryRequestHandler.java
naming/src/main/java/com/alibaba/nacos/naming/remote/handler/SubscribeServiceRequestHandler.java
naming/src/main/java/com/alibaba/nacos/naming/selector/LabelSelector.java
naming/src/main/java/com/alibaba/nacos/naming/selector/NoneSelector.java
naming/src/main/java/com/alibaba/nacos/naming/selector/Selector.java
naming/src/main/java/com/alibaba/nacos/naming/utils/ServiceUtil.java

Fix some push problem

---

common/src/main/java/com/alibaba/nacos/common/utils/NamespaceUtil.java
common/src/test/java/com/alibaba/nacos/common/utils/NamespaceUtilTest.java
config/src/main/java/com/alibaba/nacos/config/server/auth/ConfigResourceParser.java
config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigController.java
config/src/test/java/com/alibaba/nacos/config/server/utils/NamespaceUtilTest.java
naming/src/main/java/com/alibaba/nacos/naming/web/NamingResourceParser.java

[ISSUE-#4262] Fix public namespace permission problem

---

config/src/main/java/com/alibaba/nacos/config/server/utils/PropertyUtil.java
config/src/test/java/com/alibaba/nacos/config/server/model/ConfigInfoTest.java
core/src/main/java/com/alibaba/nacos/core/code/LoggingSpringApplicationRunListener.java
core/src/main/java/com/alibaba/nacos/core/code/StandaloneProfileApplicationListener.java
core/src/main/java/com/alibaba/nacos/core/code/StartingSpringApplicationRunListener.java
core/src/test/java/com/alibaba/nacos/core/cluster/MemberUtilsTest.java
core/src/test/java/com/alibaba/nacos/core/cluster/ServerMemberManagerTest.java
core/src/test/java/com/alibaba/nacos/core/distributed/raft/JRaftServerTest.java
naming/src/test/java/com/alibaba/nacos/naming/BaseTest.java
naming/src/test/java/com/alibaba/nacos/naming/consistency/persistent/ClusterVersionJudgementTest.java
naming/src/test/java/com/alibaba/nacos/naming/consistency/persistent/impl/NamingSnapshotOperationTest.java
naming/src/test/java/com/alibaba/nacos/naming/consistency/persistent/raft/RaftPeerSetTest.java
test/src/test/java/com/alibaba/nacos/test/core/SnowFlowerIdGenerator_ITCase.java
test/src/test/java/com/alibaba/nacos/test/core/cluster/MemberLookup_ITCase.java
test/src/test/java/com/alibaba/nacos/test/core/cluster/ServerMemberManager_ITCase.java

[ISSUE-#4294] Use EnvUtils.setEnvironment to replace ApplicationUtils.injectEnvironment

---

sys/src/main/java/com/alibaba/nacos/sys/utils/ApplicationUtils.java

[ISSUE-#4293] Remove env operation code in ApplicationUtils

---

core/src/main/java/com/alibaba/nacos/core/auth/AuthFilter.java

[ISSUE-#4286] When auth open, use resource parser cache to parse resource

---

config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedStoragePersistServiceImpl.java

fix: #4311 
Modify `EmbeddedStoragePersistServiceImpl` `getTenantIdList` and `getGroupIdList` method, in order to support the `Derby` data source.
Locally validated.

[ISSUE #4311] Fix Derby data source related SQL LIMIT exception

---

console/src/main/java/com/alibaba/nacos/console/utils/PasswordEncoderUtil.java

Delete the main function only for testing

[ISSUE-#4310] Delete the main function only for testing

---

sys/src/main/java/com/alibaba/nacos/sys/env/EnvUtil.java

[ISSUE-#4258]  Fix wrong path when -Dspring.config.location not set

---

core/src/main/java/com/alibaba/nacos/core/distributed/raft/RaftSysConstants.java
core/src/main/java/com/alibaba/nacos/core/distributed/raft/utils/RaftOptionsBuilder.java

[ISSUE-#4342] Fix nacos.core.protocol.raft.data.read_index_type isn't effect

---

api/src/main/java/com/alibaba/nacos/api/naming/utils/NamingUtils.java
api/src/test/java/com/alibaba/nacos/api/naming/utils/NamingUtilsTest.java
config/src/main/java/com/alibaba/nacos/config/server/service/repository/RowMapperManager.java
config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedStoragePersistServiceImpl.java
core/src/main/java/com/alibaba/nacos/core/distributed/raft/RaftSysConstants.java
core/src/main/java/com/alibaba/nacos/core/distributed/raft/utils/RaftOptionsBuilder.java
naming/src/main/java/com/alibaba/nacos/naming/controllers/CatalogController.java
pom.xml
sys/src/main/java/com/alibaba/nacos/sys/env/EnvUtil.java

Synchronize code from develop

---

naming/src/main/java/com/alibaba/nacos/naming/core/ServiceManager.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/cleaner/AbstractNamingCleaner.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/cleaner/EmptyServiceAutoCleaner.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/cleaner/EmptyServiceAutoCleanerV2.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/cleaner/ExpiredMetadataCleaner.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/cleaner/NamingCleaner.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/AbstractClient.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/Client.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/event/metadata/MetadataEvent.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/event/service/ServiceEvent.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/index/ClientServiceIndexesManager.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/ExpiredMetadataInfo.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/InstanceMetadataProcessor.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/NamingMetadataManager.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/impl/EphemeralClientOperationServiceImpl.java

Refactor auto cleaner to adapt clean metadata
- Refactor and move old EmptyServiceAutoCleaner
- Add Auto clean expired metadata
XXXX

Refactor auto cleaner to adapt clean metadata

---

config/src/main/java/com/alibaba/nacos/config/server/controller/CapacityController.java
config/src/main/java/com/alibaba/nacos/config/server/service/capacity/CapacityService.java
config/src/main/java/com/alibaba/nacos/config/server/service/capacity/EmbeddedStorageGroupCapacityPersistServiceImpl.java
config/src/main/java/com/alibaba/nacos/config/server/service/capacity/EmbeddedStorageTenantCapacityPersistServiceImpl.java
config/src/main/java/com/alibaba/nacos/config/server/service/capacity/ExternalStorageGroupCapacityPersistServiceImpl.java
config/src/main/java/com/alibaba/nacos/config/server/service/capacity/ExternalStorageTenantCapacityPersistServiceImpl.java
config/src/main/java/com/alibaba/nacos/config/server/service/capacity/GroupCapacityPersistService.java
config/src/main/java/com/alibaba/nacos/config/server/service/capacity/TenantCapacityPersistService.java
config/src/main/java/com/alibaba/nacos/config/server/service/repository/RowMapperManager.java

using the external data source start nacos GroupCapacityPersistService and TenantCapacityPersistService JDBC implementation only supports embedded database. So it will not work properly.
- For TenantCapacityPersistService and GroupCapacityPersistService Jpa implementation.
- Load different implementations according to the data source type.
XXXX

Fixed external data source startup exception

---

naming/src/main/java/com/alibaba/nacos/naming/core/v2/ServiceManager.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/cleaner/EmptyServiceAutoCleanerV2.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/event/service/ServiceEvent.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/index/ClientServiceIndexesManager.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/ExpiredMetadataInfo.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/NamingMetadataManager.java

Add the function of automatically clearing empty services

---

core/src/main/java/com/alibaba/nacos/core/listener/StartingApplicationListener.java
test/src/test/java/com/alibaba/nacos/test/config/ConfigExportAndImportAPI_CITCase.java
test/src/test/java/com/alibaba/nacos/test/naming/RegisterInstance_ITCase.java

[ISSUE-#4346] Fix import code

---

client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingService.java
client/src/main/java/com/alibaba/nacos/client/naming/cache/ServiceInfoHolder.java
client/src/main/java/com/alibaba/nacos/client/naming/core/ServiceInfoUpdateService.java
client/src/main/java/com/alibaba/nacos/client/naming/event/InstancesChangeNotifier.java
core/src/main/java/com/alibaba/nacos/core/remote/ClientConnectionEventListenerRegistry.java
naming/src/main/java/com/alibaba/nacos/naming/controllers/InstanceController.java
naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperatorServiceImpl.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/ServiceManager.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/cleaner/EmptyServiceAutoCleanerV2.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/cleaner/ExpiredMetadataCleaner.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/index/ClientServiceIndexesManager.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/index/ServiceStorage.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/NamingMetadataManager.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/pojo/InstancePublishInfo.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/impl/EphemeralClientOperationServiceImpl.java
naming/src/main/java/com/alibaba/nacos/naming/healthcheck/heartbeat/ExpiredInstanceChecker.java
naming/src/main/java/com/alibaba/nacos/naming/healthcheck/heartbeat/InstanceEnableBeatCheckInterceptor.java
naming/src/main/java/com/alibaba/nacos/naming/healthcheck/heartbeat/UnhealthyInstanceChecker.java
naming/src/main/java/com/alibaba/nacos/naming/pojo/Subscriber.java
naming/src/main/java/com/alibaba/nacos/naming/push/v2/task/PushExecuteTask.java
naming/src/main/java/com/alibaba/nacos/naming/remote/handler/SubscribeServiceRequestHandler.java

XXXXX
- use instance id get instance metadata
- Fix Disconnection can't notify to naming module.
- Support subscribe specified cluster instance for 1.x
- Fix 2.0 client subscribe service can't be notify problem
- Fix only can search the first service problem
-Fix auto clean empty service can't work problem
XXXX

Fix some bugs for naming module

---

core/src/main/java/com/alibaba/nacos/core/distributed/raft/JRaftServer.java

[ISSUE-#4374] Reuse cliClientService 

---

api/pom.xml
client/pom.xml

Upgrade Nacos Api/Client modules to support JDK 1.8 compilation

---

naming/src/main/java/com/alibaba/nacos/naming/controllers/InstanceController.java
naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperator.java
naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperatorClientImpl.java
naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperatorServiceImpl.java
naming/src/main/java/com/alibaba/nacos/naming/web/DistroFilter.java
naming/src/main/java/com/alibaba/nacos/naming/web/DistroIpPortTagGenerator.java
naming/src/main/java/com/alibaba/nacos/naming/web/DistroServiceNameTagGenerator.java
naming/src/main/java/com/alibaba/nacos/naming/web/DistroTagGenerator.java
naming/src/main/java/com/alibaba/nacos/naming/web/DistroTagGeneratorImpl.java
naming/src/main/java/com/alibaba/nacos/naming/web/NamingConfig.java
naming/src/main/java/com/alibaba/nacos/naming/web/ServiceNameFilter.java

Fix 1.X openAPI query can't auto add default group problem

---

naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperatorServiceImpl.java
naming/src/main/java/com/alibaba/nacos/naming/web/DistroFilter.java

For checkstyle

---

naming/src/main/java/com/alibaba/nacos/naming/controllers/ServiceController.java
naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperatorClientImpl.java
naming/src/main/java/com/alibaba/nacos/naming/core/ServiceOperator.java
naming/src/main/java/com/alibaba/nacos/naming/core/ServiceOperatorV1Impl.java
naming/src/main/java/com/alibaba/nacos/naming/core/ServiceOperatorV2Impl.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/event/metadata/MetadataEvent.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/impl/EphemeralClientOperationServiceImpl.java
naming/src/main/java/com/alibaba/nacos/naming/push/v2/task/PushExecuteTask.java
naming/src/main/java/com/alibaba/nacos/naming/remote/handler/ServiceListRequestHandler.java

Fix some compatible problem for 1.x client

---

sys/src/main/java/com/alibaba/nacos/sys/utils/DiskUtils.java

[ISSUE-#4401] When deleteFile, just check the file is exists.

---

config/src/main/java/com/alibaba/nacos/config/server/modules/mapstruct/ConfigInfoEntityMapStruct.java
config/src/main/java/com/alibaba/nacos/config/server/modules/mapstruct/ConfigKeyMapStruct.java
config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java

Perfect some code for multiple data source

---

core/src/main/java/com/alibaba/nacos/core/distributed/raft/utils/JRaftUtils.java

[ISSUE-#4393] Use PeerId.getEndpoint() to replace new Object

---

address/pom.xml
api/pom.xml
auth/pom.xml
client/pom.xml
cmdb/pom.xml
common/pom.xml
config/pom.xml
consistency/pom.xml
console/pom.xml
core/pom.xml
distribution/conf/application.properties
distribution/pom.xml
example/pom.xml
istio/pom.xml
naming/pom.xml
pom.xml
sys/pom.xml
test/pom.xml

Upgrade to 2.0.0-ALPHA.1

---

config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/DistributedDatabaseOperateImpl.java
consistency/src/main/java/com/alibaba/nacos/consistency/ConsistencyProtocol.java
core/src/main/java/com/alibaba/nacos/core/distributed/raft/JRaftProtocol.java
core/src/main/java/com/alibaba/nacos/core/distributed/raft/processor/NacosGetRequestProcessor.java
core/src/main/java/com/alibaba/nacos/core/distributed/raft/processor/NacosLogProcessor.java
core/src/main/java/com/alibaba/nacos/core/distributed/raft/processor/NacosReadRequestProcessor.java
core/src/main/java/com/alibaba/nacos/core/distributed/raft/processor/NacosWriteRequestProcessor.java
core/src/main/java/com/alibaba/nacos/core/distributed/raft/utils/JRaftUtils.java
naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/impl/PersistentServiceProcessor.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/InstanceMetadataProcessor.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/NamingMetadataOperateService.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/ServiceMetadataProcessor.java

fix: fix bug

---

config/src/main/java/com/alibaba/nacos/config/server/controller/HistoryController.java

Reverts alibaba/nacos#4413
This PR is for wrong branch.

Revert "[ISSUE #4412]: Update comment error"

---

config/src/main/java/com/alibaba/nacos/config/server/controller/HistoryController.java

#4412
Modify the types of pageNo and pageSize
XXXX

[ISSUE #4412]: Update comment error

---

config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/DistributedDatabaseOperateImpl.java
consistency/src/main/java/com/alibaba/nacos/consistency/ConsistencyProtocol.java
core/src/main/java/com/alibaba/nacos/core/distributed/raft/JRaftProtocol.java
core/src/main/java/com/alibaba/nacos/core/distributed/raft/processor/NacosGetRequestProcessor.java
core/src/main/java/com/alibaba/nacos/core/distributed/raft/processor/NacosLogProcessor.java
core/src/main/java/com/alibaba/nacos/core/distributed/raft/processor/NacosReadRequestProcessor.java
core/src/main/java/com/alibaba/nacos/core/distributed/raft/processor/NacosWriteRequestProcessor.java
core/src/main/java/com/alibaba/nacos/core/distributed/raft/utils/JRaftUtils.java
naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/impl/PersistentServiceProcessor.java
naming/src/main/java/com/alibaba/nacos/naming/controllers/ServiceController.java
naming/src/main/java/com/alibaba/nacos/naming/core/ServiceManager.java
naming/src/main/java/com/alibaba/nacos/naming/core/ServiceOperator.java
naming/src/main/java/com/alibaba/nacos/naming/core/ServiceOperatorV1Impl.java
naming/src/main/java/com/alibaba/nacos/naming/core/ServiceOperatorV2Impl.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/cleaner/ExpiredMetadataCleaner.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/index/ServiceStorage.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/InstanceMetadataProcessor.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/NamingMetadataManager.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/NamingMetadataOperateService.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/ServiceMetadata.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/ServiceMetadataProcessor.java
pom.xml

Adapt create service and delete service in ServiceController

---

core/src/main/java/com/alibaba/nacos/core/cluster/ServerMemberManager.java

[ISSUE-#4450] Fix memberAddressInfos not right problem when memberChange

---

sys/src/main/java/com/alibaba/nacos/sys/file/WatchFileCenter.java

[ISSUE #4415] fix NOW_WATCH_JOB_CNT record WatchDirJob count

---

naming/src/main/java/com/alibaba/nacos/naming/selector/LabelSelector.java

[ISSUE-#4436] Fix parse label expression error problem 

---

naming/src/main/java/com/alibaba/nacos/naming/controllers/ServiceController.java
naming/src/test/java/com/alibaba/nacos/naming/controllers/ServiceControllerTest.java

[ISSUE #4477] fix service/list fromIndex > toIndex

---

naming/src/main/java/com/alibaba/nacos/naming/core/ServiceManager.java

[ISSUE-#4467] Fix snowflake id problem

---

common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClientStatus.java
naming/src/main/java/com/alibaba/nacos/naming/misc/GlobalExecutor.java

Some description for RpcClientStatus is not right, fix it.

Fix RpcClientStatus description.

---

naming/src/main/java/com/alibaba/nacos/naming/core/CatalogServiceV2Impl.java

Fix #4489 
Fix can't query non-default-group problem for catalog API

[ISSUE #4489] Fix can't query non-default-group problem for catalog API

---

api/src/main/java/com/alibaba/nacos/api/remote/PayloadRegistry.java

split request and response package handle. reduce unnecessary scan operation.

Optimize PayloadRegistry#init

---

common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClient.java

reset retryTurns to 10 when it reach Integer.MAX.

Reset retryTurns when it reach Integer.MAX in RpcClient#switchServerAsync

---

api/src/main/java/com/alibaba/nacos/api/remote/PayloadRegistry.java
client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java
common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClient.java
naming/src/main/java/com/alibaba/nacos/naming/core/CatalogServiceV2Impl.java

Enhance log info and fix code checkstyle

Enhance log info and fix code checkstyle

---

naming/src/main/java/com/alibaba/nacos/naming/controllers/ServiceController.java

修复[#4424](https://github.com/alibaba/nacos/issues/4424)
当protectThreshold传入值为null时，给它设置一个默认值。
XXXX

[ISSUE #4424] Fixed issue where null values could not be converted to base parameters 

---

config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigOpsController.java

[ISSUE #4463] fix derbyOps interface security problem

---

api/src/main/java/com/alibaba/nacos/api/naming/utils/NamingUtils.java
client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingService.java

[ISSUE-#4513] Check instance illegal heart beat param before register

---

api/src/main/java/com/alibaba/nacos/api/config/remote/request/ConfigBatchListenRequest.java
api/src/main/java/com/alibaba/nacos/api/config/remote/request/ConfigQueryRequest.java
api/src/main/java/com/alibaba/nacos/api/remote/AbstractPushCallBack.java
api/src/main/java/com/alibaba/nacos/api/remote/DefaultRequestFuture.java
api/src/main/java/com/alibaba/nacos/api/remote/PayloadRegistry.java
api/src/main/java/com/alibaba/nacos/api/remote/PushCallBack.java
api/src/main/java/com/alibaba/nacos/api/remote/RequestCallBack.java
api/src/main/java/com/alibaba/nacos/api/remote/Requester.java
common/src/main/java/com/alibaba/nacos/common/remote/ConnectionType.java
common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClient.java
common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClientStatus.java
common/src/main/java/com/alibaba/nacos/common/remote/client/ServerRequestHandler.java
common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClient.java
config/src/main/java/com/alibaba/nacos/config/server/remote/RpcConfigChangeNotifier.java
core/src/main/java/com/alibaba/nacos/core/remote/RpcPushService.java
core/src/main/java/com/alibaba/nacos/core/remote/grpc/BaseGrpcServer.java
naming/src/main/java/com/alibaba/nacos/naming/remote/udp/UdpConnector.java

20201221 lzf grpc

---

core/src/main/java/com/alibaba/nacos/core/remote/BaseRpcServer.java
core/src/main/java/com/alibaba/nacos/core/remote/grpc/BaseGrpcServer.java
core/src/main/java/com/alibaba/nacos/core/remote/rsocket/RsocketRpcServer.java
naming/src/test/java/com/alibaba/nacos/naming/push/v2/executor/PushExecutorDelegateTest.java
naming/src/test/java/com/alibaba/nacos/naming/push/v2/executor/PushExecutorRpcImplTest.java
naming/src/test/java/com/alibaba/nacos/naming/push/v2/executor/PushExecutorUdpImplTest.java
naming/src/test/java/com/alibaba/nacos/naming/push/v2/task/FixturePushExecutor.java
naming/src/test/java/com/alibaba/nacos/naming/push/v2/task/PushDelayTaskExecuteEngineTest.java

Fix some typo and code enhance.

Fix some typo and code enhance.

---

config/src/main/java/com/alibaba/nacos/config/server/modules/entity/ConfigInfoEntity.java
config/src/main/java/com/alibaba/nacos/config/server/modules/entity/HisConfigInfoEntity.java
config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java

Fixed some issues with Config persistence

---

config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java

Add some missing method code

---

api/src/main/java/com/alibaba/nacos/api/PropertyKeyConst.java
client/src/main/java/com/alibaba/nacos/client/naming/net/NamingProxy.java

fix https://github.com/alibaba/nacos/issues/4583
fix namingProxy domain retry logic; 
add retry param namingRequestDomainCount

[ISSUE #4583] Fix DOMAIN mode retry logic

---

config/src/main/java/com/alibaba/nacos/config/server/model/ConfigAllInfo.java

#4570
I find HessianSerializer hava a bug, when the subclass and the parent class have the same attributes, HessianSerializer deserialize will lose these attributes. You can try this: 
```
@Test
public void testHessianSerializer(){
HessianSerializer serializer = new HessianSerializer();
ConfigAllInfo configAllInfo = new ConfigAllInfo();
configAllInfo.setType("text");
configAllInfo.setEffect("effect");
byte[] bytes = serializer.serialize(configAllInfo);
ConfigAllInfo deserialize = serializer.deserialize(bytes);
Assert.assertNull(deserialize.getType());
Assert.assertNotNull(deserialize.getEffect());
}
```
So I remove com.alibaba.nacos.config.server.model.ConfigAllInfo#type, beacuse parent class ConfigInfo hava type too.
XX …

[ISSUE #4570]fix cluster mode query config type is null

---

client/src/main/java/com/alibaba/nacos/client/config/impl/CacheData.java
client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java
common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClient.java
common/src/main/java/com/alibaba/nacos/common/remote/client/rsocket/RsocketConnection.java
common/src/main/java/com/alibaba/nacos/common/remote/client/rsocket/RsocketRpcClient.java
config/src/main/java/com/alibaba/nacos/config/server/controller/CommunicationController.java
core/src/main/java/com/alibaba/nacos/core/auth/RemoteRequestAuthFilter.java
core/src/main/java/com/alibaba/nacos/core/remote/BaseRpcServer.java
core/src/main/java/com/alibaba/nacos/core/remote/grpc/BaseGrpcServer.java
core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcBiStreamRequestAcceptor.java
core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcConnection.java
core/src/main/java/com/alibaba/nacos/core/remote/rsocket/RsocketRpcServer.java

rpc config listen notify optimize;connection_id name optimize;listeners query bugfix;

---

core/src/main/java/com/alibaba/nacos/core/distributed/distro/component/DistroTransportAgent.java
core/src/main/java/com/alibaba/nacos/core/distributed/distro/entity/DistroKey.java
core/src/main/java/com/alibaba/nacos/core/distributed/distro/task/delay/DistroDelayTaskProcessor.java
core/src/main/java/com/alibaba/nacos/core/distributed/distro/task/execute/AbstractDistroExecuteTask.java
core/src/main/java/com/alibaba/nacos/core/distributed/distro/task/execute/DistroSyncChangeTask.java
core/src/main/java/com/alibaba/nacos/core/distributed/distro/task/execute/DistroSyncDeleteTask.java
naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/component/DistroHttpAgent.java
naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/v2/DistroClientTransportAgent.java

Execute Distro transport asynchronously.
Execute Distro transport asynchronously.

Execute Distro transport asynchronously.

---

naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/AbstractClient.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/impl/ConnectionBasedClient.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/impl/IpPortBasedClient.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/ClientManager.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/ClientManagerDelegate.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/BaseClientManager.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/ConnectionBasedClientManager.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/IpPortBasedClientManager.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/NoConnectionClientManager.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/ClientOperationService.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/ClientOperationServiceProxy.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/impl/EphemeralClientOperationServiceImpl.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/impl/PersistentClientOperationServiceImpl.java
naming/src/main/java/com/alibaba/nacos/naming/utils/Constants.java

refactor: 持久化实例

---

.gitignore
console-ui/src/pages/ConfigurationManagement/ConfigurationManagement/ConfigurationManagement.js

console-ui config排序优化

---

core/src/main/java/com/alibaba/nacos/core/distributed/raft/utils/JRaftUtils.java

[ISSUE #4643] fix jraft response instance

---

core/src/main/java/com/alibaba/nacos/core/cluster/Member.java

For #4291, support remove old raft metadata
XX
XXXX

For #4291, support remove old raft metadata

---

api/src/main/java/com/alibaba/nacos/api/remote/request/RequestMeta.java
common/src/main/java/com/alibaba/nacos/common/notify/NotifyCenter.java
common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClient.java
common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClient.java
common/src/main/java/com/alibaba/nacos/common/utils/AppNameUtils.java
config/src/main/java/com/alibaba/nacos/config/server/remote/RpcConfigChangeNotifier.java
core/src/main/java/com/alibaba/nacos/core/remote/ConnectionManager.java
core/src/main/java/com/alibaba/nacos/core/remote/ConnectionMetaInfo.java
core/src/main/java/com/alibaba/nacos/core/remote/event/ConnectionLimitRuleChangeEvent.java
core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcBiStreamRequestAcceptor.java
core/src/main/java/com/alibaba/nacos/core/remote/rsocket/RsocketRpcServer.java

onnectionLimitRule submit.client use same executor during different … 

---

console-ui/package.json

upgrade axios version to 0.21.1
XX
XXXX

upgrade axios version to 0.21.1

---

common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClient.java
naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/v2/DistroClientTransportAgent.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/cleaner/EmptyServiceAutoCleanerV2.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/AbstractClient.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/Client.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/impl/IpPortBasedClient.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/ConnectionBasedClientManager.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/EphemeralIpPortClientManager.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/PersistentIpPortClientManager.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/event/client/ClientEvent.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/event/client/ClientOperationEvent.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/event/metadata/MetadataEvent.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/event/service/ServiceEvent.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/index/ServiceStorage.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/ServiceMetadataProcessor.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/impl/EphemeralClientOperationServiceImpl.java
naming/src/main/java/com/alibaba/nacos/naming/monitor/PerformanceLoggerThread.java
naming/src/test/java/com/alibaba/nacos/naming/core/SubscribeManagerTest.java

Remove service cache data when service removed

---

naming/src/main/java/com/alibaba/nacos/naming/push/ClientInfo.java

Add CSharp Client

---

client/src/main/java/com/alibaba/nacos/client/naming/net/NamingProxy.java

[ISSUE-#4662] Just choose one between nacosDomain mode and servers mode.

---

common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClient.java
naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/v2/DistroClientComponentRegistry.java
naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/v2/DistroClientTaskFailedHandler.java
naming/src/main/java/com/alibaba/nacos/naming/remote/rpc/handler/InstanceRequestHandler.java
naming/src/main/java/com/alibaba/nacos/naming/remote/rpc/handler/ServiceListRequestHandler.java
naming/src/main/java/com/alibaba/nacos/naming/remote/rpc/handler/ServiceQueryRequestHandler.java
naming/src/main/java/com/alibaba/nacos/naming/remote/rpc/handler/SubscribeServiceRequestHandler.java

Add auth for naming rpc api and ix some bugs for 2.0.0
- Add auth for naming rpc api
- Fix Callback do not execute problem
- Fix client distro do not retry problem.
XXXX

Add auth for naming rpc api and ix some bugs for 2.0.0

---

naming/src/main/java/com/alibaba/nacos/naming/misc/SwitchDomain.java
naming/src/main/java/com/alibaba/nacos/naming/push/PushService.java

naming push service support CSharp client

naming push service support CSharp client

---

istio/src/main/java/com/alibaba/nacos/istio/misc/IstioConfig.java

[ISSUE #4429] Fix mcp  can't be open

---

config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/DistributedDatabaseOperateImpl.java
consistency/src/main/java/com/alibaba/nacos/consistency/ConsistencyProtocol.java
core/src/main/java/com/alibaba/nacos/core/distributed/raft/JRaftProtocol.java
core/src/main/java/com/alibaba/nacos/core/distributed/raft/processor/NacosGetRequestProcessor.java
core/src/main/java/com/alibaba/nacos/core/distributed/raft/processor/NacosLogProcessor.java
core/src/main/java/com/alibaba/nacos/core/distributed/raft/processor/NacosReadRequestProcessor.java
core/src/main/java/com/alibaba/nacos/core/distributed/raft/processor/NacosWriteRequestProcessor.java
core/src/main/java/com/alibaba/nacos/core/distributed/raft/utils/JRaftUtils.java
naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/impl/PersistentServiceProcessor.java

Fix jraft write request problem
Fix jraft write request problem
XXXX

Cherry-pick jraft write request problem from nacos2.0.0

---

api/src/main/java/com/alibaba/nacos/api/PropertyKeyConst.java
api/src/main/java/com/alibaba/nacos/api/naming/pojo/ServiceInfo.java
auth/src/main/java/com/alibaba/nacos/auth/common/AuthConfigs.java
auth/src/main/java/com/alibaba/nacos/auth/util/AuthHeaderUtil.java
client/src/main/java/com/alibaba/nacos/client/config/http/ServerHttpAgent.java
client/src/main/java/com/alibaba/nacos/client/config/impl/SpasAdapter.java
client/src/main/java/com/alibaba/nacos/client/identify/CredentialWatcher.java
client/src/main/java/com/alibaba/nacos/client/naming/cache/ServiceInfoHolder.java
client/src/main/java/com/alibaba/nacos/client/naming/remote/http/NamingHttpClientProxy.java
config/src/main/java/com/alibaba/nacos/config/server/service/notify/AsyncNotifyService.java
console-ui/package.json
core/src/main/java/com/alibaba/nacos/core/auth/AuthFilter.java
distribution/conf/application.properties
istio/src/main/java/com/alibaba/nacos/istio/misc/IstioConfig.java
naming/src/main/java/com/alibaba/nacos/naming/misc/HttpClient.java
naming/src/main/java/com/alibaba/nacos/naming/misc/NamingProxy.java
naming/src/main/java/com/alibaba/nacos/naming/misc/SwitchDomain.java
naming/src/main/java/com/alibaba/nacos/naming/push/UdpPushService.java
naming/src/main/java/com/alibaba/nacos/naming/push/v1/ClientInfo.java

Synchronize codes from develop.

---

address/pom.xml
api/pom.xml
auth/pom.xml
client/pom.xml
cmdb/pom.xml
common/pom.xml
config/pom.xml
consistency/pom.xml
console/pom.xml
core/pom.xml
distribution/pom.xml
example/pom.xml
istio/pom.xml
naming/pom.xml
pom.xml
sys/pom.xml
test/pom.xml

Upgrade to 1.4.1

---

console/src/main/java/com/alibaba/nacos/console/config/ConsoleConfig.java
console/src/main/resources/application.properties
core/src/main/java/com/alibaba/nacos/core/auth/AuthFilter.java
core/src/main/java/com/alibaba/nacos/core/code/ControllerMethodsCache.java

Fix #4701 (#4703)

---

address/pom.xml
api/pom.xml
auth/pom.xml
client/pom.xml
cmdb/pom.xml
common/pom.xml
config/pom.xml
consistency/pom.xml
console/pom.xml
core/pom.xml
distribution/pom.xml
example/pom.xml
istio/pom.xml
naming/pom.xml
pom.xml
sys/pom.xml
test/pom.xml

Use revision to set version and upgrade to 1.4.2-SNAPSHOT
XX
XXXX

Use revision to set version and upgrade to 1.4.2-SNAPSHOT

---

config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigServletInner.java
config/src/main/java/com/alibaba/nacos/config/server/service/ConfigCacheService.java

[ISSUE #4661]configServletInner#doGetConfig code optimization

---

config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigController.java
config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedStoragePersistServiceImpl.java
config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java

[ISSUE #4672]Fix cloning configuration last desc

---

naming/src/main/java/com/alibaba/nacos/naming/core/ServiceManager.java

[ISSUE-#4699] Fix metadata batch operation may delete instance problem.

---

address/pom.xml
api/pom.xml
api/src/main/java/com/alibaba/nacos/api/config/ConfigType.java
api/src/main/java/com/alibaba/nacos/api/config/annotation/NacosConfigListener.java
api/src/main/java/com/alibaba/nacos/api/config/annotation/NacosConfigurationProperties.java
auth/pom.xml
client/pom.xml
cmdb/pom.xml
common/pom.xml
config/pom.xml
config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigController.java
config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigServletInner.java
config/src/main/java/com/alibaba/nacos/config/server/service/ConfigCacheService.java
config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedStoragePersistServiceImpl.java
config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java
consistency/pom.xml
console/pom.xml
core/pom.xml
distribution/pom.xml
example/pom.xml
istio/pom.xml
naming/pom.xml
naming/src/main/java/com/alibaba/nacos/naming/core/ServiceManager.java
pom.xml
sys/pom.xml
test/pom.xml

Synchronize codes from develop branch

---

.gitignore
naming/src/main/java/com/alibaba/nacos/naming/core/ServiceOperatorV2Impl.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/pojo/HealthCheckInstancePublishInfo.java
naming/src/main/java/com/alibaba/nacos/naming/healthcheck/v2/HealthStatusSynchronizer.java
naming/src/main/java/com/alibaba/nacos/naming/healthcheck/v2/PersistentHealthStatusSynchronizer.java
naming/src/main/java/com/alibaba/nacos/naming/healthcheck/v2/processor/HealthCheckCommonV2.java

Sync health check status for persistent instance.

---

naming/src/main/java/com/alibaba/nacos/naming/controllers/ClusterController.java
naming/src/main/java/com/alibaba/nacos/naming/core/ClusterOperator.java
naming/src/main/java/com/alibaba/nacos/naming/core/ClusterOperatorV1Impl.java
naming/src/main/java/com/alibaba/nacos/naming/core/ClusterOperatorV2Impl.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/NamingMetadataOperateService.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/ServiceMetadataProcessor.java

Support update cluster metadata.

---

client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingMaintainService.java
client/src/main/java/com/alibaba/nacos/client/naming/remote/AbstractNamingClientProxy.java
client/src/main/java/com/alibaba/nacos/client/naming/remote/NamingClientProxyDelegate.java
client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc/NamingGrpcClientProxy.java
client/src/main/java/com/alibaba/nacos/client/naming/remote/http/NamingHttpClientProxy.java

Refactor naming client proxy to support auth

---

console-ui/src/pages/ServiceManagement/ServiceDetail/EditClusterDialog.js
core/src/main/java/com/alibaba/nacos/core/auth/AuthFilter.java
naming/src/main/java/com/alibaba/nacos/naming/controllers/ClusterController.java
naming/src/main/java/com/alibaba/nacos/naming/core/Cluster.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/ClusterMetadata.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/pojo/HealthCheckInstancePublishInfo.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/pojo/InstancePublishInfo.java
naming/src/main/java/com/alibaba/nacos/naming/healthcheck/HttpHealthCheckProcessor.java
naming/src/main/java/com/alibaba/nacos/naming/healthcheck/v2/processor/HttpHealthCheckProcessor.java
naming/src/main/java/com/alibaba/nacos/naming/healthcheck/v2/processor/MysqlHealthCheckProcessor.java

 Add Http and MySQL health check.

---

client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java
common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClient.java
core/src/main/java/com/alibaba/nacos/core/remote/ConnectionManager.java

connection manager ,active send interval increase

---

api/src/main/java/com/alibaba/nacos/api/common/Constants.java
client/src/main/java/com/alibaba/nacos/client/config/impl/CacheData.java
client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java
client/src/main/java/com/alibaba/nacos/client/config/utils/ParamUtils.java
common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClient.java
core/src/main/java/com/alibaba/nacos/core/remote/ConnectionManager.java
core/src/main/java/com/alibaba/nacos/core/remote/control/MatchMode.java
core/src/main/java/com/alibaba/nacos/core/remote/control/MiddleFuzzyMonitorKeyMatcher.java
core/src/main/java/com/alibaba/nacos/core/remote/control/MonitorKeyEqualMatcher.java
core/src/main/java/com/alibaba/nacos/core/remote/control/MonitorKeyMatcher.java
core/src/main/java/com/alibaba/nacos/core/remote/control/MonitorKeyMatcherValidator.java
core/src/main/java/com/alibaba/nacos/core/remote/control/MonitorKeyPostfixMatcher.java
core/src/main/java/com/alibaba/nacos/core/remote/control/MonitorKeyPrefixMatcher.java
core/src/main/java/com/alibaba/nacos/core/remote/control/TpsMonitorManager.java
core/src/main/java/com/alibaba/nacos/core/remote/control/TpsMonitorPoint.java
test/src/test/java/com/alibaba/nacos/test/remote/TpsMonitorManagerTest.java

fuzzy match support of tps control;remove http transport of client worker ; add internal executors of CacheData notifier

---

config/src/main/java/com/alibaba/nacos/config/server/utils/PropertyUtil.java

Fix 'useExternalDB' property initialization
XX
XXXX

Fix 'useExternalDB' property initialization

---

naming/src/main/java/com/alibaba/nacos/naming/misc/GlobalExecutor.java

[ISSUE-#4762] Naming health check thread num support user define it by self.

---

client/src/main/java/com/alibaba/nacos/client/naming/remote/NamingClientProxyDelegate.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/impl/IpPortBasedClient.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/ClientManagerDelegate.java
naming/src/test/java/com/alibaba/nacos/naming/core/v2/client/manager/ClientManagerDelegateTest.java
naming/src/test/java/com/alibaba/nacos/naming/core/v2/upgrade/UpgradeJudgementTest.java

[ISSUE#4788]Fix client id judgement error for ipv6

---

api/src/main/java/com/alibaba/nacos/api/config/ConfigService.java

fix addListener method comment [issues #4806](https://github.com/alibaba/nacos/issues/4806)
if provided -> if **not** provided

[ISSUE #4806]  fix addListener method comment 

---

naming/src/main/java/com/alibaba/nacos/naming/controllers/HealthController.java
naming/src/main/java/com/alibaba/nacos/naming/controllers/OperatorController.java
naming/src/main/java/com/alibaba/nacos/naming/controllers/ServiceController.java
naming/src/main/java/com/alibaba/nacos/naming/core/HealthOperator.java
naming/src/main/java/com/alibaba/nacos/naming/core/HealthOperatorV1Impl.java
naming/src/main/java/com/alibaba/nacos/naming/core/HealthOperatorV2Impl.java
naming/src/main/java/com/alibaba/nacos/naming/core/ServiceOperator.java
naming/src/main/java/com/alibaba/nacos/naming/core/ServiceOperatorV1Impl.java
naming/src/main/java/com/alibaba/nacos/naming/core/ServiceOperatorV2Impl.java
naming/src/main/java/com/alibaba/nacos/naming/monitor/MetricsMonitor.java
naming/src/main/java/com/alibaba/nacos/naming/web/DistroIpPortTagGenerator.java

Adapt some naming openAPI

---

config/src/main/java/com/alibaba/nacos/config/server/auth/ExternalPermissionPersistServiceImpl.java
config/src/main/java/com/alibaba/nacos/config/server/auth/ExternalRolePersistServiceImpl.java
config/src/main/java/com/alibaba/nacos/config/server/auth/ExternalUserPersistServiceImpl.java
config/src/main/java/com/alibaba/nacos/config/server/modules/mapstruct/ConfigHistoryInfoMapStruct.java
config/src/main/java/com/alibaba/nacos/config/server/modules/repository/PermissionsRepository.java
config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java

1. page starts from zero
2. user create failure
3. user delete failure
4. `ConfigHistoryInfoMapStruct`  attribute map
XX
XXXX

Fix multiple data source bug

---

config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java

use mapStruct replace `BeanUtils.copyProperties`
XX
XXXX

Use mapStruct replace beancopy

---

config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java

add `listGroupKeyMd5ByPage` implement
XX
XXXX

Add `listGroupKeyMd5ByPage` implement

---

common/src/main/java/com/alibaba/nacos/common/task/engine/NacosDelayTaskExecuteEngine.java
consistency/src/main/java/com/alibaba/nacos/consistency/ProtocolMetaData.java
naming/src/main/java/com/alibaba/nacos/naming/core/ServiceManager.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/UpgradeJudgement.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/doublewrite/delay/DoubleWriteEventListener.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/doublewrite/execute/AsyncServicesCheckTask.java
naming/src/main/java/com/alibaba/nacos/naming/misc/SwitchDomain.java
naming/src/main/java/com/alibaba/nacos/naming/misc/SwitchEntry.java
naming/src/main/java/com/alibaba/nacos/naming/misc/SwitchManager.java

Add switch to close double write in 2.0.0

---

consistency/src/main/java/com/alibaba/nacos/consistency/ProtocolMetaData.java

For check style

---

client/src/main/java/com/alibaba/nacos/client/naming/core/ServiceInfoUpdateService.java
common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClient.java
naming/src/main/java/com/alibaba/nacos/naming/monitor/NamingTpsMonitor.java
naming/src/main/java/com/alibaba/nacos/naming/monitor/TpsMonitorItem.java
naming/src/main/java/com/alibaba/nacos/naming/push/v2/task/PushExecuteTask.java
test/src/test/java/com/alibaba/nacos/test/remote/NamingTpsMonitorManagerTest.java

Add some enhancements

---

config/src/main/java/com/alibaba/nacos/config/server/auth/ConfigResourceParser.java

listen config auth bugfix

---

client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc/NamingGrpcClientProxy.java

Fix getSpasHeaders serviceName exception

---

naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/doublewrite/delay/ServiceChangeV1Task.java

Fix double write NPE

---

config/src/main/java/com/alibaba/nacos/config/server/configuration/datasource/DynamicDataSource.java

remove duplicate datasource check task
XX
XXXX

remove duplicate datasource check task

---

config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java

fix some error sql

---

naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/impl/BasePersistentServiceProcessor.java
naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/impl/PersistentServiceProcessor.java
naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/impl/StandalonePersistentServiceProcessor.java
naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/raft/RaftConsistencyServiceImpl.java
naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/raft/RaftListener.java
naming/src/main/java/com/alibaba/nacos/naming/constants/ClientConstants.java
naming/src/main/java/com/alibaba/nacos/naming/constants/Constants.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/factory/ClientFactory.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/factory/ClientFactoryHolder.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/factory/impl/ConnectionBasedClientFactory.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/factory/impl/EphemeralIpPortClientFactory.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/factory/impl/PersistentIpPortClientFactory.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/ConnectionBasedClientManager.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/EphemeralIpPortClientManager.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/InstanceMetadataProcessor.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/NamingMetadataOperateService.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/ServiceMetadataProcessor.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/ClientOperationService.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/impl/PersistentClientOperationServiceImpl.java
naming/src/main/java/com/alibaba/nacos/naming/misc/GlobalConfig.java
naming/src/main/java/com/alibaba/nacos/naming/push/UdpPushService.java
naming/src/main/java/com/alibaba/nacos/naming/remote/udp/UdpConnector.java
naming/src/main/java/com/alibaba/nacos/naming/utils/InstanceUtil.java
naming/src/main/resources/META-INF/services/com.alibaba.nacos.naming.core.v2.client.factory.ClientFactory

Add ClientFactory to extend client

---

naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/factory/ClientFactoryHolder.java

Fix NPE when client factory init

---

core/src/main/java/com/alibaba/nacos/core/controller/CoreOpsController.java

[ISSUE #4917] Raft ops interface add auth

---

naming/src/main/java/com/alibaba/nacos/naming/push/v2/executor/PushExecutorDelegate.java

Fix rpc push error for ipv6

---

naming/src/main/java/com/alibaba/nacos/naming/push/v2/executor/PushExecutorDelegate.java
naming/src/main/java/com/alibaba/nacos/naming/push/v2/executor/SpiImplPushExecutorHolder.java
naming/src/main/java/com/alibaba/nacos/naming/push/v2/executor/SpiPushExecutor.java

Add spi for PushExecutor to support extend

---

naming/src/main/java/com/alibaba/nacos/naming/push/v2/PushDataWrapper.java
naming/src/main/java/com/alibaba/nacos/naming/push/v2/executor/PushExecutor.java
naming/src/main/java/com/alibaba/nacos/naming/push/v2/executor/PushExecutorDelegate.java
naming/src/main/java/com/alibaba/nacos/naming/push/v2/executor/PushExecutorRpcImpl.java
naming/src/main/java/com/alibaba/nacos/naming/push/v2/executor/PushExecutorUdpImpl.java
naming/src/main/java/com/alibaba/nacos/naming/push/v2/task/PushExecuteTask.java

Wrapper push data make executors can do operation.

---

naming/src/main/java/com/alibaba/nacos/naming/push/v2/executor/PushExecutorDelegate.java
naming/src/test/java/com/alibaba/nacos/naming/push/v2/executor/PushExecutorDelegateTest.java
naming/src/test/java/com/alibaba/nacos/naming/push/v2/executor/PushExecutorRpcImplTest.java
naming/src/test/java/com/alibaba/nacos/naming/push/v2/executor/PushExecutorUdpImplTest.java
naming/src/test/java/com/alibaba/nacos/naming/push/v2/task/FixturePushExecutor.java
naming/src/test/java/com/alibaba/nacos/naming/push/v2/task/PushDelayTaskExecuteEngineTest.java
naming/src/test/java/com/alibaba/nacos/naming/push/v2/task/PushExecuteTaskTest.java

Add push unit test

---

distribution/conf/nacos-postgresql.sql

add postgresql init sql
XX
XXXX

Multiple datasource support postgresql init sql

---

naming/src/test/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/EphemeralIpPortClientManagerTest.java

add EphemeralIpPortClientManagerTest
XXXXX
XX
XXXX

Add EphemeralIpPortClientManager unit test

---

naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/v2/DistroClientDataProcessor.java
naming/src/main/java/com/alibaba/nacos/naming/constants/ClientConstants.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/ClientSyncAttributes.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/ClientSyncData.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/factory/ClientFactory.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/factory/ClientFactoryHolder.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/factory/impl/ConnectionBasedClientFactory.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/factory/impl/EphemeralIpPortClientFactory.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/factory/impl/PersistentIpPortClientFactory.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/ClientManager.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/ClientManagerDelegate.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/ConnectionBasedClientManager.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/EphemeralIpPortClientManager.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/PersistentIpPortClientManager.java
naming/src/test/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/EphemeralIpPortClientManagerTest.java

Add ClientSyncAttributes to sync some client metadata to other server.

---

naming/src/test/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/ConnectionBasedClientManagerTest.java
naming/src/test/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/PersistentIpPortClientManagerTest.java

Add unit tests for package com.alibaba.nacos.naming.core.v2.client.manager.impl
XXXXX
XX
XXXX

Add unit tests for package com.alibaba.nacos.naming.core.v2.client.manager.impl

---

common/src/main/java/com/alibaba/nacos/common/lifecycle/Closeable.java

`Closeable` interface remove 'public'
XX
XXXX

[ Code Quality] 'Closeable' interface remove 'public'

---

client/src/main/java/com/alibaba/nacos/client/config/NacosConfigService.java
client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java

 compatible with the reflection logic of Dubbo 2.7.X

---

naming/src/test/java/com/alibaba/nacos/naming/core/v2/client/impl/ConnectionBasedClientTest.java
naming/src/test/java/com/alibaba/nacos/naming/core/v2/client/impl/IpPortBasedClientTest.java

Add unit tests for package com.alibaba.nacos.naming.core.v2.client.impl

---

client/src/main/java/com/alibaba/nacos/client/logging/log4j2/Log4J2NacosLogging.java

a small  improvement for  Log4J2NacosLogging , return directly  when location is blank.
ref:  [LogbackNacosLogging.java](https://github.com/alibaba/nacos/blob/develop/client/src/main/java/com/alibaba/nacos/client/logging/logback/LogbackNacosLogging.java#L38)
XX
XXXX

Log4J2NacosLogging.loadConfiguration() return directly When location is blank

---

naming/src/main/java/com/alibaba/nacos/naming/push/v1/ClientInfo.java

Fix #4987
- Fix throw exception when build ClientInfo with empty user-agent.

For #4987, Fix throw exception when build ClientInfo with empty user-agent.

---

naming/src/main/java/com/alibaba/nacos/naming/utils/InstanceUtil.java

Fix #4989.
Fix throws NPE when some metadata value is null.

For #4989, fix throws NPE when some metadata value is null.

---

naming/src/main/java/com/alibaba/nacos/naming/core/v2/event/service/ServiceEvent.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/index/ClientServiceIndexesManager.java
naming/src/main/java/com/alibaba/nacos/naming/push/v2/NamingSubscriberServiceV2Impl.java
naming/src/main/java/com/alibaba/nacos/naming/push/v2/task/PushDelayTaskExecuteEngine.java
naming/src/test/java/com/alibaba/nacos/naming/push/v2/NamingSubscriberServiceV2ImplTest.java
naming/src/test/java/com/alibaba/nacos/naming/push/v2/task/PushDelayTaskExecuteEngineTest.java

Single push to client when client subscribe service.

---

core/src/main/java/com/alibaba/nacos/core/controller/CoreOpsController.java
core/src/main/java/com/alibaba/nacos/core/utils/Loggers.java

[ISSUE #4996]core add log change

---

naming/src/main/java/com/alibaba/nacos/naming/push/v1/NamingSubscriberServiceV1Impl.java

Fix #5001 
returns empty list when service has no subscribers.

Fix #5001. Returns empty list when service has no subscribers.

---

api/src/main/java/com/alibaba/nacos/api/ability/ServerAbilities.java
api/src/main/java/com/alibaba/nacos/api/ability/ServerRemoteAbility.java
api/src/main/java/com/alibaba/nacos/api/config/ServerConfigAbility.java
api/src/main/java/com/alibaba/nacos/api/naming/ServerNamingAbility.java
api/src/main/java/com/alibaba/nacos/api/remote/request/ConnectionSetupRequest.java
api/src/main/java/com/alibaba/nacos/api/utils/NetUtils.java
common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClient.java
config/src/main/java/com/alibaba/nacos/config/server/service/notify/AsyncNotifyService.java
core/src/main/java/com/alibaba/nacos/core/cluster/Member.java
core/src/main/java/com/alibaba/nacos/core/cluster/MemberUtil.java
core/src/main/java/com/alibaba/nacos/core/cluster/ServerMemberManager.java
core/src/main/java/com/alibaba/nacos/core/remote/ConnectionManager.java
core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcBiStreamRequestAcceptor.java

shutdown long connection where server rollback; use client submit client ip

---

core/src/main/java/com/alibaba/nacos/core/distributed/distro/DistroProtocol.java
core/src/main/java/com/alibaba/nacos/core/distributed/distro/component/DistroDataProcessor.java
core/src/main/java/com/alibaba/nacos/core/distributed/distro/component/DistroDataStorage.java
core/src/main/java/com/alibaba/nacos/core/distributed/distro/task/load/DistroLoadDataTask.java
core/src/main/java/com/alibaba/nacos/core/distributed/distro/task/verify/DistroVerifyExecuteTask.java
core/src/main/java/com/alibaba/nacos/core/distributed/distro/task/verify/DistroVerifyTask.java
core/src/main/java/com/alibaba/nacos/core/distributed/distro/task/verify/DistroVerifyTimedTask.java
naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/DistroConsistencyServiceImpl.java
naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/component/DistroDataStorageImpl.java
naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/v2/DistroClientDataProcessor.java
naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/v2/DistroClientTransportAgent.java
naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/v2/DistroClientVerifyInfo.java
naming/src/main/java/com/alibaba/nacos/naming/controllers/DistroController.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/event/client/ClientEvent.java
naming/src/main/java/com/alibaba/nacos/naming/remote/rpc/handler/DistroDataRequestHandler.java

Refactor and enhance for client distro protocol

---

client/src/main/java/com/alibaba/nacos/client/naming/core/ServiceInfoUpdateService.java

[Issue #5028]Fix `UpdateTask` some logic errors

---

api/src/main/java/com/alibaba/nacos/api/common/Constants.java
naming/src/main/java/com/alibaba/nacos/naming/core/ServiceManager.java

[ISSUE-#4306] StringJoiner should consider '@@'.

---

api/src/main/java/com/alibaba/nacos/api/naming/pojo/ServiceInfo.java
naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperatorClientImpl.java
naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperatorServiceImpl.java
naming/src/main/java/com/alibaba/nacos/naming/remote/rpc/handler/ServiceQueryRequestHandler.java
naming/src/main/java/com/alibaba/nacos/naming/utils/ServiceUtil.java

Fix #5054 
XXXXX
XX
XXXX
* [ x ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ x ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ x ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ x ] Write necessary unit-test to verify your logic correction, more mock a little better when cross …

[ISSUE #5054] Support naming instance list with healthy protection using service.protectionThreshold.

---

client/src/test/java/com/alibaba/nacos/client/config/common/GroupKeyTest.java

fix #5030 , improve test coverage from 94% to 98%
XX
XXXX

[ISSUE #5030] add ut for package com.alibaba.nacos.client.config.common

---

common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClient.java

Remove extra semicolons
XX
XXXX

[Code quality]Remove extra semicolons

---

api/src/main/java/com/alibaba/nacos/api/remote/PayloadRegistry.java
api/src/main/java/com/alibaba/nacos/api/remote/request/ConnectionSetupRequest.java
client/pom.xml
client/src/main/java/com/alibaba/nacos/client/config/filter/impl/ConfigFilterChainManager.java
common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClient.java
core/pom.xml
core/src/main/java/com/alibaba/nacos/core/cluster/MemberUtil.java
core/src/main/java/com/alibaba/nacos/core/remote/grpc/BaseGrpcServer.java
core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcBiStreamRequestAcceptor.java
pom.xml

shade client and using remote ip from header

---

client/src/test/java/com/alibaba/nacos/client/config/impl/ConfigChangeHandlerTest.java
client/src/test/java/com/alibaba/nacos/client/config/impl/PropertiesChangeParserTest.java
client/src/test/java/com/alibaba/nacos/client/config/impl/YmlChangeParserTest.java
client/src/test/java/com/alibaba/nacos/client/config/listener/impl/AbstractConfigChangeListenerTest.java
client/src/test/java/com/alibaba/nacos/client/config/listener/impl/PropertiesListenerTest.java

fix [ISSUE #5036]add ut for com.alibaba.nacos.client.config.listener
line coverage is 84%
XX
XXXX

[ISSUE #5036]add ut for com.alibaba.nacos.client.config.listener

---

config/src/main/java/com/alibaba/nacos/config/server/controller/CommunicationController.java

listener bugfix

---

naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/impl/NamingKvStorage.java

[ISSUE #4936]Enhance the message when NamingKvStorage#get error

---

naming/src/main/java/com/alibaba/nacos/naming/healthcheck/v2/processor/HttpHealthCheckProcessor.java
naming/src/main/java/com/alibaba/nacos/naming/healthcheck/v2/processor/MysqlHealthCheckProcessor.java
naming/src/main/java/com/alibaba/nacos/naming/healthcheck/v2/processor/TcpHealthCheckProcessor.java

[ISSUE #5080] Fix health checker pre-start logic.

---

naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperatorClientImpl.java
naming/src/main/java/com/alibaba/nacos/naming/remote/rpc/handler/ServiceQueryRequestHandler.java
naming/src/main/java/com/alibaba/nacos/naming/utils/ServiceUtil.java

[ISSUE #5070] Fix catalog instance listing, make selectInstancesWithHealthyProtection isolated.

---

naming/src/main/java/com/alibaba/nacos/naming/controllers/OperatorController.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/AbstractClient.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/impl/IpPortBasedClient.java
naming/src/main/java/com/alibaba/nacos/naming/monitor/MetricsMonitor.java
naming/src/main/java/com/alibaba/nacos/naming/monitor/PerformanceLoggerThread.java
naming/src/main/java/com/alibaba/nacos/naming/push/v2/hook/NacosMonitorPushResultHook.java
naming/src/main/java/com/alibaba/nacos/naming/push/v2/hook/PushResult.java
naming/src/main/java/com/alibaba/nacos/naming/push/v2/hook/PushResultHook.java
naming/src/main/java/com/alibaba/nacos/naming/push/v2/hook/PushResultHookHolder.java
naming/src/main/java/com/alibaba/nacos/naming/push/v2/task/PushExecuteTask.java
naming/src/main/resources/META-INF/services/com.alibaba.nacos.naming.push.v2.hook.PushResultHook

XXXXX
- Add subscribe count monitor.
- Use hook to monitor and report push result.
- Fix ip count monitor will become negative number
XXXX

Use hook to monitor and report push result.

---

console-ui/src/pages/ServiceManagement/ServiceDetail/InstanceTable.js

[ISSUE #4898]Fix instance list page bug

---

client/src/test/java/com/alibaba/nacos/client/config/impl/CacheDataTest.java
client/src/test/java/com/alibaba/nacos/client/config/impl/ClientWorkerTest.java
client/src/test/java/com/alibaba/nacos/client/config/impl/ConfigHttpClientManagerTest.java
client/src/test/java/com/alibaba/nacos/client/config/impl/LimiterTest.java
client/src/test/java/com/alibaba/nacos/client/config/impl/ServerListManagerTest.java
client/src/test/java/com/alibaba/nacos/client/config/impl/SpasAdapterTest.java
client/src/test/java/com/alibaba/nacos/client/config/impl/YmlChangeParserTest.java

fix [ISSUE #5103] add ut for package com.alibaba.nacos.client.config.impl
line coverage 60%   
XX
XXXX

[ISSUE #5103] add ut for package com.alibaba.nacos.client.config.impl

---

README.md

readme: use https links

---

core/src/main/java/com/alibaba/nacos/core/storage/kv/KvStorage.java
naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/impl/NamingKvStorage.java

[Code quality] perfect KvStorage doc

---

client/src/test/java/com/alibaba/nacos/client/config/NacosConfigServiceTest.java

fix [ISSUE #5117]add ut for package com.alibaba.nacos.client.config other class
line coverage 77%
XX
XXXX

[ISSUE #5117]add ut for package com.alibaba.nacos.client.config other class

---

common/src/main/java/com/alibaba/nacos/common/utils/ConcurrentHashSet.java

[ISSUE #5114]Fix `ConcurrentHashSet` compatibility problems

---

pom.xml

[#4822,#4823,#4824,#4825,#4979] 
- Fix dependency security problem.
XXXX

[#4822,#4823,#4824,#4825,#4979] Fix dependency security problem.

---

naming/src/main/java/com/alibaba/nacos/naming/core/Service.java

Fix #4829.
-Remove instance when distro and raft remove instances data.
XXXX

[ISSUE#4829] Remove instance when distro and raft remove instances data.

---

naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/impl/PersistentServiceProcessor.java

[#4573,#4629] 
- Try to fix jraft leader status check error.
XXXX

[#4573,#4629] Jraft leader status check error.

---

common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClient.java

remote reconnect bugfix

---

client/src/test/java/com/alibaba/nacos/client/naming/backups/FailoverReactorTest.java

[ISSUE #5148] add ut for package c.a.nacos.client.naming.backups

---

client/src/test/java/com/alibaba/nacos/client/naming/cache/ConcurrentDiskUtilTest.java
client/src/test/java/com/alibaba/nacos/client/naming/cache/DiskCacheTest.java
client/src/test/java/com/alibaba/nacos/client/naming/cache/ServiceInfoHolderTest.java

[ISSUE #5150]Add unit tests for package c.a.nacos.client.naming.cache in nacos 2.0

---

console-ui/src/locales/en-US.js
console-ui/src/locales/zh-CN.js
console-ui/src/pages/ServiceManagement/ServiceList/ServiceList.js
console-ui/src/pages/ServiceManagement/SubscriberList/SubscriberList.js

#5137
1. service list :
2. jump to the subscriber page
XX
XXXX

[ISSUE #5137]service list add view subscriber feat

---

client/src/main/java/com/alibaba/nacos/client/naming/core/ServerListManager.java

Fix #5178.
- Fix NPE when init server list failed.
XXXX

[ISSUE #5178] Fix NPE when init server list failed.

---

api/src/main/java/com/alibaba/nacos/api/naming/utils/NamingUtils.java

If a serviceName's groupName is empty, throw a exception to prevent it be register.

[ISSUE-#3779] GroupName can't be empty.

---

console-ui/build/webpack.prod.conf.js

fix #4852: main.js too large
XX
XXXX

fix #4852: main.js too large

---

client/src/test/java/com/alibaba/nacos/client/naming/event/InstancesChangeEventTest.java
client/src/test/java/com/alibaba/nacos/client/naming/event/InstancesChangeNotifierTest.java

[ISSUE #5152]Add unit tests for package c.a.nacos.client.naming.event in nacos 2.0

---

test/src/test/java/com/alibaba/nacos/test/naming/AutoDeregisterInstance_ITCase.java
test/src/test/java/com/alibaba/nacos/test/naming/CPInstancesAPI_ITCase.java
test/src/test/java/com/alibaba/nacos/test/naming/ClientBeat_ITCase.java
test/src/test/java/com/alibaba/nacos/test/naming/DeregisterInstance_ITCase.java
test/src/test/java/com/alibaba/nacos/test/naming/RegisterInstance_ITCase.java

[#5171] Too much Integration Tests in package com.alibaba.nacos.test.naming cannot pass, could you fix them?

---

console-ui/src/pages/ConfigurationManagement/ConfigurationManagement/ConfigurationManagement.js
console-ui/src/pages/ConfigurationManagement/HistoryRollback/HistoryRollback.js
console-ui/src/pages/ConfigurationManagement/ListeningToQuery/ListeningToQuery.js

#4756
1. The search problem is that both the history list and the configuration list get parameters from the url.
https://user-images.githubusercontent.com/43994656/112756030-d9ef8c80-9015-11eb-9a03-9e121dab2517.mov
2. The list needs to be refreshed after sorting
https://user-images.githubusercontent.com/43994656/112756073-01465980-9016-11eb-86c5-b1d389754a99.mov
XX
XXXX

[ISSUE #4756]Fix config list sort and search problem

---

client/src/main/java/com/alibaba/nacos/client/config/NacosConfigService.java
client/src/main/java/com/alibaba/nacos/client/config/common/GroupKey.java
client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java
client/src/test/java/com/alibaba/nacos/client/config/common/GroupKeyTest.java

[ISSUE #5018] check group and dataId in groupKey

---

naming/src/main/java/com/alibaba/nacos/naming/utils/ServiceUtil.java

Fix #5204 
- Fix query error when pageNo is larger than service number.
XXXX

[ISSUE #5204], Fix query error when pageNo is larger than service number.

---

common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClient.java
common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClient.java
common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcConnection.java
core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcBiStreamRequestAcceptor.java

fix thread pool

---

client/src/test/java/com/alibaba/nacos/client/naming/utils/CollectionUtilsTest.java
client/src/test/java/com/alibaba/nacos/client/naming/utils/GenericPollerTest.java
client/src/test/java/com/alibaba/nacos/client/naming/utils/InitUtilsTest.java
client/src/test/java/com/alibaba/nacos/client/naming/utils/NamingHttpUtilTest.java
client/src/test/java/com/alibaba/nacos/client/naming/utils/PairTest.java
client/src/test/java/com/alibaba/nacos/client/naming/utils/SignUtilTest.java

[ISSUE #5154]Add unit tests for package c.a.nacos.client.naming.utils in nacos 2.0

---

address/pom.xml
pom.xml

fix #5206 , enhance unit test lib.
XX
XXXX

[WIP][ISSUE #5206] upgrade mockito from 2.3.24 to 3.8.0

---

client/src/test/java/com/alibaba/nacos/client/naming/core/BalancerTest.java
client/src/test/java/com/alibaba/nacos/client/naming/core/ProtectModeTest.java
client/src/test/java/com/alibaba/nacos/client/naming/core/PushReceiverTest.java
client/src/test/java/com/alibaba/nacos/client/naming/core/ServerListManagerTest.java
client/src/test/java/com/alibaba/nacos/client/naming/core/ServiceInfoUpdateServiceTest.java

[ISSUE #5151] add ut for package c.a.nacos.client.naming.core

---

common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClient.java
core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcClusterServer.java
core/src/main/java/com/alibaba/nacos/core/utils/GlobalExecutor.java
core/src/main/java/com/alibaba/nacos/core/utils/RemoteUtils.java
naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/v2/DistroClientTransportAgent.java
naming/src/main/java/com/alibaba/nacos/naming/monitor/NamingTpsMonitor.java
naming/src/main/java/com/alibaba/nacos/naming/monitor/TpsMonitorItem.java
naming/src/main/java/com/alibaba/nacos/naming/push/v2/task/PushExecuteTask.java

Fix ThreadPool usage problem and add some monitor for distro

---

client/src/main/java/com/alibaba/nacos/client/config/NacosConfigService.java
client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java
client/src/main/java/com/alibaba/nacos/client/config/impl/ConfigTransportClient.java
client/src/test/java/com/alibaba/nacos/client/config/NacosConfigServiceTest.java
client/src/test/java/com/alibaba/nacos/client/config/impl/ClientWorkerTest.java

[ISSUE #5175] fix publishConfig lost type

---

client/src/main/java/com/alibaba/nacos/client/config/impl/CacheData.java
client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java

some method addListeners/removeListener/addCacheDataIfAbsent  without tenant is never used.
we could remove these to make class behavior more cleanly.
XX
XXXX

clean some inner method which is never used

---

common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClient.java

fix cluster reconnection bug.

---

api/src/main/java/com/alibaba/nacos/api/common/Constants.java
api/src/main/java/com/alibaba/nacos/api/naming/pojo/healthcheck/impl/Http.java
client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java
client/src/main/java/com/alibaba/nacos/client/naming/utils/Chooser.java
cmdb/src/main/java/com/alibaba/nacos/cmdb/service/CmdbReader.java
common/src/main/java/com/alibaba/nacos/common/utils/CollectionUtils.java
config/src/main/java/com/alibaba/nacos/config/server/aspect/CapacityManagementAspect.java
config/src/main/java/com/alibaba/nacos/config/server/controller/CapacityController.java
config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigController.java
config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigServletInner.java
config/src/main/java/com/alibaba/nacos/config/server/model/ConfigInfoBase.java
config/src/main/java/com/alibaba/nacos/config/server/model/ConfigInfoBaseEx.java
config/src/main/java/com/alibaba/nacos/config/server/service/ClientTrackService.java
config/src/main/java/com/alibaba/nacos/config/server/service/ConfigCacheService.java
config/src/main/java/com/alibaba/nacos/config/server/service/ConfigSubService.java
naming/src/main/java/com/alibaba/nacos/naming/controllers/ApiController.java
naming/src/main/java/com/alibaba/nacos/naming/controllers/CatalogController.java
naming/src/main/java/com/alibaba/nacos/naming/misc/UtilsAndCommons.java
naming/src/main/java/com/alibaba/nacos/naming/push/PushService.java
test/src/test/java/com/alibaba/nacos/test/config/ConfigAPI_CITCase.java

Fix some typo

---

README.md

Fix command under Windows
Delete “cmd”

Fix README command

---

naming/src/main/java/com/alibaba/nacos/naming/remote/rpc/handler/SubscribeServiceRequestHandler.java

[ISSUE#5268] fix subscriber app unknown

---

naming/src/main/java/com/alibaba/nacos/naming/remote/rpc/handler/SubscribeServiceRequestHandler.java

Reverts alibaba/nacos#5274
Reason Error branch
should be submit to `feature_support_grpc_core`

Revert "[ISSUE#5268] fix subscriber app unknown"

---

core/src/main/java/com/alibaba/nacos/core/distributed/raft/NacosClosure.java

Memory optimize. It's also like https://github.com/sofastack/sofa-jraft/pull/566

Memory optimize.

---

distribution/conf/application.properties
naming/src/main/java/com/alibaba/nacos/naming/constants/PushConstants.java
naming/src/main/java/com/alibaba/nacos/naming/push/v2/NamingSubscriberServiceV2Impl.java
naming/src/main/java/com/alibaba/nacos/naming/push/v2/PushConfig.java
naming/src/main/java/com/alibaba/nacos/naming/push/v2/hook/PushResult.java
naming/src/main/java/com/alibaba/nacos/naming/push/v2/task/PushExecuteTask.java
naming/src/test/java/com/alibaba/nacos/naming/controllers/ServiceControllerTest.java
naming/src/test/java/com/alibaba/nacos/naming/healthcheck/heartbeat/ClientBeatCheckTaskV2Test.java
naming/src/test/java/com/alibaba/nacos/naming/push/v2/task/PushExecuteTaskTest.java

Push support config some parameters

---

console-ui/src/pages/ConfigurationManagement/ConfigurationManagement/ConfigurationManagement.js

There are many unused methods, the adjustment should be removed.
XX
XXXX

[Code quality]Remove unused methods

---

console-ui/src/pages/ServiceManagement/SubscriberList/SubscriberList.js

[ISSUE #5277]Subscriber list servername add required

---

console-ui/src/components/NameSpaceList/NameSpaceList.js

[ISSUE #5331] Fix the mouse hovers over the margin in a pointer state and cannot be clicked
change the style of namespace.
change the style from margin to padding.
- start project.
- click the space of namespace，and make sure it can be click.

[ISSUE #5331] Fix the mouse hovers over the margin in a pointer state and cannot be clicked

---

auth/src/main/java/com/alibaba/nacos/auth/common/AuthSystemTypes.java
console/src/main/java/com/alibaba/nacos/console/controller/UserController.java
console/src/main/java/com/alibaba/nacos/console/security/nacos/LdapAuthenticationProvider.java
console/src/main/java/com/alibaba/nacos/console/security/nacos/NacosAuthConfig.java
console/src/main/java/com/alibaba/nacos/console/security/nacos/NacosAuthManager.java
console/src/main/resources/application.properties
distribution/conf/application.properties

support ldap login

---

istio/src/main/java/com/alibaba/nacos/istio/mcp/NacosMcpService.java

fix issue https://github.com/alibaba/nacos/issues/5301
XX
XXXX

[ISSUE #5301] Respond all kinds of collections for istio's request

---

naming/src/main/java/com/alibaba/nacos/naming/cluster/ServerStatusManager.java
naming/src/main/java/com/alibaba/nacos/naming/consistency/ConsistencyService.java
naming/src/main/java/com/alibaba/nacos/naming/consistency/DelegateConsistencyServiceImpl.java
naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/DistroConsistencyServiceImpl.java
naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/PersistentConsistencyServiceDelegateImpl.java
naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/impl/BasePersistentServiceProcessor.java
naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/impl/PersistentServiceProcessor.java
naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/impl/StandalonePersistentServiceProcessor.java
naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/raft/RaftConsistencyServiceImpl.java
naming/src/main/java/com/alibaba/nacos/naming/web/TrafficReviseFilter.java

[#5350] In version 1.4.1, modify the Server is Down prompt to the specific reason for the machine failure and send it to the user

---

naming/src/main/java/com/alibaba/nacos/naming/remote/rpc/handler/InstanceRequestHandler.java

check isUseGrpcFeatures() when register instance using GRPC protocol
For #5361
XXXX

[ISSUE #5361] check isUseGrpcFeatures() when register instance using GRPC protocol

---

common/src/main/java/com/alibaba/nacos/common/utils/MD5Utils.java

Modify the Chinese comments in MD5Utils to English
see #5370 
XXXXX
XX
XXXX
[ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
[ ] Format the pull request title like [ISSUE #123] Fix UnknownException when host config not exist. Each commit in the pull request should have a meaningful subject line and body.
[ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
[ ] Write necessary unit-test to …

[ISSUE #5370]Modify the Chinese comments in MD5Utils to English

---

client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java
client/src/main/java/com/alibaba/nacos/client/naming/utils/UtilAndComs.java
cmdb/src/main/java/com/alibaba/nacos/cmdb/utils/CmdbExecutor.java
common/src/main/java/com/alibaba/nacos/common/http/HttpClientConfig.java
common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClient.java
core/src/main/java/com/alibaba/nacos/core/utils/GlobalExecutor.java
naming/src/main/java/com/alibaba/nacos/naming/cluster/ServerListManager.java
naming/src/main/java/com/alibaba/nacos/naming/healthcheck/TcpSuperSenseProcessor.java
naming/src/main/java/com/alibaba/nacos/naming/healthcheck/v2/processor/TcpHealthCheckProcessor.java
naming/src/main/java/com/alibaba/nacos/naming/misc/GlobalExecutor.java
naming/src/main/java/com/alibaba/nacos/naming/misc/HttpClientManager.java
naming/src/main/java/com/alibaba/nacos/naming/misc/UtilsAndCommons.java
sys/src/main/java/com/alibaba/nacos/sys/env/Constants.java
sys/src/main/java/com/alibaba/nacos/sys/env/EnvUtil.java
sys/src/test/java/com/alibaba/nacos/sys/env/EnvUtilWithConfigTest.java
sys/src/test/java/com/alibaba/nacos/sys/env/EnvUtilWithoutConfigTest.java
sys/src/test/resources/application-empty.properties
sys/src/test/resources/application-test.properties

Use ThreadUtil and EnvUtil replace Runtime.availableProcessor

---

core/src/test/java/com/alibaba/nacos/core/distributed/raft/JRaftProtocolTest.java

fix #5393 in nacos2
XXXXX
XX
XXXX

[#5393] The class core.distributed.raft.JRaftProtocol lacks a lot of Unit Tests in nacos2.

---

core/src/test/java/com/alibaba/nacos/core/distributed/raft/JRaftServerTest.java

fix #5353 in nacos2
XXXXX
XX
XXXX

[#5353] The class core.distributed.raft.JRaftServer lacks a lot of Unit Tests in nacos2.0.

---

example/src/main/java/com/alibaba/nacos/example/NamingExample.java

Add the explain of running NameingExample.
XX
XXXX

Add the explain of running NamingExample

---

common/src/main/java/com/alibaba/nacos/common/utils/IPUtil.java
common/src/test/java/com/alibaba/nacos/common/utils/IPUtilTest.java

add unit test case
fix 127.100.19 is a legal ip
unit test pass

[ISSUE #5390] Fix ip verify error

---

naming/src/main/java/com/alibaba/nacos/naming/core/v2/index/ClientServiceIndexesManager.java

For #5404, Fix frequently udp push for client 1.X

---

client/src/main/java/com/alibaba/nacos/client/naming/beat/BeatReactor.java

[ISSUE #5291]Enhancement BeatTask always execute

---

client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java

Fixes #5384 
make the config listen task to response the shutdownNow of thread pool.
XX
XXXX

[ISSUE #5384] 客户端ConfigService关闭无效处理

---

api/src/main/java/com/alibaba/nacos/api/common/Constants.java
api/src/main/java/com/alibaba/nacos/api/config/filter/AbstractConfigFilter.java
api/src/main/java/com/alibaba/nacos/api/config/filter/IConfigFilter.java
api/src/main/java/com/alibaba/nacos/api/config/filter/IConfigRequest.java
api/src/main/java/com/alibaba/nacos/api/config/filter/IFilterConfig.java
client/src/main/java/com/alibaba/nacos/client/config/NacosConfigService.java
client/src/main/java/com/alibaba/nacos/client/config/filter/impl/ConfigFilterChainManager.java
client/src/main/java/com/alibaba/nacos/client/config/filter/impl/ConfigRequest.java
client/src/main/java/com/alibaba/nacos/client/config/filter/impl/ConfigResponse.java
client/src/main/java/com/alibaba/nacos/client/config/impl/CacheData.java
client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java
client/src/main/java/com/alibaba/nacos/client/config/impl/LocalConfigInfoProcessor.java
client/src/main/java/com/alibaba/nacos/client/config/impl/LocalEncryptedDataKeyProcessor.java
pom.xml

Provide SPI to pre/post-process the config
See #5367 .
* Introduce the SPI `com.alibaba.nacos.api.NacosExtension`.
* user can custom the `NacosExtension` to pre/post-process the config

[ISSUE #5367]配置加密SPI

---

naming/src/main/java/com/alibaba/nacos/naming/web/NamingResourceParser.java
test/src/test/java/com/alibaba/nacos/test/core/auth/NamingAuth_ITCase.java
test/src/test/java/com/alibaba/nacos/test/core/auth/User_ITCase.java

Fix #5419 
- Get namespace from AbstractNamingRequest directly.

For #5419, Fix Nacos 2.0 client auth may invalid for non public namespace.

---

core/src/main/java/com/alibaba/nacos/core/distributed/raft/JRaftServer.java
core/src/main/java/com/alibaba/nacos/core/distributed/raft/utils/JRaftUtils.java

log.error(String a, Throwable b); 
the b won't be miatch {} in String `a`.

Fix error log mismatch {}.

---

client/src/main/java/com/alibaba/nacos/client/config/NacosConfigService.java
client/src/main/java/com/alibaba/nacos/client/config/impl/LocalEncryptedDataKeyProcessor.java

Fix IConfigFilter SPI:
1. call `configFilterChainManager.doFilter` only once pre request.
2. mkdir parentFile before write file.
---

Fix IConfigFilter SPI

---

naming/src/main/java/com/alibaba/nacos/naming/remote/rpc/filter/GrpcRequestFilter.java
naming/src/main/java/com/alibaba/nacos/naming/remote/rpc/handler/InstanceRequestHandler.java
naming/src/main/java/com/alibaba/nacos/naming/remote/rpc/handler/SubscribeServiceRequestHandler.java

As a supplement, I found that it's not only necessary to check whether the GRPC protocol is available when registering instances, but also when subscribing and unsubscribing services.
For #5361 
XXXX

[ISSUE #5361] check isUseGrpcFeatures() when subscribe service using GRPC

---

naming/src/main/java/com/alibaba/nacos/naming/cluster/ServerListManager.java

FIX #5442 
Change old version server state to UP when received status report from `server/status`.

[ISSUE #5442] change state to UP when received status form old version server

---

test/src/test/java/com/alibaba/nacos/test/naming/MultiTenant_InstanceAPI_ITCase.java
test/src/test/java/com/alibaba/nacos/test/naming/SelectInstances_ITCase.java
test/src/test/java/com/alibaba/nacos/test/naming/SelectOneHealthyInstance_ITCase.java

For #5171, Fix naming IT case

---

client/src/main/java/com/alibaba/nacos/client/security/SecurityProxy.java

Fixes #5190 
remove the unnecessary catch in method login.
XX
XXXX

[ISSUE #5190]remove the unnecessary catch in the login method

---

naming/src/test/java/com/alibaba/nacos/naming/consistency/DelegateConsistencyServiceImplTest.java

[#5467] com.alibaba.nacos.naming.consistency.DelegateConsistencyServiceImpl lacks a lot of Unit Tests.

---

api/src/main/java/com/alibaba/nacos/api/naming/ServerNamingAbility.java
api/src/test/java/com/alibaba/nacos/api/naming/ServerNamingAbilityTest.java
client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc/NamingGrpcConnectionEventListener.java
core/src/main/java/com/alibaba/nacos/core/cluster/ServerMemberManager.java
naming/src/main/java/com/alibaba/nacos/naming/push/v2/task/PushExecuteTask.java

Some enhancement for logs and ability.

---

core/src/main/java/com/alibaba/nacos/core/distributed/distro/DistroConfig.java
core/src/main/java/com/alibaba/nacos/core/distributed/distro/DistroConstants.java
core/src/main/java/com/alibaba/nacos/core/distributed/distro/DistroProtocol.java
distribution/conf/application.properties
naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/DistroConsistencyServiceImpl.java
naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/DistroHttpRegistry.java
naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/combined/DistroHttpCombinedKeyExecuteTask.java
naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/combined/DistroHttpCombinedKeyTaskFailedHandler.java
naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/v2/DistroClientComponentRegistry.java
naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/v2/DistroClientTaskFailedHandler.java
naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/v2/DistroClientTransportAgent.java
naming/src/main/java/com/alibaba/nacos/naming/misc/GlobalConfig.java

Refactor Distro Config as singleton and replace GlobalConfig

---

api/src/main/java/com/alibaba/nacos/api/config/filter/IConfigFilter.java
api/src/main/java/com/alibaba/nacos/api/config/filter/IConfigRequest.java
api/src/main/java/com/alibaba/nacos/api/config/filter/IConfigResponse.java
api/src/main/java/com/alibaba/nacos/api/config/filter/IFilterConfig.java
api/src/main/java/com/alibaba/nacos/api/config/remote/response/ConfigQueryResponse.java
client/src/main/java/com/alibaba/nacos/client/config/NacosConfigService.java
client/src/main/java/com/alibaba/nacos/client/config/filter/impl/ConfigFilterChainManager.java
client/src/main/java/com/alibaba/nacos/client/config/filter/impl/ConfigRequest.java
client/src/main/java/com/alibaba/nacos/client/config/filter/impl/ConfigResponse.java
client/src/main/java/com/alibaba/nacos/client/config/impl/CacheData.java
client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java
client/src/main/java/com/alibaba/nacos/client/config/impl/ConfigTransportClient.java
client/src/main/java/com/alibaba/nacos/client/config/impl/LocalConfigInfoProcessor.java
client/src/main/java/com/alibaba/nacos/client/config/impl/LocalEncryptedDataKeyProcessor.java
client/src/test/java/com/alibaba/nacos/client/config/NacosConfigServiceTest.java
client/src/test/java/com/alibaba/nacos/client/config/filter/impl/ConfigFilterChainManagerTest.java
client/src/test/java/com/alibaba/nacos/client/config/impl/CacheDataTest.java
client/src/test/java/com/alibaba/nacos/client/config/impl/ClientWorkerTest.java

Provide SPI to pre/post-process the config
See #5367 .
* Introduce the SPI `com.alibaba.nacos.api.config.filter.IConfigFilter`.
* user can custom the `com.alibaba.nacos.api.config.filter.IConfigFilter` to pre/post-process the config

[ISSUE #5367]配置加密SPI for 2.0

---

naming/src/test/java/com/alibaba/nacos/naming/consistency/persistent/PersistentConsistencyServiceDelegateImplTest.java

add unit test for PersistentConsistencyServiceDelegateImpl

---

pom.xml
sys/src/main/java/com/alibaba/nacos/sys/utils/DiskUtils.java

Upgrade dependency version to fix security alert

---

pom.xml

Upgrade version to 1.4.2

---

client/pom.xml
client/src/test/java/com/alibaba/nacos/client/naming/remote/AbstractNamingClientProxyTest.java
client/src/test/java/com/alibaba/nacos/client/naming/remote/NamingClientProxyDelegateTest.java
client/src/test/java/com/alibaba/nacos/client/naming/remote/gprc/NamingGrpcClientProxyTest.java
client/src/test/java/com/alibaba/nacos/client/naming/remote/gprc/NamingGrpcConnectionEventListenerTest.java
client/src/test/java/com/alibaba/nacos/client/naming/remote/gprc/NamingPushRequestHandlerTest.java
client/src/test/java/com/alibaba/nacos/client/naming/remote/http/NamingHttpClientManagerTest.java
client/src/test/java/com/alibaba/nacos/client/naming/remote/http/NamingHttpClientProxyTest.java
config/src/test/java/com/alibaba/nacos/config/server/utils/GroupKeyTest.java

[ISSUE #5153] Add unit tests for package com.alibaba.nacos.client.naming.remote in nacos 2.0 

---

naming/src/test/java/com/alibaba/nacos/naming/consistency/persistent/ClusterVersionJudgementTest.java

[#5545] Fix Unit test for ClusterVersionJudgementTest.java.

---

client/src/test/java/com/alibaba/nacos/client/config/filter/impl/ConfigFilterChainTest.java
client/src/test/java/com/alibaba/nacos/client/config/filter/impl/DemoFilter1.java
client/src/test/java/com/alibaba/nacos/client/config/filter/impl/DemoFilter2.java

add configFilterChain test case
see more detail from #5536 
XX
XXXX

add configFilterChain test case

---

naming/src/test/java/com/alibaba/nacos/naming/consistency/persistent/impl/NamingSnapshotOperationTest.java

[#5549] Fix Unit test for NamingSnapshotOperationTest.java

---

naming/src/test/java/com/alibaba/nacos/naming/healthcheck/ClientBeatCheckTaskTest.java

[#5551] Fix Unit Test for com.alibaba.nacos.naming.healthcheck.ClientBeatCheckTask.java

---

naming/src/test/java/com/alibaba/nacos/naming/core/DomainsManagerTest.java

[#5554] Fix Unit Test for com.alibaba.nacos.naming.core.DomainsManager.java

---

address/pom.xml
api/pom.xml
client/pom.xml
cmdb/pom.xml
common/pom.xml
config/pom.xml
console/pom.xml
core/pom.xml
example/pom.xml
istio/pom.xml
naming/pom.xml
sys/pom.xml
test/pom.xml

Parent pom.xml contains junit and mockito, there is no need to import again in sub-project.
for #5621

[ISSUE #5621] Delete duplicated dependency

---

naming/src/test/java/com/alibaba/nacos/naming/core/v2/metadata/ServiceMetadataProcessorTest.java

add unit test for ServiceMetadataProcessor

---

naming/src/test/java/com/alibaba/nacos/naming/core/v2/metadata/ServiceMetadataSnapshotOperationTest.java

[ISSUE #5522] add unit test for ServiceMetadataSnapshotOperation

---

naming/src/test/java/com/alibaba/nacos/naming/core/v2/metadata/NamingMetadataOperateServiceTest.java

[ISSUE #5522] add unit test for NamingMetadataOperateService

---

naming/src/test/java/com/alibaba/nacos/naming/core/v2/metadata/MetadataOperationTest.java

[ISSUE #5522] add unit test for MetadataOperation

---

client/src/main/java/com/alibaba/nacos/client/config/common/ConfigConstants.java
client/src/main/java/com/alibaba/nacos/client/config/common/Constants.java
client/src/main/java/com/alibaba/nacos/client/config/filter/impl/ConfigRequest.java
client/src/main/java/com/alibaba/nacos/client/config/filter/impl/ConfigResponse.java

Optimize ConfigRequest and ConfigResponse code, extract common constants
see more detail from #5547 
XX
XXXX

Optimize ConfigRequest and ConfigResponse code, extract common constants

---

naming/src/test/java/com/alibaba/nacos/naming/core/v2/index/ClientServiceIndexesManagerTest.java
naming/src/test/java/com/alibaba/nacos/naming/core/v2/index/ServiceStorageTest.java

Add unit tests for package com.alibaba.nacos.naming.core.v2.index

---

core/src/test/java/com/alibaba/nacos/core/cluster/lookup/LookupFactoryTest.java

[#5579] The class LookupFactory lacks corresponding Unit Test.

---

naming/src/test/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/DataStoreTest.java

[#5581] The class DataStore lacks a lot of Unit Tests.

---

config/src/main/java/com/alibaba/nacos/config/server/controller/CapacityController.java

Modify the Chinese log in CapacityController
see more detail from #5583 
XX
XXXX

Modify the Chinese log in CapacityController

---

core/src/test/java/com/alibaba/nacos/core/distributed/distro/entity/DistroDataTest.java
core/src/test/java/com/alibaba/nacos/core/distributed/distro/entity/DistroKeyTest.java

[#5595] Package com.alibaba.nacos.core.distributed.distro.entity lacks a lot of Unit tests

---

core/src/test/java/com/alibaba/nacos/core/distributed/distro/DistroConfigTest.java

[#5599] The class com.alibaba.nacos.core.distributed.distro.DistroConfig lacks Unit Test.

---

core/src/test/java/com/alibaba/nacos/core/distributed/distro/component/DistroComponentHolderTest.java

…nt lacks Unit Tests.
fix #5601 
XXXXX
XX
XXXX

[#5601] The package com.alibaba.nacos.core.distributed.distro.component lacks Unit Tests.

---

core/src/test/java/com/alibaba/nacos/core/cluster/lookup/AddressServerMemberLookupTest.java

…ests.
fix #5577 
XXXXX
XX
XXXX

[#5577] The AddressServerMemberLookupTest class lacks corresponding Unit Tests.

---

console-ui/src/pages/ConfigurationManagement/HistoryDetail/HistoryDetail.js

fix issue #5617 
修正问题 #5617
History Version Details When you return to the history version list page, the query parameters for the list page are missing. View is returned with parameter error.
历史版本详情在返回到 历史版本列表页时 , 列表页的查询参数丢失。 查看是返回时携带参数错误。
更正查询参数为： historyGroup & historyDataId
change param name to historyGroup & historyDataId
XXXX

[ISSUE #5617]  The Query Parameter Lose
