console-ui/src/pages/AuthorityControl/PermissionsManagement/PermissionsManagement.js
console-ui/src/pages/AuthorityControl/RolesManagement/RolesManagement.js
console-ui/src/pages/AuthorityControl/UserManagement/UserManagement.js

fix the #5635 
为 用户列表, 角色管理, 权限管理 的按钮添加右边距，使其看起来自然
button to add margin-right on the userList menu & Role Management & Privilege Management； It looks more natural
XX
XXXX

[ISSUE #5635]  button to add margin-right

---

config/src/main/java/com/alibaba/nacos/config/server/service/LongPollingService.java

Deal with the concurrency of ClientLongPolling and DataChangeTask about allSubs
see more detail from #5560 
XX
XXXX

Deal with the concurrency of ClientLongPolling and DataChangeTask about allSubs

---

client/src/test/java/com/alibaba/nacos/client/naming/NacosNamingMaintainServiceTest.java
client/src/test/java/com/alibaba/nacos/client/naming/NacosNamingServiceTest.java

[ISSUE #5155] Add unit tests for package com.alibaba.nacos.client.naming.remote in nacos 2.0

---

core/src/main/java/com/alibaba/nacos/core/distributed/distro/monitor/DistroRecord.java
core/src/main/java/com/alibaba/nacos/core/distributed/distro/monitor/DistroRecordsHolder.java
core/src/main/java/com/alibaba/nacos/core/distributed/distro/task/execute/AbstractDistroExecuteTask.java
core/src/main/java/com/alibaba/nacos/core/distributed/distro/task/verify/DistroVerifyExecuteTask.java
core/src/test/java/com/alibaba/nacos/core/distributed/distro/monitor/DistroRecordsHolderTest.java
naming/src/main/java/com/alibaba/nacos/naming/monitor/PerformanceLoggerThread.java

Add monitor for Distro

---

common/src/main/java/com/alibaba/nacos/common/utils/IPUtil.java
common/src/test/java/com/alibaba/nacos/common/utils/IPUtilTest.java
test/src/test/java/com/alibaba/nacos/test/core/JacksonUtils.java

fix test case fail
For #5538 
- fix test case fail

[ISSUE #5538] fix test case fail

---

core/src/main/java/com/alibaba/nacos/core/utils/WebUtils.java

Extract constants in WebUtils
see more detail #5676 
XX
XXXX

Extract constants in WebUtils

---

common/src/main/java/com/alibaba/nacos/common/utils/IPUtil.java

[ISSUE #5704] adjust code style

---

naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/impl/BasePersistentServiceProcessor.java

[ISSUE #5700] fix magic number

---

naming/src/test/java/com/alibaba/nacos/naming/push/v1/ServiceChangeEventTest.java

[ISSUE #5663] add unit test for ServiceChangeEvent

---

naming/src/test/java/com/alibaba/nacos/naming/push/v2/executor/SpiImplPushExecutorHolderTest.java

[ISSUE #5663] add unit test for SpiImplPushExecutorHolder

---

naming/src/main/java/com/alibaba/nacos/naming/controllers/UpgradeOpsController.java

[ISSUE #5718] Add some APIs for upgrade ops.

---

naming/src/main/java/com/alibaba/nacos/naming/cluster/transport/JacksonSerializer.java

Extract constants in JacksonSerializer
see more detail from #5724 
XX
XXXX

Extract constants in JacksonSerializer

---

config/src/main/java/com/alibaba/nacos/config/server/auth/EmbeddedPermissionPersistServiceImpl.java
config/src/main/java/com/alibaba/nacos/config/server/auth/EmbeddedRolePersistServiceImpl.java
config/src/main/java/com/alibaba/nacos/config/server/auth/EmbeddedUserPersistServiceImpl.java
config/src/main/java/com/alibaba/nacos/config/server/auth/ExternalPermissionPersistServiceImpl.java
config/src/main/java/com/alibaba/nacos/config/server/auth/ExternalRolePersistServiceImpl.java
config/src/main/java/com/alibaba/nacos/config/server/auth/ExternalUserPersistServiceImpl.java
config/src/main/java/com/alibaba/nacos/config/server/auth/PermissionPersistService.java
config/src/main/java/com/alibaba/nacos/config/server/auth/RolePersistService.java
config/src/main/java/com/alibaba/nacos/config/server/auth/UserPersistService.java

improve the code quality of `nacos-config`, directory `auth`
Fixes #5727 
mainly fixes missing notes and @Override annotaion.

[ISSUE #5727 auth] improve the code quality of nacos-config 

---

config/src/main/java/com/alibaba/nacos/config/server/aspect/CapacityManagementAspect.java

improve the code quality of `nacos-config`, directory `aspect`
Fixes #5727 
translate the Chinese log to English
XXXX

[ISSUE #5727 aspect] improve the code quality of nacos-config 

---

config/src/main/java/com/alibaba/nacos/config/server/controller/CommunicationController.java
config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigController.java
config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigOpsController.java
config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigServletInner.java
config/src/main/java/com/alibaba/nacos/config/server/controller/HealthController.java
config/src/main/java/com/alibaba/nacos/config/server/controller/HistoryController.java
config/src/main/java/com/alibaba/nacos/config/server/controller/ListenerController.java

improve the code quality of `nacos-config`, directory `controller`
Fixes #5727 
translate the Chinese javadoc to English, the if condition nest optimized, return result optimized
XXXX

[ISSUE #5727 controller] improve the code quality of nacos-config

---

config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigChangeListenContext.java
config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigPublishGroupKeyParser.java
config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigPublishGroupParser.java
config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigQueryGroupKeyParser.java
config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigQueryGroupParser.java
config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigQueryRequestHandler.java
config/src/main/java/com/alibaba/nacos/config/server/remote/InternalConfigChangeNotifier.java
config/src/main/java/com/alibaba/nacos/config/server/remote/RpcConfigChangeNotifier.java

…urn first, reduce the if/for nest.
improve the code quality of `nacos-config`, directory `remote`
Fixes #5727 
add mission @Override, return first, reduce the if/for nest.
XXXX

[ISSUE #5727 remote] improve the code quality of nacos-config

---

istio/src/main/java/com/alibaba/nacos/istio/model/mcp/AggregatedMeshConfigServiceGrpc.java
istio/src/main/java/com/alibaba/nacos/istio/model/mcp/ResourceSinkGrpc.java
istio/src/main/java/com/alibaba/nacos/istio/model/mcp/ResourceSourceGrpc.java
test/naming-test/src/test/java/com/alibaba/nacos/test/naming/ClientBeat_ITCase.java

For #5720
- delete unused import

[issue #5720] delete unused import

---

api/src/main/java/com/alibaba/nacos/api/PropertyKeyConst.java
client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingService.java

Fixes #5747 
* Support user specify NAMING_CACHE_REGISTRY_DIR property to enable the different registry to has different `cacheDir`
* If the user did not set the new property,  the `cacheDir` will keep as before.
```java
Properties properties = new Properties();
// Some other configs
// Replace ONE_FOLDER_NAME with your wantting cache registry dir
properties.setProperty(PropertyKeyConst.NAMING_CACHE_REGISTRY_DIR, "ONE_FOLDER_NAME")
NamingService naming = NamingFactory.createNamingService(properties);
```
then verify if the cache is located in the specified folder.
We can set `namingCacheRegistryDir` params from URL params, for example:
```xml
<dubbo:registry address="nacos://127.0.0.1:8849?namingCacheRegistryDir=folder1"/ …
```

[ISSUE #5747][v1.x] Support user specify NAMING_CACHE_REGISTRY_DIR property

---

naming/src/test/java/com/alibaba/nacos/naming/core/v2/cleaner/ExpiredMetadataCleanerTest.java

Add unit tests for package com.alibaba.nacos.naming.core.v2.cleaner and class naming.core.v2.cleaner.ExpiredMetadataCleaner

---

naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/ConnectionBasedClientManager.java

Remove duplicate client expire check.
XX
XXXX

[Refactor]Remove duplicate client expire check

---

config/src/main/java/com/alibaba/nacos/config/server/service/ClientIpWhiteList.java
config/src/main/java/com/alibaba/nacos/config/server/service/ConfigCacheService.java
config/src/main/java/com/alibaba/nacos/config/server/service/ConfigSubService.java
config/src/main/java/com/alibaba/nacos/config/server/service/LongPollingService.java
config/src/main/java/com/alibaba/nacos/config/server/service/SwitchService.java
config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/DistributedDatabaseOperateImpl.java
config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedPaginationHelperImpl.java
config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/StandaloneDatabaseOperateImpl.java
config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePaginationHelperImpl.java
config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java

improve the code quality of `nacos-config`, directory `service` part 2
Fixes #5727 
- add change the position of variable to match common code habits 
- add the mission @Override
- remove the unnesessary judgement.

[ISSUE #5727 service-2] improve the code quality of nacos-config

---

naming/src/main/java/com/alibaba/nacos/naming/controllers/UpgradeOpsController.java

...in UpgradeOpsController.
FIX #5756 
XX
XXXX

[ISSUE #5756] Support to specify ephemeral value for createService

---

api/src/main/java/com/alibaba/nacos/api/PropertyKeyConst.java
client/src/main/java/com/alibaba/nacos/client/naming/cache/ServiceInfoHolder.java

Fixes #5747 
Apply the same changes with #5749  to Nacos V2
see #5749
see #5749

[ISSUE #5747][v2] support of specifying NAMING_CACHE_REGISTRY_DIR property

---

config/src/main/java/com/alibaba/nacos/config/server/utils/AccumulateStatCount.java
config/src/main/java/com/alibaba/nacos/config/server/utils/ContentUtils.java
config/src/main/java/com/alibaba/nacos/config/server/utils/DiskUtil.java
config/src/main/java/com/alibaba/nacos/config/server/utils/GroupKey.java
config/src/main/java/com/alibaba/nacos/config/server/utils/GroupKey2.java
config/src/main/java/com/alibaba/nacos/config/server/utils/ParamUtils.java
config/src/main/java/com/alibaba/nacos/config/server/utils/PropertyUtil.java
config/src/main/java/com/alibaba/nacos/config/server/utils/Protocol.java
config/src/main/java/com/alibaba/nacos/config/server/utils/RegexParser.java
config/src/main/java/com/alibaba/nacos/config/server/utils/RequestUtil.java
config/src/main/java/com/alibaba/nacos/config/server/utils/YamlParserUtil.java

improve the code quality of `nacos-config`, directory `utils`
Fixes #5727 
- the Chinese javadoc translate
- return javadoc complete, the magic number fix
- the code logic format

[ISSUE #5727 utils] improve the code quality of nacos-config

---

naming/src/main/java/com/alibaba/nacos/naming/core/ServiceManager.java

[ISSUE #5767] Cleanup data of v1 after disable DoubleWrite.

---

config/src/main/java/com/alibaba/nacos/config/server/constant/PropertiesConstant.java
config/src/main/java/com/alibaba/nacos/config/server/utils/PropertyUtil.java

[ISSUE #3046] Enhancement for constant variables

---

naming/src/test/java/com/alibaba/nacos/naming/core/ClusterOperatorV2ImplTest.java

[ISSUE #5759] Add unit tests for class naming.core.ClusterOperatorV2Impl.

---

api/src/main/java/com/alibaba/nacos/api/remote/request/Request.java

Comment typos correction.

---

naming/src/main/java/com/alibaba/nacos/naming/cluster/remote/request/AbstractClusterRequest.java

[ISSUE #5774] improve the code quality of nacos-naming

---

naming/src/main/java/com/alibaba/nacos/naming/controllers/CatalogController.java
naming/src/main/java/com/alibaba/nacos/naming/controllers/ClusterController.java
naming/src/main/java/com/alibaba/nacos/naming/controllers/DistroController.java
naming/src/main/java/com/alibaba/nacos/naming/controllers/HealthController.java
naming/src/main/java/com/alibaba/nacos/naming/controllers/InstanceController.java
naming/src/main/java/com/alibaba/nacos/naming/controllers/OperatorController.java
naming/src/main/java/com/alibaba/nacos/naming/controllers/RaftController.java
naming/src/main/java/com/alibaba/nacos/naming/controllers/ServiceController.java

[ISSUE #5774] improve the code quality for controllers

---

address/src/main/java/com/alibaba/nacos/address/component/AddressServerGeneratorManager.java
address/src/main/java/com/alibaba/nacos/address/controller/AddressServerClusterController.java
address/src/main/java/com/alibaba/nacos/address/controller/ServerListController.java

Fixes #5766 
- fix the ResponseEntity
- if nest optimize
--

[ISSUE #5766] improve the code quality of nacos-address

---

naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/UpgradeJudgement.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/UpgradeStates.java
naming/src/test/java/com/alibaba/nacos/naming/core/v2/upgrade/UpgradeJudgementTest.java

FIX #5775 
Publish `UpgradeStateChangedEvent` to trigger persistent action of states.
XXXX

[ISSUE #5775] Persist the cluster upgrade states to disk.

---

naming/src/main/java/com/alibaba/nacos/naming/controllers/UpgradeOpsController.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/impl/IpPortBasedClient.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/ServiceMetadataProcessor.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/impl/PersistentClientOperationServiceImpl.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/doublewrite/execute/DoubleWriteServiceRemovalToV2Task.java

[ISSUE #5782] Fix removal of instances when DoubleWrite removing service.

---

sys/src/main/java/com/alibaba/nacos/sys/utils/InetUtils.java
sys/src/test/java/com/alibaba/nacos/sys/utils/InetUtilsTest.java

For #5765 
fix localhost not match ip
- fix problem
- add unit test

[ISSUE #5765] fix localhost not match ip

---

naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/ServiceMetadataProcessor.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/UpgradeJudgement.java

[ISSUE #5798] Fix upgraded server cannot downgrade and upgrade again.

---

client/src/test/java/com/alibaba/nacos/client/monitor/MetricsMonitorTest.java

[ISSUS #5803]add unit test for c.a.n.client.monitor

---

naming/src/main/java/com/alibaba/nacos/naming/monitor/PerformanceLoggerThread.java

There are extra curly brace suffixes in the log
XX
XXXX

Remove any extra curly brace suffixes from the log

---

common/src/main/java/com/alibaba/nacos/common/http/AbstractHttpClientFactory.java
common/src/main/java/com/alibaba/nacos/common/http/client/request/JdkHttpClientRequest.java
common/src/main/java/com/alibaba/nacos/common/http/param/Header.java
common/src/main/java/com/alibaba/nacos/common/http/param/Query.java
common/src/main/java/com/alibaba/nacos/common/notify/NotifyCenter.java

improve the code quality of `nacos-common`, directory `notify/http`
Fixes #5802 
- export magic number.
- the code logic format.

[FOR #5802 notify/http] improve the code quality of nacos-common.

---

common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClient.java
common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClientFactory.java
common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClient.java
common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcConnection.java
common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcUtils.java
common/src/main/java/com/alibaba/nacos/common/spi/NacosServiceLoader.java

improve the code quality of `nacos-common`, directory `remote/spi`
Fixes #5802 
- export magic number.
- the code logic format.

[FOR #5802 remote/spi] improve the code quality of nacos-common. 

---

common/src/main/java/com/alibaba/nacos/common/tls/SelfTrustManager.java
common/src/main/java/com/alibaba/nacos/common/utils/ExceptionUtil.java
common/src/main/java/com/alibaba/nacos/common/utils/MapUtil.java
common/src/main/java/com/alibaba/nacos/common/utils/ReflectUtils.java
common/src/main/java/com/alibaba/nacos/common/utils/ThreadUtils.java
common/src/main/java/com/alibaba/nacos/common/utils/VersionUtils.java

improve the code quality of `nacos-common`, directory `tls/utils`
Fixes #5802 
- remove unnecessary symbol
- export constant in class 
- change the Chinese javadoc to English

[FOR #5802 tls/utils] improve the code quality of nacos-common.

---

client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc/NamingGrpcConnectionEventListener.java

Fixes #5831 .
Remove the sets in connection event lister

[ISSUE#5831] Remove the sets in connection event lister

---

distribution/conf/application.properties

Fix the error merge for application.properties

---

common/src/main/java/com/alibaba/nacos/common/notify/DefaultPublisher.java
common/src/main/java/com/alibaba/nacos/common/notify/DefaultSharePublisher.java

Publisher code optimization
see more detail from #5762
XX
XXXX

Publisher code optimization

---

istio/src/main/java/com/alibaba/nacos/istio/mcp/NacosToMcpResources.java

Fix [ISSUE #5779](https://github.com/alibaba/nacos/issues/5779)
- Use the serviceManager v2 to get the service list
MCP-Over-XDS successfully synced Nacos services to Istio Envoy XDS

[ISSUE #5779] Use the correct serviceManager version to get the service list

---

client/src/main/java/com/alibaba/nacos/client/security/SecurityProxy.java

Optimize SecurityProxy code
see more detail from #5826 
XX
XXXX

Optimize SecurityProxy code

---

client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java

[#5818] the question about notes in nacos-config ClientWorker

---

consistency/src/main/java/com/alibaba/nacos/consistency/serialize/HessianSerializer.java
consistency/src/main/java/com/alibaba/nacos/consistency/serialize/JacksonSerializer.java

improve the code quality of `nacos-consistency`, all directory.
Fixes #5836 
- export constant in class 

[FOR #5836 all ] improve the code quality of nacos-consistency.

---

auth/src/main/java/com/alibaba/nacos/auth/common/AuthConfigs.java

Remove any extra curly braces from the @Value annotation
XX
XXXX

Remove any extra curly braces from the @Value annotation

---

naming/src/main/java/com/alibaba/nacos/naming/core/ServiceManager.java
naming/src/test/java/com/alibaba/nacos/naming/core/ServiceManagerTest.java

The code checking for empty 'Service' in the 'ServiceManager ' under the optimization ‘naming’ module.I think it can be used in other places,Such as 'naming' module in a class the following OperatorController getResponsibleServer4Service method and CatalogServiceV1Impl getServiceDetail method in a class and so on,So the access permission modifier is public.
XX
XXXX

Optimize code that checks for empty service.

---

console/src/main/java/com/alibaba/nacos/console/filter/JwtAuthenticationTokenFilter.java
console/src/main/java/com/alibaba/nacos/console/security/nacos/LdapAuthenticationProvider.java
console/src/main/java/com/alibaba/nacos/console/security/nacos/NacosAuthConfig.java
console/src/main/java/com/alibaba/nacos/console/security/nacos/NacosAuthManager.java
console/src/main/java/com/alibaba/nacos/console/security/nacos/roles/NacosRoleServiceImpl.java
console/src/main/resources/META-INF/nacos-default.properties

improve the code quality of `nacos-console`, directory `filter/security`
Fixes #5843  

[FOR #5843 filter/security] improve the code quality of nacos-console. 

---

console/src/main/resources/application.properties

Add automatic cleaning accesslog days.
Add automatic cleaning accesslog days.

Add automatic cleaning accesslog days.

---

client/src/main/java/com/alibaba/nacos/client/config/impl/CacheData.java

Modify the comment in CacheData to English
see more detail from #5850 
XX
XXXX

Modify the comment in CacheData to English

---

console/src/main/java/com/alibaba/nacos/console/controller/HealthController.java
console/src/main/java/com/alibaba/nacos/console/controller/NamespaceController.java
console/src/main/java/com/alibaba/nacos/console/controller/PermissionController.java
console/src/main/java/com/alibaba/nacos/console/controller/RoleController.java
console/src/main/java/com/alibaba/nacos/console/controller/ServerStateController.java
console/src/main/java/com/alibaba/nacos/console/controller/UserController.java
console/src/main/java/com/alibaba/nacos/console/enums/NamespaceTypeEnum.java
console/src/main/java/com/alibaba/nacos/console/model/Namespace.java

improve the code quality of `nacos-console`, directory `controller/model/enums`
Fixes #5843  
- fix the ResponseEntity 
- the enum create.

[FOR #5843 controller/model/enums] improve the code quality of nacos-console. 

---

naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/doublewrite/delay/ServiceChangeV1Task.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/doublewrite/execute/DefaultInstanceUpgradeHelper.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/doublewrite/execute/DefaultServiceMetadataUpgradeHelper.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/doublewrite/execute/DoubleWriteInstanceChangeToV1Task.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/doublewrite/execute/DoubleWriteMetadataChangeToV1Task.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/doublewrite/execute/InstanceUpgradeHelper.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/doublewrite/execute/ServiceMetadataUpgradeHelper.java
naming/src/main/java/com/alibaba/nacos/naming/healthcheck/HealthCheckReactor.java

[ISSUE #5870] Prevent instance ephemeral value used by DoubleWrite.

---

core/src/main/java/com/alibaba/nacos/core/cluster/MemberUtil.java
core/src/main/java/com/alibaba/nacos/core/cluster/MembersChangeEvent.java
core/src/main/java/com/alibaba/nacos/core/cluster/ServerMemberManager.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/UpgradeJudgement.java

[ISSUE #5872] Downgrade checker only focus on changing members.

---

naming/src/main/java/com/alibaba/nacos/naming/controllers/CatalogController.java
naming/src/main/java/com/alibaba/nacos/naming/controllers/OperatorController.java
naming/src/main/java/com/alibaba/nacos/naming/controllers/ServiceController.java
naming/src/main/java/com/alibaba/nacos/naming/core/CatalogServiceV1Impl.java
naming/src/main/java/com/alibaba/nacos/naming/core/ClusterOperatorV1Impl.java
naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperatorServiceImpl.java
naming/src/main/java/com/alibaba/nacos/naming/core/ServiceOperatorV1Impl.java
naming/src/test/java/com/alibaba/nacos/naming/core/ClusterOperatorV2ImplTest.java
naming/src/test/java/com/alibaba/nacos/naming/core/ServiceOperatorV1ImplTest.java

Optimizing everything in the 'naming' module in relation to checking that the 'service' is empty, throwing an exception when the service is not found
XX
XXXX

Optimize code that all checks for empty service.

---

naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/v2/DistroClientTransportAgent.java

Stop do sync when sync is no need.

---

client/src/main/java/com/alibaba/nacos/client/config/impl/ServerListManager.java
client/src/test/java/com/alibaba/nacos/client/config/impl/ServerListManagerTest.java

[ISSUE #4208] Fix bug when configuring multiple ips.

---

core/src/main/java/com/alibaba/nacos/core/auth/AuthFilter.java
core/src/main/java/com/alibaba/nacos/core/cluster/Member.java
core/src/main/java/com/alibaba/nacos/core/cluster/MemberUtil.java
core/src/main/java/com/alibaba/nacos/core/cluster/ServerMemberManager.java
core/src/main/java/com/alibaba/nacos/core/cluster/lookup/AddressServerMemberLookup.java
core/src/main/java/com/alibaba/nacos/core/cluster/lookup/FileConfigMemberLookup.java
core/src/main/java/com/alibaba/nacos/core/cluster/remote/ClusterRpcClientProxy.java

improve the code quality of `nacos-core`, directory `auth/cluster`
For #5877  

[FOR 5877 auth/cluster] improve the code quality of nacos-core.

---

core/src/main/java/com/alibaba/nacos/core/controller/ServerLoaderController.java
core/src/main/java/com/alibaba/nacos/core/distributed/ProtocolManager.java
core/src/main/java/com/alibaba/nacos/core/distributed/id/SnowFlowerIdGenerator.java
core/src/main/java/com/alibaba/nacos/core/distributed/raft/processor/AbstractProcessor.java
core/src/main/java/com/alibaba/nacos/core/listener/StartingApplicationListener.java
core/src/main/java/com/alibaba/nacos/core/monitor/MetricsMonitor.java

improve the code quality of `nacos-core`, directory `controller/distributed/listner/monitor`
For #5877  

[FOR 5877 controller/distributed/listner/monitor] improve the code quality of nacos-core.

---

core/src/main/java/com/alibaba/nacos/core/remote/control/ClientIpMonitorKey.java
core/src/main/java/com/alibaba/nacos/core/remote/control/ConnectionIdMonitorKey.java
core/src/main/java/com/alibaba/nacos/core/remote/control/MonitorKey.java
core/src/main/java/com/alibaba/nacos/core/remote/control/MonitorKeyMatcher.java
core/src/main/java/com/alibaba/nacos/core/remote/control/MonitorKeyParser.java
core/src/main/java/com/alibaba/nacos/core/remote/control/TpsControlRequestFilter.java
core/src/main/java/com/alibaba/nacos/core/remote/control/TpsMonitorManager.java
core/src/main/java/com/alibaba/nacos/core/remote/control/TpsMonitorPoint.java
core/src/main/java/com/alibaba/nacos/core/remote/control/TpsRecorder.java

improve the code quality of `nacos-core`, directory `remote/control`
For #5877  

[FOR 5877  remote/control] improve the code quality of nacos-core. 

---

core/src/main/java/com/alibaba/nacos/core/remote/ConnectionManager.java
core/src/main/java/com/alibaba/nacos/core/remote/grpc/BaseGrpcServer.java
core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcBiStreamRequestAcceptor.java
core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcConnection.java
core/src/main/java/com/alibaba/nacos/core/utils/RemoteUtils.java
core/src/main/java/com/alibaba/nacos/core/utils/ReuseUploadFileHttpServletRequest.java

improve the code quality of `nacos-core`, directory `remote-grpc/utils`
For #5877  

[FOR 5877 remote-grpc/utils] improve the code quality of nacos-core.

---

sys/src/main/java/com/alibaba/nacos/sys/env/EnvUtil.java
sys/src/main/java/com/alibaba/nacos/sys/file/WatchFileCenter.java

improve the code quality of `nacos-sys`, directory `env/file`
For #5904
- the constants export 
- redundant symbol remove

[FOR 5904 env/file] improve the code quality of nacos-sys.

---

naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/impl/IpPortBasedClient.java
naming/src/main/java/com/alibaba/nacos/naming/healthcheck/v2/HealthCheckTaskV2.java
naming/src/main/java/com/alibaba/nacos/naming/healthcheck/v2/processor/TcpHealthCheckProcessor.java

[ISSUE #5927] Init health check status when loading snapshot of persistent instances.

---

example/src/main/java/com/alibaba/nacos/example/NamingExample.java

Fixes #5689
reduce the register of instance time to 1.
run the exmaple

[ISSUE #5689] update the example in Nacos 2.0.

---

api/src/main/java/com/alibaba/nacos/api/remote/RequestCallBack.java
api/src/main/java/com/alibaba/nacos/api/remote/request/ClientDetectionRequest.java
api/src/main/java/com/alibaba/nacos/api/remote/request/ConnectResetRequest.java
api/src/main/java/com/alibaba/nacos/api/remote/request/InternalRequest.java
api/src/main/java/com/alibaba/nacos/api/utils/NetUtils.java

improve the code quality of `nacos-api`, directory `remote/utils`
For #5915
- the constants export.
- unused codes remove.

[FOR 5915 remote/utils] improve the code quality of nacos-api. 

---

api/src/main/java/com/alibaba/nacos/api/naming/NamingFactory.java
api/src/main/java/com/alibaba/nacos/api/naming/NamingMaintainFactory.java
api/src/main/java/com/alibaba/nacos/api/naming/pojo/ServiceInfo.java
api/src/main/java/com/alibaba/nacos/api/naming/remote/request/AbstractNamingRequest.java
api/src/main/java/com/alibaba/nacos/api/naming/remote/request/NotifySubscriberRequest.java

improve the code quality of `nacos-api`, directory `naming`
For #5915
- the constants export 

[FOR 5915 naming] improve the code quality of nacos-api. 

---

api/src/main/java/com/alibaba/nacos/api/config/remote/request/AbstractConfigRequest.java
api/src/main/java/com/alibaba/nacos/api/config/remote/request/ClientConfigMetricRequest.java
api/src/main/java/com/alibaba/nacos/api/config/remote/request/ConfigChangeNotifyRequest.java
api/src/main/java/com/alibaba/nacos/api/config/remote/request/ConfigQueryRequest.java

improve the code quality of `nacos-api`, directory `config`
For #5915
- the constants export 

[FOR 5915 config] improve the code quality of nacos-api.

---

client/src/test/java/com/alibaba/nacos/client/identify/CredentialServiceTest.java
client/src/test/java/com/alibaba/nacos/client/identify/CredentialWatcherTest.java
client/src/test/java/com/alibaba/nacos/client/identify/CredentialsTest.java
client/src/test/java/com/alibaba/nacos/client/identify/StsConfigTest.java

[ISSUS #5805]add unit test for c.a.n.client.identify

---

common/src/main/java/com/alibaba/nacos/common/task/AbstractDelayTask.java
common/src/main/java/com/alibaba/nacos/common/task/AbstractExecuteTask.java
naming/src/main/java/com/alibaba/nacos/naming/constants/FieldsConstants.java
naming/src/main/java/com/alibaba/nacos/naming/core/CatalogServiceV1Impl.java
naming/src/main/java/com/alibaba/nacos/naming/core/CatalogServiceV2Impl.java
naming/src/main/java/com/alibaba/nacos/naming/core/Cluster.java
naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperatorServiceImpl.java
naming/src/main/java/com/alibaba/nacos/naming/core/ServiceOperatorV1Impl.java
naming/src/main/java/com/alibaba/nacos/naming/core/ServiceOperatorV2Impl.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/cleaner/EmptyServiceAutoCleaner.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/cleaner/ExpiredMetadataCleaner.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/factory/ClientFactoryHolder.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/ClientManagerDelegate.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/NamingMetadataManager.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/impl/PersistentClientOperationServiceImpl.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/UpgradeJudgement.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/doublewrite/delay/ServiceChangeV1Task.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/doublewrite/delay/ServiceChangeV2Task.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/doublewrite/execute/AsyncServicesCheckTask.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/doublewrite/execute/DefaultInstanceUpgradeHelper.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/doublewrite/execute/DoubleWriteInstanceChangeToV1Task.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/doublewrite/execute/DoubleWriteInstanceChangeToV2Task.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/doublewrite/execute/DoubleWriteMetadataChangeToV1Task.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/doublewrite/execute/DoubleWriteMetadataChangeToV2Task.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/doublewrite/execute/DoubleWriteServiceRemovalToV1Task.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/doublewrite/execute/DoubleWriteServiceRemovalToV2Task.java

[ISSUE #5774] improve the code quality for naming core

---

naming/src/main/java/com/alibaba/nacos/naming/constants/FieldsConstants.java
naming/src/main/java/com/alibaba/nacos/naming/healthcheck/ClientBeatCheckTask.java
naming/src/main/java/com/alibaba/nacos/naming/healthcheck/ClientBeatProcessor.java
naming/src/main/java/com/alibaba/nacos/naming/healthcheck/heartbeat/ClientBeatProcessorV2.java

[ISSUE #5774] improve the code quality for naming healthcheck

---

common/src/main/java/com/alibaba/nacos/common/notify/DefaultPublisher.java
common/src/main/java/com/alibaba/nacos/common/notify/DefaultSharePublisher.java
common/src/main/java/com/alibaba/nacos/common/notify/EventPublisherFactory.java
common/src/main/java/com/alibaba/nacos/common/notify/NotifyCenter.java
common/src/main/java/com/alibaba/nacos/common/notify/ShardedEventPublisher.java
naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/v2/DistroClientDataProcessor.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/event/publisher/NamingEventPublisher.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/event/publisher/NamingEventPublisherFactory.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/index/ClientServiceIndexesManager.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/NamingMetadataManager.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/doublewrite/delay/DoubleWriteEventListener.java
naming/src/main/java/com/alibaba/nacos/naming/push/v2/NamingSubscriberServiceV2Impl.java
naming/src/test/java/com/alibaba/nacos/naming/core/v2/event/publisher/NamingEventPublisherFactoryTest.java
naming/src/test/java/com/alibaba/nacos/naming/core/v2/event/publisher/NamingEventPublisherTest.java
naming/src/test/java/com/alibaba/nacos/naming/core/v2/event/publisher/TestEvent.java

For #5918 .
- Rollback #5778.
- Add method to register custom sharded event publisher
- Make naming module event use custom sharded publisher

[ISSUE#5918] Refactor event publisher in naming module to fix event without orders.

---

api/src/main/java/com/alibaba/nacos/api/config/remote/response/ConfigPublishResponse.java
api/src/main/java/com/alibaba/nacos/api/remote/request/Request.java
client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java
client/src/main/java/com/alibaba/nacos/client/config/impl/ConfigTransportClient.java
common/src/main/java/com/alibaba/nacos/common/http/client/request/DefaultAsyncHttpClientRequest.java
common/src/main/java/com/alibaba/nacos/common/http/param/Header.java
common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClient.java
common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClientFactory.java
common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClient.java
config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigPublishRequestHandler.java
pom.xml

fix ak sk and some tiny optimize

---

client/src/main/java/com/alibaba/nacos/client/naming/core/HostReactor.java

Fixes #5699 
Simple the judge logic in HostReactor.processServiceJson 
Simple the judge logic in HostReactor.processServiceJson 

[ISSUE #5699] Simple the judge logic in HostReactor.processServiceJson 

---

client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java
client/src/main/java/com/alibaba/nacos/client/config/impl/ConfigTransportClient.java
common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClient.java
common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClient.java

fix query sla multi connection model ;add rpc client error log; optimize client shutdown

---

client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java
common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClient.java

client aware server list change

---

console-ui/README.md

[ISSUE #5945]Modify console-ui README.md to submit to Develop

---

console-ui/README.md

[ISSUE #5945]Modify console-ui README.md to submit to v1.x-develop

---

naming/src/main/java/com/alibaba/nacos/naming/core/CatalogServiceV2Impl.java
naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperatorClientImpl.java

Fixes #5921 .
- Adapt some Naming API after upgrading to v2.x.

[ISSUE#5921] Adapt some Naming API after upgrading to v2.x.

---

client/src/main/java/com/alibaba/nacos/client/naming/core/ServerListManager.java
client/src/main/java/com/alibaba/nacos/client/naming/event/ServerListChangedEvent.java
client/src/main/java/com/alibaba/nacos/client/naming/remote/AbstractNamingClientProxy.java
client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc/NamingGrpcClientProxy.java
client/src/main/java/com/alibaba/nacos/client/naming/remote/http/NamingHttpClientProxy.java
client/src/test/java/com/alibaba/nacos/client/naming/remote/AbstractNamingClientProxyTest.java
client/src/test/java/com/alibaba/nacos/client/naming/remote/gprc/NamingGrpcClientProxyTest.java
common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClientFactory.java

[ISSUE #5952] Feature make naming rpc client aware of server list change

---

client/src/main/java/com/alibaba/nacos/client/config/common/ConfigConstants.java
client/src/main/java/com/alibaba/nacos/client/config/common/GroupKey.java
client/src/main/java/com/alibaba/nacos/client/config/filter/impl/ConfigFilterChainManager.java
client/src/main/java/com/alibaba/nacos/client/config/filter/impl/ConfigRequest.java
client/src/main/java/com/alibaba/nacos/client/config/http/MetricsHttpAgent.java
client/src/main/java/com/alibaba/nacos/client/config/http/ServerHttpAgent.java

improve the code quality of `nacos-client`, directory `config  common/filter/http` 
For #5771

[FOR 5771 config  common/filter/http] improve the code quality of nacos-client. 

---

client/src/main/java/com/alibaba/nacos/client/config/NacosConfigService.java
client/src/main/java/com/alibaba/nacos/client/config/utils/ConcurrentDiskUtil.java
client/src/main/java/com/alibaba/nacos/client/config/utils/ContentUtils.java
client/src/main/java/com/alibaba/nacos/client/config/utils/JvmUtil.java
client/src/main/java/com/alibaba/nacos/client/config/utils/ParamUtils.java

improve the code quality of `nacos-client`, directory `config utils` 
For #5771

[FOR 5771 config utils] improve the code quality of nacos-client. 

---

common/src/test/resources/META-INF/services/com.alibaba.nacos.common.spi.SpiTestInterface

[5989] Fix unit tests in nacos-common

---

address/src/test/java/com/alibaba/nacos/address/AddressServerControllerTests.java

[fix5986] Fix unit tests in nacos-address

---

client/src/main/java/com/alibaba/nacos/client/config/impl/CacheData.java
client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java
client/src/main/java/com/alibaba/nacos/client/config/impl/ConfigTransportClient.java
client/src/main/java/com/alibaba/nacos/client/config/impl/Limiter.java
client/src/main/java/com/alibaba/nacos/client/config/impl/LocalConfigInfoProcessor.java
client/src/main/java/com/alibaba/nacos/client/config/impl/LocalEncryptedDataKeyProcessor.java
client/src/main/java/com/alibaba/nacos/client/config/impl/PropertiesChangeParser.java
client/src/main/java/com/alibaba/nacos/client/config/impl/ServerListManager.java
client/src/main/java/com/alibaba/nacos/client/config/impl/SpasAdapter.java
client/src/main/java/com/alibaba/nacos/client/config/impl/YmlChangeParser.java

improve the code quality of `nacos-client`, directory `config impl` 
For #5771

[FOR 5771 config impl] improve the code quality of nacos-client. 

---

naming/src/main/java/com/alibaba/nacos/naming/constants/FieldsConstants.java
naming/src/main/java/com/alibaba/nacos/naming/push/UdpPushService.java
naming/src/main/java/com/alibaba/nacos/naming/push/v1/NamingSubscriberServiceV1Impl.java
naming/src/main/java/com/alibaba/nacos/naming/web/NamingConfig.java
naming/src/main/java/com/alibaba/nacos/naming/web/NamingResourceParser.java

[ISSUE #5774] improve the code quality for naming

---

client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingService.java
client/src/main/java/com/alibaba/nacos/client/naming/backups/FailoverReactor.java
client/src/main/java/com/alibaba/nacos/client/naming/beat/BeatReactor.java
client/src/main/java/com/alibaba/nacos/client/naming/cache/ConcurrentDiskUtil.java
client/src/main/java/com/alibaba/nacos/client/naming/cache/ServiceInfoHolder.java
client/src/main/java/com/alibaba/nacos/client/naming/core/PushReceiver.java
client/src/main/java/com/alibaba/nacos/client/naming/remote/AbstractNamingClientProxy.java
client/src/main/java/com/alibaba/nacos/client/naming/remote/http/NamingHttpClientProxy.java
client/src/main/java/com/alibaba/nacos/client/naming/utils/Chooser.java
client/src/main/java/com/alibaba/nacos/client/naming/utils/InitUtils.java
client/src/main/java/com/alibaba/nacos/client/naming/utils/SignUtil.java
client/src/main/java/com/alibaba/nacos/client/naming/utils/UtilAndComs.java

improve the code quality of `nacos-client`, directory `naming` 
For #5771

[FOR 5771 naming] improve the code quality of nacos-client. 

---

istio/src/main/java/com/alibaba/nacos/istio/mcp/NacosMcpOverXdsService.java
istio/src/main/java/com/alibaba/nacos/istio/mcp/NacosMcpService.java
istio/src/main/java/com/alibaba/nacos/istio/mcp/NacosToMcpResources.java

improve the code quality of `nacos-istio`, all directory.
For #6010

[FOR 6010 all] improve the code quality of nacos-istio.

---

config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedStoragePersistServiceImpl.java
config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java

fix #5934 for 2.x

---

client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc/NamingGrpcClientProxy.java

Add/Remove cache before call server
Add/Remove cache before call server
XXXX

Add/Remove cache before call server.

---

client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingMaintainService.java
client/src/main/java/com/alibaba/nacos/client/naming/core/ServerListManager.java
client/src/main/java/com/alibaba/nacos/client/naming/remote/NamingClientProxyDelegate.java

[ISSUE #6019] Support fetching server list from endpoint with namespace.

---

console-ui/README.md

[ISSUE #5945] Feature update readme develop 

---

console-ui/README.md

[ISSUE #5945] Feature update readme v1.x develop

---

core/src/main/java/com/alibaba/nacos/core/cluster/lookup/AddressServerMemberLookup.java

fix the constant problem caused by code quality
see the PR #5894  comment 
the mistake key of System.getProperty in AddressServerMemberLookup
the origin content as below:
XXXX

[FIX PR #5894] fix the constant problem caused by code quality

---

pom.xml

Upgrade to 2.0.2

---

client/src/main/java/com/alibaba/nacos/client/utils/AppNameUtils.java
client/src/main/java/com/alibaba/nacos/client/utils/ContextPathUtil.java
client/src/main/java/com/alibaba/nacos/client/utils/EnvUtil.java
client/src/main/java/com/alibaba/nacos/client/utils/ParamUtil.java
client/src/main/java/com/alibaba/nacos/client/utils/TenantUtil.java

improve the code quality of `nacos-client`, directory `utils` 
For #5771

[FOR 5771 utils] improve the code quality of nacos-client. 

---

core/src/test/java/com/alibaba/nacos/core/utils/ClassUtilsTest.java
core/src/test/java/com/alibaba/nacos/core/utils/OverrideParameterRequestWrapperTest.java
core/src/test/java/com/alibaba/nacos/core/utils/RemoteUtilsTest.java
core/src/test/java/com/alibaba/nacos/core/utils/StringPoolTest.java
core/src/test/java/com/alibaba/nacos/core/utils/WebUtilsTest.java

for #5094 we add unit tests by directory, module  `nacos-core`  directory `utils`.
XX
XXXX

[FOR 5094 utils] add unit tests in nacos-core.

---

core/src/test/java/com/alibaba/nacos/core/storage/FileKvStorageTest.java
core/src/test/java/com/alibaba/nacos/core/storage/MemoryKvStorageTest.java
core/src/test/java/com/alibaba/nacos/core/storage/StorageFactoryTest.java

for #5094 we add unit tests by directory, module  `nacos-core`  directory `storage`.
XX
XXXX

[FOR 5094 storage] add unit tests in nacos-core.

---

naming/src/test/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/DistroConsistencyServiceImplTest.java
naming/src/test/java/com/alibaba/nacos/naming/consistency/persistent/impl/NamingKvStorageTest.java
naming/src/test/java/com/alibaba/nacos/naming/controllers/CatalogControllerTest.java
naming/src/test/java/com/alibaba/nacos/naming/controllers/ClusterControllerTest.java
naming/src/test/java/com/alibaba/nacos/naming/core/ClusterTest.java
naming/src/test/java/com/alibaba/nacos/naming/core/ServiceManagerTest.java
naming/src/test/java/com/alibaba/nacos/naming/core/ServiceOperatorV1ImplTest.java
naming/src/test/java/com/alibaba/nacos/naming/core/v2/upgrade/UpgradeJudgementTest.java
naming/src/test/java/com/alibaba/nacos/naming/healthcheck/v2/processor/HealthCheckProcessorV2DelegateTest.java
naming/src/test/java/com/alibaba/nacos/naming/healthcheck/v2/processor/HttpHealthCheckProcessorTest.java

[ISSUE#5982] Fix Unit test in nacos naming module

---

console/src/main/java/com/alibaba/nacos/console/security/nacos/LdapAuthenticationProvider.java

add error log print
fix #5909
add error log print
Verifying this change
print error log
[√ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
[√ ] Format the pull request title like [ISSUE #123] Fix UnknownException when host config not exist. Each commit in the pull request should have a meaningful subject line and body.
[√ ] Write a pull request description that is detailed …

add ldap use error, print error log

---

client/src/main/java/com/alibaba/nacos/client/config/impl/CacheData.java
client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java

concurrent sync flag fix

---

client/src/test/java/com/alibaba/nacos/client/config/utils/ContentUtilsTest.java
client/src/test/java/com/alibaba/nacos/client/naming/event/InstancesChangeNotifierTest.java

[#5984] Fix unit tests in nacos-client

---

core/src/main/java/com/alibaba/nacos/core/monitor/MetricsMonitor.java
core/src/main/java/com/alibaba/nacos/core/monitor/NacosMeterRegistry.java
core/src/test/java/com/alibaba/nacos/core/monitor/MetricsMonitorTest.java

for #5094 we add unit tests by directory, module  `nacos-core`  directory `monitor`.
XX
XXXX

[FOR 5094 monitor] add unit tests in nacos-core. 

---

pom.xml

Upgrade to 2.0.3-SNAPSHOT

---

README.md

#6079 Fix too many commits, squash to one.
XX
XXXX

Update readme who is using

---

.github/workflows/ci.yml

Add github CI

---

.github/workflows/ci.yml

Fix github CI

---

.github/workflows/ci.yml
.github/workflows/it.yml
core/src/test/java/com/alibaba/nacos/core/cluster/MemberUtilTest.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/event/publisher/NamingEventPublisher.java
pom.xml

Develop fix ci

---

README.md

[#6097] The DingDing QR code is invalid now

---

client/src/test/java/com/alibaba/nacos/client/config/http/ServerHttpAgentTest.java
client/src/test/java/com/alibaba/nacos/client/config/impl/PropertiesChangeParserTest.java
client/src/test/java/com/alibaba/nacos/client/config/impl/YmlChangeParserTest.java
common/src/test/java/com/alibaba/nacos/common/utils/InternetAddressUtilTest.java
test/config-test/src/test/java/com/alibaba/nacos/test/config/ConfigLongPollReturnChanges_CITCase.java

[ISSUE #6088] Simplify Assert

---

client/src/main/java/com/alibaba/nacos/client/naming/utils/InitUtils.java

Fixes #5845 
remove the redundant codes.
XXXX

[ISSUE #5845] remove redundant codes in class InitUtils.

---

consistency/src/test/java/com/alibaba/nacos/consistency/ProtocolMetaDataTest.java

[ISSUE#5990] Fix unit test problem for nacos-consistency.

---

core/src/test/java/com/alibaba/nacos/core/distributed/distro/task/load/DistroLoadDataTaskTest.java
core/src/test/java/com/alibaba/nacos/core/remote/TpsMonitorManagerTest.java
core/src/test/resources/application.properties

[ISSUE#5985] Fix unit test problem for nacos-core.

---

console-ui/src/layouts/Header.js

#6011 Optimized the problem that the Chinese account displayed in the header of the Chinese version of Nacos client after logging in.
XX
XXXX

Optimize the nacos client home page Chinese account gibber.

---

auth/src/main/java/com/alibaba/nacos/auth/common/AuthConfigs.java
auth/src/test/java/com/alibaba/nacos/auth/common/AuthConfigsTest.java
common/src/main/java/com/alibaba/nacos/common/event/ServerConfigChangeEvent.java
core/src/main/java/com/alibaba/nacos/core/distributed/distro/DistroConfig.java
core/src/main/java/com/alibaba/nacos/core/listener/StartingApplicationListener.java
core/src/test/java/com/alibaba/nacos/core/distributed/distro/DistroConfigTest.java
naming/src/main/java/com/alibaba/nacos/naming/push/v2/PushConfig.java
naming/src/test/java/com/alibaba/nacos/naming/push/v2/PushConfigTest.java

[ISSUE#6129] Add ServerConfigChangeEvent when config file changed.

---

core/src/main/java/com/alibaba/nacos/core/auth/RemoteRequestAuthFilter.java

[ISSUE #6132] RemoteRequestAuthFilter get error message from AccessException correctly

---

api/src/main/java/com/alibaba/nacos/api/remote/DefaultRequestFuture.java

clear future on callback timeout

---

client/src/test/java/com/alibaba/nacos/client/logging/AbstractNacosLoggingTest.java
client/src/test/java/com/alibaba/nacos/client/logging/NacosLoggingTest.java
client/src/test/java/com/alibaba/nacos/client/logging/log4j2/Log4J2NacosLoggingTest.java
client/src/test/java/com/alibaba/nacos/client/logging/logback/LogbackNacosLoggingTest.java

[ISSUE #5806]Add unit tests for package com.alibaba.nacos.client.logging in nacos 

---

console-ui/src/pages/ConfigurationManagement/ConfigDetail/ConfigDetail.js
console-ui/src/pages/ConfigurationManagement/ConfigDetail/index.scss
console-ui/src/pages/ConfigurationManagement/ConfigEditor/NewConfigEditor.js
console-ui/src/pages/ConfigurationManagement/ConfigEditor/index.scss
console-ui/src/pages/ConfigurationManagement/NewConfig/NewConfig.js
console-ui/src/pages/ConfigurationManagement/NewConfig/index.scss

[ISSUE#6100] Enhance UI.

---

istio/src/main/java/com/alibaba/nacos/istio/mcp/NacosToMcpResources.java

It's not caculate checksum of service in nacos 2.0, so we change use revision to determine whether the service has changed.
XX
XXXX

Fix: use revision to determine whether the service has changed

---

config/src/main/java/com/alibaba/nacos/config/server/controller/HistoryController.java

Fixes #5884 
Add the permission for history config.
add the annotation Secured for HistoryController.
enable the auth config and visit the history config with no auth.

[ISSUE #5884] Add the permission for history config.

---

console-ui/src/locales/en-US.js
console-ui/src/locales/zh-CN.js
console-ui/src/pages/ClusterManagement/ClusterNodeList/ClusterNodeList.js

[ISSES#1469] add cluster delete button
For #1469

[ISSES#1469] add cluster delete button

---

config/src/test/java/com/alibaba/nacos/config/server/auth/ExternalPermissionPersistServiceImplTest.java

[ISSUE #5092] Add unit tests for class ExternalPermissionPersistServiceImpl in nacos 2.0 

---

console-ui/src/pages/ClusterManagement/ClusterNodeList/ClusterNodeList.js

[ISSUE #6169] fix cluster page internationalization

[ISSUE #6169] fix cluster page internationalization

---

config/src/test/java/com/alibaba/nacos/config/server/auth/EmbeddedUserPersistServiceImplTest.java

[ISSUE #5092] Add unit tests for class EmbeddedUserPersistServiceImpl in nacos 2.0

---

config/src/test/java/com/alibaba/nacos/config/server/auth/EmbeddedRolePersistServiceImplTest.java

[ISSUE #5092] Add unit tests for class EmbeddedRolePersistServiceImpl in nacos 2.0 

---

config/src/test/java/com/alibaba/nacos/config/server/auth/EmbeddedPermissionPersistServiceImplTest.java

[ISSUE #5092] Add unit tests for class EmbeddedPermissionPersistServiceImpl in nacos 2.0

---

common/src/main/java/com/alibaba/nacos/common/utils/VersionUtils.java
common/src/test/java/com/alibaba/nacos/common/utils/VersionUtilsTest.java

For #5095
- simplify code
- add unit test
[before coverage](http://htmlpreview.github.io/?https://github.com/SunJiFengPlus/nacos/blob/common-coverage/doc/before/VersionUtils.html)
[after coverage](https://htmlpreview.github.io/?https://github.com/SunJiFengPlus/nacos/blob/common-coverage/doc/after/VersionUtils.html)

[ISSUE #5095]Add unit test for VersionUtils

---

config/src/test/java/com/alibaba/nacos/config/server/auth/ExternalRolePersistServiceImplTest.java

[ISSUE #5092] Add unit tests for class ExternalRolePersistServiceImpl in nacos 2.0

---

test/naming-test/src/test/java/com/alibaba/nacos/test/naming/CPInstancesAPI_ITCase.java

Improve naming IT stability.

---

console/src/main/java/com/alibaba/nacos/console/security/nacos/roles/NacosRoleServiceImpl.java
console/src/main/java/com/alibaba/nacos/console/security/nacos/users/NacosUserDetailsServiceImpl.java

[ISSUE #6204] Get data from database if user or role info not found in cache

---

common/src/main/java/com/alibaba/nacos/common/utils/StringUtils.java
common/src/test/java/com/alibaba/nacos/common/utils/StringUtilsTest.java

[ISSUE #6198] BUG nacos-common>utils>StringUtils.join method NullPointerException #6198

---

common/src/main/java/com/alibaba/nacos/common/utils/ArrayUtils.java
common/src/main/java/com/alibaba/nacos/common/utils/StringUtils.java
common/src/test/java/com/alibaba/nacos/common/utils/ArrayUtilsTest.java
common/src/test/java/com/alibaba/nacos/common/utils/StringUtilsTest.java

[ISSUE#3102] nacos-common module ArrayUtils、StringUtils

---

config/src/main/java/com/alibaba/nacos/config/server/auth/EmbeddedPermissionPersistServiceImpl.java
config/src/main/java/com/alibaba/nacos/config/server/auth/EmbeddedRolePersistServiceImpl.java
config/src/main/java/com/alibaba/nacos/config/server/auth/EmbeddedUserPersistServiceImpl.java
config/src/main/java/com/alibaba/nacos/config/server/auth/ExternalPermissionPersistServiceImpl.java
config/src/main/java/com/alibaba/nacos/config/server/auth/ExternalRolePersistServiceImpl.java
config/src/main/java/com/alibaba/nacos/config/server/auth/ExternalUserPersistServiceImpl.java
config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigOpsController.java
config/src/main/java/com/alibaba/nacos/config/server/service/capacity/GroupCapacityPersistService.java
config/src/main/java/com/alibaba/nacos/config/server/service/repository/PersistService.java

[ISSUE #6216]All SQL keywords are modified to uppercase

---

config/src/test/java/com/alibaba/nacos/config/server/auth/ExternalUserPersistServiceImplTest.java

[ISSUE #5092] Add unit tests for class ExternalUserPersistServiceImpl in nacos 2.0

---

naming/src/main/java/com/alibaba/nacos/naming/controllers/InstanceController.java
naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperator.java
naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperatorClientImpl.java
naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperatorServiceImpl.java
naming/src/main/java/com/alibaba/nacos/naming/healthcheck/heartbeat/ClientBeatExtensionHandler.java

Add SPI for ClientBeatExtensionHandler

---

common/src/main/java/com/alibaba/nacos/common/utils/RandomUtils.java
common/src/test/java/com/alibaba/nacos/common/utils/RandomUtilsTest.java

[ISSUE #6228] Add RandomUtils/RandomUtilsTest

---

common/src/main/java/com/alibaba/nacos/common/utils/DateFormatUtils.java
common/src/test/java/com/alibaba/nacos/common/utils/DateFormatUtilsTest.java

[ISSUE #6241] Add DateFormatUtils、DateFormatUtilsTest

---

common/src/main/java/com/alibaba/nacos/common/utils/TypeUtils.java
common/src/test/java/com/alibaba/nacos/common/utils/TypeUtilsTest.java

[ISSUE #6240] Add TypeUtils/TypeUtilsTest

---

common/src/test/java/com/alibaba/nacos/common/utils/CollectionUtilsTest.java

For #5095
- add unit test
[before coverage](https://htmlpreview.github.io/?https://raw.githubusercontent.com/SunJiFengPlus/nacos/common-coverage/docs/com.alibaba.nacos.common.utils/.classes/CollectionUtils.html)
[after coverage](https://htmlpreview.github.io/?https://raw.githubusercontent.com/SunJiFengPlus/nacos/common-coverage/common-coverage/current/common-current/com.alibaba.nacos.common.utils/.classes/CollectionUtils.html)

[ISSUE #5095] Add unit test for CollectionUtils

---

console/src/main/java/com/alibaba/nacos/console/security/nacos/users/NacosUserDetailsServiceImpl.java

[ISSUE #6280] Fix word spell error.

---

core/src/test/java/com/alibaba/nacos/core/remote/ClientConnectionEventListenerRegistryTest.java
core/src/test/java/com/alibaba/nacos/core/remote/ConnectionManagerTest.java
core/src/test/java/com/alibaba/nacos/core/remote/HealthCheckRequestHandlerTest.java
core/src/test/java/com/alibaba/nacos/core/remote/RequestFiltersTest.java
core/src/test/java/com/alibaba/nacos/core/remote/RequestHandlerRegistryTest.java
core/src/test/java/com/alibaba/nacos/core/remote/RpcPushServiceTest.java

- for #5094 we add unit tests by directory, module  `nacos-core`  directory `remote`, not include child directories.
XX
XXXX

[FOR 5094 remote] add unit tests in nacos-core.

---

LICENSE

fix LICENSE by https://www.apache.org/licenses/LICENSE-2.0.txt
the file md5 is 3b83ef96387f14655fc854ddc3c6bd57
XX
XXXX

fix LICENSE by https://www.apache.org/licenses/LICENSE-2.0.txt

---

naming/src/test/java/com/alibaba/nacos/naming/cluster/ServerStatusManagerTest.java
naming/src/test/java/com/alibaba/nacos/naming/cluster/remote/request/AbstractClusterRequestTest.java
naming/src/test/java/com/alibaba/nacos/naming/cluster/remote/request/DistroDataRequestTest.java
naming/src/test/java/com/alibaba/nacos/naming/cluster/remote/response/DistroDataResponseTest.java
naming/src/test/java/com/alibaba/nacos/naming/cluster/transport/JacksonSerializerTest.java
pom.xml

[ISSUE #6188]add ut for  com.alibaba.nacos.naming.cluster

---

core/src/test/java/com/alibaba/nacos/core/auth/AuthConfigTest.java
core/src/test/java/com/alibaba/nacos/core/auth/AuthFilterTest.java
core/src/test/java/com/alibaba/nacos/core/auth/RemoteRequestAuthFilterTest.java
core/src/test/java/com/alibaba/nacos/core/auth/condition/ParamRequestConditionTest.java
core/src/test/java/com/alibaba/nacos/core/auth/condition/PathRequestConditionTest.java

- for #5094 we add unit tests by directory, module  `nacos-core`  directory `auth`.
XX
XXXX

[FOR 5094 auth] add unit tests in nacos-core.

---

api/src/main/java/com/alibaba/nacos/api/naming/pojo/builder/InstanceBuilder.java
api/src/main/java/com/alibaba/nacos/api/naming/spi/generator/IdGenerator.java
api/src/test/java/com/alibaba/nacos/api/naming/pojo/builder/InstanceBuilderTest.java
naming/src/main/java/com/alibaba/nacos/naming/constants/Constants.java
naming/src/main/java/com/alibaba/nacos/naming/controllers/InstanceController.java
naming/src/main/java/com/alibaba/nacos/naming/controllers/UpgradeOpsController.java
naming/src/main/java/com/alibaba/nacos/naming/core/Instance.java
naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperator.java
naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperatorClientImpl.java
naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperatorServiceImpl.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/DefaultSelfUpgradeChecker.java
naming/src/main/java/com/alibaba/nacos/naming/pojo/instance/AppExtensionHandler.java
naming/src/main/java/com/alibaba/nacos/naming/pojo/instance/BeatInfoInstanceBuilder.java
naming/src/main/java/com/alibaba/nacos/naming/pojo/instance/DefaultInstanceIdGenerator.java
naming/src/main/java/com/alibaba/nacos/naming/pojo/instance/HttpRequestInstanceBuilder.java
naming/src/main/java/com/alibaba/nacos/naming/pojo/instance/InstanceExtensionHandler.java
naming/src/main/resources/META-INF/services/com.alibaba.nacos.naming.pojo.instance.InstanceExtensionHandler
naming/src/test/java/com/alibaba/nacos/naming/pojo/instance/BeatInfoInstanceBuilderTest.java
naming/src/test/java/com/alibaba/nacos/naming/pojo/instance/DefaultInstanceIdGeneratorTest.java
naming/src/test/java/com/alibaba/nacos/naming/pojo/instance/HttpRequestInstanceBuilderTest.java
naming/src/test/java/com/alibaba/nacos/naming/pojo/instance/MockInstanceExtensionHandler.java
naming/src/test/resources/META-INF/services/com.alibaba.nacos.naming.pojo.instance.InstanceExtensionHandler

Fix #6272 .
- Add InstanceBuilder and IdGenerator
- Add new builder for http request and client beat
- Use new builder to build api instance.

[ISSUE#6272] Refactor Instance builder to build and handler request from http.

---

core/src/main/java/com/alibaba/nacos/core/controller/ServerLoaderController.java
core/src/test/java/com/alibaba/nacos/core/controller/CoreOpsControllerTest.java
core/src/test/java/com/alibaba/nacos/core/controller/NacosClusterControllerTest.java
core/src/test/java/com/alibaba/nacos/core/controller/ServerLoaderControllerTest.java

- for #5094 we add unit tests by directory, module  `nacos-core`  directory `controller`.
XX
XXXX

[FOR 5094 controller] add unit tests in nacos-core.

---

sys/src/main/java/com/alibaba/nacos/sys/env/EnvUtil.java
sys/src/main/java/com/alibaba/nacos/sys/env/NacosAutoRefreshPropertySourceLoader.java
sys/src/main/java/com/alibaba/nacos/sys/utils/InetUtils.java

[ISSUE #6302] replace common-lang3 in nacos-sys module

---

test/core-test/src/test/java/com/alibaba/nacos/test/common/WatchFileCenter_ITCase.java
test/core-test/src/test/java/com/alibaba/nacos/test/core/cluster/MemberLookup_ITCase.java
test/naming-test/src/test/java/com/alibaba/nacos/test/naming/ClientBeat_ITCase.java

[ISSUE #6303] replace commons-lang3 in nacos-test module

---

core/src/test/java/com/alibaba/nacos/core/cluster/ServerMemberManagerTest.java
core/src/test/java/com/alibaba/nacos/core/cluster/lookup/FileConfigMemberLookupTest.java
core/src/test/java/com/alibaba/nacos/core/cluster/remote/ClusterRpcClientProxyTest.java

- for #5094 we add unit tests by directory, module  `nacos-core`  directory `cluster`.
XX
XXXX

[FOR 5094 cluster] add unit tests in nacos-core. 

---

common/src/main/java/com/alibaba/nacos/common/utils/ClassUtils.java
common/src/test/java/com/alibaba/nacos/common/utils/ClassUtilsTest.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/impl/PersistentClientOperationServiceImpl.java

For #5095
- fix typo
[before coverage](https://htmlpreview.github.io/?https://raw.githubusercontent.com/SunJiFengPlus/nacos/common-coverage/docs/com.alibaba.nacos.common.utils/.classes/ClassUtils.html)
[after coverage](https://htmlpreview.github.io/?https://raw.githubusercontent.com/SunJiFengPlus/nacos/common-coverage/common-coverage/common-current/com.alibaba.nacos.common.utils/.classes/ClassUtils.html)

[ISSUE #5095] Add unit test for ClassUtils

---

address/src/main/java/com/alibaba/nacos/address/component/AddressServerGeneratorManager.java
address/src/test/java/com/alibaba/nacos/address/SimpleHttpTestUtils.java
client/src/main/java/com/alibaba/nacos/client/utils/EnvUtil.java
common/src/main/java/com/alibaba/nacos/common/http/HttpUtils.java
common/src/main/java/com/alibaba/nacos/common/http/param/Query.java
common/src/main/java/com/alibaba/nacos/common/task/engine/NacosExecuteTaskExecuteEngine.java
common/src/main/java/com/alibaba/nacos/common/utils/ExceptionUtil.java
common/src/main/java/com/alibaba/nacos/common/utils/TypeUtils.java
config/src/main/java/com/alibaba/nacos/config/server/auth/ConfigResourceParser.java
config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigController.java
config/src/main/java/com/alibaba/nacos/config/server/manager/TaskManager.java
config/src/main/java/com/alibaba/nacos/config/server/service/ConfigSubService.java
config/src/main/java/com/alibaba/nacos/config/server/service/SwitchService.java
config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedStoragePersistServiceImpl.java
config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java
config/src/main/java/com/alibaba/nacos/config/server/utils/MD5Util.java
config/src/main/java/com/alibaba/nacos/config/server/utils/RegexParser.java
config/src/main/java/com/alibaba/nacos/config/server/utils/SimpleFlowData.java
core/src/main/java/com/alibaba/nacos/core/cluster/MemberUtil.java
core/src/main/java/com/alibaba/nacos/core/remote/control/TpsMonitorManager.java
naming/src/main/java/com/alibaba/nacos/naming/core/Instances.java
naming/src/main/java/com/alibaba/nacos/naming/core/Service.java
naming/src/main/java/com/alibaba/nacos/naming/core/ServiceManager.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/event/publisher/NamingEventPublisherFactory.java
naming/src/main/java/com/alibaba/nacos/naming/misc/NamingProxy.java
naming/src/main/java/com/alibaba/nacos/naming/web/NamingResourceParser.java
test/naming-test/src/test/java/com/alibaba/nacos/test/naming/NamingBase.java

Use StringBuilder#append(Char) to improve performance.
This commit switches to StringBuilder.append(char) instead of StringBuilder.append(String) whenever we append a single character to a StringBuilder.
XXXX

Use StringBuilder#append(Char) to improve performance

---

naming/src/main/java/com/alibaba/nacos/naming/healthcheck/heartbeat/ExpiredInstanceChecker.java

For #6295 .
- Fix instance metadata will not be removed for ip port client.

[ISSUE#6295] Fix instance metadata will not be removed for ip port client.

---

config/pom.xml
core/pom.xml
pom.xml
sys/pom.xml

[ISSUE #6314] Remove common-lang3 from pom.xml

---

api/src/main/java/com/alibaba/nacos/api/utils/NetUtils.java
api/src/test/java/com/alibaba/nacos/api/utils/NetUtilsTest.java

For #6160 
Optimization of IP address acquisition method
`com.alibaba.nacos.client.naming.local.ip` parameter be changed to `com.alibaba.nacos.client.local.ip` and `com.alibaba.nacos.client.local.preferHostname` parameter be provided to specify that IP is preferred to be replaced by hostname for config publishing.

[ISSUE alibaba#6160] Optimization of IP address acquisition method

---

api/src/main/java/com/alibaba/nacos/api/naming/selector/AbstractCmdbSelector.java
api/src/main/java/com/alibaba/nacos/api/naming/selector/Selector.java
api/src/main/java/com/alibaba/nacos/api/naming/selector/context/CmdbContext.java
api/src/main/java/com/alibaba/nacos/api/naming/selector/context/SelectorContextBuilder.java
naming/src/main/java/com/alibaba/nacos/naming/selector/LabelSelector.java
naming/src/main/java/com/alibaba/nacos/naming/selector/NoneSelector.java
naming/src/main/java/com/alibaba/nacos/naming/selector/Selector.java
naming/src/main/java/com/alibaba/nacos/naming/selector/SelectorManager.java
naming/src/test/java/com/alibaba/nacos/naming/selector/MockCmdbContextBuilder.java
naming/src/test/java/com/alibaba/nacos/naming/selector/MockSelector.java
naming/src/test/java/com/alibaba/nacos/naming/selector/SelectorManagerTest.java
naming/src/test/resources/META-INF/services/com.alibaba.nacos.api.naming.selector.Selector
naming/src/test/resources/META-INF/services/com.alibaba.nacos.api.naming.selector.context.SelectorContextBuilder

Fixes #6356, define the Selector workflow and add unit test.
XX
XXXX

[ISSUE #6356] Define the Selector workflow and add unit test.

---

pom.xml

updated the copyright time
updating the copyright time 
updated the "to" year to 2021
checked the pom.xml

Updated the copyright time in the pom.xml

---

naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/DistroConsistencyServiceImpl.java
naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/component/DistroDataStorageImpl.java

[ISSUE #6386] Stop v1 distro verification when cluster upgraded to v2.

---

resources/copyright

Fix the time in copyright.
Fix the time in copyright.
XXXX

Fix the time in copyright.

---

api/src/main/java/com/alibaba/nacos/api/naming/selector/AbstractCmdbSelector.java
api/src/main/java/com/alibaba/nacos/api/naming/selector/Selector.java
api/src/main/java/com/alibaba/nacos/api/naming/selector/context/CmdbContext.java
naming/src/main/java/com/alibaba/nacos/naming/selector/CmdbLabelSelector.java
naming/src/main/java/com/alibaba/nacos/naming/selector/SelectorManager.java
naming/src/main/java/com/alibaba/nacos/naming/selector/context/CmdbSelectorContextBuilder.java
naming/src/main/resources/META-INF/services/com.alibaba.nacos.api.naming.selector.Selector
naming/src/main/resources/META-INF/services/com.alibaba.nacos.api.naming.selector.context.SelectorContextBuilder
naming/src/test/java/com/alibaba/nacos/naming/selector/CmdbLabelSelectorTest.java
naming/src/test/java/com/alibaba/nacos/naming/selector/MockCmdbContextBuilder.java
naming/src/test/java/com/alibaba/nacos/naming/selector/MockSelector.java

Fixes #6365
Implement the built-in Selector in Nacos 1.x and add unit test.
Implement the built-in Selector in Nacos 1.x and add unit test.
- Implement `CmdbLabelSelector` instead of `LabelSelector` in Nacos 1.x.
- Implement `CmdbSelectorContext` to build `CmdbContext` for the `Selector` with `CMDB` context type.
- Add unit test for `CmdbLabelSelector` and modified unit test of `SelectorManager`.
XXXX

[ISSUE #6365] Implement the built-in Selector in Nacos 1.x and add unit test.

---

client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc/redo/NamingGrpcRedoService.java

[ISSUE #6416] fix some typo in NamingGrpcRedoService

---

naming/src/test/java/com/alibaba/nacos/naming/controllers/CatalogControllerTest.java
naming/src/test/java/com/alibaba/nacos/naming/controllers/DistroControllerTest.java
naming/src/test/java/com/alibaba/nacos/naming/controllers/HealthControllerTest.java
naming/src/test/java/com/alibaba/nacos/naming/controllers/OperatorControllerTest.java
naming/src/test/java/com/alibaba/nacos/naming/controllers/ServiceControllerTest.java

Fixes #5519 
Add unit tests to package com.alibaba.nacos.naming.controllers in nacos 2.0.
XXXX

[ISSUE #5519] Add unit tests to package com.alibaba.nacos.naming.controllers in nacos 2.0.

---

core/src/main/java/com/alibaba/nacos/core/distributed/id/SnowFlowerIdGenerator.java

improvement performance
Set the log level to warn, but  ```new SimpleDateFormat(DATETIME_PATTERN)).format(new Date(this.lastTime))``` always executes.
```
Benchmark                     Mode  Cnt       Score        Error  Units
Test.ori                   thrpt    5  535988.141 ± 105961.666  ops/s
Test.useIsDebugEnabled     thrpt    5  3903584.317 ± 590721.088  ops/s
```

improvement performance

---

naming/src/test/java/com/alibaba/nacos/naming/core/v2/cleaner/EmptyServiceAutoCleanerTest.java
naming/src/test/java/com/alibaba/nacos/naming/core/v2/cleaner/EmptyServiceAutoCleanerV2Test.java

Fixes #5520 Add unit tests for package com.alibaba.nacos.naming.core.v2.cleaner in nacos2.0.
Add unit tests for package com.alibaba.nacos.naming.core.v2.cleaner in nacos2.0.
XXXX

[ISSUE #5520] Add unit tests for package com.alibaba.nacos.naming.core.v2.cleaner in nacos2.0.

---

config/src/main/java/com/alibaba/nacos/config/server/utils/YamlParserUtil.java

The snakeyaml processor is not thread-safe.
XX
XXXX

[BUG]Fix yaml parse concurrent problem

---

core/src/main/java/com/alibaba/nacos/core/config/AbstractDynamicConfig.java
core/src/main/java/com/alibaba/nacos/core/distributed/distro/DistroConfig.java
core/src/main/java/com/alibaba/nacos/core/distributed/distro/DistroConstants.java
core/src/test/java/com/alibaba/nacos/core/distributed/distro/DistroConfigTest.java
distribution/conf/application.properties
distribution/conf/application.properties.example
naming/src/main/java/com/alibaba/nacos/naming/constants/ClientConstants.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/impl/ConnectionBasedClient.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/impl/IpPortBasedClient.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/EphemeralIpPortClientManager.java
naming/src/main/java/com/alibaba/nacos/naming/misc/ClientConfig.java
naming/src/main/java/com/alibaba/nacos/naming/push/v2/PushConfig.java
naming/src/test/java/com/alibaba/nacos/naming/core/v2/client/impl/ConnectionBasedClientTest.java
naming/src/test/java/com/alibaba/nacos/naming/core/v2/client/impl/IpPortBasedClientTest.java
naming/src/test/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/EphemeralIpPortClientManagerTest.java
naming/src/test/java/com/alibaba/nacos/naming/misc/ClientConfigTest.java

Fixes #6403 .
- Abstract AbstractDynamicConfig
- Add ClientConfig
- Use ClientConfig to remove expired client.

[ISSUE#6403] the expired time of naming client can be configured.

---

client/src/main/java/com/alibaba/nacos/client/naming/backups/FailoverReactor.java

improve the code quality for naming client FailoverReactor

---

common/src/main/java/com/alibaba/nacos/common/http/AbstractHttpClientFactory.java

Fixes #6367 
- Provide ConnectionManager
- Add IOReactorExceptionHandler to avoid IOReactor out of loop when meet unknown Network error.
XXXX

[ISSUE #6367] Add IOReactorExceptionHandler to avoid IOReactor out of loop when meet unknown Network error.

---

common/src/main/java/com/alibaba/nacos/common/utils/ConvertUtils.java

Replace "google.common.collect.Strings" API with jdk API

---

core/src/test/java/com/alibaba/nacos/core/remote/ConnectionManagerTest.java
pom.xml

Upgrade to 2.0.3

---

api/src/main/java/com/alibaba/nacos/api/naming/pojo/healthcheck/impl/Http.java
api/src/main/java/com/alibaba/nacos/api/naming/pojo/healthcheck/impl/Mysql.java
api/src/main/java/com/alibaba/nacos/api/naming/pojo/healthcheck/impl/Tcp.java

Replace "google.common.base.Objects" API with jdk API

---

consistency/src/test/java/com/alibaba/nacos/consistency/ProtoMessageUtilTest.java
consistency/src/test/java/com/alibaba/nacos/consistency/SerializeFactoryTest.java
consistency/src/test/java/com/alibaba/nacos/consistency/serialize/JacksonSerializerTest.java
consistency/src/test/java/com/alibaba/nacos/consistency/snapshot/LocalFileMetaTest.java
consistency/src/test/java/com/alibaba/nacos/consistency/snapshot/ReaderTest.java
consistency/src/test/java/com/alibaba/nacos/consistency/snapshot/WriterTest.java
core/src/test/java/com/alibaba/nacos/core/remote/ConnectionManagerTest.java

Fixes #5093 Add unit tests for module nacos-consistency in nacos 2.0.
Add unit tests for module nacos-consistency in nacos 2.0.
XXXX

[ISSUE #5093] Add unit tests for module nacos-consistency in nacos 2.0.

---

config/src/main/java/com/alibaba/nacos/config/server/service/capacity/CapacityService.java

replace "google.common.base.Stopwatch" API with Spring API .
for #6499

replace "google.common.base.Stopwatch" API with Spring API

---

pom.xml

Upgrade 2.1.0-snapshot

---

naming/src/main/java/com/alibaba/nacos/naming/utils/ServiceUtil.java

adding final to modify the utility class
added a final key word 
checked the code 

add final to modify the utility class

---

config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedStoragePersistServiceImpl.java
config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java
core/src/main/java/com/alibaba/nacos/core/distributed/raft/JRaftServer.java

Replace "google.common.base.Joiner" API with jdk API.
for #6497

Replace "google.common.base.Joiner" API with jdk API

---

client/src/main/java/com/alibaba/nacos/client/config/impl/Limiter.java
common/src/main/java/com/alibaba/nacos/common/cache/Cache.java
common/src/main/java/com/alibaba/nacos/common/cache/builder/CacheBuilder.java
common/src/main/java/com/alibaba/nacos/common/cache/builder/CacheItemProperties.java
common/src/main/java/com/alibaba/nacos/common/cache/decorators/AutoExpireCache.java
common/src/main/java/com/alibaba/nacos/common/cache/decorators/LruCache.java
common/src/main/java/com/alibaba/nacos/common/cache/decorators/SynchronizedCache.java
common/src/main/java/com/alibaba/nacos/common/cache/impl/SimpleCache.java
common/src/test/java/com/alibaba/nacos/common/cache/AutoExpireCacheTest.java
common/src/test/java/com/alibaba/nacos/common/cache/LruCacheTest.java
common/src/test/java/com/alibaba/nacos/common/cache/SimpleCacheTest.java
core/src/main/java/com/alibaba/nacos/core/utils/StringPool.java

Refactor the cache to replace guava. for #6503

Refactor the cache to replace guava

---

api/src/main/java/com/alibaba/nacos/api/common/Constants.java
api/src/main/java/com/alibaba/nacos/api/config/ConfigFactory.java
api/src/main/java/com/alibaba/nacos/api/config/ConfigType.java
api/src/main/java/com/alibaba/nacos/api/config/remote/request/AbstractConfigRequest.java
api/src/main/java/com/alibaba/nacos/api/config/remote/request/ClientConfigMetricRequest.java
api/src/main/java/com/alibaba/nacos/api/config/remote/request/ConfigChangeNotifyRequest.java
api/src/main/java/com/alibaba/nacos/api/config/remote/request/ConfigQueryRequest.java

#6487 exprot the constant in directory config.
export the constant.
XXXX

[FOR #6487] [nacos-api] export the constant in the directory config.

---

naming/src/test/java/com/alibaba/nacos/naming/core/CatalogServiceV2ImplTest.java
naming/src/test/java/com/alibaba/nacos/naming/core/HealthOperatorV1ImplTest.java
naming/src/test/java/com/alibaba/nacos/naming/core/HealthOperatorV2ImplTest.java
naming/src/test/java/com/alibaba/nacos/naming/core/InstanceOperatorClientImplTest.java
naming/src/test/java/com/alibaba/nacos/naming/core/ServiceOperatorV2ImplTest.java

Fixes #6543 
Add unit tests for package com.alibaba.nacos.naming.core.*.
- Add the unit tests of left class in core.*.
XXXX

[ISSUE #6543] Add unit tests for package com.alibaba.nacos.naming.core.*.

---

common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClient.java
common/src/main/java/com/alibaba/nacos/common/utils/ThreadFactoryBuilder.java
common/src/test/java/com/alibaba/nacos/common/utils/ThreadFactoryBuilderTest.java
core/src/main/java/com/alibaba/nacos/core/utils/GlobalExecutor.java

Replace "ThreadFactoryBuilder" API with jdk API and add unit test .
for #6529

Replace "ThreadFactoryBuilder" API with jdk API and add unit test

---

api/src/main/java/com/alibaba/nacos/api/common/Constants.java
api/src/main/java/com/alibaba/nacos/api/naming/remote/request/AbstractNamingRequest.java
api/src/main/java/com/alibaba/nacos/api/naming/remote/request/NotifySubscriberRequest.java
api/src/main/java/com/alibaba/nacos/api/naming/selector/AbstractCmdbSelector.java

#6487 exprot the constant in directory naming.
XX
XXXX

[FOR #6487] [nacos-api] export the constant in the directory naming.

---

api/src/main/java/com/alibaba/nacos/api/common/Constants.java
api/src/main/java/com/alibaba/nacos/api/exception/runtime/NacosDeserializationException.java
api/src/main/java/com/alibaba/nacos/api/exception/runtime/NacosSerializationException.java
api/src/main/java/com/alibaba/nacos/api/remote/request/ClientDetectionRequest.java
api/src/main/java/com/alibaba/nacos/api/remote/request/ConnectResetRequest.java
api/src/main/java/com/alibaba/nacos/api/remote/request/InternalRequest.java

Fixes #6487 exprot the constant in directory remote.
XX
XXXX

[ISSUE #6487] [nacos-api] export the constant in the directory remote.

---

api/pom.xml
config/pom.xml
istio/pom.xml
naming/pom.xml

remove pom dependency for issue #6533

Remove pom dependency

---

common/src/main/java/com/alibaba/nacos/common/utils/CollectionUtils.java
common/src/test/java/com/alibaba/nacos/common/remote/client/RpcClientFactoryTest.java
common/src/test/java/com/alibaba/nacos/common/utils/CollectionUtilsTest.java

remove guava Iterables for #6562

remove guava Iterables

---

naming/src/main/java/com/alibaba/nacos/naming/pojo/Subscriber.java

[ISSUE #6581] fix json deserialization error of ServiceController subscribers interface

---

config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedStoragePersistServiceImpl.java

Fixes #6347
The page SQL `OFFSET 0 ROWS FETCH NEXT ? ROWS ONLY` can not work deleting data in Derby, so change it to support the Derby.
change the delete sql to `delete from his_config_info where id in ( select id from his_config_info where gmt_modified < ? OFFSET 0 ROWS FETCH NEXT ? ROWS ONLY);`
XXXX

[ISSUE #6347] Change the delete by page SQL to support the Derby.

---

client/src/test/java/com/alibaba/nacos/client/config/impl/ClientWorkerTest.java
common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClient.java
common/src/main/java/com/alibaba/nacos/common/utils/CollectionUtils.java
common/src/test/java/com/alibaba/nacos/common/remote/client/RpcClientTest.java

For #6595
- replace explicit type argument with <>
- replace anonymous class with lambda
- remove redundant initializer
- format comment & log and fix typo
- add unit test to RpcClient::resolveServerInfo
- extend CollectionUtils::getOrDefault
- simplify RpcClient::resolveServerInfo
-  remove unused variable

[ISSUE #6595] Optimize RpcClient

---

client/src/test/java/com/alibaba/nacos/client/config/impl/CacheDataTest.java

Remove expired TODO

---

common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClient.java
common/src/test/java/com/alibaba/nacos/common/remote/client/RpcClientTest.java

For #6544 
- fix incorrect login
- add unit test

[ISSUE #6544] Fix RpcClient::requestFuture incorrect logic

---

naming/src/main/java/com/alibaba/nacos/naming/core/ServiceOperatorV2Impl.java

Fixes #6535 
throw the service not find exception in Nacos 2.x when service does not exist.

[ISSUE #6535] throw the NacosException in 2.x to keep same with 1.x when Service doesn't exist.

---

common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClientFactory.java

Fixes  #6433
Simple the logic of create RpcClient in RpcClientFactory.
use `map.computeIfAbsent` replace `map.compute` 
XXXX

[ISSUE #6433] Simple the logic of create RpcClient in RpcClientFactory.

---

console-ui/src/pages/ConfigurationManagement/ConfigEditor/NewConfigEditor.js

Remove unused code; Use Camel-Case;Optimize if statement;

Remove unused code; Use Camel-Case;Optimize if statement;

---

core/src/main/java/com/alibaba/nacos/core/remote/circuitbreaker/CircuitBreaker.java
core/src/main/java/com/alibaba/nacos/core/remote/circuitbreaker/CircuitBreakerConfig.java
core/src/main/java/com/alibaba/nacos/core/remote/circuitbreaker/CircuitBreakerInfo.java
core/src/main/java/com/alibaba/nacos/core/remote/circuitbreaker/CircuitBreakerRule.java
core/src/main/java/com/alibaba/nacos/core/remote/circuitbreaker/CircuitBreakerStatus.java
core/src/main/java/com/alibaba/nacos/core/remote/circuitbreaker/ConfigLoader.java
core/src/main/java/com/alibaba/nacos/core/remote/circuitbreaker/rules/impl/TpsDefaultRule.java
core/src/main/resources/META-INF/services/com.alibaba.nacos.core.remote.circuitbreaker.CircuitBreakerRule
core/src/test/java/com/alibaba/nacos/core/remote/circuitbreaker/CircuitBreakerTest.java

Add a brief framework for Circuit Breaker.
Add Circuit Breaker and its unit test cases.
* [✅] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [✅] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [✅] Write necessary unit-test to verify your logic correction, more mock a little better when cross …

Summer2021 issue#5698

---

console-ui/src/pages/ConfigurationManagement/ConfigEditor/NewConfigEditor.js
console-ui/src/pages/ConfigurationManagement/ConfigurationManagement/ConfigurationManagement.js

FIX #6625
When switching namespaces, the search criteria will be cleared.
When switching namespaces, the search criteria are cleared.

FIX #6625 When switching namespaces, search criteria do not work

---

naming/src/test/java/com/alibaba/nacos/naming/core/v2/service/impl/PersistentClientOperationServiceImplTest.java

fixes #6643 
Add unit tests for package com.alibaba.nacos.naming.core.v2.service.
XXXX

[ISSUE #6643] Add unit tests for package com.alibaba.nacos.naming.core.v2.service.

---

README.md

update enterprise info

---

client/src/main/java/com/alibaba/nacos/client/naming/cache/ServiceInfoHolder.java
common/src/main/java/com/alibaba/nacos/common/notify/DefaultPublisher.java

the warn log is incomplete, because it loses the event value.
add the "event" value to the LOGGER.warn method.

complete the warn log

---

naming/src/main/java/com/alibaba/nacos/naming/core/ServiceOperatorV2Impl.java

Fixes #6703 
- check if the service exist before delete it.
XXXX

[ISSUE #6703] when delete an nonexistent, return services not exist error.

---

distribution/bin/startup.sh

[ISSUE #6609] fix the shell issue using jdk more than 8.

---

api/src/main/java/com/alibaba/nacos/api/config/CryptoExecutor.java

[ISSUE#5695] Add a plugin SPI for configuration encryption and decryption for Nacos 2.0

---

pom.xml

Please do not create a Pull Request without creating an issue first
Upgrade jraft version to 1.3.8.
very useful.
https://github.com/sofastack/sofa-jraft/pull/586
https://github.com/sofastack/sofa-jraft/pull/629

Upgrade jraft version to 1.3.8

---

istio/src/main/java/com/alibaba/nacos/istio/mcp/NacosMcpService.java

Fix empty watched status for mcp service

---

naming/src/test/java/com/alibaba/nacos/naming/core/v2/upgrade/UpgradeStatesTest.java
naming/src/test/java/com/alibaba/nacos/naming/core/v2/upgrade/doublewrite/delay/DoubleWriteEventListenerTest.java

[ISSUE #6783] Add unit tests for package com.alibaba.nacos.naming.core.v2.upgrade.

---

istio/src/main/java/com/alibaba/nacos/istio/api/ApiConstants.java
istio/src/main/java/com/alibaba/nacos/istio/common/EventProcessor.java
istio/src/main/java/com/alibaba/nacos/istio/common/NacosResourceManager.java
istio/src/main/java/com/alibaba/nacos/istio/common/NacosServiceInfoResourceWatcher.java
istio/src/main/java/com/alibaba/nacos/istio/common/ResourceSnapshot.java
istio/src/main/java/com/alibaba/nacos/istio/mcp/NacosMcpService.java
istio/src/main/java/com/alibaba/nacos/istio/server/IstioServer.java
istio/src/main/java/com/alibaba/nacos/istio/util/IstioExecutor.java
istio/src/main/java/com/alibaba/nacos/istio/xds/NacosXdsService.java

Fix https://github.com/alibaba/nacos/issues/6798.
XXXXX
XX
XXXX

[#6798] Support to merge nacos resource update events to avoid more computation.

---

console-ui/src/components/ShowCodeing/ShowCodeing.js
console-ui/src/components/ShowCodeing/ShowServiceCodeing.js

[ISSUE #6817] sample code add C#

---

client/src/main/java/com/alibaba/nacos/client/auth/AbstractClientAuthService.java
client/src/main/java/com/alibaba/nacos/client/auth/ClientAuthPluginManager.java
client/src/main/java/com/alibaba/nacos/client/auth/ClientAuthService.java
client/src/main/java/com/alibaba/nacos/client/auth/LoginAuthConstant.java
client/src/main/java/com/alibaba/nacos/client/auth/LoginIdentityContext.java
client/src/main/java/com/alibaba/nacos/client/auth/NacosClientAuthServiceImpl.java
client/src/main/java/com/alibaba/nacos/client/auth/process/HttpLoginProcessor.java
client/src/main/java/com/alibaba/nacos/client/auth/process/LoginProcessor.java
client/src/main/resources/META-INF/services/com.alibaba.nacos.client.auth.AbstractClientAuthService
client/src/test/java/com/alibaba/nacos/client/auth/ClientAuthPluginManagerTest.java
client/src/test/java/com/alibaba/nacos/client/auth/NacosClientAuthServiceImplTest.java

Previous design only supports a authentication plugin(username and password), and consider grpc request. However, current Nacos don't support grpc in client.
This design will load all available authentication plugins, put all relevant authentication keys into a context and return to user.
> #5696
XX
XXXX

[ISSUE#5696] Add auth client: plugin and implement

---

naming/src/test/java/com/alibaba/nacos/naming/remote/rpc/filter/GrpcRequestFilterTest.java

For #6894
- add the unit test of com.alibaba.nacos.naming.remote.rpc.filter
XXXX

[FOR #6894] add the unit test of com.alibaba.nacos.naming.remote.rpc.filter.

---

naming/src/test/java/com/alibaba/nacos/naming/remote/udp/UdpConnectorTest.java

For #6894 
- add the unit test of com.alibaba.nacos.naming.remote.udp
XXXX

[FOR #6894] add the unit test of com.alibaba.nacos.naming.remote.udp.

---

README.md

Add Nacos-on-cloud information

---

config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigController.java
config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigPublishRequestHandler.java
config/src/main/java/com/alibaba/nacos/config/server/service/repository/PersistService.java
config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedStoragePersistServiceImpl.java
config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java

[ISSUE#5695] Summer2021 The clone function is compatible with configuration encryption and decryption

---

naming/src/test/java/com/alibaba/nacos/naming/remote/rpc/handler/DistroDataRequestHandlerTest.java
naming/src/test/java/com/alibaba/nacos/naming/remote/rpc/handler/InstanceRequestHandlerTest.java
naming/src/test/java/com/alibaba/nacos/naming/remote/rpc/handler/ServiceListRequestHandlerTest.java
naming/src/test/java/com/alibaba/nacos/naming/remote/rpc/handler/ServiceQueryRequestHandlerTest.java
naming/src/test/java/com/alibaba/nacos/naming/remote/rpc/handler/SubscribeServiceRequestHandlerTest.java

Fixes #6894
- add the unit test of com.alibaba.nacos.naming.remote.rpc.handler.
XXXX

[ISSUE #6894] add the unit test of com.alibaba.nacos.naming.remote.rpc.handler.

---

config/src/test/java/com/alibaba/nacos/config/server/auth/ExternalRolePersistServiceImplTest.java
config/src/test/java/com/alibaba/nacos/config/server/auth/ExternalUserPersistServiceImplTest.java

For #6957
- fix unit test fail

[ISSUE #6957] fix unit test fail

---

common/src/test/java/com/alibaba/nacos/common/codec/Base64Test.java

[ISSUE #5095] Add testcase for common base64

---

common/src/main/java/com/alibaba/nacos/common/cache/builder/CacheBuilder.java
common/src/test/java/com/alibaba/nacos/common/cache/builder/CacheBuilderTest.java
common/src/test/java/com/alibaba/nacos/common/cache/decorators/AutoExpireCacheTest.java
common/src/test/java/com/alibaba/nacos/common/cache/decorators/LruCacheTest.java
common/src/test/java/com/alibaba/nacos/common/cache/decorators/SynchronizedCacheTest.java
common/src/test/java/com/alibaba/nacos/common/cache/impl/SimpleCacheTest.java

[ISSUE #5095] Add some testcases for common cache

---

auth/src/main/java/com/alibaba/nacos/auth/configuration/ConditionOnExternalStorage.java
auth/src/main/java/com/alibaba/nacos/auth/constant/PropertiesConstant.java
auth/src/main/java/com/alibaba/nacos/auth/persist/ExternalPermissionPersistServiceImpl.java
auth/src/main/java/com/alibaba/nacos/auth/persist/ExternalRolePersistServiceImpl.java
auth/src/main/java/com/alibaba/nacos/auth/persist/ExternalUserPersistServiceImpl.java
auth/src/main/java/com/alibaba/nacos/auth/persist/datasource/DataSourcePoolProperties.java
auth/src/main/java/com/alibaba/nacos/auth/persist/datasource/DataSourceService.java
auth/src/main/java/com/alibaba/nacos/auth/persist/datasource/DynamicDataSource.java
auth/src/main/java/com/alibaba/nacos/auth/persist/datasource/ExternalDataSourceProperties.java
auth/src/main/java/com/alibaba/nacos/auth/persist/datasource/ExternalDataSourceServiceImpl.java
auth/src/main/java/com/alibaba/nacos/auth/persist/datasource/LocalDataSourceServiceImpl.java
auth/src/main/java/com/alibaba/nacos/auth/persist/repository/PaginationHelper.java
auth/src/main/java/com/alibaba/nacos/auth/persist/repository/externel/ExternalStoragePaginationHelperImpl.java
auth/src/main/java/com/alibaba/nacos/auth/persist/repository/externel/ExternalStoragePersistServiceImpl.java
auth/src/main/java/com/alibaba/nacos/auth/util/AuthPropertyUtil.java
auth/src/main/java/com/alibaba/nacos/auth/util/LogUtil.java
auth/src/main/java/com/alibaba/nacos/auth/util/Preconditions.java
auth/src/test/java/com/alibaba/nacos/auth/persist/ExternalPermissionPersistServiceImplTest.java
auth/src/test/java/com/alibaba/nacos/auth/persist/ExternalRolePersistServiceImplTest.java
auth/src/test/java/com/alibaba/nacos/auth/persist/ExternalUserPersistServiceImplTest.java
auth/src/test/java/com/alibaba/nacos/auth/persist/datasource/DataSourcePoolPropertiesTest.java
auth/src/test/java/com/alibaba/nacos/auth/persist/datasource/ExternalDataSourcePropertiesTest.java

Add MySQL DataBase
> #5696
XX
XXXX

[ISSUE#5696] Add MySQL DataBase

---

client/src/main/java/com/alibaba/nacos/client/config/AesCrypto.java

[ISSUE#5695] Summer2021 Change the AES encryption mode

---

client/src/test/java/com/alibaba/nacos/client/config/filter/impl/ConfigCryptoFilterTest.java

[ISSUE#5695] Summer2021 add unit test for ConfigCryptoFilter

---

api/src/test/java/com/alibaba/nacos/api/config/CryptoExecutorTest.java

[ISSUE#5695] Summer2021 add unit test for CryptoExecutor

---

api/src/test/java/com/alibaba/nacos/api/config/CryptoManagerTest.java

[ISSUE#5695] Summer2021  add unit test for CryptoManager

---

client/src/test/java/com/alibaba/nacos/client/config/AesCryptoTest.java

[ISSUE#5695] Summer2021 add unit test for AesCrypto

---

auth/pom.xml
auth/src/main/java/com/alibaba/nacos/auth/configuration/ConditionOnEmbeddedStorage.java
auth/src/main/java/com/alibaba/nacos/auth/configuration/ConditionStandaloneEmbedStorage.java
auth/src/main/java/com/alibaba/nacos/auth/persist/AuthEmbeddedPermissionPersistServiceImpl.java
auth/src/main/java/com/alibaba/nacos/auth/persist/AuthEmbeddedRolePersistServiceImpl.java
auth/src/main/java/com/alibaba/nacos/auth/persist/AuthEmbeddedUserPersistServiceImpl.java
auth/src/main/java/com/alibaba/nacos/auth/persist/AuthExternalPermissionPersistServiceImpl.java
auth/src/main/java/com/alibaba/nacos/auth/persist/AuthExternalRolePersistServiceImpl.java
auth/src/main/java/com/alibaba/nacos/auth/persist/AuthExternalUserPersistServiceImpl.java
auth/src/main/java/com/alibaba/nacos/auth/persist/datasource/AuthDynamicDataSource.java
auth/src/main/java/com/alibaba/nacos/auth/persist/datasource/ExternalDataSourceServiceImpl.java
auth/src/main/java/com/alibaba/nacos/auth/persist/repository/embedded/AuthEmbeddedStoragePersistServiceImpl.java
auth/src/main/java/com/alibaba/nacos/auth/persist/repository/embedded/AuthStandaloneDatabaseOperateImpl.java
auth/src/main/java/com/alibaba/nacos/auth/persist/repository/embedded/BaseDatabaseOperate.java
auth/src/main/java/com/alibaba/nacos/auth/persist/repository/embedded/DatabaseOperate.java
auth/src/main/java/com/alibaba/nacos/auth/persist/repository/embedded/EmbeddedPaginationHelperImpl.java
auth/src/main/java/com/alibaba/nacos/auth/persist/repository/externel/AuthExternalStoragePersistServiceImpl.java
auth/src/main/java/com/alibaba/nacos/auth/persist/sql/EmbeddedStorageContextUtils.java
auth/src/main/java/com/alibaba/nacos/auth/persist/sql/ModifyRequest.java
auth/src/main/resources/META-INF/spring.factories
auth/src/test/java/com/alibaba/nacos/auth/persist/AuthEmbeddedPermissionPersistServiceImplTest.java
auth/src/test/java/com/alibaba/nacos/auth/persist/AuthEmbeddedRolePersistServiceImplTest.java
auth/src/test/java/com/alibaba/nacos/auth/persist/AuthEmbeddedUserPersistServiceImplTest.java
auth/src/test/java/com/alibaba/nacos/auth/persist/AuthExternalPermissionPersistServiceImplTest.java
auth/src/test/java/com/alibaba/nacos/auth/persist/AuthExternalRolePersistServiceImplTest.java
auth/src/test/java/com/alibaba/nacos/auth/persist/AuthExternalUserPersistServiceImplTest.java
auth/src/test/java/com/alibaba/nacos/auth/persist/datasource/DataSourcePoolPropertiesTest.java

Add derby database and rename relative class
> #5696
XX
XXXX

[ISSUE#5696] add derby database

---

config/src/test/java/com/alibaba/nacos/config/server/controller/CommunicationControllerTest.java

[ISSUE #5092] add unit tests for CommunicationController in nacos-config

---

config/src/main/java/com/alibaba/nacos/config/server/controller/ClientMetricsController.java
config/src/test/java/com/alibaba/nacos/config/server/controller/ClientMetricsControllerTest.java

[ISSUE #5092] add unit tests for ClientMetricsController in nacos-config

---

config/src/test/java/com/alibaba/nacos/config/server/controller/CapacityControllerTest.java

[ISSUE #5092] add unit tests for CapacityController in nacos-config

---

client/src/main/java/com/alibaba/nacos/client/naming/core/ServerListManager.java

Not publish server list change event when the servers is not change.

Not publish server list change event when the servers is not change.

---

client/src/main/java/com/alibaba/nacos/client/utils/TemplateUtils.java

re-commit the pr #7054 
- fix the typos in TemplateUtils.java
XXXX

[ISSUE #7054] fix the typos in TemplateUtils.java.

---

api/src/main/java/com/alibaba/nacos/api/ability/ClientAbilities.java
api/src/main/java/com/alibaba/nacos/api/ability/ServerAbilities.java
api/src/main/java/com/alibaba/nacos/api/ability/initializer/AbilityInitializer.java
api/src/main/java/com/alibaba/nacos/api/config/ability/ClientConfigAbility.java
api/src/main/java/com/alibaba/nacos/api/config/ability/ServerConfigAbility.java
api/src/main/java/com/alibaba/nacos/api/naming/ability/ClientNamingAbility.java
api/src/main/java/com/alibaba/nacos/api/naming/ability/ServerNamingAbility.java
api/src/main/java/com/alibaba/nacos/api/remote/ability/ClientRemoteAbility.java
api/src/main/java/com/alibaba/nacos/api/remote/ability/ServerRemoteAbility.java
api/src/test/java/com/alibaba/nacos/api/naming/ability/ServerNamingAbilityTest.java
core/src/main/java/com/alibaba/nacos/core/ability/RemoteAbilityInitializer.java
core/src/main/java/com/alibaba/nacos/core/ability/ServerAbilityInitializer.java
core/src/main/java/com/alibaba/nacos/core/ability/ServerAbilityInitializerHolder.java
core/src/main/java/com/alibaba/nacos/core/cluster/ServerMemberManager.java
core/src/main/resources/META-INF/services/com.alibaba.nacos.core.ability.ServerAbilityInitializer
core/src/test/java/com/alibaba/nacos/core/ability/RemoteAbilityInitializerTest.java
core/src/test/java/com/alibaba/nacos/core/ability/ServerAbilityInitializerHolderTest.java
core/src/test/java/com/alibaba/nacos/core/cluster/ServerMemberManagerTest.java
core/src/test/java/com/alibaba/nacos/core/cluster/remote/ClusterRpcClientProxyTest.java
core/src/test/java/com/alibaba/nacos/core/controller/ServerLoaderControllerTest.java
naming/src/main/java/com/alibaba/nacos/naming/ability/NamingAbilityInitializer.java
naming/src/main/resources/META-INF/services/com.alibaba.nacos.core.ability.ServerAbilityInitializer
naming/src/test/java/com/alibaba/nacos/naming/ability/NamingAbilityInitializerTest.java

Refactor Server ability init login with SPI.

---

config/src/test/java/com/alibaba/nacos/config/server/controller/ConfigControllerTest.java

[ISSUE #5092] add unit tests for ConfigController in nacos-config

---

client/src/main/java/com/alibaba/nacos/client/config/impl/ServerListManager.java

[ISSUE #7220] replace with lambda

---

config/src/test/java/com/alibaba/nacos/config/server/controller/ListenerControllerTest.java

[ISSUE #5092] add unit tests for ListenerController in nacos-config

---

config/src/test/java/com/alibaba/nacos/config/server/controller/HistoryControllerTest.java

[ISSUE #5092] add unit tests for HistoryController in nacos-config

---

config/src/test/java/com/alibaba/nacos/config/server/controller/ConfigOpsControllerTest.java

[ISSUE #5092] add unit tests for ConfigOpsController in nacos-config

---

client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java

[ISSUE #7217] replace with lambda

---

auth/src/main/java/com/alibaba/nacos/auth/common/AuthConfigs.java
console/src/test/java/com/alibaba/nacos/console/security/nacos/JwtTokenManagerTest.java

- Add catch block, return getBytes result if base64 decode failed
- Add JwtTokenManager unit test
Closes #7203
nacos.core.auth.default.token.secret.key properties can't contains special characters.
- Add catch block, return getBytes result if base64 decode failed
- Add JwtTokenManager unit test
- secret key contains  special characters such as '$'  then JwtTokenManager don't throw any exception when call the createToken method

[ISSUE #7203] FIx AuthConfigs illegal base64 character

---

istio/src/main/java/com/alibaba/nacos/istio/common/NacosResourceManager.java
istio/src/main/java/com/alibaba/nacos/istio/common/ResourceSnapshot.java
istio/src/main/java/com/alibaba/nacos/istio/misc/IstioConfig.java
istio/src/main/java/com/alibaba/nacos/istio/util/IstioCrdUtil.java

Customize the hostname synchronized to istio
1. instance metadata set `istio.hostname`
2. enable`nacos.istio.mcp.server.enabled=true`

Fix #6973 problem. customer istio sync hostname

---

config/src/test/java/com/alibaba/nacos/config/server/controller/ConfigServletInnerTest.java

[ISSUE #5092] add unit test for ConfigServletInner in nacos-config

---

client/src/main/java/com/alibaba/nacos/client/config/NacosConfigService.java

fix(#7188): LocalConfigInfoProcessor.getSnapshot need encryptedDataKey with LocalEncryptedDataKeyProcessor.getEncryptDataKeySnapshot.

---

api/src/main/proto/nacos_grpc_service.proto

For #7193, Remove useless service declaration "RequestStream" in grpc proto file
only remove service RequestStream declaration in nacos_grpc_service.proto file.
XXXX

[ISSUE #7163] remove useless service declaration "RequestStream" in grpc proto file

---

naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/impl/EphemeralClientOperationServiceImpl.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/impl/PersistentClientOperationServiceImpl.java
naming/src/test/java/com/alibaba/nacos/naming/core/v2/service/impl/EphemeralClientOperationServiceImplTest.java
naming/src/test/java/com/alibaba/nacos/naming/core/v2/service/impl/PersistentClientOperationServiceImplTest.java
test/naming-test/src/test/java/com/alibaba/nacos/test/naming/CPInstancesAPI_ITCase.java

Fix #6846 .
Make one service keep one kind of instance (ephemeral or persistent).

[ISSUE#6846] Make one service keep one kind of instance (ephemeral or persistent).

---

naming/src/main/java/com/alibaba/nacos/naming/core/ServiceOperatorV2Impl.java
naming/src/main/java/com/alibaba/nacos/naming/pojo/ServiceDetailInfo.java

Add ephmeral attribute in v2 service query api.

---

core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcRequestAcceptor.java

Typo in word 'accetor'

---

config/src/test/java/com/alibaba/nacos/config/server/utils/DiskUtilsTest.java

[ISSUE #5092] add unit test for DiskUtils in nacos-config

---

client/src/main/java/com/alibaba/nacos/client/constant/Constants.java
client/src/main/java/com/alibaba/nacos/client/logging/AbstractNacosLogging.java

[ISSUE #7229] Optimize the constants to the logging package for the client module. Part 2

---

client/src/main/java/com/alibaba/nacos/client/constant/Constants.java
client/src/main/java/com/alibaba/nacos/client/utils/AppNameUtils.java
client/src/main/java/com/alibaba/nacos/client/utils/TenantUtil.java

[ISSUE #7229] Optimize the constants to the utils package for the client module. Part 5

---

config/src/main/java/com/alibaba/nacos/config/server/utils/RequestUtil.java
console/src/main/java/com/alibaba/nacos/console/security/nacos/NacosAuthManager.java

修复 #7141 的问题
后台管理系统登录后, 在NacosAuthManager.login 方法中, 将登录的用户信息存于 HttpServletRequest.setAttribute 。
此种方式在ajax异步请求时， `RequestUtil.getUser`不能成功的访问到用户信息, 从而不能记录用户更新信息
更换为 `req.getSession().setAttribute` 
将用户数据从 HttpServletRequest 中迁移到 HttpSession 中进行保存
已验证在修改和删除时能成功记录

fix: can't update user info to db , fix issue:#7141

---

config/src/test/java/com/alibaba/nacos/config/server/utils/AccumulateStatCountTest.java
config/src/test/java/com/alibaba/nacos/config/server/utils/AppNameUtilsTest.java
config/src/test/java/com/alibaba/nacos/config/server/utils/ContentUtilsTest.java

[ISSUE #5092] add unit test for utils in nacos-config

---

naming/src/main/java/com/alibaba/nacos/naming/pojo/Subscriber.java

fix(#7282): Subscriber do not have default constructor

---

client/src/main/java/com/alibaba/nacos/client/naming/core/ServiceInfoUpdateService.java

In final code block, it will execute self again.  Although service is not subscribed again.

Fix update task can't stop after unsubscribe.

---

client/src/main/java/com/alibaba/nacos/client/naming/utils/InitUtils.java

[ISSUE #7308] replace with lambda

---

client/src/main/java/com/alibaba/nacos/client/naming/cache/ServiceInfoHolder.java

[ISSUE #7310] replace with <>

---

client/src/main/java/com/alibaba/nacos/client/config/AesCrypto.java

[ISSUE #7313] IV initial vector size is 16 bytes, take the first 16 bytes of secret Key

---

config/src/test/java/com/alibaba/nacos/config/server/remote/ConfigQueryRequestHandlerTest.java

[ISSUE #5092]Add unit tests for class ConfigQueryRequestHandler in nacos 2.0

---

config/src/test/java/com/alibaba/nacos/config/server/remote/ConfigPublishRequestHandlerTest.java

[ISSUE #5092]Add unit tests for class ConfigPublishRequestHandlerTest in nacos 2.0

---

common/src/main/java/com/alibaba/nacos/common/executor/ThreadPoolManager.java

我在阅读源码的时候发现一个隐藏的bug, 并且提交了issue #7333 。代码进行优化，并尝试提交一次pr进行学习。 pr流程不是很熟悉通过这次机会进行学习。
XX
XXXX

优化代码。防止并发bug

---

pom.xml

upgrade log4j to 2.15.0

---

pom.xml

Fix for bug #7414

---

common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClient.java
common/src/test/java/com/alibaba/nacos/common/remote/client/RpcClientTest.java

- add unit test for this issue
Close #7411 
XXXXX
XX
XXXX

[ISSUE #7411] fix NPE when the RpcClient shutdown

---

client/src/main/java/com/alibaba/nacos/client/naming/cache/ServiceInfoHolder.java

If new data's lastRefTime < old data's lastRefTime, should't process it.

Fix push again problem.

---

config/src/test/java/com/alibaba/nacos/config/server/service/capacity/CapacityServiceTest.java

[ISSUE #5092] add unit test for CapacityService in service.

---

config/src/test/java/com/alibaba/nacos/config/server/utils/RegexParserTest.java
config/src/test/java/com/alibaba/nacos/config/server/utils/RequestUtilTest.java
config/src/test/java/com/alibaba/nacos/config/server/utils/ResponseUtilTest.java

[ISSUE #5092] add unit test for Request/Response/RegexParser in util

---

core/src/main/java/com/alibaba/nacos/core/distributed/ProtocolManager.java

fix : #7474 
Remove meaningless parentheses in `ProtocolManager#initCPProtocol()` ``ProtocolManager#initAPProtocol`
Remove meaningless parentheses
XXXX

[ISSUE #7474]Remove meaningless parentheses

---

config/src/test/java/com/alibaba/nacos/config/server/utils/MD5UtilTest.java

[ISSUE #5092] add unit test for the MD5UtilTest#getClientMd5Map

---

pom.xml

fix log4j to safe version
change log4j version
fix log4j version to 2.17.0 , [#7468](https://github.com/alibaba/nacos/issues/7468)
no

[ISSUE #7468] upgrade log4j to 2.17.0 for develop 

---

config/src/main/java/com/alibaba/nacos/config/server/utils/ConfigExecutor.java
config/src/test/java/com/alibaba/nacos/config/server/utils/ConfigExecutorTest.java

[ISSUE #5092] add unit test for ConfigExecutor in util.

---

pom.xml

upgrade log4j to 2.17.0 for v1.x-develop #7476

---

config/src/test/java/com/alibaba/nacos/config/server/utils/TraceLogUtilTest.java

[ISSUE #5092] add unit test for TraceLogUtilTest in util

---

api/src/main/java/com/alibaba/nacos/api/remote/PayloadRegistry.java
core/src/main/java/com/alibaba/nacos/core/remote/BaseRpcServer.java
core/src/main/java/com/alibaba/nacos/core/remote/ConnectionManager.java
core/src/main/java/com/alibaba/nacos/core/remote/grpc/BaseGrpcServer.java

Strengthen the code

---

core/src/main/java/com/alibaba/nacos/core/listener/StartingApplicationListener.java

Unnecessary 'toString()' call

---

pom.xml

fix logback bug version 1.2.9  
fix #7499

update logback version 1.2.9

---

pom.xml

translate chinese into englishh. make our code international.
XX
XXXX

[code quality] [nacos-all] translate chinese into english

---

client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java

optimize judge

---

client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java

Add error information to facilitate troubleshooting
XX
XXXX

Add error information to facilitate troubleshooting

---

client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingService.java
client/src/main/java/com/alibaba/nacos/client/naming/remote/NamingClientProxy.java
client/src/main/java/com/alibaba/nacos/client/naming/remote/NamingClientProxyDelegate.java
client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc/NamingGrpcClientProxy.java
client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc/redo/NamingGrpcRedoService.java
client/src/main/java/com/alibaba/nacos/client/naming/remote/http/NamingHttpClientProxy.java
client/src/test/java/com/alibaba/nacos/client/naming/remote/AbstractNamingClientProxyTest.java

[ISSUE#7550] Add judgement for is subscribe services.

---

client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java

The configuration cannot be updated in the case of single core
XX
XXXX

The configuration cannot be updated in the case of single core

---

core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcRequestAcceptor.java

add missing keyword to method.

#7577 fix missing return keyword of request body validated 

---

naming/src/main/java/com/alibaba/nacos/naming/controllers/InstanceControllerV2.java

[ISSUE#7208] add InstanceControllerV2

---

api/src/main/java/com/alibaba/nacos/api/naming/remote/request/NotifySubscriberRequest.java
client/src/test/java/com/alibaba/nacos/client/naming/remote/gprc/NamingPushRequestHandlerTest.java
naming/src/main/java/com/alibaba/nacos/naming/push/v2/executor/PushExecutorRpcImpl.java

optimize NotifySubscriberRequest

---

console/src/main/java/com/alibaba/nacos/console/security/nacos/roles/NacosRoleServiceImpl.java
console/src/main/java/com/alibaba/nacos/console/security/nacos/users/NacosUserDetailsServiceImpl.java

[ISSUE #7481] add user and role info to memory after db queried.

---

client/src/main/java/com/alibaba/nacos/client/config/AesCrypto.java

Summer2021 issue#5695 fix javadoc

---

client/src/test/java/com/alibaba/nacos/client/config/filter/impl/ConfigCryptoFilterTest.java
client/src/test/java/com/alibaba/nacos/client/config/filter/impl/ConfigFilterChainTest.java
client/src/test/java/com/alibaba/nacos/client/naming/remote/gprc/NamingGrpcClientProxyTest.java

Summer2021 issue#5695 fix unit test

---

client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java

remove some unused method
modify the use of slf4j
remove some unused method
modify the use of slf4j
* [*] Write a pull request description that is detailed enough to understand what the …

[ISSUE #6627]Optimize remove unused methods and  improve code quality

---

README.md

- Fix #7408 
- Add 'How can I contribute' section in 'Contributing'.
No need.

[ISSUE #7408] Add contribution description in README

---

naming/src/main/java/com/alibaba/nacos/naming/core/Instances.java
naming/src/main/java/com/alibaba/nacos/naming/core/ServiceManager.java

[1.x] change Instances list type to CopyOnWriteArrayList

---

common/src/test/java/com/alibaba/nacos/common/http/param/QueryTest.java
common/src/test/java/com/alibaba/nacos/common/utils/CollectionUtilsTest.java

#7295 
Update test behavior to use safer data structures which the orders of elements are preserved and deterministic. 
In test `testToQueryUrl`, use `LinkedHashMap` to replace `HashMap` for query parameters type. 
```sh
mvn edu.illinois:nondex-maven-plugin:1.1.2:nondex -pl common -Dtest=QueryTest#testToQueryUrl
#or
mvn test -pl common -Dtest=QueryTest#testToQueryUrl
```

Use LinkedHashMap to preserve string order

---

core/src/test/java/com/alibaba/nacos/core/storage/FileKvStorageTest.java

[ISSUE #7607] Clean test's files after run the FileKvStorageTest

---

console/src/main/java/com/alibaba/nacos/console/config/TomcatWebServerAccessLogCustomizer.java

[1.x] set max days of Tomcat access log

---

config/src/main/java/com/alibaba/nacos/config/server/service/AggrWhitelist.java

[ISSUE #7627] Remove unnecessary Service annotation

---

config/src/test/java/com/alibaba/nacos/config/server/service/AggrWhitelistTest.java

[ISSUE #7623] Optimize the AggrWhitelistTest

---

.gitignore

[ISSUE #7600] ignore log files at gitignore

---

console/src/main/java/com/alibaba/nacos/console/security/nacos/users/NacosUserDetailsServiceImpl.java

[1.x] initialize userMap at post construction

---

address/src/main/java/com/alibaba/nacos/address/component/AddressServerManager.java
address/src/test/java/com/alibaba/nacos/address/component/AddressServerManagerTests.java

Remove meaningless judgment conditions.
See `AddressServerControllerTests.java`.

[ISSUE #7591]Remove meaningless judgment conditions. 

---

naming/src/main/java/com/alibaba/nacos/naming/remote/rpc/handler/ServiceListRequestHandler.java

[ISSUE #7502] ServiceListRequestHandler return the count of serviceNames is error.

---

pom.xml

update log4j and protobuf-java version
XX
XXXX

update log4j and protobuf-java version

---

common/src/main/java/com/alibaba/nacos/common/cache/decorators/AutoExpireCache.java

Fix for bug #7387

---

config/src/main/java/com/alibaba/nacos/config/server/service/dump/DumpService.java
config/src/main/java/com/alibaba/nacos/config/server/service/repository/PersistService.java
config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePaginationHelperImpl.java
config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java

[ISSUE#7519] Optimize configuration history deletion logic

---

pom.xml

Change version to 2.0.4

---

config/src/main/java/com/alibaba/nacos/config/server/service/ConfigCacheService.java

修复集群模式使用内置数据库配置中心配置文件丢失
XX
改为：判断本地数据库和内存缓存中的数据一致，且判断磁盘中是否有对应文件成立才不写磁盘，否则还是继续写磁盘。

[ISSUE #7593]修复集群模式使用内置数据库配置中心配置文件丢失

---

config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigController.java

The request parameter srcuser does not work
XX
XXXX

The request parameter srcuser does not work

---

config/src/main/java/com/alibaba/nacos/config/server/service/ConfigCacheService.java

Strengthening the code

---

config/src/main/java/com/alibaba/nacos/config/server/controller/ListenerController.java
config/src/main/java/com/alibaba/nacos/config/server/service/ConfigSubService.java

- Remove unnecessary annotation `Autowired`
- Replace with <>
- Remove unnecessary judgment statement
- Remove unnecessary init statement
- Remove unnecessary exception declaration statement
XXXXX
XX
XXXX

Optimize some code

---

naming/src/main/java/com/alibaba/nacos/naming/utils/InstanceUtil.java

InstanceUtil 提高分支判断可读性

---

config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigController.java

删除ConfigController类冗余代码
无影响
无影响

删除ConfigController类冗余代码

---

auth/src/main/java/com/alibaba/nacos/auth/AbstractProtocolAuthService.java
auth/src/main/java/com/alibaba/nacos/auth/ProtocolAuthService.java
auth/src/main/java/com/alibaba/nacos/auth/context/GrpcIdentityContextBuilder.java
auth/src/main/java/com/alibaba/nacos/auth/context/HttpIdentityContextBuilder.java
auth/src/test/java/com/alibaba/nacos/auth/GrpcProtocolAuthServiceTest.java
auth/src/test/java/com/alibaba/nacos/auth/HttpProtocolAuthServiceTest.java
auth/src/test/java/com/alibaba/nacos/auth/context/GrpcIdentityContextBuilderTest.java
auth/src/test/java/com/alibaba/nacos/auth/context/HtppIdentityContextBuilderTest.java
auth/src/test/java/com/alibaba/nacos/auth/mock/MockAuthPluginService.java
core/src/main/java/com/alibaba/nacos/core/auth/AuthFilter.java
core/src/main/java/com/alibaba/nacos/core/auth/RemoteRequestAuthFilter.java
plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/NacosAuthPluginService.java
plugin/auth/src/main/java/com/alibaba/nacos/plugin/auth/constant/Constants.java
plugin/auth/src/main/java/com/alibaba/nacos/plugin/auth/spi/server/AuthPluginService.java

For #5696. 
- validateIdentity add Resource input for extension.
- IdentityContext parse remoteIp.

[ISSUE#5696] IdentityContext build from resource and remote ip.

---

auth/src/main/java/com/alibaba/nacos/auth/AbstractProtocolAuthService.java
auth/src/main/java/com/alibaba/nacos/auth/ProtocolAuthService.java
auth/src/test/java/com/alibaba/nacos/auth/GrpcProtocolAuthServiceTest.java
auth/src/test/java/com/alibaba/nacos/auth/HttpProtocolAuthServiceTest.java
auth/src/test/java/com/alibaba/nacos/auth/mock/MockAuthPluginService.java
core/src/main/java/com/alibaba/nacos/core/auth/AuthFilter.java
core/src/main/java/com/alibaba/nacos/core/auth/RemoteRequestAuthFilter.java
plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/NacosAuthPluginService.java
plugin/auth/src/main/java/com/alibaba/nacos/plugin/auth/spi/server/AuthPluginService.java

For #5696. 
Auth plugin add enableAuth method to switch auth more precisely.

[ISSUE#5696]Auth plugin add enableAuth method to switch auth more precisely.

---

client/src/main/java/com/alibaba/nacos/client/naming/remote/http/NamingHttpClientProxy.java

for #7738
服务端优先使用enabled来接受参数，同时兼容了enable来接受参数
客户端代码应该使用enabled来进行传参
XX
XXXX

[ISSUE#7738]Client code should use enabled to pass parameters

---

consistency/pom.xml

#7758 
update module `nacos-consistency` protobuf-maven-plugin version to `0.6.1`
* [-] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [-] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [-] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.

ISSUE #7758

---

common/src/main/java/com/alibaba/nacos/common/http/AbstractHttpClientFactory.java
common/src/main/java/com/alibaba/nacos/common/http/client/request/DefaultAsyncHttpClientRequest.java

log what causes I/O reactor status to STOPPED
see #7698

[develop] log what causes I/O reactor status to STOPPED

---

core/src/main/java/com/alibaba/nacos/core/cluster/ServerMemberManager.java

[ISSUE #7621] Add hasChange judgement in ServerMemberManager to avoid useless nacos-cluster log output

---

consistency/src/main/java/com/alibaba/nacos/consistency/ProtoMessageUtil.java
consistency/src/test/java/com/alibaba/nacos/consistency/ProtoMessageUtilTest.java

Fixes #7757.
Fix jraft read request deserialize to write request problem.

[ISSUE#7757] Fix jraft read request deserialize to write request problem.

---

config/src/main/java/com/alibaba/nacos/config/server/service/ConfigCacheService.java

[ISSUE #7593] judge whether file exists in disk in method dumpBeta and dumpTag

---

config/src/main/java/com/alibaba/nacos/config/server/service/ConfigCacheService.java

[ISSUE #7593] judge whether file exists in disk

---

config/src/test/java/com/alibaba/nacos/config/server/remote/ConfigPublishGroupKeyParserTest.java

[ISSUE #5092]add ConfigPublishGroupKeyParserTest

---

config/src/main/java/com/alibaba/nacos/config/server/service/capacity/CapacityService.java
config/src/main/java/com/alibaba/nacos/config/server/service/capacity/GroupCapacityPersistService.java
config/src/test/java/com/alibaba/nacos/config/server/service/capacity/GroupCapacityPersistServiceTest.java

[ISSUE #5092] add unit test for GroupCapacityPersistService

---

pom.xml

change plugin version base on nacos develop branch and sofa suggestion.
1. remove httpclient and httpcore version from pom.xml to avoid IOReactor shutdown when client abort exception occurred ( incompatible issue).
2. fixes log4j2 security issue.
3. update jraft version.

[1.x] Patch v1.x pom.xml

---

config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java

解决历史版本查询bug，当存在除了public的其他命名空间时，查询接口会报错
Solve the historical version query bug, when there are other namespaces except public, the query interface will report an error
XX
XXXX

fix his_config query

---

config/src/test/java/com/alibaba/nacos/config/server/service/datasource/DynamicDataSourceTest.java

[ISSUE #5092] add unit test for DynamicDataSourceTest

---

config/src/main/java/com/alibaba/nacos/config/server/service/capacity/TenantCapacityPersistService.java
config/src/test/java/com/alibaba/nacos/config/server/service/capacity/TenantCapacityPersistServiceTest.java

[ISSUE #5092] add unit test for TenantCapacityPersistService

---

config/src/main/java/com/alibaba/nacos/config/server/controller/HistoryController.java

apply PR #6173 to add permission check for config history query.

[1.x] Patch v1.x history controller

---

common/src/main/java/com/alibaba/nacos/common/utils/StringUtils.java
common/src/test/java/com/alibaba/nacos/common/utils/StringUtilsTest.java

apply PR #6213 to fix NPE of StringUtils.join method and modify StringUtilsTest.java to be compliant with jdk 1.6

[1.x] Patch v1.x string utils

---

core/src/main/java/com/alibaba/nacos/core/distributed/id/SnowFlowerIdGenerator.java

apply PR #6407 to check debug enabled status before logging.

[1.x] Patch v1.x snow flower id generator

---

config/src/main/java/com/alibaba/nacos/config/server/utils/YamlParserUtil.java

apply PR #6423 from develop to fix yaml parse concurrent problem.

[1.x] Patch v1.x yaml parser util

---

config/src/main/java/com/alibaba/nacos/config/server/utils/RequestUtil.java
console/src/main/java/com/alibaba/nacos/console/security/nacos/NacosAuthManager.java

apply PR #7252 from develop to get user key attribute from session.

[1.x] Patch v1.x RequestUtil.java and NacosAuthManager.java

---

common/src/main/java/com/alibaba/nacos/common/executor/ThreadPoolManager.java

apply PR #7341 from develop branch to address concurrent issue.

[1.x] Patch v1.x thread pool manager

---

core/src/main/java/com/alibaba/nacos/core/storage/StorageFactory.java

删除StorageFactory无效的分支判断
XX
无影响

删除StorageFactory类冗余代码

---

api/src/main/java/com/alibaba/nacos/api/remote/PayloadRegistry.java

Modifier.isAbstract(),当传入参数是“接口“类型的时候，返回依然为true，所以是Modifier.isInterface无效的逻辑判断，只需要根据Modifier.isAbstract()判断即可。
XX
无影响

删除PayloadRegistry register方法中无效的逻辑判断

---

config/src/test/java/com/alibaba/nacos/config/server/remote/ConfigQueryGroupKeyParserTest.java

[ISSUE#5092]add ConfigQueryGroupKeyParserTest

---

config/src/test/java/com/alibaba/nacos/config/server/remote/ConfigRemoveRequestHandlerTest.java

[ISSUE#5092]add ConfigRemoveRequestHandlerTest

---

config/src/test/java/com/alibaba/nacos/config/server/remote/ConfigQueryGroupParserTest.java

[ISSUE#5092]ConfigQueryGroupParserTest

---

naming/src/test/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/v2/DistroClientComponentRegistryTest.java

[ISSUE##5143]add DistroClientComponentRegistryTest

---

config/src/test/java/com/alibaba/nacos/config/server/remote/InternalConfigChangeNotifierTest.java

[ISSUE#5092]add InternalConfigChangeNotifierTest

---

config/src/test/java/com/alibaba/nacos/config/server/remote/ConfigChangeListenContextTest.java

[ISSUE#5092]add ConfigChangeListenContextTest

---

config/src/test/java/com/alibaba/nacos/config/server/service/datasource/LocalDataSourceServiceImplTest.java

[ISSUE #5092] add test for LocalDataSourceServiceImpl

---

config/src/test/java/com/alibaba/nacos/config/server/service/datasource/ExternalDataSourceServiceImplTest.java

[ISSUE #5092] add unit test for ExternalDataSourceServiceImpl

---

config/src/test/java/com/alibaba/nacos/config/server/remote/ConfigChangeBatchListenRequestHandlerTest.java

[ISSUE#5092]Config change batch listen request handler test

---

common/src/main/java/com/alibaba/nacos/common/utils/InternetAddressUtil.java

optimization append

---

auth/src/main/java/com/alibaba/nacos/auth/AbstractProtocolAuthService.java
auth/src/main/java/com/alibaba/nacos/auth/GrpcProtocolAuthService.java
auth/src/main/java/com/alibaba/nacos/auth/HttpProtocolAuthService.java
auth/src/main/java/com/alibaba/nacos/auth/annotation/Secured.java
auth/src/main/java/com/alibaba/nacos/auth/parser/AbstractResourceParser.java
auth/src/main/java/com/alibaba/nacos/auth/parser/DefaultResourceParser.java
auth/src/main/java/com/alibaba/nacos/auth/parser/ResourceParser.java
auth/src/test/java/com/alibaba/nacos/auth/parser/grpc/ConfigGrpcResourceParserTest.java
auth/src/test/java/com/alibaba/nacos/auth/parser/grpc/NamingGrpcResourceParserTest.java
auth/src/test/java/com/alibaba/nacos/auth/parser/http/ConfigHttpResourceParserTest.java
auth/src/test/java/com/alibaba/nacos/auth/parser/http/NamingHttpResourceParserTest.java
plugin/auth/src/main/java/com/alibaba/nacos/plugin/auth/constant/Constants.java

For #5696.
Add tags in Secured and inject tags into resource properties.

[ISSUE#5696] Secured annotation add tags field.

---

api/src/test/java/com/alibaba/nacos/api/remote/PayloadRegistryTest.java
config/src/test/java/com/alibaba/nacos/config/server/remote/ConfigPublishGroupKeyParserTest.java

Payload registry test

---

core/src/main/java/com/alibaba/nacos/core/cluster/AbstractMemberLookup.java
core/src/main/java/com/alibaba/nacos/core/cluster/lookup/AddressServerMemberLookup.java
core/src/main/java/com/alibaba/nacos/core/cluster/lookup/FileConfigMemberLookup.java
core/src/main/java/com/alibaba/nacos/core/cluster/lookup/StandaloneMemberLookup.java

Use template patten to refactor AbstractMemberLookup#destroy method
- add doDestroy method
- refactor destroy method for other subclass of AbstractMemberLookup
Close #7879 
XXXXX
XX
XXXX

[ISSUES#7879] Refactor destroy method of `AbstractMemberLookup`

---

common/src/main/java/com/alibaba/nacos/common/utils/IPUtil.java
common/src/test/java/com/alibaba/nacos/common/utils/IPUtilTest.java

Re-support to configure `localhost` and service-name for serverAddr.
Fix #7836

[issue #7836]Not check serverAddr.

---

core/src/main/java/com/alibaba/nacos/core/controller/ServerLoaderController.java

- some type arguments are replaced with <>
- field injection is replaced with constructor injection
- set hash map default initialCapacity
- sdkConCount string variable change to constants
Close #7902
XXXXX
XX
XXXX

[ISSUE#7902] Optimize some codes for ServerLoaderController

---

client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java

[#7904] Bad smell code in ClientWorker.java

---

naming/src/test/java/com/alibaba/nacos/naming/utils/InstanceUtilTest.java
naming/src/test/java/com/alibaba/nacos/naming/utils/ServiceUtilTest.java

add junit test for InstanceUtilTest and ServiceUtilTest
XX
XXXX

add junit for InstanceUtilTest and ServiceUtilTest

---

common/src/main/java/com/alibaba/nacos/common/http/AbstractApacheHttpClientFactory.java
common/src/main/java/com/alibaba/nacos/common/http/AbstractHttpClientFactory.java
common/src/main/java/com/alibaba/nacos/common/http/HttpClientConfig.java
common/src/main/java/com/alibaba/nacos/common/http/client/request/DefaultAsyncHttpClientRequest.java
common/src/main/java/com/alibaba/nacos/common/http/client/request/DefaultHttpClientRequest.java
naming/src/main/java/com/alibaba/nacos/naming/misc/HttpClient.java

[develop] set default connection lease request timeout and merge default config

---

consistency/src/main/java/com/alibaba/nacos/consistency/ProtoMessageUtil.java
consistency/src/test/java/com/alibaba/nacos/consistency/ProtoMessageUtilTest.java
core/src/main/java/com/alibaba/nacos/core/distributed/raft/JRaftServer.java

[1.x] add request type field at the head of task data, exchange parse order between Log and GetRequest 

---

api/src/main/java/com/alibaba/nacos/api/config/ability/ClientConfigAbility.java
api/src/main/java/com/alibaba/nacos/api/naming/ability/ClientNamingAbility.java
api/src/main/java/com/alibaba/nacos/api/remote/ability/ClientRemoteAbility.java

使用JDK序列化时，成员变量的实体类未实现Serializable接口导致序列化异常
none

fix client field not serializable exception

---

console/src/main/java/com/alibaba/nacos/console/config/ConsoleConfig.java
console/src/main/java/com/alibaba/nacos/console/filter/XssFilter.java
console/src/test/java/com/alibaba/nacos/console/filter/XssFilterTest.java

- Set response header 'Content-Security-Policy'
Close #7359 
xxx
XX
XXXX

[ISSUE #7359] Add xss filter

---

config/src/main/java/com/alibaba/nacos/config/server/service/ConfigSubService.java

fix ConfigSubService memberManager null.
API affected：http://localhost:8848/nacos/v1/cs/configs/listener?dataId=xx
OS: MacOS
XX
XXXX

fix ConfigSubService memberManager null

---

config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigServletInner.java
config/src/main/java/com/alibaba/nacos/config/server/model/Page.java
config/src/main/java/com/alibaba/nacos/config/server/service/repository/RowMapperManager.java
config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedStoragePersistServiceImpl.java
config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java

[ISSUE #5695] Obtain configuration interface compatibility decryption

---

auth/src/main/java/com/alibaba/nacos/auth/parser/grpc/AbstractGrpcResourceParser.java
auth/src/main/java/com/alibaba/nacos/auth/parser/grpc/ConfigGrpcResourceParser.java
auth/src/main/java/com/alibaba/nacos/auth/parser/grpc/NamingGrpcResourceParser.java
auth/src/test/java/com/alibaba/nacos/auth/parser/grpc/NamingGrpcResourceParserTest.java
plugin/auth/src/main/java/com/alibaba/nacos/plugin/auth/constant/Constants.java

For #5696.
Add requestClass to resource properties for grpc resource parser. 
Plugin may use the information to do some special logic. 
XXXX

[ISSUE#5696] Add requestClass to resource properties for grpc resource parser.

---

config/src/main/java/com/alibaba/nacos/config/server/controller/HistoryController.java
console-ui/src/pages/ConfigurationManagement/ConfigDetail/ConfigDetail.js

FIX: Missing parameters 'dataId' and 'group'.
XX
XXXX

[ISSUE #7941] FIX: Missing parameters 'dataId' and 'group'.

---

common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClientFactory.java
common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClient.java
common/src/main/java/com/alibaba/nacos/common/utils/PropertyUtils.java
common/src/main/java/com/alibaba/nacos/common/utils/ThreadUtils.java
core/src/main/java/com/alibaba/nacos/core/cluster/remote/ClusterRpcClientProxy.java

Support cluster grpc client to set pool size

---

core/src/main/java/com/alibaba/nacos/core/distributed/raft/NacosStateMachine.java

Follower state machine ignore read operation.

---

address/src/main/java/com/alibaba/nacos/address/controller/AddressServerClusterController.java

optimization method definition
XX
XXXX

[ISSUE #7980]optimization method definition

---

client/src/main/java/com/alibaba/nacos/client/auth/impl/process/HttpLoginProcessor.java
client/src/main/java/com/alibaba/nacos/client/config/impl/ServerListManager.java
client/src/main/java/com/alibaba/nacos/client/constant/Constants.java
client/src/main/java/com/alibaba/nacos/client/naming/core/ServerListManager.java
client/src/main/java/com/alibaba/nacos/client/naming/remote/http/NamingHttpClientManager.java
client/src/main/java/com/alibaba/nacos/client/naming/remote/http/NamingHttpClientProxy.java
client/src/main/java/com/alibaba/nacos/client/naming/utils/UtilAndComs.java
client/src/test/java/com/alibaba/nacos/client/naming/remote/http/NamingHttpClientManagerTest.java
common/src/main/java/com/alibaba/nacos/common/constant/RequestUrlConstants.java
common/src/main/java/com/alibaba/nacos/common/http/HttpUtils.java
config/src/main/java/com/alibaba/nacos/config/server/service/ConfigSubService.java
core/src/main/java/com/alibaba/nacos/core/cluster/lookup/AddressServerMemberLookup.java
core/src/test/java/com/alibaba/nacos/core/cluster/lookup/AddressServerMemberLookupTest.java
naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/raft/RaftCore.java
naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/raft/RaftProxy.java
naming/src/main/java/com/alibaba/nacos/naming/healthcheck/ClientBeatCheckTask.java
naming/src/main/java/com/alibaba/nacos/naming/healthcheck/HttpHealthCheckProcessor.java
naming/src/main/java/com/alibaba/nacos/naming/healthcheck/v2/processor/HttpHealthCheckProcessor.java
naming/src/main/java/com/alibaba/nacos/naming/misc/NamingProxy.java
naming/src/main/java/com/alibaba/nacos/naming/misc/ServerStatusSynchronizer.java
naming/src/main/java/com/alibaba/nacos/naming/misc/ServiceStatusSynchronizer.java
naming/src/main/java/com/alibaba/nacos/naming/push/NamingSubscriberServiceAggregationImpl.java
naming/src/main/java/com/alibaba/nacos/naming/web/DistroFilter.java

There are too many magic numbers like "http / /" in the source code, which are extracted as constants for easy management and maintenance
XX
XXXX

Optimize HTTP constants

---

plugin/encryption/src/main/java/com/alibaba/nacos/plugin/encryption/handler/EncryptionHandler.java
plugin/encryption/src/main/java/com/alibaba/nacos/plugin/encryption/spi/EncryptionPluginService.java
plugin/encryption/src/test/java/com/alibaba/nacos/plugin/encryption/EncryptionPluginManagerTest.java
plugin/encryption/src/test/java/com/alibaba/nacos/plugin/encryption/handler/EncryptionHandlerTest.java

SPI adds secret key encryption and decryption support
XX
XXXX

SPI adds secret key encryption and decryption support

---

api/src/main/java/com/alibaba/nacos/api/grpc/auto/BiRequestStreamGrpc.java

remove unused import

---

api/src/test/java/com/alibaba/nacos/api/naming/utils/NamingUtilsTest.java

[ISSUE #8004]update unit test to fix expected value and actual value is inverse

---

naming/src/main/java/com/alibaba/nacos/naming/consistency/ConsistencyService.java
naming/src/main/java/com/alibaba/nacos/naming/core/Cluster.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/NamingMetadataManager.java

- fix the method  comment spelling error
- fix the method comment grammar

fix comment grammar

---

config/src/main/java/com/alibaba/nacos/config/server/utils/ParamUtils.java
naming/src/main/java/com/alibaba/nacos/naming/controllers/InstanceController.java

- remove unused variety to increase the performance
- define constant replace copying four times
XX
XXXX

remove unused variety and define constant

---

config/src/main/java/com/alibaba/nacos/config/server/filter/CurcuitFilter.java
core/src/main/java/com/alibaba/nacos/core/auth/AuthFilter.java
naming/src/main/java/com/alibaba/nacos/naming/web/DistroFilter.java

[ISSUE #7966] modify returned msg in Auth/Distro/Curcuit-Filter when internal server error

---

consistency/src/test/java/com/alibaba/nacos/consistency/ProtocolMetaDataTest.java
core/src/test/java/com/alibaba/nacos/core/cluster/MemberUtilTest.java
core/src/test/java/com/alibaba/nacos/core/distributed/distro/task/load/DistroLoadDataTaskTest.java
core/src/test/resources/application.properties

There are some unit test problems in branch v1.x-develop. I found that those problems are fixed in the 2.x branch and migrated the exact changes to 1.x branch.
nacos-client: 
update compile version from 6 to 8
https://github.com/alibaba/nacos/pull/4276/files
nacos-common: 
replaces Java 8 date type to fix JSON encoding problem
https://github.com/alibaba/nacos/pull/6101/files
nacos-core: 
remove setUp codes that blocks test in MemberUtilTest.java
https://github.com/alibaba/nacos/pull/6092/files
add application.properties to make test pass
fix setUp codes that blocks test in DistroLoadDataTaskTest
https://github.com/alibaba/nacos/pull/6102/files
XXXX
Follow this checklist to help us incorporate your contribution quickly …

Migrate 2.x changes to 1.x to fix unit test problems.

---

naming/src/test/java/com/alibaba/nacos/naming/controllers/InstanceControllerTest.java

[ISSUE#8009] Fix NPE of unit test.

---

core/src/main/java/com/alibaba/nacos/core/utils/TimerContext.java

Improve the code readability of TimerContext replace if with switch case
XX
XXXX

Improve the code readability of TimerContext replace if with switch case

---

api/src/main/java/com/alibaba/nacos/api/config/ability/ServerConfigAbility.java
api/src/main/java/com/alibaba/nacos/api/config/remote/request/ClientConfigMetricRequest.java
api/src/main/java/com/alibaba/nacos/api/remote/ability/ServerRemoteAbility.java
common/src/main/java/com/alibaba/nacos/common/notify/Event.java
naming/src/main/java/com/alibaba/nacos/naming/pojo/ClusterInfo.java
naming/src/main/java/com/alibaba/nacos/naming/pojo/IpAddressInfo.java
naming/src/main/java/com/alibaba/nacos/naming/pojo/ServiceDetailInfo.java
naming/src/main/java/com/alibaba/nacos/naming/pojo/Subscribers.java

Add serialVersionUID for serializable interface
XX
XXXX

[#8035] Add serialVersionUID for serializable interface

---

config/src/main/java/com/alibaba/nacos/config/server/manager/TaskManager.java

delete redundant toString() method
No effect
XXXX

delete redundant toString() method

---

pom.xml

upgrade to 2.1.0-BETA.

---

config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigServletInner.java

fix newline

---

client/src/test/java/com/alibaba/nacos/client/utils/TemplateUtilsTest.java

Replace redundant code with lambda expression
No effect
XXXX

Replace redundant code with lambda expression

---

naming/src/test/java/com/alibaba/nacos/naming/BaseTest.java
naming/src/test/java/com/alibaba/nacos/naming/controllers/InstanceControllerV2Test.java

add junit test from InstanceControllerV2Test
XX
XXXX

add junit test from InstanceControllerV2Test

---

plugin/encryption/src/main/java/com/alibaba/nacos/plugin/encryption/handler/EncryptionHandler.java

Secret key encryption error

---

core/src/main/java/com/alibaba/nacos/core/config/AbstractDynamicConfig.java
core/src/main/java/com/alibaba/nacos/core/distributed/distro/DistroConfig.java
core/src/test/java/com/alibaba/nacos/core/distributed/distro/DistroConfigTest.java
naming/src/main/java/com/alibaba/nacos/naming/misc/ClientConfig.java
naming/src/main/java/com/alibaba/nacos/naming/push/v2/PushConfig.java
naming/src/test/java/com/alibaba/nacos/naming/misc/ClientConfigTest.java
naming/src/test/java/com/alibaba/nacos/naming/push/v2/PushConfigTest.java

[ISSUE #8050] Fix config that can't read environment args 

---

console/src/main/java/com/alibaba/nacos/console/controller/NamespaceController.java

remove unused parameters and redundant generics
XX
XXXX

clean NamespaceController code

---

console/src/main/resources/application.properties

Keep actuator default close.

---

common/src/main/java/com/alibaba/nacos/common/utils/JacksonUtils.java
common/src/test/java/com/alibaba/nacos/common/utils/JacksonUtilsTest.java

issue: https://github.com/alibaba/nacos/issues/8072
( 1.x PR: https://github.com/alibaba/nacos/pull/8075 )

[ISSUE #8072] Reduce memory cost in DistroProtocol initialization to avoid OutOfMemoryError (2.x)

---

console-ui/src/pages/ConfigurationManagement/ConfigurationManagement/ConfigurationManagement.js

[ISSUE #8087] Fix popup layer auto width

---

config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedStoragePersistServiceImpl.java
config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java

最新的开发版本，点击配置历史版本的时候，该接口报400，http://xxx:8848/nacos/v1/cs/history/configs?tenant=xxx&accessToken=xxxx&namespaceId=xxxx
XX
XXXX

bug fix config history data error

---

common/src/main/java/com/alibaba/nacos/common/utils/TypeUtils.java
common/src/test/java/com/alibaba/nacos/common/utils/JacksonUtilsTest.java
common/src/test/java/com/alibaba/nacos/common/utils/TypeUtilsTest.java

I find out PR #8075 makes checkstyle failed and create this PR to fix the error and also and migrate JacksonUtils unit test from `develop`(for v2.x) branch to `v1.x-develop`.
发现之前提的PR #8075 导致了checkstyle失败，所以创建了这个新的PR修复错误，并且顺便把2.x分支的JacksonUtils的单元测试迁移到了1.x分支。
Error detail:   https://github.com/alibaba/nacos/runs/5844257313
```
Error:  /home/runner/work/nacos/nacos/common/src/test/java/com/alibaba/nacos/common/utils/JacksonUtilsTest.java:13: First sentence of Javadoc is missing an ending period. [SummaryJavadoc]
Error:  /home/runner/work/nacos/nacos/common/src/test/java/com/alibaba/nacos/common/utils/JacksonUtilsTest.java:57:100: '{' is not followed by whitespace. [WhitespaceAround]
Error:  /home/runner/work/nacos/nacos/common/src/test/java/com/alibaba/nacos/common/utils/JacksonUtilsTest.j …
```

[ISSUE #8072] Fix checkstyle error

---

common/src/main/java/com/alibaba/nacos/common/codec/Base64.java
common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcUtils.java
common/src/main/java/com/alibaba/nacos/common/utils/ByteUtils.java
common/src/main/java/com/alibaba/nacos/common/utils/StringUtils.java
config/src/main/java/com/alibaba/nacos/config/server/aspect/CapacityManagementAspect.java

In terms of performance, this way of getting the code is much better than the previous way
XX
XXXX

[Optimize] Use StandardCharsets.UTF_8 replace Charset.forName("UTF-8")

---

config/src/main/java/com/alibaba/nacos/config/server/model/app/ApplicationInfo.java

[Optimize]Polish method comment

---

naming/src/main/java/com/alibaba/nacos/naming/healthcheck/v2/processor/HealthCheckProcessorV2Delegate.java
naming/src/main/java/com/alibaba/nacos/naming/healthcheck/v2/processor/NoneHealthCheckProcessor.java

[ISSUE #8108] Add NoneHealthCheckProcessorV2 class

---

core/src/main/java/com/alibaba/nacos/core/remote/control/TpsMonitorManager.java

[ISSUE #8092] Destroy the thread pool of TpsMonitorManager

---

auth/src/main/java/com/alibaba/nacos/auth/config/AuthConfigs.java
console/src/main/resources/application.properties
distribution/conf/application.properties
distribution/conf/application.properties.example
plugin-default-impl/pom.xml
plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/LdapAuthenticationProvider.java
plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/NacosAuthConfig.java
plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/configuration/ConditionOnLdapAuth.java

Fix issue #7924

---

naming/src/main/java/com/alibaba/nacos/naming/core/Service.java
naming/src/main/java/com/alibaba/nacos/naming/core/ServiceManager.java

do getServiceString() only once when debug;
XXXXX
XX
XXXX

do getServiceString() only once when debug

---

core/src/main/java/com/alibaba/nacos/core/controller/NacosClusterController.java

fix(#6273): server/leave, add end conditions for cluster notifications.

fix(#6273): server/leave, add end conditions for cluster notifications.

---

plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/NacosAuthConfig.java

[ISSUE #8136] Exclude LdapAutoConfiguration

---

naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/DistroConsistencyServiceImpl.java

[ISSUE #8012] Fix NPE in DistroConsistencyServiceImpl.Notifier

---

client/src/main/java/com/alibaba/nacos/client/naming/core/ServerListManager.java
naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/DistroConsistencyServiceImpl.java
naming/src/main/java/com/alibaba/nacos/naming/core/DistroMapper.java
sys/src/main/java/com/alibaba/nacos/sys/env/EnvUtil.java

[ISSUE #8144] add volatile modifier to ServerListManager.serversFromEndpoint(2.x)

---

client/src/main/java/com/alibaba/nacos/client/naming/net/NamingProxy.java
naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/DistroConsistencyServiceImpl.java
naming/src/main/java/com/alibaba/nacos/naming/core/DistroMapper.java
sys/src/main/java/com/alibaba/nacos/sys/env/EnvUtil.java

[ISSUE #8144] add volatile modifier to `NamingProxy.serversFromEndpoint`

---

client/src/main/resources/nacos-log4j2.xml

fix #4639 
nacos  client  with log4j2 can keep some nacos log in some days with property `JM.LOG.RETAIN.DURATION.OFF` and `JM.LOG.RETAIN.DURATION`
For example,
if we want to keep only recent 30 days 's log files,  we could set `JM.LOG.RETAIN.DURATION.OFF=false`  and `JM.LOG.RETAIN.DURATION=P30D`
default the feature is disabled. default value is as follow
```
JM.LOG.RETAIN.DURATION.OFF=true 
JM.LOG.RETAIN.DURATION=P180D (half year which satisfy  some safety law)
```
[ref doc](https://logging.apache.org/log4j/log4j-2.7/manual/appenders.html#CustomDeleteOnRollover)
XX
XXXX

[ISSUE 4639] add rollover with date for log4j2

---

consistency/src/test/java/com/alibaba/nacos/consistency/SerializeFactoryTest.java

[Optimize] Delete redundant code

---

common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClient.java

Keep RpcClient constructor simple
XX
XXXX

[Optimize] RpcClient constructor

---

client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc/redo/data/RedoData.java

[ISSUE #8206]Override hashCode and equals to avoid repeated item

---

client/src/main/java/com/alibaba/nacos/client/config/utils/ConcurrentDiskUtil.java
client/src/main/java/com/alibaba/nacos/client/naming/cache/ConcurrentDiskUtil.java
common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClient.java
config/src/main/java/com/alibaba/nacos/config/server/service/capacity/CapacityService.java
istio/src/main/java/com/alibaba/nacos/istio/common/EventProcessor.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/event/publisher/NamingEventPublisher.java

Set interrupted flag to caller
XX
XXXX

[Optimize] Set interrupted flag to caller

---

naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/ClientOperationService.java

ClientOperationService result.getExtendDatum multiple calls
XX
XXXX

ClientOperationService result.getExtendDatum multiple calls

---

naming/src/main/java/com/alibaba/nacos/naming/core/Service.java

add service null check

---

naming/src/main/java/com/alibaba/nacos/naming/core/Instance.java
naming/src/test/java/com/alibaba/nacos/naming/core/InstanceTest.java

[ISSUE #8208] fix ip validate

---

client/src/main/java/com/alibaba/nacos/client/config/http/ServerHttpAgent.java
client/src/main/java/com/alibaba/nacos/client/config/impl/ServerListManager.java
client/src/test/java/com/alibaba/nacos/client/config/impl/ServerListMangerTest.java

Fix https://github.com/alibaba/nacos/issues/8203
Fix the concurrency problem about the iterator of ServerListManager.
XXXX

[ISSUE #8203] Fix the concurrency problem about the iterator of ServerListManager.

---

config/src/main/java/com/alibaba/nacos/config/server/remote/RpcConfigChangeNotifier.java

add log Loggers.REMOTE_PUSH.warn format word and optimize method calls
XX
XXXX

 optimize method calls

---

naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/doublewrite/execute/DefaultInstanceUpgradeHelper.java

Fix https://github.com/alibaba/nacos/issues/8193
XX
XXXX

[ISSUE #8193] Remove redundant code

---

pom.xml

Upgrade to 2.1.0

---

common/src/main/java/com/alibaba/nacos/common/http/HttpUtils.java

Replace keySet() to entrySet()

[Optimization] Replace keySet() to entrySet()

---

naming/src/main/java/com/alibaba/nacos/naming/misc/NamingProxy.java

Optimized translateParameterMap() by replacing keySet() to entrySet()
Optimizing translateParameterMap method with entrySet() by reference to #8281.

[Optimize] Replace keySet() to entrySet()

---

config/src/main/java/com/alibaba/nacos/config/server/filter/CurcuitFilter.java

Deleting redundant toString() method by reference to #8049.
No effect

Deleting redundant toString() method

---

config/src/main/java/com/alibaba/nacos/config/server/service/ConfigCacheService.java
config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedStoragePersistServiceImpl.java
config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java

feat(#6506): Can change betaIps multiple times in beta(or gray).
1. And fix SQL `encrypted_data_key=?WHERE`.

V2.x feat(#6506): Can change betaIps multiple times in beta(or gray).

---

config/src/main/java/com/alibaba/nacos/config/server/service/ConfigCacheService.java
config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedStoragePersistServiceImpl.java
config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java

feat(#6506): Can change betaIps multiple times in beta(or gray).

V1.x feat(#6506): Can change betaIps multiple times in beta(or gray).

---

client/src/main/java/com/alibaba/nacos/client/config/NacosConfigService.java

refactor code, #8095
use getEncryptDataKeySnapshot instead of getEncryptDataKeyFailover
XXXX

[ISSUE #8095] use getEncryptDataKeySnapshot instead of getEncryptDataKeyFailover

---

config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedStoragePersistServiceImpl.java
config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java

[ISSUE #8038] Fix config_tags_relation Table can Repeat Insert bug
https://github.com/alibaba/nacos/issues/8038
Fix config_tags_relation Table can Repeat Insert bug

## @Desc:[ISSUE #8038] Fix config_tags_relation Table can Repeat Insert bug

---

config/src/main/java/com/alibaba/nacos/config/server/service/repository/RowMapperManager.java

[ISSUE #8295] fix can't login when use embedded storage in cluster model

---

naming/src/main/java/com/alibaba/nacos/naming/core/Cluster.java

[ISSUE#8283]fix issue8283

---

api/src/main/proto/nacos_grpc_service.proto

fix: update comment

---

.github/workflows/ci.yml
naming/src/main/java/com/alibaba/nacos/naming/remote/udp/UdpConnector.java
naming/src/test/java/com/alibaba/nacos/naming/controllers/OperatorControllerTest.java
naming/src/test/java/com/alibaba/nacos/naming/remote/udp/UdpConnectorTest.java

Enhance Unit test stability.

---

client/src/main/java/com/alibaba/nacos/client/config/NacosConfigService.java

Add comments about config client failover (#8327)

---

config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedStoragePersistServiceImpl.java
config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java

[ISSUE #8318] fix findAllConfigInfoForDumpAll sql args error

---

api/src/main/java/com/alibaba/nacos/api/remote/RpcScheduledExecutor.java

the purpose of the change：simplify some code

[ISSUE#8358] make this anonymous inner class a lambda（api module）

---

config/src/main/java/com/alibaba/nacos/config/server/service/datasource/ExternalDataSourceServiceImpl.java

[Minor] 显式类型可替换为 <>

---

common/src/main/java/com/alibaba/nacos/common/executor/ThreadPoolManager.java
common/src/main/java/com/alibaba/nacos/common/http/AbstractHttpClientFactory.java
common/src/main/java/com/alibaba/nacos/common/http/HttpClientBeanHolder.java

the purpose of the change：simplify some code

[ISSUE#8358] make this anonymous inner class a lambda (common module)

---

client/src/main/java/com/alibaba/nacos/client/naming/backups/FailoverReactor.java
client/src/main/java/com/alibaba/nacos/client/naming/beat/BeatReactor.java
client/src/main/java/com/alibaba/nacos/client/naming/core/PushReceiver.java

the purpose of the change：simplify some code

[ISSUE#8358] make this anonymous inner class a lambda (client module)

---

common/src/main/java/com/alibaba/nacos/common/executor/ThreadPoolManager.java

Optimization and tidy codes.
Unfiy get/put by computeIfAbsent.
Verifying this change
eclipse-pmd was used to verify the changes 
#7315

[ISSUE #7315] Unfiy Map's get and put methods by computeIfAbsent In ThreadPoolManager

---

core/src/main/java/com/alibaba/nacos/core/cluster/lookup/StandaloneMemberLookup.java

reduce magic value in `com.alibaba.nacos.core.cluster.lookup.StandaloneMemberLookup`.
reduce magic value as possible
none

reduce magic value

---

config/src/main/java/com/alibaba/nacos/config/server/service/LongPollingService.java
config/src/main/java/com/alibaba/nacos/config/server/service/notify/HttpClientManager.java
config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java

for [#8358](https://github.com/alibaba/nacos/issues/8358)
XX
XXXX

[ISSUE#8358] make this anonymous inner class a lambda (config module)

---

core/src/main/java/com/alibaba/nacos/core/remote/ConnectionManager.java
core/src/main/java/com/alibaba/nacos/core/remote/RpcAckCallbackSynchronizer.java

for [#8358](https://github.com/alibaba/nacos/issues/8358)
XX
XXXX

[ISSUE#8358] make this anonymous inner class a lambda (core module)

---

example/src/main/java/com/alibaba/nacos/example/NamingExample.java

for [#8358](https://github.com/alibaba/nacos/issues/8358)
XX
XXXX

[ISSUE#8358] make this anonymous inner class a lambda (example module)

---

sys/src/main/java/com/alibaba/nacos/sys/file/WatchFileCenter.java
sys/src/main/java/com/alibaba/nacos/sys/utils/InetUtils.java

for [#8358](https://github.com/alibaba/nacos/issues/8358)
XX
XXXX

[ISSUE#8358] make this anonymous inner class a lambda (sys module)

---

client/src/main/java/com/alibaba/nacos/client/config/impl/ServerListManager.java
client/src/test/java/com/alibaba/nacos/client/config/impl/ServerListManagerTest.java

[ISSUE #8372] Fix https connection

---

pom.xml

Upgrade jackson version to 2.12.6.1

---

api/src/main/java/com/alibaba/nacos/api/exception/runtime/NacosDeserializationException.java
api/src/main/java/com/alibaba/nacos/api/naming/pojo/Instance.java
api/src/test/java/com/alibaba/nacos/api/naming/pojo/InstanceTest.java

(https://github.com/alibaba/nacos/issues/8345)
添加clusterName校验，同时解决grpc吞异常问题。如果校验不通过，错误信息将返回到客户端，使用者可以看到错误原因

[ISSUE #8345] nacos2.0.4没有对clusterName进行校验，会出现实例成功注册，但实例列表查不出来的bug

---

client/src/main/java/com/alibaba/nacos/client/config/NacosConfigService.java

refactor code, fix #8093
change logging order by logging after invoking getSnapshot
XXXX

[ISSUE #8093] change logging order by logging after invoking getSnapshot

---

naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/UpgradeJudgement.java
naming/src/test/java/com/alibaba/nacos/naming/core/v2/upgrade/UpgradeJudgementTest.java
plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/JwtTokenManager.java
plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/NacosAuthConfig.java
plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/controller/UserController.java
plugin-default-impl/src/test/java/com/alibaba/nacos/plugin/auth/impl/JwtTokenManagerTest.java
plugin-default-impl/src/test/java/com/alibaba/nacos/plugin/auth/impl/controller/UserControllerTest.java

XXXXX
fix spring cycle dependence  JwtTokenManager
XXXX

fix spring cycle dependence  JwtTokenManager

---

pom.xml
test/pom.xml
test/src/test/java/com/alibaba/nacos/test/config/ConfigExportAndImportAPI_CITCase.java

[ISSUE #8421]remove `commonOkHttp` dependency(1.x)

---

istio/src/main/java/com/alibaba/nacos/istio/common/EventProcessor.java
naming/src/test/java/com/alibaba/nacos/naming/controllers/ClusterControllerTest.java
naming/src/test/java/com/alibaba/nacos/naming/core/v2/upgrade/UpgradeJudgementTest.java

[ISSUE#8405] Fix istio module cycle dependency problem.

---

naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/DistroConsistencyServiceImpl.java

[ISSUE #8434] enhance DistroConsistencyServiceImpl listen/unListen

---

pom.xml
test/config-test/src/test/java/com/alibaba/nacos/test/config/ConfigExportAndImportAPI_CITCase.java
test/pom.xml

[ISSUE #8421]remove `commonOkHttp` dependency(2.x)

---

plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/LdapAuthConfig.java

- Close #8407 
- Fix circular dependency
- Fix failed UT
XX
XXXX

[ISSUE #8407] Remove whitespace

---

auth/src/main/java/com/alibaba/nacos/auth/config/AuthConfigs.java

Unfiy Map's get and put methods by computeIfAbsent In AuthConfig

---

common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClient.java
common/src/test/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClientTest.java

https://github.com/alibaba/nacos/issues/8275
Get the created channel directly
no output error log

[ISSUE #8275] Fix ClassCastException: io.grpc.ClientInterceptors$InterceptorChannel cannot be cast to io.grpc.ManagedChannel

---

client/src/main/java/com/alibaba/nacos/client/logging/logback/LogbackNacosLogging.java

Solve the problem of adding logback listener repeatedly.

---

istio/src/main/java/com/alibaba/nacos/istio/common/EventProcessor.java

Fix #8405, Remove Autowired in EventProcessor.

---

config/src/main/java/com/alibaba/nacos/config/server/monitor/MetricsMonitor.java

optimizing metricsmonitor code structure
XX
XXXX

optimizing metricsmonitor code structure

---

core/src/main/java/com/alibaba/nacos/core/distributed/raft/JRaftServer.java

[clean code]: has no bolt, jraft-core exclude bolt and use rpc-grpc-impl. (#8471)
So remove bolt properties.

[ISSUE #8471] has no bolt, remove bolt properties

---

client/src/main/java/com/alibaba/nacos/client/config/http/MetricsHttpAgent.java
client/src/main/java/com/alibaba/nacos/client/monitor/MetricsMonitor.java

see #7693 
- change MetricsMonitor function.
- collect right request code when collect.
XX
XXXX

optimize. config request monitor collect right  request code.

---

api/pom.xml
istio/pom.xml
naming/pom.xml
naming/src/main/java/com/alibaba/nacos/naming/healthcheck/MysqlHealthCheckProcessor.java
naming/src/main/java/com/alibaba/nacos/naming/healthcheck/v2/processor/MysqlHealthCheckProcessor.java
pom.xml

issue #8472
Dependency Governance, Remove useless netty dependency.
`grpc-netty-shaded` already shaded netty for grpc.
io.netty.channel.ConnectTimeoutException extends java.net.ConnectException;  So replace it to be compatible.
```java
package io.netty.channel;
import java.net.ConnectException;
public class ConnectTimeoutException extends ConnectException {
private static final long serialVersionUID = 2317065249988317463L;
public ConnectTimeoutException(String msg) {
super(msg);
}
public ConnectTimeoutException() {
}
}
```
`mvn clean install -Dmaven.test.skip=true -P release-nacos`
Make sure there are no compile errors.
务必已保障没有编译错误。

[ISSUE #8472]: [Dependency Governance] Remove useless netty.

---

core/src/main/java/com/alibaba/nacos/core/code/SpringApplicationRunListener.java
naming/src/test/java/com/alibaba/nacos/naming/healthcheck/ClientBeatCheckTaskTest.java
pom.xml

Issue: #8169
参考 https://github.com/advisories/GHSA-36p3-wjmg-h94x ，升级到 Spring Boot 2.6.6 修复此问题

[ISSUE #8169] Upgrade spring-boot version to 2.6.6(1.x)

---

naming/src/main/java/com/alibaba/nacos/naming/core/ServiceManager.java

removing unnecessary 'toString()' call by reference to #7507
XX
XXXX

removing unnecessary 'toString()' call

---

pom.xml

[ISSUE #8539] fix prometheus api error

---

naming/src/main/java/com/alibaba/nacos/naming/core/v2/index/ServiceStorage.java

…fter the console operation goes offline
for #8516
https://www.yuque.com/docs/share/1b925bb8-b469-428c-869c-c81676412b7c?# 《持久化实例在控制台操作下线后变成临时实例》
XX
XXXX

[ISSUE#8516]Solve the bug: the persistent instance becomes a temporary instance

---

pom.xml

[ISSUE #8539] fix prometheus api error (1.x)

---

pom.xml

For #8540  fix spring security vulnerability（cve-2022-22978）issue#8540
XX
XXXX

fix Spring Security vulnerability（cve-2022-22978）issue#8540, upgeade springboot version to 2.6.8

---

common/src/main/java/com/alibaba/nacos/common/packagescan/resource/AbstractResource.java
common/src/main/java/com/alibaba/nacos/common/packagescan/resource/PathMatchingResourcePatternResolver.java

issue https://github.com/alibaba/nacos/issues/8472
replace `org.apache.commons.logging.Log` with `org.slf4j.Logger`
XX
XXXX

[ISSUE #8472]: Dependency Governance, replace `org.apache.commons.logging.Log` with `org.slf4j.Logger`. (#8472)

---

client/src/main/java/com/alibaba/nacos/client/monitor/MetricsMonitor.java

[ISSUE #8514] Fix typo

---

naming/src/test/java/com/alibaba/nacos/naming/healthcheck/v2/HealthCheckTaskV2Test.java
naming/src/test/java/com/alibaba/nacos/naming/healthcheck/v2/processor/HttpHealthCheckProcessorTest.java
plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/JwtTokenManager.java
plugin-default-impl/src/test/java/com/alibaba/nacos/plugin/auth/impl/JwtTokenManagerTest.java

Set jwts Objects generated by parserbuilder() are cached
detail in #8561
XX
XXXX

[ISSUE#8561]Authentication performance optimization

---

core/src/main/java/com/alibaba/nacos/core/code/SpringApplicationRunListener.java
core/src/main/resources/META-INF/services/com.alibaba.nacos.core.listener.NacosApplicationListener

Use SPI optimize StartingApplicationListener

---

config/src/main/java/com/alibaba/nacos/config/server/aspect/CapacityManagementAspect.java
config/src/main/java/com/alibaba/nacos/config/server/constant/Constants.java

Extract Constant  in LimitType
XX
XXXX

Extract Constant  in LimitType

---

core/src/main/java/com/alibaba/nacos/core/distributed/raft/NacosStateMachine.java
naming/src/main/java/com/alibaba/nacos/naming/core/ServiceManager.java
naming/src/main/java/com/alibaba/nacos/naming/healthcheck/ClientBeatCheckTask.java
naming/src/main/java/com/alibaba/nacos/naming/healthcheck/HealthCheckStatus.java
naming/src/main/java/com/alibaba/nacos/naming/push/PushService.java

fix(#7284): log print ex details.

---

common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcUtils.java

[ISSUE #8592] Optimize GrpcUtils to reduce memory and cpu cost

---

core/src/main/java/com/alibaba/nacos/core/distributed/distro/DistroConfig.java
core/src/main/java/com/alibaba/nacos/core/distributed/distro/DistroConstants.java
core/src/main/java/com/alibaba/nacos/core/distributed/distro/task/load/DistroLoadDataTask.java
naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/v2/DistroClientTransportAgent.java

[ISSUE #8594] makes distro data load timeout can be configured.

---

config/src/main/java/com/alibaba/nacos/config/server/service/datasource/DynamicDataSource.java

[ISSUE #8532]Remove component annotation

---

naming/src/main/java/com/alibaba/nacos/naming/remote/rpc/handler/SubscribeServiceRequestHandler.java

for #8632
服务端收到订阅返回的数据过滤下线实例
The server receives the data filtering offline instance returned from the subscription
XXXX

fix subscribe bug:select enable instance only.

---

config/src/main/java/com/alibaba/nacos/config/server/service/datasource/DynamicDataSource.java

remove @Component annotation and constructor privatization

---

config/src/test/java/com/alibaba/nacos/config/server/service/repository/embedded/StandaloneDatabaseOperateImplTest.java

fix unit test 
fix class StandaloneDatabaseOperateImpl unit test
XXXX

[Summer 2022] Nacos多数据源插件化建设 fix unit test 

---

naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/impl/BasePersistentServiceProcessor.java

[1.x] Patch v1.x base persistent service processor

---

api/src/main/java/com/alibaba/nacos/api/config/convert/NacosConfigConverter.java

Fix Word Spelling 'Naocs' in Comment
Fix Word Spelling 'Naocs' in Comment
XXXX

Fix Word Spelling 'Naocs' in Comment

---

api/src/main/java/com/alibaba/nacos/api/common/Constants.java
common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClusterClient.java
common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcSdkClient.java
core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcClusterServer.java
core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcSdkServer.java

SDK and cluster get the port offset from the same place
XX
XXXX

optimize: port offset constant

---

api/src/main/java/com/alibaba/nacos/api/common/Constants.java
api/src/main/java/com/alibaba/nacos/api/naming/pojo/Instance.java
api/src/main/java/com/alibaba/nacos/api/naming/utils/NamingUtils.java
api/src/test/java/com/alibaba/nacos/api/naming/pojo/InstanceTest.java
api/src/test/java/com/alibaba/nacos/api/naming/utils/NamingUtilsTest.java
client/src/test/java/com/alibaba/nacos/client/naming/NacosNamingServiceTest.java

Do some optimization for #8371 .
Check cluster name in client when registerInstance
See unit test

[ISSUE #8345] Check cluster name in client when registerInstance

---

naming/src/main/java/com/alibaba/nacos/naming/core/CatalogServiceV2Impl.java
naming/src/test/java/com/alibaba/nacos/naming/core/CatalogServiceV2ImplTest.java

For #4982 
- Add Unit test for CatalogServiceV2Impl

[ISSUE#4982] Add Unit test for CatalogServiceV2Impl

---

api/src/main/java/com/alibaba/nacos/api/config/remote/response/ConfigPublishResponse.java
api/src/main/java/com/alibaba/nacos/api/config/remote/response/ConfigRemoveResponse.java

Fix Error Class Comment
Fix Class Comment of `ConfigPublishResponse` and `ConfigRemoveResponse`
XXXX

Fix Class Comment of `ConfigPublishResponse` and `ConfigRemoveResponse`

---

api/src/main/java/com/alibaba/nacos/api/config/convert/NacosConfigConverter.java
api/src/main/java/com/alibaba/nacos/api/naming/pojo/ServiceInfo.java

Fix Word Spelling
Fix Word Spelling in Comment and Log of ServiceInfo
Fix Word Spelling in Comment and Log of ServiceInfo

Fix word spelling

---

core/src/main/java/com/alibaba/nacos/core/distributed/raft/utils/RaftExecutor.java

Fix Word Spelling 'naocs' in RaftExecutor
Fix Word Spelling 'naocs' in RaftExecutor Class File
XXXX

Fix Word Spelling 'naocs' in RaftExecutor Class

---

naming/src/main/java/com/alibaba/nacos/naming/healthcheck/HealthCheckProcessorDelegate.java
naming/src/main/java/com/alibaba/nacos/naming/healthcheck/extend/AbstractHealthCheckProcessorExtend.java
naming/src/main/java/com/alibaba/nacos/naming/healthcheck/extend/HealthCheckExtendProvider.java
naming/src/main/java/com/alibaba/nacos/naming/healthcheck/extend/HealthCheckProcessorExtendV1.java
naming/src/main/java/com/alibaba/nacos/naming/healthcheck/extend/HealthCheckProcessorExtendV2.java
naming/src/main/java/com/alibaba/nacos/naming/healthcheck/v2/processor/HealthCheckProcessorV2Delegate.java
naming/src/test/java/com/alibaba/nacos/naming/healthcheck/extend/HealthCheckExtendProviderTest.java
naming/src/test/java/com/alibaba/nacos/naming/healthcheck/extend/HealthCheckProcessorExtendV1Test.java
naming/src/test/java/com/alibaba/nacos/naming/healthcheck/extend/HealthCheckProcessorExtendV2Test.java
naming/src/test/java/com/alibaba/nacos/naming/healthcheck/extend/TestChecker.java
naming/src/test/java/com/alibaba/nacos/naming/healthcheck/extend/TestHealthCheckProcessor.java
naming/src/test/java/com/alibaba/nacos/naming/healthcheck/v2/processor/HealthCheckProcessorV2DelegateTest.java

For #8243 . adapt v2 health check plugin
add v2 HealthCheckProcessorExtend,which load HealthCheckProcessorV2 processors by SPI. and add some unit test.
verified
* [✓] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [✓] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [✓] Write a pull request …

fix(#8243): adapt v2 health check plugin

---

core/src/main/java/com/alibaba/nacos/core/controller/NacosClusterController.java
core/src/main/java/com/alibaba/nacos/core/controller/v2/NacosClusterV2Controller.java
core/src/test/java/com/alibaba/nacos/core/controller/NacosClusterControllerTest.java
core/src/test/java/com/alibaba/nacos/core/controller/v2/NacosClusterV2ControllerTest.java

Fixes #8305 .
- Remove leave nacos server nodes API temporarily.

[ISSUE#8305] Remove leave nacos server nodes API temporarily.

---

client/src/main/java/com/alibaba/nacos/client/auth/impl/process/HttpLoginProcessor.java
client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java
common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClient.java

[ISSUE #8709] check serverList size before reconnect to server

---

core/src/main/java/com/alibaba/nacos/core/distributed/distro/task/execute/AbstractDistroExecuteTask.java
naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/v2/DistroClientTransportAgent.java

[ISSUE #8707] add distroKey log output when distro sync failed.

---

api/src/test/java/com/alibaba/nacos/api/naming/utils/NamingUtilsTest.java
client/src/test/java/com/alibaba/nacos/client/naming/NacosNamingServiceTest.java
client/src/test/java/com/alibaba/nacos/client/naming/remote/NamingClientProxyDelegateTest.java
client/src/test/java/com/alibaba/nacos/client/naming/remote/gprc/redo/NamingGrpcRedoServiceTest.java
naming/src/test/java/com/alibaba/nacos/naming/push/v2/task/PushExecuteTaskTest.java
naming/src/test/java/com/alibaba/nacos/naming/remote/rpc/handler/BatchInstanceRequestHandlerTest.java

Feat/ batch register add some unit tests
XX
XXXX

batch register add some unit tests

---

plugin/auth/src/main/java/com/alibaba/nacos/plugin/auth/api/IdentityContext.java
plugin/auth/src/main/java/com/alibaba/nacos/plugin/auth/api/Permission.java
plugin/auth/src/test/java/com/alibaba/nacos/plugin/auth/api/IdentityContextTest.java
plugin/auth/src/test/java/com/alibaba/nacos/plugin/auth/api/LoginIdentityContextTest.java
plugin/auth/src/test/java/com/alibaba/nacos/plugin/auth/api/PermissionTest.java
plugin/auth/src/test/java/com/alibaba/nacos/plugin/auth/api/RequestResourceTest.java
plugin/auth/src/test/java/com/alibaba/nacos/plugin/auth/constant/ActionTypesTest.java
plugin/auth/src/test/java/com/alibaba/nacos/plugin/auth/constant/ConstantsTest.java
plugin/auth/src/test/java/com/alibaba/nacos/plugin/auth/exception/AccessExceptionTest.java
plugin/auth/src/test/java/com/alibaba/nacos/plugin/auth/spi/client/ClientAuthPluginManagerTest.java
plugin/auth/src/test/java/com/alibaba/nacos/plugin/auth/spi/mock/MockAuthPluginService.java
plugin/auth/src/test/java/com/alibaba/nacos/plugin/auth/spi/mock/MockClientAuthService.java
plugin/auth/src/test/java/com/alibaba/nacos/plugin/auth/spi/mock/MockEmptyNameAuthPluginService.java
plugin/auth/src/test/resources/META-INF/services/com.alibaba.nacos.plugin.auth.spi.server.AuthPluginService

For #4981 .
- Add UT for nacos-auth-plugin module

[ISSUE#4981] Add UT for nacos-auth-plugin module

---

common/src/main/java/com/alibaba/nacos/common/utils/StringUtils.java

Remove repeated conditional test
XX
XXXX

[Polish] Remove repeated conditional test

---

client/src/main/java/com/alibaba/nacos/client/naming/cache/ServiceInfoHolder.java
naming/src/main/java/com/alibaba/nacos/naming/core/ServiceManager.java

Remove Duplicated Check in Method com.alibaba.nacos.client.naming.cache.ServiceInfoHolder#isChangedServiceInfo
Remove Duplicated Check in Method com.alibaba.nacos.client.naming.cache.ServiceInfoHolder#isChangedServiceInfo
Test Case Passed in ServiceInfoHolderTest

Remove Duplicated Check in Method com.alibaba.nacos.client.naming.cache.ServiceInfoHolder#isChangedServiceInfo

---

core/src/main/java/com/alibaba/nacos/core/cluster/Member.java

[Polish] Add serialVersionUID

---

config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigController.java

to fix the problem that Request log section publishConfig and deleteConfig are invalid because the section parameter is inconsistent with the Controller parameter[#8720]
修复 RequestLogApsect切面定义的publishConfig、deleteConfig 和该两个入口实际参数不一致性，带来的切面失效，无法正常写入日志的问题
XX
XXXX

[#8720]fix the problem that request log(publishConfig and deleteConfig) dont effectively work

---

config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigController.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/InstanceMetadataProcessor.java

Fixes #8742 .
- Fix change instance metadata, the revision of service not change.
XXXX

[ISSUE#8742] Fix change instance metadata, the revision of service not change.

---

api/src/main/java/com/alibaba/nacos/api/remote/response/ErrorResponse.java
api/src/test/java/com/alibaba/nacos/api/remote/response/ErrorResponseTest.java
client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc/NamingGrpcClientProxy.java
client/src/main/java/com/alibaba/nacos/client/naming/remote/http/NamingHttpClientProxy.java
client/src/test/java/com/alibaba/nacos/client/naming/remote/gprc/NamingGrpcClientProxyTest.java
client/src/test/java/com/alibaba/nacos/client/naming/remote/http/NamingHttpClientProxyTest.java
core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcRequestAcceptor.java
naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperatorClientImpl.java
naming/src/main/java/com/alibaba/nacos/naming/core/ServiceManager.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/ClientOperationService.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/ClientOperationServiceProxy.java
naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/impl/EphemeralClientOperationServiceImpl.java
naming/src/main/java/com/alibaba/nacos/naming/remote/rpc/handler/InstanceRequestHandler.java
naming/src/test/java/com/alibaba/nacos/naming/core/InstanceOperatorClientImplTest.java
naming/src/test/java/com/alibaba/nacos/naming/core/v2/service/ClientOperationServiceProxyTest.java
naming/src/test/java/com/alibaba/nacos/naming/core/v2/service/impl/EphemeralClientOperationServiceImplTest.java
test/naming-test/src/test/java/com/alibaba/nacos/test/naming/AbstractInstanceOperate_ITCase.java

Check parameter for register instance request on server-side. ( #8371 )
Check cluster name in server-side when register instance.
See unit test

[ISSUE #8345] Check cluster name in server-side when registerInstance

---

naming/src/main/java/com/alibaba/nacos/naming/healthcheck/v2/HealthCheckTaskV2.java

[#8775] Fix HealthCheckTaskV2 blocks jraft's init when starting.

---

common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClient.java

Print detail exception info to log when connect to nacos server failed.
Add exception detail stacks when connect to server failed.

Add exception detail stacks when connect to server failed.

---

config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigController.java

Add comment for config aspect.

---

common/src/main/java/com/alibaba/nacos/common/cache/impl/SimpleCache.java

Add Generic Type for Simple Cache Map
Add Generic Type for Simple Cache Map

Add Generic Type for Simple Cache Map

---

pom.xml

Upgrade to 2.1.1

---

naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/AbstractClient.java

[ISSUE#8910] bug fix calcu ipCount

---

client/src/main/java/com/alibaba/nacos/client/naming/core/ServerListManager.java

for #8882 
只有endpoint和serverList都为空时才抛异常
本地启动address服务验证正常

[#ISSUE 8882]FIX nacos-client 2.1.0 erorr use endpoint configuration
