alibaba/nacos

- client/src/main/java/com/alibaba/nacos/client/config/impl/ServerListManager.java
> [ISSUE #8925] fix that the value of hasQueryString is always false

- common/src/main/java/com/alibaba/nacos/common/utils/MD5Utils.java
[ISSUES#8905]simplify some code
> [ISSUES#8905]simplify some code

- naming/src/main/java/com/alibaba/nacos/naming/core/v2/pojo/BatchInstanceData.java
For ISSUE #8931 
Fix BatchInstanceData cannot Serializable question。
append implement implements Serializable
* [] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run …
> [ISSUE #8931] Fix bug :BatchInstanceData cannot Serializable question

- distribution/bin/startup.cmd
- distribution/bin/startup.sh
解决nacos服务端没有加载鉴权/加解密插件的问题
启动脚本中`loader.path`添加目录路径`${BASE_DIR}/plugins`
XXXX
> fix #8947.

- consistency/src/test/java/com/alibaba/nacos/consistency/serialize/HessianSerializerTest.java
- console/src/test/java/com/alibaba/nacos/console/controller/NamespaceControllerTest.java
- console/src/test/java/com/alibaba/nacos/console/controller/ServerStateControllerTest.java
> add some junit test

- common/src/main/java/com/alibaba/nacos/common/packagescan/resource/PathMatchingResourcePatternResolver.java
Flip the call to equals method to avoid null pointer exception.
XXXXX
Flip the call to equals method to avoid null pointer exception. 
完善代码规范将equals调用翻转
XXXX
> Improve code specifications.

- console/src/main/java/com/alibaba/nacos/console/controller/UserController.java
1.x版本存在用户可以修改其他用户密码的问题，因为console/src/main/java/com/alibaba/nacos/console/controller/UserController.java 的 第147行虽然往前端写了403，后面的代码还是会执行，所以还是把另一个用户的密码修改成功了。
> fix #3720, one user(not admin) can change others password by api.

- core/src/test/java/com/alibaba/nacos/core/cluster/lookup/LookupFactoryTest.java
fix LookupFactoryTest  ut / ci
XX
XXXX
> fix LookupFactoryTest  ut / ci

- common/src/main/java/com/alibaba/nacos/common/utils/CollectionUtils.java
- core/pom.xml
- core/src/main/java/com/alibaba/nacos/core/cluster/address/ServerConfAddressPlugin.java
- core/src/main/java/com/alibaba/nacos/core/cluster/address/StandAloneAddressPlugin.java
- core/src/main/resources/META-INF/services/com.alibaba.nacos.plugin.address.spi.AddressPlugin
- core/src/test/java/com/alibaba/nacos/core/cluster/address/ServerConfAddressPluginTest.java
- core/src/test/java/com/alibaba/nacos/core/cluster/address/StandAloneAddressPluginTest.java
- plugin/address/pom.xml
- plugin/address/src/main/java/com/alibaba/nacos/plugin/address/common/AddressProperties.java
- plugin/address/src/main/java/com/alibaba/nacos/plugin/address/exception/AddressException.java
- plugin/address/src/main/java/com/alibaba/nacos/plugin/address/impl/EndpointAddressPlugin.java
- plugin/address/src/main/java/com/alibaba/nacos/plugin/address/impl/PropertyAddressPlugin.java
- plugin/address/src/main/java/com/alibaba/nacos/plugin/address/spi/AbstractAddressPlugin.java
- plugin/address/src/main/java/com/alibaba/nacos/plugin/address/spi/AddressPlugin.java
- plugin/address/src/main/java/com/alibaba/nacos/plugin/address/spi/AddressPluginManager.java
- plugin/address/src/main/resources/META-INF/services/com.alibaba.nacos.plugin.address.spi.AddressPlugin
- plugin/address/src/test/java/com/alibaba/nacos/plugin/address/common/AddressPropertiesTest.java
- plugin/address/src/test/java/com/alibaba/nacos/plugin/address/exception/AddressExceptionTest.java
- plugin/address/src/test/java/com/alibaba/nacos/plugin/address/impl/EndpointAddressPluginTest.java
- plugin/address/src/test/java/com/alibaba/nacos/plugin/address/impl/PropertyAddressPluginTest.java
- plugin/address/src/test/java/com/alibaba/nacos/plugin/address/spi/AddressPluginManagerTest.java
- plugin/pom.xml
- pom.xml
For #8310 , add nacos-address-plugin module
XX
XXXX
> For #8310, add nacos-address-plugin module

- common/src/test/java/com/alibaba/nacos/common/utils/ReflectUtilsTest.java
> add unit test for ReflectUtils

- common/src/test/java/com/alibaba/nacos/common/utils/ByteUtilsTest.java
- common/src/test/java/com/alibaba/nacos/common/utils/ConcurrentHashSetTest.java
- common/src/test/java/com/alibaba/nacos/common/utils/InetAddressValidatorTest.java
- common/src/test/java/com/alibaba/nacos/common/utils/PropertyUtilsTest.java
- common/src/test/java/com/alibaba/nacos/common/utils/to/User.java
add some common utils UT
XX
XXXX
> add some utils UT

- naming/src/main/java/com/alibaba/nacos/naming/healthcheck/HealthCheckCommon.java
- naming/src/main/java/com/alibaba/nacos/naming/healthcheck/v2/processor/HealthCheckCommonV2.java
Fix spelling mistakes.
XX
XXXX
> Fix spelling mistakes.

- common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClient.java
- common/src/test/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClientTest.java
Fix the problem for #9013
Add some custom config in grpc config 
e.g. nacos.client.grpc.pool.alive , nacos.client.grpc.timeout
> [ISSUE #9013] enhance grpc client

- client/src/main/java/com/alibaba/nacos/client/config/http/ServerHttpAgent.java
> [ISSUE #9047] Fix ServerListMgr is not shutdown.

- common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcUtils.java
> [ISSUE #8934] add header back after convert request to jsonBytes

- config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/DistributedDatabaseOperateImpl.java
- plugin/encryption/src/main/java/com/alibaba/nacos/plugin/encryption/handler/EncryptionHandler.java
- plugin/encryption/src/test/java/com/alibaba/nacos/plugin/encryption/handler/EncryptionHandlerTest.java
fix corner case config dataId 'cipher-' that cannot create
1. skip enc process when data-id equals encryption data-id prefix
2. a safer way to parse cipher algorithem 
success to create config 'cipher-' on page
> [ISSUE #9023] fix corner case config dataId 'cipher-' that cannot create

- client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc/NamingGrpcClientProxy.java
- client/src/test/java/com/alibaba/nacos/client/naming/remote/gprc/NamingGrpcClientProxyTest.java
fix unsubscribe request serviceName and groupName mismatch bug
> fix unsubscribe request serviceName and groupName mismatch bug

- api/src/main/java/com/alibaba/nacos/api/exception/api/NacosApiException.java
- config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigController.java
- config/src/main/java/com/alibaba/nacos/config/server/controller/v2/ConfigControllerV2.java
- config/src/main/java/com/alibaba/nacos/config/server/exception/GlobalExceptionHandler.java
- config/src/main/java/com/alibaba/nacos/config/server/service/ConfigOperationService.java
- config/src/main/java/com/alibaba/nacos/config/server/utils/ParamUtils.java
- config/src/test/java/com/alibaba/nacos/config/server/controller/ConfigControllerTest.java
- config/src/test/java/com/alibaba/nacos/config/server/controller/v2/ConfigControllerV2Test.java
- config/src/test/java/com/alibaba/nacos/config/server/service/ConfigOperationServiceTest.java
- console/src/main/java/com/alibaba/nacos/console/controller/NamespaceController.java
- console/src/main/java/com/alibaba/nacos/console/controller/v2/NamespaceControllerV2.java
- console/src/main/java/com/alibaba/nacos/console/exception/NacosApiExceptionHandler.java
- console/src/main/java/com/alibaba/nacos/console/service/NamespaceOperationService.java
- console/src/test/java/com/alibaba/nacos/console/controller/v2/NamespaceControllerV2Test.java
- console/src/test/java/com/alibaba/nacos/console/service/NamespaceOperationServiceTest.java
> for [issue#8308], fix NacosApiException

- plugin/datasource/pom.xml
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/constants/TableConstant.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/manager/InitAndClosable.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/manager/MapperManager.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/Mapper.java
For issue#8312
Create data source plugin framework.
XXXX
> Create data source plugin framework.

- config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigController.java
- config/src/main/java/com/alibaba/nacos/config/server/controller/v2/ConfigControllerV2.java
- config/src/main/java/com/alibaba/nacos/config/server/model/ConfigRequestInfo.java
- config/src/main/java/com/alibaba/nacos/config/server/model/form/ConfigForm.java
- config/src/main/java/com/alibaba/nacos/config/server/service/ConfigOperationService.java
- config/src/test/java/com/alibaba/nacos/config/server/controller/v2/ConfigControllerV2Test.java
- config/src/test/java/com/alibaba/nacos/config/server/service/ConfigOperationServiceTest.java
- console/src/main/java/com/alibaba/nacos/console/controller/v2/NamespaceControllerV2.java
- console/src/main/java/com/alibaba/nacos/console/model/form/NamespaceForm.java
- console/src/test/java/com/alibaba/nacos/console/controller/v2/NamespaceControllerV2Test.java
…orm, ConfigRequestInfo and NamespaceForm respectively
#8308 
rename ConfigVo, ConfigRequestInfoVo and NamespaceVo to ConfigForm, ConfigRequestInfo and NamespaceForm respectively
> fix incorrect class naming

- README.md
Increase README content
1. add eBook link
yes
> [ISSUE #7459] add eBook link

- common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClient.java
- common/src/test/java/com/alibaba/nacos/common/remote/client/RpcClientTest.java
> Fix the actual number of health check retries less than the set one.

- client/src/test/java/com/alibaba/nacos/client/naming/remote/gprc/NamingGrpcClientProxyTest.java
- common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClient.java
- common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClientConfig.java
- common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClientFactory.java
- common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/DefaultClientConfig.java
- common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClient.java
- common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClientConfig.java
- common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClusterClient.java
- common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcConstants.java
- common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcSdkClient.java
- common/src/test/java/com/alibaba/nacos/common/remote/client/RpcClientFactoryTest.java
- common/src/test/java/com/alibaba/nacos/common/remote/client/RpcClientTest.java
- common/src/test/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClientTest.java
- common/src/test/java/com/alibaba/nacos/common/remote/client/grpc/GrpcConstantsTest.java
- common/src/test/java/com/alibaba/nacos/common/remote/client/grpc/GrpcConstsTest.java
Fix the problem for #9013 
XXXXX
XX
XXXX
> [ISSUE #9013] Enhance Rpc config related to one RpcClientConfig

- common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClient.java
- common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClientFactory.java
- common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/DefaultClientConfig.java
- common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/DefaultGrpcClientConfig.java
- common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClient.java
- common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcConstants.java
- common/src/test/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClientTest.java
For #9013 .
- Refactor DefaultClientConfig for readability
- Rename DefaultClientConfig > DefaultGrpcClientConfig
- only load grpc config from system one time.
> [ISSUE#9013] Do some refactor for readability.

- naming/src/main/java/com/alibaba/nacos/naming/core/Cluster.java
1.Modifying duplicate code,remove unnecessary if
2.remove [instance.getIp() + ":" + instance.getPort()] and use the original Instance.toIpAddr() method,Because their implementation is the same
modifying to com.alibaba.nacos.naming.core.Cluster#updatedIps , remove redundant code
XXXX
> remove redundant code

- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/ConfigInfoMapper.java
For issue#8312
Commit ConfigInfoMapper.
> Commit ConfigInfoMapper.

- config/src/main/java/com/alibaba/nacos/config/server/service/datasource/DataSourcePoolProperties.java
- config/src/main/java/com/alibaba/nacos/config/server/service/datasource/ExternalDataSourceProperties.java
- config/src/test/java/com/alibaba/nacos/config/server/service/datasource/DataSourcePoolPropertiesTest.java
#9101 修复数据源连接DataSource中动态的ConnectionTimeout属性被覆盖问题
将连接超时和空闲超时放到了DataSourcePoolProperties类中，同时保持原有的连接超时为3s
* [x ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [x ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [x ] Write a pull request description that is detailed enough to understand …
> [ISSUE#9101] 修复数据源连接DataSource中动态的ConnectionTimeout属性被覆盖问题

- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/ConfigInfoAggrMapper.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/ConfigInfoMapper.java
For issue#8312
Update ConfigInfoMapper and create ConfigInfoAggrMapper.
> [ISSUE#8312] Update ConfigInfoMapper and create ConfigInfoAggrMapper.

- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/ConfigInfoBetaMapper.java
For issue #8312
Create ConfigInfoBetaMapper
> [ISSUE #8312] Create ConfigInfoBetaMapper.(#8312)

- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/ConfigInfoAggrMapper.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/ConfigInfoBetaMapper.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/ConfigInfoMapper.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/ConfigInfoTagMapper.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/GroupCapacityMapper.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/HisConfigInfoMapper.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/HistoryConfigInfoMapper.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/TenantCapacityMapper.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/TenantInfoMapper.java
Add more mapper.
For issue #8312 
Create ConfigInfoTagMapper, HisConfigInfoMapper and TenantInfoMapper.
> [ISSUE #8312] Add more mapper.

- config/src/main/java/com/alibaba/nacos/config/server/controller/HealthController.java
- config/src/test/java/com/alibaba/nacos/config/server/controller/HealthControllerTest.java
- core/src/main/java/com/alibaba/nacos/core/cluster/ServerMemberManager.java
- core/src/main/java/com/alibaba/nacos/core/controller/NacosClusterController.java
- core/src/main/java/com/alibaba/nacos/core/controller/v2/NacosClusterV2Controller.java
for #8310, complete server addrssing in plugin way
XX
XXXX
> [ISSUE #8310] complete server addressing  in plugin way

- config/src/main/java/com/alibaba/nacos/config/server/service/ClientTrackService.java
- config/src/main/java/com/alibaba/nacos/config/server/service/capacity/CapacityService.java
Resolve problem https://github.com/alibaba/nacos/issues/9135 redundant nullcheck code.
> [ISSUE #9135] Remove redundant nullcheck code.

- example/src/main/java/com/alibaba/nacos/example/NamingExample.java
Resolve problem #9130 running NPE.
> [ISSUE #9130] Fix naming example running NPE.

- api/src/main/java/com/alibaba/nacos/api/naming/utils/NamingUtils.java
- api/src/test/java/com/alibaba/nacos/api/naming/utils/NamingUtilsTest.java
- naming/src/main/java/com/alibaba/nacos/naming/controllers/InstanceControllerV2.java
- naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperatorClientImpl.java
- naming/src/main/java/com/alibaba/nacos/naming/misc/UtilsAndCommons.java
- naming/src/main/java/com/alibaba/nacos/naming/model/form/InstanceForm.java
- naming/src/main/java/com/alibaba/nacos/naming/model/form/InstanceMetadataBatchOperationForm.java
- naming/src/main/java/com/alibaba/nacos/naming/model/vo/InstanceDetailInfoVo.java
- naming/src/main/java/com/alibaba/nacos/naming/model/vo/InstanceMetadataBatchOperationVo.java
- naming/src/test/java/com/alibaba/nacos/naming/controllers/InstanceControllerV2Test.java
#8308 
update InstanceControllerV2 for api 2.0
> [ISSUE#8308] update InstanceControllerV2 for api 2.0

- core/src/main/java/com/alibaba/nacos/core/utils/WebUtils.java
- naming/src/test/java/com/alibaba/nacos/naming/pojo/instance/HttpRequestInstanceBuilderTest.java
> For #9106 Remove redundant judgment of WebUtils

- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/mysql/ConfigInfoAggrMapperByMySql.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/mysql/ConfigInfoBetaMapperByMySql.java
For issue#8312
Update the mysql implementation.
> [ISSUE #8312]Update the mysql implementation.

- istio/src/main/java/com/alibaba/nacos/istio/util/IstioCrdUtil.java
To improve code specifications by reference to #8965
In order to avoid null pointer exception by flipping equals()
XXXX
> Improving code specifications

- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/mysql/ConfigInfoAggrMapperByMySql.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/mysql/ConfigInfoBetaMapperByMySql.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/mysql/ConfigInfoTagMapperByMySql.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/mysql/HistoryConfigInfoMapperByMySql.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/ConfigInfoTagMapper.java
For issue#8312
Update the mappers by mysql.
> [ISSUE #8312]Update the mappers.

- core/src/main/java/com/alibaba/nacos/core/remote/control/TpsMonitorManager.java
Resolve problem https://github.com/alibaba/nacos/issues/9154 move null check operate forward and move try-catch to mothod inside.
> [ISSUE #9154] Solve the nullcheck of value previously dereferenced.

- naming/src/main/java/com/alibaba/nacos/naming/controllers/v2/HealthControllerV2.java
- naming/src/main/java/com/alibaba/nacos/naming/controllers/v2/InstanceControllerV2.java
- naming/src/main/java/com/alibaba/nacos/naming/controllers/v2/OperatorControllerV2.java
- naming/src/main/java/com/alibaba/nacos/naming/controllers/v2/ServiceControllerV2.java
- naming/src/main/java/com/alibaba/nacos/naming/core/ServiceOperatorV2Impl.java
- naming/src/main/java/com/alibaba/nacos/naming/model/form/ServiceForm.java
- naming/src/main/java/com/alibaba/nacos/naming/model/form/UpdateHealthForm.java
- naming/src/main/java/com/alibaba/nacos/naming/model/form/UpdateSwitchForm.java
- naming/src/main/java/com/alibaba/nacos/naming/model/vo/MetricsInfoVo.java
- naming/src/test/java/com/alibaba/nacos/naming/controllers/v2/InstanceControllerV2Test.java
- naming/src/test/java/com/alibaba/nacos/naming/controllers/v2/OperatorControllerV2Test.java
- naming/src/test/java/com/alibaba/nacos/naming/controllers/v2/ServiceControllerV2Test.java
#8308 
add OperatorControllerV2, update ServiceControllerV2
> update ServiceControllerV2, add OperatorControllerV2

- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/derby/ConfigInfoTagMapperByDerby.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/derby/HistoryConfigInfoMapperByDerby.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/mysql/ConfigInfoMapperByMySql.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/ConfigInfoMapper.java
For issue#8312
[ISSUE #8312]Update the ConfigInfoMapperByMySql and some derby mappers.
XXXX
> [ISSUE #8312]Update the ConfigInfoMapperByMySql and some derby mappers.

- config/src/test/java/com/alibaba/nacos/config/server/utils/GroupKeyTest.java
Solve #9172 wrong use of GroupKey2 in GroupKeyTest.
> [ISSUE #9172] Solve wrong use of GroupKey2 in GroupKeyTest.

- pom.xml
#9177 Upgrade org.yaml.snakeyaml version from 1.30 to 1.32
XXXXX
XX
XXXX
> [ISSUE #9177] Upgrade org.yaml.snakeyaml version from 1.30 to 1.32

- common/src/main/java/com/alibaba/nacos/common/notify/Event.java
- common/src/main/java/com/alibaba/nacos/common/notify/NotifyCenter.java
- common/src/main/java/com/alibaba/nacos/common/trace/event/naming/NamingTraceEvent.java
- naming/src/test/java/com/alibaba/nacos/naming/core/v2/event/publisher/NamingEventPublisherTest.java
Fixes #9060 .
Fix print logs for NamingTraceEvent.
> [ISSUE#9060] Fix print logs for NamingTraceEvent.

- config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigController.java
- config/src/main/java/com/alibaba/nacos/config/server/controller/v2/ConfigControllerV2.java
- config/src/main/java/com/alibaba/nacos/config/server/controller/v2/HistoryControllerV2.java
- config/src/main/java/com/alibaba/nacos/config/server/model/form/ConfigForm.java
- config/src/main/java/com/alibaba/nacos/config/server/service/ConfigOperationService.java
- config/src/main/java/com/alibaba/nacos/config/server/service/HistoryService.java
- config/src/main/java/com/alibaba/nacos/config/server/utils/ParamUtils.java
- config/src/test/java/com/alibaba/nacos/config/server/controller/v2/ConfigControllerV2Test.java
- config/src/test/java/com/alibaba/nacos/config/server/controller/v2/HistoryControllerV2Test.java
- console/src/main/java/com/alibaba/nacos/console/exception/NacosApiExceptionHandler.java
- naming/src/main/java/com/alibaba/nacos/naming/controllers/v2/ClientInfoControllerV2.java
- naming/src/main/java/com/alibaba/nacos/naming/misc/UtilsAndCommons.java
#8308 
add ClientInfoControllerV2
> Add ClientInfoControllerV2

- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/derby/ConfigInfoAggrMapperByDerby.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/derby/ConfigInfoMapperByDerby.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/derby/ConfigInfoTagsRelationMapperByDerby.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/mysql/ConfigInfoAggrMapperByMySql.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/mysql/ConfigInfoMapperByMySql.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/mysql/ConfigTagsRelationMapperByMySql.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/ConfigInfoAggrMapper.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/ConfigInfoMapper.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/ConfigTagsRelationMapper.java
For issue#8312
Finish all mappers.
> [ISSUE #8312]Finish all mappers.

- client/pom.xml
- client/src/main/java/com/alibaba/nacos/client/address/AbstractServerListManager.java
- client/src/main/java/com/alibaba/nacos/client/address/ServerListManager.java
- client/src/main/java/com/alibaba/nacos/client/config/http/ServerHttpAgent.java
- client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java
- client/src/main/java/com/alibaba/nacos/client/config/impl/ConfigTransportClient.java
- client/src/main/java/com/alibaba/nacos/client/config/impl/ServerListManager.java
- client/src/main/java/com/alibaba/nacos/client/naming/core/ServerListManager.java
- client/src/test/java/com/alibaba/nacos/client/config/NacosConfigServiceTest.java
- client/src/test/java/com/alibaba/nacos/client/config/http/ServerHttpAgentTest.java
- client/src/test/java/com/alibaba/nacos/client/config/impl/ServerListManagerTest.java
- client/src/test/java/com/alibaba/nacos/client/naming/core/ServerListManagerTest.java
- client/src/test/java/com/alibaba/nacos/client/naming/remote/gprc/NamingGrpcClientProxyTest.java
- common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClient.java
- core/src/main/java/com/alibaba/nacos/core/cluster/remote/ClusterRpcClientProxy.java
- pom.xml
for #8310, complete client addressing in plugin way
XX
XXXX
> [ISSUE #8310] complete client addressing in plugin way

- console/src/main/resources/application.properties
Fix wrong and duplicate mysql connection configuration.
XX
XXXX
> Fix wrong and duplicate mysql connection configuration.

- plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/controller/PermissionController.java
- plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/controller/RoleController.java
- plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/controller/UserController.java
- plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/persistence/EmbeddedPermissionPersistServiceImpl.java
- plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/persistence/EmbeddedRolePersistServiceImpl.java
- plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/persistence/EmbeddedUserPersistServiceImpl.java
- plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/persistence/ExternalPermissionPersistServiceImpl.java
- plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/persistence/ExternalRolePersistServiceImpl.java
- plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/persistence/ExternalUserPersistServiceImpl.java
- plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/persistence/PermissionPersistService.java
- plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/persistence/RolePersistService.java
- plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/persistence/UserPersistService.java
- plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/roles/NacosRoleServiceImpl.java
- plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/users/NacosUserDetailsServiceImpl.java
- plugin-default-impl/src/test/java/com/alibaba/nacos/plugin/auth/impl/persistence/EmbeddedRolePersistServiceImplTest.java
- plugin-default-impl/src/test/java/com/alibaba/nacos/plugin/auth/impl/persistence/EmbeddedUserPersistServiceImplTest.java
- plugin-default-impl/src/test/java/com/alibaba/nacos/plugin/auth/impl/persistence/ExternalRolePersistServiceImplTest.java
- plugin-default-impl/src/test/java/com/alibaba/nacos/plugin/auth/impl/persistence/ExternalUserPersistServiceImplTest.java
- plugin-default-impl/src/test/java/com/alibaba/nacos/plugin/auth/impl/roles/NacosRoleServiceImplTest.java
Support Fuzzy Query in Authority Control.
Add api to support fuzzy and accurate search in user, role, permission page.
> Feature #8941 Support Fuzzy Query in Authority Control--for api change.

- common/src/test/java/com/alibaba/nacos/common/utils/ConcurrentHashSetTest.java
- naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/v2/DistroClientDataProcessor.java
- naming/src/main/java/com/alibaba/nacos/naming/constants/ClientConstants.java
- naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/AbstractClient.java
- naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/Client.java
- naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/factory/impl/ConnectionBasedClientFactory.java
- naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/factory/impl/EphemeralIpPortClientFactory.java
- naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/impl/ConnectionBasedClient.java
- naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/impl/IpPortBasedClient.java
- naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/ClientManager.java
- naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/ClientManagerDelegate.java
- naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/ConnectionBasedClientManager.java
- naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/EphemeralIpPortClientManager.java
- naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/PersistentIpPortClientManager.java
- naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/impl/EphemeralClientOperationServiceImpl.java
- naming/src/main/java/com/alibaba/nacos/naming/utils/DistroUtils.java
- naming/src/test/java/com/alibaba/nacos/naming/core/v2/client/AbstractClientTest.java
- naming/src/test/java/com/alibaba/nacos/naming/core/v2/client/MockAbstractClient.java
- naming/src/test/java/com/alibaba/nacos/naming/core/v2/client/impl/ConnectionBasedClientTest.java
- naming/src/test/java/com/alibaba/nacos/naming/core/v2/client/impl/IpPortBasedClientTest.java
- naming/src/test/java/com/alibaba/nacos/naming/core/v2/client/manager/ClientManagerDelegateTest.java
- naming/src/test/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/ConnectionBasedClientManagerTest.java
- naming/src/test/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/EphemeralIpPortClientManagerTest.java
- naming/src/test/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/PersistentIpPortClientManagerTest.java
- naming/src/test/java/com/alibaba/nacos/naming/utils/DistroUtilsTest.java
> Support client hash revision for DISTRO

- config/src/main/java/com/alibaba/nacos/config/server/controller/v2/HistoryControllerV2.java
- console/src/main/java/com/alibaba/nacos/console/exception/NacosApiExceptionHandler.java
- naming/src/main/java/com/alibaba/nacos/naming/controllers/v2/HealthControllerV2.java
- naming/src/main/java/com/alibaba/nacos/naming/controllers/v2/InstanceControllerV2.java
- naming/src/main/java/com/alibaba/nacos/naming/controllers/v2/ServiceControllerV2.java
- naming/src/test/java/com/alibaba/nacos/naming/controllers/v2/ServiceControllerV2Test.java
> fix api result

- config/pom.xml
- config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedPaginationHelperImpl.java
- config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedStoragePersistServiceImpl.java
- config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePaginationHelperImpl.java
- config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/MapperManager.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/constants/DataSourceConstant.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/derby/ConfigInfoAggrMapperByDerby.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/derby/ConfigInfoBetaMapperByDerby.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/derby/ConfigInfoMapperByDerby.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/derby/ConfigInfoTagMapperByDerby.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/derby/ConfigInfoTagsRelationMapperByDerby.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/derby/HistoryConfigInfoMapperByDerby.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/mysql/ConfigInfoAggrMapperByMySql.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/mysql/ConfigInfoBetaMapperByMySql.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/mysql/ConfigInfoMapperByMySql.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/mysql/ConfigInfoTagMapperByMySql.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/mysql/ConfigTagsRelationMapperByMySql.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/mysql/HistoryConfigInfoMapperByMySql.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/ConfigInfoAggrMapper.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/ConfigInfoBetaMapper.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/ConfigInfoMapper.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/ConfigInfoTagMapper.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/ConfigTagsRelationMapper.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/HistoryConfigInfoMapper.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/Mapper.java
- plugin/datasource/src/main/resources/META-INF/services/com.alibaba.nacos.plugin.datasource.mapper.Mapper
For issue#8312
Finish the datasource plugin.
XXXX
> [ISSUE #8312]Finish the datasource plugin.

- api/src/main/java/com/alibaba/nacos/api/naming/remote/response/BatchInstanceResponse.java
- api/src/main/java/com/alibaba/nacos/api/naming/remote/response/InstanceResponse.java
Fix ISSUE #9251  BatchInstanceResponse and InstanceResponse grpc deserialize lost type field.
XXXXX
XX
XXXX
> [ISSUE#9251] Fix Grpc deserialize lost type field

- config/src/main/java/com/alibaba/nacos/config/server/constant/Constants.java
- config/src/main/java/com/alibaba/nacos/config/server/service/datasource/LocalDataSourceServiceImpl.java
- config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/DerbySnapshotOperation.java
For issue#6112
Unified derby-data variables
XXXX
> [ISSUE #6112]Unified derby-data variables

- core/src/main/java/com/alibaba/nacos/core/distributed/raft/JRaftServer.java
fix #9271  
Do not  continuous `cliService.getPeers` after server shutdown
> [ISSUE #9271] fix 'JraftServer' npe log

- console/src/main/resources/application.properties
- naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/impl/PersistentClientOperationServiceImpl.java
Fix issue #6876 .
XXXXX
XX
XXXX
> [ISSUE #6876] Concurrent instance deregiste NullPointerException

- config/src/main/java/com/alibaba/nacos/config/server/model/ConfigInfoBaseEx.java
Generate the serialVersionUID by IDEA to replace -1L as suggested in #9254
XX
XXXX
> Generate the serialVersionUID by IDEA

- config/src/main/java/com/alibaba/nacos/config/server/model/GroupInfo.java
- config/src/main/java/com/alibaba/nacos/config/server/model/Page.java
Generate the serialVersionUID by IDEA to replace -1L as suggested in
XXXX
* [x ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
> Update Generate serialVersionUID 1L Value to idea random

- client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java
> [ISSUE #9305] fix bug in ClientWorker.resourceBuild()

- config/src/main/java/com/alibaba/nacos/config/server/model/ConfigAdvanceInfo.java
- config/src/main/java/com/alibaba/nacos/config/server/model/ConfigInfo.java
- config/src/main/java/com/alibaba/nacos/config/server/model/ConfigInfoBase.java
- config/src/main/java/com/alibaba/nacos/config/server/model/ConfigInfoEx.java
Generate the serialVersionUID by IDEA to replace -1L as suggested in
> Update Generate serialVersionUID Value to idea random

- client/pom.xml
to reduce nacos-client jar size 
> [ISSUE#7929] minijar pom update ,to reduce nacos-client jar size 

- common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClient.java
- common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClient.java
- common/src/test/java/com/alibaba/nacos/common/remote/client/RpcClientTest.java
Fixes #9269 .
RpcClient support parse ipv6 address.
> [ISSUE#9269] RpcClient support parse ipv6 address.

- plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/LdapAuthConfig.java
> [ISSUE #9341] Bug fix can not create bean ldapAuthenticationProvider 

- naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/AbstractClient.java
- naming/src/test/java/com/alibaba/nacos/naming/core/v2/client/AbstractClientTest.java
> buf fix ip count metrics

- common/src/test/java/com/alibaba/nacos/common/utils/JacksonUtilsTest.java
Followed By ISSUE #9338
The `com.alibaba.nacos.common.utils.JacksonUtilsTest.testToJsonBytes1` at common has flakiness.
The test flakiness is due to comparisons between Json Bytes and outputs from` JacksonUtils.toJsonBytes()`.
However, `JsonObject `does not guarantee entry orders, its object is an unordered set of name/value pairs, and internal permutations may occur in the output from` toJson()`.
Since the JSON tool used in the Project is jackson, so I use the `com.fasterxml.jackson.annotation.JsonPropertyOrder` to set each parameter‘s order at the top of class.
This test avoids nested or different orders of JSON Bytes that cause flaky errors.
Since I didn't touch any Source code, it should be no impact on the project.
And it passed the local test that the guidelines mentioned.
Follow …
> [ISSUE #9338] Fixed Possible Json Ordering Permutations Problem in Tests

- test/core-test/src/test/java/com/alibaba/nacos/test/core/auth/AuthBase.java
- test/core-test/src/test/java/com/alibaba/nacos/test/core/auth/LdapAuth_ITCase.java
- test/core-test/src/test/resources/application.properties
> Add integration testing for ldap auth

- plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/LdapAuthConfig.java
- plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/NacosLdapContextSource.java
- test/core-test/src/test/java/com/alibaba/nacos/test/core/auth/LdapAuth_ITCase.java
> [ISSUE #9366] Support Ldaps authentication

- api/src/main/java/com/alibaba/nacos/api/naming/NamingService.java
- client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingService.java
- client/src/main/java/com/alibaba/nacos/client/naming/remote/NamingClientProxy.java
- client/src/main/java/com/alibaba/nacos/client/naming/remote/NamingClientProxyDelegate.java
- client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc/NamingGrpcClientProxy.java
- client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc/redo/NamingGrpcRedoService.java
- client/src/main/java/com/alibaba/nacos/client/naming/remote/http/NamingHttpClientProxy.java
- client/src/test/java/com/alibaba/nacos/client/naming/NacosNamingServiceTest.java
- client/src/test/java/com/alibaba/nacos/client/naming/remote/AbstractNamingClientProxyTest.java
fixed #9331 
support Batch DeRegister
XX
XXXX
> feat/support Batch DeRegister

- config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedStoragePersistServiceImpl.java
- config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/derby/HistoryConfigInfoMapperByDerby.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/mysql/ConfigInfoMapperByMySql.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/mysql/ConfigTagsRelationMapperByMySql.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/mysql/HistoryConfigInfoMapperByMySql.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/HistoryConfigInfoMapper.java
> [ISSUE 8312] Fixed some problems with configuration sql

- config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedStoragePersistServiceImpl.java
- config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java
Fix Some Persist Service Implementation.
XX
XXXX
> [ISSUE #8312]Fix Persist Service Implementation.

- config/src/main/resources/META-INF/nacos-db.sql
- distribution/conf/mysql-schema.sql
更新ISSUE的表的字段长度的问题
#9334 
根据讨论结果，更新为128长度，目前涉及到2个文件的改动
> [ISSUE #9334] Update group_id field length from 255 to 128

- pom.xml
> Upgrade to 2.2.0-beta.

- client/src/main/java/com/alibaba/nacos/client/naming/remote/NamingClientProxy.java
- client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc/NamingGrpcClientProxy.java
fix batch Deregister Common.
XX
XXXX
> fix batch Deregister common

- client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc/NamingPushRequestHandler.java
fix object name of NotifySubscriberRequest at NamingPushRequestHandler
XXXX
> fix NotifySubscriberRequest name

- client/src/main/java/com/alibaba/nacos/client/naming/event/InstancesChangeNotifier.java
Optimize some codes for InstancesChangeNotifier
XXXXX
XX
XXXX
> Optimize some codes for InstancesChangeNotifier

- client/src/main/java/com/alibaba/nacos/client/utils/AppNameUtils.java
- client/src/main/java/com/alibaba/nacos/client/utils/ParamUtil.java
- client/src/main/java/com/alibaba/nacos/client/utils/TenantUtil.java
- Replace system.getProperties and system.getEnv with NacosClientProperties
relate #9356
XXXXX
XX
XXXX
> [ISSUE #8622] sub pr of 9356 - util module

- config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedStoragePersistServiceImpl.java
- config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/derby/TenantInfoMapperByDerby.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/mysql/TenantInfoMapperByMySql.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/TenantInfoMapper.java
- plugin/datasource/src/main/resources/META-INF/services/com.alibaba.nacos.plugin.datasource.mapper.Mapper
Add Tenant Information mapper.
Add Tenant Information mapper.
XXXX
> [ISSUE #9449]Add Tenant Information mapper.

- client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java
fix ClientWorker nullpointer judgement order around function "refreshContentAndCheck "
the judgement " if (cache != null) " is executed after  "cacheMap.get().get(changeKey).isInitializing()"
and the object "cache" could be null
XX
XXXX
> [bug-fix]fix ClientWorker NullPointer judement order

- api/src/main/java/com/alibaba/nacos/api/common/Constants.java
- config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedStoragePersistServiceImpl.java
- config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/MapperManager.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/constants/TableConstant.java
> [ISSUE #9466] Modify the findMapper method of MapperManager to be a generic method

- config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedStoragePersistServiceImpl.java
- config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/derby/ConfigInfoAggrMapperByDerby.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/derby/ConfigInfoBetaMapperByDerby.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/derby/ConfigInfoMapperByDerby.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/derby/ConfigInfoTagMapperByDerby.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/derby/ConfigInfoTagsRelationMapperByDerby.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/derby/HistoryConfigInfoMapperByDerby.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/mysql/ConfigInfoAggrMapperByMySql.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/mysql/ConfigInfoBetaMapperByMySql.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/mysql/ConfigInfoMapperByMySql.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/mysql/ConfigInfoTagMapperByMySql.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/mysql/ConfigTagsRelationMapperByMySql.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/mysql/HistoryConfigInfoMapperByMySql.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/AbstractMapper.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/ConfigInfoAggrMapper.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/ConfigInfoBetaMapper.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/ConfigInfoMapper.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/ConfigInfoTagMapper.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/ConfigTagsRelationMapper.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/HistoryConfigInfoMapper.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/Mapper.java
> [ISSUE #9475] Abstract common count method

- config/src/main/java/com/alibaba/nacos/config/server/service/capacity/TenantCapacityPersistService.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/derby/TenantCapacityMapperByDerby.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/mysql/TenantCapacityMapperByMySql.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/TenantCapacityMapper.java
- plugin/datasource/src/main/resources/META-INF/services/com.alibaba.nacos.plugin.datasource.mapper.Mapper
For issue9449
Add Tenant Capacity mapper.
XXXX
> [ISSUE #9449]Add Tenant Capacity mapper.

- config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedStoragePersistServiceImpl.java
- config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/derby/ConfigInfoMapperByDerby.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/mysql/ConfigInfoMapperByMySql.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/ConfigInfoMapper.java
fix ： #9486
For issue#9486
Fix paging parameters.
XXXX
> [ISSUE #9486]Optimizing paging parameters.

- config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedStoragePersistServiceImpl.java
- config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/derby/ConfigInfoAggrMapperByDerby.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/derby/ConfigInfoBetaMapperByDerby.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/derby/ConfigInfoTagMapperByDerby.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/derby/ConfigInfoTagsRelationMapperByDerby.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/mysql/ConfigInfoAggrMapperByMySql.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/mysql/ConfigInfoTagMapperByMySql.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/mysql/ConfigTagsRelationMapperByMySql.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/ConfigInfoAggrMapper.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/ConfigInfoBetaMapper.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/ConfigInfoTagMapper.java
> [ISSUE #9486] Optimizing paging parameters

- config/src/main/java/com/alibaba/nacos/config/server/service/capacity/GroupCapacityPersistService.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/derby/GroupCapacityMapperByDerby.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/mysql/GroupCapacityMapperByMysql.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/GroupCapacityMapper.java
- plugin/datasource/src/main/resources/META-INF/services/com.alibaba.nacos.plugin.datasource.mapper.Mapper
- plugin/encryption/src/main/java/com/alibaba/nacos/plugin/encryption/EncryptionPluginManager.java
> [ISSUE #9506] Sql extraction of group_capacity table

- config/src/main/java/com/alibaba/nacos/config/server/service/repository/PersistService.java
- config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedStoragePersistServiceImpl.java
- config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/derby/ConfigInfoAggrMapperByDerby.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/derby/ConfigInfoMapperByDerby.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/derby/ConfigInfoTagsRelationMapperByDerby.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/mysql/ConfigInfoAggrMapperByMySql.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/mysql/ConfigInfoMapperByMySql.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/mysql/ConfigTagsRelationMapperByMySql.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/ConfigInfoAggrMapper.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/ConfigInfoMapper.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/ConfigTagsRelationMapper.java
> [ISSUE #9516] Clean up PersistService invalid code logic

- plugin/datasource/src/test/java/com/alibaba/nacos/plugin/datasource/impl/mysql/GroupCapacityMapperByMysqlTest.java
> [ISSUE #9523] Add unit tests to GroupCapacityMapperByMySql class

- plugin/datasource/src/test/java/com/alibaba/nacos/plugin/datasource/MapperManagerTest.java
> [ISSUE #9523] Add unit tests to MapperManager class

- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/AbstractMapper.java
- plugin/datasource/src/test/java/com/alibaba/nacos/plugin/datasource/mapper/AbstractMapperTest.java
> [ISSUE #9523] Add unit tests to AbstractMapper class

- plugin/datasource/src/test/java/com/alibaba/nacos/plugin/datasource/impl/mysql/TenantInfoMapperByMySqlTest.java
> [ISSUE #9523] Add unit tests to TeantInfoMapperByMySql class

- plugin/datasource/src/test/java/com/alibaba/nacos/plugin/datasource/impl/mysql/TenantCapacityMapperByMySqlTest.java
> [ISSUE #9523] Add unit tests to TeantCapacityMapperByMySql class

- plugin/datasource/src/test/java/com/alibaba/nacos/plugin/datasource/impl/mysql/HistoryConfigInfoMapperByMySqlTest.java
> [ISSUE #9523] Add unit tests to HistoryConfigInfoMapperByMySql class

- plugin/datasource/src/test/java/com/alibaba/nacos/plugin/datasource/impl/mysql/ConfigTagsRelationMapperByMySqlTest.java
> [ISSUE #9523] Add unit tests to ConfigTagsRelationMapperByMySql class

- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/mysql/ConfigInfoMapperByMySql.java
- plugin/datasource/src/test/java/com/alibaba/nacos/plugin/datasource/impl/mysql/ConfigInfoMapperByMySqlTest.java
> [ISSUE #9523] Add unit tests to ConfigInfoMapperByMySql class

- plugin/datasource/src/test/java/com/alibaba/nacos/plugin/datasource/impl/mysql/ConfigInfoBetaMapperByMySqlTest.java
> [ISSUE #9524] Add unit tests to ConfigInfoBetaMapperByMySql class

- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/mysql/ConfigInfoAggrMapperByMySql.java
- plugin/datasource/src/test/java/com/alibaba/nacos/plugin/datasource/impl/mysql/ConfigInfoAggrMapperByMySqlTest.java
> [ISSUE #9523] Add unit tests to ConfigInfoAggrMapperByMySql class

- plugin/datasource/src/test/java/com/alibaba/nacos/plugin/datasource/impl/derby/TenantCapacityMapperByDerbyTest.java
> [ISSUE #9523] Add unit tests to TenantCapacityMapperByDerby class

- plugin/datasource/src/test/java/com/alibaba/nacos/plugin/datasource/impl/derby/HistoryConfigInfoMapperByDerbyTest.java
> [ISSUE #9523] Add unit tests to HistoryConfigInfoMapperByDerby class

- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/derby/ConfigInfoAggrMapperByDerby.java
- plugin/datasource/src/test/java/com/alibaba/nacos/plugin/datasource/impl/derby/ConfigInfoAggrMapperByDerbyTest.java
> [ISSUE #9523] Add unit tests to ConfigInfoAggrMapperByDerby class

- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/derby/ConfigInfoBetaMapperByDerby.java
- plugin/datasource/src/test/java/com/alibaba/nacos/plugin/datasource/impl/derby/ConfigInfoBetaMapperByDerbyTest.java
> [ISSUE #9523] Add unit tests to ConfigInfoBetaMapperByDerby class

- plugin/datasource/src/test/java/com/alibaba/nacos/plugin/datasource/impl/derby/ConfigInfoMapperByDerbyTest.java
> [ISSUE #9523] Add unit tests to ConfigInfoMapperByDerby class

- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/derby/ConfigInfoTagMapperByDerby.java
- plugin/datasource/src/test/java/com/alibaba/nacos/plugin/datasource/impl/derby/ConfigInfoTagMapperByDerbyTest.java
> [ISSUE #9523]  Add unit tests to ConfigInfoTagMapperByDerby class

- plugin/datasource/src/test/java/com/alibaba/nacos/plugin/datasource/impl/derby/ConfigInfoTagsRelationMapperByDerbyTest.java
> [ISSUE #9523] Add unit tests to ConfigInfoTagRelationMapperByDerby class

- plugin/datasource/src/test/java/com/alibaba/nacos/plugin/datasource/impl/derby/GroupCapacityMapperByDerbyTest.java
> [ISSUE #9523] Add unit tests to GroupCapacityMapperByDerby class

- naming/src/main/java/com/alibaba/nacos/naming/core/v2/ServiceManager.java
> [ISSUE#9586]解决服务元数据清理逻辑导致的反注册失败问题

- console/pom.xml
- console/src/main/resources/application.properties
- distribution/conf/application.properties
- distribution/conf/application.properties.example
- pom.xml
- prometheus/pom.xml
- prometheus/src/main/java/com/alibaba/nacos/prometheus/PrometheusApp.java
- prometheus/src/main/java/com/alibaba/nacos/prometheus/api/ApiConstants.java
- prometheus/src/main/java/com/alibaba/nacos/prometheus/controller/PrometheusController.java
Fix issue #8694 
XXXXX
XX
XXXX
> [ISSUE #8694] Support prometheus http service discovery

- common/src/main/java/com/alibaba/nacos/common/model/RestResult.java
- common/src/test/java/com/alibaba/nacos/common/utils/JacksonUtilsTest.java
Related to issue https://github.com/alibaba/nacos/issues/9463
To fix the flaky test caused by possible JSON ordering permutations as explained in the issue https://github.com/alibaba/nacos/issues/9463.
1. Use a LinkedHashMap instead of HashMap to preserve the order of insertion.
2. Use the [@JsonPropertyOrder(alphabetic = true)](https://fasterxml.github.io/jackson-annotations/javadoc/2.8/com/fasterxml/jackson/annotation/JsonPropertyOrder.html#alphabetic()) to set order at the top of the ResultSet class.
This test avoids nested or different orders of JSON bytes that cause flaky errors.
There is 1 change in the source code - Annotation of the class ResultSet with [@JsonPropertyOrder(alphabetic = true)](https://fasterxml.github.io/jackson-annotations/javadoc/2.8/com/fasterxml/jackson/annotati …
> [ISSUE #9643] Fixed Possible JSON Ordering Permutations Problem in Tests

- core/src/main/java/com/alibaba/nacos/core/cluster/ServerMemberManager.java
- core/src/main/java/com/alibaba/nacos/core/cluster/address/ServerConfAddressPlugin.java
- plugin/address/pom.xml
- plugin/address/src/main/java/com/alibaba/nacos/plugin/address/impl/EndpointAddressPlugin.java
- plugin/address/src/main/java/com/alibaba/nacos/plugin/address/spi/AddressPluginManager.java
optimize some logic in address plugin.
optimize some logic in address plugin.
> [optimize] optimize some logic in address plugin.

- sys/src/main/java/com/alibaba/nacos/sys/file/WatchFileCenter.java
Fix issue #9603 
XXXXX
XX
XXXX
> [ISSUE #9603] Catch ClosedWatchServiceException after exit  normally.

- naming/src/main/java/com/alibaba/nacos/naming/misc/HttpClientManager.java
> [ISSUE #9474] 持久化实例的健康检查方式改为http后，部分实例显示为不健康

- config/src/main/java/com/alibaba/nacos/config/server/service/notify/AsyncNotifyService.java
FIX ISSUE #9607
1. slf4j.Logger 在确定满足日志等级情况下会去调用ex的toString，这里直接toString，会造成即使没满足日志等级的情况下也会执行toString
2. 删除注释代码
3. 解除sonar访问成员权限警告，外部类可以访问到内部类的私有成员，编译执行没有问题，和其他内部类成员访问权限保持一致（其他内部类成员也是采用相同的方式被外部类访问，例如isBeta)
please check the code diff
> [ISSUE #9607] Fix AsyncNotifyService  SonarLint check warning

- console-ui/src/pages/ServiceManagement/ServiceList/ServiceList.js
fix #9597 
feat: Service List page retains query information.
XXXX
> [ISSUE #9597]feat: Service List page retains query information.

- naming/src/main/java/com/alibaba/nacos/naming/controllers/OperatorController.java
- naming/src/main/java/com/alibaba/nacos/naming/controllers/v2/ClientInfoControllerV2.java
- naming/src/main/java/com/alibaba/nacos/naming/controllers/v2/InstanceControllerV2.java
- naming/src/main/java/com/alibaba/nacos/naming/core/v2/ServiceManager.java
- naming/src/main/java/com/alibaba/nacos/naming/core/v2/event/publisher/NamingEventPublisher.java
- naming/src/main/java/com/alibaba/nacos/naming/core/v2/index/ClientServiceIndexesManager.java
- naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/impl/PersistentClientOperationServiceImpl.java
- plugin/auth/src/main/java/com/alibaba/nacos/plugin/auth/api/IdentityContext.java
Code optimization, remove useless code.
一些是根据sonar的优化，一些是根本没用上的字段或者根本不会抛出的异常。
Some are optimizations based on sonar, some are unused fields or exceptions that will not be thrown at all.
> Code optimization, remove useless code.

- .github/workflows/ci.yml
- .github/workflows/it.yml
Replace deprecated set-state set-output GitHub Action's commands
- Update actions/cache 
- Update actions/checkout
> ci: Replace deprecated set-state set-output GitHub Action's commands

- config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedConfigInfoPersistServiceImpl.java
- config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedStoragePersistServiceImpl.java
- config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalConfigInfoPersistServiceImpl.java
- config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java
fix #9648
修复关于传入tagList长度的bug
1.修改了EmbeddedConfigInfoPersistServiceImpl.java和ExternalConfigInfoPersistServiceImpl.java需要传入的参数
params.size() -> tagArr.length
> [ISSUE #9648] 修复关于tagList传入参数有误

- client/src/test/java/com/alibaba/nacos/client/utils/ChooserTest.java
- console/src/main/resources/application.properties
> fix no dataSet when nacos server started

- auth/src/main/java/com/alibaba/nacos/auth/GrpcProtocolAuthService.java
fix GrpcProtocolAuthService comment 
XX
XXXX
> fix comment

- pom.xml
> Upgrade to 2.2.0.

- core/src/main/java/com/alibaba/nacos/core/control/SpringValueConfigsInitializer.java
- plugin/control/pom.xml
- plugin/control/src/main/java/com/alibaba/nacos/plugin/control/ControlManagerCenter.java
- plugin/control/src/main/java/com/alibaba/nacos/plugin/control/configs/ControlConfigs.java
- plugin/control/src/main/java/com/alibaba/nacos/plugin/control/configs/ControlConfigsInitializer.java
- plugin/control/src/main/java/com/alibaba/nacos/plugin/control/ruleactivator/ControlRuleChangeActivator.java
- plugin/control/src/main/java/com/alibaba/nacos/plugin/control/ruleactivator/DiskUtils.java
- plugin/control/src/main/java/com/alibaba/nacos/plugin/control/ruleactivator/LocalDiskRuleStorage.java
- plugin/control/src/main/java/com/alibaba/nacos/plugin/control/ruleactivator/RuleStorageProxy.java
> Develop optimize controplugin 20221214

- client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java
- client/src/test/java/com/alibaba/nacos/client/config/impl/ClientWorkerTest.java
> [ISSUE #9621] 增加检查服务端健康状态的功能。

- README.md
update readme for Contact Ding Group
update readme for Contact Ding Group
update readme for Contact Ding Group
update readme for Contact Ding Group
> update readme for Contact Ding Group

- console/src/main/java/com/alibaba/nacos/console/controller/v2/NamespaceControllerV2.java
> Fix namespace v2 api auth not work problem.

- client/src/main/java/com/alibaba/nacos/client/auth/impl/process/HttpLoginProcessor.java
> [ISSUE #9734] fix http login url ,add default port.

- core/src/main/java/com/alibaba/nacos/core/cluster/remote/ClusterRpcClientProxy.java
change log level from warn to info
change log level from warn to info
> polish:change log level warn to info when succeed

- core/src/main/java/com/alibaba/nacos/core/control/http/HttpTpsPointRegistry.java
RequestMappingHandlerMapping conflict
Fix Type Conflict
Add the specified bean name
> RequestMappingHandlerMapping conflict

- prometheus/src/main/java/com/alibaba/nacos/prometheus/controller/PrometheusController.java
Fix Issue #9728 
XXXXX
XX
XXXX
> [ISSUE #9728]  Prometheus http sd  返回空数组[]

- core/src/main/java/com/alibaba/nacos/core/control/http/HttpTpsPointRegistry.java
Prevent double triiger ContextRefreshedEvent  
XXXXX
XX
XXXX
> [Enhance] Prevent double triiger ContextRefreshedEvent  

- config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedConfigInfoAggrPersistServiceImpl.java
- config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedStoragePersistServiceImpl.java
- config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalConfigInfoAggrPersistServiceImpl.java
- config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/derby/ConfigInfoAggrMapperByDerby.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/mysql/ConfigInfoAggrMapperByMySql.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/ConfigInfoAggrMapper.java
- plugin/datasource/src/test/java/com/alibaba/nacos/plugin/datasource/impl/derby/ConfigInfoAggrMapperByDerbyTest.java
- plugin/datasource/src/test/java/com/alibaba/nacos/plugin/datasource/impl/mysql/ConfigInfoAggrMapperByMySqlTest.java
fix: replace the concatenated string with a placeholder in the batchRemoveAggr method (#9646)
prevent sql injection.
fix: replace concatenated strings with placeholders
- `plugin/datasource/src/test/java/com/alibaba/nacos/plugin/datasource/impl/derby/ConfigInfoAggrMapperByDerbyTest.java`
- `plugin/datasource/src/test/java/com/alibaba/nacos/plugin/datasource/impl/mysql/ConfigInfoAggrMapperByMySqlTest.java`
> [ISSUE #9646] Replace concatenated strings with placeholders

- config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalConfigInfoPersistServiceImpl.java
- config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java
remove unused local variables
XX
XXXX
> remove unused local variables

- pom.xml
FIX ISSUE #9767 #9504
XXXXX
XX
XXXX
> [ISSUE #9767 #9504] Upgeade-spring-boot version to 2.6.14

- pom.xml
1. support feature #9772 （use the same grpce version）.
2. support Apple Silicon.
3. fix CVEs。
upgrade **jraft-core** and **rpc-grpc-impl** version to **1.3.12**
XXXX
> [ISSUE #9789]upgrade jraft version to 1.3.12 .

- core/src/main/java/com/alibaba/nacos/core/remote/grpc/BaseGrpcServer.java
- core/src/main/java/io/grpc/netty/shaded/io/grpc/netty/NettyChannelHelper.java
- pom.xml
protobuf-java  to 3.21.11, proto-google-common-protos to 2.7.1
related issue #9772 
XX
XXXX
> [ISSUE #9772] feature about grpc (1/2) -- Upgrade grpc version

- client/src/main/java/com/alibaba/nacos/client/auth/impl/process/HttpLoginProcessor.java
nacos-client login failed.(In ConfigTransportClient).
related issue #9734 , #9769 .
XX
XXXX
> [ISSUE #9769] Fix config auth failed.

- core/src/main/java/com/alibaba/nacos/core/utils/StringPool.java
> [#ISSUE 9733] return origin key if value is null in StringPool.get()

- console/pom.xml
- pom.xml
fix #8541 for v1.x, Authorization bypass in Spring Security: [ CVE-2022-22978](https://github.com/advisories/GHSA-hh32-7344-cg2f)
XX
XXXX
> fix #8541 upgeade springboot version to 2.6.8

- address/pom.xml
- api/pom.xml
- auth/pom.xml
- client/pom.xml
- cmdb/pom.xml
- common/pom.xml
- config/pom.xml
- consistency/pom.xml
- console/pom.xml
- core/pom.xml
- example/pom.xml
- istio/pom.xml
- naming/pom.xml
- plugin-default-impl/pom.xml
- plugin/auth/pom.xml
- plugin/control/pom.xml
- plugin/datasource/pom.xml
- plugin/encryption/pom.xml
- plugin/environment/pom.xml
- plugin/pom.xml
- plugin/trace/pom.xml
- pom.xml
- prometheus/pom.xml
- sys/pom.xml
- test/config-test/pom.xml
- test/core-test/pom.xml
- test/naming-test/pom.xml
- test/pom.xml
replace nacos website url to https.
replace nacos website url to https.
replace nacos website url to https.
> fix:replace nacos website url to https.

- common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/DefaultGrpcClientConfig.java
- common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClient.java
- common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClientConfig.java
- common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcConstants.java
- core/src/main/java/com/alibaba/nacos/core/remote/grpc/AddressTransportFilter.java
- core/src/main/java/com/alibaba/nacos/core/remote/grpc/BaseGrpcServer.java
- core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcBiStreamRequestAcceptor.java
- core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcClusterServer.java
- core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcConnectionInterceptor.java
- core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcRequestAcceptor.java
- core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcSdkServer.java
- core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcServerConstants.java
- core/src/test/java/com/alibaba/nacos/core/remote/grpc/GrpcBiStreamRequestAcceptorTest.java
- core/src/test/java/com/alibaba/nacos/core/remote/grpc/GrpcRequestAcceptorTest.java
- distribution/conf/application.properties
Provide more configuration items about grpc.
the typical defaults reference [grpc proposal](https://github.com/grpc/proposal/blob/master/A9-server-side-conn-mgt.md#abstract)
See about feature #9772 .
XXXX
> [ISSUE #9772] feature about grpc (2/2) -- Provide more configuration items about grpc.

- core/src/main/java/com/alibaba/nacos/core/cluster/remote/ClusterRpcClientProxy.java
> [ISSUE #9837]快照首次加载失败问题

- config/src/main/java/com/alibaba/nacos/config/server/controller/v2/ConfigControllerV2.java
- config/src/main/java/com/alibaba/nacos/config/server/controller/v2/HistoryControllerV2.java
- config/src/main/java/com/alibaba/nacos/config/server/model/form/ConfigForm.java
- config/src/test/java/com/alibaba/nacos/config/server/controller/v2/ConfigControllerV2Test.java
- config/src/test/java/com/alibaba/nacos/config/server/controller/v2/HistoryControllerV2Test.java
- test/config-test/src/test/java/com/alibaba/nacos/test/base/ConfigCleanUtils.java
- test/config-test/src/test/java/com/alibaba/nacos/test/config/ConfigAPI_V2_CITCase.java
Fix Issue #9783 
XXXXX
XX
XXXX
> [ISSUE #9783] 处理namespaceId=public 时 v2接口 无法创建与删除配置

- config/pom.xml
- config/src/main/java/com/alibaba/nacos/config/server/aspect/ConfigChangeAspect.java
- config/src/main/java/com/alibaba/nacos/config/server/configuration/ConfigChangeConfigs.java
- config/src/main/java/com/alibaba/nacos/config/server/utils/ConfigExecutor.java
- config/src/test/java/com/alibaba/nacos/config/server/configuration/ConfigChangeConfigsTest.java
- console/src/main/resources/application.properties
- plugin/config/pom.xml
- plugin/config/src/main/java/com/alibaba/nacos/plugin/config/ConfigChangePluginManager.java
- plugin/config/src/main/java/com/alibaba/nacos/plugin/config/constants/ConfigChangeConstants.java
- plugin/config/src/main/java/com/alibaba/nacos/plugin/config/constants/ConfigChangeExecuteTypes.java
- plugin/config/src/main/java/com/alibaba/nacos/plugin/config/constants/ConfigChangePointCutTypes.java
- plugin/config/src/main/java/com/alibaba/nacos/plugin/config/model/ConfigChangeRequest.java
- plugin/config/src/main/java/com/alibaba/nacos/plugin/config/model/ConfigChangeResponse.java
- plugin/config/src/main/java/com/alibaba/nacos/plugin/config/spi/ConfigChangePluginService.java
- plugin/config/src/test/java/com/alibaba/nacos/plugin/config/ConfigChangePluginManagerTests.java
- pom.xml
add config cange plugin
1.config module,add aspect and configs
2.add config-change-plugin module
3.add relative server configs to application.properties(server config)
1.add relative unit tests
> [ISSUE #8460]add config change plugin

- core/src/main/java/com/alibaba/nacos/core/cluster/MemberUtil.java
The comment is written incorrectly. This commit is used to correct the comment
返回值注释与源码实际的行为不符合，这个 commit 是为了改正注释
reason:
com.alibaba.nacos.core.cluster.MemberUtil#isBasicInfoChanged 该方法返回值注释上说的是：true if all content is same, otherwise false， 实际上，恰恰相反。
```java
// com.alibaba.nacos.core.cluster.ServerMemberManager#update 方法
boolean isPublishChangeEvent = MemberUtil.isBasicInfoChanged(newMember, member);
if (isPublishChangeEvent) {
// 可见使用： isPublishChangeEvent 为 true 才通知改变数据，代表 true 是发生了数据的变更，而源码中的注释却说的是，true 代表内容全部相同。（true if all content is same）
// member basic data changes and all listeners need to be notified
notifyMemberChange(member);
}
```
将 `true if all content is same, otherwise false`  改为 `true if one content is …
> Modify the return value comment of the isBasicInfoChanged method

- core/src/main/java/com/alibaba/nacos/core/auth/AuthFilter.java
- plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/NacosAuthManager.java
- plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/NacosAuthPluginService.java
- plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/controller/UserController.java
- plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/roles/NacosRoleServiceImpl.java
- plugin-default-impl/src/test/java/com/alibaba/nacos/plugin/auth/impl/controller/UserControllerTest.java
- plugin-default-impl/src/test/java/com/alibaba/nacos/plugin/auth/impl/roles/NacosRoleServiceImplTest.java
- plugin/auth/src/main/java/com/alibaba/nacos/plugin/auth/constant/Constants.java
remove user info from request session
keep user info in `IdentityContextHolder`(threadlocal variable).
ref issuse #9819
> [ISSUE #9819] fix bug-- can't update password.

- naming/src/main/java/com/alibaba/nacos/naming/web/NamingConfig.java
Fixes #9861 .
Fix auth check before distro filter.
> [ISSUE #9861]Fix auth check before distro filter.

- core/src/test/java/com/alibaba/nacos/core/remote/grpc/GrpcBiStreamRequestAcceptorTest.java
> Fix Unit test problem.

- naming/src/main/java/com/alibaba/nacos/naming/controllers/v2/CatalogControllerV2.java
- naming/src/main/java/com/alibaba/nacos/naming/core/CatalogService.java
- naming/src/main/java/com/alibaba/nacos/naming/core/CatalogServiceV2Impl.java
add catalog API to support list instances which is unenabled
Fixes #9703 .
XXXX
> [ISSUE #9703] add catalog API to support list instances which is unenabled

- client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc/NamingGrpcClientProxy.java
- client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc/redo/NamingGrpcRedoService.java
- client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc/redo/data/BatchInstanceRedoData.java
- client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc/redo/data/RedoData.java
- client/src/test/java/com/alibaba/nacos/client/naming/remote/gprc/NamingGrpcClientProxyTest.java
- client/src/test/java/com/alibaba/nacos/client/naming/remote/gprc/redo/NamingGrpcRedoServiceTest.java
- client/src/test/java/com/alibaba/nacos/client/naming/remote/gprc/redo/RedoScheduledTaskTest.java
- client/src/test/java/com/alibaba/nacos/client/naming/remote/gprc/redo/data/BatchInstanceRedoDataTest.java
- pom.xml
> [ISSUE #9816] Add expected final state for redo data.

- naming/src/main/java/com/alibaba/nacos/naming/remote/rpc/handler/BatchInstanceRequestHandler.java
> fix batchRegister authentication

- config/src/main/java/com/alibaba/nacos/config/server/configuration/NacosConfigConfiguration.java
- config/src/main/java/com/alibaba/nacos/config/server/filter/CircuitFilter.java
> [ISSUE #9900] Fix typo "Curcuit"

- api/src/main/java/com/alibaba/nacos/api/naming/pojo/Instance.java
- api/src/main/java/com/alibaba/nacos/api/naming/pojo/ServiceInfo.java
- api/src/main/java/com/alibaba/nacos/api/naming/pojo/healthcheck/impl/Http.java
- api/src/test/java/com/alibaba/nacos/api/naming/ability/ClientNamingAbilityTest.java
- api/src/test/java/com/alibaba/nacos/api/naming/ability/ServerNamingAbilityTest.java
- api/src/test/java/com/alibaba/nacos/api/naming/listener/NamingEventTest.java
- api/src/test/java/com/alibaba/nacos/api/naming/pojo/ClusterTest.java
- api/src/test/java/com/alibaba/nacos/api/naming/pojo/InstanceTest.java
- api/src/test/java/com/alibaba/nacos/api/naming/pojo/ListViewTest.java
- api/src/test/java/com/alibaba/nacos/api/naming/pojo/ServiceInfoTest.java
- api/src/test/java/com/alibaba/nacos/api/naming/pojo/ServiceTest.java
- api/src/test/java/com/alibaba/nacos/api/naming/pojo/builder/InstanceBuilderTest.java
- api/src/test/java/com/alibaba/nacos/api/naming/pojo/healthcheck/AbstractHealthCheckerTest.java
- api/src/test/java/com/alibaba/nacos/api/naming/pojo/healthcheck/HealthCheckTypeTest.java
- api/src/test/java/com/alibaba/nacos/api/naming/pojo/healthcheck/HealthCheckerFactoryTest.java
- api/src/test/java/com/alibaba/nacos/api/naming/pojo/healthcheck/impl/HttpTest.java
- api/src/test/java/com/alibaba/nacos/api/naming/pojo/healthcheck/impl/MysqlTest.java
- api/src/test/java/com/alibaba/nacos/api/naming/pojo/healthcheck/impl/TcpTest.java
- api/src/test/java/com/alibaba/nacos/api/naming/utils/NamingUtilsTest.java
- api/src/test/java/com/alibaba/nacos/api/utils/NetUtilsTest.java
- api/src/test/java/com/alibaba/nacos/api/utils/StringUtilsTest.java
- pom.xml
> Develop add unit test api

- client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc/redo/NamingGrpcRedoService.java
- client/src/test/java/com/alibaba/nacos/client/naming/remote/gprc/redo/NamingGrpcRedoServiceTest.java
> [ISSUE #9816] check expected final state before remove redo data.

- prometheus/src/main/java/com/alibaba/nacos/prometheus/conf/PrometheusSecurityConfiguration.java
- prometheus/src/main/java/com/alibaba/nacos/prometheus/filter/PrometheusAuthFilter.java
> [ISSUE #9710]prometheus-sd support basic auth.

- api/src/test/java/com/alibaba/nacos/api/naming/remote/request/BasedNamingRequestTest.java
- api/src/test/java/com/alibaba/nacos/api/naming/remote/request/BatchInstanceRequestTest.java
- api/src/test/java/com/alibaba/nacos/api/naming/remote/request/InstanceRequestTest.java
- api/src/test/java/com/alibaba/nacos/api/naming/remote/request/NotifySubscriberRequestTest.java
- api/src/test/java/com/alibaba/nacos/api/naming/remote/request/ServiceListRequestTest.java
- api/src/test/java/com/alibaba/nacos/api/naming/remote/request/ServiceQueryRequestTest.java
- api/src/test/java/com/alibaba/nacos/api/naming/remote/request/SubscribeServiceRequestTest.java
- naming/src/test/java/com/alibaba/nacos/naming/healthcheck/interceptor/HealthCheckTaskInterceptWrapperTest.java
- naming/src/test/java/com/alibaba/nacos/naming/remote/udp/UdpConnectorTest.java
> Add Unit test for api naming remote request.

- api/src/main/java/com/alibaba/nacos/api/model/v2/Result.java
- api/src/test/java/com/alibaba/nacos/api/model/v2/ResultTest.java
- api/src/test/java/com/alibaba/nacos/api/naming/remote/response/BatchInstanceResponseTest.java
- api/src/test/java/com/alibaba/nacos/api/naming/remote/response/InstanceResponseTest.java
- api/src/test/java/com/alibaba/nacos/api/naming/remote/response/QueryServiceResponseTest.java
- api/src/test/java/com/alibaba/nacos/api/naming/remote/response/ServiceListResponseTest.java
- api/src/test/java/com/alibaba/nacos/api/naming/remote/response/SubscribeServiceResponseTest.java
> Add Unit test for api module naming package.

- client/src/main/java/com/alibaba/nacos/client/config/impl/ConfigChangeHandler.java
code optimization
use List.addAll() instead of iterator
> [ISSUE #9922] code optimization for `ConfigChangeHandler`

- console/src/main/resources/application.properties
- distribution/conf/application.properties
- plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/LdapAuthConfig.java
- plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/NacosAuthConfig.java
- plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/NacosAuthManager.java
- plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/authenticate/AbstractAuthenticationManager.java
- plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/authenticate/DefaultAuthenticationManager.java
- plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/authenticate/LdapAuthenticationManager.java
- plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/controller/UserController.java
- plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/filter/JwtAuthenticationTokenFilter.java
- plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/jwt/NacosJwtParser.java
- plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/jwt/NacosSignatureAlgorithm.java
- plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/token/TokenManager.java
- plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/token/TokenManagerDelegate.java
- plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/token/impl/CachedJwtTokenManager.java
- plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/token/impl/JwtTokenManager.java
- plugin-default-impl/src/test/java/com/alibaba/nacos/plugin/auth/impl/JwtTokenManagerTest.java
- plugin-default-impl/src/test/java/com/alibaba/nacos/plugin/auth/impl/controller/UserControllerTest.java
- plugin-default-impl/src/test/java/com/alibaba/nacos/plugin/auth/impl/jwt/NacosJwtParserTest.java
- plugin-default-impl/src/test/java/com/alibaba/nacos/plugin/auth/impl/token/TokenManagerDelegateTest.java
- plugin-default-impl/src/test/java/com/alibaba/nacos/plugin/auth/impl/token/impl/CachedJwtTokenManagerTest.java
- plugin-default-impl/src/test/java/com/alibaba/nacos/plugin/auth/impl/token/impl/JwtTokenManagerTest.java
> [ISSUE #9906] cache token to improve performance

- client/src/main/java/com/alibaba/nacos/client/config/impl/ConfigChangeHandler.java
- common/src/main/java/com/alibaba/nacos/common/http/AbstractHttpClientFactory.java
Fix word spelling error 
fix word spelling error in com.alibaba.nacos.common.http.AbstractHttpClientFactory#ASYNC_IO_REACTOR_NAME
#9930 
> [ISSUE #9930] fix word spelling error in com.alibaba.nacos.common.http.AbstractHttpClientFactory#ASYNC_IO_REACTOR_NAME

- common/src/main/java/com/alibaba/nacos/common/utils/CollectionUtils.java
CollectionUtils下for循环中的字符串拼接改用StringBuilder
> Fixed some minor bugs in CollectionUtils.java

- core/src/main/java/com/alibaba/nacos/core/cluster/ServerMemberManager.java
> Fix cluster node state error

- console/src/main/resources/application.properties
- distribution/conf/application.properties
- plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/JwtTokenManager.java
For 2.2.0.1-release
Only add PR #9992.
XX
XXXX
> Remove the default token.secret.key (#9992)

- console-ui/src/pages/ConfigurationManagement/ConfigEditor/NewConfigEditor.js
功能优化
编辑配置时代码支持折叠， issue #9881 
XXXX
> 编辑配置时代码支持折叠

- config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/BaseDatabaseOperate.java
- config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedConfigInfoPersistServiceImpl.java
- config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedStoragePersistServiceImpl.java
- config/src/main/java/com/alibaba/nacos/config/server/service/sql/EmbeddedStorageContextUtils.java
- config/src/main/java/com/alibaba/nacos/config/server/service/sql/ModifyRequest.java
Resolve Issue #9943
XXXXX
XX
XXXX
> [ISSUE #9943] Resolve issue Config cas update not work

- common/src/main/java/com/alibaba/nacos/common/utils/AbstractAssert.java
- common/src/main/java/com/alibaba/nacos/common/utils/AbstractObjectUtils.java
- common/src/main/java/com/alibaba/nacos/common/utils/ArrayUtils.java
- common/src/main/java/com/alibaba/nacos/common/utils/ByteUtils.java
- common/src/main/java/com/alibaba/nacos/common/utils/ClassUtils.java
- common/src/main/java/com/alibaba/nacos/common/utils/CollectionUtils.java
- common/src/main/java/com/alibaba/nacos/common/utils/ConvertUtils.java
- common/src/main/java/com/alibaba/nacos/common/utils/DateFormatUtils.java
- common/src/main/java/com/alibaba/nacos/common/utils/ExceptionUtil.java
- common/src/main/java/com/alibaba/nacos/common/utils/HttpMethod.java
- common/src/main/java/com/alibaba/nacos/common/utils/InetAddressValidator.java
- common/src/main/java/com/alibaba/nacos/common/utils/InternetAddressUtil.java
- common/src/main/java/com/alibaba/nacos/common/utils/IoUtils.java
- common/src/main/java/com/alibaba/nacos/common/utils/JacksonUtils.java
- common/src/main/java/com/alibaba/nacos/common/utils/LoggerUtils.java
- common/src/main/java/com/alibaba/nacos/common/utils/MD5Utils.java
- common/src/main/java/com/alibaba/nacos/common/utils/MapUtil.java
- common/src/main/java/com/alibaba/nacos/common/utils/NamespaceUtil.java
- common/src/main/java/com/alibaba/nacos/common/utils/NumberUtils.java
- common/src/main/java/com/alibaba/nacos/common/utils/Preconditions.java
- common/src/main/java/com/alibaba/nacos/common/utils/PropertyUtils.java
- common/src/main/java/com/alibaba/nacos/common/utils/RandomUtils.java
- common/src/main/java/com/alibaba/nacos/common/utils/ReflectUtils.java
- common/src/main/java/com/alibaba/nacos/common/utils/ResourceUtils.java
- common/src/main/java/com/alibaba/nacos/common/utils/StringUtils.java
- common/src/main/java/com/alibaba/nacos/common/utils/ThreadUtils.java
- common/src/main/java/com/alibaba/nacos/common/utils/TypeUtils.java
- common/src/main/java/com/alibaba/nacos/common/utils/UuidUtils.java
- common/src/main/java/com/alibaba/nacos/common/utils/VersionUtils.java
Utility classes should not have public constructors.
To com/alibaba/nacos/common/utils package under the utility class add  private constructor.
#10018
> fix:Utility classes should not have public constructors

- config/src/main/java/com/alibaba/nacos/config/server/controller/CommunicationController.java
- config/src/main/java/com/alibaba/nacos/config/server/service/notify/AsyncNotifyService.java
> Remove http data change

- REPORTING-BUGS.md
> syntax error

- core/src/main/java/com/alibaba/nacos/core/controller/ServerLoaderController.java
ServerLoaderController Code optimization
Adjust  comments for ServerLoaderController
XXXX
-  Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
-  Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
-  Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
-  Write necessary unit-test to verify your logic …
> [ISSUE #10052] ServerLoaderController Code optimization

- config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalConfigInfoPersistServiceImpl.java
Fix #10044 -- only update existed config.
Catch DuplicateKeyException instead of DataIntegrityViolationException.
XXXX
> [ISSUE #10044]Fix NPE-- only update existed config.

- client/src/main/java/com/alibaba/nacos/client/auth/ram/identify/IdentifyConstants.java
- client/src/main/java/com/alibaba/nacos/client/auth/ram/identify/StsCredentialHolder.java
- client/src/main/java/com/alibaba/nacos/client/auth/ram/injector/ConfigResourceInjector.java
- client/src/main/java/com/alibaba/nacos/client/auth/ram/injector/NamingResourceInjector.java
- client/src/test/java/com/alibaba/nacos/client/auth/ram/identify/StsCredentialHolderTest.java
- client/src/test/java/com/alibaba/nacos/client/auth/ram/injector/ConfigResourceInjectorTest.java
- client/src/test/java/com/alibaba/nacos/client/auth/ram/injector/NamingResourceInjectorTest.java
- client/src/test/java/com/alibaba/nacos/client/env/NacosClientPropertiesTest.java
Fixes #10062 .
- Naming support aliyun STS auth.
> [ISSUE#10062] Naming support aliyun STS auth.

- client/src/main/resources/nacos-log4j2.xml
- client/src/main/resources/nacos-logback.xml
> [ISSUE#10084] Use async appender to print log for nacos-client.

- client/src/main/java/com/alibaba/nacos/client/config/http/ServerHttpAgent.java
- client/src/main/java/com/alibaba/nacos/client/identify/StsCredential.java
- client/src/main/java/com/alibaba/nacos/client/naming/net/NamingProxy.java
- client/src/main/resources/nacos-log4j2.xml
- client/src/main/resources/nacos-logback.xml
> Merge #10083 and #10085 into v1.x

- client/src/main/java/com/alibaba/nacos/client/config/impl/YmlChangeParser.java
- config/src/main/java/com/alibaba/nacos/config/server/utils/YamlParserUtil.java
- pom.xml
> Upgrade snakeYaml to 2.0

- auth/src/main/java/com/alibaba/nacos/auth/config/AuthConfigs.java
- auth/src/main/java/com/alibaba/nacos/auth/config/AuthErrorCode.java
- console/src/main/resources/application.properties
- distribution/conf/application.properties
- distribution/conf/application.properties.example
> Remove identity default value.

- pom.xml
> Upgrade to 2.2.1

- common/src/test/java/com/alibaba/nacos/common/remote/client/grpc/GrpcUtilsTest.java
- common/src/test/java/com/alibaba/nacos/common/utils/AbstractAssertTest.java
- common/src/test/java/com/alibaba/nacos/common/utils/AbstractObjectUtilsTest.java
add unit tests for AbstractObjectUtils.
add unit tests for AbstractAssert.
add unit tests for GrpcUtils.
XX
XXXX
> [ISSUE #10093] Add unit tests for common module.

- common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClient.java
- core/src/main/java/com/alibaba/nacos/core/remote/BaseRpcServer.java
- core/src/main/java/com/alibaba/nacos/core/remote/RpcServerSslContextRefresher.java
- core/src/main/java/com/alibaba/nacos/core/remote/RpcServerSslContextRefresherHolder.java
- core/src/main/java/com/alibaba/nacos/core/remote/RpcServerTlsConfig.java
- core/src/main/java/com/alibaba/nacos/core/remote/SslContextChangeAware.java
- core/src/main/java/com/alibaba/nacos/core/remote/grpc/BaseGrpcServer.java
- core/src/main/java/com/alibaba/nacos/core/remote/grpc/OptionalTlsProtocolNegotiator.java
- core/src/test/java/com/alibaba/nacos/core/remote/grpc/GrpcServerTest.java
> ssl context reload spi

- naming/src/test/java/com/alibaba/nacos/naming/BaseTest.java
- naming/src/test/java/com/alibaba/nacos/naming/controllers/v2/CatalogControllerV2Test.java
- naming/src/test/java/com/alibaba/nacos/naming/controllers/v2/HealthControllerV2Test.java
> Add some unit test for V2Controller

- core/src/main/java/com/alibaba/nacos/core/distributed/raft/NacosStateMachine.java
> [ISSUE #10128]fix bug

- api/src/main/java/com/alibaba/nacos/api/remote/DefaultRequestFuture.java
> [ISSUE #10155] print connectionId when timeout in DefaultRequestFuture.java

- config/src/main/resources/META-INF/nacos-db.sql
- distribution/conf/mysql-schema.sql
fix: typo: 秘钥->密钥
#10183 
Correction of misspelled words
Not needed
> [ISSUE #10183] Fix: typo: 秘钥->密钥

- README.md
#10189 
Add DaoCloud logo.
Just update readme file to add DaoCloud logo.
See the logo in home of repo.
> [ISSUE 10189] Add DaoCloud logo

- core/src/main/java/com/alibaba/nacos/core/monitor/NacosMeterRegistryCenter.java
- core/src/test/java/com/alibaba/nacos/core/monitor/NacosMeterRegistryCenterTest.java
Code optimization for NacosMeterRegistryCenter
XXXXX
XX
XXXX
> Code optimization for NacosMeterRegistryCenter

- api/src/main/java/com/alibaba/nacos/api/exception/api/NacosApiException.java
- api/src/main/java/com/alibaba/nacos/api/exception/runtime/NacosRuntimeException.java
- api/src/main/java/com/alibaba/nacos/api/selector/AbstractCmdbSelector.java
- api/src/main/java/com/alibaba/nacos/api/utils/NetUtils.java
- api/src/test/java/com/alibaba/nacos/api/cmdb/pojo/EntityEventTest.java
- api/src/test/java/com/alibaba/nacos/api/cmdb/pojo/EntityTest.java
- api/src/test/java/com/alibaba/nacos/api/cmdb/pojo/LabelTest.java
- api/src/test/java/com/alibaba/nacos/api/exception/NacosExceptionTest.java
- api/src/test/java/com/alibaba/nacos/api/exception/api/NacosApiExceptionTest.java
- api/src/test/java/com/alibaba/nacos/api/exception/runtime/NacosDeserializationExceptionTest.java
- api/src/test/java/com/alibaba/nacos/api/exception/runtime/NacosLoadExceptionTest.java
- api/src/test/java/com/alibaba/nacos/api/exception/runtime/NacosRuntimeExceptionTest.java
- api/src/test/java/com/alibaba/nacos/api/exception/runtime/NacosSerializationExceptionTest.java
- api/src/test/java/com/alibaba/nacos/api/selector/AbstractCmdbSelectorTest.java
- api/src/test/java/com/alibaba/nacos/api/selector/ExpressionSelectorTest.java
- api/src/test/java/com/alibaba/nacos/api/selector/NoneSelectorTest.java
- api/src/test/java/com/alibaba/nacos/api/selector/context/CmdbContextTest.java
- api/src/test/java/com/alibaba/nacos/api/utils/NetUtilsTest.java
- naming/src/test/java/com/alibaba/nacos/naming/cluster/transport/JacksonSerializerTest.java
> Add unit test for api module

- client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc/NamingGrpcClientProxy.java
- client/src/test/java/com/alibaba/nacos/client/naming/remote/gprc/NamingGrpcClientProxyTest.java
For #10210
init NamingGrpcClientProxy Configure appName label.
> [ISSUE #10210] init NamingGrpcClientProxy Configure appName label.

- console-ui/src/constants.js
- console-ui/src/globalLib.js
- console-ui/src/index.js
- console-ui/src/layouts/MainLayout.js
- console-ui/src/reducers/base.js
- console-ui/src/utils/request.js
login page and notice 
XX
XXXX
> [fix]🐛nacos login page && notice config

- naming/src/main/java/com/alibaba/nacos/naming/utils/ServiceUtil.java
detail：
https://github.com/alibaba/nacos/issues/10178
是这样重新提交一个plz merge吗（还是把close的open，第一次在开源项目上提交merge，抱歉）
> selector avalanche protection

- distribution/conf/mysql-schema.sql
> remove ambiguous comments

- api/src/main/java/com/alibaba/nacos/api/remote/DefaultRequestFuture.java
- api/src/main/java/com/alibaba/nacos/api/remote/response/ResponseCode.java
- api/src/test/java/com/alibaba/nacos/api/remote/AbstractPushCallBackTest.java
- api/src/test/java/com/alibaba/nacos/api/remote/AbstractRequestCallBackTest.java
- api/src/test/java/com/alibaba/nacos/api/remote/DefaultRequestFutureTest.java
- api/src/test/java/com/alibaba/nacos/api/remote/RpcScheduledExecutorTest.java
- api/src/test/java/com/alibaba/nacos/api/remote/response/EmptyContentResponseTest.java
- api/src/test/java/com/alibaba/nacos/api/remote/response/ServerCheckResponseTest.java
- api/src/test/java/com/alibaba/nacos/api/remote/response/ServerLoaderInfoResponseTest.java
> Develop add unit test for api remote and remote.response

- api/src/test/java/com/alibaba/nacos/api/remote/request/BasicRequestTest.java
- api/src/test/java/com/alibaba/nacos/api/remote/request/ConnectResetRequestTest.java
- api/src/test/java/com/alibaba/nacos/api/remote/request/ConnectionSetupRequestTest.java
- api/src/test/java/com/alibaba/nacos/api/remote/request/EmptyContentRequestTest.java
- api/src/test/java/com/alibaba/nacos/api/remote/request/PushAckRequestTest.java
- api/src/test/java/com/alibaba/nacos/api/remote/request/RequestMetaTest.java
- api/src/test/java/com/alibaba/nacos/api/remote/request/RequestTest.java
- api/src/test/java/com/alibaba/nacos/api/remote/request/ServerReloadRequestTest.java
> Add unit test for api module remote.request package.

- api/src/test/java/com/alibaba/nacos/api/config/ConfigChangeEventTest.java
- api/src/test/java/com/alibaba/nacos/api/config/ConfigChangeItemTest.java
- api/src/test/java/com/alibaba/nacos/api/config/ConfigTypeTest.java
- api/src/test/java/com/alibaba/nacos/api/config/ability/ServerConfigAbilityTest.java
- api/src/test/java/com/alibaba/nacos/api/config/listener/AbstractListenerTest.java
- api/src/test/java/com/alibaba/nacos/api/config/listener/AbstractSharedListenerTest.java
- api/src/test/java/com/alibaba/nacos/api/config/remote/request/ClientConfigMetricRequestTest.java
- api/src/test/java/com/alibaba/nacos/api/config/remote/request/ConfigBatchListenRequestTest.java
- api/src/test/java/com/alibaba/nacos/api/config/remote/request/ConfigPublishRequestTest.java
- api/src/test/java/com/alibaba/nacos/api/config/remote/request/ConfigQueryRequestTest.java
- api/src/test/java/com/alibaba/nacos/api/config/remote/response/ClientConfigMetricResponseTest.java
- api/src/test/java/com/alibaba/nacos/api/config/remote/response/ConfigChangeBatchListenResponseTest.java
- api/src/test/java/com/alibaba/nacos/api/config/remote/response/ConfigQueryResponseTest.java
> Supple unit tests for api module config package.

- plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/roles/NacosRoleServiceImpl.java
https://github.com/alibaba/nacos/issues/10347
Correction of default namespace authentication failure
XXXX
> :bug: default namespace resource matches

- README.md
Delete invalid log
Just update readme file to reomve 'Best partner in Dongguan' and 'Sinocare' logo.
XXXX
> Delete invalid log

- test/config-test/src/test/java/com/alibaba/nacos/test/config/NacosConfigServiceComTlsGrpcClient_CITCase.java
- test/config-test/src/test/java/com/alibaba/nacos/test/config/NacosConfigServiceNoComTlsGrpcClient_CITCase.java
- test/config-test/src/test/java/com/alibaba/nacos/test/config/NacosConfigV2MutualAuth_CITCase.java
- test/core-test/src/test/java/com/alibaba/nacos/test/client/ConfigIntegrationV1ServerNonCompatibility_CITCase.java
- test/core-test/src/test/java/com/alibaba/nacos/test/client/ConfigIntegrationV2MutualAuth_CITCase.java
- test/core-test/src/test/java/com/alibaba/nacos/test/client/ConfigIntegrationV3_CITCase.java
- test/core-test/src/test/java/com/alibaba/nacos/test/core/code/ControllerMethodsCache_ITCase.java
- test/naming-test/src/test/java/com/alibaba/nacos/test/naming/NamingTlsServiceAndMutualAuth_ITCase.java
- test/naming-test/src/test/java/com/alibaba/nacos/test/naming/NamingTlsServiceTls_ITCase.java
> Fix CI problem.

- naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperatorClientImpl.java
- naming/src/main/java/com/alibaba/nacos/naming/web/NamingConfig.java
Optimize code in `NamingConfig` .
Use generic type to declare filters in `NamingConfig` .
#10400 
> [ISSUE #10400] Use Generic Type in NamingConfig

- console-ui/src/pages/ServiceManagement/ServiceDetail/InstanceTable.js
For #6819
Add a PageSizeselector in service details page
XXXX
> [ISSUE #6819] Add a PageSizeselector in service details page

- naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/v2/DistroClientDataProcessor.java
Fix incorrect service ```revision``` in the log below:
```
com.alibaba.nacos.naming.consistency.ephemeral.distro.v2.DistroClientDataProcessor#processBatchInstanceDistroData
-> com.alibaba.nacos.naming.core.v2.client.AbstractClient#addServiceInstance
-> Loggers.SRV_LOG.info("Client change for service {}, {}", service, getClientId()); // revision will not correct here
```
The processing for distro protocol passed a incorrect ```Service``` object and it should pass the singleton
Fix incorrect service revision in log.
> Fix incorrect service revision in log.

- common/src/main/java/com/alibaba/nacos/common/utils/MapUtil.java
> [Optimization] Code optimization for MapUtil 

- naming/src/main/java/com/alibaba/nacos/naming/push/v2/task/PushExecuteTask.java
> [ISSUE#10464] Fix npe when concurrent operations for client

- config/src/test/java/com/alibaba/nacos/config/server/utils/ResponseUtilTest.java
> Remove dependence of package sun.security.action for ResponseUtilTest

- pom.xml
Fix third-party component bugs
XX
XXXX
> [ISSUE #10388] Fix third-party component bugs

- core/src/main/java/com/alibaba/nacos/core/remote/NacosRuntimeConnectionEjector.java
>  add out date connection active detection,expel it when client no response.

- client/src/main/java/com/alibaba/nacos/client/naming/net/NamingProxy.java
- distribution/bin/startup.sh
> [ISSUE#10217][ISSUE#10525] V1.x develop fix bug.

- pom.xml
> Upgrade to 1.4.6 and upgrade spring boot version

- config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/DistributedDatabaseOperateImpl.java
- consistency/src/main/java/com/alibaba/nacos/consistency/serialize/HessianSerializer.java
- consistency/src/main/java/com/alibaba/nacos/consistency/serialize/NacosHessianSerializerFactory.java
- consistency/src/test/java/com/alibaba/nacos/consistency/serialize/HessianSerializerTest.java
- naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/impl/BasePersistentServiceProcessor.java
- naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/InstanceMetadataProcessor.java
- naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/ServiceMetadataProcessor.java
- naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/impl/PersistentClientOperationServiceImpl.java
> HessianSerializer add whitelist.

- api/pom.xml
- client/pom.xml
- client/src/main/java/com/alibaba/nacos/client/naming/net/NamingProxy.java
- common/pom.xml
- consistency/src/main/java/com/alibaba/nacos/consistency/serialize/HessianSerializer.java
- consistency/src/main/java/com/alibaba/nacos/consistency/serialize/NacosHessianSerializerFactory.java
- distribution/bin/startup.sh
- pom.xml
> V1.x develop

- consistency/src/main/java/com/alibaba/nacos/consistency/serialize/HessianSerializer.java
- consistency/src/main/java/com/alibaba/nacos/consistency/serialize/NacosHessianSerializerFactory.java
- consistency/src/test/java/com/alibaba/nacos/consistency/SerializeFactoryTest.java
- consistency/src/test/java/com/alibaba/nacos/consistency/serialize/HessianSerializerTest.java
- core/src/main/java/com/alibaba/nacos/core/persistence/DistributedDatabaseOperateImpl.java
- naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/impl/BasePersistentServiceProcessor.java
- naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/InstanceMetadataProcessor.java
- naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/ServiceMetadataProcessor.java
- naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/impl/PersistentClientOperationServiceImpl.java
* HessianSerializer add whitelist.
* Handle exception in onApply and onRequest to save the stateMachine.
* Add new ut for HessianSerializer
XXXXX
XX
XXXX
> HessianSerializer add whitelist. (#10542)

- config/src/main/java/com/alibaba/nacos/config/server/configuration/NacosConfigConfiguration.java
Code Optimization by Generic Type
Use Generic Type in `NacosConfigConfiguration` when Register Filters.
> [ISSUE #10551]Use Generic Type in `NacosConfigConfiguration`

- naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/v2/DistroClientDataProcessor.java
- naming/src/test/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/v2/DistroClientDataProcessorTest.java
> For #10056, set Revision of client for distro sync.

- config/src/main/java/com/alibaba/nacos/config/server/controller/ClientMetricsController.java
- config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigOpsController.java
- config/src/main/java/com/alibaba/nacos/config/server/controller/ListenerController.java
- core/src/main/java/com/alibaba/nacos/core/controller/CoreOpsController.java
- core/src/main/java/com/alibaba/nacos/core/controller/NacosClusterController.java
修复某些接口没有经过鉴权
fix #10583 
XX
XXXX
> [ISSUE #10583]修复权限

- client/src/main/java/com/alibaba/nacos/client/auth/ram/identify/CredentialService.java
- client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingService.java
- client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc/NamingGrpcClientProxy.java
- client/src/test/java/com/alibaba/nacos/client/naming/NacosNamingServiceTest.java
- client/src/test/java/com/alibaba/nacos/client/naming/remote/gprc/NamingGrpcClientProxyTest.java
fix  naming memory leak
XX
XXXX
> fix  naming memory leak

- console/src/main/resources/application.properties
- distribution/conf/application.properties
- distribution/conf/application.properties.example
Add ldap legacy configuration for application.properties
XXXX
> Optimize nacos default application.properties configuration

- client/src/main/java/com/alibaba/nacos/client/naming/core/ServerListManager.java
fix nacos client get the wrong index of nacos server list  when use nacos-address endpoint
fix #10598 
fix an index value which did not initialized
XXX
> [ISSUE #10598] Fix nacos-client get the wrong index of the nacos server list when use nacos-address endpoint

- plugin/control/pom.xml
- plugin/control/src/main/java/com/alibaba/nacos/plugin/control/ruleactivator/LocalDiskRuleStorage.java
relation #10593
修改 nacos-contrl-plugin 的数据落地位置，之前的实现方式为：
```java
private static String defaultBaseDir() {
return LocalDiskRuleStorage.class.getResource("/").getPath();
}
```
该方法在jar的情况下 win 获取到的路径为 `/C:/Users/Darren/ldeaProjects/nacos/console/target/classes/`, linux 下获取到的路径为 `file:/home/darren/nacos/nacos/target/nacos-server.jar!/BOOT-INF/classes!/`，导致 linux 下运行时会在当前目录创建一个 `file:` 文件夹，现在修改为：
```java
private static String defaultBaseDir() {
return EnvUtil.getNacosHome();
}
```
这样子新建的文件夹则在 nacos 目录下的 data 文件夹中。
XX
XXXX
> [ISSUE #10593]修改 nacos-contrl-plugin 的数据落地位置

- persistence/src/main/java/com/alibaba/nacos/persistence/datasource/ExternalDataSourceProperties.java
- persistence/src/main/java/com/alibaba/nacos/persistence/datasource/ExternalDataSourceServiceImpl.java
- persistence/src/main/java/com/alibaba/nacos/persistence/utils/ConnectionCheckUtil.java
- persistence/src/test/java/com/alibaba/nacos/persistence/utils/ConnectionCheckUtilTest.java
当前版本的代码如果启动时失败，则会提示No DataSource Set失败，让一些使用的用户无法知道时数据库连接超时问题、网络问题、还是数据库用户密码不对问题等
#10521 
代码上增加了数据源连接对象构造完成后的一个连接主动检测的方法
可以在启动时，输入错误的连接信息，进行测试
* [x ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [x ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [x ] Write a pull request description that …
> [ISSUE #10521]代码支持数据源构造后进行连接检测，解决启动出错时提示No DataSourceSet现象

- distribution/conf/application.properties.example
Fix: application.properties.example is different from application.properties
ref: #10438 
XXXXX
XX
XXXX
> Fix: update application.properties.example

- console-ui/src/pages/ServiceManagement/SubscriberList/SubscriberList.js
> Subscribe list add service name

- client/src/main/java/com/alibaba/nacos/client/config/impl/Limiter.java
- core/src/main/java/com/alibaba/nacos/core/utils/StringPool.java
guava cache tt fix memory leak
Fixes #10471
XX
XXXX
> replace nacos cache with guava cache 

- .github/workflows/pr-ci.yml
- .github/workflows/pr-e2e-test.yml
- .github/workflows/push-ci.yaml
add nacos ci.
add pr-ci.yml, pr-e2e-test.yml, push-ci.yml to support nacos ci.
XXXX
> add nacos ci

- consistency/src/main/java/com/alibaba/nacos/consistency/serialize/HessianSerializer.java
> Fix npe when hessian deserialize

- naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/PersistentIpPortClientManager.java
- naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/impl/PersistentClientOperationServiceImpl.java
> Report deregister event if read snapshot file

- distribution/conf/mysql-schema.sql
Fix [#10571](https://github.com/alibaba/nacos/issues/10571)
为创建数据库表的 SQL 中的各个字段添加上 COMMENT 部分（优化体验）
XX
XXXX
> [ISSUE #10571]Add SQL COMMENT

- naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/impl/BasePersistentServiceProcessor.java
- naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/impl/NamingSnapshotOperation.java
- naming/src/test/java/com/alibaba/nacos/naming/consistency/persistent/impl/NamingSnapshotOperationTest.java
> Publish value change event to update SwitchDomain after load snapshot

- client/src/test/java/com/alibaba/nacos/client/naming/core/ServiceInfoUpdateServiceTest.java
- core/src/main/java/com/alibaba/nacos/core/remote/BaseRpcServer.java
- core/src/main/java/com/alibaba/nacos/core/remote/grpc/BaseGrpcServer.java
- core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcClusterServer.java
- core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcSdkServer.java
- core/src/main/java/com/alibaba/nacos/core/remote/grpc/negotiator/NacosGrpcProtocolNegotiator.java
- core/src/main/java/com/alibaba/nacos/core/remote/grpc/negotiator/ProtocolNegotiatorBuilder.java
- core/src/main/java/com/alibaba/nacos/core/remote/grpc/negotiator/ProtocolNegotiatorBuilderSingleton.java
- core/src/main/java/com/alibaba/nacos/core/remote/grpc/negotiator/tls/DefaultTlsContextBuilder.java
- core/src/main/java/com/alibaba/nacos/core/remote/grpc/negotiator/tls/DefaultTlsProtocolNegotiatorBuilder.java
- core/src/main/java/com/alibaba/nacos/core/remote/grpc/negotiator/tls/OptionalTlsProtocolNegotiator.java
- core/src/main/java/com/alibaba/nacos/core/remote/tls/RpcServerSslContextRefresher.java
- core/src/main/java/com/alibaba/nacos/core/remote/tls/RpcServerSslContextRefresherHolder.java
- core/src/main/java/com/alibaba/nacos/core/remote/tls/RpcServerTlsConfig.java
- core/src/main/java/com/alibaba/nacos/core/remote/tls/SslContextChangeAware.java
- core/src/main/resources/META-INF/services/com.alibaba.nacos.core.remote.grpc.negotiator.ProtocolNegotiatorBuilder
- core/src/test/java/com/alibaba/nacos/core/remote/grpc/GrpcServerTest.java
- core/src/test/java/com/alibaba/nacos/core/remote/grpc/negotiator/tls/DefaultTlsContextBuilderTest.java
- core/src/test/java/com/alibaba/nacos/core/remote/grpc/negotiator/tls/DefaultTlsProtocolNegotiatorBuilderTest.java
- test/config-test/src/test/java/com/alibaba/nacos/test/config/NacosConfigServiceComTlsGrpcClient_CITCase.java
- test/config-test/src/test/java/com/alibaba/nacos/test/config/NacosConfigServiceNoComTlsGrpcClient_CITCase.java
- test/config-test/src/test/java/com/alibaba/nacos/test/config/NacosConfigV2MutualAuth_CITCase.java
- test/core-test/src/test/java/com/alibaba/nacos/test/client/ConfigIntegrationV1ServerNonCompatibility_CITCase.java
- test/core-test/src/test/java/com/alibaba/nacos/test/client/ConfigIntegrationV2MutualAuth_CITCase.java
- test/core-test/src/test/java/com/alibaba/nacos/test/client/ConfigIntegrationV3_CITCase.java
- test/naming-test/src/test/java/com/alibaba/nacos/test/naming/NamingCompatibilityServiceTls_ITCase.java
- test/naming-test/src/test/java/com/alibaba/nacos/test/naming/NamingTlsServiceAndMutualAuth_ITCase.java
- test/naming-test/src/test/java/com/alibaba/nacos/test/naming/NamingTlsServiceTls_ITCase.java
> Refactor grpc tls

- plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/NacosAuthConfig.java
- plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/authenticate/AuthenticationManagerDelegator.java
Fix word spelling 
Fix word spelling in `AuthenticationManagerDelegator`
XXXX
> Fix word spelling in `AuthenticationManagerDelegator`

- core/src/main/java/com/alibaba/nacos/core/remote/ConnectionManager.java
- core/src/main/java/com/alibaba/nacos/core/remote/NacosRuntimeConnectionEjector.java
> Add the handle to overload connection

- console-ui/src/layouts/MainLayout.js
- console-ui/src/pages/AuthorityControl/PermissionsManagement/PermissionsManagement.js
- console-ui/src/pages/AuthorityControl/UserManagement/UserManagement.js
- console-ui/src/pages/ServiceManagement/ServiceDetail/EditInstanceDialog.js
- console-ui/src/pages/ServiceManagement/ServiceDetail/InstanceTable.js
- console-ui/src/pages/ServiceManagement/SubscriberList/SubscriberList.js
- fix a couple of invalid props to make the console much cleaner than before
> fix a couple of invalid props in the console

- naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/impl/PersistentClientOperationServiceImpl.java
bugfix for PersistentClientOperationServiceImpl log
> bugfix for PersistentClientOperationServiceImpl log

- common/src/main/java/com/alibaba/nacos/common/paramcheck/ParamCheckRules.java
fix the param check rule
fix the param check rule
XXXX
* [Y] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [Y] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [Y] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [Y] Write …
> For #10734,fix the param check rule

- client/src/main/resources/META-INF/native-image/com.alibaba.nacos/nacos-client/reflect-config.json
fix UnsupportedFeatureError Exception for  bug  #10859
reflect-config.json
Verifyed the change in local, it is worked
> Native image SpringGateway has Routing with the same name will throw UnsupportedFeatureError

- common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClient.java
> Fix exception code error.(#10925)

- console/src/main/java/com/alibaba/nacos/console/config/ConsoleConfig.java
- console/src/main/java/com/alibaba/nacos/console/config/ConsoleModuleStateBuilder.java
- console/src/main/java/com/alibaba/nacos/console/controller/ServerStateController.java
- console/src/main/resources/META-INF/services/com.alibaba.nacos.sys.module.ModuleStateBuilder
- distribution/conf/application.properties
- distribution/conf/console-guide.conf
- pom.xml
> [ISSUE#10971] Add state to disable console ui and add api to get guide information.

- core/src/main/java/com/alibaba/nacos/core/remote/RpcAckCallbackSynchronizer.java
fix (#11032  ) , adjust comment for RpcAckCallbackSynchronizer.
> fix(#11032): adjust comment for RpcAckCallbackSynchronizer.

- plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/jwt/NacosJwtParser.java
- plugin-default-impl/src/main/java/com/alibaba/nacos/plugin/auth/impl/utils/Base64Decode.java
- plugin-default-impl/src/test/java/com/alibaba/nacos/plugin/auth/impl/utils/Base64DecodeTest.java
to forward compatible old version secretKey, see #10930
forward compatible old version secretKey
XXXX
> [ISSUE #10930] forward compatible old version secretKey

- console-ui/src/constants.js
- console-ui/src/index.js
- console-ui/src/layouts/MainLayout.js
- console-ui/src/pages/Login/Login.jsx
- console-ui/src/reducers/base.js
> feat：console&login demand

- core/src/main/java/com/alibaba/nacos/core/namespace/repository/EmbeddedNamespacePersistServiceImpl.java
- core/src/main/java/com/alibaba/nacos/core/namespace/repository/ExternalNamespacePersistServiceImpl.java
- core/src/main/java/com/alibaba/nacos/core/namespace/repository/NamespacePersistService.java
[1/4] PR-1、Core模块，调整IDE提示的拼写、冗余拆箱、单个String构造List方法。
> [#11035] (PR-1/4) core module, trim

- naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/AbstractClient.java
- naming/src/main/java/com/alibaba/nacos/naming/monitor/MetricsMonitor.java
- naming/src/test/java/com/alibaba/nacos/naming/monitor/MetricsMonitorTest.java
Fixes #11056.
- Fix Batch register count size wrong, when batch register sereval time.
XXXX
> [ISSUE#11056] Fix Batch register count size wrong, when batch register sereval time.

- config/src/main/java/com/alibaba/nacos/config/server/service/ConfigCacheService.java
- config/src/main/java/com/alibaba/nacos/config/server/service/repository/ConfigRowMapperInjector.java
- console/src/main/resources/application.properties
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/derby/ConfigInfoMapperByDerby.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/derby/HistoryConfigInfoMapperByDerby.java
Fixes #10908
1. derby syntax error
2. IllegalArgumentException:RowMapper is required
3. bean injection in Class of ConfigCacheService
XX
XXXX
> [ISSUE#10908] Fix Bean injection in class of ConfigCacheService

- config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedConfigInfoBetaPersistServiceImpl.java
- config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedConfigInfoPersistServiceImpl.java
- config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedConfigInfoTagPersistServiceImpl.java
- config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedStoragePersistServiceImpl.java
- config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalConfigInfoBetaPersistServiceImpl.java
- config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalConfigInfoTagPersistServiceImpl.java
- config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java
fix(#10940): The SQL statement should query the 'gmt_modified' field.
fix(#10940): The SQL statement should query the 'gmt_modified' field.
fix(#10940): The SQL statement should query the 'gmt_modified' field.
> fix(#10940): The SQL statement should query the 'gmt_modified' field.

- config/src/main/java/com/alibaba/nacos/config/server/service/LongPollingService.java
#10945 : Remove invalid code in the LongPollingService class.
fix(#10945 ): Remove invalid code in the LongPollingService class.
> fix(#10945): Remove invalid code in the LongPollingService class.

- config/src/main/java/com/alibaba/nacos/config/server/service/ConfigCacheService.java
- config/src/main/java/com/alibaba/nacos/config/server/service/repository/ConfigRowMapperInjector.java
- plugin/datasource/src/test/java/com/alibaba/nacos/plugin/datasource/impl/derby/ConfigInfoMapperByDerbyTest.java
- plugin/datasource/src/test/java/com/alibaba/nacos/plugin/datasource/impl/derby/HistoryConfigInfoMapperByDerbyTest.java
> fixup derby test case

- config/src/main/java/com/alibaba/nacos/config/server/filter/ConfigParamCheckFilter.java
- console/src/main/java/com/alibaba/nacos/console/filter/ConsoleParamCheckFilter.java
- core/src/main/java/com/alibaba/nacos/core/remote/grpc/RemoteParamCheckFilter.java
- core/src/test/java/com/alibaba/nacos/core/remote/grpc/RemoteParamCheckFilterTest.java
- naming/src/main/java/com/alibaba/nacos/naming/web/NamingParamCheckFilter.java
Complete parameter validation log recording and modify the returned status code to 400
Complete parameter validation log recording and modify the returned status code to 400
XXXX
* [Y] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [Y] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [Y] …
> [ISSUE #10734]Complete parameter validation log recording and modify the returned status code to 400

- config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigServletInner.java
> (refactor)Remove some unnecessary code

- core/src/main/java/com/alibaba/nacos/core/cluster/remote/ClusterRpcClientProxy.java
> (bugfix)  check null when obtaining the RpcClient.

- common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClientTlsConfig.java
Fix RPC_CLIENT_TLS_PROTOCOLS setting error.
For #11059 .
XX
XXXX
> Fix RPC_CLIENT_TLS_PROTOCOLS setting error.

- common/src/main/java/com/alibaba/nacos/common/notify/listener/SmartSubscriber.java
- common/src/main/java/com/alibaba/nacos/common/trace/event/naming/DeregisterInstanceTraceEvent.java
- common/src/main/java/com/alibaba/nacos/common/trace/event/naming/DeregisterServiceTraceEvent.java
- common/src/main/java/com/alibaba/nacos/common/trace/event/naming/HealthStateChangeTraceEvent.java
- common/src/main/java/com/alibaba/nacos/common/trace/event/naming/NamingTraceEvent.java
- common/src/main/java/com/alibaba/nacos/common/trace/event/naming/PushServiceTraceEvent.java
- common/src/main/java/com/alibaba/nacos/common/trace/event/naming/RegisterInstanceTraceEvent.java
- common/src/main/java/com/alibaba/nacos/common/trace/event/naming/RegisterServiceTraceEvent.java
- common/src/main/java/com/alibaba/nacos/common/trace/event/naming/SubscribeServiceTraceEvent.java
- common/src/main/java/com/alibaba/nacos/common/trace/event/naming/UnsubscribeServiceTraceEvent.java
- common/src/main/java/com/alibaba/nacos/common/trace/event/naming/UpdateInstanceTraceEvent.java
- common/src/main/java/com/alibaba/nacos/common/trace/event/naming/UpdateServiceTraceEvent.java
- core/src/test/java/com/alibaba/nacos/core/trace/NacosCombinedTraceSubscriberTest.java
Enhance unit tests related to trace events.
For #11072.
XX
XXXX
> [ISSUE #11072]Enhance unit tests related to trace events.

- api/src/main/java/com/alibaba/nacos/api/annotation/NacosProperties.java
- api/src/main/java/com/alibaba/nacos/api/exception/NacosException.java
- api/src/main/java/com/alibaba/nacos/api/grpc/auto/Metadata.java
- api/src/main/java/com/alibaba/nacos/api/grpc/auto/RequestGrpc.java
- api/src/main/java/com/alibaba/nacos/api/naming/NamingResponseCode.java
- api/src/main/java/com/alibaba/nacos/api/selector/Selector.java
- client/src/main/java/com/alibaba/nacos/client/config/NacosConfigService.java
1、移除未使用到的头文件导入语句
2、一个多出来的分号
3、map.getOrDefault(key, defaultValue)能够比三元表达式形式少一次元素搜索
> [ISSUE#11035](PR-3/4) api module, remove unused import.

- client/src/main/java/com/alibaba/nacos/client/config/NacosConfigService.java
- client/src/main/java/com/alibaba/nacos/client/config/impl/ServerListManager.java
- client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingService.java
- client/src/main/java/com/alibaba/nacos/client/utils/PreInitUtils.java
> Enhance config service address mode start judgement.

- api/src/main/java/com/alibaba/nacos/api/remote/RemoteConstants.java
- client/src/main/java/com/alibaba/nacos/client/monitor/MetricsMonitor.java
- client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc/NamingGrpcClientProxy.java
- client/src/test/java/com/alibaba/nacos/client/naming/remote/gprc/NamingGrpcClientProxyTest.java
…egistration.
Add registration metrics.
About #10117 .
XX
XXXX
> [ISSUE #10117]Add registration metrics.

- example/README.md
- example/src/main/java/com/alibaba/nacos/example/App.java
- example/src/main/java/com/alibaba/nacos/example/ConfigExample.java
- example/src/main/java/com/alibaba/nacos/example/NamingExample.java
Enhancements for example Module, Introduce README.md and Optimize Code.
#11094 
XX
XXXX
> [ISSUE #11094] Enhancements for example Module, Introduce README.md and Optimize Code.

- plugin-default-impl/nacos-default-control-plugin/src/main/java/com/alibaba/nacos/plugin/control/impl/NacosTpsControlManager.java
- plugin/control/src/main/java/com/alibaba/nacos/plugin/control/tps/DefaultTpsControlManager.java
- plugin/control/src/main/java/com/alibaba/nacos/plugin/control/tps/TpsControlManager.java
> use DefaultNacosTpsBarrierCreator as Tps manager default impl.

- client/src/main/java/com/alibaba/nacos/client/naming/core/ServiceInfoUpdateService.java
> Fix frequent do query service when hit protect empty.

- pom.xml
> Upgrade grpc version to 1.57.2

- api/src/main/java/com/alibaba/nacos/api/ability/constant/AbilityKey.java
- api/src/test/java/com/alibaba/nacos/api/ability/register/impl/ClusterClientAbilitiesTest.java
- api/src/test/java/com/alibaba/nacos/api/ability/register/impl/SdkClientAbilitiesTest.java
- api/src/test/java/com/alibaba/nacos/api/ability/register/impl/ServerAbilitiesTest.java
- api/src/test/java/com/alibaba/nacos/api/config/remote/request/cluster/ConfigChangeClusterSyncRequestTest.java
- api/src/test/java/com/alibaba/nacos/api/remote/request/ConnectResetRequestTest.java
- api/src/test/java/com/alibaba/nacos/api/remote/request/RequestMetaTest.java
- api/src/test/java/com/alibaba/nacos/api/remote/request/SetupAckRequestTest.java
- api/src/test/java/com/alibaba/nacos/api/remote/response/EmptyContentResponseTest.java
- api/src/test/java/com/alibaba/nacos/api/remote/response/ServerCheckResponseTest.java
- api/src/test/java/com/alibaba/nacos/api/utils/AbilityKeyTest.java
> Fill UT for api module.

- distribution/bin/shutdown.sh
- distribution/bin/startup.sh
Refactor: 
https://github.com/alibaba/nacos/issues/11212
- in shutdown.sh: Remove hacky grep and use pgrep for readability
- in startup.sh: Remove full-width alphabet
```
656497
656497
```
> ISSUE #11212

- client/src/test/java/com/alibaba/nacos/client/naming/NacosNamingServiceTest.java
This PR is use to add unit test for fuzzy watch.
Related issue: #10380 
**Please don't merge this PR at this time, subsequent unit test commits will use this PR for the commit**
Add unit test for fuzzy watch
> [ISSUE #10380]Add fuzzy watch unit test

- config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigController.java
- config/src/main/java/com/alibaba/nacos/config/server/controller/v2/ConfigControllerV2.java
- config/src/main/java/com/alibaba/nacos/config/server/model/ConfigRequestInfo.java
- config/src/main/java/com/alibaba/nacos/config/server/service/ConfigOperationService.java
- config/src/test/java/com/alibaba/nacos/config/server/service/ConfigOperationServiceTest.java
feat(#11115 ) http support cas publish.
> feat(11115): http support cas publish.

- config/src/main/java/com/alibaba/nacos/config/server/service/ConfigCacheService.java
feat(#11236): Remove invalid assertion in com.alibaba.nacos.config.server.service.ConfigCacheService#dumpChange.
> feat(#11236): Remove invalid assertion in com.alibaba.nacos.config.server.service.ConfigCacheService#dumpChange.

- naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/impl/EphemeralClientOperationServiceImpl.java
- naming/src/test/java/com/alibaba/nacos/naming/core/v2/service/impl/EphemeralClientOperationServiceImplTest.java
> [ISSUE#11192] batchRegisterInstance add recalculateRevision

- common/src/main/java/com/alibaba/nacos/common/remote/client/Connection.java
- common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClient.java
- core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcBiStreamRequestAcceptor.java
- core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcConnection.java
- test/core-test/src/test/java/com/alibaba/nacos/test/ability/AbilityDiscovery.java
> Fix npe when setup ack response in GrpcClient

- common/src/main/java/com/alibaba/nacos/common/executor/ThreadPoolManager.java
- common/src/test/java/com/alibaba/nacos/common/executor/ThreadPoolManagerTest.java
> Optimize ThreadPoolManager

- pom.xml
> Upgrade to 2.3.0-BETA.

- plugin/config/pom.xml
- plugin/control/pom.xml
> Add description for new plugin.

- api/src/main/java/com/alibaba/nacos/api/common/Constants.java
- api/src/main/java/com/alibaba/nacos/api/naming/NamingService.java
- api/src/main/java/com/alibaba/nacos/api/naming/utils/NamingUtils.java
- client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingService.java
- client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc/NamingGrpcClientProxy.java
- client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc/redo/RedoScheduledTask.java
- example/src/main/java/com/alibaba/nacos/example/FuzzyWatchExample.java
For https://github.com/alibaba/nacos/issues/10380 , Support for fuzzy watch capability for Nacos registration center.
change fuzzy watch service name pattern construct rule
add namespaceId in fuzzy watch redo log
调整了Fuzzy Watch的pattern构建规则，在NamingUtils对应地调整匹配的方法
在fuzzy Watch redo的日志处加上了NameSpace ID
> [ISSUE #10380] Change Fuzzy Watch Pattern Rule

- .github/workflows/pr-ci.yml
- .github/workflows/pr-e2e-test.yml
- .github/workflows/push-ci.yaml
Fix the error that caused the pipeline to fail due to the incorrect tar package name.
XX
XXXX
> fix CI: rename tar name

- api/src/main/java/com/alibaba/nacos/api/naming/pojo/ServiceInfo.java
> Simplify the validate method for serviceinfo

- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/MapperManager.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/proxy/MapperProxy.java
> Optimize MapperManager

- core/src/main/java/com/alibaba/nacos/core/paramcheck/ParamCheckerFilter.java
> [ISSUE #11343]Fix NPE

- api/src/test/java/com/alibaba/nacos/api/config/ability/ServerRemoteAbilityTest.java
- api/src/test/java/com/alibaba/nacos/api/config/remote/request/BasedConfigRequestTest.java
- api/src/test/java/com/alibaba/nacos/api/config/remote/request/ConfigBatchListenRequestTest.java
- api/src/test/java/com/alibaba/nacos/api/config/remote/response/ConfigChangeBatchListenResponseTest.java
- api/src/test/java/com/alibaba/nacos/api/remote/ability/ServerRemoteAbilityTest.java
Related to issue #11369
To address the issue #11369 , which is caused due to potential variations in JSON ordering. 
```
com.alibaba.nacos.api.config.ability.ServerRemoteAbilityTest.testSerialize
com.alibaba.nacos.api.config.remote.response.ConfigChangeBatchListenResponseTest.testSerializeSuccessResponse
com.alibaba.nacos.api.config.remote.request.ConfigBatchListenRequestTest.testSerialize
com.alibaba.nacos.api.remote.ability.ServerRemoteAbilityTest.testSerialize
```
This was found by using the [NonDex](https://github.com/TestingResearchIllinois/NonDex) tool.
**MODULE:** api
1. Used *MapperFeature.SORT_PROPERTIES_ALPHABETICALLY* to enable alphabetical ordering of elements of 'json' for it to be deterministic all the time.
2. Sorted the expected value in assert statements.
Encountered …
> [ISSUE #11369] Fixed ObjectMapper ordering problem in 4 tests

- style/codeStyle.md
修复错误单词
#11403 
修改错误拼写
修改错误拼写
查看页面
[codeStyle.md](https://github.com/alibaba/nacos/blob/develop/style/codeStyle.md)
> 修复错误拼写,Update codeStyle.md

- config/src/main/java/com/alibaba/nacos/config/server/service/dump/processor/DumpAllProcessor.java
Optimize DumpAllProcessor code.
#11217
XX
XXXX
> [ISSUE #11217]Optimize DumpAllProcessor code.

- api/src/main/java/com/alibaba/nacos/api/naming/pojo/ServiceInfo.java
For #11414 , Optimize ServiceInfo.validate() to reduce memory usage.
Remove the unnecessary, size unstable list that collect valid hosts. Use a boolean variable to mark whether valid host exists.
> [ISSUE #11414]Optimize ServiceInfo.validate() to reduce memory usage

- client/src/main/java/com/alibaba/nacos/client/config/impl/CacheData.java
参考 issue：https://github.com/alibaba/nacos/issues/3497
最新的1.4.6中依旧未解决 `tx=null` 问题，所以添加配置文件监听器异常信息打印到 1.x 版本中
添加配置文件监听器异常信息打印
原先的日志打印：
```text
2023-11-24 11:21:15.256 ERROR 13472 --- [48-fun-powercheng-dev] c.a.nacos.client.config.impl.CacheData   : [fixed-10.12.1.74_8848-fun-powercheng-dev] [notify-error] dataId=test-listener, group=FRAMEWORK_GROUP, md5=098f6bcd4621d373cade4e832627b4f6, listener=fun.powercheng.collection.microservice.DemoApplication$1@34b69a14 tx=null
```
修改后的日志打印（不为null且有堆栈信息）：
```text
2023-11-24 11:24:02.507 ERROR 13472 --- [48-fun-powercheng-dev] c.a.nacos.client.config.impl.CacheData   : [fixed-10.12.1.74_8848-fun-powercheng-dev] [notify-error] dataId=test-listener, group=FRAMEWORK_GROUP, …
```
> fix: 修复配置文件监听器异常信息打印会出现null的问题

- client/src/main/java/com/alibaba/nacos/client/auth/ram/injector/LockResourceInjector.java
- lock/src/main/java/com/alibaba/nacos/lock/LockManager.java
- lock/src/main/java/com/alibaba/nacos/lock/NacosLockManager.java
- lock/src/main/java/com/alibaba/nacos/lock/core/reentrant/AtomicLockService.java
- lock/src/main/java/com/alibaba/nacos/lock/core/reentrant/mutex/MutexAtomicLock.java
- lock/src/main/java/com/alibaba/nacos/lock/exception/NacosLockException.java
- lock/src/main/java/com/alibaba/nacos/lock/remote/rpc/handler/LockRequestHandler.java
- lock/src/main/java/com/alibaba/nacos/lock/service/impl/LockOperationServiceImpl.java
- lock/src/test/java/com/alibaba/nacos/lock/LockManagerTest.java
- lock/src/test/java/com/alibaba/nacos/lock/core/reentrant/mutex/ClientAtomicLock.java
> [GLCC #10378] Improve log and memory lack.

- common/src/main/java/com/alibaba/nacos/common/remote/ConnectionType.java
- common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClient.java
- common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClientFactory.java
- common/src/main/java/com/alibaba/nacos/common/remote/client/RpcConstants.java
- common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/DefaultGrpcClientConfig.java
- common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClient.java
- common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcConnection.java
- common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcConstants.java
- common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcUtils.java
- common/src/main/java/com/alibaba/nacos/common/remote/exception/ConnectionAlreadyClosedException.java
- common/src/test/java/com/alibaba/nacos/common/remote/ConnectionTypeTest.java
- common/src/test/java/com/alibaba/nacos/common/remote/TlsConfigTest.java
- common/src/test/java/com/alibaba/nacos/common/remote/client/ConnectionTest.java
- common/src/test/java/com/alibaba/nacos/common/remote/client/RpcClientTest.java
- common/src/test/java/com/alibaba/nacos/common/remote/client/RpcClientTlsConfigTest.java
- common/src/test/java/com/alibaba/nacos/common/remote/client/grpc/DefaultGrpcClientConfigTest.java
- common/src/test/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClientTest.java
- common/src/test/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClientTlsTest.java
- common/src/test/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClusterClientTest.java
- common/src/test/java/com/alibaba/nacos/common/remote/client/grpc/GrpcConnectionTest.java
- common/src/test/java/com/alibaba/nacos/common/remote/client/grpc/GrpcSdkClientTest.java
- common/src/test/java/com/alibaba/nacos/common/remote/client/grpc/GrpcUtilsTest.java
- common/src/test/java/com/alibaba/nacos/common/remote/exception/RemoteExceptionTest.java
> Develop fill ut common

- api/src/main/java/com/alibaba/nacos/api/naming/selector/NamingContext.java
- api/src/main/java/com/alibaba/nacos/api/naming/selector/NamingResult.java
- api/src/main/java/com/alibaba/nacos/api/naming/selector/NamingSelector.java
- api/src/main/java/com/alibaba/nacos/api/selector/client/SelectResult.java
- api/src/main/java/com/alibaba/nacos/api/selector/client/Selector.java
- client/src/main/java/com/alibaba/nacos/client/naming/event/InstancesDiff.java
- client/src/main/java/com/alibaba/nacos/client/naming/listener/AbstractNamingChangeListener.java
- client/src/main/java/com/alibaba/nacos/client/naming/listener/NamingChangeEvent.java
- client/src/main/java/com/alibaba/nacos/client/naming/selector/DefaultNamingSelector.java
- client/src/main/java/com/alibaba/nacos/client/naming/selector/NamingListenerInvoker.java
- client/src/main/java/com/alibaba/nacos/client/selector/AbstractSelectorWrapper.java
- client/src/main/java/com/alibaba/nacos/client/selector/ListenerInvoker.java
- client/src/test/java/com/alibaba/nacos/client/naming/event/InstancesChangeEventTest.java
- client/src/test/java/com/alibaba/nacos/client/naming/event/InstancesChangeNotifierTest.java
- client/src/test/java/com/alibaba/nacos/client/naming/event/InstancesDiffTest.java
- client/src/test/java/com/alibaba/nacos/client/naming/listener/NamingChangeEventTest.java
- client/src/test/java/com/alibaba/nacos/client/naming/selector/DefaultNamingSelectorTest.java
- client/src/test/java/com/alibaba/nacos/client/naming/selector/NamingListenerInvokerTest.java
- client/src/test/java/com/alibaba/nacos/client/selector/SelectorManagerTest.java
For [#10374](https://github.com/alibaba/nacos/issues/10374), format code using Nacos style.
> [ISSUE #10374] Format code using Nacos style

- config/src/main/java/com/alibaba/nacos/config/server/paramcheck/ConfigListenerHttpParamExtractor.java
长轮询参数校验逻辑，修复不存在的空命名空间配置校验失败bug
服务端参数校验时的逻辑是单个配置的字段数不少于3并且不大于4
客户端拼接长轮询参数时，格式是 dataId+group+md5+namespace，但是空命名空间下，namespace是空值，如果配置不存在，md5也为空，这种情况下单个配置的字段数通过split之后的数量是2，导致参数校验失败，长轮询接口报400
XXXX
> 长轮询参数校验逻辑，修复不存在的空命名空间配置校验失败bug

- config/src/main/java/com/alibaba/nacos/config/server/service/repository/ConfigRowMapperInjector.java
- register CONFIG_INFO_STATE_WRAPPER_ROW_MAPPER to RowMapperManager
Close #11459
fix an error when the user adds a new config as the nacos server run in cluster model and use dembedded storage
register CONFIG_INFO_STATE_WRAPPER_ROW_MAPPER to RowMapperManager
XXXX
> [ISSUES #11459] fix CONFIG_INFO_STATE_WRAPPER_ROW_MAPPER missing

- core/src/main/java/com/alibaba/nacos/core/remote/ConnectionManager.java
- core/src/main/java/com/alibaba/nacos/core/remote/NacosRuntimeConnectionEjector.java
> fix: connection count of current node is not accurate

- core/src/main/java/com/alibaba/nacos/core/monitor/MetricsMonitor.java
- core/src/main/java/com/alibaba/nacos/core/remote/ConnectionManager.java
- core/src/test/java/com/alibaba/nacos/core/monitor/MetricsMonitorTest.java
#10846 
XXXXX
```
nacos_monitor{module="config",name="longConnection",} 12.0
nacos_monitor{module="naming",name="longConnection",} 7.0
nacos_monitor{module="unknown",name="longConnection",} 0.0
```
XX
XXXX
> Support metric for module connection

- pom.xml
> Upgrade to 2.3.1-SNAPSHOT

- prometheus/src/main/java/com/alibaba/nacos/prometheus/filter/PrometheusAuthFilter.java
Fix issue #10752
XXXXX
XX
XXXX
> [ISSUE #10752] Fix Prometheus sd api security is not compatiable with nacos original security configs

- plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/persistence/handler/PageHandlerAdapterFactory.java
Fix issue https://github.com/alibaba/nacos/issues/11489
XX
XXXX
> [ISSUE #11489] Fix PageHandlerAdapterFactory initHandlerAdapters error

- plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/token/impl/JwtTokenManager.java
- plugin-default-impl/nacos-default-auth-plugin/src/test/java/com/alibaba/nacos/plugin/auth/impl/token/impl/JwtTokenManagerTest.java
> [ISSUE#11494] Fix frequently request login api when using 2.X client with username.

- client/src/main/java/com/alibaba/nacos/client/auth/ram/identify/CredentialService.java
- client/src/main/java/com/alibaba/nacos/client/auth/ram/identify/CredentialWatcher.java
- client/src/main/java/com/alibaba/nacos/client/auth/ram/identify/Credentials.java
- client/src/main/java/com/alibaba/nacos/client/auth/ram/utils/SignUtil.java
- client/src/main/java/com/alibaba/nacos/client/env/SearchableProperties.java
- client/src/main/java/com/alibaba/nacos/client/env/SourceType.java
- client/src/test/java/com/alibaba/nacos/client/ability/ClientAbilityControlManagerTest.java
- client/src/test/java/com/alibaba/nacos/client/auth/impl/NacosClientAuthServiceImplTest.java
- client/src/test/java/com/alibaba/nacos/client/auth/ram/identify/CredentialServiceTest.java
- client/src/test/java/com/alibaba/nacos/client/auth/ram/identify/CredentialWatcherTest.java
- client/src/test/java/com/alibaba/nacos/client/auth/ram/identify/StsConfigTest.java
- client/src/test/java/com/alibaba/nacos/client/auth/ram/identify/StsCredentialHolderTest.java
- client/src/test/java/com/alibaba/nacos/client/auth/ram/injector/AbstractResourceInjectorTest.java
- client/src/test/java/com/alibaba/nacos/client/auth/ram/utils/SignUtilTest.java
- client/src/test/java/com/alibaba/nacos/client/auth/ram/utils/SpasAdapterTest.java
- client/src/test/java/com/alibaba/nacos/client/env/SearchablePropertiesTest.java
- client/src/test/java/com/alibaba/nacos/client/env/SystemEnvPropertySourceTest.java
- client/src/test/java/com/alibaba/nacos/client/env/convert/CompositeConverterTest.java
- client/src/test/java/com/alibaba/nacos/client/naming/remote/gprc/NamingGrpcClientProxyTest.java
- client/src/test/resources/spas.identity
- client/src/test/resources/spas_docker.identity
- client/src/test/resources/spas_invalid.identity
- client/src/test/resources/spas_modified.identity
> Develop client ut

- config/src/test/java/com/alibaba/nacos/config/server/service/dump/processor/DumpAllProcessorTest.java
> Add unit tests for package com.alibaba.nacos.config.server.service.dump

- api/src/main/java/com/alibaba/nacos/api/naming/utils/NamingUtils.java
- api/src/test/java/com/alibaba/nacos/api/naming/utils/NamingUtilsTest.java
- client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingService.java
fix https://github.com/alibaba/nacos/issues/11493
XX
XXXX
> [ISSUE #11493] service name group check fix

- persistence/src/main/java/com/alibaba/nacos/persistence/datasource/ExternalDataSourceServiceImpl.java
- persistence/src/test/java/com/alibaba/nacos/persistence/datasource/ExternalDataSourceServiceImplTest.java
fix(#11498 ): fix CheckDbHealthTask.
fix(#11498 ): fix CheckDbHealthTask.
fix(#11498 ): fix CheckDbHealthTask.
> fix(#11498): fix CheckDbHealthTask.

- address/src/main/java/com/alibaba/nacos/address/config/AddressServerSecurityConfiguration.java
- plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/NacosAuthConfig.java
- prometheus/src/main/java/com/alibaba/nacos/prometheus/conf/PrometheusSecurityConfiguration.java
> [ISSUE #11586]Remove deprecated api of spring security

- plugin/control/src/main/java/com/alibaba/nacos/plugin/control/tps/barrier/SimpleCountRuleBarrier.java
fix https://github.com/alibaba/nacos/issues/11573
XX
XXXX
> [ISSUE #11573]fix default tps control plugin

- client/src/main/java/com/alibaba/nacos/client/naming/cache/ServiceInfoHolder.java
> [ISSUE #11526] Update ServiceInfoHolder.java, add log output in processServiceInfo

- naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/impl/PersistentClientOperationServiceImpl.java
FIX https://github.com/alibaba/nacos/issues/11571
> 修复client register事件跟clientManager addClient异步并行问题

- config/src/test/java/com/alibaba/nacos/config/server/aspect/CapacityManagementAspectTest.java
> [add unit test case] Add unit test for capacity management aspect

- plugin/control/src/main/java/com/alibaba/nacos/plugin/control/rule/storage/LocalDiskRuleStorage.java
fix https://github.com/alibaba/nacos/issues/11619
XX
XXXX
> [ISSUES #11619]control plugin fix LocalDiskRuleStorage mkdirs

- client/src/main/java/com/alibaba/nacos/client/naming/cache/ServiceInfoHolder.java
- plugin/control/src/test/java/com/alibaba/nacos/plugin/control/ControlManagerBuilderTest.java
- plugin/control/src/test/java/com/alibaba/nacos/plugin/control/ControlManagerCenterTest.java
- plugin/control/src/test/java/com/alibaba/nacos/plugin/control/spi/ExternalRuleStorageBuilderTest.java
- plugin/control/src/test/java/com/alibaba/nacos/plugin/control/spi/ExternalRuleStorageTest.java
- plugin/control/src/test/java/com/alibaba/nacos/plugin/control/utils/DiskUtilsTest.java
- plugin/control/src/test/java/com/alibaba/nacos/plugin/control/utils/EnvUtilsTest.java
- plugin/control/src/test/resources/META-INF/services/com.alibaba.nacos.plugin.control.spi.ControlManagerBuilder
- plugin/control/src/test/resources/META-INF/services/com.alibaba.nacos.plugin.control.spi.ExternalRuleStorageBuilder
link https://github.com/alibaba/nacos/issues/4981
XX
XXXX
> add UT for control plugin

- api/src/main/java/com/alibaba/nacos/api/PropertyKeyConst.java
- api/src/main/java/com/alibaba/nacos/api/SystemPropertyKeyConst.java
- api/src/main/java/com/alibaba/nacos/api/common/Constants.java
- client/src/main/java/com/alibaba/nacos/client/config/NacosConfigService.java
- client/src/main/java/com/alibaba/nacos/client/config/http/ServerHttpAgent.java
- client/src/main/java/com/alibaba/nacos/client/config/impl/CacheData.java
- client/src/main/java/com/alibaba/nacos/client/config/impl/ServerListManager.java
- client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingService.java
- client/src/main/java/com/alibaba/nacos/client/naming/net/NamingProxy.java
- client/src/main/java/com/alibaba/nacos/client/utils/PreInitUtils.java
- client/src/main/java/com/alibaba/nacos/client/utils/RamUtil.java
- client/src/main/resources/nacos-log4j2.xml
- client/src/test/java/com/alibaba/nacos/client/config/http/ServerHttpAgentTest.java
- client/src/test/java/com/alibaba/nacos/client/naming/net/NamingProxyTest.java
- client/src/test/resources/test_ram_info.properties
- console/src/main/java/com/alibaba/nacos/console/controller/UserController.java
- console/src/main/java/com/alibaba/nacos/console/security/nacos/NacosAuthManager.java
- distribution/bin/startup.cmd
- pom.xml
> Merged from v1.x-develop

- core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcBiStreamRequestAcceptor.java
> Server don't send its abilities if client don't send its abilities when setting up connection

- auth/src/main/java/com/alibaba/nacos/auth/config/AuthConfigs.java
fix https://github.com/alibaba/nacos/issues/11601
XX
XXXX
> [ISSUES #11601]Auth check fix

- auth/src/main/java/com/alibaba/nacos/auth/config/AuthConfigs.java
> Revert "[ISSUES #11601]Auth check fix"

- config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigServletInner.java
- config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigQueryRequestHandler.java
- config/src/main/java/com/alibaba/nacos/config/server/service/ConfigCacheService.java
- config/src/main/java/com/alibaba/nacos/config/server/utils/PropertyUtil.java
- config/src/test/java/com/alibaba/nacos/config/server/controller/ConfigServletInnerTest.java
- config/src/test/java/com/alibaba/nacos/config/server/remote/ConfigQueryRequestHandlerTest.java
- config/src/test/java/com/alibaba/nacos/config/server/service/ConfigCacheServiceTest.java
- plugin/encryption/src/main/java/com/alibaba/nacos/plugin/encryption/handler/EncryptionHandler.java
1.Remove direct read model.  Uniform dump and query procedure for all persistent models to simply code complexity.
2.optimize config query for both http and grpc handler ,simple code complexity
3.make up config query coverage to 95%+
related issue https://github.com/alibaba/nacos/issues/11607
> remove direct read

- .github/workflows/pr-e2e-test.yml
- .github/workflows/push-ci.yaml
XXXXX
add multi language test pipeline
XXXX
> Multi Language CI

- plugin/control/src/test/java/com/alibaba/nacos/plugin/control/utils/EnvUtilsTest.java
没有清理环境变量导致执行 Test Case 之后在工程 test 目录生成了临时文件。
- Add `@After` to clear system property `nacos.home`.
> Clean up system property after running the test case

- config/src/main/java/com/alibaba/nacos/config/server/service/HistoryService.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/HistoryConfigInfoMapper.java
- plugin/datasource/src/test/java/com/alibaba/nacos/plugin/datasource/impl/derby/HistoryConfigInfoMapperByDerbyTest.java
- plugin/datasource/src/test/java/com/alibaba/nacos/plugin/datasource/impl/mysql/HistoryConfigInfoMapperByMySqlTest.java
fix https://github.com/alibaba/nacos/issues/11695
XX
XXXX
> [ISSUE#11695] fix PreviousConfigHistory encryption

- config/src/main/resources/META-INF/derby-schema.sql
- config/src/main/resources/META-INF/mysql-schema.sql
- console/src/main/resources/META-INF/derby-schema.sql
- test/config-test/src/test/resources/derby-schema.sql
#11606 Make sql-schema consistent.
#11606 Make sql-schema consistent.
#11606 Make sql-schema consistent.
> build(11606): Make sql-schema consistent.

- api/src/main/java/com/alibaba/nacos/api/PropertyKeyConst.java
- client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java
- client/src/main/java/com/alibaba/nacos/client/naming/core/ServiceInfoUpdateService.java
- client/src/main/java/com/alibaba/nacos/client/naming/utils/UtilAndComs.java
#11618
Add three config
- clientWorkerMaxThreadCount
- clientWorkerThreadCount
- namingPollingMaxThreadCount
XXXX
> [ISSUE #11618] Add the config of max thread count for client worker & naming polling

- naming/src/main/java/com/alibaba/nacos/naming/push/v2/hook/NacosMonitorPushResultHook.java
- naming/src/test/java/com/alibaba/nacos/naming/push/v2/hook/NacosMonitorPushResultHookTest.java
Fix totalpush cannot increase count when push fail
Fix totalpush cannot increase count when push fail
> [ISSUE#11679] when push fail the totalpush count cannot increase

- client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java
- client/src/test/java/com/alibaba/nacos/client/config/impl/ClientWorkerTest.java
fix(#11127 ): Fix ClientWork removeListener and addListener concurrency issue.
fix(#11127 ): Fix ClientWork removeListener and addListener concurrency issue.
fix(#11127 ): Fix ClientWork removeListener and addListener concurrency issue.
> fix(11127): Fix ClientWork removeListener and addListener concurrency issue.

- core/src/main/java/com/alibaba/nacos/core/monitor/NacosMeterRegistryCenter.java
- lock/src/main/java/com/alibaba/nacos/lock/aspect/RequestLockAspect.java
- lock/src/main/java/com/alibaba/nacos/lock/monitor/LockMemoryMonitor.java
- lock/src/main/java/com/alibaba/nacos/lock/monitor/LockMetricsMonitor.java
- lock/src/main/java/com/alibaba/nacos/lock/service/impl/LockOperationServiceImpl.java
linked #10378
add lock query count and rt metrics
> [ISSUE #10378]add lock query count and rt metrics

- pom.xml
build(#11749 ): upgrade spring boot version.
build(#11749 ): upgrade spring boot version.
build(#11749 ): upgrade spring boot version.
> build(#11749 ): upgrade spring boot version.

- example/src/main/java/com/alibaba/nacos/example/NamingExample.java
- example/src/main/resources/logback.xml
> Enhance nacos example

- common/src/test/java/com/alibaba/nacos/common/utils/ExceptionUtilTest.java
- config/src/test/java/com/alibaba/nacos/config/server/controller/ConfigServletInnerTest.java
> The test case pass

- plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/persistence/handler/PageHandlerAdapterFactory.java
https://github.com/alibaba/nacos/issues/11723
XX
XXXX
> fix issues/11723 PageHandlerAdapterFactory 集合容量不够大

- README.md
update community information and official website download channel
XXXXX
XX
XXXX
> Update README.md for community information and official website download channel

- auth/src/main/java/com/alibaba/nacos/auth/GrpcProtocolAuthService.java
- client/src/main/java/com/alibaba/nacos/client/auth/ram/identify/CredentialService.java
- common/src/main/java/com/alibaba/nacos/common/spi/NacosServiceLoader.java
- common/src/main/java/com/alibaba/nacos/common/trace/publisher/TraceEventPublisher.java
- common/src/main/java/com/alibaba/nacos/common/trace/publisher/TraceEventPublisherFactory.java
- config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigChangeListenContext.java
- consistency/src/main/java/com/alibaba/nacos/consistency/ProtocolMetaData.java
- consistency/src/main/java/com/alibaba/nacos/consistency/Serializer.java
- core/src/main/java/com/alibaba/nacos/core/code/ControllerMethodsCache.java
- core/src/main/java/com/alibaba/nacos/core/distributed/distro/monitor/DistroRecordsHolder.java
- core/src/main/java/com/alibaba/nacos/core/remote/ConnectionManager.java
- naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/PersistentNotifier.java
- naming/src/main/java/com/alibaba/nacos/naming/core/v2/ServiceManager.java
- naming/src/main/java/com/alibaba/nacos/naming/core/v2/event/publisher/NamingEventPublisher.java
- naming/src/main/java/com/alibaba/nacos/naming/core/v2/event/publisher/NamingEventPublisherFactory.java
- naming/src/main/java/com/alibaba/nacos/naming/core/v2/index/ClientServiceIndexesManager.java
- naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/NamingMetadataManager.java
link #11782
1. Reduce the number of Map.hash() method
2. Optimize code writing
很多旧代码，但是核心链路，对map重复get，put等方法，导致hash方法重复调用多次。
> [ISSUE #11782] Optimized the use of map

- pom.xml
> Upgrade to 2.3.1

- pom.xml
> Upgrade to 2.4.0-SNAPSHOT.

- example/src/main/resources/logback.xml
fixs #11793 
modify the log file path. use relative paths instead of absolute paths.
XX
XXXX
> IISSUE#11793  Fix logback.xml Incorrect configuration

- client/pom.xml
> [ISSUE #11871]  remove reflection from client pom.xml

- common/pom.xml
- naming/pom.xml
- persistence/pom.xml
- pom.xml
https://github.com/alibaba/nacos/issues/11874
Using MySQL for new groupId
Upgrade MySQL dependency version
使用 MySQL 新坐标
升级 MySQL 依赖版本
:arrow_up: upgrade mysql-connector-java from 8.0.28 to 8.0.33
XXXX
> :arrow_up: upgrade mysql-connector-java from 8.0.28 to 8.0.33

- api/src/main/java/com/alibaba/nacos/api/remote/response/ErrorResponse.java
- api/src/test/java/com/alibaba/nacos/api/remote/response/ErrorResponseTest.java
> [Issue 11892] keep ErrorResponse result code the same with errorcode

- config/src/main/java/com/alibaba/nacos/config/server/service/ConfigOperationService.java
- config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedConfigInfoPersistServiceImpl.java
- config/src/test/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedConfigInfoPersistServiceImplTest.java
link #11847 
1. set old md5 before use publishCas method
2. set rollbackOnUpdateFail = true
> [ISSUE #11847] fix OpenApi publish Cas fail

- naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/impl/EphemeralClientOperationServiceImpl.java
- naming/src/test/java/com/alibaba/nacos/naming/core/v2/service/impl/EphemeralClientOperationServiceImplTest.java
fix(#11895): grpc 服务注册失败时返回了成功
fix(#11895): grpc 服务注册失败时返回了成功
fix(#11895): grpc 服务注册失败时返回了成功
> fix(#11895): grpc 服务注册失败时返回了成功

- console-ui/package-lock.json
> Bump console ui dependencies to solve security problem with audit fix.

- client/src/main/resources/META-INF/native-image/com.alibaba.nacos/nacos-client/reflect-config.json
add deletion graalvm reflect config
fix #11902
client/src/main/resources/META-INF/native-image/com.alibaba.nacos/nacos-client/reflect-config.json
ServerAbilities
ServerConfigAbility
ServerNamingAbility
ServerRemoteAbility
Member
DistroData
DistroKey
ClientConfigMetricRequest
ClientConfigMetricRequest$MetricsKey
ConfigBatchListenRequest
ConfigBatchListenRequest$ConfigListenContext
ConfigPublishRequest
ConfigQueryRequest
ConfigRemoveRequest
ConfigChangeClusterSyncRequest
BatchInstanceRequest
PersistentInstanceRequest
ServiceListRequest
ServiceQueryRequest
ClientDetectionRequest
ConnectResetRequest
PushAckRequest
ServerLoaderInfoRequest
ServerReloadRequest
SetupAckRequest
AbstractClusterRequest
MemberReportRequest …
> [ISSUE #11902] Fix request and response reflect-config.json

- pom.xml
Closes https://github.com/alibaba/nacos/issues/11980
XXXXX
XX
XXXX
> fix: CVE-2024-22262 Upgrade Spring to 5.3.34 (#11980)

- consistency/pom.xml
- consistency/src/main/java/com/alibaba/nacos/consistency/ProtocolMetaData.java
- core/pom.xml
- naming/pom.xml
- pom.xml
> [#11975] clean code , remove unused dependency javatuple

- logger-adapter-impl/log4j2-adapter/src/main/resources/nacos-log4j2.xml
- logger-adapter-impl/log4j2-adapter/src/test/java/com/alibaba/nacos/logger/adapter/log4j2/Log4J2NacosLoggingAdapterTest.java
- logger-adapter-impl/logback-adapter-12/src/main/resources/nacos-logback12.xml
> [ISSUE #12041] fix client log config

- pom.xml
support  step2 in #12016 
XX
XXXX
> [WIP] add junit  jupiter

- config/src/main/java/com/alibaba/nacos/config/server/service/ConfigCacheService.java
Bug fix https://github.com/alibaba/nacos/issues/11926 The abnormal exit mechanism does not take effect
> [ISSUE #11926] The abnormal exit mechanism does not take effect

- distribution/bin/startup.cmd
- distribution/bin/startup.sh
support https://github.com/alibaba/nacos/issues/12013
XX
XXXX
> feat(develop): [ISSUES #12013] startup.sh support environment CUSTOM_NACOS_MEMORY

- config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedConfigDumpApplyHook.java
https://github.com/alibaba/nacos/issues/12062
XX
XXXX
> [ISSUE #12062] fix EmbeddedConfigDumpApplyHook bug

- common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClient.java
> fix #11984

- sys/src/test/java/com/alibaba/nacos/sys/env/EnvModuleStateBuilderTest.java
- sys/src/test/java/com/alibaba/nacos/sys/env/EnvUtilWithConfigTest.java
- sys/src/test/java/com/alibaba/nacos/sys/env/EnvUtilWithoutConfigTest.java
- sys/src/test/java/com/alibaba/nacos/sys/module/ModuleStateHolderTest.java
- sys/src/test/java/com/alibaba/nacos/sys/utils/DiskUtilsTest.java
- sys/src/test/java/com/alibaba/nacos/sys/utils/InetUtilsTest.java
- sys/src/test/java/com/alibaba/nacos/sys/utils/MethodUtilTest.java
- sys/src/test/java/com/alibaba/nacos/sys/utils/PropertiesUtilTest.java
> [ISSUE 12106] upgrade module naocs-sys from junit4 to junit5

- auth/src/test/java/com/alibaba/nacos/auth/GrpcProtocolAuthServiceTest.java
- auth/src/test/java/com/alibaba/nacos/auth/HttpProtocolAuthServiceTest.java
- auth/src/test/java/com/alibaba/nacos/auth/config/AuthConfigsTest.java
- auth/src/test/java/com/alibaba/nacos/auth/config/AuthModuleStateBuilderTest.java
- auth/src/test/java/com/alibaba/nacos/auth/context/GrpcIdentityContextBuilderTest.java
- auth/src/test/java/com/alibaba/nacos/auth/context/HtppIdentityContextBuilderTest.java
- auth/src/test/java/com/alibaba/nacos/auth/mock/MockAuthPluginService.java
- auth/src/test/java/com/alibaba/nacos/auth/parser/grpc/ConfigGrpcResourceParserTest.java
- auth/src/test/java/com/alibaba/nacos/auth/parser/grpc/NamingGrpcResourceParserTest.java
- auth/src/test/java/com/alibaba/nacos/auth/parser/http/ConfigHttpResourceParserTest.java
- auth/src/test/java/com/alibaba/nacos/auth/parser/http/NamingHttpResourceParserTest.java
> [ISSUE #12104] upgrade module naocs-auth from junit4 to junit5

- consistency/src/test/java/com/alibaba/nacos/consistency/ProtoMessageUtilTest.java
- consistency/src/test/java/com/alibaba/nacos/consistency/ProtocolMetaDataTest.java
- consistency/src/test/java/com/alibaba/nacos/consistency/SerializeFactoryTest.java
- consistency/src/test/java/com/alibaba/nacos/consistency/serialize/HessianSerializerTest.java
- consistency/src/test/java/com/alibaba/nacos/consistency/serialize/JacksonSerializerTest.java
- consistency/src/test/java/com/alibaba/nacos/consistency/snapshot/LocalFileMetaTest.java
- consistency/src/test/java/com/alibaba/nacos/consistency/snapshot/ReaderTest.java
- consistency/src/test/java/com/alibaba/nacos/consistency/snapshot/WriterTest.java
> [ISSUE #12115] upgrade module naocs-consistency  from junit4 to junit5

- .github/workflows/ci.yml
> update codecov token.

- plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/controller/UserController.java
> [ISSUE#11957]Change duplicate create admin user api return code to 4xx.

- plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/NacosAuthPluginService.java
> [ISSUE#11957] No need init password when auth disabled.

- logger-adapter-impl/log4j2-adapter/src/test/java/com/alibaba/nacos/logger/adapter/log4j2/Log4J2NacosLoggingAdapterTest.java
- logger-adapter-impl/log4j2-adapter/src/test/java/com/alibaba/nacos/logger/adapter/log4j2/Log4j2NacosLoggingAdapterBuilderTest.java
- logger-adapter-impl/log4j2-adapter/src/test/java/com/alibaba/nacos/logger/adapter/log4j2/NacosClientPropertiesLookupTest.java
- logger-adapter-impl/logback-adapter-12/src/test/java/com/alibaba/nacos/logger/adapter/logback12/LogbackNacosLoggingAdapterBuilderTest.java
- logger-adapter-impl/logback-adapter-12/src/test/java/com/alibaba/nacos/logger/adapter/logback12/LogbackNacosLoggingAdapterTest.java
- logger-adapter-impl/logback-adapter-12/src/test/java/com/alibaba/nacos/logger/adapter/logback12/NacosClientPropertyActionTest.java
- logger-adapter-impl/logback-adapter-12/src/test/java/com/alibaba/nacos/logger/adapter/logback12/NacosLogbackConfiguratorAdapterV1Test.java
> [ISSUE #12155] upgrade module naocs-log from junit4 to junit5

- pom.xml
> Upgrade to 2.4.0-BETA

- config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigController.java
> [ISSUE #12180] 修复克隆和导入配置没有记录操作人

- plugin-default-impl/nacos-default-auth-plugin/src/test/java/com/alibaba/nacos/plugin/auth/impl/LdapAuthenticationProviderTest.java
- plugin-default-impl/nacos-default-auth-plugin/src/test/java/com/alibaba/nacos/plugin/auth/impl/configuration/ConditionOnLdapAuthTest.java
- plugin-default-impl/nacos-default-auth-plugin/src/test/java/com/alibaba/nacos/plugin/auth/impl/controller/UserControllerTest.java
- plugin-default-impl/nacos-default-auth-plugin/src/test/java/com/alibaba/nacos/plugin/auth/impl/jwt/NacosJwtParserTest.java
- plugin-default-impl/nacos-default-auth-plugin/src/test/java/com/alibaba/nacos/plugin/auth/impl/persistence/EmbeddedPermissionPersistServiceImplTest.java
- plugin-default-impl/nacos-default-auth-plugin/src/test/java/com/alibaba/nacos/plugin/auth/impl/persistence/EmbeddedRolePersistServiceImplTest.java
- plugin-default-impl/nacos-default-auth-plugin/src/test/java/com/alibaba/nacos/plugin/auth/impl/persistence/EmbeddedUserPersistServiceImplTest.java
- plugin-default-impl/nacos-default-auth-plugin/src/test/java/com/alibaba/nacos/plugin/auth/impl/persistence/ExternalPermissionPersistServiceImplTest.java
- plugin-default-impl/nacos-default-auth-plugin/src/test/java/com/alibaba/nacos/plugin/auth/impl/persistence/ExternalRolePersistServiceImplTest.java
- plugin-default-impl/nacos-default-auth-plugin/src/test/java/com/alibaba/nacos/plugin/auth/impl/persistence/ExternalUserPersistServiceImplTest.java
- plugin-default-impl/nacos-default-auth-plugin/src/test/java/com/alibaba/nacos/plugin/auth/impl/roles/NacosRoleServiceImplTest.java
- plugin-default-impl/nacos-default-auth-plugin/src/test/java/com/alibaba/nacos/plugin/auth/impl/token/TokenManagerDelegateTest.java
- plugin-default-impl/nacos-default-auth-plugin/src/test/java/com/alibaba/nacos/plugin/auth/impl/token/impl/CachedJwtTokenManagerTest.java
- plugin-default-impl/nacos-default-auth-plugin/src/test/java/com/alibaba/nacos/plugin/auth/impl/token/impl/JwtTokenManagerTest.java
- plugin-default-impl/nacos-default-auth-plugin/src/test/java/com/alibaba/nacos/plugin/auth/impl/utils/Base64DecodeTest.java
- plugin-default-impl/nacos-default-auth-plugin/src/test/java/com/alibaba/nacos/plugin/auth/impl/utils/PasswordEncoderUtilTest.java
- plugin-default-impl/nacos-default-auth-plugin/src/test/java/com/alibaba/nacos/plugin/auth/impl/utils/PasswordGeneratorUtilTest.java
- plugin-default-impl/nacos-default-control-plugin/src/test/java/com/alibaba/nacos/plugin/control/impl/NacosConnectionControlManagerTest.java
- plugin-default-impl/nacos-default-control-plugin/src/test/java/com/alibaba/nacos/plugin/control/impl/NacosControlManagerBuilderTest.java
- plugin-default-impl/nacos-default-control-plugin/src/test/java/com/alibaba/nacos/plugin/control/impl/NacosTpsControlManagerTest.java
> [ISSUE #12226 ]upgrade module naocs-plugin-impl from junit4 to junit5

- persistence/src/test/java/com/alibaba/nacos/persistence/configuration/condition/ConditionDistributedEmbedStorageTest.java
- persistence/src/test/java/com/alibaba/nacos/persistence/configuration/condition/ConditionOnEmbeddedStorageTest.java
- persistence/src/test/java/com/alibaba/nacos/persistence/configuration/condition/ConditionOnExternalStorageTest.java
- persistence/src/test/java/com/alibaba/nacos/persistence/configuration/condition/ConditionStandaloneEmbedStorageTest.java
- persistence/src/test/java/com/alibaba/nacos/persistence/datasource/ClusterExternalStorageTest.java
- persistence/src/test/java/com/alibaba/nacos/persistence/datasource/DataSourcePoolPropertiesTest.java
- persistence/src/test/java/com/alibaba/nacos/persistence/datasource/DynamicDataSourceTest.java
- persistence/src/test/java/com/alibaba/nacos/persistence/datasource/ExternalDataSourcePropertiesTest.java
- persistence/src/test/java/com/alibaba/nacos/persistence/datasource/ExternalDataSourceServiceImplTest.java
- persistence/src/test/java/com/alibaba/nacos/persistence/datasource/LocalDataSourceServiceImplTest.java
- persistence/src/test/java/com/alibaba/nacos/persistence/datasource/StandaloneExternalStorageTest.java
- persistence/src/test/java/com/alibaba/nacos/persistence/repository/embedded/operate/MockConfigInfo.java
- persistence/src/test/java/com/alibaba/nacos/persistence/repository/embedded/operate/StandaloneDatabaseOperateImplTest.java
- persistence/src/test/java/com/alibaba/nacos/persistence/utils/ConnectionCheckUtilTest.java
- persistence/src/test/java/com/alibaba/nacos/persistence/utils/DerbyUtilsTest.java
- persistence/src/test/java/com/alibaba/nacos/persistence/utils/PersistenceExecutorTest.java
> [ISSUE #12224]upgrade module naocs-persistence from junit4 to junit5

- logger-adapter-impl/pom.xml
> [ISSUE #12265] fix nacos client dependencies tree without grpc package

- client/src/main/java/com/alibaba/nacos/client/naming/backups/datasource/DiskFailoverDataSource.java
- client/src/test/java/com/alibaba/nacos/client/naming/backups/datasource/DiskFailoverDataSourceTest.java
> [ISSUE #12207] fix disk failover datasource not keep status

- auth/src/test/java/com/alibaba/nacos/auth/config/AuthModuleStateBuilderTest.java
- auth/src/test/java/com/alibaba/nacos/auth/mock/MockAuthPluginServiceB.java
- auth/src/test/resources/META-INF/services/com.alibaba.nacos.plugin.auth.spi.server.AuthPluginService
- plugin-default-impl/nacos-default-auth-plugin/src/test/java/com/alibaba/nacos/plugin/auth/impl/authenticate/AbstractAuthenticationManagerTest.java
- plugin-default-impl/nacos-default-auth-plugin/src/test/java/com/alibaba/nacos/plugin/auth/impl/authenticate/LdapAuthenticationManagerTest.java
- plugin-default-impl/nacos-default-auth-plugin/src/test/java/com/alibaba/nacos/plugin/auth/impl/controller/PermissionControllerTest.java
- plugin-default-impl/nacos-default-auth-plugin/src/test/java/com/alibaba/nacos/plugin/auth/impl/controller/RoleControllerTest.java
- plugin-default-impl/nacos-default-auth-plugin/src/test/java/com/alibaba/nacos/plugin/auth/impl/controller/UserControllerTest.java
link https://github.com/alibaba/nacos/issues/4981
XX
XXXX
> add some UT for default auth plugin

- sys/src/main/java/com/alibaba/nacos/sys/utils/InetUtils.java
- sys/src/test/java/com/alibaba/nacos/sys/utils/InetUtilsTest.java
> [ISSUE #12321] fix unexpect exception from NetworkInterface.ifUp

- test/core-test/src/test/java/com/alibaba/nacos/test/core/SnowFlowerIdGeneratorCoreITCase.java
- test/core-test/src/test/java/com/alibaba/nacos/test/core/cluster/MemberLookupCoreITCase.java
- test/core-test/src/test/java/com/alibaba/nacos/test/core/cluster/ServerMemberManagerCoreITCase.java
- test/core-test/src/test/java/com/alibaba/nacos/test/core/code/ControllerMethodsCacheCoreITCase.java
- test/core-test/src/test/java/com/alibaba/nacos/test/smoke/NacosSmokeCoreITCase.java
…re module to comply with checkstyle.
XX
XXXX
> Adjust integration tests for cluster,code,smoke modules in the core module to comply with checkstyle.

- api/pom.xml
- core/pom.xml
- pom.xml
> Upgrade grpc to 1.64.2

- config/src/main/java/com/alibaba/nacos/config/server/configuration/ConfigCommonConfig.java
- config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigOpsController.java
- config/src/test/java/com/alibaba/nacos/config/server/configuration/ConfigCommonConfigTest.java
- config/src/test/java/com/alibaba/nacos/config/server/controller/ConfigOpsControllerTest.java
- test/config-test/src/test/java/com/alibaba/nacos/test/base/BaseClusterTest.java
- test/config-test/src/test/java/com/alibaba/nacos/test/config/ConfigDerbyRaft_DITCase.java
> Close derby ops api default.

- pom.xml
> Upgrade to 2.4.0

- plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/controller/UserController.java
- plugin-default-impl/nacos-default-auth-plugin/src/test/java/com/alibaba/nacos/plugin/auth/impl/controller/UserControllerTest.java
> Fix #12395, use request context replace session depend.

- plugin-default-impl/nacos-default-plugin-all/pom.xml
https://github.com/alibaba/nacos/issues/12416
fix pom.xml version
XX
XXXX
> :wrench: fix pom.xml version

- plugin/control/src/main/java/com/alibaba/nacos/plugin/control/connection/ConnectionControlManager.java
Fix the bug of connectionControlMananger, when no connection limit rules are found, use RuleParser to create a blank rule.
During initialization, use RuleParser to create a blank rule.
XXXX
> [ISSUE #12397]Fix the bug of ConnectionControlManager,use RuleParser to create a blank rule

- test/config-test/src/test/java/com/alibaba/nacos/test/config/AbstractConfigAPIConfigITCase.java
- test/config-test/src/test/java/com/alibaba/nacos/test/config/ConfigAPIConfigITCase.java
- test/config-test/src/test/java/com/alibaba/nacos/test/config/ConfigAPIV2ConfigITCase.java
- test/config-test/src/test/java/com/alibaba/nacos/test/config/ConfigAPIWithRootContextPathConfigITCase.java
- test/config-test/src/test/java/com/alibaba/nacos/test/config/ConfigBetaConfigITCase.java
- test/config-test/src/test/java/com/alibaba/nacos/test/config/ConfigDerbyImportConfigITCase.java
- test/config-test/src/test/java/com/alibaba/nacos/test/config/ConfigDerbyRaftConfigITCase.java
- test/config-test/src/test/java/com/alibaba/nacos/test/config/ConfigExportAndImportAPIConfigITCase.java
- test/config-test/src/test/java/com/alibaba/nacos/test/config/ConfigLongPollConfigITCase.java
- test/config-test/src/test/java/com/alibaba/nacos/test/config/ConfigLongPollReturnChangesConfigITCase.java
- test/config-test/src/test/java/com/alibaba/nacos/test/config/EmbeddedStorageContextUtilsConfigITCase.java
- test/config-test/src/test/java/com/alibaba/nacos/test/config/NacosConfigServiceComTlsGrpcClientConfigITCase.java
- test/config-test/src/test/java/com/alibaba/nacos/test/config/NacosConfigServiceNoComTlsGrpcClientConfigITCase.java
- test/config-test/src/test/java/com/alibaba/nacos/test/config/NacosConfigV2MutualAuthConfigITCase.java
> [IT]Adjust config module config ITs for Checkstyle compliance. 

- test/config-test/src/test/java/com/alibaba/nacos/test/base/BaseClusterTest.java
- test/config-test/src/test/java/com/alibaba/nacos/test/base/HttpClient4Test.java
- test/config-test/src/test/java/com/alibaba/nacos/test/base/Params.java
- test/core-test/src/test/java/com/alibaba/nacos/test/core/auth/AuthBase.java
- test/core-test/src/test/java/com/alibaba/nacos/test/core/auth/ConfigAuthCoreITCase.java
- test/core-test/src/test/java/com/alibaba/nacos/test/core/auth/LdapAuthCoreITCase.java
- test/core-test/src/test/java/com/alibaba/nacos/test/core/auth/NamingAuthCoreITCase.java
- test/core-test/src/test/java/com/alibaba/nacos/test/core/auth/PermissionCoreITCase.java
- test/core-test/src/test/java/com/alibaba/nacos/test/core/auth/RoleCoreITCase.java
- test/core-test/src/test/java/com/alibaba/nacos/test/core/auth/UserCoreITCase.java
> [IT]Adjust config module base and auth ITs for Checkstyle compliance. 

- plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/jwt/NacosSignatureAlgorithm.java
fixes https://github.com/alibaba/nacos/issues/12446
对Mac getMacInstance(Key key)补充日志
XX
XXXX
头一次尝试着学习提交PR～如有规范和其它问题，希望大佬们提点，谢谢。
> [ISSUE#12446] getMacInstance 补充日志

- .github/workflows/ci.yml
> Try to fix codecov lose for PR.

- pom.xml
> Upgrade to 1.4.8.

- pom.xml
> Upgrade to 2.4.1

- client/src/main/java/com/alibaba/nacos/client/auth/impl/NacosClientAuthServiceImpl.java
> [ISSUE #12509] Fix nacos-client updating accessToken bug.

- .github/workflows/ci.yml
> checkout pr code to do ci.

- config/src/test/resources/logback-test.xml
- core/src/test/resources/logback-test.xml
- persistence/src/test/resources/logback-test.xml
- sys/src/test/resources/logback-test.xml
> Add test logback configuration to remove spring debug log.

- core/src/main/java/com/alibaba/nacos/core/paramcheck/CheckConfiguration.java
- core/src/test/java/com/alibaba/nacos/core/paramcheck/CheckConfigurationTest.java
> [ISSUE#12563] Fix paramchecker invalid bug

- consistency/pom.xml
- pom.xml
This reverts commit 5d8d81aae475e27320f1fc351aba7880c664f942.
For #12498, #12503
After jraft upgrade hessain to new version and support jdk17+, redo #11963.
XX
XXXX
> Revert "Resolve the Hessian package conflict issue. (#12449)"

- console/src/main/java/com/alibaba/nacos/console/controller/v3/ConsoleHealthController.java
- console/src/main/java/com/alibaba/nacos/console/controller/v3/ConsoleServerStateController.java
- console/src/main/java/com/alibaba/nacos/console/controller/v3/core/ConsoleNamespaceController.java
- console/src/main/java/com/alibaba/nacos/console/handler/HealthHandler.java
- console/src/main/java/com/alibaba/nacos/console/handler/ServerStateHandler.java
- console/src/main/java/com/alibaba/nacos/console/handler/core/NamespaceHandler.java
- console/src/main/java/com/alibaba/nacos/console/handler/inner/HealthInnerHandler.java
- console/src/main/java/com/alibaba/nacos/console/handler/inner/ServerStateInnerHandler.java
- console/src/main/java/com/alibaba/nacos/console/handler/inner/core/NamespaceInnerHandler.java
- console/src/main/java/com/alibaba/nacos/console/proxy/HealthProxy.java
- console/src/main/java/com/alibaba/nacos/console/proxy/ServerStateProxy.java
- console/src/main/java/com/alibaba/nacos/console/proxy/core/NamespaceProxy.java
For [12017](https://github.com/alibaba/nacos/issues/12017)
Refactor the old version of the console's controller
* Refactor the old version of the console's controller
> [ISSUE #12017] Add the console backend API for old section

- .github/workflows/push-ci.yaml
actions/download-artifact@v4.1.7 和 actions/upload-artifact@v3 有版本冲突，需要升级actions/upload-artifact到v4版本
升级actions/upload-artifact版本
XXXX
> fix: upgrade upload-artifact version

- config/src/main/java/com/alibaba/nacos/config/server/exception/GlobalExceptionHandler.java
- naming/src/main/java/com/alibaba/nacos/naming/exception/ResponseExceptionHandler.java
- pom.xml
> Fix wrong error code for http open api request.

- pom.xml
> Upgrade to 2.4.3.

- pom.xml
> Upgrade to 2.5.0-SNAPSHOT.

- sys/src/main/java/com/alibaba/nacos/sys/env/EnvUtil.java
- sys/src/main/java/com/alibaba/nacos/sys/file/WatchFileCenter.java
- sys/src/main/java/com/alibaba/nacos/sys/utils/ApplicationUtils.java
- sys/src/test/java/com/alibaba/nacos/sys/env/EnvUtilTest.java
- sys/src/test/java/com/alibaba/nacos/sys/env/OperatingSystemBeanManagerTest.java
- sys/src/test/java/com/alibaba/nacos/sys/env/OriginTrackedPropertiesLoaderTest.java
- sys/src/test/java/com/alibaba/nacos/sys/file/WatchFileCenterTest.java
- sys/src/test/java/com/alibaba/nacos/sys/filter/NacosTypeExcludeFilterTest.java
- sys/src/test/java/com/alibaba/nacos/sys/filter/mock/MockNacosPackageExcludeFilter.java
- sys/src/test/java/com/alibaba/nacos/sys/module/ModuleStateHolderTest.java
- sys/src/test/java/com/alibaba/nacos/sys/module/mock/MockRebuildModuleStateBuilder.java
- sys/src/test/java/com/alibaba/nacos/sys/utils/ApplicationUtilsTest.java
- sys/src/test/java/com/alibaba/nacos/sys/utils/DiskUtilsTest.java
- sys/src/test/java/com/alibaba/nacos/sys/utils/DiskUtilsZipTest.java
- sys/src/test/java/com/alibaba/nacos/sys/utils/InetUtilsTest.java
- sys/src/test/java/com/alibaba/nacos/sys/utils/TimerContextTest.java
- sys/src/test/resources/META-INF/services/com.alibaba.nacos.sys.filter.NacosPackageExcludeFilter
- sys/src/test/resources/conf/cluster.conf
- sys/src/test/resources/existing-non-multi-document.properties
- sys/src/test/resources/line_iterator_test.txt
- sys/src/test/resources/test-file-watcher-overflow/test.properties
- sys/src/test/resources/test-properties-malformed-unicode.properties
- sys/src/test/resources/test-properties.properties
> Develop sys ut

- .github/workflows/pr-ci.yml
- .github/workflows/pr-e2e-test.yml
- .github/workflows/push-ci.yaml
- support java auth test
- support e2e test write url to pr
- fix cpp bug cased by mirror error
XX
XXXX
> pr_url&auth_test&cpp_mirror_error

- api/src/main/java/com/alibaba/nacos/api/PropertyKeyConst.java
- api/src/main/java/com/alibaba/nacos/api/common/Constants.java
- client/src/main/java/com/alibaba/nacos/client/address/AbstractServerListManager.java
- client/src/main/java/com/alibaba/nacos/client/address/EndpointServerListProvider.java
- client/src/main/java/com/alibaba/nacos/client/address/PropertiesListProvider.java
- client/src/main/java/com/alibaba/nacos/client/address/ServerListChangeEvent.java
- client/src/main/java/com/alibaba/nacos/client/config/impl/ConfigServerListManager.java
- client/src/main/java/com/alibaba/nacos/client/naming/core/NamingServerListManager.java
- client/src/main/resources/META-INF/services/com.alibaba.nacos.client.address.ServerListProvider
- client/src/test/java/com/alibaba/nacos/client/address/AbstractServerListManagerTest.java
- client/src/test/java/com/alibaba/nacos/client/address/AddressServerListProviderTest.java
- client/src/test/java/com/alibaba/nacos/client/address/EndpointServerListProviderTest.java
- client/src/test/java/com/alibaba/nacos/client/address/PropertiesListProviderTest.java
- client/src/test/java/com/alibaba/nacos/client/address/mock/MockServerListProvider.java
- client/src/test/java/com/alibaba/nacos/client/config/http/ServerHttpAgentTest.java
- client/src/test/java/com/alibaba/nacos/client/config/impl/ConfigServerListManagerTest.java
- client/src/test/java/com/alibaba/nacos/client/naming/core/NamingServerListManagerTest.java
- client/src/test/resources/META-INF/services/com.alibaba.nacos.client.address.ServerListProvider
> [#12189] Do some enhance and refactor for new server list manager.

- pom.xml
> [ISSUE 12777] bump maven-enforcer-plugin to 3.5.0

- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/derby/HistoryConfigInfoMapperByDerby.java
- plugin/datasource/src/test/java/com/alibaba/nacos/plugin/datasource/impl/derby/HistoryConfigInfoMapperByDerbyTest.java
fix(#12769 ): remove config history by derby.
fix(#12769 ): remove config history by derby.
fix(#12769 ): remove config history by derby.
> fix(#12769 ): remove config history by derby.

- console-ui/src/components/EditorNameSpace/EditorNameSpace.js
- console-ui/src/pages/ClusterManagement/ClusterNodeList/ClusterNodeList.js
- console-ui/src/pages/ConfigurationManagement/ConfigDetail/ConfigDetail.js
- console-ui/src/pages/ConfigurationManagement/ConfigEditor/NewConfigEditor.js
- console-ui/src/pages/ConfigurationManagement/ConfigurationManagement/ConfigurationManagement.js
- console-ui/src/pages/ConfigurationManagement/ListeningToQuery/ListeningToQuery.js
- console-ui/src/pages/Register/Register.jsx
- console-ui/src/pages/ServiceManagement/ServiceDetail/EditClusterDialog.js
- console-ui/src/pages/ServiceManagement/ServiceDetail/EditInstanceDialog.js
- console-ui/src/pages/ServiceManagement/ServiceDetail/EditServiceDialog.js
- console-ui/src/pages/ServiceManagement/ServiceDetail/InstanceTable.js
- console-ui/src/pages/ServiceManagement/ServiceDetail/ServiceDetail.js
- console-ui/src/pages/ServiceManagement/ServiceList/ServiceList.js
- console/src/main/java/com/alibaba/nacos/console/controller/v3/config/ConsoleConfigController.java
- console/src/main/java/com/alibaba/nacos/console/controller/v3/core/ConsoleNamespaceController.java
- console/src/main/java/com/alibaba/nacos/console/controller/v3/naming/ConsoleServiceController.java
- console/src/main/java/com/alibaba/nacos/console/handler/config/ConfigHandler.java
- console/src/main/java/com/alibaba/nacos/console/handler/inner/config/ConfigInnerHandler.java
- console/src/main/java/com/alibaba/nacos/console/proxy/config/ConfigProxy.java
- console/src/test/java/com/alibaba/nacos/console/controller/v3/config/ConsoleConfigControllerTest.java
- console/src/test/java/com/alibaba/nacos/console/controller/v3/core/ConsoleNamespaceControllerTest.java
- plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/NacosAuthPluginService.java
For [12017](https://github.com/alibaba/nacos/issues/12017)
Fix console bugs
* Fix config clone bug
* Fix cluster leave message
* Fix admin request switch
* Fix admin init bug
> [ISSUE #12017] Fix console bugs

- console-ui/src/pages/ConfigurationManagement/ConfigurationManagement/ConfigurationManagement.js
- console-ui/src/utils/request.js
For [12017](https://github.com/alibaba/nacos/issues/12017)
Fix console state bugs
* Fix config clone bug
* Fix state version bug
> [ISSUE #12017] Fix console state bugs

- console/src/test/java/com/alibaba/nacos/console/controller/v3/ConsoleServerStateControllerTest.java
- console/src/test/java/com/alibaba/nacos/console/controller/v3/config/ConsoleConfigControllerTest.java
For [12017](https://github.com/alibaba/nacos/issues/12017)
Fix test unit bugs
* Fix config clone test unit bugs
* Fix server state test unit bugs
> [ISSUE #12017] Fix test unit bugs

- plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/token/impl/JwtTokenManager.java
> Fix empty token can start up problem.

- pom.xml
fix(#12686 ): Upgrade Spring Security version to 5.8.15
fix(#12686 ): Upgrade Spring Security version to 5.8.15
fix(#12686 ): Upgrade Spring Security version to 5.8.15
> fix(#12686): Upgrade Spring Security version to 5.8.15

- core/src/main/java/com/alibaba/nacos/core/service/NamespaceOperationService.java
- core/src/test/java/com/alibaba/nacos/core/service/NamespaceOperationServiceTest.java
fix(#11930 ): the information of default namespace should be consistent.
fix(#11930 ): the information of default namespace should be consistent.
fix(#11930 ): the information of default namespace should be consistent.
> fix(#11930): the information of default namespace should be consistent.

- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/HistoryConfigInfoMapper.java
- plugin/datasource/src/test/java/com/alibaba/nacos/plugin/datasource/impl/derby/HistoryConfigInfoMapperByDerbyTest.java
- plugin/datasource/src/test/java/com/alibaba/nacos/plugin/datasource/impl/mysql/HistoryConfigInfoMapperByMySqlTest.java
Fix the version comparison query SQL.
XXXXX
XX
XXXX
> Fix the version comparison query SQL

- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/mysql/ConfigInfoMapperByMySql.java
fix type search on mysql model
XX
XXXX
> fix type search on mysql model

- auth/src/test/java/com/alibaba/nacos/auth/parser/http/ConfigHttpResourceParserTest.java
- auth/src/test/java/com/alibaba/nacos/auth/parser/http/NamingHttpResourceParserTest.java
- client/src/test/java/com/alibaba/nacos/client/config/NacosConfigServiceTest.java
- config/src/test/java/com/alibaba/nacos/config/server/controller/ConfigControllerTest.java
- config/src/test/java/com/alibaba/nacos/config/server/controller/HistoryControllerTest.java
- config/src/test/java/com/alibaba/nacos/config/server/controller/v2/ConfigControllerV2Test.java
- config/src/test/java/com/alibaba/nacos/config/server/controller/v2/HistoryControllerV2Test.java
- config/src/test/java/com/alibaba/nacos/config/server/remote/ConfigQueryRequestHandlerTest.java
- console/src/test/java/com/alibaba/nacos/console/controller/v3/config/ConsoleConfigControllerTest.java
- console/src/test/java/com/alibaba/nacos/console/controller/v3/config/ConsoleHistoryControllerTest.java
- plugin/datasource/src/test/java/com/alibaba/nacos/plugin/datasource/impl/derby/ConfigInfoMapperByDerbyTest.java
- plugin/datasource/src/test/java/com/alibaba/nacos/plugin/datasource/impl/derby/GroupCapacityMapperByDerbyTest.java
- plugin/datasource/src/test/java/com/alibaba/nacos/plugin/datasource/impl/mysql/ConfigInfoMapperByMySqlTest.java
- plugin/datasource/src/test/java/com/alibaba/nacos/plugin/datasource/impl/mysql/GroupCapacityMapperByMysqlTest.java
- sys/src/test/java/com/alibaba/nacos/sys/env/EnvUtilTest.java
> Fix unit test for v3.0.

- config/src/main/resources/META-INF/mysql-schema.sql
ISSUE #12903
fix syntax errors
XX
XXXX
> [ISSUE #12903] Fix mysql-schema.sql syntax errors

- client/src/main/java/com/alibaba/nacos/client/config/impl/ConfigTransportClient.java
- client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingMaintainService.java
- client/src/main/java/com/alibaba/nacos/client/naming/remote/NamingClientProxyDelegate.java
- client/src/main/java/com/alibaba/nacos/client/security/SecurityProxy.java
- client/src/test/java/com/alibaba/nacos/client/security/SecurityProxyTest.java
- plugin/auth/src/main/java/com/alibaba/nacos/plugin/auth/spi/client/AbstractClientAuthService.java
- plugin/auth/src/main/java/com/alibaba/nacos/plugin/auth/spi/client/ClientAuthPluginManager.java
> [ISSUE #12257] client auth plugin support refreshing server list

- README.md
- auth/src/main/java/com/alibaba/nacos/auth/config/AuthErrorCode.java
- config/src/test/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalConfigInfoPersistServiceImplTest.java
- console-ui/src/config.js
- distribution/conf/announcement_en-US.conf
- distribution/conf/announcement_zh-CN.conf
- distribution/conf/console-guide.conf
- plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/token/impl/JwtTokenManager.java
> Use new nacos.io url replace older.

- console-ui/package-lock.json
> Bump console ui dependencies by npm audit.

- naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/NamingMetadataManager.java
- naming/src/test/java/com/alibaba/nacos/naming/core/v2/metadata/NamingMetadataManagerTest.java
> [ISSUE #12970] Fix NamingMetadataManager.removeInstanceMetadata() error

- bootstrap/src/main/java/com/alibaba/nacos/bootstrap/NacosBootstrap.java
- console/src/main/java/com/alibaba/nacos/console/config/NacosConsoleBeanPostProcessorConfiguration.java
- prometheus/src/main/java/com/alibaba/nacos/prometheus/conf/PrometheusSecurityConfiguration.java
- server/src/main/java/com/alibaba/nacos/NacosServerWebApplication.java
- server/src/main/java/com/alibaba/nacos/server/NacosWebBeanPostProcessorConfiguration.java
- server/src/main/resources/nacos-server.properties
- sys/src/main/java/com/alibaba/nacos/sys/env/AbstractNacosDuplicateBeanPostProcessor.java
- sys/src/main/java/com/alibaba/nacos/sys/env/Constants.java
- sys/src/main/java/com/alibaba/nacos/sys/env/NacosDuplicateConfigurationBeanPostProcessor.java
- sys/src/main/java/com/alibaba/nacos/sys/env/NacosDuplicateSpringBeanPostProcessor.java
- sys/src/test/java/com/alibaba/nacos/sys/env/NacosDuplicateConfigurationBeanPostProcessorTest.java
- sys/src/test/java/com/alibaba/nacos/sys/env/NacosDuplicateSpringBeanPostProcessorTest.java
- sys/src/test/java/com/alibaba/nacos/sys/env/mock/MockAutoConfiguration.java
> Enhance to reuse duplicate spring beans to reduce memory usage.

- console/src/main/resources/application.properties
> [ISSUE #13003] 修复单机默认配置启动时，未使用derby数据库问题

- console/src/main/java/com/alibaba/nacos/console/handler/impl/inner/EnabledInnerHandler.java
- console/src/main/java/com/alibaba/nacos/console/handler/impl/inner/HealthInnerHandler.java
- console/src/main/java/com/alibaba/nacos/console/handler/impl/inner/ServerStateInnerHandler.java
- console/src/main/java/com/alibaba/nacos/console/handler/impl/inner/config/ConfigInnerHandler.java
- console/src/main/java/com/alibaba/nacos/console/handler/impl/inner/config/HistoryInnerHandler.java
- console/src/main/java/com/alibaba/nacos/console/handler/impl/inner/core/ClusterInnerHandler.java
- console/src/main/java/com/alibaba/nacos/console/handler/impl/inner/core/NamespaceInnerHandler.java
- console/src/main/java/com/alibaba/nacos/console/handler/impl/inner/naming/InstanceInnerHandler.java
- console/src/main/java/com/alibaba/nacos/console/handler/impl/inner/naming/ServiceInnerHandler.java
- console/src/main/java/com/alibaba/nacos/console/handler/impl/remote/EnabledRemoteHandler.java
- console/src/main/java/com/alibaba/nacos/console/proxy/HealthProxy.java
- console/src/main/java/com/alibaba/nacos/console/proxy/ServerStateProxy.java
- console/src/main/java/com/alibaba/nacos/console/proxy/config/ConfigProxy.java
- console/src/main/java/com/alibaba/nacos/console/proxy/config/HistoryProxy.java
- console/src/main/java/com/alibaba/nacos/console/proxy/core/ClusterProxy.java
- console/src/main/java/com/alibaba/nacos/console/proxy/core/NamespaceProxy.java
- console/src/main/java/com/alibaba/nacos/console/proxy/naming/InstanceProxy.java
- console/src/main/java/com/alibaba/nacos/console/proxy/naming/ServiceProxy.java
> V3.0 develop add condition for console request handler

- client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java
- common/src/test/java/com/alibaba/nacos/common/utils/FuzzyGroupKeyPatternTest.java
- config/src/test/java/com/alibaba/nacos/config/server/utils/MD5UtilTest.java
- console/pom.xml
- naming/src/test/java/com/alibaba/nacos/naming/core/v2/index/ClientServiceIndexesManagerTest.java
> Fix running problem after upgrade to spring boot 3

- api/src/main/java/com/alibaba/nacos/api/naming/pojo/ServiceInfo.java
fix comment typo on ServiceInfo(key) constructor
> [ISSUE#13021] fix comment typo on ServiceInfo(key) constructor

- config/src/test/java/com/alibaba/nacos/config/server/service/dump/processor/DumpAllProcessorTest.java
- console-ui/package-lock.json
- naming/src/test/java/com/alibaba/nacos/naming/controllers/ServiceControllerTest.java
- pom.xml
- sys/src/test/java/com/alibaba/nacos/sys/env/EnvUtilTest.java
> Upgrade 2.5.0 and bump console-ui dependencies by npm audix.

- plugin/control/src/main/java/com/alibaba/nacos/plugin/control/connection/ConnectionControlManager.java
> [ISSUE #13038] 修复多个线程同时创建ConnectionManager类的Bean的问题

- naming/src/test/java/com/alibaba/nacos/naming/controllers/v3/ClusterControllerV3Test.java
> Migrate javax.servlet to jakarta.servlet in ClusterControllerV3Test

- api/pom.xml
- client/pom.xml
- common/pom.xml
- common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClient.java
- config/src/test/java/com/alibaba/nacos/config/server/model/ConfigCachePostProcessorDelegateTest.java
- config/src/test/java/com/alibaba/nacos/config/server/service/ConfigFuzzyWatchContextServiceTest.java
- config/src/test/java/com/alibaba/nacos/config/server/utils/Md5ComparatorDelegateTest.java
- core/src/test/java/com/alibaba/nacos/core/controller/compatibility/ApiCompatibilityConfigTest.java
- logger-adapter-impl/log4j2-adapter/pom.xml
- logger-adapter-impl/logback-adapter-12/pom.xml
- plugin/auth/pom.xml
- plugin/encryption/pom.xml
- pom.xml
> Specified nacos-client and dependencies to java 8.

- console/src/main/java/com/alibaba/nacos/console/controller/v3/config/ConsoleConfigController.java
- console/src/main/java/com/alibaba/nacos/console/handler/config/ConfigHandler.java
- console/src/main/java/com/alibaba/nacos/console/handler/impl/inner/config/ConfigInnerHandler.java
- console/src/main/java/com/alibaba/nacos/console/proxy/config/ConfigProxy.java
- console/src/test/java/com/alibaba/nacos/console/controller/v3/config/ConsoleConfigControllerTest.java
> [ISSUE #13057] 修复配置管理发布Beta然后停止Beta，client端就监听不到后续的配置变化问题

- config/pom.xml
> :heavy_minus_sign: Remove duplicate dependencies com.alibaba.nacos:nacos-control-plugin

- console/src/main/java/com/alibaba/nacos/console/config/ConsoleWebConfig.java
- console/src/main/java/com/alibaba/nacos/console/handler/config/ConfigHandler.java
- plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/configuration/NacosAuthPluginWebConfig.java
- prometheus/src/main/java/com/alibaba/nacos/prometheus/conf/PrometheusSecurityConfiguration.java
- prometheus/src/main/java/com/alibaba/nacos/prometheus/filter/PrometheusAuthFilter.java
> [ISSUE#13067] Fix prometheus auth manager problem.

- console/src/main/java/com/alibaba/nacos/console/cluster/RemoteServerMemberManager.java
- console/src/main/java/com/alibaba/nacos/console/handler/impl/remote/core/ClusterRemoteHandler.java
- core/src/main/java/com/alibaba/nacos/core/cluster/MemberLookup.java
- core/src/main/java/com/alibaba/nacos/core/cluster/NacosMemberManager.java
- core/src/main/java/com/alibaba/nacos/core/cluster/ServerMemberManager.java
- core/src/main/java/com/alibaba/nacos/core/cluster/lookup/AbstractMemberLookup.java
- core/src/main/java/com/alibaba/nacos/core/cluster/lookup/AddressServerMemberLookup.java
- core/src/main/java/com/alibaba/nacos/core/cluster/lookup/FileConfigMemberLookup.java
- core/src/main/java/com/alibaba/nacos/core/cluster/lookup/LookupFactory.java
- core/src/main/java/com/alibaba/nacos/core/cluster/lookup/StandaloneMemberLookup.java
- Support start up with console only mode: step3 - console read cluster conf to set remote server members.
XXXX
> Support nacos console deployment independent: PR 2

- naming/src/main/java/com/alibaba/nacos/naming/remote/rpc/handler/DistroDataRequestHandler.java
See [#12991](https://github.com/alibaba/nacos/issues/12991#issue-2758576289)
Set the correct result status code (`ResponseCode.FAIL`) for `Distro` protocol data processing exceptions.
> [ISSUE #12991] Set the correct result status code for Distro protocol data processing exceptions.

- config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigController.java
- config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigPublishRequestHandler.java
- config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigQueryRequestHandler.java
- config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigRemoveRequestHandler.java
- config/src/test/java/com/alibaba/nacos/config/server/remote/ConfigQueryRequestHandlerTest.java
fix bug of missing tansformation from public namespace to blank namespace in config center, including ConfigController,ConfigQueryRequestHandler,ConfigPublishRequestHandler and ConfigRemoveRequestHandler
XX
XXXX
* [*] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful …
> [ISSUE #13093]fix bug of missing tansformation of namespace in config center 

- config/src/main/java/com/alibaba/nacos/config/server/service/query/DefaultChainRequestExtractor.java
- config/src/test/java/com/alibaba/nacos/config/server/service/query/DefaultChainRequestExtractorTest.java
it is related to #13090 
XX
XXXX
> [ISSUE#13090] Compatible with v2 openapi to query configuration.

- core/src/main/java/com/alibaba/nacos/core/monitor/topn/TopNConfig.java
> [ISSUE #13106] Should resetConfig() in the constructor of TopNConfig.java

- console/src/main/resources/application.properties
- core/src/main/java/com/alibaba/nacos/core/remote/ConnectionMeta.java
- core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcBiStreamRequestAcceptor.java
- core/src/main/java/com/alibaba/nacos/core/remote/grpc/negotiator/tls/OptionalTlsProtocolNegotiator.java
add tls protected field to connection meta
> add tls protected field to connection meta

- client/pom.xml
- client/src/test/java/com/alibaba/nacos/client/config/filter/impl/ConfigEncryptionFilterTest1.java
> [client][dep] remove common-codec

- client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingService.java
- client/src/main/java/com/alibaba/nacos/client/naming/selector/NamingListenerInvoker.java
- client/src/main/java/com/alibaba/nacos/client/selector/AbstractSelectorWrapper.java
- client/src/main/java/com/alibaba/nacos/client/selector/ListenerInvoker.java
- client/src/test/java/com/alibaba/nacos/client/naming/NacosNamingServiceTest.java
- pom.xml
> Support callback service listeners anyway when listeners added.

- client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java
- client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc/NamingGrpcClientProxy.java
- client/src/test/java/com/alibaba/nacos/client/config/impl/ClientWorkerTest.java
- common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClientConfigFactory.java
- common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClientFactory.java
- common/src/main/java/com/alibaba/nacos/common/remote/client/RpcConfigFactory.java
- common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/DefaultGrpcClientConfig.java
- common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClientConfig.java
- common/src/test/java/com/alibaba/nacos/common/remote/client/RpcClientConfigFactoryTest.java
- common/src/test/java/com/alibaba/nacos/common/remote/client/RpcClientFactoryTest.java
> [ISSUE#13129] Optimize SDK connection parameter settings.

- client/src/test/java/com/alibaba/nacos/client/config/NacosConfigServiceTest.java
> add test coverage

- client-basic/src/main/java/com/alibaba/nacos/client/auth/impl/process/HttpLoginProcessor.java
> [ISSUE #13143] change the client login url

- config/src/main/java/com/alibaba/nacos/config/server/controller/v3/ConfigControllerV3.java
- config/src/main/java/com/alibaba/nacos/config/server/controller/v3/ConfigOpsControllerV3.java
- console/src/main/java/com/alibaba/nacos/console/handler/impl/remote/config/ConfigRemoteHandler.java
- maintainer-client/src/main/java/com/alibaba/nacos/maintainer/client/config/BetaConfigMaintainerService.java
- maintainer-client/src/main/java/com/alibaba/nacos/maintainer/client/config/ConfigHistoryMaintainerService.java
- maintainer-client/src/main/java/com/alibaba/nacos/maintainer/client/config/ConfigMaintainerService.java
- maintainer-client/src/main/java/com/alibaba/nacos/maintainer/client/config/ConfigOpsMaintainerService.java
- maintainer-client/src/main/java/com/alibaba/nacos/maintainer/client/config/NacosConfigMaintainerServiceImpl.java
- maintainer-client/src/main/java/com/alibaba/nacos/maintainer/client/naming/NamingMaintainerService.java
- maintainer-client/src/test/java/com/alibaba/nacos/maintainer/client/config/NacosConfigMaintainerServiceImplTest.java
> Enhance maintainer client config interface define.

- common/src/main/java/com/alibaba/nacos/common/utils/NamespaceUtil.java
- common/src/test/java/com/alibaba/nacos/common/utils/NamespaceUtilTest.java
- config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigController.java
- config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigServletInner.java
- config/src/main/java/com/alibaba/nacos/config/server/model/ConfigListenState.java
- config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigChangeBatchListenRequestHandler.java
- config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigChangeListenContext.java
- config/src/main/java/com/alibaba/nacos/config/server/remote/RpcConfigChangeNotifier.java
- config/src/main/java/com/alibaba/nacos/config/server/service/LongPollingService.java
- config/src/main/java/com/alibaba/nacos/config/server/utils/MD5Util.java
- config/src/main/java/com/alibaba/nacos/config/server/utils/Md5Comparator.java
- config/src/main/java/com/alibaba/nacos/config/server/utils/Md5ComparatorDelegate.java
- config/src/main/java/com/alibaba/nacos/config/server/utils/NacosMd5Comparator.java
- config/src/test/java/com/alibaba/nacos/config/server/controller/ConfigServletInnerTest.java
- config/src/test/java/com/alibaba/nacos/config/server/remote/ConfigChangeListenContextTest.java
- config/src/test/java/com/alibaba/nacos/config/server/service/LongPollingServiceTest.java
- config/src/test/java/com/alibaba/nacos/config/server/utils/MD5UtilTest.java
- config/src/test/java/com/alibaba/nacos/config/server/utils/Md5ComparatorDelegateTest.java
- config/src/test/java/com/alibaba/nacos/config/server/utils/NacosMd5ComparatorTest.java
XXXXX
XX
XXXX
* [*] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [*] Write necessary unit-test to verify your logic …
> [ISSUE #13140]Config change notify namespace support

- api/src/main/java/com/alibaba/nacos/api/ability/constant/AbilityKey.java
- api/src/main/java/com/alibaba/nacos/api/ability/register/impl/SdkClientAbilities.java
- api/src/main/java/com/alibaba/nacos/api/ability/register/impl/ServerAbilities.java
- api/src/main/java/com/alibaba/nacos/api/exception/NacosException.java
- api/src/main/java/com/alibaba/nacos/api/lock/LockService.java
- api/src/test/java/com/alibaba/nacos/api/ability/register/impl/ServerAbilitiesTest.java
- api/src/test/java/com/alibaba/nacos/api/remote/request/RequestMetaTest.java
- api/src/test/java/com/alibaba/nacos/api/remote/request/SetupAckRequestTest.java
- api/src/test/java/com/alibaba/nacos/api/utils/AbilityKeyTest.java
- client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java
- client/src/main/java/com/alibaba/nacos/client/config/impl/ConfigFuzzyWatchGroupKeyHolder.java
- client/src/main/java/com/alibaba/nacos/client/lock/NacosLockService.java
- client/src/main/java/com/alibaba/nacos/client/lock/remote/grpc/LockGrpcClient.java
- client/src/main/java/com/alibaba/nacos/client/naming/cache/NamingFuzzyWatchServiceListHolder.java
- client/src/main/java/com/alibaba/nacos/client/naming/remote/NamingClientProxyDelegate.java
- client/src/test/java/com/alibaba/nacos/client/ability/AbilityTest.java
- client/src/test/java/com/alibaba/nacos/client/naming/remote/NamingClientProxyDelegateTest.java
- client/src/test/java/com/alibaba/nacos/client/naming/remote/gprc/NamingGrpcClientProxyTest.java
- common/src/test/java/com/alibaba/nacos/common/ability/AbstractAbilityControlManagerTest.java
- common/src/test/java/com/alibaba/nacos/common/ability/discover/HigherMockAbilityManager.java
- common/src/test/java/com/alibaba/nacos/common/ability/discover/LowerMockAbilityManager.java
- common/src/test/java/com/alibaba/nacos/common/remote/client/ConnectionTest.java
- common/src/test/java/com/alibaba/nacos/common/remote/client/RpcClientTest.java
- config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigChangeListenContext.java
- config/src/main/java/com/alibaba/nacos/config/server/utils/NacosMd5Comparator.java
- core/src/test/java/com/alibaba/nacos/core/ability/AbilityControlManagerTest.java
- core/src/test/java/com/alibaba/nacos/core/ability/config/AbilityConfigsTest.java
- core/src/test/java/com/alibaba/nacos/core/ability/config/TestAbilityConfig.java
- test/core-test/src/test/java/com/alibaba/nacos/test/ability/AbilityDiscovery.java
- test/core-test/src/test/java/com/alibaba/nacos/test/ability/component/TestServerAbilityControlManager.java
> Client judge whether server support target ability before actual do request for fuzzy watch and distributed lock.

- client-basic/src/main/java/com/alibaba/nacos/client/auth/impl/process/HttpLoginProcessor.java
> [ISSUE #13143] client support both v1 and v3 login url.

- config/src/main/java/com/alibaba/nacos/config/server/controller/v3/ConfigControllerV3.java
- console/src/main/java/com/alibaba/nacos/console/handler/impl/inner/config/ConfigInnerHandler.java
> [ISSUE #13160] Fix missing default namespace check when cloning/importing configuration.

- console/src/main/java/com/alibaba/nacos/console/proxy/core/ClusterProxy.java
- distribution/bin/startup.cmd
- distribution/bin/startup.sh
Enhance start up script to check required configuration and can setting them.
- Enhance startup.sh
- Enhance startup.cmd 
XXXX
> Enhance start up script to check required configuration and can setting them.

- pom.xml
> Upgrade 2.5.1.

- config/src/main/java/com/alibaba/nacos/config/server/controller/v3/MetricsControllerV3.java
- config/src/main/java/com/alibaba/nacos/config/server/model/capacity/GroupCapacity.java
- config/src/main/java/com/alibaba/nacos/config/server/model/capacity/NamespaceCapacity.java
- config/src/main/java/com/alibaba/nacos/config/server/service/capacity/CapacityService.java
- config/src/main/java/com/alibaba/nacos/config/server/service/capacity/GroupCapacityPersistService.java
- config/src/main/java/com/alibaba/nacos/config/server/service/capacity/TenantCapacityPersistService.java
- config/src/test/java/com/alibaba/nacos/config/server/aspect/CapacityManagementAspectTest.java
- config/src/test/java/com/alibaba/nacos/config/server/service/NamespaceConfigInfoServiceTest.java
- config/src/test/java/com/alibaba/nacos/config/server/service/capacity/CapacityServiceTest.java
- config/src/test/java/com/alibaba/nacos/config/server/service/capacity/GroupCapacityPersistServiceTest.java
- config/src/test/java/com/alibaba/nacos/config/server/service/capacity/TenantCapacityPersistServiceTest.java
- core/src/main/java/com/alibaba/nacos/core/controller/v3/NacosClusterControllerV3.java
> Fix some admin api usage problem.

- console/src/main/java/com/alibaba/nacos/console/handler/impl/remote/NacosMaintainerClientHolder.java
> [ISSUE #13177] Fix missing subscriber for MembersChangeEvent.

- config/src/main/java/com/alibaba/nacos/config/server/service/dump/DumpService.java
- config/src/main/java/com/alibaba/nacos/config/server/service/dump/processor/DumpAllGrayProcessor.java
- config/src/test/java/com/alibaba/nacos/config/server/service/dump/processor/DumpAllGrayProcessorTest.java
> [ISSUE#13171] Fix the full regular dump for gray configuration.

- config/src/main/java/com/alibaba/nacos/config/server/configuration/ConfigCompatibleConfig.java
- config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigChangeClusterSyncRequestHandler.java
- config/src/main/java/com/alibaba/nacos/config/server/service/ConfigMigrateService.java
- config/src/main/java/com/alibaba/nacos/config/server/utils/PropertyUtil.java
Optimize the Namespace Compatible Mode switch, allowing it to be dynamically enabled or disabled via application.properties.
XX
XXXX
* [*] Write a pull request description that is detailed …
> Optimize the Namespace Compatible Mode switch

- config/src/main/java/com/alibaba/nacos/config/server/configuration/ConfigCompatibleConfig.java
- config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigChangeClusterSyncRequestHandler.java
- config/src/main/java/com/alibaba/nacos/config/server/service/ConfigMigrateService.java
- config/src/main/java/com/alibaba/nacos/config/server/service/dump/processor/DumpAllProcessor.java
- config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedConfigMigratePersistServiceImpl.java
- config/src/main/java/com/alibaba/nacos/config/server/utils/PropertyUtil.java
Fix DumpService bug and add log for configMigrateService
XX
XXXX
* [*] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [*] …
> Fix DumpService bug and add log for configMigrateService

- config/src/main/java/com/alibaba/nacos/config/server/controller/v3/MetricsControllerV3.java
- config/src/main/java/com/alibaba/nacos/config/server/service/ConfigMigrateService.java
Fix configMigrateService code style 
XX
XXXX
> Fix configMigrateService code style 

- config/src/main/java/com/alibaba/nacos/config/server/model/form/ConfigFormV3.java
- config/src/test/java/com/alibaba/nacos/config/server/controller/v3/MetricControllerV3Test.java
> V3.0 develop fix test

- config/src/main/java/com/alibaba/nacos/config/server/configuration/ConfigCompatibleConfig.java
- config/src/main/java/com/alibaba/nacos/config/server/service/ConfigMigrateService.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/derby/ConfigMigrateMapperByDerby.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/ConfigMigrateMapper.java
> [ISSUE #13200] Fix ConfigMigrateService derby bug

- style/nacos-code-style-for-idea.xml
fix a typo in code-style.xml
Not applicable.
Not applicable.
> doc: fix a typo in code-style file

- console/src/main/java/com/alibaba/nacos/console/proxy/naming/ServiceProxy.java
> Optimize the code.

- console/src/main/java/com/alibaba/nacos/console/handler/impl/inner/naming/InstanceInnerHandler.java
- core/src/main/java/com/alibaba/nacos/core/controller/v3/NacosClusterControllerV3.java
- core/src/main/java/com/alibaba/nacos/core/controller/v3/ServerLoaderControllerV3.java
- core/src/main/java/com/alibaba/nacos/core/service/NacosServerLoaderService.java
- core/src/test/java/com/alibaba/nacos/core/controller/v3/ServerLoaderControllerV3Test.java
- core/src/test/java/com/alibaba/nacos/core/service/NacosServerLoaderServiceTest.java
- k8s-sync/src/main/java/com/alibaba/nacos/k8s/sync/K8sSyncServer.java
- maintainer-client/src/main/java/com/alibaba/nacos/maintainer/client/core/AbstractCoreMaintainerService.java
- naming/src/main/java/com/alibaba/nacos/naming/controllers/v2/InstanceControllerV2.java
- naming/src/main/java/com/alibaba/nacos/naming/controllers/v3/HealthControllerV3.java
- naming/src/main/java/com/alibaba/nacos/naming/controllers/v3/InstanceControllerV3.java
- naming/src/main/java/com/alibaba/nacos/naming/core/HealthOperator.java
- naming/src/main/java/com/alibaba/nacos/naming/core/HealthOperatorV2Impl.java
- naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperator.java
- naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperatorClientImpl.java
- naming/src/main/java/com/alibaba/nacos/naming/core/ServiceOperator.java
- naming/src/main/java/com/alibaba/nacos/naming/core/ServiceOperatorV2Impl.java
- naming/src/main/java/com/alibaba/nacos/naming/core/SubscribeManager.java
- naming/src/main/java/com/alibaba/nacos/naming/pojo/InstanceOperationInfo.java
- naming/src/test/java/com/alibaba/nacos/naming/controllers/v3/HealthControllerV3Test.java
- naming/src/test/java/com/alibaba/nacos/naming/controllers/v3/InstanceControllerV3Test.java
- naming/src/test/java/com/alibaba/nacos/naming/core/InstanceOperatorClientImplTest.java
- server/src/main/resources/nacos-server.properties
> Do some refactor for 3.0 api

- api/src/main/java/com/alibaba/nacos/api/PropertyKeyConst.java
- client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java
- client/src/main/java/com/alibaba/nacos/client/naming/cache/ServiceInfoHolder.java
- client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc/NamingGrpcClientProxy.java
- client/src/main/java/com/alibaba/nacos/client/naming/remote/http/NamingHttpClientProxy.java
- client/src/test/java/com/alibaba/nacos/client/config/impl/ClientWorkerTest.java
- client/src/test/java/com/alibaba/nacos/client/naming/cache/ServiceInfoHolderTest.java
> [ISSUE#13183] Add client metrics switch.

- auth/src/main/java/com/alibaba/nacos/auth/config/NacosAuthConfigHolder.java
- auth/src/test/java/com/alibaba/nacos/auth/config/NacosAuthConfigHolderTest.java
- console/src/main/java/com/alibaba/nacos/console/controller/v3/core/ConsoleNamespaceController.java
- console/src/main/java/com/alibaba/nacos/console/controller/v3/naming/ConsoleServiceController.java
- console/src/main/java/com/alibaba/nacos/console/handler/impl/inner/core/NamespaceInnerHandler.java
- core/src/main/java/com/alibaba/nacos/core/auth/AbstractWebAuthFilter.java
- core/src/main/java/com/alibaba/nacos/core/service/NamespaceOperationService.java
- core/src/test/java/com/alibaba/nacos/core/auth/AuthFilterTest.java
- plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/controller/UserController.java
- plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/controller/v3/UserControllerV3.java
- plugin/auth/src/main/java/com/alibaba/nacos/plugin/auth/constant/Constants.java
For #12953
Change some api from public to identity check only（no permission check or check in api inner).
- list namespace list API
- check namespace exist API
- list service selector typs API
- update user password API (inner check permission)
XXXX
> Change some console api from public api to identity check only api.

- client/src/main/java/com/alibaba/nacos/client/naming/remote/http/NamingHttpClientProxy.java
- config/src/main/java/com/alibaba/nacos/config/server/constant/Constants.java
- config/src/main/java/com/alibaba/nacos/config/server/controller/CommunicationController.java
- config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigController.java
- config/src/main/java/com/alibaba/nacos/config/server/controller/v3/ConfigOpenApiController.java
- config/src/main/java/com/alibaba/nacos/config/server/service/ConfigSubService.java
- config/src/test/java/com/alibaba/nacos/config/server/controller/v3/ConfigOpenApiControllerTest.java
- naming/src/main/java/com/alibaba/nacos/naming/controllers/InstanceController.java
- naming/src/main/java/com/alibaba/nacos/naming/controllers/OperatorController.java
- naming/src/main/java/com/alibaba/nacos/naming/controllers/ServiceController.java
- naming/src/main/java/com/alibaba/nacos/naming/controllers/v3/InstanceControllerV3.java
- naming/src/main/java/com/alibaba/nacos/naming/controllers/v3/InstanceOpenApiController.java
- naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperatorClientImpl.java
- naming/src/main/java/com/alibaba/nacos/naming/misc/UtilsAndCommons.java
- naming/src/main/java/com/alibaba/nacos/naming/utils/InstanceUtil.java
- naming/src/main/java/com/alibaba/nacos/naming/utils/NamingRequestUtil.java
- naming/src/test/java/com/alibaba/nacos/naming/controllers/v3/InstanceOpenApiControllerTest.java
Add some client used http open api.
XXXX
> V3.0 develop client openapi

- config/src/main/java/com/alibaba/nacos/config/server/controller/v3/ConfigControllerV3.java
- core/src/main/java/com/alibaba/nacos/core/controller/v3/NacosClusterControllerV3.java
> Remove /node/self/health API & Fix stop beta action type.

- config/src/main/java/com/alibaba/nacos/config/server/controller/v3/ConfigControllerV3.java
- core/src/main/java/com/alibaba/nacos/core/controller/v3/NacosClusterControllerV3.java
> V3.0 develop swagger generator

- ai/pom.xml
- ai/src/main/java/com/alibaba/nacos/ai/constant/Constants.java
- ai/src/main/java/com/alibaba/nacos/ai/controller/McpController.java
- ai/src/main/java/com/alibaba/nacos/ai/form/mcp/McpDetailForm.java
- ai/src/main/java/com/alibaba/nacos/ai/form/mcp/McpForm.java
- ai/src/main/java/com/alibaba/nacos/ai/form/mcp/McpListForm.java
- ai/src/main/java/com/alibaba/nacos/ai/service/McpEndpointOperationService.java
- ai/src/main/java/com/alibaba/nacos/ai/service/McpOperationService.java
- ai/src/main/java/com/alibaba/nacos/ai/service/McpServerOperationService.java
- ai/src/main/java/com/alibaba/nacos/ai/service/McpToolOperationService.java
- api/src/main/java/com/alibaba/nacos/api/ai/constant/AiConstants.java
- api/src/main/java/com/alibaba/nacos/api/ai/model/mcp/McpCapability.java
- api/src/main/java/com/alibaba/nacos/api/ai/model/mcp/McpEndpointInfo.java
- api/src/main/java/com/alibaba/nacos/api/ai/model/mcp/McpEndpointSpec.java
- api/src/main/java/com/alibaba/nacos/api/ai/model/mcp/McpServerBasicInfo.java
- api/src/main/java/com/alibaba/nacos/api/ai/model/mcp/McpServerDetailInfo.java
- api/src/main/java/com/alibaba/nacos/api/ai/model/mcp/McpServerRemoteServiceConfig.java
- api/src/main/java/com/alibaba/nacos/api/ai/model/mcp/McpServiceRef.java
- api/src/main/java/com/alibaba/nacos/api/ai/model/mcp/McpTool.java
- api/src/main/java/com/alibaba/nacos/api/ai/model/mcp/McpToolMeta.java
- auth/src/main/java/com/alibaba/nacos/auth/HttpProtocolAuthService.java
- auth/src/main/java/com/alibaba/nacos/auth/parser/http/AiHttpResourceParser.java
- console/pom.xml
- console/src/main/java/com/alibaba/nacos/console/controller/v3/ai/ConsoleMcpController.java
- console/src/main/java/com/alibaba/nacos/console/handler/ai/McpHandler.java
- console/src/main/java/com/alibaba/nacos/console/handler/impl/inner/ai/McpInnerHandler.java
- console/src/main/java/com/alibaba/nacos/console/handler/impl/remote/ai/McpRemoteHandler.java
- console/src/main/java/com/alibaba/nacos/console/proxy/ai/McpProxy.java
- naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperator.java
- pom.xml
For #13246.
- Add MCP(Model Context Protocol) relative Models.
- Support basic MCP(Model Context Protocol) operation console apis to Nacos.
> [ISSUE#13246]  Add MCP(Model Context Protocol) Server And Support basic MCP(Model Context Protocol) operation console apis to Nacos.

- config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigController.java
- config/src/main/java/com/alibaba/nacos/config/server/model/ConfigMetadata.java
- config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedConfigInfoPersistServiceImpl.java
- config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalConfigInfoPersistServiceImpl.java
- config/src/main/java/com/alibaba/nacos/config/server/utils/YamlParserUtil.java
> [ISSUE#13229] Fix the config tag being lost during configuration export.

- plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/roles/AbstractCheckedRoleService.java
> fix public namespace auth

- ai/src/main/java/com/alibaba/nacos/ai/constant/Constants.java
- ai/src/main/java/com/alibaba/nacos/ai/service/McpToolOperationService.java
- api/src/main/java/com/alibaba/nacos/api/ai/constant/AiConstants.java
- api/src/main/java/com/alibaba/nacos/api/ai/model/mcp/McpEndpointSpec.java
- api/src/main/java/com/alibaba/nacos/api/ai/model/mcp/McpServerBasicInfo.java
- console/src/main/java/com/alibaba/nacos/console/config/ConsoleWebConfig.java
- console/src/main/java/com/alibaba/nacos/console/handler/impl/remote/NacosMaintainerClientHolder.java
- console/src/main/java/com/alibaba/nacos/console/handler/impl/remote/ai/McpRemoteHandler.java
- core/pom.xml
- core/src/main/java/com/alibaba/nacos/core/controller/v3/NamespaceControllerV3.java
- core/src/main/java/com/alibaba/nacos/core/exception/NacosApiExceptionHandler.java
- core/src/test/java/com/alibaba/nacos/core/CoreUtApplication.java
- core/src/test/java/com/alibaba/nacos/core/controller/v3/NamespaceControllerV3Test.java
- core/src/test/java/com/alibaba/nacos/core/exception/NacosApiExceptionHandlerTest.java
- maintainer-client/src/main/java/com/alibaba/nacos/maintainer/client/ai/AiMaintainerFactory.java
- maintainer-client/src/main/java/com/alibaba/nacos/maintainer/client/ai/AiMaintainerService.java
- maintainer-client/src/main/java/com/alibaba/nacos/maintainer/client/ai/McpMaintainerService.java
- maintainer-client/src/main/java/com/alibaba/nacos/maintainer/client/ai/NacosAiMaintainerServiceImpl.java
- maintainer-client/src/main/java/com/alibaba/nacos/maintainer/client/constants/Constants.java
> Add mcp api for maintainer sdk & support console deploy mode.

- ai/src/main/java/com/alibaba/nacos/ai/service/McpDefaultNamespaceService.java
- core/src/main/java/com/alibaba/nacos/core/namespace/model/NamespaceTypeEnum.java
- core/src/main/java/com/alibaba/nacos/core/service/NamespaceOperationService.java
- plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/roles/NacosRoleServiceRemoteImpl.java
- plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/users/NacosUserServiceRemoteImpl.java
> [ISSUE#13246] Add nacos-default-mcp namespace into persistence.

- config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigController.java
> [ISSUE #12484] fix ConfigController.stopBeta srcUser param is null

- .github/workflows/pr-comment.yml
> Update pr-comment.yml run on ubuntu-latest

- console-ui/src/components/NameSpaceList/NameSpaceList.js
- console-ui/src/layouts/MainLayout.js
- console-ui/src/layouts/menu.js
- console-ui/src/locales/zh-CN.js
- console-ui/src/pages/AI/McpDetail/CreateTools/DeleteTool.js
- console-ui/src/pages/AI/McpDetail/CreateTools/index.js
- console-ui/src/pages/AI/McpDetail/McpDetail.js
- console-ui/src/pages/AI/McpManagement/McpManagement.js
- console-ui/src/pages/AI/NewMcpServer/NewMcpServer.js
> feat: 更新中文翻译，调整服务类型为协议类型；移除冗余后端协议字段；优化AI页面的命名空间列表和跳转逻辑

- api/src/main/java/com/alibaba/nacos/api/ai/model/mcp/McpServerBasicInfo.java
- api/src/main/java/com/alibaba/nacos/api/ai/model/mcp/McpToolMeta.java
- client/src/main/java/com/alibaba/nacos/client/naming/remote/http/NamingHttpClientProxy.java
- client/src/test/java/com/alibaba/nacos/client/config/impl/ClientWorkerTest.java
- client/src/test/java/com/alibaba/nacos/client/naming/remote/http/NamingHttpClientProxyTest.java
- config/src/test/java/com/alibaba/nacos/config/server/service/dump/processor/DumpAllGrayProcessorTest.java
- console/src/test/java/com/alibaba/nacos/console/cluster/RemoteServerMemberManagerTest.java
- console/src/test/java/com/alibaba/nacos/console/config/ConsoleWebConfigTest.java
- console/src/test/java/com/alibaba/nacos/console/handler/impl/remote/ConsoleMaintainerClientAuthPluginTest.java
- console/src/test/java/com/alibaba/nacos/console/handler/impl/remote/NacosMaintainerClientHolderTest.java
- console/src/test/java/com/alibaba/nacos/console/handler/impl/remote/ServerStateRemoteHandlerTest.java
- plugin/datasource/src/test/java/com/alibaba/nacos/plugin/datasource/impl/derby/ConfigInfoMapperByDerbyTest.java
- plugin/datasource/src/test/java/com/alibaba/nacos/plugin/datasource/impl/mysql/ConfigInfoMapperByMySqlTest.java
> Fix unit test

- .github/workflows/ci.yml
- .github/workflows/it.yml
- .github/workflows/pr-ci.yml
- .github/workflows/push-ci.yaml
- pom.xml
> Fix test not generate jacoco coverage report.

- console-ui/src/locales/zh-CN.js
- console-ui/src/pages/AI/NewMcpServer/NewMcpServer.js
> 更新中文语言包，添加服务引用和导出路径描述；调整新建MCP服务页面的表单项和默认行数

- console-ui/src/pages/AI/McpDetail/CreateTools/DeleteTool.js
> Fix not close dialog when delete tool finished.

- console-ui/src/pages/AI/McpDetail/McpDetail.js
- console-ui/src/pages/ServiceManagement/ServiceDetail/InstanceTable.js
- console-ui/src/pages/ServiceManagement/ServiceDetail/ServiceDetail.js
Fix: fix jump from mcp detail to service detail error
XX
XXXX
> Fix: fix jump from mcp detail to service detail error

- .github/workflows/ci.yml
> use spotbugs command replace findbugs command

- auth/src/test/java/com/alibaba/nacos/auth/serveridentity/ServerIdentityCheckerHolderTest.java
- client/src/main/java/com/alibaba/nacos/client/lock/core/NLock.java
- client/src/main/java/com/alibaba/nacos/client/naming/backups/FailoverReactor.java
- client/src/main/java/com/alibaba/nacos/client/naming/event/NamingFuzzyWatchLoadEvent.java
- client/src/test/java/com/alibaba/nacos/client/lock/NacosLockServiceTest.java
- client/src/test/java/com/alibaba/nacos/client/lock/remote/grpc/LockGrpcClientTest.java
- client/src/test/java/com/alibaba/nacos/client/naming/backups/FailoverReactorTest.java
- client/src/test/java/com/alibaba/nacos/client/naming/backups/datasource/DiskFailoverDataSourceTest.java
- client/src/test/java/com/alibaba/nacos/client/naming/selector/NamingListenerInvokerTest.java
- client/src/test/java/com/alibaba/nacos/client/security/SecurityProxyTest.java
- client/src/test/java/com/alibaba/nacos/client/selector/AbstractSelectorWrapperTest.java
- common/src/main/java/com/alibaba/nacos/common/model/RestResult.java
- maintainer-client/src/main/java/com/alibaba/nacos/maintainer/client/address/DefaultServerListManager.java
- maintainer-client/src/main/java/com/alibaba/nacos/maintainer/client/ai/McpMaintainerService.java
- maintainer-client/src/main/java/com/alibaba/nacos/maintainer/client/model/HttpRequest.java
- maintainer-client/src/main/java/com/alibaba/nacos/maintainer/client/remote/ClientHttpProxy.java
- maintainer-client/src/main/java/com/alibaba/nacos/maintainer/client/remote/HttpClientManager.java
- maintainer-client/src/test/java/com/alibaba/nacos/maintainer/client/address/DefaultServerListManagerTest.java
- maintainer-client/src/test/java/com/alibaba/nacos/maintainer/client/ai/AiMaintainerFactoryTest.java
- maintainer-client/src/test/java/com/alibaba/nacos/maintainer/client/ai/NacosAiMaintainerServiceImplTest.java
- maintainer-client/src/test/java/com/alibaba/nacos/maintainer/client/config/NacosConfigMaintainerServiceImplTest.java
- maintainer-client/src/test/java/com/alibaba/nacos/maintainer/client/core/AbstractCoreMaintainerServiceTest.java
- maintainer-client/src/test/java/com/alibaba/nacos/maintainer/client/model/HttpRequestTest.java
- maintainer-client/src/test/java/com/alibaba/nacos/maintainer/client/naming/NacosNamingMaintainerServiceImplTest.java
- maintainer-client/src/test/java/com/alibaba/nacos/maintainer/client/remote/ClientHttpProxyTest.java
- maintainer-client/src/test/java/com/alibaba/nacos/maintainer/client/remote/HttpClientManagerTest.java
- maintainer-client/src/test/java/com/alibaba/nacos/maintainer/client/utils/ParamUtilTest.java
> Upstream develop add ut

- console-ui/src/pages/AI/NewMcpServer/NewMcpServer.js
[issue #13365] fix mcp server group error
XX
XXXX
> [fix] fix mcp server group error

- console-ui/src/index.js
The code runs normally
The code runs normally
> Fix capitalization issue

- distribution/bin/startup.cmd
as this issue mentioned https://github.com/alibaba/nacos/issues/13335  the windows startup.cmd，even if you have value for the following three config
`
nacos.core.auth.server.identity.key=gdgsgsdg
nacos.core.auth.server.identity.value=dgsgeg
nacos.core.auth.plugin.nacos.token.secret.key=gegegs
`
when execute startup.cmd, it also need user reinput the three config. 
so  when user not give value to the three configs value, remind user reinput them, if user has configed them in application.properties, use them directly.
enhance logic for no need re-input config in windows
this change is only for windows startup.cmd, not modify any logic in nacos core logic.
Follow this checklist to help us incorporate your contribution …
> [ISSUE #13335]fix the windows startup.cmd

- bootstrap/src/main/resources/application.properties
- config/pom.xml
- config/src/test/java/com/alibaba/nacos/config/server/service/dump/processor/DumpAllGrayProcessorTest.java
- core/pom.xml
- core/src/test/java/com/alibaba/nacos/core/config/AuthModuleStateBuilderTest.java
> [ISSUE#13321] Fix prometheus metrics api can't accept.

- config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedConfigInfoPersistServiceImpl.java
- config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalConfigInfoPersistServiceImpl.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/derby/ConfigInfoTagsRelationMapperByDerby.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/mysql/ConfigTagsRelationMapperByMySql.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/ConfigTagsRelationMapper.java
- plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/ext/WhereBuilder.java
> Support tag fuzzy search 

- plugin/datasource/src/test/java/com/alibaba/nacos/plugin/datasource/impl/derby/ConfigInfoTagsRelationMapperByDerbyTest.java
- plugin/datasource/src/test/java/com/alibaba/nacos/plugin/datasource/impl/mysql/ConfigTagsRelationMapperByMySqlTest.java
> fix V3.0 develop fix tag fuzzy search unit test

- config/src/main/java/com/alibaba/nacos/config/server/utils/MD5Util.java
> fix listen config namespace bug

- ai/src/main/java/com/alibaba/nacos/ai/service/McpServerOperationService.java
- console-ui/src/components/EditorNameSpace/EditorNameSpace.js
- console-ui/src/locales/en-US.js
- console-ui/src/locales/zh-CN.js
- console-ui/src/pages/AI/McpDetail/CreateTools/index.js
- console-ui/src/pages/AI/McpDetail/McpDetail.js
- console-ui/src/pages/AI/McpDetail/ShowTools.js
- console-ui/src/pages/AI/McpManagement/McpManagement.js
- console-ui/src/pages/AI/NewMcpServer/NewMcpServer.js
- console-ui/src/pages/ConfigurationManagement/ConfigEditor/NewConfigEditor.js
Fix Ui Bugs in mcp management.
XX
XXXX
> fix ui bugs

- console-ui/src/pages/AI/NewMcpServer/NewMcpServer.js
更新注册mcp服务Local Server 配置的提示内容
XXXX
> update mcp placeholder #13413

- console-ui/src/pages/AI/McpDetail/CreateTools/index.js
- console-ui/src/pages/AI/NewMcpServer/NewMcpServer.js
Fix ui error when args properties is null.
Support - in mcp serverName
XX
XXXX
> fix null properties error and support - in mcp server name

- .mvn/wrapper/maven-wrapper.properties
- BUILDING
- mvnw
- mvnw.cmd
> :wrench: add mvnw

- ai/src/main/java/com/alibaba/nacos/ai/constant/Constants.java
- ai/src/main/java/com/alibaba/nacos/ai/index/PlainMcpServerIndex.java
- ai/src/main/java/com/alibaba/nacos/ai/model/mcp/McpServerIndexData.java
- ai/src/main/java/com/alibaba/nacos/ai/service/McpServerOperationService.java
- ai/src/main/java/com/alibaba/nacos/ai/service/McpToolOperationService.java
- ai/src/main/java/com/alibaba/nacos/ai/utils/McpConfigUtils.java
- ai/src/main/java/com/alibaba/nacos/ai/utils/McpProtocolUtils.java
- api/src/main/java/com/alibaba/nacos/api/ai/model/mcp/McpServerBasicInfo.java
- console-ui/src/pages/AI/McpDetail/CreateTools/index.js
- console-ui/src/pages/AI/McpDetail/McpDetail.js
- console-ui/src/pages/AI/NewMcpServer/NewMcpServer.js
- maintainer-client/src/main/java/com/alibaba/nacos/maintainer/client/ai/McpMaintainerService.java
Fix ai admin api bugs.
XX
XXXX
> fix ai api bugs

- api/src/main/java/com/alibaba/nacos/api/common/Constants.java
- auth/src/main/java/com/alibaba/nacos/auth/parser/http/ConfigHttpResourceParser.java
- auth/src/test/java/com/alibaba/nacos/auth/HttpProtocolAuthServiceTest.java
- config/src/main/java/com/alibaba/nacos/config/server/controller/v3/ConfigControllerV3.java
- config/src/main/java/com/alibaba/nacos/config/server/controller/v3/HistoryControllerV3.java
- config/src/main/java/com/alibaba/nacos/config/server/controller/v3/ListenerControllerV3.java
- naming/src/main/java/com/alibaba/nacos/naming/controllers/v3/ClientControllerV3.java
- naming/src/main/java/com/alibaba/nacos/naming/controllers/v3/ClusterControllerV3.java
- naming/src/main/java/com/alibaba/nacos/naming/controllers/v3/HealthControllerV3.java
- naming/src/main/java/com/alibaba/nacos/naming/controllers/v3/InstanceControllerV3.java
- naming/src/main/java/com/alibaba/nacos/naming/controllers/v3/ServiceControllerV3.java
For #13445
Change some data relation admin api to normal user access.
So that maintainer client can get and operation data without admin users but with users which has permission.
XX
XXXX
> [ISSUE#13445] Change some data relation admin api to normal user access.

- client-basic/src/main/java/com/alibaba/nacos/client/auth/ram/RamClientAuthServiceImpl.java
- client-basic/src/main/java/com/alibaba/nacos/client/auth/ram/injector/AiResourceInjector.java
- client-basic/src/main/java/com/alibaba/nacos/client/auth/ram/injector/ConfigResourceInjector.java
- maintainer-client/src/main/java/com/alibaba/nacos/maintainer/client/ai/McpMaintainerService.java
- maintainer-client/src/main/java/com/alibaba/nacos/maintainer/client/ai/NacosAiMaintainerServiceImpl.java
- maintainer-client/src/main/java/com/alibaba/nacos/maintainer/client/config/NacosConfigMaintainerServiceImpl.java
- maintainer-client/src/main/java/com/alibaba/nacos/maintainer/client/model/HttpRequest.java
- maintainer-client/src/main/java/com/alibaba/nacos/maintainer/client/naming/NacosNamingMaintainerServiceImpl.java
- maintainer-client/src/main/java/com/alibaba/nacos/maintainer/client/remote/ClientHttpProxy.java
- maintainer-client/src/test/java/com/alibaba/nacos/maintainer/client/remote/ClientHttpProxyTest.java
- plugin/auth/src/main/java/com/alibaba/nacos/plugin/auth/api/RequestResource.java
> [#13445] Maintainer Client support aliyun ram auth plugin.

- console/src/main/java/com/alibaba/nacos/console/handler/impl/remote/ai/McpRemoteHandler.java
- console/src/test/java/com/alibaba/nacos/console/handler/impl/remote/ai/McpRemoteHandlerTest.java
- maintainer-client/src/main/java/com/alibaba/nacos/maintainer/client/ai/McpMaintainerService.java
- maintainer-client/src/main/java/com/alibaba/nacos/maintainer/client/ai/NacosAiMaintainerServiceImpl.java
> [ISSUE #13460] 修复server和console分开启动时，MCP管理存在的一些问题

- core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcRequestAcceptor.java
- core/src/test/java/com/alibaba/nacos/core/remote/grpc/GrpcRequestAcceptorTest.java
(cherry picked from commit bd7a1dd1ecb88c88262ed1af535065d718f0b207)
Fixes #13400 
XX
XXXX
> For #13400, Fix naming subscriber get appName is `-` problem. (#13464)

- README.md
> Update readme qrcode

- naming/src/main/java/com/alibaba/nacos/naming/core/CatalogServiceV2Impl.java
- naming/src/test/java/com/alibaba/nacos/naming/core/CatalogServiceV2ImplTest.java
fix #13449
fix service pagination in `CatalogServiceV2Impl.java` and add test.
fix service pagination in `CatalogServiceV2Impl.java` and add revelant test.
> [ISSUE#13449] Fix service pagination

- config/src/main/java/com/alibaba/nacos/config/server/service/ConfigMigrateService.java
- config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedConfigMigratePersistServiceImpl.java
- config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalConfigMigratePersistServiceImpl.java
Fix #13514 
During horizontal notification configuration migration, an Md5 value was added as a judgment condition, and migration operations are also performed for configurations with the same timestamp.
> [ISSUE #13514] Fix ConfigMigrateService Bug

- maintainer-client/src/main/java/com/alibaba/nacos/maintainer/client/ai/McpMaintainerService.java
add  McpServerDetailInfo getMcpServerDetail(String namespaceId, String mcpName, String version)  in McpMaintainerService, keep same with version 3.0.1.1
XX
XXXX
> Fix mcp McpMaintainerService

- k8s-sync/src/main/java/com/alibaba/nacos/k8s/sync/K8sSyncServer.java
#13498
ApplicationReadyEvent事件之后，启动K8sSyncServer
> [ISSUE #13498] start K8sSyncServer after application startup

- api/src/main/java/com/alibaba/nacos/api/ai/model/mcp/FrontEndpointConfig.java
- api/src/main/java/com/alibaba/nacos/api/ai/model/mcp/McpServerRemoteServiceConfig.java
> [ISSUE: #13527] ADD frontEndpointConfig into McpInfo

- console-ui/src/pages/ConfigurationManagement/ConfigEditor/NewConfigEditor.js
- console/src/main/java/com/alibaba/nacos/console/handler/impl/inner/config/ConfigInnerHandler.java
- console/src/test/java/com/alibaba/nacos/console/handler/impl/inner/config/ConfigInnerHandlerTest.java
Fix the issue [13580](https://github.com/alibaba/nacos/issues/13580).  In the Configuration BETA Edit Page, the format is empty.
Follow the instructions mentioned in [13580](https://github.com/alibaba/nacos/issues/13580)
1. [Backend] query the config_info and pick the `type` field from it and return to the  frontend
2. [UI] type should not support being modified in gray
> [ISSUE #13580] Format is empty in the Configuration BETA Edit Page

- ai/src/main/java/com/alibaba/nacos/ai/remote/handler/ReleaseMcpServerRequestHandler.java
- ai/src/test/java/com/alibaba/nacos/ai/remote/handler/ReleaseMcpServerRequestHandlerTest.java
> [#13524] Auto generate service with version when release new mcp version.

- core/src/main/java/com/alibaba/nacos/core/remote/grpc/BaseGrpcServer.java
- sys/src/main/java/com/alibaba/nacos/sys/env/Constants.java
- sys/src/main/java/com/alibaba/nacos/sys/utils/InetUtils.java
- sys/src/test/java/com/alibaba/nacos/sys/utils/InetUtilsTest.java
Fixes https://github.com/alibaba/nacos/issues/13549
XX
XXXX
> feat: grpc server startup support listen on specified ip

- config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigServletInner.java
Fix namespace conversion bug of 2.x #13614 
XX
XXXX
> [ISSUE #13614] Fix namespace conversion bug of 2.x

- config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigServletInner.java
- config/src/main/java/com/alibaba/nacos/config/server/controller/v3/ConfigOpenApiController.java
Fix namespace conversion bug of 3.x #13614 
XX
XXXX
> [ISSUE #13614] Fix namespace conversion bug

- config/src/main/java/com/alibaba/nacos/config/server/configuration/NacosConfigConfiguration.java
- config/src/main/java/com/alibaba/nacos/config/server/filter/NacosConsolePathTipFilter.java
Fixes https://github.com/alibaba/nacos/issues/13324
XX
XXXX
> feat: deployemnt type merged load nacos console path tip filter

- ai/src/main/java/com/alibaba/nacos/ai/remote/handler/ReleaseMcpServerRequestHandler.java
- ai/src/test/java/com/alibaba/nacos/ai/remote/handler/ReleaseMcpServerRequestHandlerTest.java
- api/src/main/java/com/alibaba/nacos/api/ai/AiService.java
- api/src/main/java/com/alibaba/nacos/api/model/v2/ErrorCode.java
- api/src/test/java/com/alibaba/nacos/api/ai/AiServiceDefaultMethodTest.java
- client/src/main/java/com/alibaba/nacos/client/ai/NacosAiService.java
- client/src/main/java/com/alibaba/nacos/client/ai/cache/NacosMcpServerCacheHolder.java
- client/src/main/java/com/alibaba/nacos/client/ai/event/McpServerChangeNotifier.java
- client/src/main/java/com/alibaba/nacos/client/ai/event/McpServerChangedEvent.java
- client/src/main/java/com/alibaba/nacos/client/ai/remote/AiGrpcClient.java
- client/src/main/java/com/alibaba/nacos/client/ai/utils/McpServerUtils.java
- client/src/test/java/com/alibaba/nacos/client/ai/NacosAiServiceTest.java
- client/src/test/java/com/alibaba/nacos/client/ai/cache/NacosMcpServerCacheHolderTest.java
- client/src/test/java/com/alibaba/nacos/client/ai/event/McpServerChangeNotifierTest.java
- client/src/test/java/com/alibaba/nacos/client/ai/remote/AiGrpcClientTest.java
> [#13524] Some enhance behavior for nacos mcp client.

- console/src/main/java/com/alibaba/nacos/console/controller/v3/ConsoleHealthController.java
- console/src/test/java/com/alibaba/nacos/console/controller/v3/ConsoleHealthControllerTest.java
> [ISSUE #13437] fix: readiness http response code 500 when not health

- ai/src/main/java/com/alibaba/nacos/ai/service/McpServerOperationService.java
- ai/src/main/java/com/alibaba/nacos/ai/service/McpServerSyncEffectService.java
- ai/src/main/java/com/alibaba/nacos/ai/service/SimpleMcpServerSyncEffectService.java
- ai/src/test/java/com/alibaba/nacos/ai/service/McpServerOperationServiceTest.java
- ai/src/test/java/com/alibaba/nacos/ai/service/McpServerSyncEffectServiceTest.java
- ai/src/test/java/com/alibaba/nacos/ai/service/SimpleMcpServerSyncEffectServiceTest.java
> [#13602] Add simple implement for mcp server operation async to sync.

- ai/src/main/java/com/alibaba/nacos/ai/service/McpEndpointOperationService.java
- ai/src/main/java/com/alibaba/nacos/ai/service/McpServerOperationService.java
- ai/src/test/java/com/alibaba/nacos/ai/service/McpEndpointOperationServiceTest.java
- ai/src/test/java/com/alibaba/nacos/ai/service/McpServerOperationServiceTest.java
fix #13678 Create new service when create new version mcp server
XX
XXXX
> [ISSUE #13678] Create new service when create new version mcp server

- console-ui/package-lock.json
- console-ui/package.json
- console-ui/src/pages/AI/McpDetail/CreateTools/index.js
- console-ui/src/pages/AI/McpDetail/ShowTools.js
Nacos MCP console support import tools from OpenApi 3.1
XX
XXXX
> feat: Nacos MCP console support import tools from OpenApi 3.1

- common/src/test/java/com/alibaba/nacos/common/task/engine/NacosDelayTaskExecuteEngineTest.java
- core/src/test/java/com/alibaba/nacos/core/cluster/remote/ClusterRpcClientProxyTest.java
- naming/src/test/java/com/alibaba/nacos/naming/healthcheck/interceptor/HealthCheckTaskInterceptWrapperTest.java
> Try to fix unit test problem.

- console-ui/src/pages/AI/McpDetail/ShowTools.js
Optimize mcp upload Open API file
XX
XXXX
> feat: optimize mcp upload Open API file

- pom.xml
Fixes https://github.com/alibaba/nacos/issues/13454
XX
XXXX
> build: upgrade nacos logback adapter to 1.1.4

- ai/src/main/java/com/alibaba/nacos/ai/constant/Constants.java
- ai/src/main/java/com/alibaba/nacos/ai/controller/AdminA2aController.java
- ai/src/main/java/com/alibaba/nacos/ai/form/a2a/admin/AgentDetailForm.java
- ai/src/main/java/com/alibaba/nacos/ai/form/a2a/admin/AgentForm.java
- ai/src/main/java/com/alibaba/nacos/ai/form/a2a/admin/AgentListForm.java
- ai/src/main/java/com/alibaba/nacos/ai/form/a2a/admin/AgentUpdateForm.java
- ai/src/main/java/com/alibaba/nacos/ai/service/A2aServerOperationService.java
- api/src/main/java/com/alibaba/nacos/api/ai/model/a2a/AgentCapabilities.java
- api/src/main/java/com/alibaba/nacos/api/ai/model/a2a/AgentCard.java
- api/src/main/java/com/alibaba/nacos/api/ai/model/a2a/AgentCardVersionInfo.java
- api/src/main/java/com/alibaba/nacos/api/ai/model/a2a/AgentCardWrapper.java
- api/src/main/java/com/alibaba/nacos/api/ai/model/a2a/AgentExtension.java
- api/src/main/java/com/alibaba/nacos/api/ai/model/a2a/AgentInterface.java
- api/src/main/java/com/alibaba/nacos/api/ai/model/a2a/AgentProvider.java
- api/src/main/java/com/alibaba/nacos/api/ai/model/a2a/AgentSkill.java
- api/src/main/java/com/alibaba/nacos/api/ai/model/a2a/AgentVersionDetail.java
- api/src/main/java/com/alibaba/nacos/api/ai/model/a2a/SecurityScheme.java
- console/src/main/java/com/alibaba/nacos/console/handler/ai/A2aHandler.java
- console/src/main/java/com/alibaba/nacos/console/handler/impl/inner/ai/A2aInnerHandler.java
- console/src/main/java/com/alibaba/nacos/console/handler/impl/remote/NacosMaintainerClientHolder.java
- console/src/main/java/com/alibaba/nacos/console/handler/impl/remote/ai/A2aRemoteHandler.java
- console/src/main/java/com/alibaba/nacos/console/proxy/ai/A2aProxy.java
- maintainer-client/src/main/java/com/alibaba/nacos/maintainer/client/ai/A2aMaintainerFactory.java
- maintainer-client/src/main/java/com/alibaba/nacos/maintainer/client/ai/A2aMaintainerService.java
- maintainer-client/src/main/java/com/alibaba/nacos/maintainer/client/ai/NacosA2aMaintainerServiceImpl.java
- maintainer-client/src/main/java/com/alibaba/nacos/maintainer/client/constants/Constants.java
its for #13322
- Add Aegnt's Admin API.
XXXX
> [ISSUE#13322] Add Admin API that supports Agent registration.

- console-ui/src/pages/AI/McpDetail/ShowTools.js
Optimizing template usage by applying aggressive options for argument passing
XXXXX
XX
XXXX
> Optimizing template usage by applying aggressive options for argument passing

- consistency/pom.xml
Upgrade os-maven-plugin version to 1.7.1 to avoid compilation errors during
XX
XXXX
> Upgrade os-maven-plugin version to 1.7.1
